kiali/kiali

handlers/grafana.go, handlers/grafana_test.go
Example: Configured Grafana URL 'http://grafana:3000?orgId=1' to not screw up link generation
Fixes https://github.com/kiali/kiali/issues/2623
Frontend PR: https://github.com/kiali/kiali-ui/pull/1752
=> Allow pre-set query params in Grafana URL

business/istio_status.go, business/istio_status_test.go, business/layer.go, config/config.go, doc.go, handlers/config.go, handlers/istio_status.go, kubernetes/client.go, kubernetes/kubernetes_service.go, kubernetes/kubetest/mock.go, routing/routes.go, status/versions.go, swagger.json
This PR adds a new endpoint that returns the status of each component of Istio. For each components it returns if it is a core component and whether it is Unhealthy or Not Found.
Unhealthy => The component has missing pods
Not Found => There isn't any deployment in that namespace for that component.
Healthy deployments aren't returned.
**warning**: means that if a component is not found or unhealthy, the UI will show a warning symbol.
**error**: if the component is not found or unhealthy, it will show an error symbol.
monolith (demo profile from > 1.5):
```
"istio-egressgateway":  warning,
"istio-ingressgateway": error,
"istiod":               error,
"grafana":              warning,
"istio-tracing":        warning,
"prometheus":           error,
``` 
mixer-base installation (tipically < …
=> Add Istio Components Status

.travis.yml, README.adoc, make/Makefile.build.mk
This commit adds arm64 support for the kiali operator image and enables the travis job on arm64.
Note: Currently just proposing this as a draft PR for comments :))
**WIP (Checklist):**
Operator related code was moved to [operator #6](https://github.com/kiali/kiali-operator/pull/6).
Signed-off-by: Henry Wang <Henry.Wang@arm.com>
Extended fix of #1091 
No.
If so, please also update README.adoc
Yes, will update the README.adoc in the final version of this patch.
=> Enable kiali travis build on arm64

hack/aws-openshift.sh, hack/istio/install-sm11.sh
Ripping out the obsolete code that installed the old SM stuff from the AWS hack script - that script should only be responsible for installing the AWS cluster (just like how the CRC hack script works).
We will introduce different scripts to install different versions of SM. We currently have install-sm10.sh and this PR will introduce install-sm11.sh to install SM 1.1.
(this is ready to be merged)
=> [hack] script to install SM 1.1

config/config.go
I won't refactor all code, just the mapping into the yaml.
Fixes https://github.com/kiali/kiali/issues/2711
Note, this requires a PR on the operator side (on the way).
=> Fixes Iter8 literal in config to please ansible operator

hack/aws-openshift.sh
OpenShift 4.4 has been released. This updates the hack script to support installing it.
=> [hack] support installing OpenShift 4.4 on AWS

hack/aws-openshift.sh
Looks like OpenShift 4.4 is already up to patch level 3 - have the hack script use it (I tested it, and it does install and start up).
=> [hack] move to OpenShift 4.4.3 in aws hack script

make/Makefile.molecule.mk
This is just for making running molecule tests with different images easier.
This PR goes with: https://github.com/kiali/kiali-operator/pull/25
You can now run the molecule-test target with the env var `MOLECULE_USE_DEV_IMAGES=true` in order to test locally build images (not specifying that will test the "latest" image from quay.io). For example:
```
MOLECULE_USE_DEV_IMAGES=true MOLECULE_SCENARIO=config-values-test make molecule-test
```
=> [operator] be able to specify what images to test via env vars.

deploy/jenkins-ci/Dockerfile, deploy/jenkins-ci/Makefile.operator.jenkins
fixes: https://github.com/kiali/kiali/issues/2674
This goes with https://github.com/kiali/kiali-operator/pull/28
This generates the all-in-one yaml and commits it to the deploy/ directory.
This all-in-one yaml should only be used for those that do not have nor wish to use Operator Lifecycle Manager to install and manage the Kiali operator installation.
=> jenkins generation of all-in-one operator deployment yaml

kubernetes/client.go, kubernetes/istio_details_service.go
This PR has the responsability to allow Kiali to run into Istio 1.5 and Istio 1.6 without triggering alerts because of the consumption of the Policy CRD.
This is preventing me to implement further features based on Istio 1.6.
The behavior is the following:
On Istio 1.5:
On Istio 1.6:
Makes #2727 less ugly. However, I couldn't consider that issue close because this workaround makes the MTLS icons disappear into istio 1.6 (except for the graph).
=> Allow Policy to return an empty array on Istio without Authentication API

.travis.yml
I've found myself many times forgetting to update the swagger files. And many times, I realized right after switching to another context. I propose to validate the swagger files as faster as possible to prevent that context switch. Like we do with the linting.
=> Fail faster: validate swagger first

kubernetes/client.go, kubernetes/istio_details_service.go, kubernetes/istio_rules_service.go
Fixes https://github.com/kiali/kiali/issues/2748
It adds additional check on GetList methods to return empty results on deprecated APIs.
Note, this is a workaround, once Istio 1.6 removes the old deprecated APIs I think we should remove them as well.
No need to make Kiali backward compatible with all versions
=> Protect networking and config .istio.io APIs in backend queries

hack/istio/install-istio-via-istioctl.sh
We still want the hack script to support 1.5. This uses the proper mtls setting for 1.6 but retains the same one used in 1.5.
=> [hack] support 1.6 as well as 1.5 - mtls options changed

config/config.go
this doesn't really address https://github.com/kiali/kiali/issues/2754 but it does need to be incorporated. The default version endpoint should be the one in istiod that was introduced in 1.6.
Note that this default doesn't really come into  play under normal circumstances - the operator will always set it and so do the upstream istio helm chart, so this default isn't used. It will only be used during tests or if you remove the setting from the configmap manually. but it is good to change it since that pilot endpoint is now gone since istio 1.6
=> pilot is gone, default the version endpoint to the new istiod

Makefile, make/Makefile.operator.mk
This just lets devs deploy kiali outside the control plane namespace via the make targets.
This was needed to test https://github.com/kiali/kiali-operator/pull/34
=> be able to deploy kiali outside istio control plane

config/config.go, kubernetes/istio_details_service.go, models/destination_rule.go, models/service_entry.go, models/sidecars.go, models/virtual_service.go, swagger.json
Related to 
kiali/kiali#2750
It updates some changes and missing types in the Istio 1.6 types.
Strong type happens on UI https://github.com/kiali/kiali-ui/pull/1783 mostly to implement yaml edition feature, so in the backend it's more relaxed.
But I'm not sure if there is some missing change needed in validations.
=> Update Istio 1.6 types

status/versions.go, status/versions_test.go
This adds support for detecting when the running istio version is an RC release (i.e.  .beta or .alpha).  For example, without this PR running istio-1.6.0-beta.0 wil be reported as:
Istio: 1.6.0
With the PR it will be reported like:
Relates to https://github.com/kiali/kiali/issues/2754
=> Handle istio alpha/beta release versions

business/namespaces.go, handlers/authentication.go
This is for plain Kubernetes environments, where the Projects API is not available. There was a RBAC limitation where Kiali was requiring read access to all Kiali accessible namespaces in order for users to be able to login.
This tries to circumvent the RBAC limiation by using the Kiali Service Account. Certainly, this is assuming that the Kiali ServiceAccount is present and has the `get namespaces` privilege. We are already assuming the presence of Kiali ServiceAccount with other sets of permissions for the following features:
* Kiali's cache
* Discovery of prometheus
* Discovery of Grafana
* Check what version of Istio's Telemetry is enabled
So, the assumption of the presence of the Kiali ServiceAccount and it's usage may not be too bad. Installation through Kiali Operator is currently …
=> Remove RBAC limitation from the token authentication

business/health.go
It was adding services based on istio metrics in addition to the ones strictly resulting from k8s api
Fixes https://github.com/kiali/kiali/issues/2772
=> Fix overview services health showing inexisting services

business/istio_validations.go, business/istio_validations_test.go, business/tls.go, kubernetes/types.go
I've detected a change from 1.6-beta.0 to beta.1. The Istio config map no longer includes the 'enableAutoMtls' field in the default installation. It means that they defaults to true.
My previous deployment defaulted to false.
This PR includes this default to true when the flag is not present.
=> AutoEnableMTLS by default is true

deploy/docker/Dockerfile-ubi7-minimal, deploy/docker/Dockerfile-ubi8-minimal
To follow container best practices, run Kiali as a regular user by default.
Fixes kiali/kiali#2745
=> Run Kiali as non-root user

status/versions.go, status/versions_test.go
This adds support for detecting when the running istio version is an RC release like x.x.x-rc.x For example, without this PR running istio-1.6.0-rc.0 wil be reported as:
Istio: 1.6.0
With the PR it will be reported like:
Istio RC: 1.6.0 (rc.0)
Relates to #2754
=> Add another RC version-string variety

Makefile, make/Makefile.cluster.mk
So, in case you use `minikube start -p foo` to have several instances, you can still use the Makefiles on any instance by setting MINIKUBE_PROFILE environment variable.
=> Add support for minikube profiles in Makefiles

hack/crc-openshift.sh
If we install everything (istio/kiali/bookinfo) then we need at least 5 CPUs, so make that the default. You can always ask for less (`-ccpus`) if you want.
This PR also outputs the # of  CPUs allocated to the VM in the status.
=> [hack] we want to give CRC 5 CPUs by default since 4 isn't enough

business/istio_validations.go
Previous review removed those two statements from the switch.
I think we should include this into 1.18
Fixes https://github.com/kiali/kiali/issues/2812
=> Allow Policies and MeshPolicies still be displayed into Istio 1.5

business/checkers/destinationrules/disabled_namespacewide_mtls_checker.go, business/checkers/destinationrules/disabled_namespacewide_mtls_checker_test.go
Fixing the following scenario:
- PeerAuthentication disabling mtls for the whole namespace (mode = DISABLE or PERMISSIVE)
- Destination Rule disabling mTLS for a whole namespace (mode = DISABLE)
- Validation appears into DR. It shouldn't.
Before:
After:
=> Disabled Namespace validation: Expects PeerAuthn not to be STRICT

business/checkers/virtual_services/no_gateway_checker.go, business/checkers/virtual_services/no_gateway_checker_test.go, business/checkers/virtual_services/subset_presence_checker.go, business/checkers/virtual_services/subset_presence_checker_test.go, kubernetes/host.go, kubernetes/host_test.go, models/istio_validation.go
Fixes https://github.com/kiali/kiali/issues/2698
It also adds a new validation regarding the nomenclature used for referring a gateway.
The FQDN and PQDN are no longer supported. Istio suggests to use `<namespace>/<gateway name>` format.
Needs a documentation PR: https://github.com/kiali/kiali.io/pull/235
=> Virtual Service: support to partially QDN in gateways

business/tls.go, business/tls_test.go
Fixes https://github.com/kiali/kiali/issues/2819
The status is the following:
|PeerAuthn | DR |  | No AutoMtls | AutoMtls |
|-------------- | ----- | - | --------------- | ---------------- |
| STRICT | empty | | Partially Enabled | Enabled |
| STRICT | ISTIO_MUTUAL | | Enabled | Enabled |
| STRICT | DISABLE | | Partially Enabled | Partially Enabled |
| PERMISSIVE | empty | | Partially Enabled | Partially Enabled |
| PERMISSIVE | ISTIO_MUTUAL | | Partially Enabled | Partially Enabled |
| PERMISSIVE | DISABLE | | Partially Enabled | Partially Enabled |
| DISABLE | empty | | Partially Enabled | Disabled |
| DISABLE | ISTIO_MUTUAL | | Partially Enabled | Partially Enabled |
| DISABLE | DISABLE | | Disabled | Disabled |
The `enabled status` implies a lock into namespace card within the …
=> Strict and permissive modes can enable/disable TLS status at ns-level

deploy/docker/Dockerfile-ubi7-minimal, deploy/docker/Dockerfile-ubi8-minimal
Run microdnf stuff prior to copying Kiali sources to speed up dev builds (uses cache)
---
I noticed that build time is longer than usual, and it's because new build steps were added to install some packages. But they can be cached for dev builds if put prior to copying kiali sources.
*Before change* build was (stops using cache from step 5):
```
STEP 1: FROM registry.access.redhat.com/ubi7-minimal
STEP 2: LABEL maintainer="kiali-dev@googlegroups.com"
--> Using cache c29dec6be71fc9e9874dcdd544d7a8b9a9a61f18738eead82497bd6f66097b02
STEP 3: ENV KIALI_HOME=/opt/kiali     PATH=$KIALI_HOME:$PATH
--> Using cache a52dd6a83921ee3d8b3efd8b95431b4cecc2b20a58f814ed985f5b7b569be2f6
STEP 4: WORKDIR $KIALI_HOME
--> Using cache 36bb6bd62e5414a0815872b099203fd0e817d8045133f97734cc0d657674b18d
STEP 5: COPY …
```
=> Optimize image build steps

business/jaeger.go, handlers/jaeger.go, jaeger/client.go, jaeger/traces.go, jaeger/types.go
Endpoint to fetch a trace by traceID was returning an array, make it returning a single object instead
This simplifies usage on UI.
Required frontend PR: https://github.com/kiali/kiali-ui/pull/1800
=> Endpoint [...]/traces/{traceID} returns single trace

business/tls.go, business/tls_test.go
backport of https://github.com/kiali/kiali/pull/2821
=> v1.18 - backport - Strict and permissive modes can enable/disable TLS status at ns-level

hack/k8s-minikube.sh, make/Makefile.cluster.mk, make/Makefile.operator.mk
1. need to specify insecure registry when starting minikube now
2. default to the most stable release of k8s
3. make should not try to delete templates (k8s doesn't have that type and we don't use templates anymore anyway)
4. make should only try to delete openshift resources when cluster type is openshift
5. xdg-open is deprecated; use gio open now
=> [hack] fix up some things for minikube that are broken

graph/telemetry/istio/appender/dead_node.go, graph/telemetry/istio/appender/dead_node_test.go
The injected service node was not being killed when:
- Service injection on
- Both the source and dest nodes were dead:
- No traffic between the source and dest
- No backing workloads for the source and dest
Fixes: #2783 
Before:
After:
=> Fix dead node corner case

make/Makefile.molecule.mk
Some clusters have hosts that are not resolveable within the molecule docker container so add some smarts to the makefile to try to pass the IPs into the container's host table.
=> molecule make target to add to the container host table

business/jaeger.go, handlers/jaeger.go, jaeger/client.go, jaeger/spans.go, jaeger/traces.go, jaeger/util.go, models/tracing.go, routing/routes.go
Using TracingQuery when kiali is queried, decoupled from jaeger query API.
Share more code between spans.go and traces.go
Fixes https://github.com/kiali/kiali/issues/2732
Frontend PR required: https://github.com/kiali/kiali-ui/pull/1810
=> Separate jaeger queries and kiali tracing queries

handlers/config.go
This is related to #2633 where extensions may need access from backend/frontend to the CanonicalMetrics flag to check if telemetry is based on v1 or v2 metrics.
This requires a frontend PR.
=> Expose Istio Telemetry Version to Public Config

business/checkers/destination_rules_checker.go, business/checkers/destinationrules/disabled_meshwide_mtls_checker.go, business/checkers/destinationrules/disabled_meshwide_mtls_checker_test.go, business/checkers/peer_authentication_checker.go, business/checkers/peerauthentications/disabled_meshwide_checker.go, business/checkers/peerauthentications/disabled_meshwide_checker_test.go, business/checkers/peerauthentications/disabled_namespacewide_checker.go, business/checkers/peerauthentications/disabled_namespacewide_checker_test.go, business/tls.go, kubernetes/istio_details_service.go, kubernetes/types.go, models/istio_validation.go, tests/data/fiture_loader.go, tests/data/fixture_loader_test.go, tests/data/loader/basic.yaml, tests/data/validations/destinationrules/disabled_meshwide_checker_1.yaml, tests/data/validations/destinationrules/disabled_meshwide_checker_2.yaml, tests/data/validations/destinationrules/disabled_meshwide_checker_3.yaml, tests/data/validations/destinationrules/disabled_meshwide_checker_4.yaml, tests/data/validations/peerauthentications/disabled_meshwide_checker_1.yaml, tests/data/validations/peerauthentications/disabled_meshwide_checker_2.yaml, tests/data/validations/peerauthentications/disabled_meshwide_checker_3.yaml, tests/data/validations/peerauthentications/disabled_namespacewide_checker_1.yaml, tests/data/validations/peerauthentications/disabled_namespacewide_checker_2.yaml, tests/data/validations/peerauthentications/disabled_namespacewide_checker_3.yaml, tests/data/validations/peerauthentications/disabled_namespacewide_checker_4.yaml, tests/data/validations/peerauthentications/disabled_namespacewide_checker_5.yaml, tests/data/validations/test_asserter.go
Three validations have been included:
- PeerAuthn: Disabling mTLS at namespace level ([steps to reproduce](https://raw.githubusercontent.com/xeviknal/swscore/kiali-2086-2/tests/data/validations/peerauthentications/disabled_namespacewide_checker_2.yaml)) (both autoMtls enabled/disabled)
- PeerAuthn: Disabling mTLS at mesh-level ([steps to reproduce](https://raw.githubusercontent.com/xeviknal/swscore/kiali-2086-2/tests/data/validations/peerauthentications/disabled_meshwide_checker_2.yaml)) (both autoMtls enabled/disabled)
- DestinationRule: Disabling mTLS at mesh-level ([steps to reproduce](https://raw.githubusercontent.com/xeviknal/swscore/kiali-2086-2/tests/data/validations/destinationrules/disabled_meshwide_checker_2.yaml)) (both autoMtls enabled/disabled)
Introduced a mechanism for …
=> PeerAuthn validations for disabling scenarios

server/server.go, server/server_test.go
fixes #https://github.com/kiali/kiali/issues/2770
backport of https://github.com/kiali/kiali/pull/2782
=> 2770 server should not allow TLS 1.1 or lower (#2782)

Makefile
As part of kiali/kiali#2862, stop using "login" strategy in the
Makefiles.
=> Don't use "login" strategy in when deploying in Makefiles

make/Makefile.operator.mk
Now you can just do `make operator-delete` and you will avoid the finalizer hanging problem.
If you want a fast way to purge it, you can still do `make kiali-purge` as always.
=> [make] the delete make target should attempt to clean up kiali CR first, then purge.

business/iter8.go, handlers/iter8.go, kubernetes/iter8.go, kubernetes/kubetest/mock_iter8.go, models/iter8.go, swagger.json
1. Auto Generate Routing References
2. Change the Kiali-specific CRD facade based on changes for 0.1.1 releases
3. Additional control endpoints - Pause/Resume and Rollforward, Rollback
This issue is created to replace the original Kiali PR 2815 
Refer - [Kiali PR# 2815](https://github.com/kiali/kiali/pull/2815)
[Main issue #2007](https://github.com/kiali/kiali/issues/2007)
and 
[Issue #2633](https://github.com/kiali/kiali/issues/2633)
** Changes **
Introduce a new Iter8 Endpoint for update experiment with action.
Change the Iter8 Experiment CRD -- add new field "action"
** UI Changes **
The new action will require changes in the Kiali-UI 
** Changes based on comment in previous PR  2815
1. Fix business/iter8 "CreateIter8Experiment -> …
=> Iter8 v0.1.1 Integration for Kiali

util/httputil/http_util.go, util/httputil/http_util_test.go
We met this problem when we connect kiali web from the service(the service ip is accessible out of k8s cluster). 
We use openid auth strategy. 
As the kiali service port is 80, we connect kiali by `http://1.1.1.1`, then the browser will redirect to openid login page; After the user login, the browser will redirect to `http://1.1.1.1:20001`, which should be `http://1.1.1.1`.
We check the func `GuessKialiURL` and find this maybe a bug. 
If the http request uses default port(80, 443) both in url and in host header, the func `GuessKialiURL` will use `cfg.Server.WebFQDN`, which maybe 20001.
So we add a step to check if it is a default port, if so, use default port instead.
Look forward to your response :)
NA
* Please, provide the link to the …
=> fix guess url for default port 

make/Makefile.molecule.mk
We can't pass this option if there is no TERM env var (i.e. when run in a cronjob) because that causes a failure.
=> pass in -t so we get color text output from ansible which makes the logs easier to read

go.mod, go.sum
Bump k-charted 0.6.0-rc5 => 0.6.0 (no change, just use released final version)
DNM until @israel-hdez 's go module PR is emrged (based on it) ; and master-rebased then
=> Bump k-charted 0.6.0 final (no change)

make/Makefile.operator.mk
fixes https://github.com/kiali/kiali/issues/2975
=> oauthclient is a cluster scoped resource - no need to pass -n when deleting

deploy/jenkins-ci/Makefile.site.jenkins
When the release script runs, it does not add the symlink to `latest` that we need to point the released version. This PR fixes it by adding everything that the script has changed.
=> Add all changes when releasing documentation

Makefile, make/Makefile.operator.mk
part of https://github.com/kiali/kiali/issues/2889
Dependent resource watching only works for those resources in watched namespaces - so deploy the operator with a default watch namespace of empty string ("") -- i.e. all namespaces.
=> operator should watch all namespaces by default

go.mod, go.sum
https://issues.redhat.com/browse/MAISTRA-1636
Marking as backport to 1.12 but note that this can not be cherry-picked because master is using go modules and 1.12 is using glide for dep handling.  The 1.12 fix will need to be manual.
=> CVE-2020-14040

graph/api/api_test.go, graph/api/testdata/test_complex_graph.expected, graph/telemetry/istio/appender/aggregate_node.go, graph/telemetry/istio/appender/response_time.go, graph/telemetry/istio/istio.go, graph/telemetry/istio/util/util.go
Egress destination telemetry is lacking and may not be easily fixed on the isti side.  This adds some special case code to help things out for the Kiali graph.
Note that the bad telem is still in Prometheus, so direct metric query won't match up completely unless we want to patch that as well.  That could be a follow up, if needed. 
Closes https://github.com/kiali/kiali/issues/2999
=> Better handle egress destination telemetry

handlers/authentication.go
Part of #2954.
Edgar asked to create a follow-up pr on [his review of the expiration date PR](https://github.com/kiali/kiali/pull/2981#discussion_r456535422) to use the expiration value on the config instead of hardcoding our own on the code.
=> Use config instead of hardcoded default for token expiration

graph/api/api_test.go, graph/api/testdata/test_complex_graph.expected, graph/telemetry/istio/appender/response_time.go, graph/telemetry/istio/istio.go, graph/telemetry/istio/util/util.go
UI PR: https://github.com/kiali/kiali-ui/pull/1858
Istio Egress destination telemetry is lacking and may not be easily fixed on their side. So, add some special case code to help things out for the Kiali graph.  Note that the bad telem is still in Prometheus, so direct metric query won't match up completely unless we want to patch that as well.
https://github.com/kiali/kiali/issues/2999
=> [v1.18 backport] Better handle egress destination telemetry (#3004)

status/versions.go, status/versions_test.go
https://github.com/kiali/kiali/issues/3032
The current 1.7 alpha release did not properly parse the version:
Version 1.7.0-alpha.1-cd46a166947eac363380c3aa3523b26a8c391f98-dirty-Modified
Old:
`Istio Dev:   7.0 (Dev 1)`
New:
`Istio RC:    1.7.0 (alpha.1)`
=> Fix version matching for alpha release

hack/istio/install-istio-via-istioctl.sh
We need the hack script to install the addons now that istio 1.7 does not include them anymore.
=> [hack] install addons since istioctl doesn't do it anymore

business/checkers/authorization/mtls_enabled_checker.go, business/istio_status.go, business/istio_status_test.go, config/config.go, handlers/config.go, handlers/metrics.go, kubernetes/cache/istio.go, kubernetes/kubernetes.go
This comes after the following issues found:
- https://github.com/kiali/kiali/issues/2916 : Support add-ons installed in different namespaces
- https://github.com/kiali/kiali/issues/3027 : Istio 1.7 changed tracing deployment name
The result is a more flexible solution for the istio components namespace. it removes hardcoded components, istio architectures (mixer or monolith) and allows users to change the severity of each component (error or warning). 
The defaults for this PR supports both 1.7 and 1.6 versions.
Needs operator changes: https://github.com/kiali/kiali-operator/pull/98
Testing comments:
This PR needs to be tested in both 1.7 and 1.6 upstream istio version. Defaults values should work with both versions.
fixes https://github.com/kiali/kiali/issues/2916
fixes …
=> Istio Components Status: addons in different ns, modify name and severity each component

business/checkers/authorization/mtls_enabled_checker.go, business/checkers/authorization/no_host_checker.go, business/checkers/authorization/no_host_checker_test.go, business/checkers/authorization_policies_checker.go, business/istio_validations.go, handlers/metrics.go, kubernetes/cache/istio.go, kubernetes/host.go, kubernetes/host_test.go, kubernetes/kubernetes.go
Fixes https://github.com/kiali/kiali/issues/3001
AuthorizationPolicies might apply to specific request matching the target host. This host might not only be internal services or service entries in the mesh but all the possible hosts that the cluster allow to get in (through gateways and virtual services).
This PR removes the false positive of the following scenario where the AuthzPolicy is applied to a host declared in a Virtual Service.
Therefore, this PR includes VirtualService's hosts in the host checking process.
ServiceEntry
```
---
kind: ServiceEntry
metadata:
name: foo-dev
spec:
endpoints:
- address: 10.15.1.121
exportTo:
- "."
hosts:
- foo-dev.istio-system.svc.cluster.local
location: MESH_EXTERNAL
ports:
- name: http …
```
=> Support VirtualServices hosts in Authz Policies

business/openshift_oauth.go, config/config.go
Do not assume the Route name is `kiali` and the OAuthClient name is prefixed with `kiali`. Let it be configurable by the installer.
Default is "kiali" (which is the prefix today's installers use) - so even if an older installer installs kiali (and thus "client_id_prefix" is missing from the ConfigMap), the openshift auth strategy will still work.
Do not merge this PR unless [the kiali server helm chart PR](https://github.com/kiali/kiali-operator/pull/105) is merged.
part of fix for: https://github.com/kiali/kiali/issues/3069
=> make client id prefix configurable

business/iter8.go, config/config.go, handlers/config.go, kubernetes/iter8.go, models/iter8.go, status/versions.go, swagger.json
1. Add Host section in CR
2. Remove RoutingPreference in the CR ( Iter8 v0.1)
3. Enforce Supporting level. (Iter8 v0.2)
*** Refer to Issue
#2007 
With this changes, we only support Iter8 v0.2 and above.
Old version of Kiali-UI will work with these changes, but will not be able to take advantage of new feature introduced in V0.2
*** Note ***
=> Supporting Iter8-v0.2

business/dashboards.go, config/config.go, go.mod, go.sum
- New NamespaceLabel field
- Prometheus' Auth now decoupled from main prometheus config
- Reorganized config for custom metrics
Part of #3055
Requires k-charted PR: https://github.com/kiali/k-charted/pull/106
Requires operator PR: https://github.com/kiali/kiali-operator/pull/100
=> Add more custom dashboards configurations

deploy/jenkins-ci/Makefile.operator.jenkins
Users can generate it via helm now.
operator PR that goes with this: https://github.com/kiali/kiali-operator/pull/108
fixes: https://github.com/kiali/kiali/issues/3075
=> Remove Jenkins generation of the all-in-one yaml

business/checkers/common/multi_match_selector_checker.go, business/checkers/common/multi_match_selector_checker_test.go, business/checkers/common/workload_selector_checker.go, business/checkers/common/workload_selector_checker_test.go, business/checkers/request_authentication_checker.go, business/istio_validations.go, business/istio_validations_test.go, kubernetes/iter8.go, kubernetes/types.go, models/istio_validation.go
Add basic support to RequestAuthentication objects:
- Multiple ns-wide objects found
- Two objects pointing to the same workload
- Workload not found
Testing scenarios: https://github.com/xeviknal/istio-lab/blob/master/2543.yaml
Fixes https://github.com/kiali/kiali/issues/2543
=> Add workload validation support to RequestAuthentication

business/checkers/virtual_services/single_host_checker.go, business/checkers/virtual_services/single_host_checker_test.go, business/checkers/virtual_services/subset_presence_checker.go
Fixes: https://github.com/kiali/kiali/issues/1471
This is a validation on Virtual Services. It appears now when both Virtual Services shares the same gateway and same host. In case, the VS doesn't have Gateway, it is compared among other VS without Gateways.
Another scenario has been covered:
1. 2 Destination Rules pointing to the same host. Each DR defines one subset.
2. 1 Virtual Service pointing to one subset.
3. VS has a `no subset found` validation. (the checker only considered one DR pointing to same host).
(user-gateway/admin-gateway should not be presented with this validation)
Testing scenario: https://github.com/xeviknal/istio-lab/blob/master/1471/issue.yaml
Testing scenario with duplicates: https://github.com/xeviknal/istio-lab/blob/master/1471/issue-dups.yaml
Before:
After:
=> Validations: More than one Virtual Service for same host considers gateways

deploy/jenkins-ci/Jenkinsfile
Actually, this change is to allow Helm charts builds only when doing
minor and patch releases.
=> Block Helm charts builds on snapshots

.travis.yml, Makefile, deploy/jenkins-ci/Dockerfile
Because of a CVE in golang: https://groups.google.com/g/golang-announce/c/NyPIaucMgXo/m/GdsyQP6QAAAJ?pli=1
=> Bump go to version 1.14.7

README.adoc, go.sum, kubernetes/client.go, kubernetes/secret.go, kubernetes/token.go
This is an experimental change that allows Kiali to fetch resources from a remote API server. Check the ticket for more details
A few comments:
- I used `CAData` instead of `CAFile` with the TLSClientConfig. Sadly `certutil.NewPool()` only takes a file, so the CA file is not validated. Using `CAFile` would require me to write the CA file to the HOME directory
- There will have to be a Kiali Operator change later on to include only what the individual clusters need. So only include the ClusterRole, ClusterRoleBinding, and ServiceAccount for the Data Plane. Exclude them for the Control Plane and add the volume to the Deployment
- Istio uses `kubeclientset.CoreV1().Secrets(namespace)` to get the remote secrets from the local api server. That'll probably be required for the multi-cluster …
=> Use remote cluster's api server

routing/router.go, routing/router_test.go
Closes #3103.
In some configurations, if a custom webroot is set and the IDP redirects
the user without the trailing slash on the URL, we redirect the user to
add the trailing slash, which makes:
1. We lose hash params as they are not sent to the server.
2. We lose query params because we are not passing them forward.
This commit fixes both, as well as adding a little bit more testing to
the routing code.
=> Fix WebRoot redirects for OIDC

business/apps.go, business/health.go, business/istio_config.go, business/istio_status.go, business/istio_validations.go, business/istio_validations_test.go, business/iter8.go, business/layer.go, business/services.go, business/tls.go, business/workloads.go, config/config.go, kubernetes/cache/cache.go, kubernetes/cache/istio.go, kubernetes/cache/kubernetes.go, kubernetes/client.go, kubernetes/istio.go, kubernetes/kubetest/mock_istio.go, kubernetes/types.go
Fixes https://github.com/kiali/kiali/issues/3147
Added to the cache:
- StatefulSets
- ConfigMaps
- Istio: Sidecar, PeerAuthentication, RequestAuthentication, AuthorizationPolicy
All of them used for common operations of tls, istio status and validations.
Refactor some logic placed on kubernetes package that makes sense to use it in the business package.
It requires a followup to update operator defaults.
@hhovsepy main testing of this PR is to validate there is no regression or any obvious perf penalty.
Otherwise it should be transparent from feature perspective.
=> Update Cache with potential perf scenarios

business/layer.go, config/config.go, kubernetes/client.go, kubernetes/client_factory.go, kubernetes/secret.go, models/workload.go
Since some cloud providers won't support configuring OpenID integration in the managed Kubernetes, users may want to use workarounds. One of them is to place a proxy in front of the Kubernetes API handing the OpenID auth (an example is kube-oidc-proxy).
This is adding support for such API proxies.
Fixes kiali/kiali#3042
=> Add support for cluster API proxies on OpenId strategy

hack/purge-kiali-from-cluster.sh
This is needed if you want to purge everything Kiali-related from your cluster and you aren't sure what resources may or may not be around. Useful if you hit installation errors or molecule test errors and you just want to start over from scratch.
If you pass `--dry-run true` to the script, it won't actually delete anything, but you will see in the output what kiali resources are in your cluster.
=> [hack] a hack script that will attempt to purge everything Kiali-related from the cluster

jaeger/traces.go, jaeger/traces_test.go
This works in general for non-envoy spans.
Related frontend PR: https://github.com/kiali/kiali-ui/pull/1914
=> Traces workload matching, use "hostname" as well

kubernetes/types.go, models/attribute_manifest.go, models/authorization_policy.go, models/cluster_rbac_config.go, models/destination_rule.go, models/envoy_filter.go, models/gateway.go, models/http_api_spec.go, models/http_api_spec_binding.go, models/istio_base.go, models/istio_rule.go, models/mesh_policy.go, models/peer_authentication.go, models/policy.go, models/quota_spec.go, models/quota_spec_binding.go, models/rbac_config.go, models/request_authentication.go, models/service_entry.go, models/service_role.go, models/service_role_binding.go, models/sidecars.go, models/virtual_service.go, models/workload_entry.go, swagger.json
Fixes https://github.com/kiali/kiali/issues/2236
Requires: https://github.com/kiali/kiali-ui/pull/1915
This feature needs to be tested in two different installations: with and without status enabled.
In order to enable the status field, please run the following:
```
istioctl install --set values.pilot.env.PILOT_ENABLE_STATUS=true --set values.global.istiod.enableAnalysis=true
```
This is an example of a Istio Analyzer message:
```
kubectl apply -f - <<EOF 
kind: VirtualService
metadata:
name: httpbin-bogus
spec:
hosts:
- "*"
gateways:
- httpbin-gateway-bogus # Expected validation
http:
- route:
- destination:
host: reviews.default.svc.cluster.local
subset: v1
EOF
```
=> Adding Status field into Istio Objects

business/jaeger.go, handlers/jaeger.go, jaeger/traces.go, jaeger/util.go
... because they are fetched for apps, and narrowed-down later. Re-apply initial limit after post-filtering.
This should attenuate the effect of having an inconsistent number of traces displayed for workloads and services (though not entirely eliminating that possibility)
Plus properly recognize "trace not found" error as a 404 instead of 503 / unmarshalling issue
Part of https://github.com/kiali/kiali/issues/3048
=> Increase limit while fetching traces for workloads and services

business/istio_validations.go, business/tls.go, config/config.go, handlers/config.go, kubernetes/istio.go, kubernetes/istio_test.go
Fixes https://github.com/kiali/kiali/issues/3187
Requires: https://github.com/kiali/kiali-operator/pull/126
When istio is installed using the canary upgrade feature [1], Kiali have errors in service details page. This is the following error:
In order to indicate the installation revision, there is now available the following setting:
```yaml
istio:
revision: canary
```
In case istio is installed without revision, then this revision setting should be `""` (or left it empty).
[1] https://istio.io/latest/docs/setup/upgrade/
=> Add revision field into config + use it to fetch istio configmap

business/openid_auth.go, handlers/authentication.go, routing/router.go
This initial implementation of the "authorization code" flow for OpenID authentication let's Kiali negotiate authentication with an extenal IdP provider as described in [section 3.1 of the OpenID spec](https://openid.net/specs/openid-connect-core-1_0.html#CodeFlowAuth). Kiali is acting as an "unauthenticated client" (i.e. no client secret is used).
This is using AES-GCM encryption to encode the cookie which prevents revealing the OpenId id_token to the network and to the browser.
Related to #3088
=> Initial implementation of OpenId's auth code flow

config/config.go
Change degraded values in configuration health
/api/config output
```json
{
"namespace": ".*",
"kind": ".*",
"name": ".*",
"tolerance": [
{
"code": "^5\\d\\d$",
"degraded": 0,
"failure": 10,
"protocol": "http",
"direction": ".*"
},
{
"code": "^4\\d\\d$",
"degraded": 10,
"failure": 20,
"protocol": "http",
"direction": ".*"
},
{
"code": "^[1-9]$|^1[0-6]$",
"degraded": 0,
"failure": 10,
"protocol": "grpc",
"direction": ".*"
}
]
}
```
=> Change degraded from 0.1 to 0

business/istio_validations.go, business/tls.go, config/config.go, handlers/config.go, kubernetes/istio.go, kubernetes/istio_test.go
Rename revision by config map name setting.
Reduce kiali code and remove the hardcoded istio config-map also.
related to https://github.com/kiali/kiali-operator/pull/127
=> Add ConfigMapName setting to kiali CR

business/istio_status.go, business/istio_status_test.go, config/config.go
Fixes https://github.com/kiali/kiali/issues/3201
Requires https://github.com/kiali/kiali-operator/pull/128
Due to the removal of `istio_component_namespaces` from the settings, the istio component health feature needs other ways to let users specify where are their components located in.
This PR adds a new namespace field in each `component_status` object. In case, the namespace is empty, it defaults to the `istioNamespace` setting (typically `istio-system`). This way, users might specify the components of tracing, grafana, prometheus and the istio components (ingress, egress and istiod).
=> Allow users to specify namespace for each Istio health component

config/config.go, graph/api/api_test.go, graph/api/testdata/test_complex_graph.expected, graph/protocol.go, graph/telemetry/common.go, graph/telemetry/istio/appender/response_time.go, graph/telemetry/istio/util/util.go, models/health.go, prometheus/client.go, prometheus/metrics.go, prometheus/prometheustest/client_test.go
Fixes #3194 
Requests that have no response must also be treated as errors because the request never completes, and a response is never sent.  Error handling up to this point assumed a valid response code for the request protocol. But when there is no response Istio sets the response_code=0 to indicate the inability to set a proper code.  Kiali needs to treat the "no response" case as an error.
- For the graph generation and appenders add support for the new case.
- For health enhance the defaults with a new error rate config and update rate eggregation
- For metrics capture the no response case in the errors queries
Also:
- fix issue by making service nodes with unknown namespace inaccessible.
**Requires UI PR: https://github.com/kiali/kiali-ui/pull/1925**
For Testing:
One way to force …
=> Add Support for requests with no response

go.mod, go.sum
Note, there's actually no code change here, it's only on the frontend, but this PR is to keep version consistent with kiali-ui
=> Bump k-charted 0.6.2

business/openid_auth.go, config/config.go, handlers/authentication.go
When OIDC client should authenticate, we need the client-secret provided/configured by/in the OIDC server. For this, we re-use our old/reserved "kiali" secret that was used in the past for the already removed login authentication strategy avoiding another set of changes in the operator.
This also:
* Fixes logout for the auth code flow
* Fixes broken OIDC "implicit flow" (nonce cookie deleted early)
* Deduplicates code doing a small rework of the `performOpenIdAuthentication` function in the authenticatin.go file
Related #3088
=> Support for acting as authenticated OIDC client (authorization code flow)

deploy/docker/Dockerfile-ubi7-minimal, deploy/docker/Dockerfile-ubi8-minimal
If someone wants to use a PodSecurityPolicies with runAsNonRootUser (even though Kiali already does this), Kiali Dockerfile needs to be set with a numeric USER. See https://kubernetes.io/docs/concepts/policy/pod-security-policy/#users-and-groups where it says, `MustRunAsNonRoot - Requires that the pod be submitted with a non-zero runAsUser or have the USER directive defined (using a numeric UID) in the image`.
https://github.com/kiali/kiali/issues/3224
Yes. This PR simply uses the same UID as what was used before (1000) except now the Dockerfile is explicit about it (rather than use the uesr name "kiali").
=> 3224 - define USER as numeric uid in dockerfile

business/jaeger.go
It means that the workload which we're looking at, probably doesn't produce any more spans
(Also it was crashing with out-of-bound error)
Fixes https://github.com/kiali/kiali/issues/3233
=> Do not refine spans query when no spans were found

business/jaeger.go
It means that the workload which we're looking at, probably doesn't produce any more spans
(Also it was crashing with out-of-bound error)
Fixes https://github.com/kiali/kiali/issues/3233
=> [1.24] Do not refine spans query when no spans were found

business/test_util.go, business/workloads.go, business/workloads_test.go
Closes #3264.
This PR adds some support to parsing log messages from the workload, so we can apply some better filtering (as an example, kubernetes pod logs api supports a start time, but not an end time).
Some implementation details:
- Timestamp support uses ISO8601 instead of RFC3339 (which is go default), because no other stack seems to be using it from what I've seen.
- I could not find a good ISO8601 (or RFC3339 for that matter) regexp that could cover all our cases, because go does not support Perl-like lookarounds, like many mature regexp engines around.
For log severity, I'm currently supporting only named ones (INFO, WARN, ERROR). Log formats are really, really unreliable.
=> Support parsed log messages for the workload logs

models/virtual_service.go
Fixes https://github.com/kiali/kiali/issues/3271
Virtual Service matching for services was limited to 'http' and 'tcp' protocols, this PR adds 'tls'.  This is purely for visualization, the badging applied in the graph should now show VS badges for relevant service nodes.
To test, apply the following virtual service to bookinfo:
```
cat <<VSD | kubectl -n bookinfo create -f -
kind: VirtualService
metadata:
name: badge-test
spec:
hosts: 
- badge-test.test.com
tls:
- match:
- port: 8443
sniHosts:
- badge-test.test.com
route:
- destination:
host: details
port: 
number: 8443
subset: v1
weight: 100
VSD
```
Note that this just a bogus VS, the PR is only related to detecting the VS for badging purposes.  Without the PR the details …
=> Add 'tls' Spec to virtual service matching.

handlers/authentication.go
The missing path directive for OpenShift authentication is creating a cookie targeting https://{fqdn}/{webroot}/api (notice the "api" sub-path).
When logging out, cookies are cleared using the Kiali root path (i.e. https://{fqdn}/{webroot}). This causes a mismatch in the browser and the session cookie is not cleared for OpenShift strategy. As a consequence, Kiali ends in a bad state where it's not possible to login again (workaround is to manually clear browser cookies).
This fixes the creation of the session cookie for OpenShift by specifying the root path. Also, when deleting the session cookie, in addition to setting an expiry time in the past, the MaxAge attribute is also passed with negative value.
Fixes kiali/kiali#3313
=> Fix the path of the cookie for OpenShift authentication strategy

config/config.go, prometheus/cache.go, prometheus/client.go
Fixes https://github.com/kiali/kiali/issues/3315 
Analyzing the queries involved in a graph + healh generation we can see a pattern like this [1].
There are a level of repetitive queries when involved multiple namespaces and health.
This PR introduces caching on the prometheus/client.go API, similar as used for namespaces and proxy-status in the kubernetes/cache/cache.go.
As a first result, with a short term expiration of 10 seconds (used by default) it gets a hit ratio of ~76%.
It approaches only the `Get*` API used mainly for Health.
Also, it's configurable (enabled/disabled and duration).
In terms of design I think it's better to keep separated the three major domains: kubernetes, prometheus and jaeger, as each APIs may have their own particularities. I was tempted to propose a single …
=> Short term expiration cache for Health Prom queries

business/test_util.go, business/workloads.go, business/workloads_test.go, doc.go, handlers/workloads.go, swagger.json
Closes #3303.
This adds support to a new `duration` param to the logs endpoint. It supports the usual duration format we use everywhere else (`1m`, `1h` and so on).
It has less priority than tail lines filtering, so their behaviours should not clash.
=> Implement duration filtering for logs

business/dashboards.go, business/dashboards_test.go, graph/telemetry/istio/appender/response_time.go, graph/telemetry/istio/appender/response_time_test.go, prometheus/metrics_definitions.go, prometheus/prometheustest/client_test.go, tests/e2e/tests/test_kiali_application_endpoint.py, tests/e2e/tests/test_kiali_service_endpoint.py, tests/e2e/tests/test_kiali_workload_endpoint.py
- remove telem-v1 request_duration_seconds metric, v2 supports only request_duration_milliseconds
closes https://github.com/kiali/kiali/issues/3338
=> Remove mixer/telemetry-v1 use of request_duration_seconds

business/workloads.go, business/workloads_test.go
- leave support only for log entries
- be more careful about sending empty log messages
part of https://github.com/kiali/kiali/issues/3067
=> workload logs: remove support for logs blob

business/jaeger.go, business/jaeger_test.go, jaeger/util.go
Fix no trace displayed for istio ingress service
For Service traces, a post-filtering based on operation names was performed.
It's generally ok, except some special situations like when trace comes from ingress (or when trace isn't generated from envoy)
Now we're by-passing this post-filtering in the case where the service name matches the app name.
=> [v1.24] Fix no trace displayed for istio ingress service

business/jaeger.go, business/jaeger_test.go, jaeger/util.go
Cherry-picking https://github.com/kiali/kiali/pull/3364 from v1.24
Fix no trace displayed for istio ingress service
For Service traces, a post-filtering based on operation names was performed.
It's generally ok, except some special situations like when trace comes from ingress (or when trace isn't generated from envoy)
Now we're by-passing this post-filtering in the case where the service name matches the app name.
=> Fix no trace displayed for istio ingress service

go.mod, go.sum
Note: this doesn't fix anything on the backend, but just to keep version on page with the frontend
cf https://github.com/kiali/kiali-ui/pull/1988
=> Bump k-charted 0.6.3

business/openid_auth.go, config/config.go, go.mod, go.sum, handlers/authentication.go
Add support for using OpenId providers to login into Kiali even if the Kubernetes cluster has no OIDC integration. This is done by turning off RBAC and using the Kiali ServiceAccount token regardless of the logged in user.
Most of the code is related to adding several checks on the OpenId token. On the "integrated" scenario, these checks were delegated to the Kubernetes cluster. But on the "non-integrated" scenario (which this PR is adding support for) we are no longer passing the openid token to Kubernetes (because we are using the Kiali ServiceAccount token). Thus, without these checks, the token would not be fully validated.
This is adding two new dependencies:
* golang.org/x/sync v0.0.0-20190911185100-cd5d95a43a6e -- used for multi-thread synchronization when fetching "common" data …
=> [OpenId] Support for clusters without OIDC integration (no RBAC will be possible)

business/workloads.go, handlers/workloads.go
This is a followup to #3331, using criterias to generate the options so we don't have to access the underlying types directly, and thus avoiding the `business` package to conflict with the `business` variable we use for the business layer.
=> Workload Logs: Avoid business package name shadowing by using criterias

tests/e2e/tests/test_api_methods.py
IstioConfigDetails test method deprecated because unavailable of parameters according to Swagger file. This test case is based on IstioConfigDetails test case
=> E2E:Update test_negative_403

business/openshift_oauth.go
As pointed out by @jotak , the go http client does not have a timeout by default, which can cause a hang in API calls.  Apply a timeout when interacting with the OpenAuth API.  Also, don't leave behind any keep-alive sessions.
In testing under load we did see the timeout trigger and the issue seems to be resolved with these changes.  This fix seemed to resurface a lingering issue, #3313, which we were hopefully able to finally squash.  So that UI PR is being required here.
UI PR: https://github.com/kiali/kiali-ui/pull/1994
Fixes #2905
=> Add timeout and client close

README.adoc
The URL of the diagram contains an extra : that effectively breaks the URL. Removing the : fixed it.
=> Remove : from URL link

make/Makefile.build.mk
this should have been part of https://github.com/kiali/kiali/issues/2893
-v no longer valid - set LOG_LEVEL env var.
=> use LOG_LEVEL in make run target since -v is invalid now

business/checkers/gateway_checker.go, business/checkers/gateways/selector_checker.go, business/checkers/gateways/selector_checker_test.go, business/istio_validations.go
Fixes https://github.com/kiali/kiali/issues/3265#
Goal: include istio-system workloads to the look up for workloads in the gateways selector checker.
I have several thoughts regarding this change:
1. It breaks the cross-namespace validation rule. Security-wise, bad-intended users without access to istio-system could gain information about workloads in the istio-system that match that specific selector. Is it that bad?
2. I think it might be different kinds of deployments where the ingress/egress are going to be in different namespaces than the control plane. Therefore, the validation will keep failing.
3. Because of the previous thoughts, I am wondering if we should remove the warning at all. 
Thoughts?
=> Include ControlPlane workloads to KIA0302 no matching workload

business/istio_status.go, business/istio_status_test.go, config/config.go, kubernetes/kubetest/mock.go, log/log_test.go
Fixes https://github.com/kiali/kiali/issues/3353
requires https://github.com/kiali/kiali-ui/pull/1999
requires https://github.com/kiali/kiali-operator/pull/195
Instead of computing the health of these addons (jaeger, prom, grafana) using their deployment components, this PRs aims to use their service urls (defined in the config) to see if they are reachable or not.
- Grafana/tracing: using the internal_url
- prometheus: the url.
In case there is a problem fetching these endpoints, the status will be `unreachable`.
There is still one flag in the config for grafana/tracing for users to tune in the behavior:
- `external_services.tracing.core_component = [true | false]`
- `external_services.grafana.core_component = [true | false]`
When the mentioned flags above are set to true:
With default …
=> Prom, Jaeger, Grafana component status computed using their service url

make/Makefile.operator.mk
When the makefile create a Kiali deployment (which is done outside of Maistra/OLM), the Maistra NetworkPolicy forbids access to that Kiali deployment. So we need to create our own NetworkPolicy to enable access to our dev deployments.
fixes: https://github.com/kiali/kiali/issues/3433
=> need to create NetworkPolicy when deploying dev builds inside a Maistra environment

business/metrics.go
This may happen when there's no metrics at all for the target workload (eg. when workload is in CrashLoopBackoff state)
=> (trivial) Initialize stats array for non-null json

business/istio_status_test.go
fixes https://github.com/kiali/kiali/issues/3453
Adding a mutex to prevent a race condition when accessing to same counter at the same time.
=> Add mutex to prevent test-race in Istio Status test scenario

Makefile, deploy/docker/Dockerfile-multi-arch, make/Makefile.build.mk, make/Makefile.container.mk
_Please describe what the code change is about_
* Merge `Dockerfile-ubi{7|8}-minimal` to single `Dockerfile` (and make it support `docker build` & `docker buildx build` both)
* added `DORP=dockerx` to build mulit-arch image by [buildx](https://docs.docker.com/buildx/working-with-buildx/)
```bash
TARGET_ARCH="amd64 arm64 ppc64le" DORP=dockerx make build-linux container-build-kiali container-push-kiali-quay
```
example: https://hub.docker.com/r/morlay/kiali/tags
#1091
=> Add multi-arch image builds supports

business/istio_validations.go, business/services.go, kubernetes/cache/kubernetes.go, kubernetes/types.go
Fixes https://github.com/kiali/kiali/issues/3467
In some cases, fetching the kubernetes service bypassed the kiali cache.
This was unnoticed until we reviewed this WIP work https://github.com/kiali/kiali/pull/3362 that may need to fetch the service info more frequently so, it should use the caching mechanism.
Also adding an informer for Endpoints for consistency.
For QE: just validate that there are no regressions when deploying with operator.
=> Add Service details into kialiCache

make/Makefile.operator.mk
1. need to install operator-sdk.util via ansible-galaxy because the ansible tasks now use that library
2. also turn on profiler when appropriate
=> get the run-operator-playbook target to run all the way through and with profiler

Makefile, make/Makefile.helm.mk
Be able to turn off the git pull of the helm-chart repo (via `HELM_CHARTS_REPO_PULL=false`)
If the git pull is turned on (which is the default) but it fails, a better error message is output to the user.
fixes https://github.com/kiali/kiali/issues/3500
There are three scenarios:
1) You want to pull the helm charts by default, and your helm repo has a branch checked out that has a remote upstream branch set up. In this case, the build just succeeds:
```
$ make .ensure-helm-charts-repo-exists
Pulling down latest helm-charts from remote repo to here: /home/jmazzite/source/kiali/helm-charts
```
2) You want to pull the helm charts by default, but your helm chart repo does not have a branch with a valid remote upstream branch. In this case, the build will fail, but you now get a better error …
=> Provide better flexibility when building helm charts.

Makefile, make/Makefile.build.mk
the Makefile is hardcoding "go" which assumes Go is in the PATH and that's the version of Go to use, which is not a good assumption. This is why we have the GO env var - so that should be used.
=> need to use the GO env var in makefiles

kubernetes/iter8.go
Support Ratio_Statistics ( in Kiali-ui, the data is used in the experiment assessment page for min/max credible interval)
=> Update mis-spelled ratio_statitics to ratio_statistics

hack/ci-openshift-molecule-tests.sh
This will be useful for QE since they want to run molecule tests against a specific version of Istio.
New option: `-iv` or `--istio-version` - pass in a X.Y.Z version ... eg. `-iv 1.7.0`
=> hack script can now be told what version of Istio to download

business/openid_auth.go, config/config.go
Closes #3451 .
This PR adds proxy support to OpenId's requests for metadata for the
issuer. This fixes the problem where Kiali requires a proxy to connect
to the outside world. This is not normally a problem, as the resources we
connect using Kiali are usually inside the cluster.
OpenID is the exception, as we need to connect to the issuer to get
information to move the user forward. This PR adds proxy support to this
specific request.
1. Install Squid on your machine, or other HTTP proxy.
2. Install kiali with the correct configuration options (`http_proxy`
and `https_proxy` on the openid section of the CR, and OpenId configured).
3. Connect/authenticate on Kiali using OpenID
4. Check squid log for the request.
=> Add proxy to OpenId metadata http requests

make/Makefile.molecule.mk
when running molecule tests, get make to build the updated helm chart so devs don't have to remember to do it.
=> create the helm charts so people don't have to remember to do it when running tests

make/Makefile.operator.mk
Make target should ensure the CRDs exist and create a "dummy" Kiali CR.
This must be paired with this PR: https://github.com/kiali/kiali-operator/pull/229
fixes: https://github.com/kiali/kiali/issues/3528
=> get the "run-operator-playbook" make target to behave more like a deployed operator

business/istio_status.go, business/istio_status_test.go
This change tries to approach [this comment](https://github.com/kiali/kiali/issues/3508#issuecomment-742617476).
The main point for them was:
1. They misplaced the `istio_namespace` config in the CR.
2. They correctly placed a different namespace for the `kiali` deployment (through: `spec.deployment.namespace`).
3. The operator set `istio_namespace` to `spec.deployment.namespace` (see [operator code](https://github.com/kiali/kiali-operator/blob/22e89317e94dc22667fe00ac98c5fdccda130b66/roles/v1.0/kiali-deploy/tasks/main.yml#L38-L47))
4. The istio components feature couldn't find any istio components (istiod, istio-ingress/egress).
5. The proxy status in health couldn't find any `istiod` pod to fetch the syncs.
In order to leverage attention in users minds, I've placed a notification like …
=> Add a notification when kiali can't find any istio component

business/istio_status.go, business/istio_status_test.go, kubernetes/istio.go
This is a workaround for the https://github.com/kiali/kiali/issues/3543
Right now, Istio forces the usage of the app label as "app" while there are user which use different app label in their other deployments. It sounds a bit inconsistent.
Need this PR to quickly fix the bug in our users but we expect Istio to fix this situation. When this is fixed in upstream Istio, we'll be back to previous usage.
To reproduce change the istio_labels settings in your CR similarly to the following snippet:
```yaml
istio_labels:
app_label_name: different_app_label
version_label_name: different_version_label
```
Previous behavior:
- Error message shown right after login:
- All health in warning (unsync'ed workloads):
Right after, those errors shouldn't show up.
=> Force kiali to use "app" label name for fetching istio components

graph/telemetry/istio/appender/appender.go, graph/telemetry/istio/appender/service_entry.go, graph/telemetry/istio/appender/service_entry_test.go
When matching Service Entries with hosts make sure the SE is exported to the current namespace.
Fixes https://github.com/kiali/kiali/issues/3552
=> Handle `ExportTo` when Service Entry matching

prometheus/client.go
fixes: https://github.com/kiali/kiali/issues/3518
=> make a copy of the prometheus default round tripper http transport to avoid race condition

business/health.go, business/proxy_status.go, business/workloads.go, models/pod.go
fixes https://github.com/kiali/kiali/issues/3539
The idea behind is to disable the unsync'ed pods when the cache is disabled.
This will avoid the situation mentioned in the issue linked right above and won't show warnings in all health.
The proxy-status is disabled when cache is disabled because the query performed can be massive and will dramatically damage the whole performance in medium deployments.
To reproduce:
Add the following config in your kiali CR to disable the cache:
```yaml
kubernetes_config:
cache_enabled: false
```
Bug:
You should be able to see all the health in the mesh with unsynced proxies.
=> Disable the proxy status into health when cache is disabled (all pods doesn't have sidecar)

business/layer.go, hack/k8s-minikube.sh, hack/run-molecule-tests.sh, handlers/dashboards.go, handlers/utils.go, kubernetes/kubernetes.go
Update the run-molecule-tests script so it prepares header-auth correctly.
Also change the k8s-minikube.sh hack script to only create that special role when requested.
Cleans up some import ordering, too.
=> Fix some things to work with the new header auth strategy

business/mesh.go, handlers/config.go
The server configuration API endpoint will now return the cluster_id and the network_id of the cluster.
This code is to support UI changes: kiali/kiali-ui#2052
Related kiali/kiali#3523
=> Add Cluster info to the server config

business/jaeger.go, routing/router.go
- There was no internal metrics for jaeger, adding some
- There was a bug in handler metrics, only the ones from unauthenticated
routes were created. Fix that.
This is a prequel of https://github.com/kiali/kiali/issues/3514 , to measure performance changes before/after that task
=> Add jaeger measurements, fix handler metrics

kubernetes/cache/cache.go, kubernetes/client.go, kubernetes/client_factory.go
These changes are, apparently, unneeded. Also, it's a error prone, because there were two tokens involved when creating the client. There was one in the `config` parameter, and another one in `authInfo` parameter. Only the token in `config` was being used. The `authInfo` is used only to pass impersonation data, but this data shouldn't always be honored because it's only valid when using the `header` strategy.
So, I think it's better to rollback these changes and pass the impersonation data already embedded in the `config` parameter when it's strictly needed. The `config` parameter already has impersonation fields, so the extra `authInfo` is, apaprently, redundant.
Related kiali/kiali#3207
=> Rollback a few changes to NewClientFromConfig

models/service_entry.go
Fixes the key in the ServiceEntry model spec for the workloadSelector, ensuring this displays correctly in the kiali UI.
https://github.com/kiali/kiali/issues/3587
Yes
=> Fix ServiceEntry model spec workloadSelector key

business/workloads.go, kubernetes/filters.go, models/workload.go
Fixes https://github.com/kiali/kiali/issues/3532
Some frameworks create custom workload controllers replacing standard "Deployment" or kubernetes controller with a custom one.
This fix improves the support for those cornercases.
It assumes that, as it happens with a Deployment, a custom controller define a child controller as a ReplicaSet and try to use it for basic workload information: pod and service status.
Most information is ok but custom properties of the controller are not supported as we would need to extend the native controllers that Kiali can handle beyond the standard ones.
For QE, how to test:
- Verify no regressions on existing workloads logic.
- Install a third party framework with custom controllers, i.e. https://argoproj.github.io/argo-rollouts/#quick-start
- Deploy an …
=> Better support for custom controllers

business/mesh.go, config/config.go, handlers/config.go
Adding a function to check if multi-cluster is enabled in Istio. The config endpoint uses this new funct to return cluster data only if multi-cluster is enabled. This is to allow the UI to conditionally hide or show multi-cluster features.
Related to #3592
=> Check if Istio has multi-cluster enabled

hack/istio/install-istio-via-istioctl.sh
don't always assume the user wants gcr.io. This allows you to tell the script to get the images from the default hub.
=> [hack] be able to tell the script to get the images from a custom hub

graph/telemetry/istio/appender/idle_node.go, graph/telemetry/istio/appender/idle_node_test.go
When checking for Idle Nodes we need to incorporate the proper clusterName into the ID of the candidate node.
Fixes https://github.com/kiali/kiali/issues/3611
For QE Test:
With master:
1) Install using hack/istio/install-istio-via-istioctl.sh or otherwise ensure you configure with a meshId and clusterName
2) Generate bookinfo graph with traffic
3) Enable Display Idle Nodes
See unexpected Idle Nodes appear
Repeat with PR, no Idle Nodes should appear
=> Fix Idle Node detection for multi-cluster

business/openshift_oauth.go
This one function has *four* identical error messages that could get logged. Because all four messages are identical, when you see the log message in the pod logs, it isn't immediately easy to figure out where the error was happening.
This PR makes the messages unique so you know what failed immediately when you read the message.
=> make error messages unique

business/mesh.go, config/config.go
The constant isn't guaranteed to be the name of the istio configmap, so do not use it. This PR removes it as well as the one reference to it.
fixes: https://github.com/kiali/kiali/issues/3634
fixes: https://github.com/kiali/kiali/issues/3637
backport PR: https://github.com/kiali/kiali/pull/3638
=> Use the configured name for the Istio ConfigMap - do not use the constant

business/mesh.go, config/config.go
This is a backport of https://github.com/kiali/kiali/pull/3636
=> [v1.29] Use the configured name for the Istio ConfigMap - do not use the constant

kubernetes/istio.go
fixes https://github.com/kiali/kiali/issues/3605
1. The proxy-status is only fetch from pods in the `Running` state.
2. Kiali returns the proxy-status even if there is one non-responding `istiod` (following the `istioctl` approach). The proxy-status then might be partial because each `istiod` pod controls different set of envoys (e.g. `istiod1` controls `details` and `productpage`, `istiod2` controls `ratings` and `reviews`). If this scenario happens, then the Istio Component Status modal in the mast-head will be in red. Hence, it'd mean that the mesh is unstable and the admin/op needs to act.
3. New logs has been added to better troubleshoot this scenarios.
=> Proxy status: fetching status only from running istiod pods + always returning status if present

business/dashboards_test.go, prometheus/client.go, prometheus/metrics.go, prometheus/prometheustest/mock.go
- Do not copy prom's default round tripper as it contains a lock
- Add trace-level logs on prom queries
=> Prometheus client: fix lock copy + add traces

business/dashboards.go, config/config.go
- discovery_enabled (true/false/auto) to switch discovery mode
- discovery_auto_threshold: pods threshold above which discovery is
skipped in auto mode
Part of https://github.com/kiali/kiali/issues/3660
Operator PR: https://github.com/kiali/kiali-operator/pull/243
=> Performance / custom dashboards: new configs

business/dashboards.go, config/config.go
(backport of #3668)
- discovery_enabled (true/false/auto) to switch discovery mode
- discovery_auto_threshold: pods threshold above which discovery is
skipped in auto mode
Part of https://github.com/kiali/kiali/issues/3660
=> [v1.29] Performance / custom dashboards: new configs (#3668)

business/istio_status.go, business/istio_status_test.go, kubernetes/client.go, kubernetes/istio.go, kubernetes/kubernetes.go, kubernetes/kubetest/mock_kubernetes.go
This PR attempts to add prevention fixes to the forever taking request when the kube-api doesn't have access to istiod pods.
Fixes https://github.com/kiali/kiali/issues/3494
Three additions:
1. Adding timeouts to Pod Proxy calls.
2. Early return when Kiali can't check one healthy Istiod liveliness probe endpoint.
3. The Istio Component Status (masthead light) incorporates the liveliness probe result for each istiod pod (only shows the non reachable istiods)
To reproduce the scenario:
```
watch -n 3 kubectl delete pod -n istio-system --selector=app=istiod
```
=> Prevent Proxy Status endpoint to hang + Add unreachable istiod into Istio Component Statuses

hack/istio/install-istio-via-istioctl.sh
fixes: https://github.com/kiali/kiali/issues/3714
The problem here is we need to also workaround a bug in istioctl that also doesn't allow us to install in a non-istio-system namespace. We need that bug to be fixed. For now, there is workaround code in here that avoids that istioctl bug.
=> [hack] be able to install in a non-default namespace

graph/config/cytoscape/cytoscape.go, graph/telemetry/istio/appender/appender.go, graph/telemetry/istio/appender/dead_node_test.go, graph/telemetry/istio/appender/service_entry.go, graph/telemetry/istio/appender/service_entry_test.go, graph/types.go, swagger.json
Replacing "isServiceEntry", which wasn't actually a bool but a string
MESH_INTERNAL or MESH_EXTERNAL, with a struct holding "location" and
"hosts"
Fixes https://github.com/kiali/kiali/issues/3728
Frotnend PR: https://github.com/kiali/kiali-ui/pull/2089
=> Add hosts to SE node in graph

business/istio_status.go, business/istio_status_test.go, kubernetes/istio.go
While computing the istio component status, in particular the istiod reachability, kiali might introduce a sequential 10s waiting.
This PR approach this adding recurrence in each call to istiod. 
The scenario to reproduce this should be having 2+ istiod pods not responding. Then, Kiali should be waiting 10s for each istiod. After this PR, Kiali should only wait for 10s max (due to the concurrence).
In addition, there it fixes a bug that might also impact the computation of the `proxy status`. A bad usage of pointers might kiali make fetch envoy status to non-healthy istiods.
=> Adding concurrency to istio components status

business/dashboards.go, prometheus/client.go
Fixes https://github.com/kiali/kiali/issues/3737
Necessary when app/version labels are not the default ones
=> Fix sanitizing label names

handlers/authentication.go
The code handling OIDC authentication for the "implicit flow" is not
fully validating the received id_token *when* RBAC is turned off. Under
these cofiguration, only the CSRF mitigation check and the replay attack
mitigation is happening.
This is adding the missing lines of code to fully verify the id_token on
an "implicit flow + RBAC off" configuration.
=> Add missing token validation for implicit flow

business/checkers/destinationrules/disabled_namespacewide_mtls_checker.go, business/checkers/destinationrules/disabled_namespacewide_mtls_checker_test.go, business/checkers/peerauthentications/disabled_namespacewide_checker.go, business/checkers/peerauthentications/disabled_namespacewide_checker_test.go, tests/data/validations/peerauthentications/disabled_namespacewide_checker_6.yaml
Found when preparing the demo last friday.
To reproduce:
- Enable mtls at mesh-level (PeerAuthn + DR)
- Disable mtls at ns-level (PA + DR)
See this yaml: [disabled_namespacewide_checker_6.yaml](https://github.com/kiali/kiali/blob/dbaa2698d80ea0321a8e157dde18f38d6e5ec1fb/tests/data/validations/peerauthentications/disabled_namespacewide_checker_6.yaml)
Before the PR: validations should apply into DR/PA at NS-level.
After PR: no validations for DR/PA at NS-level.
=> Bug: Disabled mtls at ns-level + Strict mtls at mesh-level

business/istio_status.go, business/istio_status_test.go
fixes https://github.com/kiali/kiali/issues/3682
needs front end: https://github.com/kiali/kiali-ui/pull/2100
Steps to reproduce:
1. Downscale to 0 replicas for each istio component deployment you want to test
Note: Istiod and egress are the one downscaled. The ingress status is legit (nothing have to do with the modification)
=> Add NotReady status for replicas downscaled to 0

.github/workflows/kiali-ci.yml, Makefile, README.adoc, deploy/jenkins-ci/Dockerfile
Because go 1.14 is now unmaintained.
Fixes #3722
=> Bump golang version to 1.16.2

hack/istio/install-error-rates-demo.sh, hack/istio/install-travel-agency-demo.sh
Make hack scripts easier for deploying local demo versions of travel or error-rates demo
adds -s|--source option
=> Make hack scripts easier for deploying local demo versions

deploy/jenkins-ci/Dockerfile, deploy/jenkins-ci/Jenkinsfile, deploy/jenkins-ci/README.md, deploy/jenkins-ci/jenkins_ref/init.groovy.d/setup-jenkins.groovy, deploy/jenkins-ci/jenkins_ref/jobs/kiali-helm-release/config.xml, deploy/jenkins-ci/jenkins_ref/jobs/kiali-operator-release/config.xml, deploy/jenkins-ci/jenkins_ref/jobs/kiali-release/config.xml, deploy/jenkins-ci/jenkins_ref/jobs/kiali-website-release/config.xml
This is also adding mail notifications for failed builds... only if back-end or front-end fails. Operator, Helm charts and website won't have failure notifications, because that needs to be added in the corresponding repos.
Related to #2895
=> Simplify pipeline parameters and update README

business/mesh.go, config/config.go
Istiod deployment might have different names depending of the instalation. for example, istio upgrade via canary deployments changes the name in the following convention `istiod-${istio-version}` (e.g. istiod-1-9-1). However, the other bits of the deployment aren't changed at all (image, labels, template labels, so on).
This PR approaches the problem as it was approached for the config map: adding a new config into the kiali CR to specify the specific name.
```
istio:
istiod_deployment_name: "istiod-1-9-1"
config_map_name: "istio-1-9-1"
```
This partially fixes https://github.com/kiali/kiali/issues/2884 (at least the original description).
This PR needs an operator PR: https://github.com/kiali/kiali-operator/pull/270
**Steps to test:**
One way to try this fix is by …
=> Add the IstiodDeploymentName to config and use it in the mesh business

README.adoc, hack/run-kiali-config-template.yaml, hack/run-kiali.sh
fixes: https://github.com/kiali/kiali/issues/3781
This script will allow you to run Kiali on the local machine so you can do quick code/build/test cycles without having to deploy the server on the cluster.
It attempts to auto-discover the k8s api master endpoint - but there are cmdline options to let you override it.
It attempts to auto-discover the location of your UI console build - but there is a cmdline option to tell it where it is.
There are other cmdline options available, such as being able to tell the script to download a specific version of the UI console in order to be able to test a specific UI release.
The config can be overridden, but it will provide you with a set of defaults out of box. Nothing special today, but I suspect in the future (maybe part of this PR if I have …
=> script that you can use to run kiali on the local machine

business/istio_config.go
Required for https://github.com/kiali/kiali/issues/3763
One line fix, it doesn't need to wait for a UI pr.
How to test:
```
GET http://admin:admin@localhost:8000/api/istio/permissions?namespaces=default
```
should include "serviceentries" in the "permissions" result.
=> Include ServiceEntries in GetPermissions

hack/istio/install-sm2.sh
This is still left behind doing the documented uninstall procedures:
```
$ oc get -n kube-system daemonset
NAME             DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
istio-cni-node   3         3         3       3            3           kubernetes.io/os=linux   7d20h
```
This PR deletes that.
=> [hack] clean up the istio-cni pods from kube-system, too

business/mesh_test.go, routing/router.go, util/httputil/http_util.go
I'm not sure why this is happening, because #3144 was supposed to fix the unneeded redirection. Anyway, this is yet another change to fix it "again".
Fixes #3762
=> Fix redirection from root-path without slash to root-path with slash

business/checkers/destinationrules/no_dest_checker.go
Since cross-ns validations are not in-place, when the host is not found for a DR, there is no need to check if there are workloads serving traffic for that host and matching the subset. It will always result in a not found place: the host is not found, therefore no workloads under the service listening to that host.
fixes https://github.com/kiali/kiali/issues/800#issuecomment-804741626
=> KIA0203 - If host not found, kiali will never find workloads matching labels

hack/istio/install-istio-via-istioctl.sh, hack/istio/multicluster/README.adoc, hack/istio/multicluster/config-mesh-networks.sh, hack/istio/multicluster/deploy-kiali.sh, hack/istio/multicluster/env.sh, hack/istio/multicluster/install-everything.sh, hack/istio/multicluster/setup-ca.sh, hack/istio/multicluster/split-bookinfo.sh, hack/istio/multicluster/start-kind.sh, hack/istio/multicluster/start-minikube.sh, hack/istio/multicluster/uninstall-everything.sh, hack/k8s-minikube.sh
Based off work done by @israel-hdez - originally from his gist - see Discussion https://github.com/kiali/kiali/discussions/3699
This is now done. It supports `OpenShift` (you must start 2 clusters yourself), `Minikube` (the script can create 2 minikube clusters for you) and `Kind` (again, the script will create 2 kind clusters for you).
The main script is `install-everything.sh`. Use the option `--help` for usage. To uninstall, use `uninstall-everything.sh`.
```
./install-everything.sh \
-c oc \
-it 1.9.2 \
-c1c https://api.your-openshift1.com:6443 \
-c2c https://api.your-openshift2.com:6443
```
(note that today you need to build a custom istioctl to work with openshift due to an istioctl bug that is not fixed until Istio 1.10. For details on how to build it, see: …
=> [hack] multi-cluster setup scripts

make/Makefile.molecule.mk
This is needed when we want to start testing different versions via the molecule tests.
=> [molecule] set image version when testing non-default spec.version

business/openid_auth.go, config/config.go, handlers/authentication.go
Azure requires:
* Usage of access_token rather than the id_token. This is because Azure doesn't use a real "openid" configuration. Instead, it uses webhooks to validate bearer tokens and check privileges.
* A target resource_id when redirecting the user for authentication. However, rather than adding a specific setting for this, an additional_request_params configuration is added to make it more generic.
Authentication with azure is going to work **only on the authorization code flow**.
Operator PR: https://github.com/kiali/kiali-operator/pull/289
Related #3294
=> OpenID Azure AKS+AAD support

handlers/config.go
This is to allow cross-linking Kialis.
Front-end PR: kiali/kiali-ui#2118
Related #3717
=> Add full list of discovered clusters to config endpoint

business/istio_status.go, business/istio_status_test.go, config/config.go
fixes #3631 
This PR allows users to specify which URL should kiali ping to compute the health check for each add-on (jaeger, prom, grafana and custom dashboards).
There are a lot of different deployments for each add-on, so this give flexibility.
This PR needs **operator changes**: https://github.com/kiali/kiali-operator/pull/277
=> Allow users to override add-on urls to check health for istio component status

business/istio_status.go, business/istio_status_test.go, business/layer.go
fixes https://github.com/kiali/kiali/issues/3725
needs operator PR: https://github.com/kiali/kiali-operator/pull/262
needs helm-chart PR: https://github.com/kiali/helm-charts/pull/51
To reproduce this one:
1. Delete the istio ingress deployment
2. Apply the following daemonset
`k apply -f https://raw.githubusercontent.com/xeviknal/istio-lab/master/istio-ingressgateway-daemonset.yaml -n istio-system`
DNM - needs https://github.com/kiali/kiali-operator/pull/261 to be merged first.
=> Istio ingress may be installed as a daemonset

business/openid_auth.go, handlers/authentication.go
In the authorization code flow, tokens returned by IdP can be long to the point that the session cookie also becomes long. Although RFCs don't set a maximum cookie size (see https://tools.ietf.org/html/rfc2965), in practice, major browsers use the RFC minimum limit as it's supported maximum - which is 4K. This means that longs tokens can cause the session token to reach this limit and be discarded by browsers.
This is overcoming these limitations by splitting session data in chunk no longer than 4K and setting multiple cookies, if needed.
The multi-cookie approach is applied only to the "authorization code" flow of OpenID. The "implicit flow" is left unchanged because IDPs tend to omit group membership data, which is the data that users have reported to generate larger tokens.
Fixes #3874
=> Fix login failure with long OpenId tokens

make/Makefile.operator.mk
Needed for devs that run the operator playbook via make, like this:
`make -e OPERATOR_PROFILER_ENABLED=true -e CLUSTER_TYPE=minikube run-operator-playbook `
=> need to allow ad hoc namespace and images when running the playbook target

CONTRIBUTING.md
Fixes a broken link in the [Developing section](https://github.com/kiali/kiali/blob/master/CONTRIBUTING.md#developing) of the `CONTRIBUTING` guide.
=> Fix broken link in CONTRIBUTING guide

business/mesh.go
Adds the namespace as additional context to the 404 error message returned from the `MessageService.IsMeshConfigured` method. This error gets directly surfaced to the UI on the graph page.
New error message with additional context added
Fixes #3821
=> Add additional context to configmap 404 message

business/mesh.go, business/mesh_test.go, config/config.go
This change addresses #3923 by adding a new configuration attribute for istio_sidecar_injector_config_map_name
#3923 
Should be backwards compatible
Updated kiali_cr.yaml in https://github.com/kiali/kiali-operator/pull/295
=> Adds configuration for the istio-sidecar-injector configmap name

Makefile, kiali_api.md, make/Makefile.build.mk
Generate API markdown (kiali_api.md) as part of the swagger-gen make target. This will give devs a way to look at a simple API document via github.
- also, update go-swagger version to the latest.
Fixes https://github.com/kiali/kiali/issues/3491
=> Generate API markdown (kiali_api.md) as part of swagger-gen

Makefile
Adds an additional env var to the makefile to check if the cluster is ready. Useful if other env vars need to talk to the cluster to determine their value and might otherwise timeout such as with `IS_MAISTRA`.
Should also help speed up unit tests run in CI where there isn't a working cluster.
Fixes #3910
=> Adds a check to the makefile to see if OC is ready

graph/telemetry/istio/appender/dead_node.go, graph/telemetry/istio/appender/idle_node.go, graph/telemetry/istio/appender/idle_node_test.go
Adds idle nodes to the graph in the homecluster instead of "unknown".
Behavior before the change:
Behavior after the change:
Fixes #3917
=> Ensure idle nodes are created in the homecluster

jaeger/http_client.go
Fixes https://github.com/kiali/kiali/issues/3939
cc @brendarearden 
Kiali is using GRPC and HTTP clients to connect Jaeger.
It keeps both because some systems may use an OAuth sidecar to protect Jaeger and we've found that GRPC + OAuth sidecars may introduce some problems.
So, in short, there is a bug in the legacy HTTP query that it was missing a unit in the backend code when present a parameter.
How to test:
- Navigate into the traces tab in any of the demos examples we use with traces enabled and set the percentile options.
- Validate that no errors are found and Traces tab is stable.
=> Fix missing units in jaeger query

business/workloads.go, business/workloads_test.go
Fixes https://github.com/kiali/kiali/issues/3830
This fix will provide better support for custom controllers and invalid types.
QE:
- Test a invalid/valid query:
```
GET http://admin:admin@localhost:8000/api/namespaces/default/workloads/reviews-v3/health?rateInterval=60s&type=invalid
```
404 expected
```
GET http://admin:admin@localhost:8000/api/namespaces/default/workloads/reviews-v3/health?rateInterval=60s&type=Deployment
```
200 expected
- Regression testing for custom controllers:
https://github.com/argoproj/argo-rollouts
https://github.com/argoproj/argo-rollouts/blob/master/docs/getting-started.md
Check that RollOut controllers are seeing in Kiali as Workloads without any crash
cc @hhovsepy I'm starting to adding you on PR as Dev role :) just with the aim to get you familiar with the …
=> Fix invalid workload types

graph/telemetry/istio/appender/service_entry.go, graph/telemetry/istio/appender/service_entry_test.go
Fixes #3938 
Creates Service Entry nodes in the homecluster instead of `unknown`.
Before change:
After:
=> Create service entry nodes in homecluster

hack/ci-minikube-molecule-tests.sh, hack/k8s-minikube.sh
In older versions of minikube, our molecule tests that needed Dex would fail. So we always had to use an older version of k8s (v1.18).
But now it seems things work with the latest minikube and the latest stable k8s that it uses (v1.20).
Once this is merged, the nightly molecule test runs no longer have to ask minikube to start an older version of k8s.
I confirmed the molecule tests involving authentication work with this. Run this:
```
hack/run-molecule-tests.sh --client-exe $(which kubectl) -dorp podman --cluster-type minikube -at "header-auth-test openid-test token-test"
```
and you get:
```
header-auth-test... success [2m 34s]
openid-test... success [2m 1s]
token-test... success [2m 21s]
```
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", …
```
=> [hack] some tweaks to k8s-minikube.sh

kubernetes/cache/istio.go, kubernetes/cache/istio_test.go
Sets `TypeMeta` for istio objects returned from the cache. Other parts of the codebase rely on that `TypeMeta` information being set but Kubernetes/client-go does not set this information on its own.
Fixes #3837
=> Set typemeta for istio cache objects

config/config.go, kiali_api.md, models/pod.go, swagger.json
@lucasponce Here is a server-side solution to #3977.  It could also be solved client-side, either way requires some special-casing of the istio pods (gateways) that are themselves proxies, not injected, but native.  This change allows clients to treat them as proxies, in particular the workload logs can then offer the special handling of the access logs.
So, let me know if this solution seems OK to you, or if you think a client-side solution would be better.
Fixes https://github.com/kiali/kiali/issues/3977
REQUIRES UI PR: https://github.com/kiali/kiali-ui/pull/2155
Related Operator PR: https://github.com/kiali/kiali-operator/pull/314
=> Make sure Istio gateways are captured as proxies

kiali.go, routing/router.go, routing/router_test.go, server/server_test.go
Specifically, stop writing changes to the index.html and env.js files, which come from the UI package.
These files are now generated on the back-end and served directly, rather than changing the files on the pod filesystem.
This allows using `readOnlyRootFilesystem: true` for the securityContext in the Kiali pod.
Related FAQ entry is removed in: https://github.com/kiali/kiali.io/pull/375
Fixes #3810
=> Allow read-only file system in Kiali's pod

hack/purge-kiali-from-cluster.sh
either this is new behavior in the latest kubectl or I never noticed this before but the purge script isn't deleting cluster resources on minikube because the command fails when it can't find any oauth or consolelink times (those are openshift only).
this fixes that problem
=> [hack] fix purge script so it purges correctly on minikube

business/istio_config.go, business/istio_validations.go, config/config.go, kiali_api.md, kubernetes/cache/istio.go, kubernetes/types.go, models/istio_config.go, models/workload_group.go, swagger.json
Fixes https://github.com/kiali/kiali/issues/4019
Fixes https://github.com/kiali/kiali/issues/4025
Fixes https://github.com/kiali/kiali/issues/4015
UI needed https://github.com/kiali/kiali-ui/pull/2160
Operator https://github.com/kiali/kiali-operator/pull/319
This group of PRs (backend, frontend and operator) has two goals:
- Unify the caching of Istio resources.
- Add missed WorkloadGroup Istio resource into Kiali.
How to test:
- The https://github.com/kiali/kiali/issues/4019 scenario applies only on OpenShift platform, in the case where a user has accesss to a project/namespace BUT it has not access to the Istio resources, Kiali would be able to show the list of resources if cache is enabled; when a user tries to access to a particular resource, it will throw an error as it has not …
=> Update Istio Cache + Include WorkloadGroup resources

business/iter8.go, kiali_api.md, models/iter8.go, swagger.json
Iter8 Info endpoint now contains namespace and version info, preparing for the support for Iter8 v2.x
the /iter8Info endpoints now also return namespace of where iter8 is installed. And if the Iter8 version is 2.x, the `supportedVersion` field will be false, indicating 2.x version is yet supported.
The namespace info is retrieved from Kiali CR.  
```
{
"enabled": true,
"supportedVersion": false,
"controllerImgVersion": "",
"analyticsImgVersion": "2.1.0",
"namespace": "iter8-system"
}
```
=> Iter8 Info Endpoint changes

config/config.go
Graph Find/Hide now offers preset expressions via new dropdowns on each input. The preset expressions are supplied via the UIDefaults supplied by the server, and so can be configured by users via the CR.
Part-Of kiali/kiali#3708
UI PR: https://github.com/kiali/kiali-ui/pull/2159
Operator PR: https://github.com/kiali/kiali-operator/pull/315
=> Introduce Graph Find/Hide presets

business/health.go, graph/telemetry/istio/appender/util.go, graph/telemetry/istio/istio.go, graph/util.go, handlers/dashboards.go, handlers/errors.go, handlers/mesh.go, handlers/metrics.go, handlers/namespaces.go, prometheus/client.go, prometheus/metrics.go
Assume a connectivity issue on Prometheus API failures. A CX issue is fairly typical, an application error is very unlikely.  This stops stack traces returned to the user on a prom connectivity problem.
Fixes https://github.com/kiali/kiali/issues/4014
=> Assume a connectivity issue on Prometheus API failures

business/checkers/authorization/no_host_checker.go, business/checkers/authorization/no_host_checker_test.go, business/checkers/destinationrules/multi_match_checker.go, business/checkers/destinationrules/multi_match_checker_test.go, business/checkers/destinationrules/no_dest_checker.go, business/checkers/destinationrules/no_dest_checker_test.go, business/istio_validations.go
Fixes https://github.com/kiali/kiali/issues/4049
This PRs fixes the use of FQDN when validating if a host is present in the Istiod registry.
This work also "adjusts" the behaviour of several cross-namespace validation on the DestinationRules, now that the registry has all services available, a DR can detect when a host is present or not.
How to test:
- Check that a scenario like https://github.com/kiali/kiali/issues/4049 is supported.
- Check that a service defined in a ns1 namespace is validated in a DR/VS if it's defined in a ns2 namespace.
- Validate that the only changes/regressions will be the "cross-namespace" ones that now should be adjusted in the integration tests.
@skondkar @hhovsepy I expect that this PR may be not 100% complete and some corner case may be missed, let me know …
=> Use FQDN in Istiod Registry validations

graph/config/cytoscape/cytoscape.go, graph/meta.go, graph/telemetry/istio/appender/istio_details.go, graph/telemetry/istio/appender/istio_details_test.go, graph/types.go, kiali_api.md, swagger.json
Adds all supported kiali traffic wizard scenarios to the service node metadata if they have the `kiali_wizard` label.
Relates to: #1477 
Front end changes: https://github.com/kiali/kiali-ui/pull/2165
=> Add additional kiali scenarios to node metadata

handlers/health.go
Support 'queryTime' query parameter for Health requests.  Previously assumed  'Now' for the endTime of all health time periods.
Part of https://github.com/kiali/kiali/issues/4058
**UI PR:** https://github.com/kiali/kiali-ui/pull/2172
=> Support 'queryTime' query parameter for Health requests.

models/pod.go, swagger.json
Fix of https://github.com/kiali/kiali/issues/3529
Front-end changes required https://github.com/kiali/kiali-ui/pull/2171
Taking "Ready" property from Pod.Status.ContainerStatuses for each Container and passing that into json.
This property will be used in Kiali UI per Workload's Pod to show whether there is any failing container in pod.
=> Added IsReady status on ContainerInfo taking from ContainerStatus

hack/docker-io-auth.sh
If you are hitting the docker.io rate limiting on your non-openshift clusters (e.g. minikube), this should help work around it.
Note also you can now pass in `-pi true` and get a list of all the images in your cluster that comes from docker.io (these are the ones that will potentially be rate-limited). On my minikube with Istio 1.10 installed and bookinfo installed (both using our hack scripts), those images are:
```
kiali/kiali-test-mesh-traffic-generator:latest
grafana/grafana:7.4.3
jimmidyson/configmap-reload:v0.5.0
prom/prometheus:v2.24.0
registry:2.7.1@sha256:d5459fcb27aecc752520df4b492b08358a1912fcdfa454f7d2101d4b09991daa
docker.io/istio/examples-bookinfo-details-v1:1.16.2
docker.io/istio/examples-bookinfo-mongodb:1.16.2
docker.io/istio/examples-bookinfo-productpage-v1:1.16.2 …
```
=> [hack] Support non-openshift clusters and add --print-images option

hack/ci-openshift-molecule-tests.sh
We lost our freenode registrations for the room and users, so we are moving over to libera for hopefully better stability and sanity within their network.
How dumb freenode is - we'll be learning about this debacle in business schools across the country for decades :)
=> ci script now sends results to libera chat room.

doc.go, graph/config/cytoscape/cytoscape.go, graph/meta.go, graph/telemetry/istio/appender/appender.go, graph/telemetry/istio/appender/response_time.go, graph/telemetry/istio/appender/response_time_test.go, graph/telemetry/istio/appender/security_policy.go, graph/telemetry/istio/appender/throughput.go, graph/telemetry/istio/appender/throughput_test.go, graph/telemetry/istio/istio.go, kiali_api.md, swagger.json
Add "throughput" appender to support new throughput edge labeling. 
Also
- Some changes to responseTime appender for "option" support analogous to Throughput
- update queryParam support for responseTime appender (it was broken anyway)
- change param from responseTimeQuantile to responseTime
- now support fixed [percentile] values only: avg | 50 | 95 | 99
- add support for average response time (prevuiously only supported quantiles
- add to doc.go, including some previously missed API stuff
PartOf: https://github.com/kiali/kiali/issues/2897
**UI PR:** https://github.com/kiali/kiali-ui/pull/2177 (see the UI PR for more detail on the issue)
=> Display throughput on the graph edges

business/checkers/authorization/no_host_checker.go, business/checkers/authorization/no_host_checker_test.go, business/checkers/destinationrules/no_dest_checker.go, business/checkers/virtual_services/no_host_checker.go, kubernetes/host.go
Tiny DRY refactor that I found while reviewing PRs related to the introduction of the service registry consumption.
And also making it a bit more consistent with the `HasMatching[Workloads|Services|ServiceEntries|VirtualServices]` methods already in place in the same package and for similar purposes.
=> Reusing Filter method for Service Registry loopup

business/services.go, models/pod.go, models/service.go, models/service_test.go, models/workload.go
Fix for issue https://github.com/kiali/kiali/issues/3904.
When counting sidecar persistence on service via logic that all pods have sidecars of this service, then health of the service is not shown.
But service can have some workloads which have all pods with sidecars. For those workloads the health exists and should be shown for service.
The purpose of this change is to consider the workloads sidecars existence for service sidecar.
=> Service Details sidecar is now checked in workload's sidecars.

business/openid_auth.go, config/config.go
Adding support for custom CA certificate for the OpenID authentication.
The CA certificate is provided through a volume mount. Thus, this checks for existence of the certificate file and uses it, if available.
Related operator PR: https://github.com/kiali/kiali-operator/pull/333
Related #4050
=> Support for custom CA certificate for OpenID auth

make/Makefile.operator.mk
I would like these backported to the v1.36 branch so that branch's makefile will be able to run the molecule tests against an operator that has been installed via OLM. Should make testing 1.36 builds easier.
This is a backport of:
* https://github.com/kiali/kiali/pull/4126
* https://github.com/kiali/kiali/pull/4127
=> [v1.36] backport some fixes to the makefile to support testing with OLM

business/checkers/virtual_services/no_gateway_checker.go, business/checkers/virtual_services/no_gateway_checker_test.go, tests/data/validations/virtualservices/non-existent-gateway-in-match.yaml, tests/data/validations/virtualservices/non-existent-ns-gateway-in-match.yaml
**Description**
This PR enhances the validation of gateways in VirtualServices, specifically the gateways contained by HTTPMatchRequests objects.
**Issue**
[2932](https://github.com/kiali/kiali/issues/2932)
The following VirtualService will have 2 errors during validation:
```yaml
kind: VirtualService
metadata:
name: bookinfo
namespace: default
spec:
hosts:
- '*'
gateways:
- nonexistent-bookinfo-gateway
http:
- match:
- gateways:
- bookinfo-gateway
- uri:
exact: /productpage
- uri:
prefix: /static
- uri:
exact: /login
- uri:
exact: /logout
- uri:
prefix: /api/v1/products
route:
- destination:
host: productpage
port:
number: 9080
- match:
- gateways:
- bookinfo-gateway
- nonexistent-bookinfo-gateway
- uri:
exact: /productpage
- …
```
=> Validate gateways contained by HTTPMatchRequests objects

business/dashboards.go, config/dashboards/dashboards_config.go, kiali_api.md, models/dashboards.go, swagger.json
Fixes https://github.com/kiali/kiali/issues/4156
With the refactoring of the Metrics tabs and the MonitoringDashboard definitions there was introduced the lack to allow users to define multiple rows in the new layout.
This PR (and the UI one https://github.com/kiali/kiali-ui/pull/2200) adds flexibility of the rows definition.
So, a dashboard may optionally define the rows, by default it will be a setup of two rows.
But user can define that, columns will be populated in a flex manner using spans to fill the grid (as used today).
So, using an example based on namespace:
```
apiVersion: v1
kind: Namespace
metadata:
name: default
annotations:
dashboards.kiali.io/templates: |
- name: custom_envoy
title: Custom_Envoy
discoverOn: "envoy_server_uptime"
rows: 4
items:
- chart:
name: "Pods uptime" …
```
=> Support multiple rows in metrics dashboards

business/checkers/common/export_to_namespace_checker.go, business/checkers/common/export_to_namespace_checker_test.go, business/checkers/destination_rules_checker.go, business/checkers/service_entry_checker.go, business/checkers/virtual_service_checker.go, business/istio_validations.go, models/istio_validation.go, tests/data/validations/exportto/dr_exportto_invalid.yaml, tests/data/validations/exportto/dr_exportto_valid.yaml, tests/data/validations/exportto/se_exportto_invalid.yaml, tests/data/validations/exportto/se_exportto_valid.yaml, tests/data/validations/exportto/vs_exportto_invalid.yaml, tests/data/validations/exportto/vs_exportto_valid.yaml
Added a validation of the namespace values "exportTo" fields.
Checking if namespace exists and user has access to it.
Validation is added for VirtualService, ServiceEntry and DestinationRule Istio Objects.
Error is displayed when namespace does not exist or is not accessible: "KIA0005 No matching namespace found or namespace is not accessible"
RFE: https://github.com/kiali/kiali/issues/1370
=> Added validation for "exportTo" fields of VirtualService, ServiceEntry and DestinationRule.

business/istio_status.go, business/istio_status_test.go, kubernetes/istio.go, kubernetes/kubernetes.go, kubernetes/kubetest/mock_kubernetes.go, util/httputil/port_forwarder.go, util/httputil/port_pool.go, util/httputil/port_pool_test.go
fix https://github.com/kiali/kiali/issues/4054
needs https://github.com/kiali/helm-charts/pull/84
needs https://github.com/kiali/kiali-operator/pull/336
What do you think if we replace the usage of the sub-resource `pod/proxy` by simple HTTP Get calls?
The idea is instead of using the Kube API to send GET requests to each IstioD pods, use the associated IP of each IstioD pod and send the request. This change would remove the requirement of opening the port 8080 from control plane to the istio system.
The initial rationale of using the sub-resource was basically following the steps of the istioctl. However, tried to consume the debug endpoints at service level or using pod names, but didn't work. It seems that using pod's IPs works.
However, I don't know how robust is the usage of POD's …
=> Replace PodProxy calls by plain HTTP GET calls

graph/telemetry/istio/appender/istio_details.go, graph/telemetry/istio/appender/istio_details_test.go, graph/types.go, models/virtual_service.go, models/virtual_service_test.go
Updates the istio appender to add the kiali scenario node metadata labels based on the VS spec instead of the presence of the wizard label.
Fixes: #4090
=> Add kiali scenarios to graph node from VS spec

hack/ci-minikube-molecule-tests.sh, hack/ci-openshift-molecule-tests.sh
This enables the ci-minikube to upload logs to a git repo just like ci-openshift can. In addition, this change allows both scripts to be told what branch to commit the logs to.
This allows us to upload the logs to a single git repo in different branchs. For example, the minikube test logs can go in branch "minikube" and the openshift test logs can go into the "openshift" branch. In fact, this is what I am now doing when running the nightly CI builds on my home machines: [minikube](https://github.com/jmazzitelli/kiali-molecule-test-logs/tree/minikube) and [openshift](https://github.com/jmazzitelli/kiali-molecule-test-logs/tree/openshift) logs.
=> be able to upload logs to different branches for ci-minikube and ci-openshift scripts

graph/telemetry/istio/appender/service_entry.go, graph/telemetry/istio/appender/service_entry_test.go
Removes the restriction that service entries have only a single edge since mesh internal service entries can have multiple edges to different workloads.
Fixes #4072
=> Allow service entries with multiple edges

business/checkers/common/export_to_namespace_checker.go, business/checkers/common/export_to_namespace_checker_test.go, tests/data/validations/exportto/dr_exportto_all_valid.yaml, tests/data/validations/exportto/se_exportto_all_valid.yaml, tests/data/validations/exportto/vs_exportto_all_valid.yaml
Fix for the issue https://github.com/kiali/kiali/issues/4203
Currently for VirtualService, in the current Istio release, the exportTo value is restricted to “.” or “*” (i.e., the current namespace or all namespaces).
Modified according to Istio requirements.
Modified the tests.
For QE:
Verify that: VS now shows warning when exportTo is something different than "." or "*".
Regression test existing 'exportTo' scenarios for VS, SE and DR.
"*" is now explicitly supported and means that exporting to all namespaces.
"." is still supported for all.
=> VirtualService's exportTo field's value is restricted to “.” or “*”.

hack/ci-kind-molecule-tests.sh, hack/run-molecule-tests.sh, make/Makefile.molecule.mk
This is a cherry pick of: https://github.com/kiali/kiali/pull/4189 because we cherry picked [its operator peer](https://github.com/kiali/kiali-operator/pull/376) and so we might as well get this in too (allows kind to run the tests in the 1.36 branch now)
* run molecule tests with kind
* Use volumes rather than mounts, and use full fork names
* Prefer using volumes rathern than mounting directories on the host
machine into the container. Although this was mainly to add
compatibility for using a remote docker engine, in general, this
potentially works better. The rationale is that there is no need to
adjust privileges nor SELinux on the host for the container to work
properly, because the container engine is fully managing the volume.
* Use forks's fullname rather than just the …
=> [v1.36] Run molecule tests with KinD (#4189)

config/dashboards/dashboards_config.go, swagger.json
This PR fixes the missing Grafana links in Workloads and Service metrics pages.
=> Fix missing Grafana Workload and Service links

config/config.go
fix https://github.com/kiali/kiali/issues/4238
related https://github.com/kiali/kiali-operator/pull/370
The default in_cluster_url should point to the new grpc port of jaeger.
Notice that kiali default installation will fail for older jaeger releases than 1.20. However, users will only need to change the configmap/kiali-cr fixing the port.
@jmazzitelli do we need to update any other thing to have all the installations covered?
I guess that  https://github.com/kiali/kiali-operator/pull/370 covered the installation through the operator, and with this PR we are covering helm and addons, right?
=> Jaeger v1.20+ uses new port for grpc. Default url points to it

business/mesh.go, graph/telemetry/istio/appender/aggregate_node_test.go, graph/telemetry/istio/appender/dead_node.go, graph/telemetry/istio/appender/dead_node_test.go, graph/telemetry/istio/appender/idle_node.go, graph/telemetry/istio/appender/idle_node_test.go, graph/telemetry/istio/appender/istio_details_test.go, graph/telemetry/istio/appender/response_time_test.go, graph/telemetry/istio/appender/security_policy_test.go, graph/telemetry/istio/appender/service_entry.go, graph/telemetry/istio/appender/sidecars_check_test.go, graph/telemetry/istio/appender/throughput_test.go
* Provide better defaults when ClusterID cannot be found.
* Avoid a crash if the configured sidecar injector configmap does not exist.
Fixes kiali/kiali#4221
=> Fix graph with spurious cluster boxes and a crash

routing/router.go
Fix non '/' root url failing to load if there are URL parameters (i.e. there is a ? symbol in the URL)
Fixes kiali/kiali#4215
=> Fix root URL not loading with URL parameters

business/mesh.go, graph/telemetry/istio/appender/aggregate_node_test.go, graph/telemetry/istio/appender/dead_node.go, graph/telemetry/istio/appender/dead_node_test.go, graph/telemetry/istio/appender/idle_node.go, graph/telemetry/istio/appender/idle_node_test.go, graph/telemetry/istio/appender/istio_details_test.go, graph/telemetry/istio/appender/response_time_test.go, graph/telemetry/istio/appender/security_policy_test.go, graph/telemetry/istio/appender/service_entry.go, graph/telemetry/istio/appender/sidecars_check_test.go, graph/telemetry/istio/appender/throughput_test.go, routing/router.go
Backports of both #4235 and #4231.
Just in case we go forward with a v1.38.1 release.
=> [v1.38] Fix router issue and cluster discovery

business/istio_status.go, business/istio_status_test.go, business/jaeger.go, config/config.go, jaeger/client.go, jaeger/http_client.go, jaeger/jaegertest/mock.go
backport of https://github.com/kiali/kiali/pull/4249
=> [v1.38] Using gRPC or HTTP methods to check health of the jaeger component

business/grafana_test.go, config/config.go
fixes https://github.com/kiali/kiali/issues/4261
Now, all the three addons have a default value: prom, jaeger and grafana.
=> Adding default grafana in_cluster_url

hack/istio/install-bookinfo-workload-entry.sh, hack/istio/workloadentry/bookinfo-service-entry.yaml, hack/istio/workloadentry/istiod-ingress.yaml, hack/istio/workloadentry/workloadgroup_template.yaml
Adds a hack script for easily testing workload entry/service entry changes locally.
The script assumes that you have the following running on your local machine:
- minikube started with podman driver `minikube start --driver=podman`
- Bookinfo installed along with Istio
If you are using the `k8s-minikube.sh` hack script on fedora, this should get you a working environment:
```
./hack/k8s-minikube.sh -kdr podman -mf --feature-gates=LocalStorageCapacityIsolation=false start
./hack/k8s-minikube.sh istio
./hack/k8s-minikube.sh bookinfo
./hack/istio/install-bookinfo-workload-entry.sh
make DORP=podman CLUSTER_TYPE=minikube build cluster-push operator-create kiali-create
```
At this point you should see traffic hitting your workload pod running outside of the minikube cluster: 
```
sudo podman …
```
=> Hack script for running podman pods as Workload Entries

business/checkers/virtual_service_checker.go, business/checkers/virtualservices/subset_presence_checker.go, business/checkers/virtualservices/subset_presence_checker_test.go, tests/data/validations/virtualservices/subset-presence-export-subset.yaml, tests/data/validations/virtualservices/subset-presence-no-matching-export-subset.yaml
Second PR for RFE https://github.com/kiali/kiali/issues/3061
Added Cross Namespace validations for SubsetPresenceChecker of Virtual Services.
Added support of exportTo field for validation "KIA1107 Subset not found".
=> Added support of exported DestinationRules for SubsetPresenceChecker of VirtualSevices. Added tests.

business/checkers/destinationrules/no_dest_checker.go, business/checkers/destinationrules/no_dest_checker_test.go, business/checkers/no_service_checker.go, tests/data/validations/virtualservices/subset-presence-matching-not-referenced.yaml, tests/data/validations/virtualservices/subset-presence-not-referenced.yaml, tests/data/validations/virtualservices/subset-presence-referenced.yaml, tests/data/validations/virtualservices/subset-presence-wrongly-referenced.yaml
POC for RFE: https://github.com/kiali/kiali/issues/4218
Documentation changes: https://github.com/kiali/kiali.io/pull/402
Make DestinationRules subset validations "Error" to "Info" when no VirtualService is referencing to that DestinationRule.
Before:
Error was displayed always when DR subset workload was not found.
After:
When DR subset workload is not found but that subset is not linked in any VS, Info severity is shown.
=> Make DRs subset validation error to info when no VS created for this subsets. Tests added.

business/istio_config.go, config/config.go, handlers/config.go
**Description**
This PR adds the property viewOnlyMode into the server configuration. 
This property can be used to avoid doing validations with k8s API and return faster from methods that manage resources.
```
http://localhost:20001/kiali/api/config
```
```json
{
...
"deployment": {
"viewOnlyMode": true
},
...
}
```
Frontend PR https://github.com/kiali/kiali-ui/pull/2219
=> Add viewOnlyMode property into config object

business/checkers/destination_rules_checker.go, business/checkers/destinationrules/multi_match_checker.go, business/checkers/destinationrules/multi_match_checker_test.go, business/checkers/destinationrules/multi_match_exported_checker_test.go, business/istio_validations.go, kubernetes/host.go
Third PR for https://github.com/kiali/kiali/issues/3061
Covering cross-namespace support of DestinationRule's '"exportTo" field in a scope of validation error "KIA0201 More than one DestinationRules for the same host subset combination"
Before:
After:
=> Added cross-namespace validation support for DestinationRule's MultiMatch checker message KIA0201

graph/config/cytoscape/cytoscape.go, graph/config/cytoscape/cytoscape_test.go, graph/meta.go, graph/telemetry/istio/appender/appender.go, graph/telemetry/istio/appender/workload_entry.go, graph/telemetry/istio/appender/workload_entry_test.go, kiali_api.md, swagger.json
Creates a `WorkloadEntry` appender that labels graph nodes which have a corresponding `WorkloadEntry` Istio config.
Fixes #4223 
Front-end changes: kiali/kiali-ui#2221
To test this locally, you can use [this hack script](https://github.com/kiali/kiali/blob/master/hack/istio/install-bookinfo-workload-entry.sh). See https://github.com/kiali/kiali/pull/4274 for more instructions on how to use the hack script.
=> Add workload entry appender to label WE nodes

business/checkers/destination_rules_checker.go, business/checkers/destinationrules/traffic_policy_checker.go, business/checkers/destinationrules/traffic_policy_checker_test.go, business/checkers/destinationrules/traffic_policy_exported_checker_test.go
Added support of exported DestinationRules in validation of TrafficPolicyChecker for message: "KIA0204 mTLS settings of a non-local Destination Rule are overridden."
Epic https://github.com/kiali/kiali/issues/3061
Subtask https://github.com/kiali/kiali/issues/4315
Create a DR in different namespace, having mTLS enabled, exported to local namespace or anywhere and also in host pointing to service from local namespace.
Create a DR in local namespace which does not have mTLS enabled, and pointing to the same local service.
Before, the validations does not include exported DRs from different namespace which have the same  host, only the 'default' DR:
Now, validations include cross namespace exported DRs as well:
=> Added support of exportTo field's validation for DestimationRule TrafficPolicyChecker.

hack/aws-openshift.sh
Trying to re-use the aws script.
=> hack: bump ocp version in aws helper script

GOVERNANCE.md
This is:
* Adding the `leader` and `tester` roles to the contributor ladder, which we have had for quite a long time. This is simply formalizing those roles.
* As they are "new", I tried to describe them based on how they current behave
* I added how to apply for these roles. This is mainly based on how to apply for the "maintainer" role. It's quite simplistic. Probably not everybody may agree but, if needed, I want to open here the discussion about if the step-in process makes sense.
* Added how to become an _Owner_ of the Kiali organization. I'm not sure if this is really right to mention.
* Updated channel to propose new contributors or changes to the governance: either by a PR or a GitHub discussion. This removes mentions to the already deprecated mail lists.
* Adding `Inactivity`, …
=> Contributor ladder update

hack/run-kiali.sh
need this to be able to use the script with vs-code debugging.
With this, you can use the VS code debugger to step through the kiali server.
Run this:
```
./hack/run-kiali.sh -kc current -es false -trd $HOME/tmp
```
And with this vs-code launch.json file (note - replace \<your-home-dir> with your user home directory):
```
{
// Use IntelliSense to learn about possible attributes.
// Hover to view descriptions of existing attributes.
// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
"version": "0.2.0",
"configurations": [
{
"name": "Launch Kiali",
"type": "go",
"request": "launch",
"mode": "debug",
"program": "kiali.go",
"cwd": "<your-home-dir>/tmp/run-kiali",
"args": ["-config", "<your-home-dir>/tmp/run-kiali/run-kiali-config.yaml"],
"env": { …
```
=> be able to tell the run-kiali-sh script where to write tmp files

util/httputil/http_util.go
Fixes args not being passed to `CreateTransport` correctly as a result of merging #4312.
=> Pass empty custom headers

business/workloads.go, kubernetes/cache/kubernetes.go, kubernetes/kubernetes.go
This PR aims to ensure that Kiali does not consider historical replicasets, and ignores their pods when "discovering" workloads.  Kiali identifies workloads using sort-of a bottom-up approach that starts with Pods and looks for thir owners. The owner can be a ReplicaSet. Our list of Pods is cached (as is our list of ReplicaSets) and I think what happens is that we get a cached pod for an old ReplicaSet. Our list of ReplicaSets contains all the ReplicaSets for the namespace, both active and inactive (note that inactive RS can result from Deployments that have revisionHistoryLimit > 0). So we can get a cached pod that is owned by an inactive ReplicaSet. For Kiali, I don't think old ReplicaSets for the same owner (Deployment) are useful. If we filter them away I think the related issue will …
=> Ensure only active ReplicaSets are returned from GetReplicaSets

business/checkers/destinationrules/no_dest_checker.go, business/checkers/destinationrules/no_dest_checker_test.go, business/checkers/no_service_checker.go, business/checkers/no_service_checker_test.go, business/checkers/service_entry_checker.go, business/istio_validations.go, tests/data/service_entry_data.go
RFE https://github.com/kiali/kiali/issues/3061
Subtask : https://github.com/kiali/kiali/issues/4316
On validation message "KIA0202 This host has no matching entry in the service registry (service, workload or service entries)" is now added a support of cross-namespace checking of ServiceEntries.
So create a ServiceEntry:
Before when linking from DR to that SE which was in different namespace, it was showing an error:
Now error on host is not shown:
But try to export SE into local namespace only:
The error is shown, as SE is not available into DR's namespace:
=> Added cross-namespace validation support on validation KIA0202 for exportTo field of ServiceEntry

business/dashboards.go, prometheus/client.go, prometheus/prometheustest/mock.go
fixes: https://github.com/kiali/kiali/issues/3704
This is trying to work around the problem where api.Series is being called during dashboard discovery, which could return a huge amount of data.
We want to only look for specific metric names - those metrics listed as "discoverOn" metrics in the dashboards. Those are the only ones we care about.
=> custom dashboard discovery - only look for discoverOn metrics

graph/telemetry/istio/appender/workload_entry.go, graph/telemetry/istio/appender/workload_entry_test.go
Ensure workload_entry appender does not process nodes outside of the requested namespace being processed by the appender.  When querying for istio config you may hit a "leaf" node (for the entire graph), that is inaccessible or excluded from the UI.
This issue was introduced in v1.40 with the new workload_entry appender.
Fixes https://github.com/kiali/kiali/issues/4384
To Recreate/Test:
1. install travel demo
2. select `travel-agency` namespace and verify graph includes incoming traffic from `travel-portal` nodes.  And that those `travel-portal` nodes are accessible (you can select, double-click, right-click etc).
3. update the  CR to exclude the `travel-portal` namespace
```
spec:
api:
namespaces:
exclude:
- istio-operator
- kube-.*
- openshift.*
- ibm.*
- kiali-operator
- travel-portal …
```
=> Ensure workload_entry appender does not process nodes outside of the requested namespace

graph/telemetry/istio/appender/istio_details.go, graph/telemetry/istio/appender/istio_details_test.go, graph/telemetry/istio/appender/service_entry.go
Istio appender was skipping further adding missing labels of ServiceEntries. Probably, it made sense at that moment that code was introduced. However, nowdays Istio doc tells that SE resources can be used to "decorate" services from other registries. See https://istio.io/v1.10/docs/reference/config/networking/service-entry/#ServiceEntry.
So, we no longer can simply skip adding missing labels for SEs. We should check if a SE is augmenting a regular service and add missing labels if needed.
Fixes kiali/kiali#4295.
=> Fix ServiceEntry not grouped in app box

business/dashboards.go, business/istio_certs_test.go, config/config.go, graph/config/cytoscape/cytoscape_test.go, kiali_api.md, models/dashboards.go, models/dashboards_test.go, swagger.json
Adding possibility to configure _additional_ label aggregations in metric tabs.
For example, a Kiali CR with the following configuration:
```yaml
spec:
kiali_feature_flags:
ui_defaults:
metrics_inbound:
aggregations:
- display_name: Istio Network
label: topology_istio_io_network
- display_name: Istio Revision
label: istio_io_rev
```
will generate the following options in the metrics menu:
Fixes kiali/kiali#2911.
=> Configurable label aggregations in metric tabs

business/checkers/authorization/no_host_checker.go, business/checkers/authorization/no_host_checker_test.go, business/checkers/authorization_policies_checker.go, business/istio_validations.go
RFE https://github.com/kiali/kiali/issues/3061
Subtask : https://github.com/kiali/kiali/issues/4316
On validation message of AuthorizationPolicy "KIA0104 This host has no matching entry in the service registry", is now added a support of cross-namespace checking of ServiceEntries.
With created ServiceEntry:
AuthorizationPolicy was not supporting cross-namespaces validations:
Now it supports:
And when wrong host is set in "to" field, it shows a error:
=> Added cross-namespace support for ServiceEntry in AuthorizationPolicy validations

graph/config/cytoscape/cytoscape.go, graph/config/cytoscape/cytoscape_test.go, graph/telemetry/istio/appender/workload_entry.go, graph/telemetry/istio/appender/workload_entry_test.go, graph/types.go, kiali_api.md, swagger.json
Adds all the found `WorkloadEntries` to the associated node's metadata.
Relates to #kiali#4219
Front end: kiali/kiali-ui#2241
=> Add all associated WorkloadEntries to node metadata

business/workloads.go, business/workloads_test.go
When composing the workloads response, assume that if the controller is a type unknown to Kiali, the workload is directly controlling the pods i.e. the pods have an owner ref to the workload type.
Fixes #3733
=> Handle workloads with direct pod controllers

business/apps.go, business/services.go, kubernetes/filters.go, kubernetes/filters_test.go
RFE https://github.com/kiali/kiali/issues/4326
When VirtualService have linked Gateways, then these Gateways are listed in Details column of ServiceLists and AppLists pagea.
Also Services they can be filtered by Gateways.
Gateways can be linked for instance while creating Routing via Wizard.
=> Gateways linked in VirtualServices are listed in Service/App Lists 'Details' columns.

business/checkers/gateways/multi_match_checker.go, business/checkers/gateways/multi_match_checker_test.go
This PR makes sure that `port` is set if `intutil.Convert` successfully converts the port from the server definition (no errors), rather than only setting it when it can't convert the port.
Added a test for servers with the same host but different ports, asserting that it is considered valid.
Resolves #4466
=> Set port correctly when validating more than one Gateway for the same host port combination

config/config.go
This PR adds a similar function than "isIstioNamespace" but for the administrative root namespace.
Requires [#441](https://github.com/kiali/kiali-operator/pull/441)
Requires [#114](https://github.com/kiali/helm-charts/pull/114)
Resolves #4448
If not configured, the root namespace will be "istio-system".
Note: This is an alternative solution to #4448 comparing to #4447
=> New function to check if namespace is the root namespace

business/checkers/service_entry_checker.go, business/checkers/serviceentries/workload_entry_address_match.go, business/checkers/serviceentries/workload_entry_address_match_test.go, business/istio_validations.go, models/istio_validation.go, tests/data/validations/serviceentries/workload_entry_address_match.yaml, tests/testutils/validations/fixture_loader.go
fix https://github.com/kiali/kiali/issues/4339
Adding validation on ServiceEntries.Addresses field. There should be list all the addresses from all Workloads matching ServiceEntry.workloadSelector labels.
I've prepared a yaml with tests that might help the testing:
https://github.com/kiali/kiali/pull/4489/files#diff-22ff27b34bdc7a01afc5a03561bbaa6b48c3e8e2fcebf70b247587a40ebc65cd
=> Service Entry validation: SE must have listed all address from its matching WorkingEntries

graph/config/cytoscape/cytoscape.go, graph/meta.go, graph/telemetry/istio/appender/istio_details.go, kiali_api.md, swagger.json
This adds the list of configured hosts to the metadata of graph nodes detected as egress gateways. This allows the UI to show the configured hosts in the topology graph.
Related #3765.
=> Hostnames for egress gateways nodes

tests/e2e/tests/test_api_methods.py
/api/namespaces/istio-system/services/invalid
Changed from 404 to 502
fixed these test cases
tests.test_api_methods.test_invalid_service_traces_list_negative_503
tests.test_api_methods.test_invalid_service_spans_list_negative_503
=> E2E: fix_upstream_api

business/checkers/services/port_mapping_checker.go, business/checkers/services/port_mapping_checker_test.go, kubernetes/istio.go, kubernetes/istio_test.go, models/istio_validation.go, models/port.go, swagger.json
Fix for https://github.com/kiali/kiali/issues/4486
The https://kiali.io/docs/features/validations/#kia0601---port-name-must-follow-protocol-suffix-form validation was checking only the port name in protocol [-suffix] format, but name can be not in that format and instead appProtocol parameter has the format of protocol. As described in https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#explicit-protocol-selection.
So now these both formats of ports are correct for Services. 
```
ports:
- port: 9080
name: http-correct
- port: 3306
name: database
appProtocol: http
```
=> While validating port name in Services, consider also appProtocol parameter's value.

business/checkers/sidecars/global_checker.go, business/checkers/sidecars/global_checker_test.go
This PR updates the global sidecar validation to honor the root namespace instead of the istio namespace.
Depends on #4465 
Fixes #4449
In the following example, the global validation applies to the Sidecar created in istio-config namespace (the root namespace).
=> Global sidecar validation using the root namespace 

business/checkers/peer_authentication_checker.go, business/istio_validations.go, business/tls.go
This PR updates the peer authentication validations to honor the root namespace instead of the istio namespace.
Depends on #4465
Fixes #4450
=> Peer authentication validations using the root namespace

business/checkers/virtual_service_checker.go, business/checkers/virtualservices/route_checker.go, business/checkers/virtualservices/route_checker_test.go, models/istio_validation.go
Fix for https://github.com/kiali/kiali/issues/4458.
Create a VS without a subsets in route, like this:
```
route:
- destination:
host: reviews
weight: 80
- destination:
host: reviews.bookinfo2.svc.cluster.local
weight: 10
- destination:
host: reviews.bookinfo.svc.cluster.local
weight: 10
```
Before it was showing warning message in wrong place because validation was tightened to only subset:
Now it validates host+subset combination and considers host in fqdn and puts validation message on the host line:
=> While validating VS subsets repeatings, consider hosts and subset combinations

config/config.go, kubernetes/istio.go
Because sometimes people need to change the monitoring port on the IstioD pod when using host network mode.
Operator PR: https://github.com/kiali/kiali-operator/pull/455
Fixes kiali/kiali#4462
=> Add configuration for IstioD pod monitoring port

business/checkers/authorization/no_host_checker.go, business/checkers/destinationrules/no_dest_checker.go, business/checkers/destinationrules/no_dest_checker_test.go, business/checkers/no_service_checker.go, business/checkers/no_service_checker_test.go, business/checkers/virtualservices/no_host_checker.go, business/checkers/virtualservices/no_host_checker_test.go, business/istio_validations_test.go, business/services.go, kubernetes/filters.go, kubernetes/host.go, tests/data/service_data.go
RFE #3061 
Subtask: https://github.com/kiali/kiali/issues/4317
In NoHostChecker of VirtualService, now it supports exported Services from other namespaces set into route -> destination -> host.
Exporting of Service is done via "networking.istio.io/exportTo" annotation on Service in Kubernetes.
Before, it was showing message that cross-namespace validations for hosts are not supported:
Now if Service is available it does not show any warning or error:
But when Service is exported only to own namespace, thus not available in other namespaces, error is shown on hosts of VS:
=> Added support of exported Services into VirtualService validation NoHostChecker

hack/ci-openshift-molecule-tests.sh
need to override GOPATH wherever it is used because it needs to point to the location where the script clones the kiali repo.
=> [hack] set GOPATH appropriately so kiali exe can be found

kubernetes/cache/cache.go, kubernetes/cache/cache_test.go
regex.Compile is quite expensive and was previously called once per
namespace. This change instead compiles the namespace regexes once at cache instantiation.
Fixes https://github.com/kiali/kiali/issues/4590
no
Shouldn't be necessary IMHO
=> Compile namespace regex when instanciating cache

graph/config/cytoscape/cytoscape.go
Closes https://github.com/kiali/kiali/issues/4547
Omit boxes when there is only one member, or only one discriminating value in the graph (i.e. one namespace or one cluster).
Also, never box `unknown`.
Because boxing is now a bit lighter, and it is common to enable boxing, the UI PR makes an additional change and enables cluster and namespace boxing by default.
**UI PR:** https://github.com/kiali/kiali-ui/pull/2277
=> Remove unnecessary graph boxes

business/tls.go, business/tls_perf_test.go, business/tls_test.go, kubernetes/cache/istio_test.go, kubernetes/cache/tls_test_helper.go, kubernetes/filters.go
Fixes https://github.com/kiali/kiali/issues/4224
Improve the getAllDestinationRules to use the AllNamespaces flag that queries directly the Istio Registry to collect the DestinationRules needed for this cross-namespace validation.
It's still in a draft mode, tests need to be updated and registry cache can be indexed per type to reduce the O(N) -> O(1) using memory.
Also related with https://github.com/kiali/kiali/discussions/4509 discussion
=> Use AllNamespaces flag in IstioConfig for TLS validation

business/checkers/sidecars/egress_listener_checker.go, business/checkers/sidecars/egress_listener_checker_test.go, business/checkers/sidecars_checker.go, business/istio_validations.go
RFE https://github.com/kiali/kiali/issues/4546
Sidecar's egress listener host now supports checking services from current namespaces and exported services from Registry.
So when service from different namespace is exported to all namespaces. then host "productpage.bookinfo2" is recognized.
But try to export the 'productpage.bookinfo2' Service into namespaces other than 'bookinfo', then the 'bookinfo' namespce's Sidecar's host will fail to recognize the service from different namespace.
=> Added support of Exported Registry Services in Sidecar's host egress listener checker.

business/checkers/gateways/multi_match_checker.go
When checking for duplicate hosts, `regexp.Compile()` is currently called twice per comparison. This is a costly operation, which is fine for clusters with few gateway hosts. In our setup we heavily utilize the namespacing of hosts, though, so we have many repeating host entries, causing many regexp Compilations on the same hosts.
This PR implements a caching mechanism for compiled `regexp.Regexp` that lives as long as the Validation is running. The change heavily reduces CPU load in our setup, and should have minimal impact on memory.
In this change I also extracted the String manipulations for converting hosts to regexes into their own function and found, that the replacement of `*` -> `.*` was never actually used in the regex and had no effect, so I removed it …
=> Cache compiled regexes in multi match checker

business/checkers/destinationrules/no_dest_checker.go, business/checkers/virtualservices/no_gateway_checker.go, business/checkers/virtualservices/no_host_checker.go, business/checkers/virtualservices/subset_presence_checker.go, business/istio_config_test.go, graph/telemetry/istio/appender/istio_details.go, graph/telemetry/istio/appender/istio_details_test.go, kubernetes/filters.go, kubernetes/istio_test.go, models/destination_rule.go
Badging of VSs was assuming that Istio VirtualServices resources and graph service nodes belong to the same namespace. This is not necessarily true. This fixes VS badging to take into account that a VS can route to a Service in another namespace.
Fixes #4541
=> Fix VS badging

make/Makefile.build.mk
**Describe the change** 
add --no-open flag to fix no screen found error
**Issue reference** 
``` bash
The swagger spec at "./swagger.json" is valid against swagger specification 2.0
webbrowser: tried to open "http://localhost:44497/docs", no screen found
make: *** [make/Makefile.build.mk:110: swagger-serve] Error 1
```
=> fix(swagger): add --no-open flag to fix no screen found error

make/Makefile.build.mk
fix: remove -i flag for its deprecated
The -i flag is deprecated. Compiled packages are cached automatically.
=> fix: remove -i flag for its deprecated

business/apps.go, handlers/apps_test.go, handlers/health_test.go
Fix for issue https://github.com/kiali/kiali/issues/4608
Before Kiali was loading Services for App pages by "app" label name using in Service selector, and in a case when AppLabelName and Service selector were not equal, the Services for App details page was showing empty.
Now with this change the Workloads for App are loaded first, then per workload the Services are loaded by using Workload labels as Service Selector.
One thing in this PR to discuss is loading Services in the loop of workloads then adding them into Service list of results after checking their duplicity.
=> Changed the loading App to first load Workloads then Services.

business/apps_test.go, business/health_test.go, business/istio_validations_test.go, business/mesh.go, business/mesh_test.go, business/registry_status.go, business/services.go, business/services_test.go, graph/telemetry/istio/appender/health_config_test.go, handlers/apps_test.go, handlers/health_test.go, tests/data/registry/istio-east-registryz.json
Fixes https://github.com/kiali/kiali/issues/4570
This PRs address two potential problems:
- During Istio Registry call, the assignment is protected but not the call to registry, so due https://github.com/istio/istio/issues/36448 now the refresh operation should be protected.
- In multi-cluster scenarios, the Istio Registry replicates the Kubernetes services, so, Istio registry services should be filtered to only used based on the istiod cluster he is connected to (probably this needs to be revisited when a Kiali instance may connect multiple control planes).
How to test:
- This issue requires a multi-cluster setup in https://github.com/kiali/kiali/discussions/3699 there are some good helpers to define one in minikube.
- Create a namespaces in both istio-east and istio-west, populates only …
=> Fix Service list bug on multi-cluster scenarios

business/workloads.go, business/workloads_test.go, kubernetes/filters.go, kubernetes/filters_test.go
When fetching workloads, Kiali should match the replicaset owner ref's full name instead of relying on a prefix.
Fixes #4477
=> Filter pods based on full owner ref name

business/checkers/authorization/mtls_enabled_checker.go, business/checkers/authorization_policies_checker.go, business/istio_validations.go, business/istio_validations_test.go, business/tls.go, kubernetes/filters.go, kubernetes/filters_test.go, util/mtls/status.go
RFE https://github.com/kiali/kiali/issues/4546
Depends on https://github.com/kiali/kiali/pull/4536
What is changed in AuthorizationPolicy validations:
It now supports exported DestinationRules belonging to Services from different namespaces alongside with local namespace's Services and DestinationRules.
Originally mTLS validation functionality was added in PR https://github.com/kiali/kiali/pull/2938
=> Consider Registry Services in Workload MTLS Status check alongside with local namespace Services.

.github/workflows/config/.golangci.yml, .github/workflows/kiali-ci.yml, business/checkers/destinationrules/traffic_policy_exported_checker_test.go, business/checkers/peerauthentications/disabled_namespacewide_checker.go, business/istio_config.go, business/istio_config_test.go, business/istio_validations_test.go, business/jaeger_test.go, business/services_test.go, business/tls_perf_test.go, business/tls_test.go, jaeger/client.go, kubernetes/cache/istio_test.go, kubernetes/cache/tls_test_helper.go, kubernetes/kubetest/mock_istio.go, make/Makefile.build.mk, models/endpoint.go, models/port.go, models/service.go, tests/data/virtual_service_data.go
Adds `goimports` to the list of linters run by CI. This detects that the imports are sorted properly for most cases.
Fixes #4442
=> Use goimports for linting in CI

jaeger/http_client.go
Fixes https://github.com/kiali/kiali/issues/4636
When using the HTTP configuration to access jaeger from Kiali:
```
tracing:
enabled: true
in_cluster_url: http://localhost:16686/jaeger
url: http://localhost:16686/jaeger
port: 443
service: jaeger-query
```
There was a bug when access to a trace detail, the base URL was overwritten, which produced that following queries would fail. The problem is only visible in the HTTP mode, not GRPC.
=> Fix wrong pointer in jaeger http client

doc.go, kiali_api.md, swagger.json
(a) what is broken or missing?
In app and versionApp graph
+ graphType is required 
+ workload and service are not supported types 
(b) what the new code is doing to fix it?
separate graphApp graphAppVersion from graphParam and create a new param for app.
=> fix(app/versionApp): graphType is required and types are different

doc.go, kiali_api.md, swagger.json
(a) what is broken or missing?
validate query is missing in some routes: `istioConfigList, istioConfigDetails, serviceDetails, serviceUpdate`
(b) what the new code is doing to fix it?
add missing validate query in swagger and update swagger.json
=> sync(validate): add validate query in swagger

business/checkers/virtualservices/no_gateway_checker.go, business/checkers/virtualservices/no_gateway_checker_test.go
Fix for https://github.com/kiali/kiali/issues/4645
Create VS and add 2 non existing Gateways into spec, before it was showing error message only on first one.
Now all non existing Gateways get error messages:
=> Show all non existing Gateways errors in VirtualServices

business/checkers/authorization_policies_checker.go, business/checkers/destination_rules_checker.go, business/checkers/destinationrules/multi_match_checker.go, business/checkers/destinationrules/multi_match_checker_test.go, business/checkers/destinationrules/multi_match_exported_checker_test.go, business/checkers/no_service_checker.go, business/checkers/sidecars_checker.go, business/checkers/virtual_service_checker.go, business/checkers/virtual_service_checker_test.go, business/checkers/virtualservices/single_exported_host_checker_test.go, business/checkers/virtualservices/single_host_checker.go, business/checkers/virtualservices/single_host_checker_test.go, business/checkers/virtualservices/subset_presence_checker.go, business/checkers/virtualservices/subset_presence_checker_test.go, business/istio_validations.go, business/istio_validations_test.go, business/mesh_test.go, kubernetes/cache/registry_test_helper.go, kubernetes/types.go
As now the exported resources contains all objects, skip using Istio Objects from IstioConfigList for local namespace.
Exported resources fortains Istio Objects from IstioConfigList for AllNamespaces, so using any other list will cause duplicates.
Fix for issue https://github.com/kiali/kiali/issues/4641
For QE:
Full manual regression testing is required for VirtualServices, DestinationRules and ServiceEntries validations from https://kiali.io/docs/features/validations/
Full UI/E2E automation regression testing is required.
=> Removed duplications for VS, DR and SE in Istio Validations.

business/services.go
Related to https://github.com/kiali/kiali/issues/4589 and https://github.com/kiali/kiali-ui/pull/2283
A regression was introduced as the services linked with a workload were reset to a nil pointer instead of an empty list when a workload has no services.
=> Fix empty service list instead of nil value

go.mod, go.sum
I'm not an expert in gomod changes.  I added an entry for the desired version of golang.org/x/crypto.  The resulting go.sum has the bew version, along with older versions as well.  I did build successfully (required some go installs) and a smoke test seemed ok.
https://issues.redhat.com/browse/OSSM-873
=> bump version of golang.org/x/crypto

tests/e2e/tests/test_api_methods.py
https://github.com/kiali/kiali-operator/pull/475.
Iter8 feature has been deleted, that is the resaon. removed that API from test run
=> E2E: Removed_Iter8 api

business/checkers/authorization_policies_checker.go, business/checkers/destination_rules_checker.go, business/checkers/service_entry_checker.go, business/checkers/sidecars_checker.go, business/istio_validations.go
Use single list of ServiceEntries retrieved from Registry for validations.
For QE: Regression testing of automations is required.
Manual regression testing of Istio Validations related to ServiceEntries https://kiali.io/docs/features/validations/
=> Use ServiceEntries from Istio Registry in validations.

config/token.go, handlers/authentication_test.go, kiali.go, kiali_test.go
This is to support sessions with AES-GCM encryption.
Related to #4542
=> Enforce specific lengths for signing key

business/checkers/authorization/no_host_checker.go, business/checkers/authorization/no_host_checker_test.go, business/checkers/authorization_policies_checker.go, business/checkers/no_service_checker.go, business/checkers/virtualservices/no_host_checker.go, business/checkers/virtualservices/no_host_checker_test.go, business/istio_validations.go, business/istio_validations_test.go, kubernetes/cache/registry_test_helper.go, tests/data/service_data.go, tests/data/virtual_service_data.go
Changed several validations to use ServiceRegistry Instead of ServiceList to decrease the validation time and optimize the validation logic
Touched validation messages:
AuthPolicy: "KIA0104 This host has no matching entry in the service registry"
VirtualService: "KIA1101 DestinationWeight on route doesn't have a valid service (host not found)"
Full regression testing is required for those validations.
Regression testing is required for all other validations.
=> Replace ServiceList usage by RegistryServices

business/checkers/authorization_policies_checker.go, business/checkers/destination_rules_checker.go, business/checkers/destinationrules/multi_match_checker.go, business/checkers/destinationrules/multi_match_checker_test.go, business/checkers/destinationrules/multi_match_exported_checker_test.go, business/checkers/destinationrules/traffic_policy_checker.go, business/checkers/destinationrules/traffic_policy_checker_test.go, business/checkers/destinationrules/traffic_policy_exported_checker_test.go, business/checkers/virtual_service_checker.go, business/checkers/virtual_service_checker_test.go, business/checkers/virtualservices/single_exported_host_checker_test.go, business/checkers/virtualservices/single_host_checker.go, business/checkers/virtualservices/single_host_checker_test.go, business/checkers/virtualservices/subset_presence_checker.go, business/checkers/virtualservices/subset_presence_checker_test.go, business/istio_validations.go
Replaced ExportedDestinationRules variable with DestinationRules param is coming from Registry and includes local and exported ones.
Update: Did the same for ExportedVirtualServices.
For QE:
Full manual regression testing for all Destination Rules and Virtual Services validations from https://kiali.io/docs/features/validations/
Automation regression testing.
=> Replaced ExportedDestinationRules variable with DestinationRules.

business/checkers/sidecars/egress_listener_checker.go, business/checkers/sidecars/egress_listener_checker_test.go, business/checkers/sidecars_checker.go, business/istio_validations.go
Modified the EgressHostChecker to use Services from Registry instead of only local namespace ones.
So now it supports exported Services as well.
The affected validation message is:
"KIA1004 This host has no matching entry in the service registry"
For QE:
Test the https://kiali.io/docs/features/validations/#kia1004---this-host-has-no-matching-entry-in-the-service-registry
Sidecar in "bookinfo", but using host from different namespace, for instance "bookinfo2/reviews.bookinfo2.svc.cluster.local".
Then "reviews/bookinfo2" service export to "bookinfo3" (Service annotation "networking.istio.io/exportTo") and verify that Sidecar host shows warning.
=> Sidecar EgressChecker now supports Services from Registry.

business/checkers/authorization/mtls_enabled_checker.go, business/checkers/authorization/mtls_enabled_checker_test.go, business/checkers/authorization/no_host_checker.go, business/checkers/authorization/no_host_checker_test.go, business/checkers/authorization_policies_checker.go, business/checkers/destinationrules/no_dest_checker.go, business/checkers/destinationrules/no_dest_checker_test.go, business/checkers/no_service_checker.go, business/checkers/no_service_checker_test.go, business/checkers/sidecars/egress_listener_checker_test.go, business/checkers/virtualservices/no_gateway_checker.go, business/checkers/virtualservices/no_host_checker.go, business/checkers/virtualservices/single_host_checker.go, business/istio_validations.go, business/istio_validations_test.go, kubernetes/cache/registry_test_helper.go, kubernetes/host.go, tests/data/service_data.go, tests/testutils/validations/fixture_loader.go, util/mtls/status.go
Replaced ServiceList by RegistryServices in all remaining validations.
For QE:
Full regression testing of validations. https://kiali.io/docs/features/validations/
UI and e2e  automations run.
=> Remove Service list usage by RegistryServices in validations

make/Makefile.operator.mk
This is needed to help workaround this [issue](https://github.com/kiali/kiali/issues/4691) which does not yet have a solution.
=> [make] add target to restart the operator pod

business/layer.go, kubernetes/cache/cache.go, server/server.go
Fixes https://github.com/kiali/kiali/issues/4502
Suggested test plan (QE @skondkar):
- This PR shouldn't change the current behavior from the user's perspective, it can be tested validating that when the Kiali server starts (with NO access from the UI, just deployment), the log should show that the Kiali has been populated.
- A basic access to the Overview page should be enough to validate regressions.
=> Init Kiali Cache on Server startup

status/versions.go, status/versions_test.go
_Please describe what the code change is about._
istio dev version has dev prefix like this:
`1.10-dev-65a124dc2ab69f91331298fbf6d9b4335abcf0fd-Clean`
_Please, provide the link to the GitHub issue here._
_describe the changes if appropriate._
If so, please also update [README.adoc](README.adoc)
=> fix: add dev to istioDevVersionExpr

go.mod, go.sum
Protobuf version upgraded to v1.3.2 due to vulnerabilities.
The testing I did was:
- Install v1.36 with Istio 1.9 
- Install bookinfo demo
- Check that traffic is generating traces
- Check that the traces are accessible from Kiali
=> [v1.36] Protobuf version upgraded to v1.3.2

business/workloads.go
The excluded type(s) adding to controllers seems to cause "xxx is not found as xxx" issue.  
Let's take job type as an example. As it is excluded, the job array remains empty:
``` go
// business/workloads.go
var jbs []batch_v1.Job  // line 593
go func() {  // line 709
defer wg.Done()
var err error
if isWorkloadIncluded(kubernetes.JobType) { // job type is excluded, condition is not met
jbs, err = layer.k8s.GetJobs(namespace)
if err != nil {
log.Errorf("Error fetching Jobs per namespace %s: %s", namespace, err)
errChan <- err
}
}
}()
```
And the "is found" validation will always return false, which cause the  "xxx is not found as xxx" issue:
``` go
// business/workloads.go
case kubernetes.JobType:  // line 1048
found := false
iFound := -1
for i, jb := range jbs {
if jb.Name == cname { …
```
=> Fix "xxx is not found as xxx" issue

Makefile, README.adoc, deploy/get-console.sh, hack/ci-openshift-molecule-tests.sh
Minor fix to the console path
Follow these commands in README:
``` bash
mkdir kiali_sources
cd kiali_sources
export KIALI_SOURCES=$(realpath .)
git clone https://github.com/kiali/kiali.git
git clone https://github.com/kiali/kiali-ui.git
git clone https://github.com/kiali/kiali-operator.git
git clone https://github.com/kiali/helm-charts.git
ln -s $KIALI_SOURCES/kiali-operator kiali/operator
cd $KIALI_SOURCES/kiali
make build test
cd $KIALI_SOURCES/kiali-ui
yarn && yarn build && yarn test
```
When we run `make container-build` :
```
❯ make container-build
CONSOLE_DIR is /root/github.com/kiali_sources/kiali/../../../../../kiali-ui
Apparently, this CONSOLE_DIR does not contain the kiali-ui
make: *** …
```
=> fix: remove extra path in console local dir

go.mod, go.sum, graph/config/cytoscape/cytoscape_test.go, tools/README.md, tools/cmd/generate/main.go, tools/cmd/proxy/main.go, tools/cmd/util.go, tools/generator/generator.go, tools/generator/options.go
The generator creates a very basic graph but has a few configurable knobs. This was primarily tested with [this patch](https://github.com/nrfox/kiali/compare/kiali-4585...nrfox:patch-graph-generator?expand=1) but the eventual goal is to use something like cypress from https://github.com/kiali/kiali-ui/pull/2264 when it's ready to mock out the request and return the json data generated by the generator.
Also adds a simple proxy server to serve the generated graph data from memory. See [here](https://github.com/kiali/kiali/blob/d5ee726d0859886cd978cd74a9d3a3e37344f87d/tools/README.md) for instructions on running/testing both.
Sample output:
Relates to #4585
=> Add graph generator for creating mock graph data

graph/finalizer.go, graph/options.go, graph/telemetry/common.go, graph/telemetry/istio/finalizer/finalizer.go, graph/telemetry/istio/finalizer/outsider.go, graph/telemetry/istio/finalizer/traffic_generator.go, graph/telemetry/istio/istio.go
This is pure code organization at the moment.  But I think it may be useful for some of the
projected features.  I am tying this to a current epic, which likely
will want to add k8s label info to graph nodes. This could be done in
an appender, but may lend itself better to being done one time, at the end.
Even if we don't add more finalizers, it's still not a bad thing.  There
isn't really a perf hit and I think it adds some structure.
relates to https://github.com/kiali/kiali/issues/4605
=> Add Finalizers to the graph generation architecture

hack/istio/install-bookinfo-demo.sh
This allows you to re-run the script to re-deploy things that may not have installed correctly the first time (which happens to me when I forget to specify the minikube profile that causes the traffic generator to fail installation).
=> [hack] install bookinfo - use apply instead of create

business/dashboards.go, business/dashboards_test.go, config/config.go
Fixes https://github.com/kiali/kiali/issues/4769
Istio 1.13.x ships Prometheus v2.31.1 (chart 1.15) (vs Istio 1.12/Prometheus v2.26.0 - chart 1.14 -).
Prometheus v2.31.1 has introduced an alignment in the labels of the "kubernetes_pod" job, that affects the "namespace" label used in the CustomDashboards (also used by the Envoy subtab) [1].
[1] https://github.com/prometheus/prometheus/pull/9832
By default, CustomDashboards have the "kubernetes_namespace" label that needs to change to "namespace" in custom queries.
With this change, the custom dashboards work as expected.
This PR is not yet finished, it's just a draft to give visibility, it needs to apply the change into the tests and other places.
I think that the defaults should point to the default version this targets (Istio 1.13.x, …
=> Align namespace label in custom dashboards

kubernetes/istio.go
Fix for https://github.com/kiali/kiali/issues/4711
When there are multiple istiod pods, Registry Services and Configs were loading multiple times, so causing duplicates and odd errors in validations.
Now Registry Configs and Services are loaded only for the first istiod pod.
For QE:
Increase istiod pods count.
List istio configs for bookinfo.
Before: all configs were having warnings and references to themselves.
Now: no additional warnings and duplicate references in configs.
=> Single loading of multiple istiod registry services and configs

business/apps.go, business/apps_test.go, handlers/apps.go
Related to https://github.com/kiali/kiali/pull/4755#discussion_r818643828 discussion.
GetServiceList, GetWorkloadList, GetIstioConfigList were moved to use a "criteria" parameter to define what elements are needed.
GetAppList was missing, but in the context of the graph appender can be used like this:
https://github.com/kiali/kiali/blob/master/graph/telemetry/istio/appender/appender.go#L239
https://github.com/kiali/kiali/blob/master/graph/telemetry/istio/appender/appender.go#L279
=> Add an AppCriteria to GetAppList for consistency

models/istio_validation.go, models/istio_validation_test.go
Fix for https://github.com/kiali/kiali/issues/4766
UI changes are required: https://github.com/kiali/kiali-ui/pull/2315
Before, it was generating validation result JSON with config  'type' and 'name' in a key. So for multiple namespaces having similar config names were causing overriding the key in map, thus confusion is UI.
Now, it uses config's 'name.namespace' as a key, to make sure multiple namespaces are supported.
For QE:
Create 'bookinfo', 'bookinfo2' and 'bookinfo3' namespaces.
Make sure that several configs in 'bookinfo' only is broken, so contains warnings and errors.
List all istio configs for all namespaces.
Refresh the content several times.
Verify that all configs configuration statuses are consistent within all refreshes.
=> For Istio Config validations result JSON, make the key 'name.namespace' instead of 'name' only to support multiple namepaces

business/checkers/services/port_mapping_checker.go, business/checkers/services/port_mapping_checker_test.go
Fixing https://github.com/kiali/kiali/issues/4764.
For the Services in istio-system control plane namespace, skip "KIA0701 Deployment exposing same port as Service not found" validation.
But keep it for other namespaces.
For QE:
In "istiod", "tracing" and other Services from istio-system namespace, verify that validation warning "Deployment exposing same port as Service not found" is not shown.
Before:
After:
Regression test if Services from other nemaspaces continue getting validation warning: https://raw.githubusercontent.com/Kiali-QE/kiali-qe-python/master/data/resources/istio_objects/validation/ratings_java_svc.yaml
=> Skip KIA0701 Port missmatch validation check for Services in istio-system namespace.

handlers/config.go
Prometheus deprecated "storage.tsdb.retention" many versions back, and
it is no longer valid.  Unfortunately it is still set, but to 0, invalidating
this information in serverConfig.  Switch to "storage.tsdb.retention.time",
the valid setting.  Also, add a check to ensure this setting is never 0.
Furthermore, ensure that if all fails we provide a valid default to
consumers of the config.
Fixes https://github.com/kiali/kiali/issues/4784
=> Fix Prometheus TSDB retention config

business/istio_validations.go, business/references/auth_policy_references.go, business/references/auth_policy_references_test.go, business/references/destination_rule_references.go, business/references/destination_rule_references_test.go, business/references/gateway_references.go, business/references/peer_auth_references.go, business/references/peer_auth_references_test.go, business/references/service_entry_references.go, business/references/service_entry_references_test.go, business/references/sidecar_references.go, business/references/sidecar_references_test.go, business/references/virtual_service_references.go, business/references/virtual_service_references_test.go, tests/data/references/auth-policy.yaml, tests/data/references/destination-rule.yaml, tests/data/references/multiple-gateways.yaml, tests/data/references/peer-auth-drs.yaml, tests/testutils/validations/fixture_loader.go
RFE https://github.com/kiali/kiali/issues/2447
AuthorizationPolicy objects, added references to Workloads, Services, ServiceEntries and VirtualServices.
ServiceEntry objects, added references to AuthorizationPolicies and DestinationRules.
Sidecar objects, references to Workloads, Services and ServiceEntries.
PeerAuth objects, references to DestinationRules and Workloads.
UI changes are required for testing: https://github.com/kiali/kiali-ui/pull/2299
=> Added references in PeerAuth, AuthPolicy, ServiceEntry and Sidecar.

business/istio_config.go, business/istio_config_test.go, handlers/istio_config.go, kiali_api.md, routing/routes.go, swagger.json
Fix for https://github.com/kiali/kiali/issues/4692
It used to list Gateways per Namespace in Service Details page for Wizzard.
Now there is a new API "/api/istio" for listing Istio Configs for All Namespaces.
This PoC has a weakness:  Listing Gateways for All Namespaces means listing them from Registry, and it returns all Configs, not only Gateways.
=> Added new API endpoint to list all Istio Configs for All Namespaces

config/config.go, handlers/istio_config.go, kiali_api.md, models/istio_config.go, swagger.json
Work in progress.
Required by [#2299](https://github.com/kiali/kiali-ui/pull/2299).
When fetching the Istio config details for some config object, a new parameter can be configured to get help for some key object fields:
`http://localhost:20001/api/namespaces/bookinfo/istio/virtualservices/bookinfo?validate=true&help=true`
Then, this information can be displayed alongside the YAML to help the users to understand some important fields.
=> Help messages for some key fields in Istio config details method

routing/router.go
I found this by accident when I happened to read this code. We should fix this - no sense getting the config again when we already have it.
=> use the config var - don't Get() again

hack/purge-kiali-from-cluster.sh
This fixes the problem where the cluster resources aren't purged when on non-OpenShift but -c kubectl is not specified.
You now are told that -c kubectl is needed.
=> [hack] do not allow using 'oc' if not logged in or not talking to OpenShift.

hack/ci-kind-molecule-tests.sh
Hopefully, this will fix the failing molecules in GHActions.
---
Prefer a tagged version instead of master.
This is also removing the creation of a secret, which is no longer
needed (it is created automatically).
=> Use a tagged version of metallb

hack/istio/multicluster/start-kind.sh
Missing commit of #4821 - because GitHub's status degraded and it didn't include this when merging.
=> Feedback: Also use tagged version of metallb for multi-cluster scripts

Makefile, README.adoc, make/Makefile.ui.mk
This is for developers who are not familiar with (or who forget :) the proxy setting and where/how to set it in the package.json. You just have to provide your server URL via `-e YARN_START_URL` such as `make -e YARN_START_URL="http://localhost:20001" yarn-start`. Once that updates the package.json it will invoke `yarn start`. You won't have to set that env var thereafter unless you reset package.json. If the package.json already has a proxy setting, the env var is ignored. You can just run `make yarn-start` in that case.
Here is how to test. Get a cluster up with istio installed. Then run the "run-kiali.sh" hack script to start the server.  Then run this make target to start a ui via yarn start.  At this point, you have a development environment of both the backend (you can use a …
=> [make] provide a make target to allow for an easy way to "yarn start"

business/checkers/gateway_checker.go, business/checkers/gateways/selector_checker.go, business/checkers/gateways/selector_checker_test.go, business/istio_validations.go, business/mesh.go, business/mesh_test.go
Solution for https://github.com/kiali/kiali/issues/3408.
When istiod deployment has env variable PILOT_SCOPE_GATEWAY_TO_NAMESPACE= true, then a gateway workload can only select gateway resources in the same namespace. Gateways with same selectors in different namespaces will not be applicable.
Before
After
=> Added a support of istiod's PILOT_SCOPE_GATEWAY_TO_NAMESPACE env variable

business/authentication/auth_controller.go, business/authentication/openid_auth_controller.go, business/authentication/openshift_auth_controller.go, business/authentication/token_auth_controller.go, handlers/authentication.go
Refactor the OpenShift strategy to use the "auth controller" form. This moves it away from the dgrijalva/jwt library
Related to #4542
=> Refactor OpenShift auth to stop using the dgrijalva/jwt library

kubernetes/istio.go
Fixes https://github.com/kiali/kiali/issues/4892
@lucasponce I'm not as familiar with this code as you, but this seems to be the root of a UI crash I've been getting, as described in the issue.  Please take a look.  If this is in fact a desierd fix, I think we may need a 1.48 backport.
=> make sure RegistryConfiguration is initialized with empty arrays.

hack/istio/install-error-rates-demo.sh
The hack for the error-rates demo missed the "NetworkAttachmentDefinition" for OpenShift environments.
=> Fix install-error-rates-demo hack

.github/workflows/kiali-ci.yml, Makefile, make/Makefile.build.mk
Run backend integration tests as part of upstream CI. Runs as a separate job with a separate e2e env in parallel with the frontend integration tests. Builds PR go binaries with the `-race` flag for race detection while running tests. Releases won't be built with this flag since there is a perf penalty associated with it.
Fixes #4874
=> Run backend integration tests in CI

.github/workflows/kiali-ci.yml, README.adoc, make/Makefile.ui.mk
Adds a make command for cypress and tweaks some cypress settings in CI to reduce memory consumption (and hopefully speed up tests).
Config reference: https://docs.cypress.io/guides/references/configuration#Global
> The number of tests for which snapshots and command data are kept in memory. Reduce this number if you are experiencing high memory consumption in your browser during a test run.
Removes screenshots/videos from CI to save on GH resource consumption.
=> Add make cmd for cypress and reduce mem usage in CI

deploy/jenkins-ci/Jenkinsfile, deploy/jenkins-ci/Makefile
Jenkins was still using the kiali/kiali-ui repo and bundling that. These
changes should update Jenkins to only use the unified kiali/kiali repo.
This is a simple "patch" since it is know that we are already in the
process of phasing out Jenkins (i.e. this is just best effort patches).
Related to #4827
=> Fix Jenkins releases

.github/dependabot.yml
if this works it will help ensure the new branch covers all of the npm security alerts.
related to #4836
=> temporary change to get dependabot to run against our dep update branch

.github/dependabot.yml
it was a failed experiment, the issue is having a '#' in the `target-branch` branch name.  Fixing that issue should allow me to do this dependabot checking in my fork.
=> revert dependabot config change

deploy/get-console.sh, frontend/package.json, frontend/src/components/About/AboutUIModal.tsx, frontend/src/types/StatusState.ts, hack/run-kiali.sh, kiali.go, status/status.go
Fix https://github.com/kiali/kiali/issues/4895
- Removed **Kiali console version**
- Rename ~~**Kiali core version**~~ to **Kiali version**
- Rename ~~**Kiali core commit hash**~~ to **Kiali commit hash**
```json
{
"status": {
"Kiali console version": "unknown",
"Kiali container version": "v1.49.0-SNAPSHOT",
"Kiali core commit hash": "4f71e03c078592c10aee8a8deb48c4c066feea1a",
"Kiali core version": "v1.49.0-SNAPSHOT",
"Kiali state": "running"
},
"externalServices": [
{
"name": "Kubernetes",
"version": "v1.21.2"
},
{
"name": "Grafana"
},
{
"name": "Jaeger"
}
],
"warningMessages": [
"failed to get mesh version, please check if url_service_version is configured correctly."
],
"istioEnvironment": {
"isMaistra": false
}
}
```
```json
{
"status": {
"Kiali commit hash": …
```
=> Kiali UI and Kiali Server can point to a single commit

frontend/cypress/integration/common/overview.ts
Hopefully fixes flaky CI test. This is hard to reproduce locally but failures are frequent in CI since the tests run slower there. Some different examples:
- https://github.com/kiali/kiali/runs/5980401734?check_suite_focus=true
- https://github.com/kiali/kiali/runs/5980025014?check_suite_focus=true
This change makes separate calls to `cy.get(...)` between clicks so cypress will wait for the inner element to exist before trying to click it.
=> Fix flaky frontend test

make/Makefile.ui.mk
Remove the check for an existing `proxy` line during `make yarn-start` so that the `proxy` line will always be replaced with the value of `YARN_START_URL` even if an old `proxy` line exists in the `package.json`.
=> `make yarn-start`: replace proxy line when env var set

models/istio_validation.go
Move the ignored validations message to "Trace" level instead of "Debug".
There is a validation disabled by default ("AuthorizationPolicies" on workloads) that populates the log pretty easily while trying to debug other things.
In the Kiali startup, there is an "Info" message that tells the user about this issue, so I think is reasonable to move the level.
=> Move the ignored validation message to trace level instead of debug

frontend/cypress/integration/common/overview.ts
My working theory for why the tests are flaking in CI is that a re-render happens when the url changes. The URL gets updated with options from the overview toolbar: refresh & duration. We set `refresh` explicitly but we should also set `duration` so kiali doesn't try to update the URL with the default duration. If a re-render happens between the `cy.get('button[aria-labelledby^="overview-type"]')` and the `.click()` then this causes the reference to `cy.get(button...)` to be `undefined`.
=> Include duration in test url

business/checkers/services/port_mapping_checker.go
Moving some well-known repetitive debug messages to trace level, as this would help to differentiate those debug/trace situations:
=> Move port-matching skip message to trace level

frontend/cypress/integration/common/overview.ts, frontend/src/pages/Overview/OverviewCardContentCompact.tsx, frontend/src/pages/Overview/OverviewCardContentExpanded.tsx, frontend/src/pages/Overview/OverviewCardSparkline.tsx, frontend/src/pages/Overview/OverviewPage.tsx, frontend/src/pages/Overview/OverviewToolbar.tsx
This is still a draft/work in progress to unify the "naming" for the "data-test" attributes and also to review the "flaky" tests on the overview page in slow pipelines.
(Note, it's not yet finished or ready for review, just giving visibility on this effort).
=> Refine UI tests on overview page

frontend/cypress/integration/featureFiles/overview.feature
The "Sort by name" test in the overview page is designed over the "alpha,beta" namespaces.
To select them, it used the "Failure" filter, BUT after adding the Traffic Generator in the "bookinfo" namespace, the cluster can be unstable, and that namespace throws more errors.
It's a separate discussion if we could improve the "generators" as the kind cluster is very short in terms of resources, but in any case, the UI test was showing that something was not 100% well designed.
Also, general note, at some point, we need to investigate these errors at the PR level, in theory, there shouldn't be more "flaky" tests. 
Tests could be slow but we need to design the suite to support those conditions as well, or to have clear messages when it's a platform issue rather than a test.
Once these tests are …
=> Improve 'Sort by name' test in the overview page

frontend/cypress/integration/common/kiali_cookie.ts, frontend/cypress/integration/featureFiles/kiali_cookie.feature, frontend/cypress/support/commands.ts
In some recent change, kilai auth cookie was renamed. This PR is fixing `cy.login()` function with new kaili cookie name. There is also more isolation in smoke test itself.
Tested on stage, please test locally.
=> [cypress] login cookie renamed, cy.login() polishing

hack/istio/install-bookinfo-demo.sh
Added a note/comment in the install-bookinfo-demo.sh script.
There are some considerations that are platform/mesh dependent and I hope it would save time for others.
I revert the change, as some tests expect the traffic coming from out of the cluster.
=> Add a comment for the minikube setup in the bookinfo demo

business/checkers/destinationrules/no_dest_checker_test.go, kubernetes/host.go
Fixes https://github.com/kiali/kiali/issues/4975
Add support to the ".svc" host format, used for validations:
```
// Valid cases:
// tracing.istio-system
// tracing.istio-system.svc
// tracing.istio-system.svc.cluster.local
// Not valid:
// tracing.istio-system.svc.cluster
```
=> Fix .svc short host name

.github/workflows/integration-tests-frontend.yml, frontend/cypress.json, frontend/cypress/README.md, frontend/cypress/global.d.ts, frontend/cypress/integration/common/namespace.ts, frontend/cypress/integration/common/navigation.ts, frontend/cypress/integration/common/services.ts, frontend/cypress/integration/common/table.ts, frontend/cypress/integration/common/transition.ts, frontend/cypress/integration/featureFiles/services.feature, frontend/cypress/support/commands.ts, frontend/cypress/support/index.ts, frontend/cypress/tsconfig.json, frontend/src/components/NamespaceDropdown.tsx, frontend/src/components/VirtualList/Renderers.tsx, hack/istio/install-error-rates-demo.sh, hack/istio/install-testing-demos.sh
Adds cypress tests for the services list page. Adds a `getBySel` custom command to select an element based on the `data-test` attribute. Adds back screenshots for failed CI tests to help debug flakes. Updates hack script to deploy demos to wait for demos to be ready before running tests.
Fixes #4955
=> [cypress] Tests for services list and helper cmd

.github/workflows/release.yml, .github/workflows/util/bump.py, .github/workflows/util/release_type.sh
This is the migrated pipeline for the Kiali server.
Notes:
- I tested this as is me was the kiali bot, but in this PR there are mentions to kiali-bot, but never tried with it, we will need to create a GitHub Actions secret call GH_TOKEN
- I'm not using a fork and the reasons for that are 1) simplicity (not seeing any issue, if there is one, let me know :D) 2) that when CPaaS try to grab the tag, in the past, the commit usually doesn't belong to the repo (I guess it belongs to the fork, and the tag is created before this) and it fails, this was something we discuss with @aljesusg.
- The pipeline for now can be started manually (with workflow_dispatch option, that only works when master, so for that reason I was working on my master's branch in my fork)
Resolves …
=> Release pipeline for Kiali server

hack/setup-kind-in-ci.sh
Sets the url field for grafana and jaeger in CI environment. Needed for #5018
=> Set url for grafana and jaeger in CI environment

.github/workflows/nightly.yml, .github/workflows/release.yml
Resolves #5029.
This PR contains the following:
- Adds a nightly build pipeline to generate a latest image every weekday at 01:00.
- Removes the snapshots so a release pipeline only has "minor" and "patches" options (latest is left for the nightly, that can also be started manually)
- Updates the package.json file with the next version when creating a PR to master (minor release only)
Some comments:
1) According to the following link: https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow:
Warning: To prevent unnecessary workflow runs, scheduled workflows may be disabled automatically. When a public repository is forked, scheduled workflows are disabled by default. In a public repository, scheduled workflows are automatically disabled when no …
=> Refinements to Kiali server pipeline

README.adoc, make/Makefile.ui.mk
This is so it is easy to remember what they go.
cypress-gui runs the GUI so you can pick which individual tests to run.
cypress-run runs the full test suite headless.
Side note: also fixes the help text (make help).. the UI ones were getting indented too much.
=> add cypress-gui and cypress-run targets

hack/run-molecule-tests.sh
This is useful to tools that want to consume the results of the molecule test run.
=> [molecule] generate a results.xml file using junit xml format

.github/workflows/release.yml
Due to some general time off, the release will be on the next Monday after the end of the sprint.
That Monday the release will be started manually (to avoid updating the logic that decides if a minor release is required). After the release, the scheduling will be enabled again.
=> Disabling pipeline scheduled for next release

frontend/cypress/integration/common/sidecar_injection.ts
Look for '=' instead of ':' in labels due to label format change with the Patternfly4 update.
Closes #5054
=> [cypress] Fix sidecar injection tests

frontend/src/components/Filters/StatefulFilters.tsx, frontend/src/components/TrafficList/TrafficListComponent.tsx, frontend/src/components/VirtualList/Config.ts
Epic #4260 
- ensure column header names appear in full for list pages and traffic tab
- remove excess left and right padding for StatefulFilters
[skip-ci]
=> PF-React, style updates

hack/run-molecule-tests.sh
following schema documented here: https://llg.cubic.org/docs/junit/
(cherry picked from commit 2bd41759523cae8c2aa8094675d86e40dbf2dead)
see https://github.com/kiali/kiali/pull/5062
backporting this so we can produce a junit xml file that polarion can (hopefully) accept now
This is only changing a hack script used to run molecule tests - nothing in the server code is changing.
=> [v1.48] [molecule] add more fields to the junit xml results file

frontend/cypress.json, frontend/cypress/integration/common/graph_display.ts, frontend/package.json, make/Makefile.ui.mk
Epic #4260 
- add "--profile" to the build. This option adds a little bit of overhead but has the advantage of not munging names that can be important for understanding profiler information, but in this case, also for searching on react component names in tests.
also:
- move #root into config, as suggested in crs doco
- turn off video when running headless via make
- update one test that was failing due to the slightly different demo app setup in CI, as compared to what I had locally.
=> fix cypress graph display  feature in CI

business/checkers/authorization/principals_checker.go, business/checkers/authorization/principals_checker_test.go, business/checkers/authorization_policies_checker.go, business/istio_validations.go, kubernetes/istio.go, models/istio_config.go, models/istio_validation.go, tests/data/authorization_policy_data.go, tests/integration/assets/bookinfo-auth-policy-principals.yaml, tests/integration/tests/config_validations_test.go
RFE https://github.com/kiali/kiali/issues/4424
Istio documentation https://istio.io/latest/docs/reference/config/security/authorization-policy/#Source
Authorization Policy Source has a "principals" field, which contains a list of ServiceAccounts names in "<TRUST_DOMAIN>/ns/<NAMESPACE>/sa/<SERVICE_ACCOUNT>" format.
This PR adds a validation on an existence of those ServiceAccounts, based on searching among Workloads SAs.
Error message is displayed on a principal, which does not refer to existing SA which is labeled to any Workload.
=> Added principals checkers for AuthPolicy

frontend/cypress/support/commands.ts
When running tests on openshift, after login the browser is redirected to the overview page. If the tests also navigate to a page, the redirect to the overview page can happen _after_ the tests try to navigate to a particular page causing a test failure on the first test in the test suite.
This change waits for the redirect to the overview page to happen after logging in. Also clears the username/pw fields in the login form in case there is any placeholder text there.
=> [cypress] wait for redirect to overview page after logging in

frontend/cypress/integration/common/graph_display.ts, frontend/cypress/integration/common/graph_toolbar.ts, frontend/cypress/integration/featureFiles/graph_display.feature, frontend/cypress/integration/featureFiles/graph_toolbar.feature, frontend/src/components/DurationDropdown/DurationDropdown.tsx, frontend/src/components/Refresh/Refresh.tsx, frontend/src/components/Time/TimeDurationComponent.tsx, frontend/src/components/ToolbarDropdown/ToolbarDropdown.tsx, frontend/src/pages/Graph/GraphToolbar/GraphReset.tsx, frontend/src/pages/Graph/GraphToolbar/GraphToolbar.tsx, make/Makefile.ui.mk
Toolbar tests not covered by other dedicated features.
Epic #4854 
Closes #4960 
- duration selection
- refresh selection
- graph type selection
- traffic selection
- graph factory-reset for traffic
- graph tour
Also:
- change tooltip positions for duration and refresh, it should not cover the
menu (both for ux and also because it can break tests)
- improve tooltip position option for affected dropdown components
- improve assertions in graph_display feature
- added graph factory reset test in graph_display feature
- fix cypress-run to not generate video
=> [cypress] Graph toolbar tests

hack/istio/install-bookinfo-demo.sh
In cases when the CI is removing existing demo app and installing new one, it often fails because the removal operation is not blocking and the namespace is still being terminated when trying to install new app there.
This will wait for namespace to be removed.
There is no timeout defined but if it ever gets stuck on this operation, it will require manual interaction with the cluster anyway.
=> Wait for given namespace to be removed when uninstalling bookinfo app

tests/integration/README.md, tests/integration/utils/exec_client.go
RFE https://github.com/kiali/kiali/issues/4826
Added support of providing oc or kubectl command name to execute.
So now, for executing e2e integration tests on environment where `oc` command is not available, but `kubectl` is there, the `-e OC_COMMAND="kubectl"` env variable should be provided.
=> [e2e] Added a support of new env variable OC_COMMAND

business/openshift_oauth.go, config/config.go, handlers/authentication.go
Openshift authentication strategy is perfect when kiali is running inside the mesh cluster. If kiali is running outside the cluster, but the cluster APIs are hosted also outside of the cluster (common in case of managed Openshift clusters in pubic clouds), the same logic is applicable without the assumption of the in-cluster network settings.
This change makes the openshift authentication details configurable, with fallback to the original behavior.
https://github.com/kiali/kiali/issues/4359
* If this is a fix for a GH-issue, please link it here
=> Added authentication for remote Openshift clusters.

frontend/README.adoc, frontend/package.json, frontend/yarn.lock
Epic https://github.com/kiali/kiali/issues/4260
source-map-explorer dependency has dependabot issues.  I don't think
anyone runs this, if so it can be added back by someone, in a working
fashion.
=> Remove support for `yarn run analyze`.  The command is broken and the

frontend/package.json, frontend/yarn.lock
- add async "^3.2.2" to resolutions to fix cypress hoist
- up node-sass to "^7.0.1" to fix json-schema hoist
=> Dependabot Updates to clear issues post-pf-update

frontend/src/styles/_overrides.scss
Epic #4260 
@lucasponce This just brings back the black background for the login page.  I think I will also create a new issue to update the login page to use more current PF components and styling, but it was too risky at this time.  Let;s just merge this for the 1.51 build.
=> Bring back the black background for login page

frontend/cypress/integration/common/apps.ts, frontend/cypress/integration/common/services.ts, frontend/cypress/integration/common/table.ts, frontend/cypress/integration/common/workloads.ts, frontend/cypress/integration/featureFiles/services.feature, frontend/cypress/integration/featureFiles/workloads.feature
Add cypress tests for health indicators in workloads and services list pages.
Looks like tests in the overview page does not apply, since the health indicator on overview is focused only on apps.
=> [cypress] add health indicator checks for workloads and services lists

frontend/cypress/integration/common/graph_display.ts, frontend/cypress/integration/common/graph_find_hide.ts, frontend/cypress/integration/featureFiles/graph_find_hide.feature, frontend/src/pages/Graph/GraphHelpFind.tsx, frontend/src/pages/Graph/GraphToolbar/GraphFind.tsx, frontend/src/pages/Graph/GraphToolbar/GraphFindOptions.tsx
Adds cypress tests for graph find/hide.
Tests:
- Finding unhealthy nodes
- Hiding unhealthy nodes
- Using find/hide presets
- Opening help menu
Fixes: #5073
=> Add graph find/hide cypress tests

frontend/src/pages/IstioConfigNew/AuthorizationPolicyForm/RuleList.tsx, frontend/src/pages/IstioConfigNew/AuthorizationPolicyForm/When/ConditionList.tsx
- Use `.join(',')` to display condition values and notValues as comma-separated string
- Update this in ConditionList and RuleList
- Fixes #5111
=> Display multiple condition values as comma-separated string

frontend/cypress/integration/common/overview.ts, frontend/cypress/integration/featureFiles/overview.feature, frontend/src/app/History.ts, frontend/src/components/VirtualList/Renderers.tsx, frontend/src/pages/Overview/OverviewCardContentExpanded.tsx, frontend/src/pages/Overview/OverviewCardSparkline.tsx, frontend/src/pages/Overview/OverviewPage.tsx, frontend/src/pages/Overview/OverviewToolbar.tsx
RFE https://github.com/kiali/kiali/issues/4896
Added Traffic Direction dropdown in Overview toolbar to select Outbound and Inbound traffic to show. Selection triggers reload of Overview items and the traffic with particular direction.
Added cypress tests.
=> Outbound traffic in Overview cards. Added dropdown.

.github/workflows/release.yml, frontend/package.json
In the last release, the package.json version did not match the requirements of the version checker, it has an extra "v" prefixed. 
This PR fix the version and also the pipeline that modifies that.
Next time the version checker should pass.
=> Fix package.json version and release pipeline

frontend/src/pages/IstioConfigDetails/IstioConfigDetailsPage.scss
Update info icon in the yaml config editor, regression after Patternfly update 
It looks like the icon code changed. 
Fixes https://github.com/kiali/kiali/issues/5097
=> Update info icon in the yaml config editor

business/authentication/openshift_auth_controller.go, frontend/src/app/App.tsx
The third party must modify every request and inject an OpenShift token via the HTTP `Authorization` Header (preferred) or via the URL `oauth_token` parameter.
Fixes #5127.
=> OpenShift auth: Allow sessions from 3rd parties

business/checkers/sidecars/egress_listener_checker.go, business/checkers/sidecars/egress_listener_checker_test.go, business/checkers/virtualservices/no_host_checker.go, business/checkers/virtualservices/no_host_checker_test.go, models/istio_validation.go
These checkers are now obsolete, because Istio is actively ensuring that the offending configurations verified by KIA1003 and KIA1103 cannot make it into the cluster (i.e. the cluster will reject a resource with the offending configs). This means that KIA1003 and KIA1103 are now dead checkers and can be removed safely.
Found while working on #5085.
=> Remove KIA1003 and KIA1103 checkers

.github/workflows/kiali-ci.yml, Makefile
Upgrade version to 1.17.10 for builds
=> [v1.36] Bump go version to 1.17.10

frontend/cypress/integration/common/sidecar_injection.ts
Using the ensureKialiFinishedLoading() in preference over cy.wait().
Hopefully, fixes #5076.
=> Try to fix the flaky sidecar cypress tests

hack/run-kiali-config-template.yaml, hack/run-kiali.sh
Added istio port forward to run kiali script when istio_url is passed as a parameter. 
Changes from https://github.com/kiali/kiali/pull/5061/files#diff-4835d54dd5ef3a768c44727c31447cdc82e8fe4cb7be22858493b38ca2d239c4
For more details, see https://github.com/kiali/kiali.io/pull/537#issuecomment-1142047243 
cc @jmazzitelli
=> Added istio port-forward to run-kiali script

frontend/src/pages/Graph/SummaryPanelClusterBox.tsx, frontend/src/pages/Graph/SummaryPanelGraph.tsx, frontend/src/pages/Graph/SummaryPanelNamespaceBox.tsx
Related to review comments for:
issue: https://github.com/kiali/kiali/issues/4896
pr: https://github.com/kiali/kiali/pull/5117
For graph side-panels with Inbound/Outbound/Total tabs, add tooltips that
explain the semantics for each, as each side-panel is different.
=> Add tooltips to graph side-panel traffic tabs

business/checkers/destinationrules/no_dest_checker.go, business/checkers/destinationrules/no_dest_checker_test.go, business/checkers/no_service_checker.go, tests/data/destination_rules_data.go, tests/data/service_entry_data.go, tests/integration/assets/bookinfo-service-entry-labels.yaml, tests/integration/assets/bookinfo-service-entry-wrong-labels.yaml, tests/integration/tests/config_validations_test.go
RFE https://github.com/kiali/kiali/issues/5131
DestinationRule subset labels has been checked to match workload labels.
In case when no Workload/Service exists, the ServiceEntry could be created which points to external resource and match the DestinationRule subset labels.
With this PR, the validation of DR subset labels is extended to consider ServiceEntry endpoint labels when no Workload is found with labels.
=> Added support of considering ServiceEntry endpoint labels in DestinationRule subset labels validation

frontend/src/components/MessageCenter/MessageCenterTrigger.tsx, frontend/src/components/Nav/Masthead/HelpDropdown.tsx
Align toolbar icons Bell and Help from Helpdropdown and MessageCenter.
Fixes #5148 
cc @jshaughn
=> Toolbar help and bell icons misaligned

frontend/src/components/MetricsOptions/MetricsSettingsDropdown.tsx
Adjust font style in metrics charts options. Was displayed in bold, and with different style in the titles. 
Fixes https://github.com/kiali/kiali/issues/5168
=> Update MetricsSettingsDropdown styles

frontend/src/components/Charts/CustomTooltip.tsx, frontend/src/components/JaegerIntegration/TraceTooltip.tsx
The property constraintToVisibleArea seems to collide somehow with the with and heigh modified by the tooltip. 
https://formidable.com/open-source/victory/docs/victory-tooltip/#constraintovisiblearea
But, maybe it is expected to render the tooltip just inside the graph?
Fixes https://github.com/kiali/kiali/issues/5160
=> Update customTooltip to place tooltip in the correct point in the graph

hack/ibmcloud-openshift.sh
If you run this and point to a running cluster, you can be granted admin rights:
```
hack/ibmcloud-openshift.sh admin
```
This is what it looks like when the cluster is running and the operation succeeds:
```
$ hack/ibmcloud-openshift.sh -np jmazzite-kiali-perf admin
...
📄 Adding you as a cluster admin user
OK
The configuration for jmazzite-kiali-perf-cluster was downloaded successfully.
Added context for jmazzite-kiali-perf-cluster to the current kubeconfig file.
You can now execute 'kubectl' commands against your cluster. For example, run 'kubectl get nodes'.
If you are accessing the cluster for the first time, 'kubectl' commands might fail for a few seconds while RBAC synchronizes.
```
If the cluster is not running, this is the error you will get:
```
$ hack/ibmcloud-openshift.sh admin …
```
=> [hack] ask that you be added as an admin on the cluster

frontend/cypress/integration/common/kiali_login.ts, frontend/cypress/integration/featureFiles/kiali_about.feature, make/Makefile.ui.mk
This fixes the login test.
To test, this assumes you have a kiali user created in the htpasswd provider in your cluster. You can create this via `make cluster-add-users`.
Once you do that, run (note: set your base url correctly):
```bash
make -e CYPRESS_AUTH_PROVIDER=htpasswd \
-e CYPRESS_PASSWD=kiali \
-e CYPRESS_USERNAME=kiali \
-e CYPRESS_BASE_URL=https://your.kiali.route.url.here \
cypress-gui
```
Then select the `kiali_login.feature` test to run. It should now pass.
=> Fix cypress kiali_login.feature test

frontend/src/pages/IstioConfigDetails/IstioObjectDetails/IstioConfigOverview.tsx, frontend/src/pages/IstioConfigDetails/IstioObjectDetails/IstioStatusMessageList.tsx
Starting Istio with values.global.istiod.enableAnalysis=true
Starting Istio with values.global.istiod.enableAnalysis=false
No errors:
* I've seen the kiali validations don't have a link to the docs (https://kiali.io/docs/features/validations/), but Itsio validations have. An improvement could be, adding these links into kiali validations also. 
Sending as a draft to get feedback
Fixes https://github.com/kiali/kiali/issues/5204
=> Add Kiali validations on the Istio Config Detail sidepanel

business/workloads.go, business/workloads_test.go, frontend/cypress/integration/common/workload_logs.ts, frontend/cypress/integration/featureFiles/workload_logs.feature, frontend/src/pages/WorkloadDetails/WorkloadPodLogs.tsx, frontend/src/services/Api.ts, frontend/src/types/IstioObjects.ts, handlers/workloads.go, kubernetes/kubernetes.go, kubernetes/kubetest/mock_kubernetes.go, tests/integration/tests/pod_logs_test.go, tests/integration/tests/workloads_test.go
The pod logs endpoint was loading to memory the whole results from the cluster API, then parsing/processing them (also on memory) and, finally sending the results to the browser/client. While this works OK for small data sets, this is leading to high memory usage for large logs.
This is changing the how the input from the cluster API is read and how the results are sent:
1. There is the specific case when the users chooses a time range specifying both a start and end date AND also chooses to show only the last _N_ lines. For this case, the original code is changed only slightly:
* Instead of loading the whole response of the cluster API into memory to thereafter process it, the response from the cluster API is read as processing is possible. So, only one unprocessed/raw log line is loaded …
=> Reduce memory usage for the pod logs endpoint

business/mesh.go, frontend/src/config/Config.ts, frontend/src/pages/Overview/NamespaceInfo.ts, frontend/src/pages/Overview/OverviewPage.tsx, frontend/src/services/Api.ts, handlers/mesh.go, routing/routes.go
RFE https://github.com/kiali/kiali/issues/4896
Adding support of showing mesh config OutBoundTrafficPolicy mode on Overview page, as a suffix on "istio-system" namespace.
=> Added support of showing OutBoundTrafficPolicy

hack/ci-kind-molecule-tests.sh, hack/run-molecule-tests.sh, make/Makefile.molecule.mk
Molecule tests no longer support the docker driver.
=> Default to podman in CI molecule tests

hack/istio/install-istio-via-istioctl.sh, hack/setup-kind-in-ci.sh
Useful when running Istio on a machine with not alot of resources.
fixes: https://github.com/kiali/kiali/issues/5264
Pass `-rr true` to the hack script to reduce memory/cpu usage of sidecar.
=> [hack] Provide an option to run istio configured to consume less CPU and memory

frontend/src/components/Envoy/EnvoyDetails.tsx, frontend/src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
Fix https://github.com/kiali/kiali/issues/5250
Envoy Tab change after refresh to default one ("clusters").
Now we keep the tab selected
=> Keep tab envoy after refresh

config/config.go, frontend/cypress/integration/common/graph_toolbar.ts, frontend/src/components/ToolbarDropdown/__tests__/__snapshots__/ToolbarDropdown.test.tsx.snap, frontend/src/config/Config.ts, frontend/src/config/ServerConfig.ts, frontend/src/reducers/__tests__/UserSettingsState.test.ts
- remove invalid durations based on globalScrapeInterval (duration < 2 x scrape)
- add 2m duration to choices.  This is good when 1m is invalid, and may
be useful even when 1m is available.
- fix bug in toValidDuration util
- change default refreshInterval from 15s to 1m, 15s is too frequent, especially
in non-trivial installs.  1m may also be too small, but it's better.
Part-of https://github.com/kiali/kiali/issues/5269
=> Improve Duration/Refresh handling

frontend/src/components/Charts/ChartWithLegend.tsx, frontend/src/components/JaegerIntegration/JaegerScatter.tsx, frontend/src/components/Metrics/SpanOverlay.ts
Fixes https://github.com/kiali/kiali/issues/5276
Follow-up work to change the mouse pointer when:
- "Show spans" is enabled in metrics.
- "Traces" main chart.
=> Adjust mouse pointer in charts for traces

hack/ci-openshift-molecule-tests.sh
Now that @nrfox showed me a trick to reduce istio memory footprint, this PR is useful for running tests on openshift clusters that don't have a lot of resources (e.g. my basement machine :) )
=> [hack] ci openshift script can install istio with reduced resources

frontend/cypress/README.md, frontend/cypress/fixtures/perf/graphParams.json, frontend/cypress/integration/common/kiali_cookie.ts, frontend/cypress/integration/common/kiali_login.ts, frontend/cypress/perf/Graphload.spec.ts, frontend/cypress/plugins/bdd.ts, frontend/cypress/plugins/index.ts, frontend/cypress/support/commands.ts
This replaces the manual flow that required cypress to actually navigate to the login page and type fields into boxes. Not only is this faster, but it eliminates the need for all the hacks around the login page. It is also the only way to login to the perf clusters. Note that the manual login flow is still being tested by the `kiali_login` feature.
=> Login programatically for cypress tests

frontend/src/components/MTls/NamespaceMTLSStatus.tsx, frontend/src/types/TLSStatus.ts
RFE https://github.com/kiali/kiali/issues/5263
In Overview page, while showing mTLS lock icon on namespaces, where mTLS is enabled not for namespace but for Mesh-wide, it will show now a message in lock's tooltip that mTLS status is extended from Mesh-wide.
=> Added new option for namespace's mTLS enabled extended from Mesh-wide

frontend/src/pages/Graph/GraphToolbar/GraphToolbar.tsx
The "Display" drop down in the the Graph page is misaligned when an invalid operand is typed (Find...)
As the container is display as a flex, the issue can be fixed with a align-items property.
Fixes #5302
=> Alignment of Display Dropdown in Graph options

hack/istio/install-electronic-shop-demo.sh, hack/istio/install-federated-travels-demo.sh, hack/istio/install-music-store-demo.sh, hack/istio/install-runtimes-demo.sh, hack/istio/install-scale-mesh-demo.sh, hack/istio/install-service-spawner-demo.sh, hack/istio/install-topology-generator-demo.sh
Adding some hack scripts to install demos in OpenShift.
The idea is they work the same - Having each one their own particularities: 
- h for help 
- d for uninstall 
- c for client (oc by default, tested also for kubectl)
demos added: 
- electronic shop
- federated travels: When installing this one in open shift, for some reason, it doesn't look to be injecting pro pertly the Istio injections, but it looks to be installed in the mesh. To be reviewed. 
- music store
- runtimes
- scale mesh
- service spawner: For some reason I'm not able to install the example. There is a crashLoopBackOff error trying to deploy the image quay.io/jotak/nginx-hello:0.2 - I should look into this, or probably remove the script in the meantime. 
- topology generator
Fixes …
=> Hack scripts to install demos in OpenShift 

.github/workflows/build-backend.yml, .github/workflows/build-frontend.yml, .github/workflows/release.yml
When starting pipelines, the source where the pipeline is obtained is configurable, usually is master, using the lastest pipeline, but someone can point to another branch/tag.
To fix the situation of duplicating a pipeline just to avoid integration testing, I'm introducing GitHub Actions pipelines to v1.48, a version that didn't have this kind of automations in the past.
The pipeline that I'm adding is the same as the current but without the automations.
This is just for v1.48 as is the only version with no integration tests which we might need patches, for the subsequents, we will continue using the lastest version of the release workflow.
I will document this on the document in the master branch.
=> Adding release scripts to this version without integration testing

frontend/src/components/HeatMap/HeatMap.tsx
Remove the whitespace for label cells for the heatmap component in Trace Details .
Fixes #5291
=> Trace details heatmap vertical labels are truncated 

frontend/cypress/README.md, frontend/cypress/fixtures/perf/overviewPage.json, frontend/cypress/perf/Graphload.spec.ts, frontend/cypress/plugins/bdd.ts, frontend/cypress/tsconfig.json
Adds performance tests for the overview page when varying amounts of namespaces are present to understand the impact of merely having a larger number of namespaces.
Related to #5144
=> Perf tests for overview page and varying namespaces

frontend/src/components/JaegerIntegration/TracesComponent.tsx, frontend/src/components/Metrics/IstioMetrics.tsx
Place "View in Grafana" link in the same row of the metrics filters. 
Also place "View in Tracing" link in the same row that the filters. It looks to have the same issue:
Fixes #5273 
Fixes #5287
=> Adjust the view in Grafana and View in tracing link

business/checkers/common/multi_match_selector_checker.go, business/checkers/common/multi_match_selector_checker_test.go, business/checkers/common/workload_selector_checker_test.go, tests/data/validations/destinationrules/no-subset-labels-checker.yaml, tests/data/workload_data.go
Issue https://github.com/kiali/kiali/issues/5310
When checking "KIA0002 More than one selector-less object in the same namespace" and "KIA0003 More than one object applied to the same workload" for Sidecars, PeerAuthentications and RequestAuthentiations, it should show validation reference objects to only local namespace objects. Cross namespace validations are not supported for these object types.
Before: Sidecars, PeerAuths and RequestAuths validations of workload selectors "KIA0003" and "KIA0002" were considering objects from all namespaces.
Now: As those objects are not supporting cross-namespace validations, consider objects only from own namespace.
=> Consider objects from own namespace only in workload selector/less checkers.

frontend/src/components/Charts/ChartWithLegend.tsx
This ensures that the clickable area of the chart encompasses the largest point. Otherwise the points on the edge of the graph can't be clicked.
fixes #5222
=> Add padding to charts equal to largest data size

business/workloads.go, business/workloads_test.go, frontend/src/pages/WorkloadDetails/WorkloadPodLogs.tsx, frontend/src/types/IstioObjects.ts
Retrieve miliseconds in the WorkloadPodLogs so logs can be sorted using decimals. 
Fixes #5246
=> Milliseconds precision for sorting log entries in the Logs tab

models/istio_validation.go
Issue https://github.com/kiali/kiali/issues/5343
Before, it was considering workloads as well into analyzed objects for namespace validations summary:
Now, only configs are counted:
=> Skip workloads when summarizing config validations in Overview page and in Graph

business/istio_config.go, frontend/src/pages/IstioConfigList/IstioConfigListPage.tsx, frontend/src/pages/Overview/OverviewPage.tsx, frontend/src/pages/ServiceDetails/ServiceDetailsPage.tsx, frontend/src/services/Api.ts, frontend/src/types/IstioConfigList.ts, handlers/istio_config.go, models/istio_config.go
RFE https://github.com/kiali/kiali/issues/5153
Before, while loading Istio Config list:
It was requesting configs per namespace.
Now: it does not provide namespace list into API call, and the handler loads all configs for all namespaces.
This approach is used,  as handler is now loading configs from Registry, where all configs are cached for all namespaces.
=> Optimized Istio Config list loading

frontend/cypress/integration/common/sidecar_injection.ts
Test flake - Sidecar injection override default policy
I was not able to reproduce this error in my environment, I guess it depends, as this is a test flake. 
But I've changed the refresh time to 0 - See if that helps.
It is weird, the message seems to be the same as when you are selecting a non existent namespace, but in that screenshot, the menu with the <Overview, Traffic, Logs, etc> links seems to be moved to the bottom of the page. 
See example: 
Fixes #5236
=> Set refresh time to 0 for sidecar_injection tests

frontend/src/components/IstioWizards/ServiceWizardDropdown.tsx, frontend/src/components/IstioWizards/WorkloadWizardDropdown.tsx
It looks like the "Tab" component from Patternfly is not using the key in its implementation: 
```
<li
className={css(styles.tabsItem, eventKey === localActiveKey && styles.modifiers.current, childClassName)}
ref={innerRef}
>
```
---
Removed the icon from the DropdownToggle component that was causing the error. It looks to not be having any effect on the component, as it was the default icon. This change affects the Service and Workload details views. 
Fixes #5360
=> Remove icon prop to DropdownToggle causing js error

frontend/src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
The error seems to be reproduced when selecting a trace that belongs to a pod from another namespace. 
The WorkloadPodLogs component is initialized using: 
```
namespace={this.props.match.params.namespace}
workload={this.props.match.params.workload}
pods={this.state.workload!.pods}
```
The workload and the namespace are correct, because they come from the current call, but, the pod is retrieved from the current state, which is not yet updated, because the API call to fetch the current workload has not finished. 
This fix uses await to make the fetchWorkload async and update the state once the fetch has finished.  
Fixes https://github.com/kiali/kiali/issues/5289
=> Logs tab page has wrong container when navigating from trace tab

.github/workflows/tag-creator.yml
This workflow let us create for n releases (Ex: v1.24,v1.36) their tags.
This check if the version is an old one where the UI is in kiali/kiali-ui.
We need a secret called KIALI_TOKEN with rights to create tags in kiali/kiali-ui otherwise is going to use the token of kiali/kiali. I don't know if GH actions has rights inside org.
This was tested in my locally repos https://github.com/aljesusg/kiali/runs/7685956294?check_suite_focus=true
=> Tag creator workflow

Makefile, make/Makefile.cluster.mk, make/Makefile.olm.mk, make/Makefile.operator.mk
This allows you to test deploying the operator via OLM (as opposed to helm).
This will exercise the OLM metadata on your local machine.
fixes: https://github.com/kiali/kiali/issues/5364
In short, there are now three main make targets introduced by this PR:
* `olm-operator-create`: Installs the operator via OLM
* `olm-operator-delete`: Removes the operator and all other OLM-released resources
* `run-operator`: Runs the operator locally using the same mechanism/shell process that the real operator does in-cluster.
* `olm-install`: Installs the OLM infrastructure. Use this if on minikube or kind to get OLM installed. OpenShift doesn't need this - it already has OLM
To test this PR (and its required operator PR https://github.com/kiali/kiali-operator/pull/554):
* Test procedures for minikube: …
=> [make] be able to deploy the operator via OLM

frontend/cypress/integration/common/kiali_help.ts, frontend/cypress/integration/featureFiles/kiali_help.feature
Some tests from the old [Selenium](https://github.com/Kiali-QE/kiali-qe-python/blob/master/kiali_qe/tests/test_menu.py) suite revolved around the "Help" dropdown, now migrated into the Cypress framework 
It does everything the old suite did and a little more:
- Clicks on the "Help" button
- Checks if all the 4 options are present
- Checks if the "Documentation" link exists
- Opens modals for debug and certificates
Due to some inconsistencies mentioned in #5384 , I am not able to properly test the text fields in the "View Debug Info" modal. Right now, it only checks if the modal has opened.
=> [Cypress] "Help" dropdown test migration

business/health.go, business/health_test.go, graph/options.go, graph/telemetry/istio/appender/health.go, graph/telemetry/istio/appender/health_test.go, graph/telemetry/istio/istio.go, graph/types.go, graph/util.go, handlers/health.go
Adds node health data when traffic map is being generated. The health appender is still responsible for gathering the workload statuses and annotations for apps/services/workloads.
Fixes #4566
=> Use traffic data for node health rates

make/Makefile.cluster.mk, make/Makefile.operator.mk
OpenShift 4.11 no longer provides a secret with SAs. We need to fix our dev tools to work with 4.11 (but don't break when on 4.10 and before).
=> [make] fix pull secret

config/config.go, handlers/jaeger.go, jaeger/client.go
Closes https://github.com/kiali/kiali/issues/4635
**Operator PR: ** https://github.com/kiali/kiali-operator/pull/558
As an example, By adding this to the Kiali CR:
```
spec:
tracing:
query_scope:
test: test-value
```
I then get this in the Jaeger query:
```
2022-08-19T15:04:38Z INF Prepared Jaeger query: query:{service_name:"x-server.alpha" tags:{key:"test" value:"test-value"} start_time_min:{seconds:1660921234} start_time_max:{seconds:1660921478 nanos:862887247} duration_min:{} search_depth:15}
```
=> For Tracing queries, add QueryScope support (analogous to Prometheus)

frontend/src/components/CytoscapeGraph/MiniGraphCard.tsx, frontend/src/components/DurationDropdown/DurationDropdown.tsx, frontend/src/components/Refresh/Refresh.tsx, frontend/src/components/Time/TimeDurationModal.tsx, frontend/src/components/Time/TimeRangeComponent.tsx, frontend/src/components/ToolbarDropdown/ToolbarDropdown.tsx
**This only affects the kiosk=parent mode**
The _refresh interval_ and _duration_ controls are currently not available in the kiosk mode, because toolbars are not visible.
When Kiali is running under in kiosk mode, the title of the mini-graph card (i.e. the time range) will become clickable. When clicking, a modal dialog will appear offering the missing time controls.
Since this is done in the mini-graph card component, these changes are reflected in all detail pages (apps, workloads, services).
Related to kiali/openshift-servicemesh-plugin#42
=> Show time controls in a modal from mini-graph card

hack/perf-ibmcloud-openshift.sh
Adds options to specify the number of namespaces and traffic rate for demo workloads when creating a perf cluster.
Relates to #5144
=> [hack] Add option to specify number of namespaces to perf cluster

make/Makefile.olm.mk
Without this fix, you'll never get the latest image to be used
even after doing a make cluster-push-operator. And it will drive
you crazy wondering why your changes aren't getting picked up.
=> [make] Force the operator image to always be pulled when debugging via OLM

frontend/cypress/integration/common/kiali_sidebar_toggle.ts, frontend/cypress/integration/featureFiles/kiali_sidebar_toggle.feature
Another migrated test from the old [Selenium](https://github.com/Kiali-QE/kiali-qe-python/blob/6acc35c8e2f38bf9b7daa5db5ee14114e867772a/kiali_qe/tests/test_menu.py#L47) suite.
Does nothing less than toggling the sidebar and verifying if it is or is not visible.
=> [Cypress] Navbar toggle test

business/checkers/telemetries_checker.go, business/checkers/wasm_plugin_checker.go, business/istio_config.go, business/istio_validations.go, business/registry_status.go, frontend/src/components/Pf/PfBadges.tsx, frontend/src/components/VirtualList/Config.ts, frontend/src/pages/IstioConfigList/FiltersAndSorts.ts, frontend/src/pages/IstioConfigList/__tests__/IstioConfigListComponent.test.ts, frontend/src/types/IstioConfigDetails.ts, frontend/src/types/IstioConfigList.ts, frontend/src/types/IstioObjects.ts, frontend/src/utils/IstioConfigUtils.ts, kubernetes/cache/istio.go, kubernetes/istio.go, kubernetes/types.go, models/istio_config.go, models/istio_validation.go
New Istio Types support, excluding validations at this stage. 
Telemetry example: 
wasm plugin:
The types have been tested with the following yaml in crc: 
oc apply -f telemetry.yaml
```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
name: mesh-default
spec:
tracing:
- randomSamplingPercentage: 10.00
customTags:
my_new_foo_tag:
literal:
value: "foo"
```
oc apply -f wasmplugin.yaml
```
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
name: openid-connect
spec:
selector:
matchLabels:
istio: ingressgateway
url: oci://private-registry:5000/openid-connect/openid:latest
imagePullPolicy: IfNotPresent
imagePullSecret: private-registry-pull-secret
phase: AUTHN
pluginConfig:
openid_server: authn
openid_realm: ingress
``` …
=> Support Telemetry and WasmPlugin Istio objects

frontend/cypress/integration/common/graph_toolbar_legend.ts, frontend/cypress/integration/featureFiles/graph_toolbar_legend.feature, frontend/src/pages/Graph/GraphLegend.tsx, frontend/src/pages/Graph/GraphToolbar/__tests__/__snapshots__/GraphLegend.test.tsx.snap
Another migrated [suite from Selenium](https://github.com/Kiali-QE/kiali-qe-python/blob/75f60eed7cb290e7e3c94f71cf870d1445154468/kiali_qe/tests/test_graph_page.py#L124).
The old suite most likely switched between the 4 available graph layouts. The new suite tests all of the buttons, as well as button groups (for example you should not be able to have active more than one Graph Layout at once). It also briefly checks the opening and closing of the Legend sidebar. 
The tests mess only with the buttons, not with the graph itself. We might do that sometimes in a future, however it is not a priority now.
Related issue: #5390
=> [Cypress] Migration from Selenium (graph buttons and legend sidebar test)

config/version-compatibility-matrix.yaml, status/versions_test.go
cherry pick of baa62a2a348ee08f165a01f0a6bcfaaebc50f128 which comes from https://github.com/kiali/kiali/pull/5401
fixes: https://github.com/kiali/kiali/issues/5420
=> [v1.55] new istio 1.15 compat matrix info

kubernetes/client_factory.go, kubernetes/client_factory_test.go
Replaces read lock with read/write locks and moves some global variables into the factory. I'm not totally sure what was causing the race condition but I suspect something to do with either the read locks themselves or when the lock/unlocking was happening.
I ran this locally for ~50 iterations with `make test-race` and encountered 0 failures.
Fixes #4849
=> Use rw locks and remove globals

frontend/cypress/integration/common/kiali_sidebar_toggle.ts
Updates the assertion in the test to `be.visible`. Using `exists` would cause the `then` statement to fail because the element can exist in the dom but not be visible yet.
Example of flake: https://github.com/kiali/kiali/runs/8140114181?check_suite_focus=true
=> Fix cypress graph toggle flake

config/config.go, handlers/authentication.go, kubernetes/cache/cache.go, kubernetes/token.go, kubernetes/token_test.go
k8s service token is never refreshed, so this PR is adding some logic to re-read the token:
- Setting the expire token time  in token_expire_duration, in seconds, defaults to 1 minute: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md 
The auth strategy "anonymous" uses this token also as the user auth token. As the user is anonymous, get the SA to inherit its permissions.
- the cache uses a timer that runs every tokenExpireDuration because it needs to create a new client with the new token for each restClient. 
- GetKialiToken also uses a refresh timestamp when it is called outside the cache
Fixes https://github.com/kiali/kiali/issues/5070
=> Refresh K8s Service Account Token (a)

hack/istio/install-bookinfo-demo.sh, hack/istio/install-error-rates-demo.sh, hack/istio/install-testing-demos.sh, hack/istio/install-travel-agency-demo.sh
- Moved the creation of the scc before apply any yaml in the namespace to avoid warnings. 
- Added scc for the user. Related: https://istio.io/latest/docs/setup/platform-setup/openshift/ (The Istio sidecar injected into each application pod runs with user ID 1337, which is not allowed by default in OpenShift. )
Fixes #5394
=> Update testing demos to be compatible with OpenShift 4.11

frontend/src/components/CytoscapeGraph/MiniGraphCard.tsx, frontend/src/components/IstioWizards/LoadingWizardActionsDropdownGroup.tsx, frontend/src/hooks/services.ts, frontend/src/pages/Graph/SummaryPanelNode.tsx, frontend/src/pages/ServiceDetails/ServiceDetailsPage.tsx, frontend/src/pages/ServiceDetails/ServiceInfo.tsx, frontend/src/types/IstioObjects.ts
In Kiosk mode, the actions drop-down is not available. Thus, the wizards cannot be launched.
To allow usage of the wizards in the Kiosk mode, this is adding the relevant entries to the Kebab menu of the MiniGraphCard.tsx.
Fixes kiali/openshift-servicemesh-plugin#43
=> Launch Wizards from MiniGraphCard.tsx

hack/setup-kind-in-ci.sh
Workaround for #5441 while https://github.com/kiali/kiali/pull/5442 is not fixed
=> Force use kindest version 1.24 by default in CI

business/tls.go, frontend/src/app/AuthenticationController.tsx, frontend/src/components/MTls/MeshMTLSStatus.tsx, frontend/src/pages/Overview/OverviewPage.tsx, frontend/src/reducers/MeshTlsState.ts, frontend/src/store/Selectors.ts, frontend/src/types/TLSStatus.ts, models/mtls_status.go
RFE https://github.com/kiali/kiali/issues/5263
The idea of this change it to show Kiali users more information about mTLS configuration icon shown in toolbar.
When enableAutoMtls:true then mTLS status is taken from default config.
QE: Regression testing is required for "enableAutoMtls:true/false". Namespace wide TLS.
=> mTLS lock icon's tooltip contains hint about default "enableAutoMtls:true"

hack/setup-kind-in-ci.sh
This is a cypress tests which was failing at times. Looks like, the source of the issue is the environment which sometimes records more errors than expected leading to an error status of a service that is expected to give only up to degraded status.
This changes Kiali configuration to extremely tolerant with the relevant service: only if 100% of the traffic is erring, the service will be flagged as faulty. Otherwise, its health will be degraded as long as more than 2% of the traffic fails.
Fixes #5226
=> [CI] Fix test validating that the degraded status of a service is reported

hack/istio/install-istio-via-istioctl.sh
Change defaults for the istio install hack script such that it doesn't look like a multi-cluster install.  This lets devs run kiali outside of the cluster (via run-kiali.sh) without seeing extra cluster-labeling in the graph. Of course, if you are testing multi-cluster, you can specify args to the hack script to set a non-default cluster-name.
Closes https://github.com/kiali/kiali/issues/5248
=> Change defaults for the istio install hack script

config/version-compatibility-matrix.yaml
Right now it looks like it will be 1.57, but this could change.
See: https://issues.redhat.com/browse/OSSM-1964
=> add 2.3 compat information.

frontend/cypress/integration/common/istio_config_type_filters.ts, frontend/cypress/integration/common/istio_config_validation_filters.ts, frontend/cypress/integration/common/label_check.ts, frontend/cypress/integration/featureFiles/istio_config_type_filters.feature, frontend/cypress/integration/featureFiles/istio_config_validation_filters.feature, frontend/src/components/Filters/StatefulFilters.tsx
This is the refinement of the #5424, which I decided to close due to heavy changes in all of the code.
Another migration from the Selenium. These suites are supposed to check whether are all of the filters usable or not.
Most of the implementation is in the istio_config_type_filters.ts. The files doesn't take that much time and I also use `cy.intercept()` on many places to verify that the filtering happend.
This PR is related to https://github.com/kiali/kiali/issues/5392 and https://github.com/kiali/kiali/issues/5393 issues.
=> [Cypress] Istio page filters migration (refinement)

hack/run-kiali.sh
The istiod service name is different in OSSM. Be able to tell run-kiali.sh what the service name is (e.g. `-isn istiod-custom`).
This is also useful for upstream canary deployments where the istiod service name is also different from "istiod".
=> [hack] run-kiali to support running in OSSM environment

kubernetes/kubernetes.go
The rest call for the api group does not require cluster permissions and is a more efficient way of determining if the gateway apis are installed in the cluster. It's also how the `IsOpenshiftCall` is implemented.
=> Use rest call to discover gateway api

business/test_util.go, business/workloads.go, business/workloads_test.go, kubernetes/cache/kubernetes.go, kubernetes/kubernetes.go
For a custom controller that manages replica sets (like Argo Rollout), defer to the replica sets as the workloads, and not the custom controller. The controller may control multiple replica sets, it may not live in the same namespace as the replica sets, and it may have unusual characteristics. But maybe most importantly, Istio telemetry will report the RS as the workload, and so it is critical to the graph, and linking, to use the RS as the workload.
Closes https://github.com/kiali/kiali/issues/5261
Closes #4210
=> For Argo rollout, use the controller's replica sets as workloads

frontend/cypress/integration/common/apps.ts
Fixes https://github.com/kiali/kiali/issues/5499
Change flaky click to a visibility check for the kebab menu.  This is just trying to ensure that we get span rows, a specific click on the kebab is not particularly needed and our attempts to solve the [scrolling?] problem have not been successful.  This test should still be sufficient to prove the feature is working.
=> Change flaky click to a visibility check for the kebab menu.  This is

frontend/src/pages/Overview/OverviewCardControlPlaneNamespace.tsx
Fixes #5495 
Note: After approval, I will create a backport PR to v1.57
=> Adding more space between the chart name and the y axis value

business/test_util.go, business/workloads.go, business/workloads_test.go, kubernetes/cache/kubernetes.go, kubernetes/kubernetes.go
Backport cherry-pick of https://github.com/kiali/kiali/pull/5491
=> [v1.57] For Argo rollout, use the controller's replica sets as workloads (#5491)

jaeger/client.go
In the past, the name recorded for services in the istio namespace didn't include the namespaces in traces. Currently, that is no longer the case, apparently.
Since Kiali was omitting the namespace for services in the istio namespace, traces/spans of such services weren't being fetched and were missing in Kiali. Most notably, this was the case for istio gateways workloads (either ingress or egress).
This is removing the conditional to omit the namespace based only on configuration flags.
Fixes #4935
=> Do not omit namespace when querying for traces

business/istio_config.go, frontend/cypress/integration/common/istio_config.ts, frontend/cypress/integration/featureFiles/istio_config.feature, frontend/src/components/IstioActions/IstioActionsNamespaceDropdown.tsx, frontend/src/components/IstioConfigPreview/IstioConfigPreview.tsx, frontend/src/components/IstioWizards/WizardActions.ts, frontend/src/config/ServerConfig.ts, frontend/src/pages/IstioConfigNew/GatewayForm/AddressBuilder.tsx, frontend/src/pages/IstioConfigNew/GatewayForm/AddressList.tsx, frontend/src/pages/IstioConfigNew/GatewayForm/ListenerBuilder.tsx, frontend/src/pages/IstioConfigNew/GatewayForm/ListenerList.tsx, frontend/src/pages/IstioConfigNew/IstioConfigNewPage.tsx, frontend/src/pages/IstioConfigNew/K8sGatewayForm.tsx, frontend/src/types/ErrorRate/__testData__/ErrorRateConfig.ts, frontend/src/types/IstioObjects.ts, frontend/src/types/ServerConfig.ts, frontend/src/types/__testData__/HealthConfig.ts, handlers/config.go
RFE https://github.com/kiali/kiali/issues/5502
For testing:
Go to Istio Config list page.
"Actions" dropdown, added new option "Create K8s Gateway".
When Gateway API is enabled (https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/ also add 'app' label into Gateway object), newly added option is enabled. What Gateway API CRD is not installed, then option is disabled.
=> K8s Gateway object creation in Wizard

frontend/cypress/integration/common/sidecar_injection.ts
https://issues.redhat.com/browse/OSSM-2105
Clears the annotation if it's present and only uses the label. Adds a note for platform specific tags.
=> [Cypress] Fix sidecar injection cypress tests that assumed only label

frontend/cypress/integration/common/sidecar_injection.ts
=> [v1.57] Fix sidecar injection tests that assumed label

frontend/src/pages/Overview/OverviewCardControlPlaneNamespace.tsx
For example, when the memory series has no values:
=> Hide memory or CPU charts if there is no values to show

hack/istio/install-bookinfo-demo.sh
In some environments some bookinfo pods are started without a side car even though everything is configured correctly. This is an attempt to fix this behavior so the pods are not patched before smmr is Ready.
=> An attempt to fix timing issue resulting in missing side car

tests/integration/tests/kiali_urls_test.go
https://issues.redhat.com/browse/OSSM-2138
Not critical check of Cluster name is removed.
On OCP clusters retrieving Cluster ID from istiod pod fails and is ignored on Kiali side.
https://github.com/kiali/kiali/blob/master/handlers/config.go#L106
=> [v1.57] Ignore cluster info checking, as Kiali ignores it in case of any problem

.github/workflows/build-backend.yml, Makefile, README.adoc, make/Makefile.build.mk
Adds ability to pass go test flags through make. Enables you to run individual tests and/or set other options while still using the `make test` command.
=> Pass go test flags through make

tests/integration/tests/kiali_urls_test.go
Cherry-pick of https://github.com/kiali/kiali/pull/5573 from v1.57 into master.
=> [e2e] Ignore cluster info checking, as Kiali ignores it in case of any problem

frontend/src/components/IstioConfigPreview/IstioConfigPreview.tsx
Add an additional state item so IstioConfigPreview can control when the modal is Open. 
Fix #5546
=> Preview shows old state in Istio Config Wizard Preview

make/Makefile.container.mk
The full distro image will be flagged with "-distro" in the tag.
fixes: https://github.com/kiali/kiali/issues/5508
=> switch images so the distroless is the default image

hack/istio/install-bookinfo-demo.sh, hack/istio/kustomization/bookinfo-ppc64le.yaml, hack/istio/kustomization/bookinfo-s390x.yaml
This is required by IBM p/z teams as there are no official ppc64le and s390x bookinfo images. This change allows to specify architecture to use matching bookinfo images.
=> Adding support for IMB's p/z arch to bookinfo install script

hack/istio/install-error-rates-demo.sh, hack/istio/install-testing-demos.sh
This is required by IBM p/z teams as there are no official ppc64le and s390x error rates images. This change allows to specify architecture to use matching error rates images. Also updating install-testing-demos.sh to work with new arch.
=> Adding support for IMB's p/z arch to error rates install script

make/Makefile.molecule.mk
On the occasions when you run the molecule tests and you need to abort the test, you can kill the running podman process. But in some cases when you abort, the podman volume remains. Then when you attempt to run the molecule tests again, it will fail with:
```
podman volume create molecule-tests-volume
Error: volume with name molecule-tests-volume already exists: volume already exists
make: *** [make/Makefile.molecule.mk:162: .prepare-molecule-data-volume] Error 125
```
Thus the developer is forced to manually remove the volume.
This PR automatically purges any old/obsolete podman volume if it exists thus cleaning up after a failed attempt without requiring the developer to manually do it.
=> [make][molecule] purge the podman volume if an old one still exists

frontend/src/components/IstioStatus/IstioStatus.tsx, frontend/src/components/IstioStatus/IstioStatusInline.tsx, frontend/src/pages/Overview/ControlPlaneBadge.tsx, frontend/src/pages/Overview/OverviewPage.tsx
This replicates the status indicator for control plane components in the control plane card of OverviewPage.tsx.
For the card, the indicator icon is changed to match the icons used in the tooltip. The masthead indicator is unchanged.
The shown/hidden behavior of the indicator in the control plane card is the same as in the masthead: it is hidden if all components are OK, and it is shown if something has some potential issue.
Fixes #5525
=> Add Control Plane status indicator in Overview card

frontend/cypress/integration/common/navigation.ts, frontend/cypress/integration/common/service_details.ts, frontend/cypress/integration/featureFiles/service_details.feature
This is a little test case related [to this issue fix](https://github.com/kiali/kiali-ui/pull/2328) from 1.48.  
It toggles the node graph on the services/<detail>/ page and then checks that the graph type dropdown on the top of the page is disabled.
=> [Cypress] Mismatched node type graph fix testing

frontend/src/actions/MetricsStatsThunkActions.ts, frontend/src/components/Charts/ChartWithLegend.tsx, frontend/src/components/JaegerIntegration/JaegerScatter.tsx, frontend/src/components/JaegerIntegration/TraceTooltip.tsx
Trace scatter-chart tooltips pull stats from the backend to show heatmaps. Prevent flooding the backend with concurrent calls as the user drags across the chart:
- move launch of the backend request from the N tooltip components to the single JaegerScatter component, to be able to throttle the api calls. Add some callback props for this support.
- ensure the thunk action returns a promise and use it to preven the concurrent calls.
- ignore making calls for points that are just moused-over while moving across the chart.
- also, remove an unnecessary deprecated arg in Dashboard.tsx
Fixes http://github.com/kiali/kiali/issues/5584
=> Prevent flooding backend with concurrent calls as the user drags across trace chart

business/istio_config.go, config/config.go, kubernetes/filters.go
Issue https://github.com/kiali/kiali/issues/5594
Filtering K8s API Gateways to show only those ones which are pointing to GatewayClass created by Istio.
Using 'istio' as default GatewayClass Name to filter K8sGatgeways from Gateway API.
=> Filter K8sGateways by GatewayClass Names, which by default is 'istio'

business/checkers/services/port_mapping_checker.go, business/checkers/services/port_mapping_checker_test.go, business/services.go, frontend/src/components/CytoscapeGraph/MiniGraphCard.tsx, frontend/src/components/IstioConfigPreview/IstioConfigPreview.tsx, frontend/src/components/IstioWizards/ConfirmDeleteTrafficRoutingModal.tsx, frontend/src/components/IstioWizards/GatewaySelector.tsx, frontend/src/components/IstioWizards/K8sGatewaySelector.tsx, frontend/src/components/IstioWizards/K8sRequestRouting.tsx, frontend/src/components/IstioWizards/K8sRequestRouting/K8sMatchBuilder.tsx, frontend/src/components/IstioWizards/K8sRequestRouting/K8sMatches.tsx, frontend/src/components/IstioWizards/K8sRequestRouting/K8sRuleBuilder.tsx, frontend/src/components/IstioWizards/K8sRequestRouting/K8sRules.tsx, frontend/src/components/IstioWizards/K8sRouteHosts.tsx, frontend/src/components/IstioWizards/RequestRouting/Matches.tsx, frontend/src/components/IstioWizards/ServiceWizard.tsx, frontend/src/components/IstioWizards/ServiceWizardActionsDropdownGroup.tsx, frontend/src/components/IstioWizards/ServiceWizardDropdown.tsx, frontend/src/components/IstioWizards/WizardActions.ts, frontend/src/pages/Graph/GraphPage.tsx, frontend/src/pages/Graph/SummaryPanelNode.tsx, frontend/src/pages/ServiceDetails/ServiceDetailsPage.tsx, frontend/src/pages/ServiceDetails/ServiceInfo.tsx, frontend/src/services/Api.ts, frontend/src/services/__mockData__/getServiceDetail.ts, frontend/src/types/IstioConfigList.ts, frontend/src/types/IstioObjects.ts, frontend/src/types/ServiceInfo.ts, kubernetes/filters.go, models/service.go
RFE https://github.com/kiali/kiali/issues/5502
Added a feature of Creating, Reading, Updating and Deleting of K8s Gateway API Routes for Service details page.
Currently it can create only  "Match" Rules from https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1beta1.HTTPRouteRule
The rest of supported filters will be added in further PRs.
The feature can be reviewed now.
There is one bug code now about auto created default "path PathPrefix /" match which is under investigation.
=> Adding Gateway API support into Service Wizard

frontend/src/components/Overview/TLSInfo.tsx, frontend/src/pages/Overview/OverviewPage.tsx
Fixes #5597
Adding information tooltip: 
Also, if serverConfig.kialiFeatureFlags.certificatesInformationIndicators.enabled is false, not shows the tooltip with certificates information in the lock icon
=> Improvements in CP card for min TLS

business/authentication/session_persistor_test.go
Fix for https://github.com/kiali/kiali/issues/5197
Instead of checking Contains cookie value, now it checks equals cookie value + checks contains the cookie json.
=> Fixing flaky session test.

config/version-compatibility-matrix.yaml, status/versions_test.go
need to backport this to v1.59 and build a new v1.59.1 so we can support Istio 1.16.1 when it is release (we missed the train for istio 1.16.0).
=> compat matrix for istio 1.16

config/version-compatibility-matrix.yaml, status/versions_test.go
backport of https://github.com/kiali/kiali/pull/5628
=> [v1.59] compat matrix for istio 1.16

business/metrics.go, frontend/src/actions/MetricsStatsThunkActions.ts, frontend/src/components/JaegerIntegration/JaegerResults/SpanTable.tsx, frontend/src/components/JaegerIntegration/JaegerResults/StatsComparison.tsx, frontend/src/components/JaegerIntegration/JaegerResults/TraceDetails.tsx, frontend/src/components/JaegerIntegration/JaegerScatter.tsx, frontend/src/components/JaegerIntegration/TraceTooltip.tsx, frontend/src/components/JaegerIntegration/TracesComponent.tsx, frontend/src/types/Metrics.ts, frontend/src/types/MetricsOptions.ts, frontend/src/utils/tracing/TraceStats.ts, frontend/src/utils/tracing/__tests__/TraceStats.test.ts
Fixes https://github.com/kiali/kiali/issues/5634
This PR introduces BEHAVIORAL CHANGE:  
- reduce the trace scatter chart tooltips to use "compact" heatmaps
- a compact heatmap is 2 x 3 as opposed to the previous 3 x 4 [60m,3h] x [avg,50%,90%] vs [10m,60m,6h] x [avg,50%,90%,99%]
- we fetch only what we need.  it's less information that before but hopefully enough to indicate if it's an interesting trace
- we still fetch the full stats when the user clicks a trace
- but note that we have replaced 6h with 3h.  This means prom needs to read/aggregate ~50% less data per query.
- the trace detail span table will also render the 2 x 3.  This is more for simplicity/consistency than perf, because we are alerady fetching the full stats for a selected trace. Server Side:
- Chunk the prometheus …
=> [perf] reduce computation needs of Kiali heatmap tooltips

frontend/src/components/Link/KioskLink.tsx, frontend/src/components/Link/ServiceLink.tsx, frontend/src/components/Link/WorkloadLink.tsx, frontend/src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx, frontend/src/pages/IstioConfigDetails/IstioObjectDetails/IstioConfigOverview.tsx, frontend/src/pages/IstioConfigDetails/IstioObjectDetails/IstioConfigReferences.tsx
RFE https://github.com/kiali/openshift-servicemesh-plugin/issues/52
Kiosk mode for config views made read-only.
Fixed kiosk mode Workload and Service links in Istio Config Overview page
=> Kiosk mode for config views made read-only.

hack/run-molecule-tests.sh
part of https://github.com/kiali/kiali/issues/5611
=> the CI script used to run the molecule tests needs to set up the header and openid tests using new role

business/apps.go, frontend/src/components/Details/DetailDescription.tsx, frontend/src/components/MissingSidecar/MissingSidecar.tsx, frontend/src/components/VirtualList/Config.ts, frontend/src/components/VirtualList/Renderers.tsx, frontend/src/helpers/LabelFilterHelper.ts, frontend/src/helpers/__tests__/LabelFilterHelper.test.ts, frontend/src/pages/ServiceDetails/ServiceDescription.tsx, frontend/src/pages/WorkloadDetails/WorkloadDescription.tsx, frontend/src/types/App.ts, models/app.go
Original issue happens in Service Mesh and is: When there is additional Ingress Gateways created not in control plane namespace, it shows warning "Missing Sidecar" on that Gateway's Workload and Application List and Details pages.
Before:
This fix is ignoring showing "Missing Gateways" on any Workload or Application which contains label "istio=ingressgateway". This label value is hardcoded for now.
After:
To test this on Kiali upstream, it needs to create any Deployment on some namespace besides "istio-system" and make sure that it does not have sidecar injected and has label "istio=ingressgateway".
=> Skip "Missing Sidecar" on Ingress Gateways from all namespaces.

frontend/cypress/integration/common/overview.ts, frontend/cypress/integration/featureFiles/overview.feature
One of the tests for the new features added in the OSSM 2.3 version of Kiali
The test checks the new Control plane for Istio in the overview page. It also checks some additional links in its kebab menu, which are not available in the other namespaces.
=> Added smoke test for the new Overview page brought in 1.57.

frontend/src/actions/MetricsStatsThunkActions.ts, frontend/src/components/Charts/ChartWithLegend.tsx, frontend/src/components/JaegerIntegration/JaegerScatter.tsx, frontend/src/components/JaegerIntegration/TraceTooltip.tsx
v1.57 Backport of https://github.com/kiali/kiali/pull/5600
Trace scatter-chart tooltips pull stats from the backend to show heatmaps.
Prevent flooding the backend with concurrent calls as the user drags across the chart:
- move launch of the backend request from the N tooltip components to the single JaegerScatter component, to be able to throttle the api calls. Add some callback props for this support.
- ensure the thunk action returns a promise and use it to preven the concurrent calls.
- ignore making calls for points that are just moused-over while moving across the chart.
http://github.com/kiali/kiali/issues/5584
=> [v1.57] Trace scatter-chart tooltips pull stats from the backend to show heatmaps

hack/istio/install-error-rates-demo.sh, hack/istio/install-fraud-detection-demo.sh, hack/istio/install-testing-demos.sh, hack/istio/install-travel-agency-demo.sh
Adding waiting for smmr being ready before enabling side car injection so the pods are restarted to pick up a side car. We already have this in master.
=> [v1.57] An attempt to fix timing issue resulting in missing side car

frontend/src/components/IstioWizards/K8sRequestRouting.tsx, frontend/src/components/IstioWizards/K8sRequestRouting/K8sFilterBuilder.tsx, frontend/src/components/IstioWizards/K8sRequestRouting/K8sFilters.tsx, frontend/src/components/IstioWizards/K8sRequestRouting/K8sMatchBuilder.tsx, frontend/src/components/IstioWizards/K8sRequestRouting/K8sRuleBuilder.tsx, frontend/src/components/IstioWizards/K8sRequestRouting/K8sRules.tsx, frontend/src/components/IstioWizards/K8sTrafficShifting.tsx, frontend/src/components/IstioWizards/WizardActions.ts, frontend/src/components/IstioWizards/WizardHelp.tsx, frontend/src/types/IstioObjects.ts
RFE https://github.com/kiali/kiali/issues/5502
Added a new tab in K8s Gateway API Routing wizard: "Route Filtering".
It supports only "RequestHeaderModifier" type of filtering so far. The rest of filter types will be added in further PRs.
=> Added K8s Route Filtering into wizard

frontend/cypress/integration/common/apps.ts, frontend/cypress/integration/common/workloads.ts, frontend/cypress/integration/featureFiles/apps.feature, frontend/cypress/integration/featureFiles/workloads.feature
Some minor additions to existing tests. All of these are visual regression tests. This PR contains small test on the Apps page and also filtering on the Workloads page by app and version labels, which was not present before. 
I'll turn this as "Ready for review" if the CI won't fail.
=> [Cypress] Minor improvements regarding visual regression testing

business/istio_validations_test.go, business/layer.go, business/test_util.go, business/workloads.go, business/workloads_test.go, config/config.go, kubernetes/cache/cache.go, kubernetes/cache/cache_test.go, kubernetes/cache/cachingclient.go, kubernetes/cache/istio.go, kubernetes/cache/istio_test.go, kubernetes/cache/kubernetes.go, kubernetes/cache/kubernetes_test.go, kubernetes/client.go, kubernetes/kubernetes.go, kubernetes/kubetest/fake.go, util/httputil/port_forwarder.go
Relates to #5599. Splitting out the changes into multiple PRs to make the more reviewable.
This PR also fixes some race conditions present in the cache.
=> Use cache only for workload service

business/proxy_logging.go, business/proxy_status.go, business/workloads.go, handlers/proxy_logging_test.go, kubernetes/cache/cache.go, kubernetes/cache/cache_test.go, kubernetes/cache/proxy_status.go
Helps mitigate #5669 by fetching proxy status continually every 10 seconds rather than fetching it only when it's asked for. This will limit the amount of times the proxy status service will attempt to port forward to istiod.
=> Poll for proxy status continually rather than fetching lazily

frontend/src/components/DebugInformation/DebugInformation.tsx, frontend/src/components/Tab/Tabs.tsx
- apply standard formatting to DebugInformation.tsx
- alphabetize DebugInformationState
- ensure modal always opens with default tab
- simplify change to Tabs component, instead of adding new "skipHistory" property, make "tabName" an optional property
=> Minor post-merge follow-up for kiali-5588 PR

graph/types.go
It seems there is a legitimate case (possibly with a newer version of Istio, I'm not sure) where the telemetry may have app set, but not workload or service.  Possibly when the workload is not injected but app/version labeling is still applied to the workload.
In this case, avoid a graph-gen panic when trying to generate a workload graph node, and instead default to an Unknown service node.  Panics don't really help anyone, so anything we can do to avoid that situation is, I think, better.
Closes https://github.com/kiali/kiali/issues/5696
=> Avoid graph generation panic scenario

business/checkers/k8sgateways/multi_match_checker.go, business/checkers/k8sgateways/multi_match_checker_test.go, models/istio_validation.go
Fixes #5710 
It is currently no possible to create a k8s gw with no listeners: 
`
error: error validating "/home/jcordoba/dev/deployments/k8sgwwrong.yaml": error validating data: ValidationError(Gateway.spec): missing required field "listeners" in io.k8s.networking.gateway.v1beta1.Gateway.spec; if you choose to ignore these errors, turn validation off with --validate=false`
So, no extra validation was done in this PR.
=> Add unique listener per GW

business/istio_validations.go, business/references/k8shttproute_references.go, business/references/k8shttproute_references_test.go
RFE https://github.com/kiali/kiali/issues/5709
References to K8s Gateways and Services in K8s HTTPRoute object details page.
=> Added Gateway and Service references in HTTPRoute object details

frontend/src/pages/WorkloadDetails/WorkloadPodLogs.tsx, handlers/proxy_logging.go
Fixes #5714 
In view only mode disable the option to set the log level: 
Note: There is no change in kiosk mode.
=> Disable set log level dropdown in view only mode

frontend/src/components/IstioWizards/WizardActions.ts, models/workload.go
removes annotation when adding auto-injection label
part of: https://github.com/kiali/kiali/issues/5713
backport of: https://github.com/kiali/kiali/pull/5718
=> [v1.57] better workload auto-injection label/annotation processing

config/version-compatibility-matrix.yaml, status/versions_test.go
part of https://github.com/kiali/kiali/issues/5773
We need to backport this to 1.63 branch - that is this PR: https://github.com/kiali/kiali/pull/5775
=> update compatibility matrix for istio 1.17

config/config.go
This small change will prevent reading (unmarshalling) the kubernetes_config.cache_enabled configuration from a YAML file (i.e. from a Kubernetes ConfigMap).
This effectively makes it impossible to disable Kiali's kube cache via the usual configuration mechanism. This will allow to write new code under the assumption that the kube cache is always enabled (i.e. no more if/else conditionals around this configuration variable).
The kube cache can still be disabled programmatically. This will allow to gradually update existing code to stop relying on the removed configuration (most notably, unit tests need to be adapted).
Related #5599
=> No longer read kubernetes_config.cache_enabled config

business/apps_test.go, business/health_test.go, business/istio_status_test.go, business/test_util.go, business/workloads.go, business/workloads_test.go, graph/telemetry/istio/appender/dead_node_test.go, graph/telemetry/istio/appender/health_test.go, graph/telemetry/istio/appender/labeler_test.go, graph/telemetry/istio/appender/sidecars_check_test.go, handlers/workloads_test.go
The fetchWorkload(s) funcs used the business layer k8s rather than the workload service's k8s. This resulted in the fetchWorkload(s) funcs not using the caching client and causing a perf regression since fetchWorkloads called the API server directly rather than pulling from the kube cache.
Fixes #5743
=> Fix caching when fetching workloads

business/jaeger.go, config/config.go, frontend/src/components/JaegerIntegration/TracesDisplayOptions.tsx, jaeger/client.go
- Do not inflate the query limit for workload and service trace queries, it is misleading on the client and can cause unexpected timeout.
- Add info tooltip in Traces Display dropdown to better explain query limit
- fix tooltip styling and position for the existing menu
Part-of  https://github.com/kiali/kiali/issues/5751
**OPERATOR PR**: https://github.com/kiali/kiali-operator/pull/610
=> Honor configured timeout for calls to tracing API

frontend/package.json, frontend/src/index.tsx, frontend/src/polyfills.ts, frontend/yarn.lock
The '@webcomponents/custom-elements' package has been removed from the 'package.json' file since Firefox ESR supports it natively.
this issue reference to https://github.com/kiali/kiali/issues/5805
=> Remove @webcomponents/custom-elements package

hack/istio/multicluster/deploy-kiali.sh, hack/istio/multicluster/env.sh, hack/istio/multicluster/start-minikube.sh
be able to build your own kiali dev image and have that be used in the MC set up.
See the `--kiali-use-dev-image` option. You need to make sure you build a dev image on your local box (`make build build-ui`) and then ensure its container is built and tagged as `quay.io/kiali/kiali:dev` (which is the default, anytime you do `make container-build` or `make cluster-push` this happens, you can even just do `make container-build-kiali` to just build the server image).
=> [hack] support dev images in mc script

Makefile, go.mod
This change updates the Kiali codebase to use Go 1.19 instead of Go 1.18 as the build environment. The reason for this change is that Go 1.18 is considered deprecated and is no longer receiving patches, making it less stable and compatible than more recent versions of the Go language.
_explanation of what it does_
This pull request updates the Kiali codebase to build with Go 1.19 instead of Go 1.18. Go 1.18 is should be considered as deprecated and no longer receives patches, so updating to a newer and maintained version will ensure stability and compatibility for Kiali.
Changes:
- Update the build scripts to specify Go 1.19 as the target version.
- Test the build process and application functionality with Go 1.19.
- have tested these changes on multiple …
=> Update Kiali to build with Go 1.19

business/health.go, business/health_test.go, business/layer.go, kubernetes/kubetest/mock.go
Removes unused k8s dep from health service and refactors the test to use fake client instead of mocks.
Relates to #5599
=> Remove unused deps from health svc and refactor tests

hack/istio/install-istio-via-istioctl.sh
Since Istioctl uninstall is now officially supported, it is possible to remove experimental scope (x) from istio uninstall command.
[hack] use the official istioctl uninstall command now (#5429) 
** Testing **
Execute './hack/istio/install-istio-via-istioctl.sh -di true' to uninstall istio with stable command.
=> Remove experimental scope for istio uninstall command

frontend/cypress/integration/common/apps.ts, frontend/cypress/integration/common/istio_config.ts, frontend/cypress/integration/featureFiles/apps.feature, frontend/cypress/integration/featureFiles/istio_config.feature
This PR is related to 2 flaky tests on OCP.
These tests expected exactly one item to be present after filtering, but there are more items present due to Gateway API being used. Now the tests expect variable number of items.
=> [Cypress] Fix for test flakes introduced by the presence of the Gateway API

business/authentication/openid_auth_controller.go
openid authentication was raising an error message even when the authentication is successful. The message is useful for diagnose purposes just in case the authentication failed, so changing the message log level to debug.
=> Change log level to debug in openid auth controller

handlers/proxy_status.go, kubernetes/istio.go
I'm not sure if this is fair. I'm anyway suggesting these.
This is doing two fixes:
* In istio.go some messages are moved from ERR level to TRACE level. Apparently, when these funcs fail because of the user not having enough privileges, Kiali will retry using its ServiceAccount. So, these messages are not that useful unless something weird happened.
* In proxy_status.go config dumps are now retrieved using the Kiali ServiceAccount rather than the token of the logged-in user. This is for the "Envoy" tab of Workloads to work properly if the user has "less" privileges.
Related #5720
=> RBAC-related fixes

make/Makefile.build.mk
the linter used in this branch does not work with go 1.19. If we upgrade, we'll get a bunch of errors from the linter that we do not want to fix in this branch. So this PR disables the linter.
=> [1.48] disable linter

make/Makefile.build.mk
the linter used in this branch does not work with go 1.19. If we upgrade, we'll get a bunch of errors from the linter that we do not want to fix in this branch. So this PR disables the linter.
=> [1.57] disable linter

frontend/cypress/integration/common/wizard_istio_config.ts, frontend/cypress/integration/featureFiles/wizard_istio_config.feature
Tests related to the #5811 issue. This suite increases coverage of the wizard menu for the ServiceEntries and Gateways in the Istio config section of Kiali. The tests cover creation of said objects, tests of the text fields for valid and invalid values and also tests that object of same name cannot be created twice. Currently not sure if I should implement a teardown of some sort to clean the created objects after the suite is completed.
=> [Cypress] Istio Config page wizard coverage

hack/setup-kind-in-ci.sh
Ref. https://github.com/kiali/kiali/issues/5846
Revert the specific Istio version in setup Kind script, now the latest image is available in gcr.io
=> Revert specify Istio image in setup kind ci hack script

README.adoc
fixes: https://github.com/kiali/kiali/issues/5818
This is the new section: https://github.com/kiali/kiali/blob/177125ebcd374b431b5fa7787f44aa5745bbe491/README.adoc#upgrading-go
=> document how to upgrade the project to a new Go version

business/checkers/gateways/multi_match_checker.go, business/checkers/gateways/multi_match_checker_test.go, config/config.go
RFE: https://github.com/kiali/kiali/issues/5711
Added new option "skip_wildcard_gateway_hosts" to skip "KIA0301 More than one Gateway for the same host port combination" validation for Gateways with wildcard in hostname.
How to test:
Create 3 Gateways:
1. Hostname: host.com
2. Hostname: *
3. Hostname: host.com
Verify that all 3 Gateways are showing warning and references to each other.
Change "skip_wildcard_gateway_hosts: true"
Verify that Gateway number 2 with wildcard is not in validation warnings and references anymore.
=> Add new option to skip KIA0301 for Gateways with wildcard hosts.

frontend/src/components/Nav/RenderPage.tsx
Convert simple render error message to a more visual one (adding error icon and return to last page button).
Closes #5862 
** Testing **
Just adding `throw new Error()` in componentDidMount() method of any rendered page (e.g., OverviewPage) to cause an intentional error and see the error message.
=> Beautify render error message

business/apps_test.go, business/test_util.go
The adaptation moves from using mocks to using a fake client. This allows for starting a cache where the underlying client is a fake, making it possible to allow the code to use "caching" as with the real client.
Related #5599
=> Adapt apps_test.go to not rely on turning off the cache

graph/api/api.go, graph/config/cytoscape/cytoscape_test.go, graph/telemetry/istio/appender/aggregate_node.go, graph/telemetry/istio/appender/aggregate_node_test.go, graph/telemetry/istio/appender/dead_node_test.go, graph/telemetry/istio/appender/health_test.go, graph/telemetry/istio/appender/idle_node.go, graph/telemetry/istio/appender/idle_node_test.go, graph/telemetry/istio/appender/istio_details_test.go, graph/telemetry/istio/appender/labeler_test.go, graph/telemetry/istio/appender/response_time.go, graph/telemetry/istio/appender/response_time_test.go, graph/telemetry/istio/appender/security_policy.go, graph/telemetry/istio/appender/security_policy_test.go, graph/telemetry/istio/appender/service_entry.go, graph/telemetry/istio/appender/service_entry_test.go, graph/telemetry/istio/appender/sidecars_check_test.go, graph/telemetry/istio/appender/throughput.go, graph/telemetry/istio/appender/throughput_test.go, graph/telemetry/istio/appender/workload_entry_test.go, graph/telemetry/istio/istio.go, graph/types.go, tools/generator/generator.go
Fixes https://github.com/kiali/kiali/issues/5890
Don't let the graph generation panic on unexpected/corrupt telemetry.  Instead, add error return values as needed, and use then to skip over the bad telem.  The change here is fairly straightforward but it touches a lot of files, many test files, because the call signatures change for a few commonly used functions in graph generation.
=> Don't let the graph generation panic on unexpected/corrupt telemetry.

hack/istio/multicluster/env.sh, hack/istio/multicluster/install-multi-primary.sh, hack/istio/multicluster/install-primary-remote.sh, hack/istio/multicluster/prometheus.yaml, hack/istio/multicluster/start-minikube.sh
This PR adds the workaround for Metallb (needed until the next Minikube release) in the start-minikube script so both hack scripts to install primary-remote and multi-primary can benefit from it.
Also, adds the same logic to federate west's Prometheus into East's.
Finally, the default value for the generation of cross gateways (eastwest-gateway) is default to true as this is needed for proper communication between services across clusters.
=> Changes to the multi-primary hack script

kubernetes/cache/kube_cache.go, kubernetes/cache/kube_cache_test.go, kubernetes/client.go, kubernetes/kubernetes.go, kubernetes/kubetest/fake.go, kubernetes/kubetest/mock.go
Resolves #5939.
Similarly to the GatewayAPI logic, this PR adds the same for Istio APIs. This will be necessary for the remote clusters where is not mandatory to have the CRDs installed.
The following is an example of a Primary-Remote setup with Kiali working ok:
=> Check if Istio API (CRDs) are defined to cache them

business/mesh.go, business/mesh_test.go
Check for nil before accessing limits. Return error when deployment not found. Report binary resources correctly. Add tests.
Fixes #5742
=> Fix panic in istiod resource thresholds

make/Makefile.operator.mk
fixes: https://github.com/kiali/kiali/issues/5950
When you run `make run-operator` and you see the operator finish reconciling, this kind of report should now appear in the output logs:
```
Tuesday 28 March 2023  08:23:53 -0400 (0:00:00.941)       0:00:00.990 ********* 
=============================================================================== 
Get all Kiali CRs ------------------------------------------------------- 0.94s
[.... and a whole bunch of other tasks and their times will be here...]
/home/jmazzite/source/kiali/kiali/operator/playbooks/kiali-new-namespace-detected.yml:18 
```
=> [make] turn on profiler when running the operator via run-operator

frontend/src/components/Pf/PfBadges.tsx
Follow up PR after https://github.com/kiali/kiali/pull/5944#issuecomment-1492348024
Cluster badge color is set to blue darker than Container badge.
=> Blue badge background for Cluster

hack/istio/functions.sh, hack/istio/install-bookinfo-demo.sh, hack/istio/install-error-rates-demo.sh, hack/istio/install-fraud-detection-demo.sh, hack/istio/install-testing-demos.sh, hack/istio/install-travel-agency-demo.sh
OSSM cluster wide mode has a different approach for member namespace management. This change is updating demo apps hack scripts to follow that.
Also the prepare_maistra functions has been moved to external script.
=> Update demo apps hack scripts to support OSSM cluster wide mode

hack/istio/functions.sh, hack/istio/install-bookinfo-demo.sh, hack/istio/install-error-rates-demo.sh, hack/istio/install-fraud-detection-demo.sh, hack/istio/install-testing-demos.sh, hack/istio/install-travel-agency-demo.sh
Update demo apps hack scripts to support OSSM cluster wide mode OSSM cluster wide mode has a different approach for memeber namespace management. This change is updating demo apps hack scripts to follow that.
Also the prepare_maistra functions has been moved to external script.
=> [1.65]Update demo apps hack scripts to support OSSM cluster wide mode

frontend/reporter-config.json, hack/istio/download-istio.sh
We need to extend XML reporting for polarion. Following changes are related only to XML reports from Cypress. This setting is tested locally.
Also small fix recommended by @jmazzitelli in shell script to download the istio from correct URL.
=> XML reporting upgrade + get istio shell script fix

frontend/cypress/integration/featureFiles/app_details.feature, frontend/cypress/integration/featureFiles/graph_display.feature, frontend/cypress/integration/featureFiles/graph_toolbar.feature, frontend/cypress/integration/featureFiles/istio_config_editor.feature, frontend/cypress/integration/featureFiles/istio_config_type_filters.feature, frontend/cypress/integration/featureFiles/istio_config_validation_filters.feature, frontend/cypress/integration/featureFiles/kiali_cookie.feature, frontend/cypress/integration/featureFiles/kiali_homepage.feature, frontend/cypress/integration/featureFiles/kiali_login.feature, frontend/cypress/integration/featureFiles/service_details.feature, frontend/cypress/integration/featureFiles/services.feature, frontend/cypress/integration/featureFiles/workloads.feature
Polarion cannot process generated XML files from Cypress due to duplicate names of scenarios. This change removes all duplicate scenario names. Functionality was not changed.
=> [OSSM-3538] removed duplicate scenario names

.dockerignore, tests/integration/Dockerfile, tests/integration/run-tests.sh
Image produced by this Dockerfile will be used by the interop pipeline in OpenShift CI.
We can add targets for building and pushing to the makefile later. This is just to test integration with openShiftCI.
=> [OSSM-3496]Adding a Dockerfile for integration tests to be used with OpenShiftCI

hack/setup-kind-in-ci.sh
Without this patch releases fail to install the kiali helm chart because `SNAPSHOT` is not present when you run the workflow from the patch release.
=> Remove SNAPSHOT from chart glob in CI script

tests/integration/Dockerfile
We need to set HOME when running on OCP with random UID, otherwise the home is set to / and any writing there will fail with permission denied
=> Fixing integration tests dockerfile for OCP

frontend/src/reducers/NamespaceState.ts
This combines all namespaces of the same name in the namespace dropdown. This should also fix the problem of duplicate entries showing up on the list pages. This works because the Kiali API makes a list call per namespace selected in the dropdown. On the backend, the business services will reach out to every connected cluster returning the aggregated results across each. Now that there are no longer duplicate namespaces in the dropdown and there's only one list call per namespace regardless of how many clusters that namespace appears in, we no longer see duplicate entries for workloads.
Fixes #6007
=> Multicluster - Filter duplicate namespaces in namespace dropdown

GOVERNANCE.md
See Discussion https://github.com/kiali/kiali/discussions/6014
Fernando has 6 votes FOR and 0 AGAINST, from 9 current maintainers.  Congratulations, Fernando, you are the newest Kiali Maintainer!
=> Add Fernando Hoyos as a Kiali Maintainer

business/apps_test.go, business/layer.go, business/mesh.go, business/mesh_test.go, business/namespaces.go, business/namespaces_test.go, business/services_test.go, config/config.go, kiali.go, kiali_test.go, kubernetes/cache/cache.go, kubernetes/cache/cache_test.go, kubernetes/cache/kube_cache.go, kubernetes/client.go, kubernetes/client_factory.go, kubernetes/cluster_secret_test.go, kubernetes/istio.go, kubernetes/istio_internal_test.go, kubernetes/istio_test.go, kubernetes/kubetest/fake.go, kubernetes/kubetest/mock.go
Adds an option to the Kiali config to provide the kube cluster name for the home cluster. Defaults to `Kubernetes`. In the future, Kiali could auto-detect this value from the environment.
Fixes #6001
=> Add kube cluster name to Kiali config

frontend/src/pages/WorkloadDetails/WorkloadPodLogs.tsx
Fixes https://github.com/kiali/kiali/issues/5989 
I was able to reproduce this issue in Firefox (111.0.1), but not in Chrome (112.0.5615.49). 
Firefox view: 
Chrome: 
I've tried to use the Grid (https://github.com/bvaughn/react-virtualized/blob/master/docs/Grid.md) instead of the List, but I had the same issue in Firefox. 
The Container style has the following: 
`overflow: auto`
An for firefox: 
`overflow: hidden auto`
Setting the overflow to auto seems to do the trick:
=> Adjust scroll for Workload Pod Logs

business/namespaces.go, config/config.go, kubernetes/cache/kube_cache_test.go, kubernetes/cache/tls_test_helper.go, kubernetes/istio.go, kubernetes/istio_test.go, kubernetes/types.go
fixes: https://github.com/kiali/kiali/issues/3914
operator PR: https://github.com/kiali/kiali-operator/pull/628
The Istio ConfigMap has discoverySelectors that Kiali will now use to filter namespaces.
If no discoverySelectors are specified, or discoverySelectors is specified as an empty list in the ConfigMap, then Kiali works as before.
If discoverySelectors are specified, then they will filter out any namespaces that do not match. After that filter is performed, Kiali will further exclude namespaces defined in the excludes config settings in the Kiali CR (this works as before).
=> use discovery selectors to filter namespaces

frontend/cypress/integration/common/wizard_istio_config.ts, frontend/cypress/integration/featureFiles/wizard_istio_config.feature
This PR is an automation for #5868. The PR contains 2 tests. One of them is checking if the validations are present when 2 K8s Gateways with same ports and hosts are created. The other test then deletes one of the gateways and checks that the validations are no longer present. 
Related to #5853.
(works for the upstream OCP, not sure about the CI yet)
=> Automation of a test procedure related to multiple K8 Gateways with same ports and hosts at the same time

business/istio_config.go, business/istio_config_test.go, business/mesh.go, business/services.go, frontend/src/pages/Overview/OverviewPage.tsx, frontend/src/pages/Overview/OverviewTrafficPolicies.tsx, frontend/src/services/Api.ts, handlers/istio_config.go, handlers/namespaces.go
- Use the k8s client from the user to check for permissions 
- For Alpha support, writes will be disabled in remote clusters
- Use the cluster to validate permissions
Fixes #5765
How to test: Update namespaces (Enable/disable Auto injection), Create traffic policies, should be possible for the local cluster (If the user has permissions) but not for the remote clusters.
=> Use cluster parameter for permissions check

.dockerignore, tests/integration/Dockerfile
We will use also hack scripts to install bookinfo via this image. Also 'which' package was missing and it is needed for the bookinfo install script.
=> [v1.57] We also need hack scripts and 'which' package for bookinfo install

business/apps.go, frontend/src/pages/AppDetails/AppDescription.tsx, frontend/src/pages/ServiceDetails/ServiceDescription.tsx, frontend/src/pages/WorkloadDetails/WorkloadDescription.tsx, frontend/src/types/App.ts, frontend/src/types/ServiceInfo.ts, models/app.go
At the moment I have kept just the "C", but it can changed easily. 
Moved the cluster name to the header bottom to have space for larger cluster names. 
Fixes #6059
=> Multicluster - Cluster badge and cluster name in details pages 

make/Makefile.olm.mk
The CSV was changed last year but we didn't realize it broke the make target to test on OLM. See: https://github.com/kiali/kiali-operator/pull/577
=> [make] fix olm-operator-create target so it works again.

business/namespaces.go, handlers/istio_config.go
Fixes https://github.com/kiali/kiali/issues/6084
Prevent scenario where a token's namespaces cache can be set to the unfiltered namespaces for a single cluster.
I think this problem emerged gradually, due to a couple of things.
1) We introduced business.namespaces.go#GetNamespacesByCluster()
This method supports GetNamespaces() and is called for each cluster such that the parent can get the cross-cluster list.  I think there were two problems here.  First, it was declared public but really should have been private because it really should only be consumed by GetNamespaces to be launched as a gofunc.  Second, and more importantly, it sets the token's namespace cache to the partial, unfiltered list of namespaces for one cluster.  I'm pretty sure this was just a mistake.  Although …
=> Prevent crash scenario in namespace management

frontend/package.json, frontend/src/components/VirtualList/Config.ts, frontend/src/components/VirtualList/Renderers.tsx, frontend/src/pages/Overview/OverviewCardSparklineChartsComponent.tsx, frontend/src/pages/Overview/OverviewPage.tsx
Resolves https://github.com/kiali/kiali/issues/5921.
This PR adds the cluster badge to all views. It also fixes a problem in list view that wasn't showing the control plane metrics.
=> Cluster badge on the Overview page

business/namespaces.go
**Backport** of https://github.com/kiali/kiali/pull/6085
Prevent scenario where a token's namespaces cache can be set to the unfiltered namespaces for a single cluster.
I'm not 100% sure v1.67 suffers from a problem because the call from istio_config is not yet made, but this should ensure the problem does not happen in an unanticipated scenario.
https://github.com/kiali/kiali/issues/6084
=> [v1.67] Prevent bad namespaces cache scenario (#6085)

business/layer.go, business/services.go, business/tls.go, business/tls_perf_test.go, business/tls_test.go, frontend/src/components/MTls/MeshMTLSStatus.tsx, frontend/src/pages/Overview/OverviewPage.tsx, frontend/src/services/Api.ts, handlers/tls.go
Subtask https://github.com/kiali/kiali/issues/6064
All 'namespace/tls' requests into backend are containing 'cluster' param.
Can be seen in Overview page:
mTLS request for the home cluster does not send 'cluster' param and the default home cluster name is chosen backend.
Consider this [logged issue](https://github.com/kiali/kiali/issues/6063) when verifying mTLS for namespace only, as the created PeerAuth will be shown for same named namespaces in all clusters, thus all same named namespaces will be considered as enabled mTLS.
=> Cluster support for mTLS

frontend/src/components/Details/DetailDescription.tsx, frontend/src/pages/ServiceDetails/ServiceDescription.tsx
Issue https://github.com/kiali/kiali/issues/6127
How to test:
App, Workload and Service details page's Overview sections contain cross links, which should contain `cluster` param.
=> Added missing cluster params in Service/App Details pages links

business/istio_config.go, frontend/src/hooks/services.ts, frontend/src/pages/WorkloadDetails/WorkloadInfo.tsx, frontend/src/services/Api.ts
Fix for https://github.com/kiali/kiali/issues/6063
Skipping Registry usage for now for remote clusters because still the home cluster istiod is called when loading from registry.
Now the configs are not duplicated between clusters.
Tested also in primary remote mode when Istio CRDs are installed (https://raw.githubusercontent.com/istio/istio/master/manifests/charts/base/crds/crd-all.gen.yaml)
=> Skip loading istio configs from registry for remote clusters.

frontend/cypress/integration/common/sidecar_injection.ts, frontend/cypress/integration/common/wizard_istio_config.ts
- also, reformatting automatically applied, sorry, but I guess it's necessary.
https://issues.redhat.com/browse/OSSM-3940
If this passes upstream CI we need to backport to 2.4 (v1.65 branch) to try and get OCP CI to pass.
=> Try to fix flakes by ensuring button visibility before click

frontend/src/components/CytoscapeGraph/graphs/GraphStyles.ts
Closes #6123 
Relates To #5922
In the graph, replace parenthesized label information with properly PF badged content.  This is for when labels add namespace and/or cluster disciminators to ensure label uniqueness.  
To test you need to generate situations where labels would previously use the parenthesized information for namespace/cluster discriminator.  Some ways of doing this:
- multi-cluster
- select multiple namespaces for the graph
- remove namespace and/or cluster boxing
Negative testing may also be useful, to ensure unnecessary badging doesn't now appear.  Different graph types, enable boxing, single namespace, single cluster, etc.
=> Improve graph labels with PF badges instead of parentheses

frontend/cypress/README.md
Adding readme section which describes how to run cypress tests in a container
=> Adding readme for cypress tests in a container

hack/ci-minikube-molecule-tests.sh
This test requires the operator to allow security context override; when installing the operator via OLM we need to enable that feature.
fixes: https://github.com/kiali/kiali/issues/6155
=> fix the config-values-test molecule test when testing with OLM

frontend/src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
There was some code that was removed, because it was expecting a link to a remote kiali instance, but in this case, we want the link to be in this Kiali instance (We are just expecting one)
Fixes #6150
=> Add contextual menu for read links for remote clusters 

business/apps.go, business/istio_config.go, business/workloads.go, frontend/src/pages/WorkloadDetails/WorkloadInfo.tsx, models/istio_config.go
Issue https://github.com/kiali/kiali/issues/6136
App and Workload lists pages are sending request to backend to load items per namespace and for all clusters,
and they require also loading Istio configs per Workload and App to be shown in Details column.
Before: Istio configs were loaded for all clusters, which was causing a mess.
Now: Istio configs are loaded per cluster.
New method 'GetIstioConfigMap' is introduced, this method will replace 'GetIstioConfigList' in further task: https://github.com/kiali/kiali/issues/6052
Loading workload validations is disabled, because it is never used, we have a task for this: https://github.com/kiali/kiali/issues/6020
How to test:
Create a PeerAuth in 'west' cluster, it should not be shown in 'east' clsuter's Workloads and Applications.
``` …
```
=> Workload and App lists are loading Istio configs per cluster.

handlers/config.go
Fix accessibleNamespaces typo in handlers/config.go
Fixes #6160.
** Test steps **
In any Kiali application page:
Open chrome developer tools and go to Network tab
Search for config API request
Check the accessibleNamespaces field in the response contains two 's' instead of only one.
=> Fix accessibleNamespaces typo
