kiali/kiali

README.adoc
describe more about nodejs version control to avoid `kiali-ui` build with failure.
=> chore: describe more to nodejs version

PULL_REQUEST_TEMPLATE.md
(a) what is broken or missing?
Fix markdown errors
(b) what the new code is doing to fix it?
Update PR template
Before: 
After:
=> chore: fix markdown errors and update PR template

doc.go, kiali_api.md, swagger.json
(a) what is broken or missing?
`boxBy` and `appenders` default values are not `none` and `run all appenders`
(b) what the new code is doing to fix it?
set default to empty in `boxBy` and `appenders`
=> fix(boxBy-appenders):  update and set default to empty

business/checkers/virtualservices/single_host_checker.go
Fix for issue https://github.com/kiali/kiali/issues/4652
Now the "KIA1106 More than one Virtual Service for same host" is shown correctly for cross-namespace cases, and validations references are shown.
=> Fixed issue with missing error KIA1106 VS host duplications and references to validations.

design/KEPS/kiali-enhancement-proposal/proposal.md
Establishes a process to propose enhancements to the Kiali project.
[discussion](https://github.com/kiali/kiali/discussions/4208)
=> KEP - Establish KEP process

make/Makefile.build.mk
+ ci: add kiali_api check to swagger-ci 
+ fix swagger install (add GOOS to install path to support multi-platform like `darwin`)
we should check if we update kiali_api.md after changes made in `doc.go`
#4649 
_describe the changes if appropriate._
If so, please also update [README.adoc](README.adoc)
=> ci: add kiali_api check to swagger-ci and fix swagger install

hack/k8s-minikube.sh
This small change is required to fix the openid-test molecule.
Also, needs: https://github.com/kiali/kiali-operator/pull/483
Related to kiali/kiali#4682
=> Fix auth molecules (openid-test)

business/checkers/gateways/multi_match_checker.go
Fix for https://github.com/kiali/kiali/issues/4675
With this fix, the Gateway validation references are not showing duplicates, in a case when referenced Gateway has 2 duplicate hosts.
Also reference to own host is not shown.
=> Fixed showing duplicate validation references in Gateways. Skip own reference.

go.mod, go.sum
Manual backport of https://github.com/kiali/kiali/pull/4625
=> [v1.24] bump golang.org/crypto

status/versions.go
Fix: https://github.com/kiali/kiali/issues/4742
cc @jmazzitelli
=> fix: prevent twice debug log

business/apps.go
change  observability name  GetAppList to   GetApp
=> change  observability name  GetApp

config/config.go, kiali.go, status/status.go, status/versions.go, status/versions_test.go
consolidate version checking
Resolve: https://github.com/kiali/kiali/issues/4759
No
=> optimize: version check logics

.github/workflows/kiali-ci.yml, Makefile
This updates the GO version to 1.17.7 that includes security fixes
Reported to kiali-security@googlegroups.com
- Changes are backward compatible
It does not require README updates as it is a patch version change for golang.
=> Feature/go 1.17.7 update

business/checkers/common/multi_match_selector_checker.go
Fix for https://github.com/kiali/kiali/issues/4640
From Istio: Request authentication policies can specify more than one JWT if each uses a unique location. When more than one policy matches a workload, Istio combines all rules as if they were specified as a single policy. 
So skipping KIA0003 Multi Match checker for RequestAuthentication.
For QE:
Create 2 RequestAuthentications both having same selector labels pointing to the same workload.
Verify that no error is displayed.
Before:
Now:
Regression test the same scenario for Sidecars and PeerAuths and see that error KIA0003 is shown for them.
=> Skip KIA0003 Multi Match checker for RequestAuthentication.

business/istio_config_test.go
Additional assertions from https://github.com/kiali/kiali/pull/4796
=> Added more assertions in config tests.

business/apps.go, business/apps_test.go, business/health.go, business/workloads.go, business/workloads_test.go, handlers/apps.go, handlers/dashboards.go, handlers/workloads.go, kiali_api.md, models/app.go, models/workload.go, swagger.json
Require: https://github.com/kiali/kiali/pull/4763
Related with: https://github.com/kiali/kiali/issues/4611
=> Add health information in details

business/apps.go, business/apps_test.go, business/istio_validations.go, business/workloads.go, business/workloads_test.go, graph/telemetry/istio/appender/appender.go, graph/telemetry/istio/appender/istio_details.go, handlers/apps.go, handlers/workloads.go, kiali_api.md, swagger.json
Fix things related to @israel-hdez and @jshaughn comments in [health](https://github.com/kiali/kiali/pull/4799)
=> Fix includehealth

business/apps.go, business/health.go, business/health_test.go, business/services.go, business/workloads.go, handlers/health.go, handlers/health_test.go, handlers/workloads.go, kiali_api.md, models/service.go, routing/routes.go, swagger.json
Fix duplication of fetches inside business health methods
Fix missing cache hit for DaemonSet
Fix swagger
UI https://github.com/kiali/kiali-ui/pull/2335
=> Remove unused health endpoints

models/istio_config.go
=> Adding envoy filter help messages (and reordering alphabetically)

tests/e2e/tests/test_api_methods.py, tests/e2e/tests/test_kiali_application_endpoint.py, tests/e2e/tests/test_kiali_health.py, tests/e2e/tests/test_kiali_service_endpoint.py, tests/e2e/tests/test_kiali_workload_endpoint.py
Remove failing Health Tests due to recent API changes.
=> E2E - Fix Health Tests

graph/telemetry/istio/appender/health.go, graph/telemetry/istio/appender/health_test.go, graph/telemetry/istio/util/util_test.go
Speed up the health appender by fetching health in parallel.
=> Parallelize health appender

status/status.go, status/status_test.go
Signed-off-by: bitliu <bitliu@tencent.com>
fix: add RW lock to put status
resolve: https://github.com/kiali/kiali/issues/4842
=> fix: add RW lock to put status

status/status.go, status/status_test.go
backporting fix for https://github.com/kiali/kiali/issues/4842
=> [v1.48] fix: add RW lock to put status (#4843)

status/status.go, status/status_test.go, status/versions.go
fix concurrent map reads
fix: https://github.com/kiali/kiali/issues/4842
=> fix: add read lock when getting status

status/status.go, status/status_test.go, status/versions.go
backport of https://github.com/kiali/kiali/pull/4856
_explanation of what it does_
* If this is a fix for a JIRA, please put JIRA-reference in the PR title like _`KIALI-7 New icons`_ (Jira-id, one space, description)
* If this is a fix for a GH-issue, please link it here
** Backwards compatible? **
[ ] Is your change introducing backwards incompatible changes?
_Describe the changes if appropriate. E.g. a new link, a change on what a click does, etc_
** Screenshot **
Add a screenshot of the UI after your changes.
Does your contribution contain user-visible changes like e.g. new or changed configuration settings?
If so, provide an update to documentation if appropriate …
=> [v1.48] fix: add read lock when getting status (#4856)

LICENSE
resolve: https://github.com/kiali/kiali/issues/4860
=> fix: license copyright

config/config.go, frontend/src/app/AuthenticationController.tsx, frontend/src/components/MessageCenter/NotificationList.tsx, frontend/src/config/ServerConfig.ts, frontend/src/pages/WorkloadDetails/WorkloadDetailsPage.tsx, frontend/src/types/ErrorRate/__testData__/ErrorRateConfig.ts, frontend/src/types/ServerConfig.ts, frontend/src/types/StatusState.ts, frontend/src/types/__testData__/HealthConfig.ts, handlers/workloads.go, kiali.go, status/status.go
part of: https://github.com/kiali/kiali/issues/4737
(this also fixes https://github.com/kiali/kiali/issues/4871)
server PR: https://github.com/kiali/kiali/pull/4839
operator PR: https://github.com/kiali/kiali-operator/pull/507
helm PR: https://github.com/kiali/helm-charts/pull/130
=> provide the ability to disable features

frontend/cypress/plugins/bdd.ts
Fixes the path where cypress is looking for TS. Broke because of frontend repo merge.
=> Fix cypress pathing

.github/workflows/kiali-ci.yml
Lost this line when rebasing #4905
=> Fix CI yaml

PULL_REQUEST_TEMPLATE.md
The PR template is outdated (i.e. we don't use JIRA).
Just to have a clean format.
=> Trivial. Clean PR template messages

.github/workflows/kiali-ci.yml, frontend/cypress/integration/common/overview.ts, frontend/cypress/integration/featureFiles/overview.feature, frontend/src/pages/Overview/OverviewCardContentCompact.tsx, frontend/src/pages/Overview/OverviewCardContentExpanded.tsx, frontend/src/pages/Overview/OverviewCardSparkline.tsx, frontend/src/pages/Overview/OverviewPage.tsx, frontend/src/pages/Overview/OverviewToolbar.tsx
Fixes https://github.com/kiali/kiali/issues/4872
An early draft of basic UI tests, just to give visibility and get feedback about how we want to write these tests.
What I'd try to do here is:
- Take the assumption that the integration test cluster has a set of demos deployed.
- The cypress test will check:
- Namespaces exist.
- User can filter a specific namespace.
- User can change the view of the namespaces.
- User can interact with the namespace.
=> [cypress] Overview page

frontend/package.json
Cachito require the field version in package.json :(
=> Add version to package.json

.github/workflows/integration-tests-backend.yml, .github/workflows/integration-tests-frontend.yml, .github/workflows/kiali-ci.yml, README.adoc, frontend/cypress/README.md, frontend/cypress/integration/common/overview.ts, frontend/src/components/ToolbarDropdown/ToolbarDropdown.tsx, frontend/src/components/ToolbarDropdown/__tests__/__snapshots__/ToolbarDropdown.test.tsx.snap, hack/istio/install-error-rates-demo.sh, hack/istio/install-testing-demos.sh, hack/setup-kind-in-ci.sh
Update README with cypress requirements and add a hack script for installing demos necessary for cypress tests.
=> Update README and add hack script for demo setup

business/authentication/openid_auth_controller.go
part of https://github.com/kiali/kiali/issues/4964
=> fix trivial error in log function call

frontend/README.adoc, frontend/package.json, frontend/yarn.lock
Follow-up clean task related to https://github.com/kiali/kiali/pull/4915 changes.
Fixes the added proxy in the package.json.
=> Remove snyk deps from package.json

routing/router.go
Fix for url rewrites when proxies are placed in front of Kiali
https://github.com/kiali/kiali/issues/4459
=> Fix url rewrites 

kubernetes/client_factory.go, kubernetes/client_factory_test.go
provide recycleChan to clean expired clients
related to https://github.com/kiali/kiali/issues/4849
=> feat: provide recycleChan to clean expired clients

frontend/cypress/support/commands.ts
Bugfix: UI login flow for OCP instances
=> [cypress] login bugfix for stage

tests/integration/tests/kiali_metrics_test.go, tests/integration/tests/pod_logs_test.go, tests/integration/utils/kiali_client.go
RFE https://github.com/kiali/kiali/issues/4826
Added tests for Metrics of Namespace, Apps, Workloads and Services.
Added Pod's Logs tests.
=> [e2e] Added tests for metrics and logs endpoints.

business/checkers/destinationrules/no_dest_checker_test.go, kubernetes/host.go
=> [v1.48] Fix .svc short host name (#5000)

handlers/config.go
see: https://issues.redhat.com/browse/OSSM-1437
=> refer to deprecated prometheus retention time setting when appropriate

tests/integration/tests/applications_test.go, tests/integration/tests/istio_config_test.go, tests/integration/tests/namespaces_test.go, tests/integration/tests/services_test.go, tests/integration/tests/traces_spans_test.go, tests/integration/tests/workloads_test.go, tests/integration/utils/kiali_client.go
RFE https://github.com/kiali/kiali/issues/4826
Added tests for Health of Namespace for types: Apps, Workloads and Services.
Also added some negative tests.
=> [e2e] Added Namespace health and negative tests.

README.adoc
resolve: https://github.com/kiali/kiali/issues/5014
=> style: update tweet badge

GOVERNANCE.md
Add Xunzhuo as a new maintainer
refer to: https://github.com/kiali/kiali/discussions/4730
=> Add Xunzhuo as a new maintainer

.github/workflows/kiali-ci.yml, .github/workflows/release.yml
Fixing CI when run agains PR branches.
=> Fix CI branching issue for PRs

.github/workflows/kiali-ci.yml
pass through some changes without triggering workflows
**issue reference**
resolve: https://github.com/kiali/kiali/issues/5017
=> ci: optimize workflows triggers

.github/workflows/version-checker.yml
=> Improve workflow message in version_checker

frontend/package.json
Versions in Makefile and frontend/package.json must be aligned
=> Versions must be aligned

CODE_OF_CONDUCT.md, CONTRIBUTING.md, GOVERNANCE.md
Hi @xeviknal @abonas!
We are having some activity on the list of contributors and I've updated the list with our Emeritus contributors :) (but we keep welcome any contribution :)).
Please, let me know if that works for you.
Also, this PR has changed in the contacts of the Code of Conduct and some minor re-wording on the contributing doc.
=> Update Emeritus Contributors list

.github/workflows/integration-tests-frontend.yml, frontend/cypress/integration/common/sidecar_injection.ts, frontend/cypress/integration/featureFiles/sidecar_injection.feature, frontend/src/components/IstioWizards/WorkloadWizardDropdown.tsx, frontend/src/components/Label/Labels.tsx, frontend/src/components/Label/__tests__/__snapshots__/Labels.test.tsx.snap, frontend/src/components/MissingSidecar/MissingSidecar.tsx, frontend/src/pages/Overview/OverviewNamespaceActions.tsx, frontend/src/pages/Overview/OverviewPage.tsx, frontend/src/pages/Overview/OverviewTrafficPolicies.tsx, frontend/src/pages/WorkloadDetails/WorkloadDescription.tsx, hack/istio/install-testing-demos.sh
Add cypress test for controlling sidecar injection.
Related to #4854
=> [cypress] Add scenarios for controlling sidecar injection

deploy/jenkins-ci/Jenkinsfile
=> Stop scheduled Jenkins builds

frontend/cypress/integration/common/table.ts, frontend/cypress/integration/common/wizard_request_routing.ts, frontend/cypress/integration/featureFiles/wizard_request_routing.feature, frontend/src/components/IstioConfigCard/IstioConfigCard.tsx, frontend/src/components/IstioConfigCard/__tests__/__snapshots__/IstioConfigCard.test.tsx.snap, frontend/src/components/IstioConfigPreview/IstioConfigPreview.tsx, frontend/src/components/IstioWizards/RequestRouting/MatchBuilder.tsx, frontend/src/components/IstioWizards/RequestRouting/Matches.tsx, frontend/src/components/IstioWizards/RequestRouting/RuleBuilder.tsx, frontend/src/components/IstioWizards/ServiceWizard.tsx, frontend/src/components/IstioWizards/ServiceWizardDropdown.tsx, frontend/src/components/IstioWizards/Slider/Slider.tsx, frontend/src/components/Link/IstioObjectLink.tsx, frontend/src/components/Link/ServiceLink.tsx, frontend/src/components/Link/WorkloadLink.tsx
Related to https://github.com/kiali/kiali/issues/5001
I've elaborated a "Wizard" test as they are typically complex with modals, forms, confirmation, etc.
Then it may work as an example for other Wizards and Service Details tests.
I cc @hhovsepy as he also battled a lot with the automation of these UI tests in the past.
=> [cypress] Service Details: Request Routing Wizard tests

hack/run-molecule-tests.sh
=> [v1.48] [molecule] generate a results.xml file using junit xml format

frontend/src/components/IstioWizards/ServiceWizard.tsx
Epic https://github.com/kiali/kiali/issues/4260
Review PF4 changes that affect the cypress tests around the Wizard.
=> [cypress] fix tests on wizard

frontend/cypress/integration/common/services.ts, frontend/cypress/integration/featureFiles/services.feature, frontend/src/components/NamespaceDropdown.tsx, frontend/src/helpers/LabelFilterHelper.ts, frontend/src/helpers/__tests__/LabelFilterHelper.test.ts
Epic #4260 
[cypress] Fix tests on services list
- Fix double-slash issue in Nav (sent everything to overview)
- Fix bug in label handling using new '=' separator
- Fix services feature for updated PF
=> [cypress] Fix tests on services list

hack/run-molecule-tests.sh
following schema documented here: https://llg.cubic.org/docs/junit/
=> [molecule] add more fields to the junit xml results file

config/config.go
Use a more general default value for Istio UrlServiceVersion
Fixes #4985
=> Default Istio.UrlServiceVersion configuration value improvement #4985

frontend/cypress/integration/common/table.ts, frontend/cypress/integration/common/workloads.ts, frontend/cypress/integration/featureFiles/workloads.feature, frontend/package.json
Resolves https://github.com/kiali/kiali/issues/4912.
Adds basic Cypress testing to the Workloads page.
Epic: https://github.com/kiali/kiali/issues/4854
=> [cypress] Workloads page testing

frontend/cypress/integration/common/apps.ts, frontend/cypress/integration/common/istio_config.ts, frontend/cypress/integration/common/table.ts, frontend/cypress/integration/common/transition.ts, frontend/cypress/integration/featureFiles/apps.feature, frontend/cypress/results/combined-report.xml, frontend/src/app/InitializingScreen.tsx
Cypress tests for the Apps List page.
Fixes #4967
=> [cypress] Tests for Apps page

hack/istio/install-testing-demos.sh
This allows someone to clean up their cluster and remove all the installed demos.
To test - pass in `--delete true` or `-d true` to the script. You should see all the demos get removed from the cluster.
=> [hack] provide option to delete all the demos

frontend/src/components/Nav/Page/RenderHeader.tsx, frontend/src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx, frontend/src/styles/_overrides.scss
RFE https://github.com/kiali/kiali/issues/4936
=> Added interval refresh on IstioConfigDetails page. Removed content change notifications.

frontend/cypress/integration/common/graph_replay.ts, frontend/cypress/integration/featureFiles/graph_replay.feature, frontend/src/components/Time/Replay.tsx, frontend/src/components/Time/TimeDurationComponent.tsx
epic: https://github.com/kiali/kiali/issues/4854
closes: https://github.com/kiali/kiali/issues/5084
=> [cypress] graph replay tests

frontend/package.json, frontend/yarn.lock
Epic #4260 
- needs a "resolutions" entry
=> second try to resolve an issue with json-schema

frontend/cypress/integration/common/wizard_request_routing.ts, frontend/cypress/integration/featureFiles/wizard_request_routing.feature, frontend/src/components/IstioWizards/ServiceWizard.tsx, frontend/src/pages/IstioConfigDetails/IstioObjectDetails/IstioConfigOverview.tsx, frontend/src/pages/IstioConfigDetails/IstioObjectDetails/IstioStatusMessageList.tsx
RFE https://github.com/kiali/kiali/issues/4864
When configuration analysis messages are enabled on Istio, Kiali shows valiation messages alongside with these Istio configuration analysis messages. Also removed object status icon in that cases.
=> Added Kiali validation messages alongside with Istio Analysis.

frontend/cypress/integration/common/kiali_about.ts, frontend/cypress/integration/featureFiles/kiali_about.feature, frontend/src/components/Nav/Masthead/HelpDropdown.tsx
It is verifying the user help validation
=> [cypress] user_about

tests/integration/README.md, tests/integration/utils/exec_client.go
Changed environment variable and README reference CLIENT_EXE for test integrations
https://github.com/kiali/kiali/issues/5093
=> Changed the environment variable and the readme exec_client

frontend/src/helpers/ValidationHelpers.ts, frontend/src/pages/IstioConfigNew/AuthorizationPolicyForm/When/ConditionBuilder.tsx
- Adds support for `remote.ip`, `request.auth.claims` authorization policy conditions
- Fixes #5109
=> Add support for authorization policy conditions that was missing

hack/crc-openshift.sh
This allows us to install OpenShift 4.10
=> [hack] update crc to latest

README.adoc
Update Guide of External Control Plane Setup
=> Update Guide of External Control Plane Setup

frontend/src/pages/Overview/OverviewToolbar.tsx
Follow up change request: https://github.com/kiali/kiali/pull/5117#issuecomment-1139601934
=> Show Traffic dropdown only in mode when traffic graph is shown.

frontend/cypress/integration/common/app_details.ts, frontend/cypress/integration/common/navigation.ts, frontend/cypress/integration/common/table.ts, frontend/cypress/integration/featureFiles/app_details.feature, frontend/src/components/CytoscapeGraph/MiniGraphCard.tsx, frontend/src/components/JaegerIntegration/JaegerResults/JaegerTraceTitle.tsx, frontend/src/components/JaegerIntegration/JaegerScatter.tsx, frontend/src/components/JaegerIntegration/TracesComponent.tsx, frontend/src/pages/AppDetails/AppDescription.tsx, frontend/src/pages/AppDetails/AppDetailsPage.tsx
Basic cypress tests for the App details page.
Fixes #5008
=> [cypress] Add tests for App details page

frontend/src/pages/Graph/GraphToolbar/GraphFind.tsx, frontend/src/pages/Graph/GraphToolbar/GraphFindOptions.tsx, frontend/src/styles/_overrides.scss
Fix toolbar alignment issues after Patternfly update. 
I could reproduce the issue in chrome. With the change, looks correct in FF and Chrome, tested minimizing windows and different screens.
https://github.com/kiali/kiali/issues/5125
cc @jshaughn
=> toolbar alignment issues

frontend/cypress/integration/common/kiali_logout.ts, frontend/cypress/integration/featureFiles/kiali_logout.feature
=> [cypress] user_logout

.github/workflows/kiali-ci.yml, Makefile
Upgrade version to 1.17.10 for builds
=> [v1.48] Bump go version to 1.17.10

.github/workflows/build-backend.yml, .github/workflows/integration-tests-backend.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, Makefile
Upgrade version to 1.17.10 for builds
=> Bump go version to 1.17.10

frontend/src/components/Envoy/tables/ClusterTable.ts, frontend/src/components/Envoy/tables/ListenerTable.ts, frontend/src/components/Envoy/tables/RouteTable.ts
Fixes #5161 
The Cypress test for this scenario is being worked at: #5141.
=> Fix for Envoy filters on Workloads details

tests/integration/tests/config_validations_test.go
Issue https://github.com/kiali/kiali/issues/5164
Loading Istio config by poll.
=> Fixed potential flaky tests.

.github/workflows/release.yml
Releasing early allowing more people to use it on that day.
=> Changing the release time to 7:00 UTC

config/version-compatibility-matrix.yaml, status/versions_test.go
* Add Istio 1.14 to version compatibility
* Missing update for 1.13 + unit tests
=> [v1.51] Add Istio 1.14 to version compatibility (#5169)

config/version-compatibility-matrix.yaml, status/versions_test.go
* Add Istio 1.14 to version compatibility
* Missing update for 1.13 + unit tests
=> [v1.50] Add Istio 1.14 to version compatibility (#5169)

business/istio_validations.go
Research RFE for validation optimization: https://github.com/kiali/kiali/issues/5153
Optimization suggestion:
When specifying a Workload, then no need to load all workloads per namespace.
=> Optimized workload validations load.

frontend/src/components/IstioStatus/IstioStatus.tsx, frontend/src/components/IstioStatus/__tests__/__snapshots__/IstioStatus.test.tsx.snap
Toolbar icons missaligment. Adjust IstioStatus alert icon, missed to check from merged PR.
Fixes #5155
=> Toolbar icons missaligment. Adjust IstioStatus alert icon

frontend/src/components/Nav/Page/RenderHeader.tsx
Alignment of the actions dropdown on details pages
Fixes https://github.com/kiali/kiali/issues/5186
=> Alignment of the actions dropdown on details pages

hack/istio/install-istio-via-istioctl.sh
To test, download two versions of Istio in order of their release numbers:
```
hack/istio/download-istio.sh -iv 1.13.0
hack/istio/download-istio.sh -iv 1.14.0
```
Now try to install the earlier version:
```
hack/istio/install-istio-via-istioctl.sh -iv 1.13.0
```
The way this used to work, the last version you downloaded would have been installed. So `install-istio-via-istioctl.sh` (without any options) would have installed 1.14. But now you can tell it to install an earlier version, even if you already downloaded another version recently.
Note another test - if you have NOT downloaded the version yet, it will download it for you, then install... so try this to test that that works:
```
hack/istio/install-istio-via-istioctl.sh -iv 1.12.0
```
=> be able to install a specific version of istio

frontend/src/pages/Graph/SummaryLink.tsx, frontend/src/pages/Graph/SummaryPanelAppBox.tsx, frontend/src/pages/Graph/SummaryPanelNode.tsx
Epic #4789 
These have annoyed me forever, couldn't stand it any more :-)
=> resolve a variety of "unique-key" console errors in graph side-panels

frontend/cypress/support/commands.ts
Attempts to fix an issue where kiali will redirect to the overview page after login causing initial page visits during other tests to be replaced with the overview page.
=> [cypress] Fix redirects to the overview page after login

business/apps_test.go, business/health_test.go, business/istio_validations_test.go, business/mesh.go, business/mesh_test.go, business/registry_status.go, business/services.go, business/services_test.go, graph/telemetry/istio/appender/health_config_test.go, handlers/apps_test.go, handlers/health_test.go, tests/data/registry/istio-east-registryz.json
Per discussion https://github.com/kiali/kiali/pull/4572 this fix is backported to the v1.44 to make it available for Istio 1.12 users.
cc @zijianz
=> [v1.44] Fix race while querying the Istio registry

tests/integration/tests/config_validations_test.go
Fix for https://github.com/kiali/kiali/issues/5219
=> [e2e] Fixed flaky config tests.

frontend/src/components/ErrorSection/ErrorSection.tsx, frontend/src/pages/AppDetails/AppDetailsPage.tsx, frontend/src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx, frontend/src/pages/ServiceDetails/ServiceDetailsPage.tsx, frontend/src/pages/WorkloadDetails/WorkloadDetailsPage.tsx, frontend/src/types/ErrorMsg.ts
Not found messages may have a better message in the body page.
Done for apps and workloads. 
Fixes https://github.com/kiali/kiali/issues/5206
=> Not found messages in body page for workloads and Apps

hack/ibmcloud-openshift.sh, hack/perf-ibmcloud-openshift.sh
Instead of using the addon prometheus, deploy a separate instance with dedicated volumes and resources.
=> Perf environment - deploy separate prometheus

frontend/cypress/integration/common/service_details.ts, frontend/cypress/integration/featureFiles/service_details.feature
Adding Cypress UI tests for the Service Details page
Fixes https://github.com/kiali/kiali/issues/5001
=> Cypress UI tests for the Service Details page

tests/integration/tests/config_validations_test.go
Issue https://github.com/kiali/kiali/issues/5219
There was a bug in tests.
=> Fixed bug in tests.

hack/ci-kind-molecule-tests.sh
Attempt to fix molecule test failures: https://github.com/kiali/kiali/runs/7067029704?check_suite_focus=true
=> Build molecule test image with podman

frontend/src/pages/IstioConfigDetails/IstioObjectDetails/IstioStatusMessageList.tsx
Fix for https://github.com/kiali/kiali/issues/5257
=> Fixed Config page crush by Info severity icon issue.

frontend/src/components/Envoy/EnvoyDetails.tsx, frontend/src/components/Envoy/tables/BaseTable.tsx, frontend/src/components/Envoy/tables/ClusterTable.tsx, frontend/src/components/Envoy/tables/ListenerTable.tsx, frontend/src/components/Envoy/tables/RouteTable.tsx, frontend/src/components/Filters/StatefulFilters.tsx
Fix https://github.com/kiali/kiali/issues/5162
cc @lucasponce
=> Add tooltip in envoy tabs

frontend/src/components/CytoscapeGraph/CytoscapeGraph.tsx
Part-of https://github.com/kiali/kiali/issues/5276
=> In graph, change to mouse cursor when over nodes and edges

models/istio_validation.go
RFEs:
https://github.com/kiali/kiali/issues/5266
https://github.com/kiali/kiali/issues/5262
Docs changes: https://github.com/kiali/kiali.io/pull/552
=> Validations synced up with docs.

frontend/cypress/integration/featureFiles/istio_config.feature
Fix after https://github.com/kiali/kiali/pull/5299
=> [cypress] Fixed failing tests by fixing the message severity.

config/config.go, graph/api/api.go, graph/telemetry/istio/istio.go, observability/tracing.go
Adds tracing to graph generation to give better insight into graph requests.
=> Add more tracing and make sampling rate configurable

frontend/src/pages/Login/LoginPage.tsx
=> Use standard PF alerts in the login page

hack/perf-ibmcloud-openshift.sh
Adds option to specify a custom cluster name and installs demo workloads to generate load by default.
=> Allow custom names in perf script and install wklds

frontend/cypress/integration/common/graph_find_hide.ts, frontend/cypress/integration/featureFiles/graph_find_hide.feature
Just a little suit for my PR involving logging in, visiting the graph page, typing something random into the find form and then expecting an error message to pop up.
Far from being perfect, but it is what it is.
(accidentally pushed some junk last time, now it should be alright)
=> [Cypress] Graph page find form test

frontend/src/pages/ServiceDetails/ServiceDetailsPage.tsx
=> Overlay trace onclick event doesn't work

frontend/src/components/IstioWizards/ServiceWizard.tsx
=> Remove js error in missing title in Modal component

frontend/cypress/integration/common/istio_config_editor.ts, frontend/cypress/integration/common/table.ts, frontend/cypress/integration/featureFiles/istio_config_editor.feature
Adding new testcase for istio config editor, for now its only simple test.
Also there is new method for handling anchors in tables.
=> [Cypress] istio config editor test

config/version-compatibility-matrix.yaml, status/versions_test.go
part of https://github.com/kiali/kiali/issues/5396
=> new istio 1.15 compat matrix info

hack/run-kiali.sh
This is to support k8s versions that do not by default provide SA secrets.
part of https://github.com/kiali/kiali/issues/5258
To test, just run `hack/run-kiali.sh` and if it works, this PR is good. Do NOT use `-kc current` option - that will not test this change. You must run this without that option.
=> [hack] run-kiali.sh no longer expects default SA secret for obtaining tokens/certs

GOVERNANCE.md
It's been a pleasure working with the Kiali and Istio teams. 
They keep working on awesome stuff that will help shape how big architectures will work in the cloud and how users can have a rich experience in managing it.
I will focus on other projects and will not be able to follow or contribute to Kiali/Istio in the short/mid-term, so I think it makes sense to update the Governance.
Best,
Lucas
cc @kiali/maintainers
=> Moving lucasponce to Emeritus contributors

frontend/cypress/README.md
"CYPRESS_VIDEO=true" option activates video recording.
=> Added video recording option in cypress readme.

frontend/cypress/integration/common/workloads_details.ts, frontend/src/components/Metrics/CustomMetrics.tsx
Issue https://github.com/kiali/kiali/issues/5407
Added message "Loading metrics" while custom dashboards ate not loaded, waiting for that message to disappear in cypress tests.
=> Added message while loading metrics for custom dashboards

frontend/src/components/MissingLabel/MissingLabel.tsx
=> Relax missing label wording

hack/istio/install-testing-demos.sh, hack/setup-kind-in-ci.sh
Use a version of the yaml for the load balancer compatible with kube 1.25
Fixes #5441
=> Update kind hack script

frontend/cypress/integration/common/service_details.ts, frontend/cypress/integration/featureFiles/service_details.feature, frontend/src/components/Details/DetailDescription.tsx, frontend/src/components/HeatMap/HeatMap.tsx, frontend/src/components/IstioWizards/ConfirmDeleteTrafficRoutingModal.tsx, frontend/src/components/IstioWizards/ServiceWizardActionsDropdownGroup.tsx, frontend/src/components/IstioWizards/ServiceWizardDropdown.tsx, frontend/src/components/IstioWizards/WorkloadWizard.tsx, frontend/src/components/JaegerIntegration/JaegerResults/JaegerTraceTitle.tsx, frontend/src/components/JaegerIntegration/JaegerResults/SpanTable.tsx, frontend/src/components/JaegerIntegration/JaegerResults/StatsComparison.tsx, frontend/src/components/Time/TimeDurationModal.tsx, frontend/src/components/VirtualList/Renderers.tsx
Fixes https://github.com/kiali/kiali/issues/5358
- ensure kebab is visible before click
- only test span select span one time
- reduces scrolling which may contribute to the problem
- reduce unnecessary redundancy/speed up test
- remove some unused imports and variables
=> Fix Test Flake [hopefully]

.github/workflows/integration-tests-frontend.yml, business/istio_config.go, business/layer.go, business/namespaces.go, business/services.go, business/workloads.go, config/config.go, config/config_test.go, kubernetes/cache/cache.go, kubernetes/cache/cache_handlers.go, kubernetes/cache/cache_handlers_test.go, kubernetes/cache/cache_test.go, kubernetes/cache/istio.go, kubernetes/cache/istio_test.go, kubernetes/cache/kubernetes.go, kubernetes/cache/kubernetes_test.go, kubernetes/cache/tls_test_helper.go, kubernetes/kubernetes.go, server/server.go
Utilizes a cluster scoped cache if the Kiali service account has cluster-scoped permissions for each of the cache types.
Fixes #4678
=> Cluster-scoped cache

hack/setup-kind-in-ci.sh
Fix integration test failure related to change in default values for install-istio-via-istioctl.sh
Related to #5248
=> Fix integration test failure

.github/workflows/integration-tests-frontend.yml, frontend/cypress/integration/common/kiali_login.ts, frontend/cypress/support/commands.ts, hack/setup-kind-in-ci.sh
=> Use "token" auth strategy for front-end integration tests

Makefile
We need to fix the Makefile version setting it to the last tag that already exists, that is v1.36.9.
=> fix version in Makefile

frontend/src/app/AuthenticationController.tsx, frontend/src/components/About/AboutUIModal.tsx, frontend/src/components/Nav/Masthead/HelpDropdown.tsx, frontend/src/types/StatusState.ts, status/status.go
=> Move version check message to the About dialog

frontend/cypress/integration/common/app_details.ts, frontend/cypress/integration/common/apps.ts, frontend/cypress/integration/common/kiali_sidebar_toggle.ts, frontend/cypress/integration/common/overview.ts, frontend/cypress/integration/common/service_details.ts, frontend/cypress/integration/common/transition.ts, frontend/cypress/integration/common/workloads_details.ts, frontend/cypress/integration/featureFiles/app_details.feature, frontend/cypress/integration/featureFiles/kiali_sidebar_toggle.feature, frontend/cypress/integration/featureFiles/overview.feature, frontend/cypress/integration/featureFiles/service_details.feature, frontend/cypress/integration/featureFiles/workloads_details.feature, frontend/src/app/AuthenticationController.tsx, frontend/src/pages/Login/LoginPage.tsx, frontend/src/pages/Login/__tests__/__snapshots__/LoginPage.test.tsx.snap
Consolidates some step definitions shared across apps/services/workloads pages. Ensures that the toggle test waits for the page to load before beginning.
Fixes #5437
=> Fix toggle test and consolidate tracing step definitions

.github/workflows/nightly.yml, .github/workflows/release.yml, Makefile, deploy/docker/Dockerfile-multi-arch-distroless, make/Makefile.container.mk
Issue #5239
Add distroless image definitions following istio's pattern
=> Add distroless image

.github/workflows/build-frontend.yml, .github/workflows/integration-tests-backend.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/tag-creator.yml, .github/workflows/version-checker.yml
It just bugs me, that's why :)
=> [trivial] remove eol spaces in github workflow yaml

frontend/src/components/CytoscapeGraph/graphs/GraphStyles.ts, frontend/src/pages/Graph/SummaryPanelNode.tsx, frontend/src/types/Graph.ts, graph/config/cytoscape/cytoscape.go, graph/meta.go, graph/telemetry/istio/appender/istio_details.go, kiali_api.md
Issue https://github.com/kiali/kiali/issues/5490
Now the Gateway API applications in Graph page are shown with similar icons as Ingress gateway ones.
=> Added Gateway API support in Graph

hack/istio/install-error-rates-demo.sh
Fixing err demo installation script on maistra
=> We need to update deployment annotations after we create it

frontend/src/components/CytoscapeGraph/graphs/GraphStyles.ts, frontend/src/pages/Graph/SummaryPanelNode.tsx, frontend/src/types/Graph.ts, graph/config/cytoscape/cytoscape.go, graph/meta.go, graph/telemetry/istio/appender/istio_details.go, kiali_api.md
Cherry-pick of https://github.com/kiali/kiali/pull/5496
Added Gateway API support in Graph
=> [v1.57] Added Gateway API support in Graph (#5496)

frontend/cypress/integration/common/apps.ts
Backport cherry-pick https://github.com/kiali/kiali/pull/5500
=> [v1.57] Change flaky click to a visibility check for the kebab menu

frontend/cypress/integration/featureFiles/kiali_about.feature, frontend/cypress/integration/featureFiles/kiali_cookie.feature, frontend/cypress/integration/featureFiles/kiali_help.feature, frontend/cypress/integration/featureFiles/kiali_homepage.feature, frontend/cypress/integration/featureFiles/kiali_login.feature, frontend/cypress/integration/featureFiles/kiali_sidebar_toggle.feature
added `@smoke` annotations to related feature files
=> [Cypress] added @smoke annotations to related feature files

frontend/src/pages/Overview/OverviewCardControlPlaneNamespace.tsx
Backport cherry-pick of https://github.com/kiali/kiali/pull/5503
=> [v1.57] Adding more space between the chart name and the y axis value (#5503)

hack/istio/install-testing-demos.sh
Adding support for maistra so the sidecars are enabled for all used demo applications. Also adding support for custom istio namespace.
=> [v1.57] Adding support for maistra and custom istio namespace

hack/istio/install-testing-demos.sh
Adding support for maistra so the sidecars are enabled for all used demo applications. Also adding support for custom istio namespace.
=> Adding support for maistra and custom istio namespace

.github/workflows/release.yml
Due to flaky tests in v1.57, I decided to skip integration testing.
=> By passing integration tests for building v1.57

business/namespaces.go, config/config.go
fixes: https://github.com/kiali/kiali/issues/5516
server PR: https://github.com/kiali/kiali/pull/5521
operator PR: https://github.com/kiali/kiali-operator/pull/574
doc PR: https://github.com/kiali/kiali.io/pull/587
=> support more include/exclude features in namespaces api

frontend/cypress/integration/common/graph_toolbar.ts
https://issues.redhat.com/browse/OSSM-2094
=> Don't assume the prom config when testing for durations.

frontend/cypress/integration/common/graph_toolbar.ts
backport cherry-pick of https://github.com/kiali/kiali/pull/5549
=> [v1.57] Don't assume the prom config when testing for durations.

frontend/cypress/integration/common/graph_display.ts, frontend/cypress/integration/featureFiles/graph_display.feature
backport cherry pick https://github.com/kiali/kiali/pull/5552
=> [v1.57] Soften test for idle edges

frontend/src/components/IstioWizards/WizardActions.ts, frontend/src/components/IstioWizards/WorkloadWizardDropdown.tsx, frontend/src/types/ServerConfig.ts, models/workload.go
Backport cherry-pick of https://github.com/kiali/kiali/pull/5554
=> [v1.57] Remove "isMaistra" conditional code regarding workload-level injection

.github/workflows/integration-tests-backend.yml, .github/workflows/integration-tests-frontend.yml, .github/workflows/kiali-ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/tag-creator.yml, .github/workflows/version-checker.yml
Signed-off-by: bitliu <bitliu@tencent.com>
Fixes: #5556
=> chore: remove deprecated set-outputs

frontend/cypress/integration/common/kiali_login.ts, frontend/cypress/integration/featureFiles/kiali_login.feature
Fixes #5568 
Reproduced with the steps provided by @nrfox 
Tested with 1 and 2 providers.
=> Remove Login to openshift click in kiali_login test

make/Makefile.operator.mk
this is just for developers use... nothing changes in the production code
=> [make] for dev work - need to set the new env var so run-operator-playbook will run

hack/istio/install-scale-mesh-demo.sh
Allows you to pass number of workloads into scale mesh demo hack script.
=> Add option to specify number of workloads to scale script

config/config.go, config/config_test.go
part of https://github.com/kiali/kiali/issues/5591
server PR: https://github.com/kiali/kiali-operator/pull/585
=> secrets now injected into pod file system, not as env vars

frontend/cypress/integration/common/overview.ts, frontend/cypress/integration/featureFiles/overview.feature, frontend/src/components/Overview/TLSInfo.tsx
=> New test in Overview for Min TLS

business/mesh.go, business/mesh_test.go, frontend/cypress/integration/common/overview.ts, frontend/cypress/integration/featureFiles/overview.feature, frontend/src/components/Overview/TLSInfo.tsx, frontend/src/config/Config.ts, frontend/src/pages/Overview/CanaryUpgradeProgress.tsx, frontend/src/pages/Overview/ControlPlaneBadge.tsx, frontend/src/pages/Overview/ControlPlaneNamespaceStatus.tsx, frontend/src/pages/Overview/ControlPlaneVersionBadge.tsx, frontend/src/pages/Overview/NamespaceStatuses.tsx, frontend/src/pages/Overview/OverviewCardControlPlaneNamespace.tsx, frontend/src/pages/Overview/OverviewPage.tsx, frontend/src/services/Api.ts, frontend/src/types/IstioObjects.ts, handlers/mesh.go, models/istio_canaries.go, routing/routes.go
=> Canary upgrade status in Control Plane card

frontend/src/components/Overview/TLSInfo.tsx
=> Add key atribute to remove react warning

config/config.go, config/config_test.go
* secrets now injected into pod file system, not as env vars
* unit test now uses files, not env vars
cherry pick of https://github.com/kiali/kiali/pull/5592
`make build test` will ensure the unit test passes.
=> [v1.57] secrets now injected into pod file system, not as env vars

frontend/src/pages/Login/LoginPage.tsx
=> show generic login error in UI, only log the specific error messages

frontend/src/pages/Login/LoginPage.tsx
backport of PR https://github.com/kiali/kiali/pull/5638
=> [v1.57] show generic login error in UI, only log the specific error messages

deploy/docker/Dockerfile-distroless, deploy/docker/Dockerfile-multi-arch-distroless
fixes: https://github.com/kiali/kiali/issues/5643
=> Put root CA certificates in container

business/openshift_oauth.go, config/config.go
fixes: https://github.com/kiali/kiali/issues/5650
PRs that implement this feature:
* https://github.com/kiali/kiali/pull/5652
* https://github.com/kiali/kiali-operator/pull/593
* https://github.com/kiali/helm-charts/pull/183
=> Be able to customize some timeouts for openshift auth

business/openshift_oauth.go, config/config.go
cherry pick of: https://github.com/kiali/kiali/pull/5652
=> [1.57] Be able to customize some timeouts for openshift auth

frontend/src/pages/Login/LoginPage.tsx
In OAuth/OpenId implicit flow, errors are passed as hash params rather than query params. Errors passed as hash params weren't being read potentially causing a login/redirect loop, because the front-end assumes that the user was landing for the first time in Kiali and doing the automatic redirection to the 3rd party provider.
Fixes kiali/kiali#5663
=> Catch OAuth/OpenId implicit flow error params

frontend/cypress/integration/common/kiali_login.ts, frontend/cypress/integration/featureFiles/kiali_login.feature
A little PR containing some smokes around the login page. The smokes test logging in with invalid or missing credentials.
=> [Cypress] Smoke tests around the login page

business/proxy_logging.go, business/proxy_status.go, business/workloads.go, handlers/proxy_logging_test.go, kubernetes/cache/cache.go, kubernetes/cache/cache_test.go, kubernetes/cache/proxy_status.go
Backport of #5674 
Relates to #5669
=> [v1.57 - backport] Poll for proxy status continually rather than fetching lazily

frontend/src/components/DebugInformation/DebugInformation.tsx, frontend/src/components/Nav/Masthead/HelpDropdown.tsx, frontend/src/components/Tab/Tabs.tsx, frontend/src/config/ServerConfig.ts, frontend/src/types/ErrorRate/__testData__/ErrorRateConfig.ts, frontend/src/types/ServerConfig.ts, frontend/src/types/__testData__/HealthConfig.ts, handlers/config.go, log/log.go
Fixes #5588 
Ref https://github.com/kiali/kiali/pull/5616
=> Show Kiali Configuration (b)

frontend/cypress/integration/common/overview.ts, frontend/cypress/integration/featureFiles/overview.feature
Fixes https://github.com/kiali/kiali/issues/5689
=> Fix flaky test in the Overview page

frontend/src/pages/WorkloadDetails/WorkloadPodLogs.tsx, handlers/proxy_logging.go
=> [v1.57] Backport Disable set log level dropdown in view only mode (#5717)

frontend/cypress/integration/common/istio_config_type_filters.ts, frontend/cypress/integration/common/istio_config_validation_filters.ts, frontend/cypress/integration/common/label_check.ts, frontend/cypress/integration/featureFiles/graph_toolbar.feature
Fix for:
https://github.com/kiali/kiali/issues/5715
https://github.com/kiali/kiali/issues/5704
https://github.com/kiali/kiali/issues/5636
=> [cypress] Fixing related flaky tests

frontend/src/pages/Overview/OverviewPage.tsx, frontend/src/pages/Overview/__tests__/OverviewPage.test.tsx, status/versions.go
namespace label is not currently honored in ossm environments
fixes https://github.com/kiali/kiali/issues/5725
=> try to hide the namespace injection menu option on OSSM

frontend/src/components/IstioWizards/WizardActions.ts, models/workload.go
fixes: https://github.com/kiali/kiali/issues/5713
=> better workload auto-injection label/annotation processing

frontend/src/pages/Overview/OverviewCardControlPlaneNamespace.tsx, frontend/src/pages/Overview/OverviewCardSparklineCharts.tsx, frontend/src/pages/Overview/OverviewPage.tsx, routing/routes.go
=> trivial - noticed a pervasive typo that also shows up in UI error text

business/checkers/authorization/principals_checker.go, business/checkers/authorization/principals_checker_test.go
Bug https://github.com/kiali/kiali/issues/5729
Added wildcard support on AuthPolicy principals field checking ServiceAccounts.
Logic is adjusted to Istio docs https://istio.io/latest/docs/reference/config/security/authorization-policy/#Source:
Exact match: “abc” will match on value “abc”.
Prefix match: “abc*” will match on value “abc” and “abcd”.
Suffix match: “*abc” will match on value “abc” and “xabc”.
Presence match: “*” will match when value is not empty.
Before
Now
=> AuthPolicy principals checking wildcard

business/checkers/authorization/principals_checker.go, business/checkers/authorization/principals_checker_test.go
Cherry-pick of https://github.com/kiali/kiali/pull/5745
Checking now a wildcard in AuthPolicy principals prefix and suffix:
=> AuthPolicy principals checking wildcard (#5745)

make/Makefile.olm.mk, make/Makefile.operator.mk
part of: https://github.com/kiali/kiali/issues/5657
=> [dev] update some operator version things for dev purposes

frontend/src/components/Charts/CustomTooltip.tsx, frontend/src/components/SummaryPanel/ResponseTimeChart.tsx, frontend/src/components/SummaryPanel/RpsChart.tsx, frontend/src/index.tsx, frontend/src/pages/Overview/OverviewCardControlPlaneNamespace.tsx, frontend/src/pages/Overview/OverviewCardDataPlaneNamespace.tsx
=> Add date to chart tooltips

tests/integration/assets/bookinfo-service-entry-external.yaml, tests/integration/tests/no_istiod_test.go, tests/integration/utils/kiali_client.go
Fixes #5722 
Integration tests
=> [CI] Kiali working with No Istiod access test

frontend/cypress/integration/common/istio_config.ts, frontend/cypress/integration/common/istio_config_validation_filters.ts, frontend/cypress/integration/common/label_check.ts, hack/istio/install-istio-via-istioctl.sh, hack/setup-kind-in-ci.sh, tests/integration/assets/bookinfo-k8sgateways-addresses.yaml, tests/integration/assets/bookinfo-k8sgateways-listeners.yaml, tests/integration/assets/bookinfo-k8sgateways.yaml, tests/integration/assets/bookinfo-k8shttproutes-gateways.yaml, tests/integration/assets/bookinfo-k8shttproutes-services.yaml, tests/integration/tests/config_validations_test.go, tests/integration/tests/istio_config_test.go
RFE https://github.com/kiali/kiali/issues/5726
Installing K8s Gateway API on CI env.
Added Gateway API Objects validations tests.
=> [CI] K8s Gateway API integration tests

tests/integration/tests/no_istiod_test.go
Conflict happened in github PRs merge, resolving asap.
=> Merging conflicts resolved

frontend/cypress/integration/common/wizard_request_routing.ts, frontend/cypress/integration/featureFiles/wizard_k8sgw_api_routing.feature, frontend/src/components/IstioWizards/K8sRequestRouting/K8sFilterBuilder.tsx
RFE https://github.com/kiali/kiali/issues/5753
=> [cypress] Added Service Details wizard check for K8s Gateway API Routing

business/istio_validations.go, business/references/k8s_gateway_references.go, business/references/k8s_gateway_references_test.go, kubernetes/filters.go
=> Show HTTPRoutes references in K8s Gateway details

frontend/cypress/integration/common/wizard_istio_config.ts, frontend/cypress/integration/featureFiles/wizard_istio_config.feature, frontend/src/components/IstioActions/IstioActionsNamespaceDropdown.tsx, frontend/src/pages/IstioConfigNew/GatewayForm/ListenerBuilder.tsx, frontend/src/pages/IstioConfigNew/IstioConfigNewPage.tsx
RFE https://github.com/kiali/kiali/issues/5753
=> [cypress] Added test for K8sGateway in Istio config wizard

frontend/cypress/integration/common/istio_config_validation_filters.ts, frontend/cypress/integration/common/wizard_istio_config.ts, frontend/cypress/integration/common/wizard_request_routing.ts
Fixes https://github.com/kiali/kiali/issues/5761
=> Fixed potential flakes

business/mesh.go, business/mesh_test.go
part of: https://github.com/kiali/kiali/issues/5738
=> read the remote cluster secrets from the file system

frontend/src/pages/Overview/OverviewPage.tsx
=> Show NA for istio config if istio api disabled

handlers/authentication.go
This change applies only to the OpenShift authentication mechanism.
Previously, the cluster version was retrieved using an unauthenticated query to the cluster API. This is ensuring that such query is authenticated using the Kiali ServiceAccount. This is to overcome situations when non-authenticated users cannot query the cluster version.
There are cases when users choose to remove the privileges to fetch the cluster version to unauthenticated queries to the cluster API. Presumably, this is because of security reasons. Since Kiali was using an unauthenticated query to fetch the cluster version, OpenShift authentication becomes unusable in such situation.
I was thinking in also modifying the kiali-operator, so that the Kiali SA explicitly gets privileges to query …
=> Fetch OpenShift version using Kiali ServiceAccount

handlers/authentication.go
=> Fetch OpenShift version using Kiali ServiceAccount (v1.57)

frontend/cypress/integration/common/wizard_request_routing.ts
Fixing potential flake https://github.com/kiali/kiali/issues/5770
=> [cypress] Potential flake test fix

config/version-compatibility-matrix.yaml, status/versions_test.go
part of https://github.com/kiali/kiali/issues/5773
backport of https://github.com/kiali/kiali/pull/5774
=> [v1.63] update compatibility matrix for istio 1.17

business/apps_test.go, business/health_test.go, business/istio_status_test.go, business/test_util.go, business/workloads.go, business/workloads_test.go, graph/telemetry/istio/appender/dead_node_test.go, graph/telemetry/istio/appender/health_test.go, graph/telemetry/istio/appender/labeler_test.go, graph/telemetry/istio/appender/sidecars_check_test.go, handlers/workloads_test.go
=> [Backport v1.63] Fix caching when fetching workloads (#5784)

business/apps_test.go, business/health_test.go, business/istio_status_test.go, business/test_util.go, business/workloads.go, business/workloads_test.go, graph/telemetry/istio/appender/dead_node_test.go, graph/telemetry/istio/appender/health_test.go, graph/telemetry/istio/appender/labeler_test.go, graph/telemetry/istio/appender/sidecars_check_test.go, handlers/workloads_test.go
=> [Backport v1.62] Fix caching when fetching workloads (#5784)

frontend/src/components/IstioWizards/WizardActions.ts, frontend/src/pages/IstioConfigNew/K8sGatewayForm.tsx
=> Remove "Labels" in Create K8s Gateway Wizard

CONTRIBUTING.md
part of : https://github.com/kiali/kiali/issues/5808
=> document where discussions/issues should be created

frontend/package.json
=> Fix prettier pre-commit hook

frontend/cypress/integration/common/wizard_istio_config.ts, frontend/cypress/integration/featureFiles/wizard_istio_config.feature, frontend/src/pages/IstioConfigNew/GatewayForm.tsx, frontend/src/pages/IstioConfigNew/GatewayForm/AddressBuilder.tsx, frontend/src/pages/IstioConfigNew/GatewayForm/AddressList.tsx, frontend/src/pages/IstioConfigNew/GatewayForm/ListenerBuilder.tsx, frontend/src/pages/IstioConfigNew/GatewayForm/ListenerList.tsx, frontend/src/pages/IstioConfigNew/GatewayForm/ServerBuilder.tsx, frontend/src/pages/IstioConfigNew/GatewayForm/ServerList.tsx, frontend/src/pages/IstioConfigNew/K8sGatewayForm.tsx, frontend/src/pages/IstioConfigNew/ServiceEntryForm.tsx, frontend/src/types/IstioObjects.ts
=> Update Forms to add elements

business/checkers/k8sgateway_checker.go, business/checkers/k8sgateways/multi_match_checker.go, business/checkers/k8sgateways/multi_match_checker_test.go, business/checkers/k8sgateways/status_checker.go, business/checkers/k8shttproute_checker.go, business/checkers/k8shttproute_checker_test.go, business/checkers/k8shttproutes/no_host_checker.go, business/checkers/k8shttproutes/no_k8sgateway_checker.go, business/checkers/k8shttproutes/no_k8sgateway_checker_test.go, business/istio_config.go, business/references/k8s_gateway_references.go, business/references/k8s_gateway_references_test.go, business/references/k8shttproute_references.go, business/references/k8shttproute_references_test.go, frontend/src/components/IstioWizards/WizardActions.ts, graph/telemetry/istio/appender/istio_details.go, kubernetes/cache/kube_cache.go, kubernetes/filters.go, kubernetes/istio.go, kubernetes/types.go, models/istio_config.go, models/service.go, tests/data/k8sgateway_data.go, tests/integration/assets/bookinfo-k8sgateways-addresses.yaml, tests/integration/assets/bookinfo-k8sgateways-listeners.yaml, tests/integration/assets/bookinfo-k8sgateways.yaml, tests/integration/assets/bookinfo-k8shttproutes-gateways.yaml, tests/integration/assets/bookinfo-k8shttproutes-services.yaml
=> Migrate K8s Gateway API to v1beta1 version

hack/setup-kind-in-ci.sh
Always use the Helm chart downloaded from Kiali scripts.
Helm charts PR: https://github.com/kiali/helm-charts/pull/193
=> Use downloaded Helm instead of the packed in the VM

.github/workflows/build-backend.yml, .github/workflows/kiali-ci.yml, .github/workflows/release.yml, Makefile, go.mod
Fix https://github.com/kiali/kiali/issues/5799
=> [1.48] Upgrade go version to 1.19.4

business/authentication/openid_auth_controller.go
Fixes #5833 
Removed support for implicit flow in OpenID
=> Remove check for response type id_token

frontend/cypress/integration/common/wizard_istio_config.ts, frontend/src/pages/IstioConfigNew/GatewayForm.tsx, frontend/src/pages/IstioConfigNew/GatewayForm/AddressBuilder.tsx, frontend/src/pages/IstioConfigNew/GatewayForm/ListenerBuilder.tsx, frontend/src/pages/IstioConfigNew/GatewayForm/ServerBuilder.tsx, frontend/src/pages/IstioConfigNew/K8sGatewayForm.tsx, frontend/src/pages/IstioConfigNew/ServiceEntryForm.tsx, frontend/src/types/IstioObjects.ts
Fixes #5834 
- Use constant for MAX and MIN port numbers
- Use unique identifiers by row in form wizards
- Fix React warning
=> Fix port number and add unique identifiers for in some wizards

frontend/src/components/DebugInformation/DebugInformation.tsx
Add 'Download" button for Debug information
Closes #4276
=> Download button for debug info

hack/setup-kind-in-ci.sh
Ref. #5846 
Use kiali 1.16.2 in setup Kind script while latest image is not available
=> Use kiali 1.16.2 in setup Kind script while 1.17 image is not available

hack/istio/multicluster/kiali-create-remote-cluster-secret.sh
I noticed that the kubeconfig may have the CA data directly defined (as opposed to referring to a file that we then have to read in). This will happen if you install CRC/OpenShift, for example. If the certificate-authority-data is already in the kubeconfig, use it as-is. Otherwise, try to get the CA file and read it like before.
=> [hack] ca data might be specified directly (as with CRC)

hack/crc-openshift.sh
This version use:
- OpenShift 4.12.0
- Podman 4.3.1
- OKD 4.11.0-0.okd-2022-11-05-030711
=> Upgrade crc from 2.5 to 2.13.1

frontend/cypress/README.md, frontend/cypress/integration/common/wizard_istio_config.ts, frontend/cypress/integration/common/wizard_request_routing.ts, frontend/cypress/integration/featureFiles/wizard_istio_config.feature, frontend/cypress/support/commands.ts, frontend/src/components/IstioWizards/K8sGatewaySelector.tsx, frontend/src/components/IstioWizards/K8sRouteHosts.tsx, frontend/src/components/IstioWizards/ServiceWizard.tsx, frontend/src/pages/IstioConfigNew/GatewayForm/ListenerBuilder.tsx, frontend/src/utils/IstioConfigUtils.ts
Continues #5852.
Fixes https://github.com/kiali/kiali/issues/5802
=> Fix validation for K8s gateway hosts (continue)

server/server.go
see: https://issues.redhat.com/browse/OSSM-3438
=> explicitly declare support for HTTP2

frontend/src/components/IstioWizards/ServiceWizardActionsDropdownGroup.tsx, frontend/src/components/IstioWizards/ServiceWizardDropdown.tsx, frontend/src/components/IstioWizards/WizardAnnotations.tsx, frontend/src/components/IstioWizards/WorkloadWizardDropdown.tsx, models/service.go, models/workload.go
Fix https://github.com/kiali/kiali/issues/5864
=> Fix annotations if value is null

business/checkers/k8sgateways/multi_match_checker.go, business/checkers/k8sgateways/multi_match_checker_test.go, business/istio_validations.go
Resolves https://github.com/kiali/kiali/issues/5769
=> Add validation references to K8S Gateways validations

models/config_dump.go
Fixes https://github.com/kiali/kiali/issues/5872
Before:
After:
=> Fix display of Envoy listener DestinationPort

kiali.go, make/Makefile.build.mk
fixes: https://github.com/kiali/kiali/issues/5878
=> log the Go version when the server starts up

graph/telemetry/istio/istio.go
TelemtryVendor -> TelemetryVendor
None, it's a minor change
=> Fix typo in Go comment TelemtryVendor -> TelemetryVendor

business/checkers/sidecars/outbound_traffic_policy_mode.go, business/checkers/sidecars/outbound_traffic_policy_mode_test.go, business/checkers/sidecars_checker.go, models/istio_validation.go
fixes: https://github.com/kiali/kiali/issues/5882
=> validation: flag sidecar outbound traffic policy as ambiguous

hack/istio/install-error-rates-demo.sh
This PR adds a new modifier to the hack script that installs the errors rate demo:
`.hack/istio/install-error-rates-demo.sh -c kubectl -dd true`
Note: This is not supported for OpenShift for now.
Resolves https://github.com/kiali/kiali/issues/5884
=> distributed errors demo for multicluster testing

make/Makefile.operator.mk
fixes: https://github.com/kiali/kiali/issues/5945
=> [make] the --to option no longer writes to stdout so we need to refactor this.

README.adoc
=> provide gui debugger help in README

graph/telemetry/istio/appender/workload_entry_test.go
Fixed by using ChatGPT for issue https://github.com/kiali/kiali/issues/5972
=> Fixed failing test by sorting

frontend/cypress/integration/featureFiles/app_details.feature, frontend/cypress/integration/featureFiles/graph_display.feature, frontend/cypress/integration/featureFiles/graph_toolbar.feature, frontend/cypress/integration/featureFiles/istio_config_editor.feature, frontend/cypress/integration/featureFiles/istio_config_type_filters.feature, frontend/cypress/integration/featureFiles/istio_config_validation_filters.feature, frontend/cypress/integration/featureFiles/kiali_cookie.feature, frontend/cypress/integration/featureFiles/kiali_homepage.feature, frontend/cypress/integration/featureFiles/kiali_login.feature, frontend/cypress/integration/featureFiles/service_details.feature, frontend/cypress/integration/featureFiles/services.feature, frontend/cypress/integration/featureFiles/workloads.feature, frontend/reporter-config.json, hack/istio/download-istio.sh
details in https://github.com/kiali/kiali/pull/5948 and https://github.com/kiali/kiali/pull/5986
=> cherrypicking fixes for polarion to Kiali v1.57 [OSSM-3538]

business/apps.go, business/apps_test.go, business/health.go, business/istio_config.go, business/layer.go, frontend/package.json, frontend/src/components/VirtualList/Config.ts, frontend/src/config/Config.ts, frontend/src/helpers/__tests__/LabelFilterHelper.test.ts, frontend/src/pages/AppDetails/AppDetailsPage.tsx, frontend/src/pages/AppList/AppListClass.tsx, frontend/src/pages/AppList/AppListPage.tsx, frontend/src/services/Api.ts, frontend/src/types/App.ts, frontend/src/types/AppList.ts, handlers/apps.go, models/app.go
Fixes https://github.com/kiali/kiali/issues/5961
=> Applications list for Multicluster

business/services_test.go
=> Sort test before relying on order

business/apps.go
=> For apps list return error just if we are in single cluster

business/apps.go, business/health.go, business/health_test.go, business/services.go, business/workloads.go, handlers/health.go, handlers/workloads.go, prometheus/cache.go, prometheus/client.go, prometheus/metrics.go, prometheus/prometheustest/mock.go
=> Multicluster - Health for applications/services/workloads

business/jaeger.go, business/services.go, frontend/src/components/JaegerIntegration/TracesComponent.tsx, frontend/src/components/Metrics/IstioMetrics.tsx, frontend/src/components/TrafficList/TrafficDetails.tsx, frontend/src/components/TrafficList/TrafficListComponent.tsx, frontend/src/hooks/services.ts, frontend/src/pages/IstioConfigList/IstioConfigListPage.tsx, frontend/src/pages/Overview/OverviewPage.tsx, frontend/src/pages/ServiceDetails/ServiceDetailsPage.tsx, frontend/src/pages/ServiceDetails/ServiceInfo.tsx, frontend/src/services/Api.ts, frontend/src/services/GraphDataSource.ts, frontend/src/types/ServiceInfo.ts, handlers/dashboards.go, handlers/jaeger.go, handlers/services.go, models/service.go
Fixes https://github.com/kiali/kiali/issues/5964
=> Services details view

frontend/cypress/integration/featureFiles/kiali_login.feature
just removing one annoying test that fails on OCP all the time
this will be reworked later to comply with interop pipeline, where it fails all the time
=> removing flaky login test [OSSM-3772]

frontend/cypress/integration/featureFiles/kiali_login.feature
same as https://github.com/kiali/kiali/pull/6078
=> [1.57] removing flaky login test [OSSM-3772]

frontend/cypress/integration/featureFiles/kiali_login.feature
same as https://github.com/kiali/kiali/pull/6078
=> [1.65] removing flaky login test [OSSM-3772]

business/apps.go, business/apps_test.go, business/jaeger.go, frontend/src/components/Details/DetailDescription.tsx, frontend/src/components/Metrics/IstioMetrics.tsx, frontend/src/config/Config.ts, frontend/src/pages/AppDetails/AppDescription.tsx, frontend/src/pages/AppDetails/AppDetailsPage.tsx, frontend/src/pages/AppDetails/AppInfo.tsx, frontend/src/pages/Graph/SummaryPanelCommon.tsx, frontend/src/services/Api.ts, frontend/src/services/GraphDataSource.ts, frontend/src/types/App.ts, handlers/apps.go, handlers/dashboards.go, handlers/jaeger.go, handlers/metrics.go
Subtask https://github.com/kiali/kiali/issues/5966
=> App details view multicluster

business/istio_config.go, frontend/src/components/Ambient/AmbientBadge.tsx
Fixes https://github.com/kiali/kiali/issues/6103
=> Change configmap istio-cni error message for debug

frontend/src/pages/AppDetails/AppDescription.tsx, frontend/src/pages/ServiceDetails/ServiceDescription.tsx, frontend/src/pages/WorkloadDetails/WorkloadDescription.tsx
Fixes https://github.com/kiali/kiali/issues/6107
=> Check number of clusters to show the cluster badge in details pages

deploy/docker/Dockerfile-cypress
cherrypicking for v1.57
same as https://github.com/kiali/kiali/pull/6029
=> [v1.57] [OSSM-1216] cypress container

business/istio_config.go, kubernetes/cache/kube_cache.go
fixes: https://github.com/kiali/kiali/issues/6114
=> fix bug when doing cluster-scoped lookups when not authorized to do so [OSSM-3868]

frontend/cypress/integration/common/wizard_istio_config.ts
- some slight reformatting as well
https://issues.redhat.com/browse/OSSM-3809
=> Try and resolve rare cypress flake

business/mesh.go
fixes: https://github.com/kiali/kiali/issues/6124
=> do not hardcode istio label names

business/mesh.go
fixes: https://github.com/kiali/kiali/issues/6124
cherry-pick of https://github.com/kiali/kiali/pull/6125
=> [v1.65] do not hardcode istio label names

frontend/src/pages/IstioConfigDetails/IstioObjectDetails/IstioConfigOverview.tsx
=> Add cluster badge in Istio config details 

frontend/src/app/AuthenticationController.tsx
=> Remove the check for number of valid Kiali instances in remote clusters

frontend/cypress/integration/common/sidecar_injection.ts, frontend/cypress/integration/common/wizard_istio_config.ts
- also, reformatting automatically applied, sorry, but I guess it's necessary.
https://issues.redhat.com/browse/OSSM-3940
Manual backport of https://github.com/kiali/kiali/pull/6143
=> [v1.65] Try to fix flakes by ensuring button visibility before click

frontend/src/components/TrafficList/TrafficListComponent.tsx
=> Showing cluster in the traffic details

business/metrics.go, frontend/src/actions/JaegerThunkActions.ts, frontend/src/actions/MetricsStatsThunkActions.ts, frontend/src/components/JaegerIntegration/JaegerResults/SpanDetails.tsx, frontend/src/components/JaegerIntegration/JaegerResults/SpanTable.tsx, frontend/src/components/JaegerIntegration/JaegerResults/TraceDetails.tsx, frontend/src/components/JaegerIntegration/JaegerScatter.tsx, frontend/src/components/JaegerIntegration/TracesComponent.tsx, frontend/src/components/JaegerIntegration/TracesFetcher.ts, frontend/src/pages/Graph/GraphPage.tsx, frontend/src/pages/Graph/SummaryPanelCommon.tsx, frontend/src/pages/Graph/SummaryPanelNamespaceBox.tsx, frontend/src/pages/Graph/SummaryPanelNodeTraces.tsx, frontend/src/pages/Graph/SummaryPanelTraceDetails.tsx, frontend/src/pages/Overview/OverviewPage.tsx, frontend/src/services/Api.ts, frontend/src/types/JaegerInfo.ts, frontend/src/types/MetricsOptions.ts, frontend/src/utils/tracing/TraceStats.ts, frontend/src/utils/tracing/TraceTransform.ts, frontend/src/utils/tracing/TracingHelper.ts, frontend/src/utils/tracing/__tests__/TracingHelper.test.ts, handlers/metrics.go, models/metrics.go
Fix https://github.com/kiali/kiali/issues/6065
=> Multicluster - Add cluster params for metrics 

frontend/src/services/GraphDataSource.ts
Resolves #6062.
Given the following graph topology:
Service's minigraph for ratings on west cluster
Application's minigraph for ratings on west cluster
Application's minigraph for reviews on west cluster
Service's minigraph for reviews on west cluster
=> Fix app and service minigraph on multicluster

frontend/src/types/ErrorRate/GraphEdgeStatus.ts
fixes: https://github.com/kiali/kiali/issues/6138
=> ensure healed graph edges go back to green on refresh

frontend/src/types/ErrorRate/GraphEdgeStatus.ts
backport of: https://github.com/kiali/kiali/pull/6165
part of: https://github.com/kiali/kiali/issues/6138
=> [v1.65] ensure healed graph edges go back to green on refresh

frontend/src/types/ErrorRate/GraphEdgeStatus.ts
backport of: https://github.com/kiali/kiali/pull/6165
part of: https://github.com/kiali/kiali/issues/6138
=> [v1.67] ensure healed graph edges go back to green on refresh

deploy/docker/Dockerfile-cypress
Adding missing packages to cypress image
=> Adding missing packages to cypress image

deploy/docker/Dockerfile-cypress
Adding missing packages to cypress image
=> [v1.57] Adding missing packages to cypress image

tests/integration/README.md, tests/integration/run-tests.sh
Also getting kiali route dynamically
=> [v1.57] Adding readme for int tests in a container

frontend/cypress/integration/common/sidecar_injection.ts
Update Cypress to handle that use-case.
https://issues.redhat.com/browse/OSSM-3989
=> Kiali does not handle namespace-level injection enable/disable for Maistra

frontend/cypress/integration/common/sidecar_injection.ts, frontend/cypress/integration/common/wizard_istio_config.ts
v1.65 Backport of https://github.com/kiali/kiali/pull/6172 to resolve some cypress failures.
=> [v1.65] Kiali does not handle namespace-level injection enable/disable for Maistra 

frontend/cypress/integration/common/apps.ts, frontend/cypress/integration/common/wizard_istio_config.ts, frontend/cypress/integration/featureFiles/wizard_istio_config.feature
- Improve previous apps.ts fix
- Simplify the unexplained failing action in wizard_istio_config tests in the hopes that it improves the situation.
Just merging, CI will tell us if it's good...
=> [v1.65] More cypress fix attempts for the downstream CI

kubernetes/cache/kube_cache.go, tests/integration/tests/no_istiod_test.go
=> Check kube cache namespace

util/httputil/http_util.go
fixes: https://github.com/kiali/kiali/issues/6180
cherry-pick of: https://github.com/kiali/kiali/pull/6181
=> [v1.57] authenticate when kiali is deployed behind openshift route with non-standard port

make/Makefile.operator.mk, util/httputil/http_util.go
fixes: https://github.com/kiali/kiali/issues/6180
cherry-pick of: https://github.com/kiali/kiali/pull/6181
=> [v1.65] authenticate when kiali is deployed behind openshift route with non-standard port

.github/workflows/kiali-ci.yml
see https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#using-filters-to-target-specific-branches-or-tags-for-push-events
=> [github workflow] fix regex in branches setting

config/config.go, tests/integration/assets/remote-istiod/proxy-patch.yaml, tests/integration/tests/applications_test.go, tests/integration/tests/config_validations_test.go, tests/integration/tests/dashboards_test.go, tests/integration/tests/external_host_node_test.go, tests/integration/tests/graph_badges_test.go, tests/integration/tests/graph_nodes_test.go, tests/integration/tests/graph_test.go, tests/integration/tests/istio_config_test.go, tests/integration/tests/kiali_metrics_test.go, tests/integration/tests/kiali_urls_test.go, tests/integration/tests/namespaces_test.go, tests/integration/tests/no_istiod_test.go, tests/integration/tests/pod_logs_test.go, tests/integration/tests/remote_istiod_test.go, tests/integration/tests/services_test.go, tests/integration/tests/traces_spans_test.go, tests/integration/tests/workloads_test.go, tests/integration/utils/kiali/kiali_client.go, tests/integration/utils/kiali_client.go, tests/integration/utils/kube/kube_client.go, tests/integration/utils/kube_client.go
Refactor some integration tests. 
Fixes https://github.com/kiali/kiali/issues/6203 
- Use Istio Deployment name for patching istio deployment
- Use nginx unprivileged for proxy patch so no permission issues in OCP.
=> Create kube client with common funcions

Makefile, go.mod, go.sum, handlers/authentication_test.go, kiali_test.go, make/Makefile.build.mk, server/server_test.go, tools/generator/generator.go
Fix issue https://github.com/kiali/kiali/issues/6218
```bash
agutierr@agutierr:~/kiali/kiali (issue_6218_master)$go mod tidy -v
go: downloading gopkg.in/check.v1 v1.0.0-20200227125254-8fa46927fb4f
go: downloading github.com/mwitkow/go-conntrack v0.0.0-20190716064945-2f068394615f
go: downloading github.com/armon/go-socks5 v0.0.0-20160902184237-e75332964ef5
go: downloading github.com/google/uuid v1.1.2
go: downloading google.golang.org/appengine v1.6.7
go: downloading github.com/onsi/ginkgo v1.14.0
go: downloading github.com/jpillora/backoff v1.0.0
go: downloading github.com/niemeyer/pretty v0.0.0-20200227124842-a10e7caefd8e
go: downloading github.com/kr/text v0.2.0
```
=> Upgrade go version to 1.20

hack/istio/multicluster/deploy-kiali.sh
the west and east now use the east's issuer uri:
$ kubectl get cm kiali -n istio-system --context west -oyaml | grep issuer_uri
issuer_uri: https://keycloak-192-168-59-254.nip.io/realms/kube
$ kubectl get cm kiali -n istio-system --context east -oyaml | grep issuer_uri
issuer_uri: https://keycloak-192-168-59-254.nip.io/realms/kube
$ minikube -p east ip
192.168.59.254
=> [hack] fix multicluster hack script so west cluster can use keycloak in east

business/checkers/checker.go, business/checkers/common/multi_match_selector_checker.go, business/checkers/common/multi_match_selector_checker_test.go, business/checkers/destination_rules_checker.go, business/checkers/destinationrules/multi_match_checker.go, business/checkers/gateway_checker.go, business/checkers/gateways/multi_match_checker.go, business/checkers/peer_authentication_checker.go, business/checkers/request_authentication_checker.go, business/checkers/sidecars_checker.go, business/checkers/virtual_service_checker.go, business/checkers/virtualservices/single_host_checker.go, business/istio_validations.go, business/istio_validations_test.go, business/layer.go, business/workloads.go, frontend/src/pages/Overview/OverviewPage.tsx, handlers/istio_config.go
RFE https://github.com/kiali/kiali/issues/5967
Subtask: https://github.com/kiali/kiali/issues/6056
Istio config list and details shows validations from remote clusters.
=> Remote cluster configs validation

frontend/cypress/README.md
cherry picking docs for container
=> added container readme for v1.65 [OSSM-1216]

frontend/src/types/IstioObjects.ts
Fix the type of some istio object fields (K8sMetadata and K8sOwnerReference) 
Fixes #6011
=> Fix Istio object type fields

hack/setup-kind-in-ci.sh
try to get CI to pass on 1.57 branch
=> try to get CI to pass on 1.57 branch

hack/setup-kind-in-ci.sh
=> try to get CI to pass on 1.65 branch

Makefile, go.mod, handlers/authentication_test.go, kiali_test.go, make/Makefile.build.mk, server/server_test.go, tools/generator/generator.go
Fix https://github.com/kiali/kiali/issues/6218
=> [1.65] Upgrade go to 1.20

frontend/src/pages/AppDetails/AppDetailsPage.tsx, frontend/src/pages/ServiceDetails/ServiceDetailsPage.tsx, frontend/src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
Fix history build issue produced by PR #6288
Fixes #6298
=> Fix history build issue

business/services.go
Cherry pick of https://github.com/kiali/kiali/pull/6295
=> Fixed showing error when Service is found in registry.

hack/setup-kind-in-ci.sh
Update Kind version to fix CI failing workflow
Fixes #6300
=> Update kind version on CI test setup

frontend/src/app/History.ts, frontend/src/routes/AppDetailsRoute.tsx, frontend/src/routes/GraphRoute.tsx, frontend/src/routes/IstioConfigDetailsRoute.tsx, frontend/src/routes/IstioConfigNewRoute.tsx, frontend/src/routes/ServiceDetailsRoute.tsx, frontend/src/routes/WorkloadDetailsRoute.tsx, frontend/src/services/Api.ts
Add Kiali proxy value from environment variable (optional) to API url.
Closes #6265
=> Add Kiali proxy to API url

frontend/cypress/integration/common/kiali_login.ts
=> login fix backport (#6305)

deploy/docker/Dockerfile-cypress, frontend/cypress/README.md
Adding cypress image dockerfile and updating readme. This is needed for interop job to use OSSM 2.4
=> [v1.65] Cypress image

SECURITY.md
We have been getting some security scans from the community where they are running reports and blindly sending them to us without doing any kind of validation or verification of those reports. We want to ask people to at least make sure (a) they are running them on the latest version and (b) that they aren't old security issues that don't affect Kiali in any way.
=> security scan notice

frontend/src/pages/Mesh/MeshPage.tsx
Fixes https://github.com/kiali/kiali/issues/6338
=> Remove the experimental warning in the Mesh page

frontend/src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
Issue https://github.com/kiali/kiali/issues/6330
=> Show wizard items for all cluster's service detail in graph

frontend/cypress/integration/common/graph_display.ts, frontend/cypress/integration/common/hooks.ts, frontend/cypress/integration/featureFiles/graph_display.feature, hack/istio/install-error-rates-demo.sh
Related to #6331 
**NOTE - this requires merge of error-rates demo update, see https://github.com/kiali/demos/pull/52**
=> Enhance the cypress testing related to the kiali6331 Show Idle Nodes bug

frontend/cypress/integration/common/istio_config.ts, frontend/cypress/integration/common/istio_config_validation_filters.ts, frontend/cypress/integration/common/label_check.ts
Backport the flaky test fix from https://github.com/kiali/kiali/pull/5733
=> Backport flaky test fix

hack/istio/multicluster/deploy-kiali.sh
fixes https://github.com/kiali/kiali/issues/6366
=> ensure var is alway set

kubernetes/cache/kube_cache.go
fixes https://github.com/kiali/kiali/issues/6380
=> support namespace scoped gateway informers

kubernetes/cache/kube_cache.go
=> [v1.66] Add correct resource to registry handler

hack/setup-kind-in-ci.sh
=> [v1.66] Backport - Update kind version (#6301)

frontend/cypress/integration/common/label_check.ts
Fix for https://github.com/kiali/kiali/issues/6390
=> Fix potential flaky test by timeout

business/istio_config.go
Fixes https://github.com/kiali/kiali/issues/6401
Create a more robust way to detect Istio Ambient
=> Update the way kiali identifies Ambient

hack/istio/install-bookinfo-demo.sh
=> [hack] check that /productpage can be accessed via ingress

hack/istio/install-bookinfo-demo.sh
Include waypoint option to create a waypoint proxy in bookinfo demo hack script. Just in case ambient is enabled
Ref. https://github.com/kiali/kiali/issues/5476
=> Include waypoint creation in bookinfo demo hack script

hack/istio/multicluster/start-minikube.sh
Pinning to the last known working version of keycloak.
Workaround but not a complete solution for #6455
=> Update tls value for keycloak helm

hack/run-integration-tests.sh
Removes old options from the help text and adds a `setup_only` option that will setup the environment for you but not run the integration tests.
=> Cleanup unused options and add a setup-only opt

hack/ci-kind-molecule-tests.sh, hack/run-molecule-tests.sh
helps people run this via cron and not require to have kind in path
=> [hack] update to ci-kind-molecule hack script so you can specify the kind executable

hack/ci-kind-molecule-tests.sh
fixes: https://github.com/kiali/kiali/issues/6481
this also has a small change to infomsg to support -n (no newline at the end)
=> [hack] [molecule] allow OLM installed operator to change security contexts

hack/istio/multicluster/install-multi-primary.sh, hack/istio/multicluster/install-primary-remote.sh, hack/istio/multicluster/setup-tracing.sh
Aggregates tracing in local/testing multicluster environments.
=> Add hack script to aggregate traces in MC env

frontend/src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
Cherry-pick of https://github.com/kiali/kiali/issues/6374
=> Fixed null replacement in json

frontend/src/components/BreadcrumbView/BreadcrumbView.tsx, frontend/src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx, frontend/src/components/CytoscapeGraph/MiniGraphCard.tsx, frontend/src/components/DetailDescription/DetailDescription.tsx, frontend/src/components/TrafficList/TrafficListComponent.tsx, frontend/src/pages/Overview/OverviewPage.tsx, frontend/src/services/GraphDataSource.ts
Issue https://github.com/kiali/kiali/issues/6487
Check:
Traffic tab links.
Service/App/Workload details page links.
Graph page links.
Overview page metrics functionality.
=> Skip clusterName param in single cluster

kubernetes/client.go, kubernetes/kubernetes.go
fixes: https://github.com/kiali/kiali/issues/6387
=> ensure safety with concurrent access to some k8s client fields

business/workloads.go
**Fix comment error**
fix comment for cronjob
=> fix comment for cronjob

frontend/src/components/BreadcrumbView/BreadcrumbView.tsx, frontend/src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx, frontend/src/components/CytoscapeGraph/MiniGraphCard.tsx, frontend/src/components/DetailDescription/DetailDescription.tsx, frontend/src/components/Link/IstioObjectLink.tsx, frontend/src/components/Link/KialiPageLink.tsx, frontend/src/components/Link/ServiceLink.tsx, frontend/src/components/Link/WorkloadLink.tsx, frontend/src/components/TrafficList/TrafficListComponent.tsx, frontend/src/components/VirtualList/Renderers.tsx, frontend/src/config/ServerConfig.ts, frontend/src/pages/AppDetails/AppDescription.tsx, frontend/src/pages/AppList/AppListPage.tsx, frontend/src/pages/Graph/SummaryPanelAppBox.tsx, frontend/src/pages/Graph/SummaryPanelNode.tsx, frontend/src/pages/IstioConfigDetails/IstioObjectDetails/IstioConfigOverview.tsx, frontend/src/pages/IstioConfigList/IstioConfigListPage.tsx, frontend/src/pages/Overview/OverviewPage.tsx, frontend/src/pages/ServiceDetails/ServiceDescription.tsx, frontend/src/pages/ServiceList/ServiceListPage.tsx, frontend/src/pages/WorkloadDetails/WorkloadDescription.tsx, frontend/src/pages/WorkloadList/WorkloadListPage.tsx, frontend/src/services/GraphDataSource.ts
Fixes https://github.com/kiali/kiali/issues/6544
- Add cluster badging to Node side panel in MC env
- Add 'clusterName' param to links in MC env
- other
- make ServerConfig#isMultiCluster a boolean var, calculated once, as opposed to a function
- add ServerConfig#isHomeCluster utility
- add ServerConfig#isConfiguredCluster utility
=> Fix multi-cluster issues in graph side panel

frontend/src/components/Nav/NavUtils.tsx, frontend/src/pages/Graph/GraphPage.tsx, frontend/src/pages/GraphPF/GraphPagePF.tsx, frontend/src/pages/GraphPF/components/stylesComponentFactory.tsx, frontend/src/utils/SearchParamUtils.ts
Fixes https://github.com/kiali/kiali/issues/6548
=> [WIP] Fix for double tap on a node in MC redirecting to wrong cluster

frontend/src/pages/Graph/GraphHelpTour.tsx, frontend/src/pages/Graph/SummaryPanel.tsx, frontend/src/pages/GraphPF/GraphPF.tsx, frontend/src/pages/GraphPF/GraphPagePF.tsx
Resolves https://github.com/kiali/openshift-servicemesh-plugin/issues/202
This PR fixes two stops that weren't working in PF graph (Layout and Legend) and also updates a little bit some wording in the Graph and ContextualMenu stops.
=> Fix some tour stops in PF graph

frontend/cypress/integration/featureFiles/app_details_multicluster.feature, frontend/cypress/integration/featureFiles/app_details_multicluster_graph.feature, frontend/cypress/integration/featureFiles/service_details_multicluster.feature, frontend/cypress/integration/featureFiles/workloads_details_multicluster.feature
=> Multicluster Gherkin scenarios for details pages

frontend/cypress/integration/featureFiles/graph_display.feature
=> Multicluster - Gherkin scenarios for graph page

frontend/src/pages/WorkloadDetails/WorkloadPodLogs.tsx
This line caused an error in 1.65 CI testing. See https://github.com/kiali/kiali/pull/6569
We don't see it in master for some reason but we want this change anyway.
=> fix error that shows up in testing

hack/ci-kind-molecule-tests.sh
fixes: https://github.com/kiali/kiali/issues/6567
=> make molecule test script more tolerant of slow-starting operator

frontend/src/pages/Overview/Sorts.ts
Fixes https://github.com/kiali/kiali/issues/6504
=> Fix Cluster column sort on Overview list view

frontend/package.json, frontend/src/setupTests.ts, frontend/yarn.lock
Fix https://github.com/kiali/kiali/issues/6587
Remove CI=false
Fix some issues relted with patternfly 5.0.2
=> Upgrade patternfly to 5.0.4

frontend/src/components/Pf/PfColors.tsx
Refactor PFColors. Only replace colors in one site
=> Refactor PFColors

frontend/package.json, frontend/src/components/Health/__tests__/__snapshots__/HealthIndicator.test.tsx.snap, frontend/src/components/Label/__tests__/__snapshots__/Label.test.tsx.snap, frontend/src/components/Label/__tests__/__snapshots__/Labels.test.tsx.snap, frontend/src/components/ToolbarDropdown/__tests__/__snapshots__/ToolbarDropdown.test.tsx.snap, frontend/src/components/Validations/__tests__/__snapshots__/ServiceValidationSummary.test.tsx.snap, frontend/src/components/Validations/__tests__/__snapshots__/ValidationSummary.test.tsx.snap, frontend/src/pages/Graph/GraphToolbar/__tests__/__snapshots__/GraphLegend.test.tsx.snap, frontend/src/pages/Login/__tests__/__snapshots__/LoginPage.test.tsx.snap, frontend/src/pages/Overview/__tests__/__snapshots__/OverviewPage.test.tsx.snap, frontend/src/pages/WorkloadDetails/__tests__/__snapshots__/ProxyStatusList.test.tsx.snap, frontend/src/styles/StyleUtils.ts
Backport of #6562 to Kiali version v1.73
=> [v1.73] Backport - Increase specificity of kiali style (#6562)

frontend/src/pages/GraphPF/components/groupExpanded.tsx, frontend/src/pages/GraphPF/components/node.tsx
Backport of https://github.com/kiali/kiali/pull/6459 to Kiali version v1.73
=> [v1.73] Backport - Protect console errors when "raising" d3 target in PFT graph (#6459)

frontend/src/pages/IstioConfigDetails/IstioObjectDetails/IstioConfigOverview.tsx
Backport of https://github.com/kiali/kiali/pull/6596 to Kiali version v1.73
=> [v1.73] Backport - 'Edit in Kiali' link (kiosk mode) (#6596)

frontend/package.json, frontend/src/components/Charts/ChartWithLegend.tsx, frontend/src/components/Charts/Container.tsx, frontend/yarn.lock
Backport of https://github.com/kiali/kiali/pull/6584 to Kiali version v1.73
=> [v1.73] Backport - Remove PF direct dependencies from package.json (#6584)

frontend/cypress/integration/common/istio_config.ts, frontend/cypress/integration/common/istio_config_type_filters.ts, frontend/cypress/integration/common/table.ts, frontend/cypress/integration/featureFiles/apps.feature, frontend/cypress/integration/featureFiles/istio_config.feature, frontend/cypress/integration/featureFiles/istio_config_type_filters.feature, frontend/cypress/integration/featureFiles/services.feature, frontend/cypress/integration/featureFiles/workloads.feature, frontend/src/pages/AppList/FiltersAndSorts.ts, frontend/src/pages/IstioConfigList/FiltersAndSorts.ts, frontend/src/pages/ServiceList/FiltersAndSorts.ts, frontend/src/pages/WorkloadList/FiltersAndSorts.ts
=> [v1.73] Prevent "istio type" filter carryover

frontend/src/pages/Overview/Sorts.ts
=> [v1.73] Fix cluster sort on Overview list view

frontend/src/pages/Graph/GraphPage.tsx, frontend/src/pages/GraphPF/GraphPagePF.tsx, frontend/src/pages/ServiceDetails/ServiceInfo.tsx
Issue https://github.com/kiali/kiali/issues/6615
=> Added missing cluster params in graph wizards.

hack/istio/install-istio-via-istioctl.sh
fixes: https://github.com/kiali/kiali/issues/6635
=> allow some of the istio and addon deployments to be deployed on openshift

hack/istio/install-istio-via-istioctl.sh
more for https://github.com/kiali/kiali/issues/6635
=> specifically specify istio SAs. remove priviledged permissions, that is not needed

hack/istio/multicluster/env.sh, hack/istio/multicluster/install-multi-primary.sh, hack/istio/multicluster/install-primary-remote.sh, hack/run-integration-tests.sh, hack/setup-kind-in-ci.sh
this will help with testing PRs like this one that works only with the upstream Istio master branch, but not with any releases yet - https://github.com/kiali/kiali/pull/6629
=> [CI] [hack] be able to run integration tests using Istio dev builds

.github/workflows/build-frontend.yml, .github/workflows/integration-tests-frontend-multicluster.yml, .github/workflows/integration-tests-frontend.yml, frontend/package.json, frontend/src/pages/WorkloadDetails/WorkloadPodLogs.tsx, frontend/src/pages/WorkloadDetails/__tests__/WorkloadPodLogs.test.tsx, frontend/src/services/__tests__/ApiMethods.test.tsx.ts, frontend/yarn.lock
Backport of https://github.com/kiali/kiali/pull/6582 to Kiali version v1.73
=> [v1.73] Add openssl-legacy-provider flag to support Node 18 (#6582)

frontend/src/pages/GraphPF/GraphPF.tsx, frontend/src/pages/GraphPF/GraphPFElems.tsx, frontend/src/pages/GraphPF/GraphPagePF.tsx, frontend/src/pages/GraphPF/components/group.tsx, frontend/src/pages/GraphPF/components/groupExpanded.tsx, frontend/src/pages/GraphPF/components/node.tsx, frontend/src/pages/GraphPF/styles/styleGroup.tsx, frontend/src/pages/GraphPF/styles/styleNode.tsx
Resolves https://github.com/kiali/openshift-servicemesh-plugin/issues/203.
=> Add a focus animation when going back from node graph

frontend/src/components/IstioConfigPreview/EditorPreview.tsx, frontend/src/components/Kiosk/KioskActions.ts, frontend/src/components/Nav/Page/RenderComponentScroll.tsx, frontend/src/components/Nav/RenderPage.tsx, frontend/src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx, frontend/src/pages/WorkloadDetails/WorkloadPodLogs.tsx, frontend/src/services/Api.ts
Backport of https://github.com/kiali/kiali/pull/6607 to Kiali version v1.73
=> [v1.73] Make the scrollbar in RenderComponentScroll optional (#6607)

frontend/src/components/Nav/NavUtils.tsx, frontend/src/pages/Graph/GraphPage.tsx, frontend/src/pages/GraphPF/GraphPagePF.tsx, frontend/src/pages/GraphPF/components/stylesComponentFactory.tsx, frontend/src/utils/SearchParamUtils.ts
Backport of https://github.com/kiali/kiali/pull/6542 to Kiali version v1.73
=> [v1.73] Fix for double tap on a node in MC redirecting to wrong cluster (#6542)

frontend/src/components/BreadcrumbView/BreadcrumbView.tsx, frontend/src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx, frontend/src/components/CytoscapeGraph/MiniGraphCard.tsx, frontend/src/components/DetailDescription/DetailDescription.tsx, frontend/src/components/Link/IstioObjectLink.tsx, frontend/src/components/Link/KialiPageLink.tsx, frontend/src/components/Link/ServiceLink.tsx, frontend/src/components/Link/WorkloadLink.tsx, frontend/src/components/TrafficList/TrafficListComponent.tsx, frontend/src/components/VirtualList/Renderers.tsx, frontend/src/config/ServerConfig.ts, frontend/src/pages/AppDetails/AppDescription.tsx, frontend/src/pages/AppList/AppListPage.tsx, frontend/src/pages/Graph/SummaryPanelAppBox.tsx, frontend/src/pages/Graph/SummaryPanelNode.tsx, frontend/src/pages/IstioConfigDetails/IstioObjectDetails/IstioConfigOverview.tsx, frontend/src/pages/IstioConfigList/IstioConfigListPage.tsx, frontend/src/pages/Overview/OverviewPage.tsx, frontend/src/pages/ServiceDetails/ServiceDescription.tsx, frontend/src/pages/ServiceList/ServiceListPage.tsx, frontend/src/pages/WorkloadDetails/WorkloadDescription.tsx, frontend/src/pages/WorkloadList/WorkloadListPage.tsx, frontend/src/services/GraphDataSource.ts
Backport of https://github.com/kiali/kiali/pull/6551 to Kiali version v1.73
=> [v1.73] Fix multi-cluster issues in graph side panel (#6551)

frontend/src/pages/GraphPF/GraphPF.tsx, frontend/src/pages/GraphPF/GraphPFElems.tsx, frontend/src/pages/GraphPF/GraphPagePF.tsx, frontend/src/pages/GraphPF/components/group.tsx, frontend/src/pages/GraphPF/components/groupExpanded.tsx, frontend/src/pages/GraphPF/components/node.tsx, frontend/src/pages/GraphPF/styles/styleGroup.tsx, frontend/src/pages/GraphPF/styles/styleNode.tsx
=> [v1.73] Add a focus animation when going back from node graph (#6642)

frontend/cypress/integration/featureFiles/graph_context_menu.feature, frontend/cypress/integration/featureFiles/graph_side_panel.feature, frontend/cypress/integration/featureFiles/service_details.feature, frontend/cypress/integration/featureFiles/wizard_istio_config_multicluster.feature, frontend/cypress/integration/featureFiles/wizard_request_routing.feature
=> Gherkin scenarios for Istio Config page

frontend/src/pages/Graph/GraphPage.tsx, frontend/src/pages/GraphPF/components/stylesComponentFactory.tsx
Fixes https://github.com/kiali/kiali/issues/6657
=> Fix double tap on same node

README.adoc
https://github.com/kiali/kiali/blob/master/frontend/package.json#L145
Update README.adoc with current version of node in package.json
* If this is a fix for a GH-issue, please link it here
=> Update README.adoc based on frontend/package.json

hack/istio/tempo/install-tempo-env.sh
Fixes: https://github.com/kiali/kiali/issues/6663 
Run: 
`istio/tempo/install-tempo-env.sh -c oc`
Kiali config: 
```
tracing:
enabled: true
provider: "tempo"
in_cluster_url: http://localhost:3200
url: http://tempo-cr-query-frontend-tempo.apps-crc.testing
```
=> Update tempo hack script for OpenShift

tracing/otel/model/converter/converter.go, tracing/otel/model/json/model.go, tracing/tempo/http_client.go
Fixes #6674 
How to validate: 
- Go to the Graph page. 
- Select a workload 
- In the summary panel view, select Traces
- Select one trace. 
- All the trace path should be highlighted in the map.
=> Tempo support - Convert references to Jaeger 

frontend/src/components/IstioWizards/WizardActions.ts
Issue https://github.com/kiali/kiali/issues/6702
Overview page, Namespace card's actions => Create Traffic Policies:
=> Fixed AuthPolicy apiVersion in overview wizard.

.github/workflows/build-backend.yml, .github/workflows/kiali-ci.yml, .github/workflows/release.yml, Makefile
Ref. https://github.com/kiali/kiali/issues/6716
=> [backport 1.48] Update go version 1.20.10

frontend/cypress/integration/featureFiles/wizard_request_routing.feature
Backport of https://github.com/kiali/kiali/commit/39ba5ba9b4a8d7e088ae3228f6f227729824a298#diff-4ae784ad0be35a26c3cedb2593703569ba1060a9a05344760d2919f28b0adb22
=> [v1.57] Fix for wizard request routing test

frontend/cypress/integration/featureFiles/wizard_request_routing.feature
Backport of https://github.com/kiali/kiali/commit/39ba5ba9b4a8d7e088ae3228f6f227729824a298#diff-4ae784ad0be35a26c3cedb2593703569ba1060a9a05344760d2919f28b0adb22
=> [v1.65] Fix for wizard request routing test

Makefile
Fixes https://github.com/kiali/kiali/issues/6716
=> [backport 1.75] Update go version 1.20.10

README.adoc
=> added Kind in README

Makefile, WORKING_WITH_OSSMC.md, hack/run-molecule-tests.sh, make/Makefile.cluster.mk, make/Makefile.molecule.mk, make/Makefile.olm.mk, make/Makefile.operator.mk
- Kiali: https://github.com/kiali/kiali/pull/6691
- Kiali Operator: https://github.com/kiali/kiali-operator/pull/691
- Helm Charts: https://github.com/kiali/helm-charts/pull/226
- Kiali.io docs: https://github.com/kiali/kiali.io/pull/705
- OSSMC: https://github.com/kiali/openshift-servicemesh-plugin/pull/211
see: https://issues.redhat.com/browse/OSSM-4944
=> support for OSSMC in the Kiali Operator

Makefile
Fixes https://github.com/kiali/kiali/issues/6716
=> [backport 1.66] Update go version 1.19.13

frontend/cypress/integration/featureFiles/istio_config.feature
Cherry-pick of https://github.com/kiali/kiali/pull/6727
=> [v1.57] Added wildcard validation scenario for KIA0301

frontend/cypress/integration/featureFiles/istio_config.feature
Cherry-pick of https://github.com/kiali/kiali/pull/6727
=> [v1.65] Added wildcard validation scenario for KIA0301

frontend/cypress/integration/featureFiles/istio_config.feature
Added new test for KIA0301 in wildcards.
=> Added wildcard validation scenario for KIA0301

frontend/src/components/About/AboutUIModal.tsx
Fixes #6687 
Not sure if we should hide the query param in the url link?
=> Tempo - Update the main external link to distributed tracing

hack/run-kiali-config-template.yaml, hack/run-kiali.sh
fixes: https://github.com/kiali/kiali/issues/6742
=> run-kiali.sh now works if Istio is installed with an unset cluster name

hack/istio/install-istio-via-istioctl.sh
Fixes https://github.com/kiali/kiali/issues/6751
=> istio hack script: cluster name should not be set to empty string

handlers/dashboards.go
Issue https://github.com/kiali/kiali/issues/6745
Service details metrics now is filtering by cluster.
=> Added missing cluster param

frontend/src/components/Metrics/CustomMetrics.tsx, frontend/src/services/Api.ts, frontend/src/types/MetricsOptions.ts
https://github.com/kiali/kiali/issues/6731
** First commit  **
https://github.com/kiali/kiali/pull/6737
Thank you for your suggestions. 
Now I have resubmitted the PR to fix this problem, please review my code! 
I fix this issue on frontend now.
=> Fixed getting cluster name from url on frontend

hack/setup-kind-in-ci.sh
Add absolute script dir path in setup-kind-ci.sh script
Fixes #6750
=> Add absolute script dir path in setup-kind-ci.sh script

frontend/package.json, frontend/yarn.lock
Backport of #6568 to version v1.73
=> [v1.73] Update react-scripts dependencies (#6568)

.gitignore, frontend/src/components/CytoscapeGraph/graphs/GraphStyles.ts, frontend/src/config/Icons.ts, graph/telemetry/istio/appender/istio_details.go
Closes #6740 
Backport of #6747 but without the PF5 icon name changes.
=> [v1.73] Fix issues with gateway-badging in graph

frontend/src/components/IstioWizards/WizardActions.ts
Backport of https://github.com/kiali/kiali/pull/6705
Issue https://github.com/kiali/kiali/issues/6702
=> [v1.73] Fixed AuthPolicy apiVersion in overview wizard.

frontend/src/components/Metrics/CustomMetrics.tsx, frontend/src/services/Api.ts, frontend/src/types/MetricsOptions.ts
Backport of #6748 to version 1.73
=> [v1.73] Fixed getting cluster name from url on frontend (#6748)

hack/istio/functions.sh, hack/istio/install-testing-demos.sh
Trying to workaround missing side car in demo apps problem which is causing failures in interop pipeline.
=> OSSM-4624: trying to workaround missing side car in demo apps problem

frontend/src/components/About/AboutUIModal.tsx, frontend/src/components/Nav/Menu.tsx, frontend/src/components/Nav/Navigation.tsx, frontend/src/components/Nav/__tests__/Navigation.test.tsx, frontend/src/components/Nav/__tests__/RenderPage.test.tsx, frontend/src/components/TracingIntegration/TracesComponent.tsx
=> Tempo - Update Tracing url for Tempo

frontend/src/components/Nav/Menu.tsx
Remove extra space between left nav and top nav.
Fixes #6810.
=> Remove padding from navigation list

frontend/cypress/integration/common/app_details.ts, frontend/cypress/integration/common/graph_side_panel.ts, frontend/cypress/integration/featureFiles/graph_side_panel.feature, frontend/src/pages/Graph/SummaryPanelNodeTraces.tsx, frontend/src/pages/Graph/SummaryPanelTraceDetails.tsx
Issue https://github.com/kiali/kiali/issues/6815
Added missing clusterName param, added tests.
=> Added missing clusterName param in graph sidepanel 'Show Traces' button

business/tracing.go, tracing/tempo/http_client.go
Fixes: https://github.com/kiali/kiali/issues/6540
=> Update filtered spans for Tempo

frontend/src/components/Refresh/RefreshButton.tsx, frontend/src/pages/Graph/GraphToolbar/GraphToolbar.tsx
Backport of #6809 to version 1.73
=> [1.73] Add refresh delay to avoid multiple refresh in a very short period of time

tracing/tempo/http_client.go, tracing/tempo/traceQLBuilder.go
Fixes https://github.com/kiali/kiali/issues/6616
=> Tempo - Use select for queries

tracing/jaeger/http_client.go
=> Update min duration unit for Jaeger traces filter

hack/setup-kind-in-ci.sh
Align Istio versions with OSSM
#6858
=> [1.57] Align Istio versions with OSSM

hack/setup-kind-in-ci.sh
Align Istio versions with OSSM
#6858
=> [1.73] Align Istio versions with OSSM

hack/setup-kind-in-ci.sh
Align Istio versions with OSSM
#6858
=> Align Istio versions with OSSM

frontend/src/components/Nav/Navigation.tsx
Backport of #6812 to version 1.73
=> [1.73] Remove padding from navigation menu

tests/integration/tests/config_validations_test.go
Issue https://github.com/kiali/kiali/issues/6850
=> Potential flake fix

frontend/cypress/integration/common/overview.ts, frontend/cypress/integration/featureFiles/overview.feature
Some additional checks related to #6094.
=> Test coverage for MC badges on the Overview page

frontend/cypress/integration/featureFiles/wizard_istio_config.feature
=> Additional checks related to an inconsistency in an Istio config list

observability/tracing.go
Fixes https://github.com/kiali/kiali/issues/6916
=> Use the Tracer Name to emit traces

hack/istio/tempo/install-tempo-env.sh, tracing/client_test.go, tracing/tempo/grpc_client.go, tracing/tempo/grpc_client_test.go, tracing/tempo/http_client.go, tracing/tempo/http_client_test.go, tracing/tracingtest/response.json, tracing/tracingtest/responseTrace.json
Fixes https://github.com/kiali/kiali/issues/6919
=> Add Tempo tests

business/istio_config.go, config/config.go, kubernetes/istio.go
=> Include istio-waypoint api class as default

business/istio_status.go, business/istio_status_test.go
cherry pick of https://github.com/kiali/kiali/pull/6969
part of: https://github.com/kiali/kiali/issues/6966
=> [1.73] for health check, use prom healthy endpoint by default

handlers/config.go, prometheus/client.go, prometheus/prometheustest/client_test.go, prometheus/prometheustest/mock.go
fixes: https://github.com/kiali/kiali/issues/5734
=> get the prometheus runtime info in order to obtain the retention period

frontend/src/pages/WorkloadDetails/WorkloadPodLogs.tsx
Backport of #6986 in v1.73 branch
#6982
=> [1.73] Fix Workload Logs scrollbar issue

hack/istio/wait-for-namespace.sh
Test case `The idle status of a service is reported in the list of services` is failing with OSSM 2.5 because `wait-for-namespace.sh` script cannot find `istio` namespace
ref: https://issues.redhat.com/browse/OSSM-5599
=> [1.73][OSSM-5599] Add support for OSSM for wait-to-namespace script

frontend/cypress/integration/common/table.ts, frontend/cypress/integration/featureFiles/apps.feature
Finishes apps list page implementation for multi-cluster.
Relates to #6474
=> [Cypress] Add test for sorted cluster column - apps list page

.github/workflows/test-images-creator.yml, .github/workflows/test-images-release.yml, .github/workflows/test-images-update-latest.yml, Makefile, deploy/docker/Dockerfile-cypress, frontend/cypress/README.md, make/Makefile.container.mk, tests/integration/Dockerfile, tests/integration/README.md, tests/integration/run-tests.sh
Backport of https://github.com/kiali/kiali/pull/6938
=> [v1.73] - [OSSM-5306][OSSM-5307] Add building tests images into pipeline

.github/workflows/test-images-creator.yml, .github/workflows/test-images-release.yml, .github/workflows/test-images-update-latest.yml, Makefile, deploy/docker/Dockerfile-cypress, frontend/cypress/README.md, hack/istio/install-sleep-demo.sh, hack/istio/install-testing-demos.sh, make/Makefile.container.mk, tests/integration/Dockerfile, tests/integration/README.md, tests/integration/run-tests.sh
Backport of https://github.com/kiali/kiali/pull/6938 and https://github.com/kiali/kiali/pull/6959 (only which is related to master)
=> [master] - [OSSM-5306][OSSM-5307] Add building tests images into pipeline

business/istio_config.go, frontend/cypress/integration/common/wizard_istio_config.ts, frontend/cypress/integration/featureFiles/wizard_istio_config.feature, frontend/src/components/IstioConfigPreview/IstioConfigPreview.tsx, frontend/src/components/IstioWizards/WizardActions.ts, frontend/src/pages/IstioConfigNew/IstioConfigNewPage.tsx, frontend/src/pages/IstioConfigNew/K8sReferenceGrantForm.tsx
Issue https://github.com/kiali/kiali/issues/6918
=> K8sReferenceGrant: new Istio config creation wizard item

frontend/cypress/integration/common/services.ts, frontend/cypress/integration/common/table.ts, frontend/cypress/integration/featureFiles/istio_config.feature, frontend/cypress/integration/featureFiles/services.feature, frontend/cypress/integration/featureFiles/workloads.feature, frontend/src/components/Validations/Validation.tsx
Implements remaining multi-cluster list page cypress tests.
Fixes #6474
=> multi-cluster list page e2e test implementations

kubernetes/cache/kube_cache.go
Kiali pod is failing with nil error on OCP cluster in `.isK8sGatewayListerInit`.
Seems checking only cache lister `c.getCacheLister(namespace).k8sgatewayLister == nil` is causing `nil` in case of cluster or namespace scope of caches. 
Added a `nil` check similar to `GetK8sGateways` method structure.
=> Fix nil error in OCP

frontend/cypress/fixtures/details-destinationrule.json, frontend/cypress/fixtures/details-virtualservice.json, frontend/cypress/fixtures/ratings-destinationrule.json, frontend/cypress/fixtures/ratings-virtualservice.json, frontend/cypress/fixtures/reviews-destinationrule.json, frontend/cypress/fixtures/reviews-virtualservice.json, frontend/cypress/integration/common/apps.ts, frontend/cypress/integration/common/graph.ts, frontend/cypress/integration/common/graph_context_menu.ts, frontend/cypress/integration/common/graph_display.ts, frontend/cypress/integration/common/graph_side_panel.ts, frontend/cypress/integration/featureFiles/graph_context_menu.feature, frontend/cypress/integration/featureFiles/graph_display.feature, frontend/cypress/integration/featureFiles/graph_side_panel.feature, hack/istio/multicluster/split-bookinfo.sh
Adds remaining graph multi-cluster test implementations.
Fixes #6476
=> [cypress] Add graph side panel multi-cluster test implementation

hack/istio/install-testing-demos.sh
cherry pick of https://github.com/kiali/kiali/pull/7051
=> [v1.73] [hack] update for arm64

.github/workflows/build-backend.yml, .github/workflows/build-frontend.yml, .github/workflows/integration-tests-backend.yml, .github/workflows/integration-tests-frontend-multicluster-multi-primary.yml, .github/workflows/integration-tests-frontend-multicluster-primary-remote.yml, .github/workflows/integration-tests-frontend-tempo.yml, .github/workflows/integration-tests-frontend.yml, .github/workflows/nightly.yml, .github/workflows/release.yml
PRs generated by dependabot https://github.com/kiali/kiali/pull/6968 and https://github.com/kiali/kiali/pull/6967 are failing because they need each other to work. For this reason I merge these two PRs into one.
Besides, some yamls are formatted according to our format standards (https://www.github.com/kiali/kiali/pull/7011)
=> Upgrade download and upload github actions to v4

frontend/src/components/IstioCertsInfo/IstioCertsInfo.tsx
I have fixed the typo to make certificate information close button works correctly.
Fixes #7074
=> Fix certificate information close button issue

frontend/src/pages/GraphPF/GraphPF.tsx, frontend/src/pages/GraphPF/components/stylesComponentFactory.tsx
Fixes https://github.com/kiali/kiali/issues/7077
Add handling of graph [background] selection to ensure we properly unselect any currently selected element.
=> Add handling of graph [background] selection

frontend/cypress/integration/common/workloads_details.ts, frontend/cypress/integration/featureFiles/workloads_details.feature, frontend/src/components/TracingIntegration/TracesComponent.tsx
New tracing link test
CY is working. 3 new tests running for workloads details. 
See https://github.com/kiali/kiali/issues/7094
Fixes https://github.com/kiali/kiali/issues/7094
=> New tracing link test

frontend/src/pages/Overview/ControlPlaneBadge.tsx, frontend/src/pages/Overview/__tests__/ControlPlaneBadge.test.tsx
Backports #7054 to v1.79
Original issue: #7053
=> [v1.79] Backport of #7054

frontend/cypress/fixtures/perf/commonParams.json, frontend/cypress/perf/appsload.spec.ts, frontend/cypress/perf/common.ts, frontend/cypress/perf/graphload.spec.ts, frontend/cypress/perf/istioconfigsload.spec.ts, frontend/cypress/perf/servicesload.spec.ts, frontend/cypress/perf/workloadsload.spec.ts, make/Makefile.ui.mk
Issue https://github.com/kiali/kiali/issues/7088
Added tests for:
=> Added App, Workload, Service and Config details pages perf tests

frontend/src/config/Config.ts, frontend/src/pages/Overview/OverviewPage.tsx, frontend/src/services/Api.ts, frontend/src/types/Metrics.ts, handlers/metrics.go, handlers/utils.go, models/metrics.go, routing/routes.go, tests/integration/tests/kiali_metrics_test.go, tests/integration/utils/kiali/kiali_client.go
Issue https://github.com/kiali/kiali/issues/7058
Performance improvements in Overview page: Metrics requests per cluster with a list of namespaces.
=> Optimization overview Metrics per cluster's namespaces

hack/istio/skupper/install-skupper-demo.sh
Pass in `-kv` (aka `--kiali-version`) with the version you want to install (e.g. `v1.79.0`). If you pass in `dev`, a local build will be done and the dev build pushed into your cluster and installed. `dev` is the default.
=> [hack] skupper hack script: be able to install a specific kiali version

frontend/src/pages/Graph/GraphHelpFind.tsx, frontend/src/pages/Mesh/MeshHelpFind.tsx, frontend/src/pages/Mesh/toolbar/MeshFind.tsx
Fix issues in Mesh Find/Hide
- fix some type casting
- fix some redux decls
- improve debug logging
https://github.com/kiali/kiali/issues/7117
=> Fix issues in Mesh Find/Hide

frontend/src/pages/Graph/GraphToolbar/GraphSettings.tsx
Fixes https://github.com/kiali/kiali/issues/7149
Has been wrong since kiali/kiali-ui#2106 was merged.
=> Fix Security graph Display option help text

hack/use-openshift-prometheus.sh
We changed the way this script works because the secret token we were using is [no longer valid in OpenShift 4.15](https://issues.redhat.com/browse/OSSM-6008). This new way will work in 4.12+ and is also simpler.
=> [hack] use kiali token for access to openshift user monitoring prometheus

frontend/src/components/Envoy/AccessLogModal.tsx
fixes: https://github.com/kiali/kiali/issues/7071
=> fix envoyproxy.io doc links

graph/telemetry/istio/appender/dead_node.go, graph/telemetry/istio/appender/dead_node_test.go
Fixes https://github.com/kiali/kiali/issues/7179
Fix DeadNode appender when dealing with inaccessible workload.  Don't try to fetch it, just assume it's valid.
To Test:
A little bit tricky, covered now with a unit test.  You need to set up requests from an accessible to an inaccessible workload (like from an accessible namespace to an inaccessible namespace, or cluster).  Then stop the flow of traffic.  And then it would blow up because DeadNodeAppender would try to fetch the inaccessible workload, but only happens when the traffic stops, which lest DNA get to that point.
=> Fix DeadNode appender when dealing with inaccessible workload

hack/istio/install-sleep-demo.sh, hack/istio/install-testing-demos.sh
Adding support for IBM metal, original issue https://issues.redhat.com/browse/OSSM-6012
Should be backported into OSSM 2.5 & 2.4
=> support of s390x in sleep.yaml

hack/istio/install-sleep-demo.sh, hack/istio/install-testing-demos.sh
backport of https://github.com/kiali/kiali/pull/7182
=> [v1.73] Sleep app support for s390x in Kiali v1.73 [OSSM-6012]

hack/istio/tempo/install-tempo-env.sh
Update resource usage per component
- Run `istio/tempo/install-tempo-env.sh -c kubectl`
- Setup Kiali to use Tempo
- Navigate throw the Traces tabs, find no issues 
Testing already covering this feature
Fixes https://github.com/kiali/kiali/issues/7185
=> [Tempo] Update resource usage per component

hack/istio/wait-for-namespace.sh
script extended with support of kubectl for upstream environments 
closing https://github.com/kiali/kiali/issues/7004
=> added support of kubectl into hack/istio/wait-for-namespace.sh

go.mod, go.sum
https://issues.redhat.com/browse/OSSM-6037
This same change should be applied to 1.73 branch.
=> Update protobuf dependency

frontend/package.json, frontend/yarn.lock
https://issues.redhat.com/browse/OSSM-6114
=> Upgrade axios and follow-redirects libraries

business/workloads.go, frontend/src/pages/WorkloadDetails/WorkloadInfo.tsx, models/health.go, models/workload.go, models/workload_test.go, tests/integration/tests/workloads_test.go
Cherry-pick of https://github.com/kiali/kiali/pull/7128
Initial issue https://github.com/kiali/kiali/issues/7127
Downstream issue OSSM-5961
=> [v1.73] Skip Gateway workload pods proxy status check. (#7128)

tests/integration/assets/bookinfo-k8sgateways-addresses.yaml, tests/integration/assets/bookinfo-k8sgateways-listeners.yaml, tests/integration/tests/config_validations_test.go
Cherry-pick of flaky fixes https://github.com/kiali/kiali/pull/6875
=> [v1.73] CP of flaky fixes

frontend/cypress/integration/common/kiali_cookie.ts, frontend/cypress/support/commands.ts
Related to #7018 
Working on every platform mentioned in the issue except for ibmcloud, which I don't have access to.
=> Add cy.session to Cypress auth

frontend/cypress/integration/common/kiali_cookie.ts, frontend/cypress/support/commands.ts
=> Add cy.session to Cypress auth (backport)

hack/istio/wait-for-namespace.sh
Check the `accessible_namespaces` value in `wait-for-namespace.sh` script to determine if it has to patch the Kiali CR or not to include the test namespace.
PR is good if the CI tests pass
=> Check Kiali accessible namespaces in wait-for-namespace.sh script

hack/istio/wait-for-namespace.sh
Backport of #7230 to `v1.73` branch.
This PR is needed to perform OSSMC tests in v1.73 branch
=> [v1.73] Check Kiali accessible namespaces in wait-for-namespace.sh script

hack/istio/skupper/install-skupper-demo.sh
installing this demo is useful because it shows http metrics
east-west demo from here: https://skupper.io/start/
=> [hack] skupper script can now install the east-west demo

deploy/docker/Dockerfile-cypress, tests/integration/Dockerfile
Adding missing packages which are needed by our test jobs.
=> [1.73] Add missing packages for test dockerfiles

business/authentication/openid_auth_controller.go, business/authentication/openid_auth_controller_test.go, business/authentication/token_auth_controller.go, go.mod, go.sum, kubernetes/kubetest/mock.go
Backport of https://github.com/kiali/kiali/pull/7248 to 1.73 branch.
=> [v1.73] go jose bump

frontend/cypress/integration/common/kiali_login.ts, frontend/cypress/integration/featureFiles/kiali_login.feature, frontend/src/services/Api.ts
* Update encoding for login requests
Backport fot issue https://github.com/kiali/kiali/issues/7252
1. auth strategy should be set to token/OpenShift
2. Try to login with a valid token or username/pwd
Added e2e test.
Ref https://github.com/kiali/kiali/issues/7252
=> [v1.73] Update Content-Type for login request

frontend/src/services/Api.ts
Change login request content type for OpenShift login request. 
login with strategy: openshift
already covered
Fixes #7252
=> Update also content type for OpenShift login request

frontend/src/services/Api.ts
Update content type for OpenShift login request
Use strategy openshift for login 
Already included.
#7252
Backport of https://github.com/kiali/kiali/pull/7264
=> [v1.73] Update also content type for OpenShift login request

tests/integration/tests/namespaces_test.go
Adjust the inaccessible namespace error message to OCP runs
=> [flake] fixed namespaces test

hack/use-openshift-prometheus.sh
Updating a hack script to edit existing Telemetry resource when found instead of creating new one
=> Edit existing Telemetry resource when found instead of creating new one

hack/istio/install-sleep-demo.sh
=> [v1.73] fixed sleep yaml for s390x 

hack/istio/skupper/demo-emit-metrics-deployment/k8s.yaml
jay's original thoughts on potential kiali extension metrics for skupper.
=> [hack] demo with proposed extensions

hack/istio/install-testing-demos.sh
=> [v1.65] Sleep app yaml edit for s390x

hack/istio/install-testing-demos.sh
=> added sleep.yaml edit for s390x

hack/istio/multicluster/setup-tracing.sh
A backport for https://github.com/kiali/kiali/pull/7291
=> [v1.73][backport] Update helm chart values for otel (#7291)

deploy/docker/Dockerfile-cypress
Backport of https://github.com/kiali/kiali/pull/7302
=> Fix cypress cache folder in test image

deploy/docker/Dockerfile-cypress, frontend/cypress/README.md, frontend/cypress/integration/featureFiles/apps.feature, frontend/cypress/integration/featureFiles/overview.feature, frontend/cypress/integration/featureFiles/services.feature, frontend/cypress/integration/featureFiles/workloads.feature
Support for [this](https://github.com/kiali/kiali/pull/7299) in test container
=> Add test_group support to the test container

deploy/docker/Dockerfile-cypress, frontend/cypress/README.md, frontend/cypress/integration/featureFiles/apps.feature, frontend/cypress/integration/featureFiles/overview.feature, frontend/cypress/integration/featureFiles/services.feature, frontend/cypress/integration/featureFiles/workloads.feature, frontend/package.json
Backport of https://github.com/kiali/kiali/pull/7299 , https://github.com/kiali/kiali/pull/7309
=> [backport-master][OSSM-1471] Add possibility to run different test groups

tests/integration/utils/kiali/kiali_client.go
Removes the use of old `/api/authenticate` route in integration tests. Inside of `httputil` we're already sending the token with the proper auth header for the `openshift` strategy so getting the kiali cookie is not needed.
Integration tests pass on openshift.
Integration tests pass on openshift.
=> Remove old auth route from integration tests

hack/crc-openshift.sh
There was a problem that the CRC folks figured out over here: https://github.com/crc-org/crc/issues/4110 
@ferhoyos can confirm the problem I am seeing - he sees the same error.
This new PR performs the workaround that the CRC folks recommended.
=> [hack] bump crc to 2.34.1 / openshift 4.15

tests/integration/assets/remote-istiod/proxy-patch.yaml
Backport of https://github.com/kiali/kiali/pull/7340
=> Use quay image for nginx-unprivileged in remote istiod test (#7340)

hack/istio/install-istio-via-istioctl.sh
Starting in 1.22, zipkin tracing is no longer enabled by default. Therefore, in our CI setup we need to explicitly enable it.
=> Explicitly enable tracing in ci istio setup

hack/setup-kind-in-ci.sh
to test -- cd to some directory (like `/hack`) and run the script. It should still work.
=> [hack] clean up the SCRIPT_DIR declaration and usage

tracing/jaeger/grpc_client.go
=> remove tautological if-stmt

tests/integration/assets/remote-istiod/proxy-patch.yaml
Backport of https://github.com/kiali/kiali/pull/7340
=> Use quay image for nginx-unprivileged in remote istiod test

frontend/cypress/integration/common/kiali_help.ts, frontend/cypress/integration/featureFiles/kiali_help.feature
=> Negative check added for the Certificates information test

business/authentication/openid_auth_controller.go, business/authentication/token_auth_controller.go, go.mod, go.sum, kubernetes/kubetest/mock.go
=> [v1.65] Bump go jose

hack/ci-kind-molecule-tests.sh
similar to what we did in PR https://github.com/kiali/kiali/pull/7427 for other CI tests
If you really want to see it work, run:
```
./hack/ci-kind-molecule-tests.sh --client-exe $(which kubectl) --kind-exe $(which kind) --all-tests "config-values-test" --git-clone-protocol https --irc-room "" --upload-logs false --rebuild-cluster true -ci true --operator-installer helm --olm-enabled false
```
(if you run that, you should see it end successfully. After it finishes, clean up via `kind delete cluster --name=ci`
=> [molecule] make sure to use ipv4 in molecule tests

business/mesh_test.go, config/config.go
fixes: https://github.com/kiali/kiali/issues/7425
=> remove now-obsolete "kiali_feature_flags.clustering" setting

config/config.go, frontend/src/components/JaegerIntegration/TracesFetcher.ts, server/server.go
Backport https://github.com/kiali/kiali/pull/7389
=> [v1.73] Configurable server timeout

hack/istio/skupper/demo-emit-metrics-deployment/k8s.yaml
=> [hack] skupper metrics update

hack/istio/skupper/install-skupper-demo.sh
1. run the script: hack/istio/skupper/install-skupper-demo.sh -kv 1.86.0 install
2. look at the kiali graph and see the mysql serviceentry accepting traffic:  hack/istio/skupper/install-skupper-demo.sh kui
3. look at the skupper UI for the mysql pipe and see that there is traffic flowing: hack/istio/skupper/install-skupper-demo.sh -kv 1.86.0 suimysql
This shows that we have a skupper pipe on the other side of the service entry. So we have istio traffic going to the service entry which enters the skupper pipes that reaches the other cluster (where the mysql db is).
This works the same if on OpenShift. Start CRC and install thusly:
```
hack/istio/skupper/install-skupper-demo.sh -kv 1.86.0 -c $(which oc) -ct openshift -os1a https://api.crc.testing:6443 -os2a https://api.crc.testing:6443 …
```
=> [hack] skupper demo: send mysql traffic through a service entry

frontend/cypress/integration/common/istio_config.ts, frontend/cypress/integration/featureFiles/istio_config.feature
This is a copy of @matejnesuta 's PR: https://github.com/kiali/kiali/pull/7484, rebased on kiali master.  Wondering if this will resolve the unexpected cypress fails...
Matej is no longer around to rebase the PR, so if this works we can merge this and close his PR.
closes https://github.com/kiali/kiali/issues/7218
=> Cypress tests for Gateway API validations [rebased] 

frontend/src/components/DebugInformation/DebugInformation.tsx
Backport of PR #7505 to version 1.86
Issue: https://github.com/kiali/kiali/issues/7504
=> [v1.86] Fix issue with yaml debug-info generation (#7505)

frontend/src/services/Api.ts
Backport of PR #7498 to version 1.86
Issue: https://github.com/kiali/openshift-servicemesh-plugin/issues/330
=> [v1.86] Stringify the query data only if it is not already stringified (#7498)

design/KEPS/namespace-discovery/proposal.md
This is an initial write-up. It needs to be fleshed out more.
=> KEPS - namespace discovery

status/versions.go
Determine Tempo version using API url /api/status/buildinfo
```
// 20240709120142
// http://localhost:3200/api/status/buildinfo
{
"version": "2.5.0",
"revision": "46dad3411",
"branch": "HEAD",
"buildUser": "",
"buildDate": "",
"goVersion": "go1.21.3"
}
```
- Install istio and tempo: 
`istio/tempo/install-tempo-env.sh -c kubectl`
- Check the Tempo and the Mesh page, Tempo version should be visualized: 
Fixes #7531
=> Determine tempo version in Mesh page

graph/telemetry/istio/appender/ambient.go
Fixed #7549 
Fix issue where we mistakenly discarded http edges when tcp edges weren't also in the graph (and therefore no edges to/from waypoints).  The fix could have been centered around fixing the initialization of
`graphEdge := []*graph.Edge{}`
to preserve non-tcp edges.  But the code was a little confusing to me, so this reworks things a bit to [hopefully] make it more simple.
@josunect ,  this should solve the reported bug but there will still be follow-on work to do.  We can still think more about waypoint visualization.  With this, if you add in waypoints you can see them but it's uni-directional.  Also, you may notice that if you remove service nodes you mostly lose TCP visualization, also related to waypoint handling/ztunnel reporting.
To test, this is fairly easy to see with …
=> [ambient graph] Fix HTTP traffic loss when disabling TCP traffic

frontend/yarn.lock
Backport of PR https://github.com/kiali/kiali/pull/7579 to version 1.73
=> [v1.73] Update frontend dev dependencies

frontend/yarn.lock
Backport of PR https://github.com/kiali/kiali/pull/7579 to version 1.65
=> [v1.65] Update frontend dev dependencies

go.mod
upgrade go from 1.22.4 to 1.22.5
=> Move to go 1.22.5

frontend/yarn.lock, hack/setup-kind-in-ci.sh, hack/start-kind.sh
Backport of PR https://github.com/kiali/kiali/pull/7579 to version 1.57
=> [v1.57] Update frontend dev dependencies

.github/workflows/build-backend.yml, .github/workflows/integration-tests-backend.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, Makefile, go.mod, graph/telemetry/istio/appender/util_test.go, make/Makefile.build.mk, prometheus/prometheustest/client_test.go, prometheus/prometheustest/mock.go
=> [1.57] Move to go 1.22.5

Makefile, go.mod, graph/telemetry/istio/appender/util_test.go, make/Makefile.build.mk, prometheus/prometheustest/client_test.go, prometheus/prometheustest/mock.go
=> [V1.65]Upgrade to go 1.22.5

Makefile, go.mod, go.sum, graph/telemetry/istio/appender/util_test.go, make/Makefile.build.mk, prometheus/prometheustest/client_test.go, prometheus/prometheustest/mock.go
=> [1,73] Upgrade go to 1.22.5

frontend/package.json, frontend/yarn.lock, go.mod
=> [v1.86] Upgrade micromatch and golang

frontend/package.json, frontend/yarn.lock
Backport of PR https://github.com/kiali/kiali/pull/7579 to version 1.86
=> [v1.86] Update frontend dev dependencies

hack/istio/kustomization/bookinfo-ppc64le.yaml, hack/istio/kustomization/bookinfo-s390x.yaml
Update bookinfo images for IBM
Verified on IBM P an Z cluster 🆗
=> Update IBM images

frontend/src/services/Api.ts, frontend/src/types/Auth.ts
Backport of PR https://github.com/kiali/kiali/pull/7568 to version 1.73
=> [v1.73] Add CSRF token to OSSMC non-GET request header

frontend/src/services/Api.ts
Backport of PR https://github.com/kiali/kiali/pull/7498 to version 1.73
Issue: https://github.com/kiali/openshift-servicemesh-plugin/issues/330
=> [v1.73] Stringify the query data only if it is not already stringified (#7498)

.github/workflows/build-frontend.yml, .github/workflows/integration-tests-frontend-ambient.yml, .github/workflows/integration-tests-frontend-multicluster-multi-primary.yml, .github/workflows/integration-tests-frontend-multicluster-primary-remote.yml, .github/workflows/integration-tests-frontend-tempo.yml, .github/workflows/integration-tests-frontend.yml, README.adoc, frontend/package.json, frontend/yarn.lock
Upgrade Node to version 20
Check that Kiali works as expected
N/A
Closes #7503
=> Upgrade Node to version 20

.github/workflows/build-frontend.yml, .github/workflows/integration-tests-frontend-ambient.yml, .github/workflows/integration-tests-frontend-multicluster-multi-primary.yml, .github/workflows/integration-tests-frontend-multicluster-primary-remote.yml, .github/workflows/integration-tests-frontend-tempo.yml, .github/workflows/integration-tests-frontend.yml, README.adoc, deploy/docker/Dockerfile-cypress, frontend/package.json, frontend/yarn.lock
Backport of PR https://github.com/kiali/kiali/pull/7519 to version 1.86
=> [v1.86] Upgrade Node to version 20

.github/workflows/build-backend.yml, .github/workflows/build-frontend.yml, .github/workflows/integration-tests-backend.yml, .github/workflows/integration-tests-frontend-multicluster.yml, .github/workflows/integration-tests-frontend.yml, .github/workflows/molecules.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/tag-creator.yml, .github/workflows/test-images-update-latest.yml, .github/workflows/version-checker.yml, deploy/docker/Dockerfile-cypress, frontend/package.json, frontend/yarn.lock
Backport of PR https://github.com/kiali/kiali/pull/7519 to version 1.73
=> [v1.73] Upgrade Node to version 20

.github/workflows/build-backend.yml, .github/workflows/build-frontend.yml, .github/workflows/integration-tests-backend.yml, .github/workflows/integration-tests-frontend.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/tag-creator.yml, .github/workflows/test-images-update-latest.yml, .github/workflows/version-checker.yml, README.adoc, deploy/docker/Dockerfile-cypress, frontend/package.json, frontend/yarn.lock
Backport of PR https://github.com/kiali/kiali/pull/7519 to version 1.65
=> [v1.65] Upgrade Node to version 20

frontend/cypress/integration/common/authorization.ts, frontend/cypress/integration/common/overview.ts, frontend/cypress/integration/featureFiles/app_details_multicluster_graph.feature, frontend/cypress/integration/featureFiles/graph_display.feature, frontend/cypress/integration/featureFiles/graph_display_user.feature, frontend/cypress/integration/featureFiles/overview.feature, frontend/cypress/integration/featureFiles/workloads_details_multicluster_graph.feature, frontend/cypress/support/commands.ts, hack/istio/multicluster/deploy-kiali.sh, hack/run-integration-tests.sh
Adds implementation for no-access to remote cluster cypress tests.
Included.
Relates to #7021
=> Add multi-cluster no-access test

frontend/package.json, frontend/yarn.lock
Fix https://github.com/kiali/kiali/issues/7632
=> [v1.65] Remove openssl flag 

frontend/cypress/integration/common/hooks.ts, frontend/cypress/integration/common/overview.ts, frontend/cypress/integration/common/workloads.ts, frontend/cypress/integration/featureFiles/apps.feature, frontend/cypress/integration/featureFiles/overview.feature, frontend/cypress/integration/featureFiles/workloads.feature
See: https://github.com/kiali/kiali/pull/7625
=> [backport-v1.86][OSSM-6835][OSSM-6843] Fix for cypress flakiness on OCP 4.16

frontend/cypress/integration/common/hooks.ts, frontend/cypress/integration/common/overview.ts, frontend/cypress/integration/common/workloads.ts, frontend/cypress/integration/featureFiles/apps.feature, frontend/cypress/integration/featureFiles/overview.feature, frontend/cypress/integration/featureFiles/workloads.feature
See: https://github.com/kiali/kiali/pull/7625
=> [backport-master][OSSM-6835][OSSM-6843] Fix for cypress flakiness on OCP 4.16

frontend/package.json, frontend/yarn.lock
=> Update axios 1.7.4

frontend/package.json, frontend/yarn.lock
Update axios 1.7.4
N/A
Ref. https://github.com/kiali/kiali/pull/7641 backport v1.86
=> [v1.86] Update axios version

frontend/package.json, frontend/yarn.lock
Update axios 1.7.4
N/A
Ref. https://github.com/kiali/kiali/pull/7641 backport v1.73
=> [v1.73] Update axios version

frontend/package.json, frontend/yarn.lock
Update axios 1.7.4
N/A
Ref. https://github.com/kiali/kiali/pull/7641 backport v1.89
=> [v1.89] Update axios version

frontend/cypress/integration/common/sidecar_injection.ts
Support OSSM 2.x in ClusterWide mode
- run with ClusterWide ossm: https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/kiali/job/test-jobs/job/kiali-cypress-tests/2883/
- run with MultiTenant ossm: https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/kiali/job/test-jobs/job/kiali-cypress-tests/2901/
=> [v1.73 only] Adapt tests to SMCP in ClusterWide mode

frontend/cypress/integration/common/hooks.ts, frontend/cypress/integration/featureFiles/istio_config.feature
Backport of https://github.com/kiali/kiali/pull/7642
=> [OSSM-6967] Clean up created resources in istio namespace after test

frontend/cypress/integration/common/hooks.ts, frontend/cypress/integration/featureFiles/istio_config.feature
Backport of https://github.com/kiali/kiali/pull/7642
=> [v1.86][OSSM-6967] Clean up created resources in istio namespace after test

frontend/cypress/integration/common/hooks.ts, frontend/cypress/integration/common/overview.ts, frontend/cypress/integration/common/workloads.ts, frontend/cypress/integration/featureFiles/apps.feature, frontend/cypress/integration/featureFiles/istio_config.feature, frontend/cypress/integration/featureFiles/overview.feature, frontend/cypress/integration/featureFiles/workloads.feature
Backports of 
- https://github.com/kiali/kiali/pull/7642
- https://github.com/kiali/kiali/pull/7625
=> [v1.89][OSSM-6967] Clean up created resources in istio namespace after test + Fix for cypress flakiness on OCP 4.16

hack/istio/multicluster/env.sh
=> Check if a Helm chart tarbal is defined when using a dev image in a MC script

hack/istio/multicluster/setup-tracing.sh
Update the tracing script for Multicluster for sending traces from the remote (west) to the local (east) cluster with Tempo setup. 
- Run the following script to setup 2 kind clusters with Tempo for Tracing: 
`./hack/run-integration-tests.sh --test-suite frontend-primary-remote --setup-only true --tempo true`
- Verify there are traces in both local and remote cluster
- Verify the traces include the right cluster_id: 
For this, we can:
- port forward Grafana (This includes other external services): 
`./hack/run-kiali.sh -pg 13000:3000 -pp 19090:9090 -pt 3200:3200 -app 8080 -es false -iu http://127.0.0.1:15014 -tr tempo-cr-query-frontend -ts tempo-cr-query-frontend -tn tempo`
- Setup a new Tempo datasource: 
(Setup as the IP the tempo-cr-query-frontend in port 3200) 
- Verify the cluster id …
=> [Tempo] Modify setup tracing script for Tempo multicluster 

frontend/yarn.lock
Backport of PR #7675 to version 1.89
=> [v1.89] Update webpack to version 5.94.0

frontend/yarn.lock
Backport of PR https://github.com/kiali/kiali/pull/7675 to version 1.73
=> [v1.73] Update webpack to version 5.94

graph/telemetry/istio/appender/service_entry.go, graph/telemetry/istio/appender/service_entry_test.go
Backport of #7589 fix https://github.com/kiali/kiali/pull/7673
=> [v1.89] Fix multicluster service entry scenario

business/discovery_selectors.go, business/discovery_selectors_test.go
fixes: https://github.com/kiali/kiali/issues/7687
=> exclude system namespaces if no discovery selectors were defined

hack/istio/install-sleep-demo.sh
IBM clusters are not able to pull from the DockerHub, use quay instead
=> Use curl image from quay for P and Z

frontend/src/assets/img/graph/pf/edge-tcp.svg
Update tcp legend for patternfly graph
Check the legend in the patternfly graph and verify it is a square termination.
N/A
N/A
=> [Graph] Update tcp legend for patternfly graph

status/versions.go
fixes: https://github.com/kiali/kiali/issues/7651
=> use prometheus buildinfo endpoint to get its version

graph/telemetry/istio/appender/appender.go, graph/telemetry/istio/appender/istio_details_test.go
Straightforward v1.89 backport of #7689
=> [v1.89] Fix graph appender problem

frontend/src/components/Metrics/CustomMetrics.tsx
Backport of https://github.com/kiali/kiali/pull/7705
Issue https://github.com/kiali/kiali/issues/7638
=> Fixed hardcoded App param for CustomMetrics Links (#7705)

frontend/src/components/CytoscapeGraph/__tests__/GraphScore.test.ts, frontend/src/components/CytoscapeGraph/graphs/GraphStyles.ts, frontend/src/pages/GraphPF/GraphHighlighterPF.ts, frontend/src/pages/GraphPF/GraphPFElems.tsx, frontend/src/types/Graph.ts, graph/config/cytoscape/cytoscape.go, graph/meta.go, graph/telemetry/istio/appender/ambient.go
Bidirectional edges for waypoint
Backport from: https://github.com/kiali/kiali/pull/7593
Install Kiali and Ambient:
- ` minikube start`
New tests will be added in a separate PR.
Backport from https://github.com/kiali/kiali/pull/7593
=> [v1.89] [ambient] waypoint arrows and PF fix 

frontend/src/components/CytoscapeGraph/graphs/GraphStyles.ts, frontend/src/pages/GraphPF/GraphPFElems.tsx
Update comments
N/A (Just comments)
N/A
Ref. https://github.com/kiali/kiali/pull/7575
=> Update comments for waypoint icons

config/config.go, frontend/src/config/ServerConfig.ts, frontend/src/helpers/LabelFilterHelper.ts, frontend/src/helpers/__tests__/LabelFilterHelper.test.ts, frontend/src/types/ErrorRate/__testData__/ErrorRateConfig.ts, frontend/src/types/ServerConfig.ts, frontend/src/types/__testData__/HealthConfig.ts, graph/telemetry/istio/appender/mesh_check.go, models/workload.go, models/workload_test.go
Backport of https://github.com/kiali/kiali/pull/7721
Issue https://github.com/kiali/kiali/issues/7720
=> Added missing K8sGateway label name check for MissingSidecar icon

hack/istio/install-istio-via-istioctl.sh
Update install istio script to make values.cni.ambient.ipv6 optional
Run: 
`istio/install-istio-via-istioctl.sh -c kubectl -cp ambient -d6 false`
Disable IPV6 should be false and no argument: 
```
DISABLE_IPV6: false
...
MANIFEST_CONFIG_SETTINGS_TO_APPLY= --set hub=gcr.io/istio-release  --set values.meshConfig.enableAutoMtls=true --set values.pilot.env.ENABLE_NATIVE_SIDECARS=false   --set values.gateways.istio-egressgateway.enabled=true --set values.gateways.istio-ingressgateway.enabled=true --set values.meshConfig.enableTracing=true --set values.meshConfig.defaultConfig.tracing.sampling=100.0 --set values.meshConfig.defaultConfig.tracing.zipkin.address=zipkin.istio-system:9411 --set values.meshConfig.accessLogFile=/dev/stdout
```
If no argument -d6 ipv6 should be passed (Just with …
=> Update install istio script to make arg optional

make/Makefile.olm.mk
bumps up some stuff in the olm makefile so we can test our CSVs
=> [make] bump some olm stuff

frontend/package.json, frontend/yarn.lock
Backport of PR https://github.com/kiali/kiali/pull/7750 to version 1.73
=> [v1.73] Update serialize-javascript dependency

frontend/package.json, frontend/yarn.lock
Backport of PR https://github.com/kiali/kiali/pull/7750 to version 1.65
=> [v1.65] Update serialize-javascript dependency

frontend/package.json, frontend/yarn.lock
Backport of PR https://github.com/kiali/kiali/pull/7750 to version 1.89
=> [v1.89] Update serialize-javascript dependency

grafana/grafana.go, status/versions.go
fixes: https://github.com/kiali/kiali/issues/7758
=> obtain the grafana and tracing version from the internal in-cluster url

Makefile
Next operator version will be v1.89.7 so this needs to be aligned.
=> Sync version to the operator version for release

frontend/src/pages/Graph/SummaryPanelEdge.tsx
Fixes https://github.com/kiali/kiali/issues/7774
- The problem here was the assumption that a 'from' waypoint edge was always the 'fromEdge' of a bidirectional edge. But there can be uni-directional edges both to and from waypoints.
- Part of the confusion may have been some overloading of 'waypoint' variable names.  This PR updates some var/type names to hopefully make things more clear. It also adds some stricter typing.
- Note that 'to' waypoint edges are 'source' reported, and 'from' waypoint edges are 'destination' reported.
=> Fix sparkline issue for waypoint-edge side panel

frontend/cypress-perf.config.ts, frontend/cypress/fixtures/perf/baselines.json, frontend/cypress/fixtures/perf/commonParams.json, frontend/cypress/fixtures/perf/graphParams.json, frontend/cypress/perf/common.ts, frontend/cypress/perf/graphload.spec.ts
Adjusted existing Graph performance tests to PF Graph.
Taking 3 measurements:
1. All Namespaces.
2. All Namespaces with Idle nodes.
3. Selected (few) Namespaces.
Perf tests added
https://github.com/kiali/kiali/issues/7709
=> PF Graph performance tests.

business/metrics.go
Fixes https://github.com/kiali/kiali/issues/7829
To Test, re-run the repro steps in the issue.
=> [mesh page] Protect against the possibility of no time-series for the proxy sync time.

.github/workflows/release.yml, Makefile, hack/hooks/pre-commit.sh
This PR adds the ability to do major releases.
Schedule runs are disabled for now.
This PR also sets the 2.0 version for the next Kiali major release on next Monday.
=> Add the ability to do major releases

frontend/yarn.lock
Upgrade http-proxy-middleware to 2.0.7
https://issues.redhat.com/browse/OSSM-8281
=> Upgrade http-proxy-middleware to 2.0.7

frontend/cypress/integration/common/graph_display-pf.ts, frontend/cypress/integration/common/waypoint.ts, frontend/cypress/integration/featureFiles/waypoint.feature
Wait for the traffic to be created.
`yarn cypress open -e TAGS=@waypoint`
cypress tests update
Ref. https://github.com/kiali/kiali/pull/7799
=> Uncomment waypoint tests

frontend/src/types/Health.ts
Fixes https://github.com/kiali/kiali/issues/7317
=> Change icon color to something more appropriate

mesh/generator/generator.go
In mesh discovery of external_services, if the internal_url is IP-based and not in one of the expected "namespace.service" formats then don't attempt auto-discovery of the service.
Fixes https://github.com/kiali/kiali/issues/7844
=> protect against IP internal_url in mesh service discovery

README.adoc
This was to make changes (take out the word 'you'), spelling errors, and make the READ.me more formal
No steps to test, however; if things are no longer valid or used, please let me know so I can make respected changes
No testing needed
No github issue
=> READ.me changes

deploy/docker/Dockerfile-distroless, deploy/docker/Dockerfile-multi-arch, deploy/docker/Dockerfile-multi-arch-distroless
fixes: https://github.com/kiali/kiali/issues/7896
=> move to UBI9 as server base image

frontend/package.json, frontend/yarn.lock
Backport of PR https://github.com/kiali/kiali/pull/7910 to version 1.73
https://issues.redhat.com/browse/OSSM-8365
=> [v1.73] Update cross-spawn dependency

frontend/package.json, frontend/yarn.lock
Backport of PR https://github.com/kiali/kiali/pull/7910 to version 1.65
https://issues.redhat.com/browse/OSSM-8366
=> [v1.65] Update cross-spawn dependency

frontend/cypress/integration/common/workload_logs.ts, frontend/cypress/integration/featureFiles/traffic_policies_multicluster.feature, frontend/cypress/integration/featureFiles/wizard_istio_config_multicluster.feature, frontend/cypress/integration/featureFiles/wizard_request_routing.feature, frontend/cypress/integration/featureFiles/workload_logs.feature
Backport https://github.com/kiali/kiali/pull/7908
=> [1.89] Fix CI failures with Istio 1.24

hack/istio/multicluster/kiali-prepare-remote-cluster.sh
part of https://github.com/kiali/kiali/issues/7926
=> support insecure comm in remote cluster secret

business/istio_validations_test.go
Fixing the flaky tests introduced after Validation cache rebase PR.
=> Flaky validations test

frontend/package.json, frontend/yarn.lock
Update `postcss` dependency
N/A
https://issues.redhat.com/browse/OSSM-8384
=> [v1.73] Update postcss dependency

hack/istio/install-bookinfo-demo.sh
Support usage of ingress gateway from different namespace as istio control plane in the traffic generator
=> [bookinfo] Support usage of ingress gateway from different namespace as istio control plane in the traffic generator

hack/use-openshift-prometheus.sh
fixes: https://github.com/kiali/kiali/issues/7954
=> tell user-monitoring prometheus to store the app/version labels Kiali needs

business/istio_validations.go
Missing item for https://github.com/kiali/kiali/issues/7457
=> Fixed missing GVK String.

business/istio_validations.go
Backport of https://github.com/kiali/kiali/pull/7962 just in case to have in branch at least.
=> [v2.1] Fixed missing GVK String.

hack/istio/install-bookinfo-demo.sh, hack/istio/install-testing-demos.sh
- Support bookinfo ingress gw on OCP in install-testing-demos script (moved gateway_yaml before if-else and used it for openshift case too )
- Add route for bookinfo ingress gateway in bookinfo ns
- Use that route in traffic generator when exists (1st, it tries `istio-ingressgateway` route (in ingressgateway/controlplane ns), 2nd it tries bookinfo-gateway-istio (in bookinfo app ns), 3rd it uses a direct route to productpage
=> Support bookinfo ingress gw on OCP in install-testing-demos script

config/config.go, go.mod, graph/telemetry/istio/appender/health_test.go, handlers/authentication.go, handlers/tracing.go, make/Makefile.build.mk, tests/integration/utils/exec_client.go, tracing/tempo/http_client.go
Fix https://github.com/kiali/kiali/issues/7977
Upgrade golang to 1.23.2
=> Bump golang version to 1.23.2

frontend/reporter-config.json
added tag to Junit reporter for better distinguish in Jenkins results
=> added tag for kiali tests

frontend/package.json, frontend/yarn.lock
V1.73 backport Resolves OSSM-8528 / https://github.com/advisories/GHSA-rhx6-c78j-4q9w
=> [V1.73] update path-to-regexp

frontend/package.json, frontend/yarn.lock
V1.73 backport Resolves OSSM-8538 / https://github.com/advisories/GHSA-mwcw-c2x4-8c55
=> [V1.73] update nanoid

frontend/src/pages/GraphPF/TrafficAnimation/TrafficRendererPF.tsx
fix traffic animation issue where a very small error rate resulted in a uniform stream of error trafficpoints.
Related to #7934 
@josunect This should resolve the issue we saw with the very small error rate resulting in all error points.  Note that with the fix you may not see any error trafficPoints, the error rate of 0.3 is very small and may get rounded down to 0 in the new approach.
=> [graph] fix traffic animation with very small error rates

hack/istio/install-bookinfo-demo.sh
Right now, traffic generator is searching for ingress in order:
1. istio-ingressgateway in istio-system ns (old way of set up)
2. bookinfo-gateway-istio in bookinfo ns (new way of set up, used in integration test only)
3. direct route to the producpage pod
However, until OSSM-8542 is done, there can be a mix of setups in Kiali upstream Jenkins job ( istio is set up by istioctl with istio-ingressgateway in istio system but bookinfo app for integration test is set up with bookinfo gateway in the namespace ). 
In that "mixed" case when both ingresses exist, the bookinfo gateway **should take precedence** (since VirtualService/HTTPRoute is set up for that usage). Otherwise (when only one gateway exist, no change)
This PR changed the searching order.
Tests run against this mixed environment …
=> Change order of searching ingress gateway for traffic generator

tests/integration/utils/kiali/kiali_client.go
Backport of https://github.com/kiali/kiali/pull/7698 (to stabilize tests with spans/traces) + fix failing TestNoIstiod.istioStatus test on OSSM3 (when `istio_api_enabled=false`, `/api/status` query takes ~11s, default timeout in integration tests is 10s)
Downstream test job with v2.1 :green_circle: : https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/kiali/job/test-jobs/job/kiali-integration-tests/3157/
=> Add a bigger timeout for tracing/spans and istioApi queries in integration tests

business/checkers/virtualservices/route_checker.go
fix KIA1104 report on tcp/tls route
1. install istio and kiali
1. apply tcp-echo demo
1. apply samples/tcp-echo/tcp-echo-all-v1.yaml, then check
https://github.com/kiali/kiali/issues/8000
=> fix KIA1104 report on TCP/TLS route

hack/crc-openshift.sh
The name of the ssh identify file changed in recent versions of CRC - this updates the name (this allows us to ssh into the VM - this feature is used when obtaining status of the cluster, for example).
This also adds the option to enable user network mode in case you need to tell the VM to use the host's own networking.
And of course this also updates to the latest version of CRC.
=> [hack] update CRC and provide a user network mode option

frontend/yarn.lock
Backport of PR #8018 to branch v2.3 since this is the branch currently used in Konflux build system
=> [v2.3] Avoid duplicated tarballs (#8018)

hack/ci-kind-molecule-tests.sh
This works - see the test action run in my fork - it is green: https://github.com/jmazzitelli/kiali/actions/runs/12677210951
=> delegate creating the KinD cluster to the start-kind hack script

frontend/cypress/integration/common/waypoint.ts, frontend/cypress/integration/featureFiles/waypoint.feature, frontend/src/components/DetailDescription/DetailDescription.tsx, frontend/src/pages/WorkloadDetails/PodStatus.tsx, frontend/src/pages/WorkloadDetails/WorkloadPods.tsx
Add cypress tests
```
cd frontend
yarn cypress:run:ambient
```
**e2e** tests created for this PR https://github.com/kiali/kiali/pull/7970
Fixes #8031
=> [cypress] Waypoint tests

hack/istio/install-bookinfo-demo.sh, hack/istio/kustomization/bookinfo-ppc64le.yaml, hack/istio/kustomization/bookinfo-s390x.yaml
Backport of https://github.com/kiali/kiali/pull/8059
=> [backport-2.4][hackscripts] Update IBM P/Z images for bookinfo app

hack/istio/install-bookinfo-demo.sh, hack/istio/kustomization/bookinfo-ppc64le.yaml, hack/istio/kustomization/bookinfo-s390x.yaml
=> [hackscripts] Update IBM P/Z images for bookinfo app

hack/istio/install-bookinfo-demo.sh, hack/istio/kustomization/bookinfo-ppc64le.yaml, hack/istio/kustomization/bookinfo-s390x.yaml
Backport of https://github.com/kiali/kiali/pull/8059
=> [backport-2.1][hackscripts] Update IBM P/Z images for bookinfo app

hack/run-integration-tests.sh
fixes: https://github.com/kiali/kiali/issues/8064
=> [hack] integration test should not fail on missing applications list

frontend/cypress/integration/common/workload_logs.ts
Update logs timeout for cypress test flake in workload logs
We can run the cy suite frontend tests. Also, cy should pass. 
e2e tests
=> [cy] Update logs timeout

frontend/src/components/Nav/Masthead/ThemeSwitch.tsx, frontend/src/types/Common.ts, frontend/src/utils/ThemeUtils.ts
Backport of https://github.com/kiali/kiali/pull/8072
=> [v2.4] Fix theme storage

frontend/src/routes.tsx, frontend/src/routes/WildcardRoute.tsx, handlers/authentication/openshift_auth_controller.go
=> Catch OpenShift login error and display an error

frontend/cypress/integration/featureFiles/workload_logs.feature, hack/istio/cypress/get-node-architecture.sh, hack/istio/install-bookinfo-demo.sh, hack/istio/install-istio-via-sail.sh, hack/istio/install-testing-demos.sh, hack/istio/istio-gateway.yaml, hack/run-integration-tests.sh
Use sail in frontend test setup.
Automated tests pass.
Included updates to automation.
Part of #7830
=> Use sail in frontend tests

hack/istio/install-bookinfo-demo.sh
Change name of istio-ingressgateway port after this change https://github.com/kiali/kiali/commit/2a869dfb36af712d1c2de1ca623a81173a4eb90b#diff-83d320000696644969bd58e84e1c6f0b5a81868ba1d5141ea8780354e39420eeR61
=> Update port name for bookinfo istio ingress gateway

hack/istio/install-bookinfo-demo.sh
Backport of https://github.com/kiali/kiali/pull/8094
=> [backport v2.4] Update port name for bookinfo istio ingress gateway

make/Makefile.cluster.mk
We already had a "cluster-add-users" target, but it only added users for OpenShift. This adds the ability to add a "user" (really, a SA) that you can use to test auth stuff with (e.g. I needed this to help reproduce https://github.com/kiali/kiali/issues/8084). Use the "token" auth strategy when using this stuff.
Run this:
`make CLUSTER_TYPE=minikube NAMESPACE=default cluster-add-users`
and this is the output you will see:
```
Create ServiceAccount 'testsa' and give it permissions for namespace [default]
serviceaccount/testsa created
clusterrole.rbac.authorization.k8s.io/testsa-namespace-auth unchanged
rolebinding.rbac.authorization.k8s.io/testsa-namespace-auth created
If you want to give the SA access to another namespace (e.g. 'foo'), create this object:
cat <<EOM | …
```
=> [make] be able to create SAs in make - useful for testing

frontend/src/pages/Graph/SummaryPanelGraph.tsx, frontend/src/utils/Common.ts, frontend/src/utils/__tests__/Common.test.ts
CP of https://github.com/kiali/kiali/pull/8082
=> [v2.4] Added filter namespaces per cluster in Graph Validations (#8082)

frontend/public/locales/zh/translation.json, frontend/src/pages/Mesh/toolbar/MeshSettings.tsx
=> Fix I18n issue on Mesh Page Display menu help

frontend/src/pages/Graph/GraphToolbar/GraphTraffic.tsx
similar to https://github.com/kiali/kiali.io/pull/859
=> Adjust ztunnel casing

tests/integration/tests/traces_spans_test.go, tests/integration/utils/kiali/kiali_client.go
Cherry pick from https://github.com/kiali/kiali/pull/8116
=> [v2.4 backport] Update integration tests for Tempo (#8116)

frontend/cypress/integration/common/istio_config.ts
This PR fixes the color comparison in crd validation cypress tests. It seems that the icon element inherits all the color values, so it is not enough to verify that the color just exists. Now we have to get the exact CSS color value of the icon and compare it with the health status color.
Verify that the Cypress tests pass in CI. Additionally, test locally that changing one of the health status in a @crd-validation test of `istio_config.feature` (e.g. warning to danger) make the cypress test fails.
Fixes #8126
=> Fix color comparison in crd validation cypress tests

business/layer.go, business/workloads.go
part of : https://github.com/kiali/kiali/issues/8084
(a manual cherry pick from commit 551a2c8883190124f0969a8a9ef365ebea742324)
=> [v1.73] some resources are not in the cache - use SA client to get them

business/layer.go, business/workloads.go
part of: https://github.com/kiali/kiali/issues/8084
(cherry picked from commit 551a2c8883190124f0969a8a9ef365ebea742324)
=> [v2.4] some resources are not in the cache - use SA client to get them

frontend/src/types/IstioConfigList.ts, kubernetes/types.go
Backport of PR #8134 to `v2.4` branch
Issue: #8133
=> [v2.4] Set apiVersion of ReferenceGrant to v1beta1 (#8134)

hack/istio/ambient/egress-gateway.yaml, hack/istio/ambient/install-sidecars-ambient.sh, hack/istio/ambient/install-waypoints.sh
- New ambient hack script for sidecar-ambient traffic tests
- Fix example with waypoints in different namespace
- `hack/istio/ambient/install-sidecars-ambient.sh` 
Fixes https://github.com/kiali/kiali/issues/5980
=> Ambient - Sidecar hack script

.github/workflows/build-backend.yml, .github/workflows/build-frontend.yml, .github/workflows/integration-tests-backend-multicluster-external-controlplane.yml, .github/workflows/integration-tests-backend.yml, .github/workflows/integration-tests-frontend-ambient.yml, .github/workflows/integration-tests-frontend-multicluster-multi-primary.yml, .github/workflows/integration-tests-frontend-multicluster-primary-remote.yml, .github/workflows/integration-tests-frontend-tempo.yml, .github/workflows/integration-tests-frontend.yml, .github/workflows/molecules.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/tag-creator.yml, .github/workflows/test-images-creator.yml, .github/workflows/test-images-release.yml, .github/workflows/test-images-update-latest.yml, .github/workflows/version-checker.yml, RELEASING.md, tests/integration/utils/exec_client.go
Update ubuntu version on GH actions
Verify that the CI tests pass, as they will run on the latest Ubuntu version. This will be enough since there are no specific commands in any GitHub Action requiring the previous Ubuntu version.
Closes #8175
=> Update ubuntu version on GH actions

go.mod, go.sum
=> K8s GW API to 1.2.1

CACHE.md
Documenting what is Cached and what is not cached in Kiali.
https://github.com/kiali/kiali/issues/8080
=> [doc] What is cached in Kiali

handlers/authentication/openid_auth_controller.go, handlers/authentication/token_auth_controller.go, handlers/mesh.go
fixes: https://github.com/kiali/kiali/issues/8241
=> make sure user clients and SA clients are passed in correctly

handlers/authentication/openid_auth_controller.go, handlers/authentication/token_auth_controller.go, handlers/mesh.go
fixes: https://github.com/kiali/kiali/issues/8241
cherry pick of https://github.com/kiali/kiali/pull/8242
=> [v2.7] make sure user clients and SA clients are passed in correctly

go.mod
Upgrade golang to 1.23.6
https://issues.redhat.com/browse/OSSM-8745
https://issues.redhat.com/browse/OSSM-8837
=> Upgrade to golang 1.23.6

frontend/cypress/integration/common/graph_display-pf.ts, frontend/cypress/integration/common/waypoint.ts, frontend/cypress/integration/featureFiles/waypoint.feature, hack/istio/ambient/install-waypoints.sh, hack/istio/install-testing-demos.sh
Add test coverage for: 
- Traffic sidecar-ambient 
- Waypoint proxy scenarios
`yarn run:ambient `
e2e tests
Ref. https://github.com/kiali/kiali/issues/8184 (Covers 3,4,5 points)
=> Ambient - Increase test coverage

hack/istio/install-istio-via-sail.sh, hack/istio/sail/func-sm.sh
=> [v2.4] move sail operator to v1 (#8231)

.github/workflows/config/.golangci.yml, Makefile, go.mod, make/Makefile.build.mk, status/versions.go
Upgrade golang to 1.23.6
https://issues.redhat.com/browse/OSSM-8745
https://issues.redhat.com/browse/OSSM-8837
=> [v1.73] Upgrade golang to 1.23.6

frontend/cypress/integration/common/kiali_login.ts, frontend/cypress/integration/featureFiles/kiali_login.feature
fixes https://github.com/kiali/kiali/pull/8209 for master
=> removing negative login testcase

handlers/README.md, handlers/apps.go, handlers/apps_test.go, handlers/testing.go, kubernetes/kubetest/mock.go, routing/routes.go
Adds a `README` for adding new handlers to Kiali and refactors app handlers.
I'm breaking this up into pieces and starting with the app handlers. Otherwise the diff will be huge and unreviewable.
N/A
N/A
https://github.com/kiali/kiali/issues/6923
=> Refactor apps handlers

business/tracing.go, tracing/jaeger/grpc_client.go
Include more tracing trace messages to understand the query for gRPC also, and the span matching criteria.
- Install Istio and Kiali with tracing enabled
- Set Kiali to TRACE
- Go to any traces tab
- See detailed logs
ref. https://github.com/kiali/kiali/issues/8266
=> Include more tracing trace messages

business/checkers/gateways/multi_match_checker.go
closes #8211 
Hopefully this refactor is more efficient.
=> [perf] refactor gateway multi-match-checker

istio/discovery.go, istio/discovery_internal_test.go
Adds a separate timeout for getting the istio version during mesh discovery so the request doesn't cause the whole discovery process to hang.
N/A
Added unit test.
Relate to: https://github.com/kiali/kiali/discussions/8283
=> Add separate timeout for getting istio version during discovery

frontend/src/components/Envoy/EnvoyDetails.tsx, frontend/src/components/Envoy/tables/BaseTable.tsx, frontend/src/components/Nav/Page/RenderComponentScroll.tsx, frontend/src/components/Nav/Page/RenderContent.tsx, frontend/src/components/Table/SimpleTable.tsx, frontend/src/components/VirtualList/VirtualList.tsx
Sticky headers in Virtual List
https://github.com/user-attachments/assets/a078c2ad-a1ae-44e7-a7cd-77fe34939e42
https://github.com/kiali/kiali/issues/8197
=> Sticky headers in VirtualList

.github/workflows/build-backend.yml, .github/workflows/build-frontend.yml, .github/workflows/integration-tests-backend.yml, .github/workflows/integration-tests-frontend-multicluster.yml, .github/workflows/integration-tests-frontend.yml, .github/workflows/molecules.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/tag-creator.yml, .github/workflows/test-images-release.yml, RELEASING.md, tests/integration/utils/exec_client.go
Backport of https://github.com/kiali/kiali/issues/8175
=> [v1.73] Update ubuntu version on GH actions

frontend/cypress/integration/common/apps.ts, frontend/cypress/integration/featureFiles/app_details.feature, frontend/cypress/integration/featureFiles/app_details_multicluster.feature, frontend/cypress/integration/featureFiles/service_details.feature, frontend/cypress/integration/featureFiles/waypoint.feature, frontend/cypress/integration/featureFiles/workloads_details.feature, frontend/src/components/Metrics/TraceLimit.tsx, frontend/src/components/TracingIntegration/TracesDisplayOptions.tsx
Backport of #8247 to v2.4 branch
=> [v2.4] Bump the limit of traces we see in e2e tests (#8247)

.github/workflows/build-backend.yml, .github/workflows/build-frontend.yml, .github/workflows/integration-tests-backend-multicluster-external-controlplane.yml, .github/workflows/integration-tests-backend.yml, .github/workflows/integration-tests-frontend-ambient.yml, .github/workflows/integration-tests-frontend-multicluster-multi-primary.yml, .github/workflows/integration-tests-frontend-multicluster-primary-remote.yml, .github/workflows/integration-tests-frontend-tempo.yml, .github/workflows/integration-tests-frontend.yml, .github/workflows/molecules.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/tag-creator.yml, .github/workflows/test-images-release.yml, RELEASING.md, tests/integration/utils/exec_client.go
Backport of PR https://github.com/kiali/kiali/pull/8190 in the `v2.4` branch
https://github.com/kiali/kiali/issues/8175
=> [v2.4] Update ubuntu version on GH actions

.github/workflows/molecules.yml, .github/workflows/release.yml
This PR adds an extra step to run the molecule tests before doing the actual release.
=> Run molecule tests before releasing

hack/istio/multicluster/setup-tracing.sh, hack/run-integration-tests.sh
=> [v2.4] Backport tracing flake fix

business/apps.go, business/istio_status.go, business/istio_status_test.go, business/namespaces.go, business/tracing.go, business/tracing_test.go, handlers/tracing.go, log/log_names.go, tracing/client.go, tracing/jaeger/grpc_client.go, tracing/jaeger/http_client.go, tracing/jaeger/logging.go, tracing/tempo/grpc_client.go, tracing/tempo/http_client.go, tracing/tempo/http_client_test.go, tracing/tempo/logging.go, tracing/tracingtest/mock.go
part of https://github.com/kiali/kiali/issues/8348
This is adding structured logging and metrics to the tracing code for better diagnostics during debugging.
This requires adding context.Context to many functions.
=> get logging in tracing code

config/dashboards/dashboards.go, prometheus/internalmetrics/internal_metrics.go, tracing/client.go
part of https://github.com/kiali/kiali/issues/8348
=> add tracing metrics

frontend/cypress/integration/common/graph_display.ts, frontend/src/pages/Graph/TrafficAnimation/TrafficRenderer.tsx
Import React library in TrafficRenderer.tsx and fix lint issues.
Verify that cypress test pass. This PR fixes OSSMC issue. Kiali should not be affected by this PR.
Fixes https://github.com/kiali/kiali/issues/8417
=> Fix traffic animation rendering in OSSMC

graph/api/api.go
fixes: https://github.com/kiali/kiali/issues/8430
=> fix graph node size metric

frontend/cypress/integration/common/graph_display-pf.ts, frontend/src/pages/GraphPF/TrafficAnimation/TrafficRendererPF.tsx
backport of https://github.com/kiali/kiali/pull/8419 as part of #8417
=> [v2.4] Fix traffic animation rendering in OSSMC (#8419)

make/Makefile.molecule.mk
If it appears a molecule test failed because the Galaxy server was down, this will retry the test. It will retry every 60 seconds for 60 retry attempts before failing. In other words, we are giving the Galaxy Server an hour to right itself. That is usually a sufficient time to wait.
fixes: https://github.com/kiali/kiali/issues/8402
=> [molecule][CI] retry a molecule test that failed when it appears the failure was due to Galaxy server being down

.github/workflows/release.yml
Rolling back to the previous logic of pushing directly to the version branch for fixing patch releases.
=> Fix patch releases

business/istio_config.go, handlers/istio_config.go, handlers/namespaces.go, handlers/proxy_logging.go, handlers/services.go, handlers/workloads.go, log/log_names.go, routing/router.go
part of https://github.com/kiali/kiali/issues/8348 and https://github.com/kiali/kiali/issues/8347
=> Istio Config and some Validations logging

kiali.go
Controller-runtime starts informers lazily so fetching workloads and istio config at startup as a way of starting the informers before the API server starts serving requests.
1. Deploy Kiali
```
make build build-ui
hack/run-integration-tests.sh --test-suite backend --setup-only true
```
2. Open the network tab of dev console on browser
3. Navigate to graph page and ensure the first request for each endpoint e.g. `/config` and `/status` is not slow.
N/A
Relates to #8445
=> Get workloads and istio config as part of startup

business/controlplane_monitor.go, controller/validations.go, istio/discovery.go, istio/version.go
fixes: https://github.com/kiali/kiali/issues/8347
=> help make debug logs less noisy

config/config.go, frontend/src/components/Metrics/TraceLimit.tsx, frontend/src/components/TracingIntegration/TracesDisplayOptions.tsx, frontend/src/config/ServerConfig.ts, frontend/src/types/ErrorRate/__testData__/ErrorRateConfig.ts, frontend/src/types/ServerConfig.ts, frontend/src/types/__testData__/HealthConfig.ts
Backport from https://github.com/kiali/kiali/pull/8521
=> [v2.11] set up trace limit in config 

frontend/cypress/integration/common/mesh.ts
Added retries for checking values in control panel since it is flaky sometimes (e.g. memory chart is not displayed)
=> Add retries to for checking control panel

frontend/cypress/integration/common/hooks.ts, frontend/cypress/integration/common/mesh.ts
Backports fixes for https://github.com/kiali/kiali/issues/8518 (#8519 #8534) + #8563
=> [v2.11] Backport fixes for Shared Mesh page flaky test 

frontend/package.json, frontend/yarn.lock
Backport of https://github.com/kiali/kiali/pull/8589 to branch v2.4
=> [v2.4] Upgrade axios and form-data dependencies (#8589)

frontend/package.json, frontend/yarn.lock
Backport of #8589 to branch v2.11
=> [v2.11] Upgrade axios and form-data dependencies (#8589)

cache/cache.go, cache/cache_test.go
Cherry-pick of https://github.com/kiali/kiali/pull/8586
=> [v2.11] Skip cluster wide query when no access. (#8586)

frontend/reporter-config.json
Fixes https://github.com/kiali/kiali/issues/8644
=> [v2.4] Fix illegal path character in jenkins

.github/workflows/integration-tests-backend-multicluster-external-controlplane.yml, .github/workflows/integration-tests-backend.yml, .github/workflows/integration-tests-frontend-ambient.yml, .github/workflows/integration-tests-frontend-multicluster-multi-primary.yml, .github/workflows/integration-tests-frontend-multicluster-primary-remote.yml, .github/workflows/integration-tests-frontend-tempo.yml, .github/workflows/integration-tests-frontend.yml, hack/setup-kind-in-ci.sh, make/Makefile.olm.mk
part of: https://github.com/kiali/kiali/issues/8237
server PR: https://github.com/kiali/kiali/pull/8545
operator PR: https://github.com/kiali/kiali-operator/pull/928
helm PR: https://github.com/kiali/helm-charts/pull/327
comprehensive test procedures:
* [base test](https://github.com/kiali/kiali/issues/8237#issuecomment-3029115905)
* [upgrade test](https://github.com/kiali/kiali/issues/8237#issuecomment-3191685263)
=> [CI] run CI tests using helm charts appropriate for the server PR

config/config.go, make/Makefile.olm.mk, server/server.go
part of: https://github.com/kiali/kiali/issues/8685
* server PR: https://github.com/kiali/kiali/pull/8686
* operator PR: https://github.com/kiali/kiali-operator/pull/953
* helm PR: https://github.com/kiali/helm-charts/pull/345
=> match with schema

frontend/cypress/integration/common/graph_display.ts, frontend/cypress/integration/featureFiles/waypoint.feature
Explanation of what this PR does
Recommendations for how to test this PR. Reminder that each PR should also include a "Test" label.
=> [CI] Update Ambient tests

frontend/cypress/integration/common/graph_display.ts
The test start failing in master, so reverting possible changes
Recommendations for how to test this PR. Reminder that each PR should also include a "Test" label.
Ref. https://github.com/kiali/kiali/actions/runs/17383761058
=> [CI] Revert changes

business/workloads.go
Handle error when there is an error getting the services for getCapturingWaypoints
- Install Ambient
- See waypoint information. The ideal should be to be able to reproduce the error.
Fixes https://github.com/kiali/kiali/issues/8737
=> Fix nil services capturing waypoint path

.github/workflows/kiali-ci.yml
Limit concurrent group to the workflows from the same PR 
Recommendations for how to test this PR. Reminder that each PR should also include a "Test" label.
Ref. https://github.com/kiali/kiali/pull/8738
=> [CI] Update concurrency group

go.mod
Update GoLang to 1.24.4
https://github.com/kiali/kiali/issues/8755
=> [go] Update GoLang to 1.24.4
