kiali/kiali

business/workloads.go
frontend/src/pages/WorkloadDetails/WorkloadDescription.tsx
frontend/src/pages/WorkloadList/WorkloadListPage.tsx
frontend/src/utils/IstioConfigUtils.ts
models/istio_validation.go

Issue https://github.com/kiali/kiali/issues/6020
Operator PR: https://github.com/kiali/kiali-operator/pull/647
Helm PR https://github.com/kiali/helm-charts/pull/210
Original feature PR: https://github.com/kiali/kiali/pull/4409
Validation warning "KIA1301" will be by default ignored instead of KIA1201 which was set by typo (or by mistake).
And when not ignored, it will be shown in Workload List and Details pages:

Added back validation message on workload list and details pages.

---

frontend/src/pages/Overview/OverviewPage.tsx

I have tested with Chrome and Firefox, but probably it would worth a try with other screen / browser versions, ...
Fixes #6133

Fix header in overview page for large names

---

business/checkers/authorization_policies_checker.go
business/checkers/checker.go
business/checkers/destination_rules_checker.go
business/checkers/gateway_checker.go
business/checkers/k8sgateway_checker.go
business/checkers/k8shttproute_checker.go
business/checkers/no_service_checker.go
business/checkers/no_service_checker_test.go
business/checkers/peer_authentication_checker.go
business/checkers/request_authentication_checker.go
business/checkers/service_checker.go
business/checkers/service_entry_checker.go
business/checkers/sidecars_checker.go
business/checkers/virtual_service_checker.go
business/checkers/workloads_checker.go
business/istio_validations.go
handlers/namespaces.go
models/istio_validation.go
models/istio_validation_test.go

In a multi cluster environment, if we don't send the cluster parameter, it means we want the validations from all the clusters that include that namespace. This is a unified view for a particular case, the summary panel for the graph:

unified validations for summary graph

---

frontend/cypress/integration/common/hooks.ts
frontend/cypress/integration/featureFiles/istio_config.feature
frontend/cypress/integration/featureFiles/wizard_istio_config.feature
frontend/cypress/integration/featureFiles/wizard_k8sgw_api_routing.feature

There has already been some usage of the tags in the gherkin code. However, you can also use Cypress hooks with these to allow for some specific setups or teardowns when needed. This PR is meant to be a PoC of this Cypress feature. 
To demonstrate this:
- setup Kiali without the Gateway API
- run some of the feature files, which contains the `@gateway-api` tag
- you should see those specific tests ~~to be skipped/pending~~ passing instead of running and failing due to the Gateway API not being enabled
This approach might be useful in the future for the multicluster testing or the parallel execution of the Cypress suite. I am also planning to resolve the #6073 issue in a similiar fashion. 
Props to @ScriptingShrimp for guiding me through this.

Skipping the Gateway API tests when Gateway API is not enabled using Cypress hooks

---

frontend/cypress/integration/common/apps.ts
frontend/cypress/integration/common/wizard_istio_config.ts
frontend/cypress/integration/featureFiles/apps.feature

- make apps test happy even if bookinfo has the traffic generator app
- remove the 'be.enabled' tests in most places, it's not happy in CI.

Fix apps cypress failures in downstream CI

---

make/Makefile.build.mk
tests/integration/tests/no_istiod_test.go
tests/integration/tests/remote_istiod_test.go

Fixes https://github.com/kiali/kiali/issues/6121
There was a couple of failures: 
- **no_istiod**: It is not enough for wait for the pod to be ready, we need to wait to the old pod is terminated. Otherwise, doing a request to the application we receive an error `The application is currently not serving requests at this endpoint. It may not have been started or is still starting.`
-  **remote_istiod**: There was a couple of things: 
- One of the calls was using wrong namespace (kialiNS vs KialiDeploymentNS)
- It is safer to don't delete the pod it a Kiali CRD exists - The operator will handle it.  
- Time out per test has to be increased

Fix OCP tests

---

frontend/cypress/integration/common/apps.ts
frontend/cypress/integration/featureFiles/apps.feature

make apps test happy even if bookinfo has the traffic generator app
forward-port of ossm-3940 change in v1.65

[master] Fix apps CI failure in downstream CI

---

frontend/src/reducers/GraphDataState.ts
graph/options.go
graph/telemetry/istio/appender/aggregate_node.go

Fixes https://github.com/kiali/kiali/issues/6098
When generating a Service graph don't change the users' settings for showServiceNodes and showOperationNodes.  The user shouldn't care that those being enabled does not make sense for Service graphs, and shouldn't get surprised by them suddenly getting disabled. Instead, let the backend ignore those settings as needed.

When generating a Service graph don't change user display settings

---

util/httputil/http_util.go

fixes: https://github.com/kiali/kiali/issues/6180
- backport PR to v1.65: https://github.com/kiali/kiali/pull/6194
- backport PR to v1.57: https://github.com/kiali/kiali/pull/6195

authenticate when kiali is deployed behind openshift route with non-standard port

---

handlers/istio_config.go
models/istio_config.go
tests/integration/tests/config_validations_test.go
tests/integration/tests/no_istiod_test.go

Fixes https://github.com/kiali/kiali/issues/6196
Validations test in no_istiod can be uncommented now. 
The behavior will keeps the same - validations not available, Istio configs available.

get config list by namespace when not all namespaces are accessible

---

kubernetes/istio.go
kubernetes/istio_internal_test.go

Issue https://github.com/kiali/kiali/issues/6212
Before:
After:
For Service:
```
apiVersion: v1
kind: Service
metadata:
name: ratings-java
labels:
app: ratings-java
service: ratings-java
spec:
ports:
- name: grpc-name-j
protocol: TCP
appProtocol: grpc-web
port: 8080
targetPort: 8080
- name: http-j
protocol: TCP
appProtocol: http
port: 8480
targetPort: 8480
- name: http2-j
protocol: TCP
appProtocol: grpc
port: 8380
targetPort: 8380
```

Added grpc-web protocol in supported

---

business/namespaces.go
business/testing.go
graph/telemetry/istio/appender/health.go
graph/telemetry/istio/appender/health_test.go

Key did not include cluster and when multiple namespaces exist across clusters the request was being overwritten.
Fixes #6185

Include cluster in health appender request key

---

business/istio_validations.go
frontend/src/pages/Overview/OverviewPage.tsx
frontend/src/services/Api.ts
handlers/namespaces.go
models/istio_validation.go

Issue https://github.com/kiali/kiali/issues/6070
Before: 
There was request to backend with a chunks of namespaces, and without cluster params, the namespaces were duplicated. So in Overview page for remote cluster's namespaces it was showing the home cluster validations.
Now:
Single validations and configs request to backend without namespaces param, will return validations and configs by default for home cluster.
Only home cluster's config validations are shown, for remote ones N/A.
TODO: Separate sub-epic for remote cluster's configs validations.

Skip validations for OverviewPage remote cluster's namespaces

---

.gitleaks.toml
business/authentication/openid_auth_controller.go
business/authentication/openid_auth_controller_test.go

json unmarshalling produces []interface{}, we need to support that type
fixes: https://github.com/kiali/kiali/issues/6226

openid audience claim check needs to support []interface{} type.

---

frontend/cypress/integration/common/wizard_istio_config.ts
frontend/cypress/integration/featureFiles/wizard_istio_config.feature

Fixes #6073.
I added one step before all affected tests to delete the object. 
I also merged the dependent scenarios together. Do we want it this way or is there a more suitable way? The gherkins are huge. @ScriptingShrimp

Test objects cleanup related to the Istio Config Wizard

---

business/istio_config.go
business/istio_config_test.go
frontend/src/components/IstioWizards/ServiceWizard.tsx
frontend/src/components/IstioWizards/ServiceWizardDropdown.tsx
frontend/src/components/IstioWizards/WizardActions.ts
frontend/src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
frontend/src/pages/Overview/OverviewPage.tsx
frontend/src/pages/Overview/OverviewTrafficPolicies.tsx
frontend/src/pages/ServiceDetails/ServiceDetailsPage.tsx
frontend/src/services/Api.ts

RFE https://github.com/kiali/kiali/issues/6239
Remote clusters Istio Configs can be edited in 3 places now:
1. Config Details YAML editor. Edit and Delete.
2. Overview Page Namespace card. Create, Update, Delete traffic policies.
3. Service Details page Traffic Wizard. Crete, Update, Delete traffic.
TODO: Istio Config creation wizard is a separate epic.

Remote cluster - Istio Configs Editable

---

hack/istio/install-sleep-demo.sh
hack/istio/install-testing-demos.sh

Due to the upcoming Cypress hooks, I needed to move the installation of the Sleep app into a separate file. This file is now intended to be called from Cypress when Sleep demo app is not detected.
Tested on upstream OCP and it works.

Sleep hack script refactor to a separate file

---

frontend/cypress/integration/common/hooks.ts
frontend/cypress/integration/featureFiles/app_details.feature
frontend/cypress/integration/featureFiles/apps.feature
frontend/cypress/integration/featureFiles/graph_context_menu.feature
frontend/cypress/integration/featureFiles/graph_display.feature
frontend/cypress/integration/featureFiles/graph_side_panel.feature
frontend/cypress/integration/featureFiles/istio_config.feature
frontend/cypress/integration/featureFiles/istio_config_editor.feature
frontend/cypress/integration/featureFiles/overview.feature
frontend/cypress/integration/featureFiles/service_details.feature
frontend/cypress/integration/featureFiles/services.feature
frontend/cypress/integration/featureFiles/wizard_istio_config.feature
frontend/cypress/integration/featureFiles/wizard_k8sgw_api_routing.feature
frontend/cypress/integration/featureFiles/wizard_request_routing.feature
frontend/cypress/integration/featureFiles/workload_logs.feature
frontend/cypress/integration/featureFiles/workloads.feature
frontend/cypress/integration/featureFiles/workloads_details.feature

This is related to the OSSM-4049 ticket. 
In order to make more robust setup, we want Cypress to detect if certain demoapps are installed before related tests. For example, if the test uses bookinfo, then all of the 6 bookinfo pods and traffic generator must be installed. If they are not or if they are malformed at some way (for example missing pod), then Cypress installs the specific demo app via the hack scripts. 
To test this:
- Deploy Kiali without the bookinfo demo app
- Run any Cypres feature file, which has the `@bookino-app` tag.
- Bookinfo demo app should be installed prior to the first test and all tests related to bookinfo from that FeatureFile should pass
- This should work both for the OCP and non-OCP.
(Drafting this with bookinfo app only. I will turn it into a regular PR …

Bookinfo gherkin annotations for upcoming hook

---

handlers/istio_config.go

Issue https://github.com/kiali/kiali/issues/6253
Istio objects which are not in a Cache (hence K8s Gateways) were not loaded in a case when accessible_namespaces are not ["**"], this happens after merging a PR https://github.com/kiali/kiali/pull/6204.
The [initial issue](https://github.com/kiali/kiali/issues/6196) was about IstioAPI disabled case.
The fix it to add additional check when IstioAPI is not enabled, only then skip loading configs from registry.

Fixed not loading of several config objects which are not cached.

---

frontend/src/components/VirtualList/Config.ts
frontend/src/components/VirtualList/VirtualList.tsx
frontend/src/pages/AppList/AppListPage.tsx
frontend/src/pages/IstioConfigList/IstioConfigListPage.tsx
frontend/src/pages/Overview/OverviewPage.tsx
frontend/src/pages/ServiceList/ServiceListPage.tsx
frontend/src/pages/WorkloadList/WorkloadListPage.tsx

Virtual list type is not a dynamic value, so it does not need to depend on url value. To make it compatible with OSSMC plugin, type is converted to React input property.
Closes #6262

Virtual list type does not depend on url value

---

hack/setup-kind-in-ci.sh

we no longer look for SNAPSHOT in the name - this is so we can run this script in version branches (like `v1.65`).

[ci] don't expect SNAPSHOT to be in helm chart name

---

frontend/src/pages/AppDetails/AppDetailsPage.tsx
frontend/src/pages/Graph/GraphPage.tsx
frontend/src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
frontend/src/pages/IstioConfigNew/IstioConfigNewPage.tsx
frontend/src/pages/ServiceDetails/ServiceDetailsPage.tsx
frontend/src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
frontend/src/routes.tsx
frontend/src/routes/AppDetailsRoute.tsx
frontend/src/routes/GraphRoute.tsx
frontend/src/routes/IstioConfigDetailsRoute.tsx
frontend/src/routes/IstioConfigNewRoute.tsx
frontend/src/routes/ServiceDetailsRoute.tsx
frontend/src/routes/WorkloadDetailsRoute.tsx

Remove routing properties from Kiali pages to be able to use them without react-router. Route wrappers have been created to extract routing properties and add to Kiali pages as React input properties
Closes #6263

Remove routing properties from Kiali pages

---

business/metrics.go
config/dashboards/dashboards.go
config/dashboards/dashboards_config_test.go
frontend/cypress/integration/common/overview.ts
frontend/cypress/integration/featureFiles/overview.feature
frontend/src/pages/Overview/OverviewCardControlPlaneNamespace.tsx
frontend/src/pages/Overview/OverviewCardSparklineChartsComponent.tsx
frontend/src/pages/Overview/OverviewPage.tsx
frontend/src/types/Metrics.ts

Resolves #6177.
Docs PR: https://github.com/kiali/kiali.io/pull/664
This PR adds some logic to fetch the "process" metrics (CPU and memory) if "container" metrics are not available in Prometheus (this is the case for OSSM when it's using it's own Prometheus, which hasn't configured cAdvisor scraping metrics).
Kiali will indicate the source of the metric like:

Control plane metrics improvements

---

frontend/cypress/integration/featureFiles/wizard_istio_config.feature
frontend/src/pages/IstioConfigNew/ServiceEntryForm.tsx

Issue https://github.com/kiali/kiali/issues/6287
Go To Istio Config page.
Actions -> Create ServiceEntry.
Fill the 'Name' and 'Hosts' fields.
Empty 'Ports' were showing error message but the 'Preview' button was enabled and confusing.
Now the 'Preview' button will be disabled when Ports are not set at all.
Before:
Now:

Empty ServiceEntry Ports disables Preview button

---

business/services.go

Issue https://github.com/kiali/kiali/issues/6294
Even though ServiceEntry was found in Registry, the initial error of not found in cache was returning.
Fixed to override the initial error.

Fixed showing error when Service is found in registry.

---

business/mesh.go
business/mesh_test.go
config/config.go
hack/istio/multicluster/kiali-prepare-remote-cluster.sh
kubernetes/client.go
kubernetes/client_config.go
kubernetes/client_factory.go
kubernetes/client_test.go
kubernetes/cluster_secret_test.go
kubernetes/secret.go

**Describe the change** 
Currently, kiali only supports SA bearer tokens for connections to the remote cluster when the auth strategy is Anonymous.
This PR allows the use of [ExecProvider](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins) supported by kubernetes in addition to SA bearer tokens.
Please note that while there is a discussion of sidecar support by kiali in #6193, these features are not necessarily required in this case. This is because at this time users are free to add sidecar and other definitions by using the json patch in kustomize, etc.
**Issue reference** 
- Fixed #6193

Support exec credentials in remote secret

---

frontend/cypress/integration/common/kiali_login.ts

The test expects buttons with auth providers when on Openshift. When no users are present on the cluster and the only way to log in is using the Kubeadmin, Openshift login page skips the buttons and goes straight to login form. However, the test still expects buttons, which causes it to fail. 
I've added a condition to prevent this from happening.
Thanks @FilipB for discovering this.

Cypress Kiali Login test fix

---

tests/integration/Dockerfile

This pgk is required for hack scripts which are installing demo apps

[v1.65] adding missing pkg for int tests image

---

frontend/src/app/History.ts
frontend/src/components/BreadcrumbView/BreadcrumbView.tsx
frontend/src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
frontend/src/components/CytoscapeGraph/MiniGraphCard.tsx
frontend/src/components/DetailDescription/DetailDescription.tsx
frontend/src/components/Link/IstioObjectLink.tsx
frontend/src/components/Link/ServiceLink.tsx
frontend/src/components/Link/WorkloadLink.tsx
frontend/src/components/Metrics/CustomMetrics.tsx
frontend/src/components/TrafficList/TrafficListComponent.tsx
frontend/src/components/VirtualList/Renderers.tsx
frontend/src/pages/AppDetails/AppDetailsPage.tsx
frontend/src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
frontend/src/pages/Overview/OverviewPage.tsx
frontend/src/pages/ServiceDetails/ServiceDetailsPage.tsx
frontend/src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
frontend/src/services/Api.ts
frontend/src/types/MetricsOptions.ts
handlers/apps.go
handlers/health.go
handlers/utils.go
handlers/utils_test.go
handlers/workloads.go

This is changed just in the parameter, the variable name "cluster" was not renamed. 
I wonder if I should also change it to keep consistency, but still at some point (Like in the queries), clusterMesh should be changed by cluster.
Fixes #6322

Rename cluster param for clusterMesh

---

business/metrics_definitions.go
config/config.go
frontend/src/pages/Graph/GraphToolbar/GraphFind.tsx
frontend/src/types/ServerConfig.ts

Fixes #6012
Operator PR: https://github.com/kiali/kiali-operator/pull/665 
kiali.io PR: https://github.com/kiali/kiali.io/pull/671
Example for testing: 
```
ui_defaults: 
graph:
hide_options:
- description: "Hide unselected namespaces"
expression: "outside"
- description: "Hide nodes with no label region"
expression: "!label:region"
find_options:
- description: "name not contains rev"
expression: "name not contains rev"
- description: "tcpserver"
expression: "name = tcpserver"
auto_enable: true
```

Auto-enable find/hide filters via Kiali CR

---

frontend/src/components/BreadcrumbView/BreadcrumbView.tsx
frontend/src/services/Api.ts
frontend/src/services/GraphDataSource.ts

Remove cluster param from the workload graph API url. 
Besides, I have found a cluster param reference in BreadCrumbView component (renamed to clusterName).
Fixes #6328 
** Testing PR **
1. Select any workload.
2. Go to graph API request URL (Network section of Chrome developer tools)
3. Check that only cluster param does not appear (only clusterName)

Remove cluster param from workload graph API url

---

deploy/docker/Dockerfile-distroless
deploy/docker/Dockerfile-multi-arch-distroless

use the ubi8/openssl container image as the kiali base image so the Dockerfiles are simpler. 
ubi8/openssl is exactly what we need - the ubi8-micro plus the openssl stuff.

use ubi8/openssl for our base image (it is micro + openssl)

---

business/namespaces.go
graph/telemetry/istio/appender/appender.go
graph/telemetry/istio/appender/idle_node.go
graph/telemetry/istio/appender/istio_details.go

Fixes https://github.com/kiali/kiali/issues/6331
Fix issue with IdleNodes detection. The multi-cluster changes resulted in only looking at clusters WITH traffic, but for idle nodes we need to look at all clusters for a namespaces, regardless of traffic.
- Adds new NamespaceService.GetNamespaceClusters() utility function
https://github.com/kiali/kiali/issues/6331
Test Note:
To recreate this bug you need to have NO traffic for any services/workloads in the target namespace, for the time period.

Fix issue with IdleNodes detection

---

.github/workflows/build-backend.yml
.github/workflows/release.yml

Fixes #6324.
In this PR:
- Setup Go honoring the variable GO_VERSION_KIALI found in the Makefile
- Simplify the options when building:
When the workflow is set from master, means we are building a minor version and when the workflow comes from other branches (usually prior versions like v1.70, etc) will are building a patch release from that branch's code.
If this PR is merged, this will be the new way of launching builds for master and also for the branches that has this definition backported, meaning, ideally we should backport this changes to the branches we usually release (OSSM versions). 
What happens if we don't backport this change? When choosing from the combo box where the workflow comes from, let's say we want to release a patch for v1.69, we are going to look for that …

Actions improvements

---

kubernetes/client_factory.go

When OpenID authentication is used and the `disable_rbac` flag is set to `true`, kiali should use its own K8s ServiceAccount to access remote clusters
closes #6308

fix incorrect K8s SA being used with OIDC when RBAC is disabled

---

tests/integration/tests/remote_istiod_test.go

Reported failure for interop tests: 
`deployments.apps "istiod-install-istio-system" not found`
The Istio deployment name was hard coded in the tests.

v1.65 - remote istiod obtain Istio deployment name 

---

hack/istio/multicluster/deploy-kiali.sh
hack/istio/multicluster/env.sh
hack/istio/multicluster/install-primary-remote.sh
hack/istio/multicluster/kiali-prepare-remote-cluster.sh
hack/istio/multicluster/start-kind.sh

Adds kind support for MC hack scripts. Only `anonymous` mode is supported for now since some of the setup for keycloak is minikube specific. 
Testing instructions:
1. Deploy istio primary-remote
```
hack/istio/multicluster/install-primary-remote.sh --manage-kind true -dorp docker
```
2. Deploy Kiali
```
hack/istio/multicluster/deploy-kiali.sh --manage-kind true -dorp docker -kas anonymous
```
3. Visit Kiali URL and verify everything is working correctly
```
curl http://$(kubectl get svc -n istio-system istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip})/kiali
``` 
Fixes #6358

Kind support for MC hack scripts

---

business/authentication/openid_auth_controller_test.go
business/authentication/token_auth_controller_test.go
business/istio_config.go
business/istio_status_test.go
business/layer.go
business/mesh_test.go
business/namespaces.go
business/namespaces_test.go
business/workloads_test.go
config/config.go
go.mod
go.sum
graph/api/api_test.go
graph/telemetry/istio/appender/health_test.go
handlers/apps_test.go
handlers/proxy_logging_test.go
handlers/workloads_test.go
kubernetes/cache/cache.go
kubernetes/cache/kube_cache.go
kubernetes/cache/kube_cache_test.go
kubernetes/cache/registry_test_helper.go
server/server.go
server/server_test.go

Cleanup `cache != nil` checks since cache has been mandatory for awhile. Also removes some caching options from the kiali config.
Fixes #5599

Make cache mandatory and remove some cache config opts

---

business/apps.go
business/health.go
business/istio_config.go
business/istio_validations.go
business/mesh.go
business/namespaces.go
business/namespaces_test.go
business/services.go
business/tls.go
business/workloads.go
handlers/apps.go
handlers/apps_test.go
handlers/dashboards.go
handlers/health.go
handlers/istio_config.go
handlers/metrics.go
handlers/metrics_test.go
handlers/namespaces.go
handlers/services.go
handlers/services_test.go
handlers/tls.go
handlers/utils.go
handlers/utils_test.go
handlers/workloads.go
handlers/workloads_test.go
kubernetes/kubetest/mock_kubernetes.go

Fixes https://github.com/kiali/kiali/issues/6333
There was some calls to getNamespace that didn't include the cluster parameter. But in a multicluster environment, a namespace with the same name can exist in different clusters, which can result in more than one namespace. getNamespace mehod was returning just one namespace, the first namespace found, which is a behavior non deterministic. 
This behavior was changed to use, when we want a namespace and we don't know the cluster (So we can expect to have more than one) GetNamespaceClusters, implemented as part as https://github.com/kiali/kiali/pull/6336/files.
The majority of the calls include the cluster parameter. Some metrics calls doesn't include it, because in the right panel summary for the graphs, we want the metrics for the …

Use cluster param when it is available

---

hack/istio/multicluster/deploy-kiali.sh
hack/run-kiali.sh

Fixes `hack/run-kiali.sh` script by creating a temp kubeconfig and using that as a [remote secret](https://github.com/kiali/kiali#observing-a-remote-cluster) rather than trying to use the "in cluster config".

Use remote secret in hack run script

---

business/layer.go
business/openshift_oauth.go

The Openshift OAuth business service now relies on the kiali service account client but it wasn't being passed in by the business layer.
Fixes #6381

Pass kiali SA client to OS biz svc

---

kubernetes/cache/kube_cache.go

Backporting error checks from #6231 since the linter complains about this during release.

[v1.66] Backport error checks for registry handler

---

tests/integration/tests/applications_test.go
tests/integration/tests/config_validations_test.go
tests/integration/tests/dashboards_test.go
tests/integration/tests/external_host_node_test.go
tests/integration/tests/graph_badges_test.go
tests/integration/tests/graph_nodes_test.go
tests/integration/tests/graph_test.go
tests/integration/tests/istio_config_test.go
tests/integration/tests/kiali_metrics_test.go
tests/integration/tests/kiali_urls_test.go
tests/integration/tests/namespaces_test.go
tests/integration/tests/no_istiod_test.go
tests/integration/tests/pod_logs_test.go
tests/integration/tests/services_test.go
tests/integration/tests/traces_spans_test.go
tests/integration/tests/workloads_test.go

Replaces  `assert` with `require` in e2e tests to ensure that tests immediately fail and stop executing if unexpected input is encountered. This is necessary to avoid nil pointer access. For example
```
resp, err := request(...)
assert.Nil(err)
assert.NotNil(resp)
resp.Name
```
would result in a panic if there's an error and resp is nil because `assert` does not stop executing the test. Whereas using `require` would stop execution of the test making it more clear where/how the test failed.
Also replaces `Nil(err)` checks with `NoError(err)` because the latter will log the error instead of printing the error object which does not show you the error text.
Note this doesn't fix any CI flake but it should make it more visible what the problem is when flakes or e2e test failures happen in the …

[CI] e2e tests - Fail on error

---

kubernetes/cache/kube_cache.go

Fixes a typo that added the refresh handler to the `Gateways` resource instead of the `HTTPRoutes` resource.

Add correct resource to registry handler

---

frontend/src/config/Icons.ts
frontend/src/pages/GraphPF/GraphPF.tsx
frontend/src/pages/GraphPF/GraphPFElems.tsx
frontend/src/pages/GraphPF/styles/styleNode.tsx

Closes #6370 
Because PFT allows for only a single labelIcon (i.e badge), we will reserve that specifically to indicate Traffic Sources (or Gateways) because it helps users identify where traffic is entering the mesh.  The other badges we see in Cytoscape will be presented as node attachments.  BUT, since there are only a limited number of attachments (4), and we want to present badges in a consistent location, all VS features will be indicated by the VS icon, and the tooltip will indicate the specific VS features in play.

An approach to handling the "mutiple badge" issue for Nodes

---

business/health.go
models/workload.go

Issue https://github.com/kiali/kiali/issues/6372
The issue can be reproduced on multicluster env, for 'east' cluster's 'istio-system' namespace (easiest way).
It shows 1 Error on the 'istio-system' namespace card for 'east' cluster in Overview page for Apps and Workloads, for the workload 'istio-ingressgateway', but in fact when checking Apps list or details, all are healthy.
The failure is because there is some 'outbound' request with '403' for that workload 'istio-ingressgateway'.
The issue is in inconsistency when calculating health for App/Workloads and for Namespace in Overview page.
For individual or list of Apps/Workloads, those workloads which does not have sidecars, the health does not include Requests.
But in Overview page there was a bug, if at least one workload has a sidecar, …

Skip loading requests health for apps and workloads without sidecar

---

hack/istio/install-bookinfo-demo.sh

This supports ambient mode. The default behavior stays the same (which is auto-injecting the sidecar), however, if you turn off auto-injection (`-ai false`) then no sidecars are injected. If you do this, a message will spit out telling you what you have to do to enable ambient mode (you are told what command to use to label the namespace).
Note that this still retains the ability to manually inject the sidecars via istioctl (you do this using the `-mi` option )

[hack] support ambient by telling bookinfo install script if you want injection and if so what kind

---

frontend/src/pages/Graph/GraphPage.tsx
frontend/src/pages/Graph/GraphToolbar/GraphToolbar.tsx

Fixes #6248 
Fix regression introduced in https://github.com/kiali/kiali/pull/6087 (v1.69). That PR successfully fixed an metrics query issue caused by premature rendering of the SummaryPanel.  But the overly-delayed rendering caused a resize of the available graph space, which forced a unwanted "fit".  The fit operation loses the user's custom zoom/pan. This PR changes the approach, delaying an appropriate amount.
To test, open the browser debug Network tab.  Filter on 'metrics'.   Go to the main graph and set a 10s refresh.  Ensure that the main graph renders fine.  Zoom in and ensure the zoom stays constant on auto-refresh.  Select nodes and ensure the side-panel updates as expected and refreshes as expected.
Double-click a node to enter the node-detail graph.  Ensure it looks fine and …

Fix unwanted graph "fit" on refresh 

---

config/config.go
hack/run-kiali-config-template.yaml
hack/run-kiali.sh
kubernetes/client.go
kubernetes/client_factory.go
kubernetes/client_factory_test.go
kubernetes/testdata/remote-cluster-multiple-users.yaml
kubernetes/testing.go
kubernetes/token.go
kubernetes/token_test.go

Instead of taking the first item in the auth info map for the remote secret, Kiali will now look at the current context and get the auth info for the current context. An error is returned if the current context is not set in the kubeconfig.
Also exposes the remote secret path as a config value so that you don't have to use the hardcoded `/kiali-remote-secret/kiali`. Useful when running locally with `run-kiali.sh` so you don't have to create that root dir.
Fixes #6402

Look for current context in remote secret

---

frontend/src/components/CytoscapeGraph/CytoscapeGraph.tsx
frontend/src/components/Link/KialiPageLink.tsx
frontend/src/components/Nav/Masthead/Masthead.tsx
frontend/src/components/Nav/Menu.tsx
frontend/src/components/Nav/Navigation.tsx
frontend/src/config/ServerConfig.ts
frontend/src/config/index.ts
frontend/src/pages/Graph/SummaryLink.tsx
frontend/src/pages/Graph/__tests__/SummaryLink.test.tsx
frontend/src/pages/Graph/__tests__/SummaryPanelNode.test.tsx
frontend/src/pages/GraphPF/GraphPFElems.tsx
frontend/src/pages/IstioConfigDetails/IstioObjectDetails/IstioConfigOverview.tsx
frontend/src/store/ConfigStore.ts
frontend/src/types/ServerConfig.ts
handlers/config.go

Get cluster info from the clusters object and remove the duplicated `ClusterInfo` field from the `/config` response.
Fixes #6373

Remove cluster info from config response

---

config/config.go
frontend/cypress/integration/common/apps.ts
handlers/metrics.go
models/metrics.go

Issue https://github.com/kiali/kiali/issues/6405
For single OCP cluster environment, the Target.Cluster param is empty in Metrics json query. Thus the backend fails to retrieve userClient for a cluster. https://github.com/kiali/kiali/blob/master/business/namespaces.go#L570
Using similar logic as in `clusterNameFromQuery` for Target.Cluster.
Is there a better way to set default cluster?

Use KubernetesConfig.ClusterName for Metrics query Target.Cluster by default

---

hack/ci-kind-molecule-tests.sh

This is useful when running multiple tests and you want to start each with a fresh cluster (like when testing with OLM and then with helm).

[hack] be able to rebuild cluster to start tests fresh.

---

frontend/cypress/integration/common/graph_display.ts
frontend/cypress/integration/featureFiles/graph_display.feature

This is a Cypress automation of a test scenario (#6307) and it relates to certain Graph page controls being disabled when using the Service graph (#6188).

Cypress automation for a Graph page test scenario

---

frontend/src/pages/GraphPF/GraphPF.tsx

There was an extra parenthesis in the PF Graph, which was visible in the left middle of the graph: 
To reproduce, we should set impl: "pf"

Remove extra parenthesis in PF Graph

---

frontend/package.json
frontend/src/pages/GraphPF/components/groupExpanded.tsx
frontend/src/pages/GraphPF/components/node.tsx
frontend/src/pages/GraphPF/layouts/layoutFactory.ts

Epic https://github.com/kiali/openshift-servicemesh-plugin/issues/99
This PR makes two enhancements:
- small changes to the layout to reduce distances between nodes and lengths of edges.  This makes the graph slightly more compact to better fit larger graphs.
- add support for bringing labels to the top on hover, to be able to see labels that may be partially overlapped.
- note that this adds a D3 dependency into package.json.  This is the same version already required by PFT, so I don't think it adds any size or risk, but I did want to call it out.
Before:
- Note the nodes are more zoomed out because the graph takes more space
After:
- The graph is easier to read because it takes less space and requires less zoom
- Note that the "bookinfo" label has ben brought forward by a hover

PFT graph enhancements

---

frontend/cypress/integration/common/wizard_istio_config.ts
frontend/cypress/integration/featureFiles/wizard_istio_config.feature

Related to #6295.
Do we want to backport this test to 1.65 as well?

Cypress automation for 'Service details of ServiceEntry fails' fix

---

frontend/cypress/integration/common/istio_config.ts
frontend/cypress/integration/featureFiles/istio_config.feature

Issue https://github.com/kiali/kiali/issues/6460
'bookinfo' VS is a wildcard, which covers KIA0104 validation, so make sure it is removed before.

Remove wildcard VS bookinfo before checking KIA0104

---

frontend/src/components/JaegerIntegration/JaegerResults/SpanTable.tsx
frontend/src/components/TrafficList/TrafficListComponent.tsx
frontend/src/utils/SearchParamUtils.ts

Issue https://github.com/kiali/kiali/issues/6462
In "View metrics" url's parameter 'tab' had hardcoded separator '?', but with with '?clusterName=...' param it was having a conflict, so added a check to put '&' separator.
In "Traffic" tab's "View Metrics" links and in 'Span Details' subtab's kebab menu 'Inbound/Outbound Metrics' links.

Fixed hardcoded params separator for metrics tab links.

---

hack/run-kiali.sh

Ref. #5848 
To use it with the environment set in https://github.com/kiali/kiali.io/pull/686:
`./run-kiali.sh -pg 13000:3000 -pp 19090:9090 -app 8080 -es false -iu http://127.0.0.1:15014 -tr tempo-smm-query-frontend -ts tempo-smm-query-frontend -tn tempo`

Adapt run-kiali script to use other tracing backend than Jaeger

---

hack/run-integration-tests.sh
tests/integration/utils/kiali/kiali_client.go
tests/integration/utils/kiali/retry.go

Add an external health check before running tests. My guess is that it takes a minute for the pods to be added to the service's load balancer pool even after the pods are ready so we need to do an external health check before running the tests.
Fixes (hopefully) https://github.com/kiali/kiali/issues/6418

Do external health check before running tests

---

make/Makefile.molecule.mk

This auto-detection of hosts should never occur unless the cluster is openshift. Without this fix, the getent commands hang until they timeout causing the test times to go from 2 minutes to 16 minutes. lol

[make] fix molecule test make target

---

.github/workflows/molecules.yml

This runs the molecule tests nightly. It will run the tests twice - once with the operator installed via helm and once with the operator installed via OLM.
(merge this only after https://github.com/kiali/kiali/pull/6484 is merged)

[CI] run molecule tests nightly

---

hack/README.adoc
hack/run-integration-tests.sh

Adds a section to the README and help message about increasing some kernel settings when setting up a multi-cluster environment locally with kind.

Add sysctl info to README and hack script

---

business/istio_validations.go
business/layer.go
business/mesh.go
business/mesh_test.go
business/testing.go
handlers/mesh.go
handlers/mesh_test.go
handlers/testing.go
kubernetes/cache/cache.go
kubernetes/cache/kube_cache.go
kubernetes/cluster_secret.go
kubernetes/types.go
models/namespace.go
routing/routes.go

Creates a couple new models to store controlplane configuration per controlplane since with multi-primary there can be multiple controlplanes. Even with single cluster there can be multiple controlplanes when revisions are used. This will allow Kiali to better support control plane revisions in the future even for single cluster.
This adds the models but stops short of updating various methods that gather controlplane info to use them yet.
Fixes #6430

Add GetMesh method to gather info about controlplanes

---

frontend/src/components/Envoy/tables/BaseTable.tsx

Fixes: #6502
This is a very small fix to not fix the position of the help icon (In the right corner of the table) in the Envoy tab. 
Previous to this fix: 
The position of the icon was fixed, so it didn't move when we scroll down. 
After the fix:

Change fixed position for help icon in Envoy tab

---

frontend/src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx

Issue https://github.com/kiali/kiali/issues/6374
At some point `"` does not exist in json from YAML for deleted array lines.

Config deletion - Fixed null replacement in json

---

business/mesh.go
config/config.go

Issue https://github.com/kiali/kiali/issues/6243
Operator PR https://github.com/kiali/kiali-operator/pull/672
A new configuration is added in Kiali configmap, called 'kiali_urls', which is a mapping between cluster name and Kiali URL.
This value will be used if Kiali Service annotation 'kiali.io/external-url' does not have value.

Added new config for kiali URL per cluster name mapping

---

business/mesh.go

fixes: https://github.com/kiali/kiali/issues/6517

only call with empty namespace when in cluster-wide access mode

---

frontend/cypress/integration/featureFiles/workloads_details.feature

In feature file there are two tags added. This test fail only on OCP and in interop. Hope this will fix that @FilipB

Cypress: doubled timeouts for flaky test on interop OSSM-4624

---

tests/integration/tests/applications_test.go
tests/integration/tests/config_validations_test.go
tests/integration/tests/dashboards_test.go
tests/integration/tests/external_host_node_test.go
tests/integration/tests/graph_badges_test.go
tests/integration/tests/graph_nodes_test.go
tests/integration/tests/graph_test.go
tests/integration/tests/istio_config_test.go
tests/integration/tests/kiali_metrics_test.go
tests/integration/tests/kiali_urls_test.go
tests/integration/tests/namespaces_test.go
tests/integration/tests/no_istiod_test.go
tests/integration/tests/pod_logs_test.go
tests/integration/tests/services_test.go
tests/integration/tests/traces_spans_test.go
tests/integration/tests/workloads_test.go

Backport of #6389 to v1.65. Just a find/replace of `assert` --> `require` in e2e tests so that tests will fail without panicing.

[v1.65] Backport of https://github.com/kiali/kiali/pull/6389

---

frontend/src/services/Api.ts

When a token is present, we send it through params and when a username and password is present, we send it through Auth header. 
There is no need to send Auth header when the token is not empty.
https://github.com/kiali/kiali/issues/6533

Change login func to not send Auth header when token is present

---

frontend/src/pages/GraphPF/components/groupExpanded.tsx
frontend/src/pages/GraphPF/components/node.tsx

When user hovers an application label in PF graph, application considers that d3 target can have only one class, but this is not correct and the error is produced. Instead of comparing the whole string, just check the first class is `pf-topology__group`
Fixes #6458
** PR testing **
After the fix is applied, no error message appears in the console.

Consider d3 target to have multiple classes in pf graph

---

kiali.go

add sigterm signal handle. 
In most time, service use 15 signal to stop process
fixes: https://github.com/kiali/kiali/issues/6535

add sigterm signal handle

---

make/Makefile.olm.mk

fixes: https://github.com/kiali/kiali/issues/6545
We will want to do a similar fix for the OSSMC make target that is similar: https://github.com/kiali/openshift-servicemesh-plugin/blob/main/make/Makefile.olm.mk#L69 (_update_: this was done in this PR: https://github.com/kiali/openshift-servicemesh-plugin/pull/201)

workaround opm render bug by providing custom docker_config location

---

frontend/src/components/Health/__tests__/__snapshots__/HealthIndicator.test.tsx.snap
frontend/src/components/Label/__tests__/__snapshots__/Label.test.tsx.snap
frontend/src/components/Label/__tests__/__snapshots__/Labels.test.tsx.snap
frontend/src/components/ToolbarDropdown/__tests__/__snapshots__/ToolbarDropdown.test.tsx.snap
frontend/src/components/Validations/__tests__/__snapshots__/ServiceValidationSummary.test.tsx.snap
frontend/src/components/Validations/__tests__/__snapshots__/ValidationSummary.test.tsx.snap
frontend/src/pages/Graph/GraphToolbar/__tests__/__snapshots__/GraphLegend.test.tsx.snap
frontend/src/pages/Login/__tests__/__snapshots__/LoginPage.test.tsx.snap
frontend/src/pages/Overview/__tests__/__snapshots__/OverviewPage.test.tsx.snap
frontend/src/pages/WorkloadDetails/__tests__/__snapshots__/ProxyStatusList.test.tsx.snap
frontend/src/styles/StyleUtils.ts

A typestyle custom style is added when you want to apply a direct style to a component. For this reason it should have a high specificity value to be at the top of CSS cascade (more details about CSS specificity here: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance). Currently kiali style has a specificity of (0,1,0) which is quite low to be placed at the the top of CSS cascade. Actually there are some Openshift CSS classes that have more specificity and overwrite the typestyle style defined for the component in OSSMC plugin.
For this reason specificity of kiali styles have been increased to (0,3,0). This value is quite high and it is weird that an external CSS class has more specificity than that (usual values are 0,1,0 …

Increase specificity of kiali style

---

frontend/cypress/integration/common/istio_config.ts
frontend/cypress/integration/common/istio_config_type_filters.ts
frontend/cypress/integration/common/table.ts
frontend/cypress/integration/featureFiles/apps.feature
frontend/cypress/integration/featureFiles/istio_config.feature
frontend/cypress/integration/featureFiles/istio_config_type_filters.feature
frontend/cypress/integration/featureFiles/services.feature
frontend/cypress/integration/featureFiles/workloads.feature
frontend/src/pages/AppList/FiltersAndSorts.ts
frontend/src/pages/IstioConfigList/FiltersAndSorts.ts
frontend/src/pages/ServiceList/FiltersAndSorts.ts
frontend/src/pages/WorkloadList/FiltersAndSorts.ts

Fixes https://github.com/kiali/kiali/issues/6512
Prevent "istio type" filter carryover between config list page and other list pages.
- Change "Istio Type" filter to be "Type" for Istio Config list page, the context is implied.
- Change "Istio Type" filter to be "Istio Config Type" for other list pages. the filter should be more explicit.
- The change in filter naming prevents the previous "Istio Type" filter carryover

Prevent "istio type" filter carryover

---

config/config.go
kubernetes/filters.go

RFE https://github.com/kiali/kiali/issues/6429
For testing this:
Apply Contour implementation of Gateway API: https://projectcontour.io/docs/1.26/guides/gateway-api/
In Kiali CR make sure to configure classes:
```
istio:
gateway_api_classes:
- name: Contour
class_name: contour
- name: Istio
class_name: istio
```
New Gateway config will appear in list:
TODO in next PR: Apply multiple classes in config wizards.

Added support of multiple Gateway API classes

---

frontend/package.json
frontend/src/components/Charts/ChartWithLegend.tsx
frontend/src/components/Charts/Container.tsx
frontend/yarn.lock

There are some dependencies in package.json that are direct dependencies of PF libraries and tightly related (only used to support PF components):
- d3
- victory
- @patternfly/react-tokens (this one is not used directly by Kiali)
All these libraries can be removed from package.json since they are direct dependencies of PF and downloaded with PF libraries. Then we do not have to update version of such libraries when we update PF. 
Closes #6564

Remove PF direct dependencies from package.json

---

hack/istio/create-mesh-namespace.sh
hack/istio/install-bookinfo-demo.sh
hack/istio/install-electronic-shop-demo.sh
hack/istio/install-error-rates-demo.sh
hack/istio/install-federated-travels-demo.sh
hack/istio/install-fraud-detection-demo.sh
hack/istio/install-music-store-demo.sh
hack/istio/install-runtimes-demo.sh
hack/istio/install-scale-mesh-demo.sh
hack/istio/install-service-spawner-demo.sh
hack/istio/install-sleep-demo.sh
hack/istio/install-topology-generator-demo.sh
hack/istio/install-travel-agency-demo.sh
hack/perf-ibmcloud-openshift.sh

https://docs.openshift.com/container-platform/4.13/authentication/managing-security-context-constraints.html#scc-prioritization_configuring-internal-oauth
The SCC created by the script didn't have a priority, so it defaults to 0, which is the same as all the other restrictive sccs that come out of box. So...
```
If the priorities are equal, the SCCs are sorted from most restrictive to least restrictive.
```

[hack] fix install-bookinfo-demo and other hack scripts for SCC priority

---

hack/ci-kind-molecule-tests.sh

fixes: https://github.com/kiali/kiali/issues/6567
This is what the output should look like now:
```
...
[INFO] OLM v0.25.0 is installed.
[INFO] Installing Kiali Operator via OLM
subscription.operators.coreos.com/my-kiali created
[INFO] Waiting for Kiali CRD to be created...............
[INFO] Waiting for Kiali CRD to be established.
customresourcedefinition.apiextensions.k8s.io/kialis.kiali.io condition met
[INFO] Waiting for operator to be created.
[INFO] Waiting for deployments to start up in the operators namespace.
deployment.apps/kiali-operator condition met
[INFO] Configuring the Kiali operator to allow ad hoc images, ad hoc namespaces, and changes to security context.
[INFO] Kiali operator namespace: [operators]
...
```

[ci test] wait for the operator deployment to be created

---

hack/istio/tempo/install-tempo-env.sh
hack/istio/tempo/minio.yaml

Fixes #6592 
Grafana Tempo docs: https://grafana.com/docs/tempo/latest/setup/operator/ 
`kiali/hack$ istio/tempo/install-tempo-env.sh `
The script will install:
- tempo namespace with cert manager (required for tempo operator), the tempo operator, minio, tempoStack resource, istio (Optional), kiali (optional) and bookinfo demo (optional). 
Can be tested validating that all the tempo resources are running: 
`kubectl get all -n tempo`
```
deployment.apps/minio                 
deployment.apps/tempo-smm-compactor  
deployment.apps/tempo-smm-distributor      
deployment.apps/tempo-smm-querier        
deployment.apps/tempo-smm-query-frontend
```
To test with Kiali, there is needed another PR with the tempo integration: https://github.com/kiali/kiali/pull/6518
Kiali config: 
```
tracing: …
```

New hack script for tempo

---

frontend/src/pages/IstioConfigDetails/IstioObjectDetails/IstioConfigOverview.tsx

Absolute url is defined in 'Edit in Kiali' link to support those use cases where Kiali instance is not hosted at the same path that kiosk mode Kiali frontend (e.g. OSSMC).
Fixes #6593.
**PR Testing**
1. Go to any Istio Config page and select any object to see YAML editor.
2. Add `?kiosk=true` to URL to activate kiosk mode
3. Click on 'Edit in Kiali' link to check that it redirects to the Kiali instance.

Use Kiali instance url info to create 'Edit in Kiali' link (kiosk mode)

---

business/istio_config.go
config/config.go
frontend/src/components/DebugInformation/DebugInformation.tsx
frontend/src/components/IstioWizards/GatewaySelector.tsx
frontend/src/components/IstioWizards/K8sGatewaySelector.tsx
frontend/src/components/IstioWizards/ServiceWizard.tsx
frontend/src/components/IstioWizards/WizardActions.ts
frontend/src/config/ServerConfig.ts
frontend/src/pages/IstioConfigNew/K8sGatewayForm.tsx
frontend/src/types/ErrorRate/__testData__/ErrorRateConfig.ts
frontend/src/types/ServerConfig.ts
frontend/src/types/__testData__/HealthConfig.ts
handlers/config.go
kubernetes/filters.go
kubernetes/istio.go

Issue https://github.com/kiali/kiali/issues/6429
When there are more than 2 Gateway classes configured in Kiali CR
```
gateway_api_classes:
- name: Istio
class_name: istio
- name: Contour
class_name: contour
```
In both wizards, Kiali Service -> Create K8s Gateway API Routing and Istio Config -> Create K8s Gateway, it appears dropdown to select the Gateway API implementation:

Gateway API class selector in K8s Gateway Istio config wizard

---

frontend/cypress/integration/common/app_details.ts
frontend/cypress/integration/common/apps.ts
frontend/cypress/integration/common/graph_context_menu.ts
frontend/cypress/integration/common/graph_display.ts
frontend/cypress/integration/common/kiali_help.ts
frontend/cypress/integration/common/navigation.ts
frontend/cypress/integration/common/overview.ts
frontend/cypress/integration/common/service_details.ts
frontend/cypress/integration/common/wizard_istio_config.ts
frontend/cypress/integration/common/workloads_details.ts
frontend/cypress/integration/featureFiles/app_details.feature
frontend/cypress/integration/featureFiles/apps.feature
frontend/cypress/integration/featureFiles/graph_context_menu.feature
frontend/cypress/integration/featureFiles/graph_display.feature
frontend/cypress/integration/featureFiles/graph_side_panel.feature
frontend/cypress/integration/featureFiles/istio_config.feature
frontend/cypress/integration/featureFiles/istio_config_editor.feature
frontend/cypress/integration/featureFiles/kiali_help.feature
frontend/cypress/integration/featureFiles/overview.feature
frontend/cypress/integration/featureFiles/service_details.feature
frontend/cypress/integration/featureFiles/services.feature
frontend/cypress/integration/featureFiles/wizard_istio_config.feature
frontend/cypress/integration/featureFiles/workloads.feature
frontend/cypress/integration/featureFiles/workloads_details.feature

Related to #6549. 
This PR is adding additional tests and checks to ensure Multi-cluster related features are not causing problems for the single cluster setup. This includes checking that no clusterName parameter is used in links, no cluster badges and columns are visible and also no cluster dropdown should be available in the Istio config wizard.

Multi-cluster - negative testing against single cluster setup

---

README.adoc
hack/istio/multicluster/install-primary-remote.sh

Partially fixes #6606.
According to the [Istio 1.19 change notes](https://istio.io/latest/news/releases/1.19.x/announcing-1.19/change-notes/#istioctl), `remote_clusters` and `create-remote-secret` subcommands were moved out of the experimental section. 
Situation before: https://github.com/kiali/kiali/actions/runs/6164572810/job/16730830468?pr=6605#step:8:423
Situation now:

Failing gateway pod due to istioctl 1.19 update

---

hack/istio/multicluster/deploy-kiali.sh
hack/setup-kind-in-ci.sh

Related to #6547.
To test this:
- build Kiali locally 
- run the `./hack/run-integration-tests.sh --test-suite frontend-multi-cluster -so true` command
- open the Kiali page and check that it uses SNAPSHOT version and not release

Make Multicluster CI use snapshot version and not release version

---

frontend/src/components/IstioConfigPreview/EditorPreview.tsx
frontend/src/components/Kiosk/KioskActions.ts
frontend/src/components/Nav/Page/RenderComponentScroll.tsx
frontend/src/components/Nav/RenderPage.tsx
frontend/src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
frontend/src/pages/WorkloadDetails/WorkloadPodLogs.tsx
frontend/src/services/Api.ts

By default, Kiali hides the global scrollbar (`overflow: hidden` in global style) and fixes the height for pages that use RenderComponentScroll to force the scrollbar to appear. The issues is that hiding the global scrollbar is not possible when Kiali is embedded in other application (like Openshift Console). For this reason an environment variable `RENDER_SCROLLBAR` has been added to make the scrollbar in RenderComponentScroll optional. When `RENDER_SCROLLBAR` is false, the height is not fixed and the component does not force a new scrollbar to appear (the user will use the global scrollbar in this case).
This environment variable is not defined in standalone Kiali application (the value is always true).
Besides, heights of some components have been adjusted in …

Make the scrollbar in RenderComponentScroll optional

---

frontend/src/components/BreadcrumbView/BreadcrumbView.tsx
frontend/src/components/VirtualList/VirtualList.tsx
frontend/src/pages/IstioConfigList/FiltersAndSorts.ts

Fixes https://github.com/kiali/kiali/issues/6632
- Fix breadcrumb link issue for istio config type
- some cleanup: Fix type in type name, add some type safety, add some alphabetization, remove unnecessary vars
- Fix a sorting issue in VirtualList, when there are hidden columns

Fix breadcrumb link issue for istio config type

---

business/checkers/k8sgateway_checker.go
business/checkers/k8sgateways/multi_match_checker.go
business/checkers/k8sgateways/multi_match_checker_test.go

Issue https://github.com/kiali/kiali/issues/6633
Now the validation results will be consistent in lists and details of K8s Gateway objects.
Create 2 K8s Gateways with the same host and port combination. Warning will be shown for both of them.

Added missing cluster in K8s Gateway validations.

---

frontend/src/components/BreadcrumbView/BreadcrumbView.tsx
frontend/src/components/VirtualList/VirtualList.tsx
frontend/src/pages/IstioConfigList/FiltersAndSorts.ts

- Fix breadcrumb link issue for istio config type
- Fix a sorting issue in VirtualList, when there are hidden columns
Backport for https://github.com/kiali/kiali/issues/6632

[v1.73] Fix breadcrumb link issue for istio config type

---

.github/workflows/integration-tests-backend.yml
.github/workflows/integration-tests-frontend-multicluster.yml
.github/workflows/integration-tests-frontend.yml
.github/workflows/test-istio-version.yml
hack/istio/multicluster/env.sh
hack/istio/multicluster/install-primary-remote.sh
hack/setup-kind-in-ci.sh

This provides a new workflow that can be triggered manually. It will allow you to run the integration tests with any version of Istio you want (including even dev builds of Istio that have not been released, such as `1.20-dev`).
This will provide us the ability to see if Kiali can support older versions (or newer versions in development) of Istio.
You can test master branch or any other branch you select.

[CI] github workflow to test with specific istio version

---

hack/istio/install-istio-via-istioctl.sh
hack/istio/nativesiecars/install-native-sidecars-env.sh
models/pod.go

Issue https://github.com/kiali/kiali/issues/6130
Istio is supporting Native Sidecars since version 1.19.0.
When kubernetes env is created in SidecarContainers mode, and Istio is installed by 'ENABLE_NATIVE_SIDECARS=true', then Kiali is recognizing "istio-proxy" in a `initContainers` instead of `containers` of pods and not showing any warning that "Missing Sidecar".
Added a script to prepare `kind` environment and test on 'bookinfo'.
Run `./hack/istio/nativesiecars/install-native-sidecars-env.sh` and the env will be created and installed.
Run the proxy and connect to your local running Kiali from this PR sources.
No warning message about missing sidecars in Workloads/Apps/Services, Kiali behaves as usual when sidecars are installed.
More info in …

Support K8s Native Sidecars. Added a script to prepare env.

---

frontend/cypress/integration/featureFiles/kiali_alert.feature

Currently, there are 2 different CI jobs for front-end testing and there is also an enhancement in the backlog (#6609), which might extend the Status for external services related to multicluster. Because of this, I think it is suitable to duplicate this test.

Istio Status test for Multicluster

---

business/workloads.go
config/config.go
frontend/src/components/Ambient/AmbientBadge.tsx
frontend/src/config/ServerConfig.ts
frontend/src/pages/Overview/ControlPlaneBadge.tsx
frontend/src/pages/Overview/OverviewPage.tsx
frontend/src/pages/WorkloadDetails/WorkloadInfo.tsx
frontend/src/types/ErrorRate/__testData__/ErrorRateConfig.ts
frontend/src/types/Mesh.ts
frontend/src/types/ServerConfig.ts
frontend/src/types/__testData__/HealthConfig.ts
handlers/config.go
models/namespace.go
models/pod.go

Fixes #6522 
- Include some istio Ambient annotations as part of the config. 
- The labels used internally by Istio were just added as a constant. 
- Update the badge messages in the control plane to indicate that the ztunnel was detected in the control plane, independently as how the user installs it (If with the profile, helm chart, ...)

Include Ambient annotations in the config

---

hack/istio/install-testing-demos.sh
hack/run-integration-tests.sh

Reviewing the failures of these flakes, the test seems to happen when there are no traces yet, for some reason. 
There are no errors in the logs or the screenshot (related to error getting traces). 
There are another traces test, that runs latter, `See graph traces for productspage service details` and never seen it flake (At least when this test failed). 
It makes me think it could be related to something not ready yet in the environment. 
Fixes #6671

[Test Flake] See tracing info after selecting a trace

---

hack/run-integration-tests.sh

Fix the issue in run-integration-tests:
```
2023-10-05T11:28:45.4174734Z [INFO] Waiting for Kiali to have traces
2023-10-05T11:28:45.4323074Z curl: (3) URL using bad/illegal format or missing URL
```

Fix typo in var name

---

frontend/src/components/IstioWizards/WizardAnnotations.tsx

https://github.com/kiali/kiali/issues/6676
Deleting a numeric key in map does not reorder the keys, so recreating a map.

Recreate map with annotations after deleting a numeric key

---

kubernetes/client_factory.go
kubernetes/client_factory_test.go

fix condition when kiali uses user token instead kiali SA
We should use user token only when both condition is true:
1) Auth strategy isn't anonymous
2) OpenID RBAC isn't disabled
[Bug after v1.72.0 release with oAuth2 strategy when DisableRBAC is true](https://github.com/kiali/kiali/issues/6677)

fix condition when kiali uses user token instead kiali SA

---

tracing/otel/model/converter/converter.go

Fixes #6693 
Now the span data is complete: 
No incomplete span data message:

Convert kind span data

---

business/istio_status.go
config/config.go

Issue https://github.com/kiali/kiali/issues/6609
Now it is possible to check Istio component status on multiple clusters,
just add to any component's config the new `is_multicluster: true` (by default 'false') and the component status check will check the existence of the particular component in all clusters.
```
istio:
component_status:
components:
- app_label: istio-eastwestgateway
is_core: true
is_proxy: true
is_multicluster: true
namespace: ''
```

Component status check in multicluster mode

---

Makefile

Fixes https://github.com/kiali/kiali/issues/6716 
https://github.com/kiali/kiali/blob/master/README.adoc#upgrading-go 
```
go mod tidy -v
go: downloading gopkg.in/check.v1 v1.0.0-20201130134442-10cb98267c6c
go: downloading go.uber.org/goleak v1.2.1
go: downloading github.com/mwitkow/go-conntrack v0.0.0-20190716064945-2f068394615f
go: downloading github.com/armon/go-socks5 v0.0.0-20160902184237-e75332964ef5
go: downloading github.com/onsi/ginkgo/v2 v2.9.1
go: downloading google.golang.org/appengine v1.6.7
go: downloading github.com/onsi/gomega v1.27.4
go: downloading github.com/golang/glog v1.1.0
go: downloading github.com/kr/pretty v0.3.0
go: downloading github.com/rogpeppe/go-internal v1.10.0
go: downloading github.com/kr/text v0.2.0
go: downloading github.com/jpillora/backoff v1.0.0
go: …
```

Update go version 1.20.10

---

.github/workflows/build-backend.yml
Makefile

Fixes https://github.com/kiali/kiali/issues/6716
```
go mod tidy -v
go: downloading google.golang.org/appengine v1.6.7
go: downloading gopkg.in/check.v1 v1.0.0-20200227125254-8fa46927fb4f
go: downloading golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1
go: downloading github.com/mwitkow/go-conntrack v0.0.0-20190716064945-2f068394615f
go: downloading github.com/google/uuid v1.1.2
go: downloading github.com/armon/go-socks5 v0.0.0-20160902184237-e75332964ef5
go: downloading github.com/elazarl/goproxy v0.0.0-20180725130230-947c36da3153
go: downloading github.com/onsi/ginkgo v1.14.0
go: downloading github.com/onsi/gomega v1.10.1
go: downloading github.com/jpillora/backoff v1.0.0
go: downloading github.com/niemeyer/pretty v0.0.0-20200227124842-a10e7caefd8e
go: downloading …
```

[backport 1.65] Update go version 1.20.10

---

business/checkers/sidecars/egress_listener_checker.go

Issue https://github.com/kiali/kiali/issues/6010
Unable to reproduce, the fix is just to avoid potential runtime error with panic.
Probably this will never happen.

Avoid potential runtime error

---

business/proxy_status.go

Found missing a `cluster` in reading namespaces while checking https://github.com/kiali/kiali/issues/6711
However the original issue could not be reproduced.

Read Namespaces per cluster

---

hack/istio/install-istio-via-istioctl.sh

Increases the sampling rate for tracing to 100. This will hopefully fix #6671 where traces are not being seen because the env is very slow. The kiali traffic generator that creates traffic for the e2e tests probably doesn't produce enough requests to overwhelm the jaeger deployment in the testing environment but the sampling rate can be lowered in the future if that happens.

[hack] When installing via istioctl, emit all traces

---

business/mesh_test.go
frontend/cypress/integration/featureFiles/app_details_multicluster.feature
frontend/cypress/integration/featureFiles/service_details_multicluster.feature
frontend/cypress/integration/featureFiles/workloads_details_multicluster.feature
kubernetes/cache/kube_cache.go

Issue https://github.com/kiali/kiali/issues/6682
For services loading from kube cache, does not mater local or remote, the label selector was filtering out the services which did not have `version` label selector.
In an contrary, the registry loading was loading all services then filtering by selector.
This was causing an issue for remote cluster services loaded for workload. The selector which contains `version` for workload was filtering out all services from cache. The local cluster's workload's services were loading from registry and were fine. Which was correct but still an Inconsistency with remote ones. 
Now when selector is provided for loading services from kube cache, it lists all services then filters out the selector matched ones, similar to loading from registry.
When no …

Apply filter by service selector after loading from kube cache

---

frontend/src/components/TrafficList/TrafficDetails.tsx
frontend/src/services/GraphDataSource.ts

https://github.com/kiali/kiali/issues/6712
Remote cluster's App Details and Service Details pages Traffic tab pages sent 'clusterName' params.

Added missing cluster param in App and Service traffic.

---

kiali.go
kubernetes/client.go
kubernetes/client_factory.go
kubernetes/client_factory_test.go

Previously the auto-detect of the cluster name was skipped entirely when `config.InCluster = false`. Kiali can still auto-detect the cluster name in this case so there's no reason to skip it.
Related to #6742

Fix auto-detect of istio cluster name for "remote kiali" setup

---

.gitignore
frontend/src/components/CytoscapeGraph/graphs/GraphStyles.ts
frontend/src/config/Icons.ts
graph/telemetry/istio/appender/istio_details.go

Fixes #6740 
As far as I can tell this has been broken since Kiali v1.69, due to the multi-cluster work in https://github.com/kiali/kiali/pull/6209.  That is a server-side problem.  But then there was a second problem introduced with the PF5 update, which changed the name of the icon we are using for our gateway badge.
We should backport this to 1.73 (careful of the icon name changes, those may not be necessary).

Fix issues with gateway-badging in graph

---

frontend/src/components/Time/DateTimePicker.tsx

z-index of datepicker has been increased to overlap Metric charts.
Fixes #6781

Increase z-index of datepicker to overlap Metric charts

---

business/istio_certs.go
business/istio_validations.go
business/istio_validations_test.go
business/mesh.go
business/mesh_test.go
business/namespaces.go
business/tls.go

Uses: `conf.ExternalServices.Istio.ConfigMapName` without adding the rev tag when it is set and not the default `istio`.
Fixes #6669

Fix double revision in istio configmap name

---

graph/options.go
graph/telemetry/istio/appender/appender.go
graph/telemetry/istio/appender/health_test.go
graph/telemetry/istio/appender/istio_details.go
graph/telemetry/istio/appender/mesh_check.go
graph/telemetry/istio/appender/mesh_check_test.go
graph/telemetry/istio/appender/outsider.go
graph/telemetry/istio/appender/service_entry_test.go

Fixes https://github.com/kiali/kiali/issues/6772
Make sure mesh_check appender only tries to check nodes in accessible namespaces. Otherwise the fetch of workload information will fail.

Make sure mesh_check appender only tries to check nodes in accessible namespaces

---

hack/istio/multicluster/deploy-kiali.sh
hack/setup-kind-in-ci.sh

Backport of #6755 to version 1.73. There are more changes than in referenced PR because there are previous PRs modifying this file that have not been backported. For this reason I have pushed the latest version of the hack script into v1.73.
Closes #6750

[1.73] Add absolute script dir path in setup-kind-ci.sh script (#6755)

---

make/Makefile.operator.mk

I missed this spot when I did https://github.com/kiali/kiali/issues/6790
This make target runs the operator locally - useful for dev debugging. It now needs to pass in the correct watches file.
This doesn't affect anything other than a make target that is used during development.

[make] pass in correct watches file when using make target run-operator

---

kubernetes/client_factory.go
kubernetes/client_factory_test.go

Backport of #6679 to v1.73.
Fixes #6677

[1.73] Backport rbac fix

---

frontend/src/pages/AppDetails/AppDetailsPage.tsx
frontend/src/pages/AppList/AppListPage.tsx
frontend/src/pages/Graph/SummaryPanelNamespaceBox.tsx
frontend/src/pages/Overview/OverviewPage.tsx
frontend/src/pages/Overview/__tests__/__snapshots__/OverviewPage.test.tsx.snap
frontend/src/pages/ServiceList/ServiceListPage.tsx
frontend/src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
frontend/src/pages/WorkloadList/WorkloadListPage.tsx
frontend/src/services/Api.ts
frontend/src/services/GraphDataSource.ts
frontend/src/services/__mocks__/Api.ts
frontend/src/types/App.ts
frontend/src/types/AppList.ts
frontend/src/types/Graph.ts
frontend/src/types/Health.ts
frontend/src/types/IstioConfigDetails.ts
frontend/src/types/IstioConfigList.ts
frontend/src/types/IstioObjects.ts
frontend/src/types/MetricsOptions.ts
frontend/src/types/ServiceInfo.ts
frontend/src/types/ServiceList.ts
frontend/src/types/Workload.ts

API getNamespaceMetrics is modified to send clusterName query param instead of cluster:
To avoid the use of cluster param in the future, I have added types to query params of all API methods (too many anys in Api.ts). Besides, cluster should be a parameter in the API method, not an attribute in the query params type.
For this reason I have removed cluster attribute from IstioMetricsOptions interface:
```
export interface IstioMetricsOptions extends MetricsQuery {
direction: Direction;
filters?: string[];
requestProtocol?: string;
reporter: Reporter;
}
export const getNamespaceMetrics = (namespace: string, params: IstioMetricsOptions, cluster?: string) => {
const queryParams: QueryParams<IstioMetricsOptions> = { ...params };
if (cluster) {
queryParams.clusterName = …
```

Avoid cluster in API query params, only clusterName

---

frontend/cypress/integration/featureFiles/app_details_multicluster.feature
frontend/cypress/integration/featureFiles/service_details_multicluster.feature
frontend/cypress/integration/featureFiles/workloads_details_multicluster.feature
frontend/src/components/TracingIntegration/TracesFetcher.ts
frontend/src/types/TracingInfo.ts
handlers/tracing.go
tracing/client.go
tracing/jaeger/http_client.go
tracing/jaeger/model/types.go
util/maps.go
util/maps_test.go

Issue https://github.com/kiali/kiali/issues/6710
Follow up after discussion on https://github.com/kiali/kiali/pull/6749
In a multi-cluster primary-remote mode, when Jaeger is configured to have Cluster ID [(Multi-cluster Setup)](https://kiali.io/docs/configuration/multi-cluster/#setup) and the Istio installation includes the [workaround for Telemetry setup](https://github.com/istio/istio/issues/35750#issuecomment-1165988761).
The Jaeger traces are including a `cluster` tag.
As in the multi-cluster env, the Tracing service supposed to be setup at once and during the installation, then it will be configured to support traces per cluster. This is the expected behavior, otherwise all Traces will be duplicated per service name which exists in all clusters.
What is done: 
In Multi-cluster mode, …

Filter traces by cluster, show warning otherwise

---

hack/crc-openshift.sh

This option is necessary if you want CRC to install OpenShift with its own Prometheus server.
This PR is needed before you can use the new hack script to configure everything else (see https://github.com/kiali/kiali/pull/6822)

[hack] flag for enabling monitoring so we can have prometheus in the cluster

---

tracing/client.go
tracing/jaeger/grpc_client.go
tracing/jaeger/http_client.go
tracing/tempo/http_client.go

Part of https://github.com/kiali/kiali/issues/6578
Creates a grpc interface that will allow to have multiple gRPC client implementations (Now for Jaeger, next for Tempo). 
Ref. https://github.com/kiali/kiali/pull/6758

Refactor grpc client

---

hack/use-openshift-prometheus.sh

Some docs to help with implementing this:
1. https://docs.openshift.com/container-platform/4.14/service_mesh/v2x/ossm-observability.html#ossm-integrating-with-user-workload-monitoring_observability (this doesn't work fully when using upstream Istio, trying to find out what is missing)
2. https://docs.openshift.com/container-platform/4.14/rest_api/monitoring_apis/servicemonitor-monitoring-coreos-com-v1.html
3. https://docs.openshift.com/container-platform/4.14/rest_api/monitoring_apis/podmonitor-monitoring-coreos-com-v1.html
4. https://docs.openshift.com/container-platform/4.14/monitoring/configuring-the-monitoring-stack.html#preparing-to-configure-the-monitoring-stack
5. https://docs.openshift.com/container-platform/4.14/monitoring/enabling-monitoring-for-user-defined-projects.html
Test …

[hack] script to set up openshift prometheus for istio monitoring

---

hack/run-kiali-config-template.yaml
hack/run-kiali.sh

Adapt standard kiali configuration template to latest changes in tracing:
- Add tracing provider: `${TRACING_APP}`
- Add tracing prefix for jaeger client: `/jaeger`
- Disable `use_grpc` by default in tracing
Fixes #6808

Fix tracing config in run-kiali template

---

frontend/cypress/integration/common/hooks.ts
frontend/cypress/integration/common/wizard_request_routing.ts
frontend/cypress/integration/featureFiles/wizard_request_routing.feature

A few of the implemented gherkin scenarios for MC which have been previously marked with the @skip tag. 
I have also added a hook to install the necessary CRDs if not detected on the remote cluster. 
I am not sure, if we want to test with enabled or disabled CRDs, but we can always alter the execution order later

Cypress implementation of the Request Routing tests for the Multicluster setup 

---

frontend/src/components/Refresh/RefreshButton.tsx
frontend/src/pages/Graph/GraphToolbar/GraphToolbar.tsx

Add refresh delay when clicking Refresh Button to avoid multiple refresh in a very short period of time.
Besides, I have converted the Refresh button component in a React Hook.
Fixes #6714.

Add refresh delay to avoid multiple refresh in a very short period of time

---

hack/setup-kind-in-ci.sh

Install compatible Istio versions depending on target branch when performing integration tests.
Compatible Istio versions are obtained from:
https://kiali.io/docs/installation/installation-guide/prerequisites/#version-compatibility
Compatible Kubernetes versions are obtained from:
https://istio.io/latest/docs/releases/supported-releases/
#6858

Install compatible Istio versions on integration tests

---

tracing/client.go
tracing/otel/model/types.go
tracing/tempo/http_client.go
util/slice.go

Fixes #6710 (Tempo)
For some reason, telemetry is not adding the cluster tag. But without this fix, Tempo search is not working, as the cluster tag is included and the search is not returning any result.

Use cluster tag for Tempo

---

kubernetes/filters_test.go
kubernetes/types.go
tests/data/service_data.go
tests/data/service_entry_data.go

Issue https://github.com/kiali/kiali/issues/6856
The RegistryService since Istio 1.20, is returned from Istio reigstry with "map[string]struct{}" value for 'ExportTo' field, instead of 'map[string]bool' previously.
This was causing errors when we had a ServiceEntry with "exportTo" attribute, this was generating a Service which was set in ServicesRegistry.
All the other Istio Config object types are not touched with this issue, as the issue is in Service Registry results parsing.
Added exportTo value int ServiceEntry test data for e2e tests.

Registry Service ExportTo is now map[string]struct{}.

---

kubernetes/filters_test.go
kubernetes/types.go
tests/data/service_data.go
tests/data/service_entry_data.go

Cherry pick of https://github.com/kiali/kiali/pull/6866

[v1.76] Registry Service ExportTo is now map[string]struct{}. (#6866)

---

kubernetes/filters_test.go
kubernetes/types.go
tests/data/service_data.go
tests/data/service_entry_data.go

Cherry pick of https://github.com/kiali/kiali/pull/6866

[v1.77] Registry Service ExportTo is now map[string]struct{}. (#6866)

---

hack/setup-kind-in-ci.sh

Install compatible Istio version 1.17 for Kiali 1.65 when performing integration tests.
Compatible Istio versions are obtained from:
https://kiali.io/docs/installation/installation-guide/prerequisites/#version-compatibility
Compatible Kubernetes versions are obtained from:
https://istio.io/latest/docs/releases/supported-releases/
#6858

[1.65] Install compatible Istio versions on integration tests

---

frontend/src/components/Health/HealthIndicator.tsx
frontend/src/components/Health/Helper.ts
frontend/src/components/Pf/PfBadges.tsx
frontend/src/pages/Graph/SummaryLink.tsx
frontend/src/pages/Graph/SummaryPanelAppBox.tsx
frontend/src/pages/Graph/SummaryPanelNode.tsx
frontend/src/styles/GlobalStyle.ts

Realign healthy icon in summary panel graph next to application/service badge link instead of previous label.
Previous:
Now:
I have removed `health` label in order to be consistent with other parts of Kiali where health indicator is placed next to application/service name (e.g. detail info):
Besides, I have reduced a bit the top padding of kebab toggle menu in graph and overview:
Fixes #6884

Realign healthy icon in summary panel graph

---

hack/istio/multicluster/split-bookinfo.sh

Fixes https://github.com/kiali/kiali/issues/6780

Adding traffic shifting rules to enforce traffic to all west's reviews v2 and v3 workloads

---

frontend/.eslintrc_precommit
frontend/.husky/pre-commit
frontend/package.json
frontend/yarn.lock

I have configured `yarn eslint:precommit` command with different eslint config file to apply new rules only to committed files.
For the moment the new rules I have applied are:
- "no-var": Use const or let instead of var
- "prefer-template": Use template interpolation instead of string literals (https://github.com/kiali/kiali/issues/6736)
- "prefer-arrow-callback": Use arrow functions instead of normal functions
- "@typescript-eslint/no-inferrable-types": Avoid typing the type if a default value is set (to reduce verbosity)
- "@typescript-eslint/explicit-function-return-type": Return types have to be specified in functions
- "@typescript-eslint/explicit-module-boundary-types": Method types have to be specified in functions
Besides, I have updated Husky (library …

New eslint config for precommit linting

---

frontend/.eslintrc_precommit
frontend/src/components/Pf/PfColors.tsx
frontend/src/pages/WorkloadDetails/WorkloadPodLogs.tsx

I have removed black background of workload log checkboxes that makes the look and feel a bit weird. In order to maintain the legend of integrated logs, I have change the color of the checkbox itself with `accent-color` CSS class. Also I have adapted log colors to work fine both in light and dark themes and adjust some margins and paddings of log lines.
For first application container I have selected blue color. These are the other colors selected for multiple application containers:
Besides, I have added new eslint rule `@typescript-eslint/member-ordering` to force type and interface properties to be sorted alphabetically and modify `@typescript-eslint/explicit-function-return-type` to allow expressions (probably more rules will have to be adjusted in the next PRs …

Improve appearance of workload log checkboxes

---

frontend/src/pages/GraphPF/GraphPFElems.tsx
frontend/src/pages/GraphPF/components/NodeDecorator.tsx

Fixes #6926 
A fix is introduced because decorators were failing due to a change introduced in PF5.

Fixed graph node decorators in PF5

---

hack/istio/install-bookinfo-demo.sh

There may not be an ingress installed in istio-system - if not, have bookinfo demo traffic gen go directly to the productpage route on openshift

[hack] if there is no ingress, have traffic gen use productpage route

---

hack/istio/install-bookinfo-demo.sh

Note that this fixes a bug in the hack script - it was trying to expose the openshift routes before the services even existed. This also fixes that problem.

[hack] on OpenShift when no ingress gateway is installed, wait for productpage route

---

business/checkers/k8shttproutes/no_host_checker.go
business/checkers/k8shttproutes/no_host_checker_test.go
models/istio_validation.go
tests/integration/tests/config_validations_test.go

Issue https://github.com/kiali/kiali/issues/6948
Before: Kiali was accepting FQDN in K8sHTTPRoute config's 'backendRef.name' as a Service name, but Gateway API expects it to be 'name' only. A bug!
Now: Error `KIA1402` will be extended to be shown also in FQDN formatted Service name (even if FQDN is correct). Error message is changed to be more clear that not a `host` is expected but `Service name`.
However, Kiali requires `istio_identity_domain: svc.cluster.local` set in `kiali` configmap, or not set that property at all to take the default.

Include FQDN in error list for K8s HTTPRoute backend ref service name.

---

hack/istio/functions.sh
hack/istio/install-sleep-demo.sh
hack/istio/install-testing-demos.sh

Fix autoinjection for `bookinfo` and `sleep` demo projects when using with OSSM
Due to this change https://github.com/kiali/kiali/commit/997f5440113462d0d6fc41e1fbde66e72ad75b31 , the bookinfo script doesn't use `ENABLE_INJECTION` anymore, however, it is needed in `prepare_maistra` function.
Also, `ISTIO_NAMESPACE` env is needed in `prepare_mainstra` function so it was added to `install-sleep-demo.sh` script. (in version 1.65, the sleep installation was a part of `install-testing-demos.sh` where the ENV was available) 
https://issues.redhat.com/browse/OSSM-5564

[OSSM-5564][hack] Fix install testing demo script to support OSSM 2.5

---

business/istio_status.go
business/istio_status_test.go

fixes: https://github.com/kiali/kiali/issues/6966

for health check, use prom healthy endpoint by default

---

business/istio_certs.go
business/istio_validations.go
business/istio_validations_test.go
business/mesh.go
business/mesh_test.go
business/namespaces.go
business/tls.go

backport fix for issue https://github.com/kiali/kiali/issues/6669
(cherry picked from commit edc574d01d9d70222de1b86b82f1035e3e68b3d4 which was PR https://github.com/kiali/kiali/pull/6675)

[v1.73] Fix double revision in istio configmap name

---

business/istio_config.go
business/istio_validations.go
business/services.go
frontend/src/components/Pf/PfBadges.tsx
frontend/src/components/VirtualList/Config.ts
frontend/src/pages/IstioConfigList/FiltersAndSorts.ts
frontend/src/pages/IstioConfigList/__tests__/IstioConfigListComponent.test.ts
frontend/src/types/IstioConfigDetails.ts
frontend/src/types/IstioConfigList.ts
frontend/src/types/IstioObjects.ts
frontend/src/utils/IstioConfigUtils.ts
kiali_internal_api.md
kubernetes/cache/kube_cache.go
kubernetes/kubernetes.go
kubernetes/types.go
models/istio_config.go
tests/integration/assets/bookinfo-k8sgateways.yaml
tests/integration/tests/istio_config_test.go

Issue https://github.com/kiali/kiali/issues/6918
Added support to list and show YAML details of K8s Gateway API "ReferenceGrant" object.
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
name: referencegrant
spec:
from:
- group: "gateway.networking.k8s.io"
kind: HTTPRoute
to:
- group: ""
kind: Service
```

K8sReferenceGrants support in Istio Config List/Details pages

---

log/log.go

Correct log level information can be found in zerolog.GlobalLevel(), not from log.Logger.GetLevel()
Fixes #6964

Retrieve log level from correct source

---

tracing/client.go
tracing/client_test.go
tracing/jaeger/grpc_client.go
tracing/jaeger/http_client.go
tracing/jaeger/model/types.go

Ref. #6844
https://github.com/kiali/kiali/issues/6844#issuecomment-1854504377
In order to get a sample of the traces from different times and a limited number of results, in some calls (Like the node graph for traces), splits the search query in 10, this is, will perform up to 10 concurrent requests to the tracing platform. 
When there are no cluster tags, each query is repeated, which in a busy environment can be translated in a worst performance. This PR tries to get this information when the tracing client is created and avoid the duplication of calls to the backend.

Use ignorecluster global for tracing

---

frontend/src/pages/WorkloadDetails/WorkloadPodLogs.tsx

Fix of two scrollbar issues in workload logs:
- Horizontal scrollbar does not appear in Firefox:
React Virtualized List component has different overflow style depending on browser:
- Chrome: `overflow: auto`
- Firefox: `overflow: hidden auto`
Setting the oveflow style to `auto !important` makes the trick.
- Double scrollbar in Chrome when user zooms in:
Extra `overflow` style present in the List component. 
Fixes #6982

Fix Workload Logs scrollbar issue

---

business/tracing.go
tracing/tempo/http_client.go

For some reason, it looks like Tempo returns more than the limit results. 
It limits the number of results and splits the query when necessary. 
It looks like with increasing the number of results supports the load. 
With this change, with Tempo: 
- No more results than the limit are returned. 
- Traces are distributed between the graph. 
Ref. #6844

Update trace logic for Tempo lo limit the number of results

---

business/checkers/k8shttproute_checker.go
business/checkers/k8shttproutes/no_host_checker.go
business/checkers/k8shttproutes/no_host_checker_test.go
business/istio_validations.go
kubernetes/host.go
tests/data/k8sgateway_data.go

Issue https://github.com/kiali/kiali/issues/6918
In K8s HTTPRoute Backend reference (https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.BackendObjectReference), when the Namespace where Service is referenced differs from the local namespace, where the HTTPRoute is created, then a ReferenceGrant object is required to reference the Service namespace and local namespace.
Now: KIA1402 validation is modified to consider ReferenceGrant objects when those 2 namespaces are different. 
How to test it:
Apply K8s Gateway API CRD v1.0.0
Create HTTPRoute and ReferenceGrant.
```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
name: inbookinfo
spec:
rules:
- matches:
- path:
type: Exact
value: "/bar"
backendRefs:
- name: kiali
namespace: …
```

Consider ReferenceGrant in HTTPRoute Service validation KIA1402

---

business/layer.go
business/tracing.go
kiali.go
server/server.go
status/status.go
tracing/client.go
tracing/client_test.go

When tracing fails to initialize, the server should still startup because tracing is not an essential component.

Initialize tracing client asynchronously

---

frontend/src/components/Ambient/AmbientBadge.tsx
frontend/src/pages/Overview/OverviewPage.tsx

Remove extra padding and fix truncate on long namespaces in Overview page cards
#6998

Remove extra padding and fix truncate on long namespaces

---

business/layer.go
business/mesh.go
business/mesh_test.go
business/services.go
config/config.go
frontend/src/actions/__tests__/ClusterAction.test.ts
frontend/src/config/ServerConfig.ts
frontend/src/pages/Graph/__tests__/SummaryLink.test.tsx
frontend/src/pages/Graph/__tests__/SummaryPanelNode.test.tsx
frontend/src/types/Mesh.ts
graph/telemetry/istio/appender/health_test.go
handlers/config.go
handlers/mesh.go
handlers/namespaces.go
handlers/utils.go
kiali.go
kubernetes/cache/kube_cache.go
kubernetes/cluster_secret.go
routing/router.go
routing/router_test.go
routing/routes.go
server/server.go
server/server_test.go
tests/integration/tests/clusters_test.go
tests/integration/tests/testing.go
tests/integration/utils/kiali/instance.go
tests/integration/utils/kiali/kiali_client.go
tests/integration/utils/kube/kube_client.go

This change lets you manually specify a cluster in the kiali config that there is no remote secret for. This cluster is considered "inaccessible" meaning that Kiali won't try to connect to it and the frontend won't consider it for the "multi-cluster mode" e.g. there won't be a cluster column when there's one accessible cluster and one inaccessible cluster.
To test:
1. Create two clusters. You can use: `hack/run-integration-tests.sh --test-suite frontend-multi-primary --setup-only true`.
2. Deploy kiali on both clusters including the "west" cluster. `./hack/istio/multicluster/deploy-kiali.sh --single-kiali false --cluster1-context kind-east --cluster2-context kind-west --kiali-auth-strategy anonymous --manage-kind true --kiali-use-dev-image true`
3. Add the "east" …

Add separate cluster for configured kiali instance

---

.github/workflows/test-images-creator.yml
.github/workflows/test-images-release.yml
.github/workflows/test-images-update-latest.yml
Makefile
make/Makefile.container.mk

Adding a workflow (`tests-images-creator.yml`) for building and pushing integration and cypress test images (both at once or a particular one). The workflow can be run from a different workflow or manually (e.g. for manually rebuilding a particular tag).
1. The workflow is called from `tests-images-update-latest.yml` job, which is watching folders related to tests. If something is pushed into those folders, the job detects in which folders the changes were done and rebuilds the cypress, integration, or both test images accordingly. So the `latest` tag will always contain the latest changes in test suites.
2 In addition, the workflow is called whenever a new tag is created (e.g. after release) by `tests-images-release.yml`. In that case, the new integration and …

[OSSM-5306][OSSM-5307] Add building tests images workflow into pipeline

---

frontend/src/pages/Graph/GraphToolbar/GraphSettings.tsx

Display rank options in the graph vertically:
Fixes #6961

Fix rank options in the graph

---

business/checkers/k8sreferencegrants/namespace_checker.go
business/checkers/k8sreferencegrants/namespace_checker_test.go
business/checkers/k8sreferencegrants_checker.go
business/checkers/k8sreferencegrants_checker_test.go
business/istio_validations.go
models/istio_validation.go
tests/integration/assets/bookinfo-k8sreferencegrants-from-namespaces.yaml
tests/integration/tests/config_validations_test.go

Issue https://github.com/kiali/kiali/issues/6918
An Error severity message is added for "Spec.From.Namespace" field of "K8sReferenceGrant" object checking if namespace exists: "KIA1601 Namespace is not found or is not accessible"

Added new check KIA1601 for ReferenceGrant

---

hack/test-pull-request.sh

A script that lets you test a PR (or set of PRs, in case it involves kiali server and kiali operator changes).
Run `hack/test-pull-request.sh --help` for options.
You must have a cluster installed already, and you must be connected to/logged into that cluster. You also need Istio already installed for Kiali to work. Because this script builds the server image from source, you need `go` installed and in your $PATH (to build the backend), as well as `yarn` (to build the frontend).
You can use this script to build and deploy PRs by specifying the fork name for the kiali repo and kiali-operator repo (the default is kiali for both but, for example, you can use my forks by passing in my github username .. so `-kf jmazzitelli` will pull [my fork of kiali …

[hack] script that can deploy server and/or operator built from PR branches and installed via OLM

---

frontend/cypress/integration/common/apps.ts
frontend/cypress/integration/common/navigation.ts
frontend/cypress/integration/featureFiles/app_details_multicluster_graph.feature
frontend/cypress/integration/featureFiles/workloads_details_multicluster_graph.feature

Implements the rest of the multi-cluster detail page definitions for multi-cluster. There's one scenario that is skipped since that will require much more work outside cypress to get working properly. Created this issue is a followup for that one: https://github.com/kiali/kiali/issues/7021.
Fixes #6475

[e2e] - Implement the rest of the multi-cluster details pages 

---

business/mesh.go
business/mesh_test.go
config/config.go
tests/integration/tests/clusters_test.go

Removes the `inaccessible_clusters` field in favor of the existing `clusters` field. `clusters` is already used by the operator and there's no need to have both `clusters` and `inaccessible_clusters`. Also removes the `accessible` field from the `cluster` object. Instead specifying a cluster without a secret name will automatically mark the cluster as inaccessible.
To test:
1. Create two clusters. You can use: `hack/run-integration-tests.sh --test-suite frontend-multi-primary --setup-only true`.
2. Deploy kiali on both clusters including the "west" cluster. `./hack/istio/multicluster/deploy-kiali.sh --single-kiali false --cluster1-context kind-east --cluster2-context kind-west --kiali-auth-strategy anonymous --manage-kind true --kiali-use-dev-image true`
3. Add …

Remove accessible field and rename inaccessible_clusters

---

config/config.go
observability/tracing.go
observability/tracing_test.go
server/server_test.go

Remove Jaeger exporter.
Example to test: 
```
server:
observability: 
tracing: 
collector_url: "localhost:4318"
enabled: true
protocol: "http"
tls_enabled: false
tls_config: 
skip_verify: true
ca_name: "/tmp/tls.crt"
```
I've included some changes in the observability section from the configuration. As there is just one collector type, the option `collector_type` was removed. Because of this, the `otel` configuration section was renamed to `tls_config`, and the `protocol` and `tls_enabled` was moved to the `tracing` section. 
I have in mind to minimize this CR changes, but, I think this reorganization makes more sense and probably the new settings (With the collector_type) were not used a lot yet. 
Fixes #6908

Remove Jaeger Exporter

---

kubernetes/cache/kube_cache.go

Issue https://github.com/kiali/kiali/issues/7006
Make sure that `k8sgatewayLister` exists before calling it, to skip 'nil' errors.
This can happen when K8s GW CRDs are creatd, but the cache it not reloaded.

Check K8sGatewayLister init.

---

frontend/src/pages/Overview/OverviewPage.tsx

Modify overview background style to cover whole window (only affects OSSMC)
**Steps to test PR**
This PR does not affect Kiali, only OSSMC.
1. (Optional) Check that Kiali overview page looks fine
2. Copy `OverviewPage.tsx file` into local OSSMC repository (folder `plugin/src/kiali/pages/Overview/OverviewPage.tsx`)
3. Run OSSMC plugin locally and check that PR fixes the issue.
Fixes https://github.com/kiali/openshift-servicemesh-plugin/issues/237

[v1.73] OSSMC - Make overview background fulfill whole window

---

frontend/src/components/DetailDescription/DetailDescription.tsx
frontend/src/components/Pf/PfBadges.tsx
frontend/src/pages/Graph/SummaryPanelNode.tsx
frontend/src/types/Graph.ts
graph/config/cytoscape/cytoscape.go
graph/meta.go
graph/telemetry/istio/appender/ambient.go
graph/telemetry/istio/appender/ambient_test.go
graph/telemetry/istio/appender/mesh_check.go

It looks like the graph generation is not looking at the labels of the workload, it is looking at the [source_canonical_service](https://github.com/kiali/kiali/blob/master/graph/telemetry/istio/istio.go#L280) to fill the fill the app field. 
That's the reason to include the waypoint check in the frontend code. 
Ref. https://github.com/kiali/kiali/issues/7022

Hide application link for waypoint in graph

---

frontend/src/components/IstioActions/IstioActionsNamespaceDropdown.tsx
frontend/src/pages/IstioConfigNew/K8sReferenceGrantForm.tsx

Second PR from https://github.com/kiali/kiali/issues/7025 (second subtask)
Having this small feature separately from the main PR https://github.com/kiali/kiali/pull/7033
Plus a small fix, K8sReferenceGrant action is disabled when K8s Gateway API is not enabled:

Reference Grant form: GRPC/TCP/TLS Routes

---

business/authentication/header_auth_controller.go
business/authentication/openid_auth_controller.go
business/dashboards.go
business/dashboards_test.go
business/istio_status.go
handlers/authentication.go
handlers/authentication_test.go
handlers/dashboards.go
kubernetes/cache/cache.go
kubernetes/cache/cache_test.go
kubernetes/cache/kube_cache.go
kubernetes/client_factory.go
kubernetes/client_factory_test.go
kubernetes/cluster_secret.go
kubernetes/cluster_secret_test.go
kubernetes/kubetest/mock.go
kubernetes/testdata/sa-token.yaml
kubernetes/token.go
kubernetes/token_test.go
prometheus/client.go
status/discover.go
status/versions.go

fixes: https://github.com/kiali/kiali/issues/6924

use built-in SA token refresh functionality within client-go

---

config/config.go
tests/integration/tests/clusters_test.go
tests/integration/tests/no_istiod_test.go
tests/integration/tests/remote_istiod_test.go
tests/integration/utils/kiali/instance.go
tests/integration/utils/kube/kube_client.go

Fix clusters test for operator deployments and cleanup e2e tests by using `kiali.Instance` to manage config.

Fix clusters e2e test for operator deployments

---

frontend/cypress/integration/common/istio_config.ts
frontend/cypress/integration/featureFiles/istio_config.feature
frontend/cypress/integration/featureFiles/sidecar_injection.feature

Cherry pick of https://github.com/kiali/kiali/pull/7056
OSSM-4460
Add page refresh to allow time for sidecar injection to happen and be reflected in the UI.  Note that this introduces a delay of a few seconds because the refresh button is temporarily hidden by a message center toast.
Also, rename one action to be more generic, for re-use.

[v1.73] Try to resolve cypress fails in sidecar_injection feature

---

tests/integration/utils/kiali/instance.go

Waits for old kiali pod to be deleted before continuing with the test.

e2e tests - Wait for deployment replicas to fully match spec

---

business/controlplane_monitor.go

Registry.IstiodURL by default can have an empty value, so need to ignore it and go on with port forwarding.

Add a check for empty IstiodURL.

---

business/checkers/destination_rules_checker.go
business/checkers/service_entry_checker.go
business/checkers/virtual_service_checker.go
business/istio_validations.go
business/istio_validations_test.go
handlers/istio_config.go
models/namespace.go
tests/data/validations/exportto/cns/dr_bookinfo1_to_2_3.yaml
tests/data/validations/exportto/cns/dr_bookinfo1_to_this.yaml
tests/data/validations/exportto/cns/dr_bookinfo2_to_1.yaml
tests/data/validations/exportto/cns/dr_bookinfo2_to_this.yaml
tests/data/validations/exportto/cns/dr_bookinfo3.yaml
tests/data/validations/exportto/cns/dr_bookinfo3_to_2.yaml
tests/data/validations/exportto/cns/dr_bookinfo3_to_all.yaml
tests/data/validations/exportto/cns/dr_bookinfo3_to_wrong.yaml
tests/data/validations/exportto/cns/se_bookinfo1_to_2_3.yaml
tests/data/validations/exportto/cns/se_bookinfo1_to_this.yaml
tests/data/validations/exportto/cns/se_bookinfo2_to_1.yaml
tests/data/validations/exportto/cns/se_bookinfo2_to_this.yaml
tests/data/validations/exportto/cns/se_bookinfo3_to_2.yaml
tests/data/validations/exportto/cns/se_bookinfo3_to_all.yaml
tests/data/validations/exportto/cns/se_bookinfo3_to_wrong.yaml

Issue https://github.com/kiali/kiali/issues/6879
In a case of Ambient mesh, the `ExportTo` field of several Istio config objects are ignored, and the Object is validated only in own namespace scope. Affected configs: VirtualService, DestinationRule, ServiceEntry.
Added tests, but in fact made tests disabled because the `layer.IstioConfig` is not reset from test to test.

Ignore ExportTo for Ambient mesh

---

tests/integration/tests/services_test.go

'tests.TestServicesList' is failing because of flaky 'TestK8sGatewaysAddressesError' not deleting auto-generated Service without 'app' label because of K8sGateway.
Skip validations for services besides 'productpage' to avoid potential flakes.

Skip service validations for potential flaky remaining services

---

.github/pull_request_template.md
PULL_REQUEST_TEMPLATE.md

Adapt PR template to recently changed issue template and move it to the same folder (`.github`).
New sections added to complete PR description

Adapt PR template to issue format

---

config/config.go
routing/router.go
routing/router_test.go
server/server.go
server/server_test.go

To test, set Kiali CR `spec.server.profiler.enabled` to `true`. The server logs should then have a line like this at startup:
```
2024-02-07T18:09:40Z INF Profiler is enabled
```
Go to the Kiali URL, specifically the `<root context>/debug/pprof/` endpoint and you get the html index page of the profiler. Click all the links to see the data.
For example, if you port-forward to the Kiali server that is running on minikube (say, via `hack/kiali-port-forward.sh`), you should be able to see it at http://localhost:20001/kiali/debug/pprof/
Then use the "go tool pprof" utility to view it in a web browser. For example:
```
go tool pprof -http :8080 http://localhost:20001/kiali/debug/pprof/heap?debug=1
```
will bring up a browser tab pointing to the heap profiler. You can access the other profiles …

add profiler to kiali server

---

routing/router.go
routing/router_test.go
server/server.go
server/server_test.go

To assuage those with security paranoia, this PR puts the pprom endpoint behind the Kiali auth. If Kiali is in anonymous mode, you can still get to pprom without credentials, but if Kiali has a non-anonymous auth-strategy set, then pprom will require credentials just as the Kiali console does.

put /debug/pprof behind auth

---

business/checkers/checker.go
frontend/src/components/VirtualList/Renderers.tsx
frontend/src/pages/Graph/SummaryPanelGraph.tsx
frontend/src/pages/Overview/OverviewPage.tsx
frontend/src/pages/Overview/__tests__/OverviewSort.test.ts
frontend/src/services/Api.ts
frontend/src/types/IstioObjects.ts
handlers/namespaces.go
models/istio_validation.go
models/istio_validation_test.go

Fetches validations once per cluster instead of once per namespace.
ref: #7076 
Test with:
1. Creating ~200 namespaces with something like:
```bash
for i in {1..200}; do kubectl create ns test-$i; done
```
2. Visit the graph page.
3. Compare previous time it takes to load all the requests and the page with this PR.
Cleanup with:
```bash
for i in {1..200}; do kubectl delete ns test-$i --wait=false --ignore-not-found=true; done
```
In my environment with 208 namespaces selected:
Before:
211 requests ~10.2s
After:
4 requests ~1.8s

Optimize fetching validations on graph page

---

frontend/cypress/integration/common/graph_side_panel.ts
frontend/cypress/integration/featureFiles/graph_side_panel.feature
frontend/src/services/Api.ts
frontend/src/types/ServiceInfo.ts

Passes cluster name to API call when deleting istio object from the graph's context menu.
1. Deploy kiali in a multi-primary env: `./hack/run-integration-tests.sh --test-suite frontend-multi-primary --setup-only true`
2. Remove traffic routing in the "west" cluster from the graph's context menu.
3. Should see success.
Covered by added cypress test.
Fixes #7024

Pass cluster name when deleting istio obj from graph

---

hack/istio/skupper/install-skupper-demo.sh

Script to install skupper-istio-kiali demo - useful for doing future integration work.
Look at `-h` output - important to note is there are different commands to point your browser to different UIs.
Things to try:
* `hack/istio/skupper/install-skupper-demo.sh install` -- installs everything
* `hack/istio/skupper/install-skupper-demo.sh sprom`  -- opens browser tab to the Skupper Prometheus UI
* `hack/istio/skupper/install-skupper-demo.sh iprom`  -- opens browser tab to the  Istio Prometheus UI
* `hack/istio/skupper/install-skupper-demo.sh sui`  -- opens browser tab to the  Skupper UI
* `hack/istio/skupper/install-skupper-demo.sh kui`  -- opens browser tab to the  Kiali UI
* `hack/istio/skupper/install-skupper-demo.sh smetrics`  -- dumps live metrics from the  Skupper scrape endpoint to …

hack script to start a multi-cluster skupper demo on minikube or OpenShift

---

.gitleaks.toml
hack/istio/multicluster/env.sh
hack/istio/multicluster/setup-keycloak.sh

Note that this script is for testing only and demos/examples.
Adds a hack script to setup an "SSO" idp across two openshift clusters for testing multi-cluster kiali setups on openshift.
1. Create two openshift clusters.
2. Login via CLI and rename your kube contexts to "east" and "west".
3. Run this script:
`./hack/istio/multicluster/setup-keycloak.sh --manage-minikube false --manage-kind false --cluster1-context "east"  --cluster2-context "west"`
4. Navigate to the first cluster's console and login to the openid idp with the kiali user.
5. Navigate to the second cluster's console and the login should be skipped.
N/A
Related to #7042

Add hack script for setting up an "SSO" idp on openshift across two clusters

---

business/workloads.go
frontend/src/pages/WorkloadDetails/WorkloadInfo.tsx
models/health.go
models/workload.go
models/workload_test.go
tests/integration/tests/workloads_test.go

Skip proxy status checks for Workloads which are Gateways.
Steps to deploy a Gateway 'istio-ingressgateway' into namespace different than 'istio-system' https://docs.openshift.com/container-platform/4.14/service_mesh/v2x/ossm-traffic-manage.html#ossm-automatic-gateway-injection_traffic-management
Here for this Workload it was showing a Proxy Status warning message, but it fact it should not. For Gateways in 'istio-system' it used to ignore the check.
With this PR it will not show Proxy check warning message on Gateways at all.
Regression test the 'istio-ingressgateway' in 'istio-system' namespace and other Worklaods from 'bookinfo' namespace with sidecars.
Covered in unit and integration tests.
Issue https://github.com/kiali/kiali/issues/7127

Skip Gateway workload pods proxy status check.

---

frontend/src/pages/Mesh/Mesh.tsx
frontend/src/pages/Mesh/MeshElems.tsx
frontend/src/pages/Mesh/MeshPage.tsx
frontend/src/pages/Mesh/layouts/layoutFactory.ts
frontend/src/pages/Mesh/target/TargetPanelNamespace.tsx
frontend/src/types/Graph.ts
mesh/api/api_test.go
mesh/api/testdata/test_mesh_graph.expected
mesh/config/cytoscape/cytoscape.go
mesh/options.go

The namespace box was not properly attached to its parent cluster box.
- change "non-infra" terminology to "data planes"
- simplify boxing strategy
- change node shapes to be more distinct from the traffic graph
- increase node sizes for easier visibility and more distinction from the traffic graph
- add dataplane namespaces to test mesh
Closes https://github.com/kiali/kiali/issues/7118

Fix the dataplane namespaces box

---

graph/telemetry/istio/appender/service_entry.go
graph/telemetry/istio/appender/service_entry_test.go

Fixes https://github.com/kiali/kiali/issues/7153
Yet another pass as ServiceEntry handling
- Update approach to ensure that we consider ALL of the service entry definitions that are local to, or exported to, the cluster+namespace of the source node requesting the serviceEntry host.
- And also all of those serviceEntry's hosts
- Remove duplicates when determining "se-service" candidates
- replace slice with map
- Revise service_entry appender comments, for clarity
- Add test specific to the bug's use-case

[graph] Fix serviceEntry handling when the definition is exported (not local) to the source node namespace

---

hack/istio/multicluster/kiali-prepare-remote-cluster.sh

- Extend validation to allow AWS EKS ARN format for REMOTE_CLUSTER_NAME
- Extract cluster name from ARN if REMOTE_CLUSTER_NAME is in ARN format
- Update error messages to reflect new validation rules
Adds AWS EKS ARN support for remote cluster names and updates error messages.
Set REMOTE_CLUSTER_NAME to a valid Kubernetes name and verify no errors.
Set REMOTE_CLUSTER_NAME to a valid AWS EKS ARN and verify extraction of the cluster name.
Set REMOTE_CLUSTER_NAME to an invalid value and verify the appropriate error message.
fixes: https://github.com/kiali/kiali/issues/7160

feat: Add AWS EKS ARN support for remote cluster name

---

frontend/src/pages/Mesh/Mesh.tsx
frontend/src/pages/Mesh/MeshElems.tsx

Fixes https://github.com/kiali/kiali/issues/7122
Fix Mesh "fit" issues via graph reset and/or layout in response to:
- group box collapse/expand
- graph canvas resize
Check to see if the graph resets/relayouts reasonably(*) when you:
- Collapse/Expand the data-plane box.
- Collapse/Expand the side panel.
- Resize the browser
(*) By "reasonably" I mean it doesn't have to be perfect.  There are still unusual layout issues, especially with the collapsed "dataplane" box, and sometimes labels may not always be completely visible.

Fix Mesh "fit" issues

---

business/istio_config.go
business/namespaces_test.go
config/config.go
kubernetes/cache/kube_cache.go
models/namespace.go

Add istioAmbientNamespace as a config parameter and add Ambient Namespace logic to projects (For OpenShift). 
Kiali running in OpenShift and Istio 1.22.alpha: 
(Note: I was not able to run it from the hack script because I was received `Error: generate config: failed to read profile openshift-ambient from : open profiles/openshift-ambient.yaml: file does not exist`, tested with: `istio/install-istio-via-istioctl.sh -cp openshift-ambient -ih gcr.io/istio-testing -it 1.22-alpha.f1898ff2fc1406b7899dcf2409876f94b0e76dca -ic ~/Downloads/istio-1.21.0-rc.0/bin/istioctl`
`wget -O - https://storage.googleapis.com/istio-build/dev/1.22-alpha.f1898ff2fc1406b7899dcf2409876f94b0e76dca/istioctl-1.22-alpha.f1898ff2fc1406b7899dcf2409876f94b0e76dca-linux-amd64.tar.gz | tar zxvf -`
./istioctl install --set …

change detection method for Istio Ambient

---

frontend/cypress/fixtures/perf/baselines.json
frontend/cypress/perf/appsload.spec.ts
frontend/cypress/perf/common.ts
frontend/cypress/perf/istioconfigsload.spec.ts
frontend/cypress/perf/overviewload.spec.ts
frontend/cypress/perf/servicesload.spec.ts
frontend/cypress/perf/workloadsload.spec.ts

Added 'baselines.json' file with some test baselines.
Using the baselines to compare load time for each test.
Currently only logging the compared results without failing.
make perf-tests-run
https://github.com/kiali/kiali/issues/7174

[Perf] Added performance baselines

---

business/istio_config.go
business/istio_status_test.go
business/istio_validations.go
business/istio_validations_test.go
business/testing.go
business/tls_test.go
handlers/config.go
handlers/istio_config.go
kubernetes/cache/cache.go
kubernetes/cache/cache_test.go
kubernetes/cache/proxy_status.go
kubernetes/cache/registry_status.go
store/expiration_store.go
store/expiration_store_test.go
store/store.go
store/store_test.go
store/threadsafe_store.go
util/pointer.go

Moves `AmbientEnabled` check to the `KialiCache` and make the check cluster specific. This gets rid of the global variables that were breaking the unit tests.
Split out from #7136

Move `AmbientEnabled` to the `KialiCache`

---

config/config.go
tracing/client_test.go
tracing/otel/model/types.go
tracing/tempo/http_client.go
tracing/tempo/http_client_test.go

- Use a healh_check_url for tracing
- Better error handling in case of http errors to the API 
I've a Grafana cloud endpoint for testing, please ping me for details if needed. 
The datasource provides the health check at https://tempo-prod-10-prod-eu-west-2.grafana.net 
Kiali really doesn't validates the response, so I guess the URL could be just the search api url, but, the difference is that the check url is not authenticated. 
With this endpoint configuration: 
```
tracing:
enabled: true
provider: "tempo"
in_cluster_url: https://tempo-prod-10-prod-eu-west-2.grafana.net/tempo
url: https://tempo-prod-10-prod-eu-west-2.grafana.net/tempo
query_timeout: 40
whitelist_istio_system:
- jaeger-query
- istio-ingressgateway
port: 443
service: tracing …
```

Update health_check_url for tracing, better error handling

---

frontend/cypress/integration/common/graph_display.ts
frontend/cypress/integration/featureFiles/graph_display.feature

Related to #6661.
I had to use 2 tap actions, as none of the default cytoscape.js double-click events worked with the graph. 
I have also removed one skipped test for the Multi-primary, as the gherkins were already implemented.

[MC] Test coverage for a bug related to double clicking on a graph node + test implementation of a test around Istio Config wizard

---

make/Makefile.operator.mk

Rather than abort if kiali isn't installed, wait for kiali to start. This is because usually you use the ossmconsole-create target together with kiali-create. If you do, ossmconsole-create should wait for that Kiali CR to be reconciled by the operator and for Kiali to start.
Assuming you have the operator installed on OpenShift (run `make build build-ui cluster-push operator-create`), you can run this and see that it is successful and both Kiali and OSSMC are installed:
`make kiali-create ossmconsole-create`
You should see the make target wait for some time until the kiali pod starts:
```
$ make kiali-create ossmconsole-create 
...
Deploy Kiali using the settings found in /home/jmazzite/source/kiali/kiali/operator/deploy/kiali/kiali_cr_dev.yaml
...
kiali.kiali.io/kiali created
...
Kiali …
```

[make] ossmconsole-create target should wait for kiali to start

---

Makefile
make/Makefile.cluster.mk
make/Makefile.molecule.mk
make/Makefile.olm.mk
make/Makefile.operator.mk

Backport of make option `ossmconsole-create` to be able to deploy local OSSMConsole plugin in remote clusters for 1.73 release (OSSM 2.5)
Run `make clean build build-ui cluster-push operator-create kiali-create ossmconsole-create` in OCP cluster to check that OSSMConsole plugin is installed correctly

[v1.73] Add make ossmconsole-create option

---

log/log.go
log/log_test.go

It has been deprecated/superceded since v1.26 (4 years ago)
fixes: https://github.com/kiali/kiali/issues/7208

remove verbose_mode that has been deprecated

---

business/apps.go
business/apps_test.go
frontend/cypress/integration/common/apps.ts
frontend/cypress/integration/featureFiles/apps.feature
frontend/src/components/VirtualList/Config.ts
frontend/src/components/VirtualList/Renderers.tsx
frontend/src/components/VirtualList/VirtualItem.tsx
frontend/src/config/Config.ts
frontend/src/helpers/__tests__/LabelFilterHelper.test.ts
frontend/src/pages/AppList/AppListClass.tsx
frontend/src/pages/AppList/AppListPage.tsx
frontend/src/pages/AppList/FiltersAndSorts.ts
frontend/src/services/Api.ts
frontend/src/types/AppList.ts
frontend/src/utils/Common.ts
hack/run-integration-tests.sh
handlers/apps.go
handlers/apps_test.go
models/app.go
routing/routes.go
tests/integration/tests/applications_test.go
tests/integration/utils/kiali/kiali_client.go

Apps page was querying backend per namespace, now it queries per cluster by providing selected namespaces.
New API endpoing "api/clusters/apps" is added.
Create a set of namespaces:
for i in {1..200}; do kubectl create ns test-$i; done
Open the Apps list page and select all apps.
Compare the loading time between before and now.
Check if all fields are loaded correctly.
Modified e2e and unit tests.
https://github.com/kiali/kiali/issues/4832

Apps lists page optimized to query per cluster

---

business/istio_config.go
business/namespaces.go
business/services.go
handlers/apps.go

1. Ignores `IsForbidden` errors in `business.IstioConfig` when in multi-cluster mode. 
2. In the apps handler, only checks namespaces filtered by `GetClusterNamespaces`
Test with:
1. Setup
```
hack/istio/multicluster/install-multi-primary.sh -mm true -kudi true -md kvm2
hack/istio/multicluster/deploy-kiali.sh --single-kiali true --cluster1-context east --cluster2-context west --kiali-auth-strategy openid
```
2. Login to kiali with kiali user
3. Verify no errors on the apps/graph pages

Skip forbidden namespaces in multi-cluster mode

---

frontend/cypress/integration/featureFiles/services.feature
frontend/src/pages/ServiceList/ServiceListPage.tsx
frontend/src/types/ServiceList.ts

Fixes flake for service entry test by inverting the default on the toggles since these are usually not present unless you've explicitly enabled them.
Create a service entry. Visit the services page to ensure that the health/config columns show up.
Fixes this flake: https://github.com/kiali/kiali/actions/runs/8438002236/job/23109424160?pr=7228#step:8:1534

Fix defaulting of toggles

---

frontend/cypress/integration/common/namespace.ts
frontend/cypress/integration/featureFiles/graph_toolbar.feature
frontend/src/components/NamespaceDropdown.tsx

Sorts namespaces alphabetically in the dropdown selector.
Deploy kiali. Repeatedly click the namespace dropdown and ensure the namespaces are always sorted correctly.
Included with this change.
Fixes #7227

Ensure namespace dropdown is sorted alphabetically

---

frontend/src/components/IstioActions/IstioActionsNamespaceDropdown.tsx
frontend/src/components/Metrics/CustomMetrics.tsx
frontend/src/components/Metrics/IstioMetrics.tsx
frontend/src/pages/Graph/GraphToolbar/GraphToolbar.tsx
frontend/src/pages/GraphPF/components/stylesComponentFactory.tsx
frontend/src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
frontend/src/pages/IstioConfigNew/IstioConfigNewPage.tsx
frontend/src/pages/WorkloadDetails/WorkloadPodLogs.tsx
frontend/src/services/Api.ts
frontend/yarn.lock

Partial backport of https://github.com/kiali/kiali/pull/7224 (only those changes that affect v1.73 and PF4):
- Add kiosk redirection to all history modifications (graph context menu, trace tab, etc.)
- Stringify body data when content-type is application/x-www-form-urlencoded
https://github.com/kiali/openshift-servicemesh-plugin/issues/284

[v1.73] Add kiosk support to all Kiali links

---

GOVERNANCE.md

Matej Kralik has been working on Kiali for over 3 months and has contributed to improving our test coverage and processes, especially in the area of OpenShift support.
Maintainers, please upvote or downvote this change.

This PR adds mkralik as an official Tester for the Kiali Project

---

frontend/src/components/IstioActions/IstioActionsNamespaceDropdown.tsx
frontend/src/components/Metrics/CustomMetrics.tsx
frontend/src/components/Metrics/IstioMetrics.tsx
frontend/src/components/Nav/Page/RenderComponentScroll.tsx
frontend/src/pages/Graph/GraphLegend.tsx
frontend/src/pages/Graph/GraphToolbar/GraphToolbar.tsx
frontend/src/pages/Graph/GraphToolbar/__tests__/__snapshots__/GraphLegend.test.tsx.snap
frontend/src/pages/GraphPF/GraphHighlighterPF.ts
frontend/src/pages/GraphPF/GraphLegendPF.tsx
frontend/src/pages/GraphPF/components/stylesComponentFactory.tsx
frontend/src/pages/GraphPF/styles/styleEdge.tsx
frontend/src/pages/GraphPF/styles/styleGroup.tsx
frontend/src/pages/GraphPF/styles/styleNode.tsx
frontend/src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
frontend/src/pages/IstioConfigNew/IstioConfigNewPage.tsx
frontend/src/pages/Mesh/MeshHighlighter.ts
frontend/src/pages/Mesh/MeshLegend.tsx
frontend/src/pages/Mesh/styles/MeshEdge.tsx
frontend/src/pages/Mesh/styles/MeshGroup.tsx
frontend/src/pages/Mesh/styles/MeshNode.tsx
frontend/src/pages/Mesh/toolbar/__tests__/__snapshots__/MeshLegend.test.tsx.snap
frontend/src/pages/WorkloadDetails/WorkloadPodLogs.tsx
frontend/src/services/Api.ts

This PR adapts Kiali code to make OSSMC compatible with OCP 4.15:
- Add kiosk redirection to all history modifications (graph context menu, trace tab, etc.)
- Stringify body data when content-type is `application/x-www-form-urlencoded`
- According to [console-dynamic-plugin-sdk](https://github.com/openshift/console/blob/master/frontend/packages/console-dynamic-plugin-sdk/README.md#patternfly-dynamic-modules) README, we should avoid non-index imports for any PatternFly packages. Some of the imports are still non-index since they have to be exported correctly from `patternfly-react` library (https://www.github.com/patternfly/patternfly-react/issues/10155)
- Lint issues
This PR only affects OSSMC, so there should not be any change from Kiali perspective.
N/A
Kiali part of …

Adapt Kiali code to make OSSMC compatible with OCP 4.15

---

hack/crc-openshift.sh

_tl;dr This allows you to use CRC to run multiple OpenShift clusters on a local network. Very useful for multi-cluster work._
This is a very useful enhancement to the CRC hack script.
We already had a command "expose" and "unexpose" which exposes the CRC cluster to remote machines on the local network. This allows you to access the OpenShift cluster via a browser or an oc/kubectl client running anywhere on the network (not just from the same box where CRC is running). This uses firewall rules.
However, the problem is you can only have one CRC cluster on your network because CRC fixes the domain name to "crc.testing". So if I want to start two CRC clusters, one on machine "foo" and one on machine "bar" they both bind to "crc.testing" and therefore only one can be exposed to remote machines …

[hack] support unique domain names for CRC clusters to enable multiple clusters on the same network

---

frontend/cypress/support/commands.ts
hack/istio/multicluster/deploy-kiali.sh
hack/istio/multicluster/env.sh
hack/istio/multicluster/install-multi-primary.sh
hack/istio/multicluster/start-minikube.sh
hack/keycloak.sh
hack/run-integration-tests.sh
hack/setup-kind-in-ci.sh
hack/start-kind.sh

Adds keycloak and deploys kiali with `openid` auth in the CI pipeline so that multi-cluster access tests can be performed.
1. Setup environment
```hack/run-integration-tests.sh --test-suite frontend-multi-primary --setup-only true```
2. Visit kiali url and login to keycloak with `kiali:kiali`
If current automation passes then all is well.
Fixes #7021

Setup keycloak and openid auth in multi-primary CI pipeline

---

frontend/cypress/fixtures/perf/baselines.json
frontend/cypress/fixtures/perf/commonParams.json
frontend/cypress/perf/overviewload.spec.ts
hack/run-performance-tests.sh

Added a new hack script 'run-performance-tests.sh' which prepares the test data and executes Kiali performance tests.
To run Kiali cypress perf tests now can be done within a single script: `./hack/run-performance-tests.sh -td 10`
where '-td' parameter indicates how many empty 'perf-test-$i' namespaces should be created before testsuite run.
The 'make perf-tests-gui' and 'yarn cypress:perf' endpoints are remaining untouched.
https://github.com/kiali/kiali/issues/7058

Script for perf tests run and test data creation

---

business/services.go
business/services_test.go
frontend/cypress/integration/common/graph_side_panel.ts
frontend/src/config/Config.ts
frontend/src/pages/ServiceList/ServiceListPage.tsx
frontend/src/services/Api.ts
frontend/src/services/__tests__/ApiMethods.test.ts
frontend/src/types/ServiceList.ts
graph/telemetry/istio/appender/istio_details.go
handlers/services.go
models/service.go
routing/routes.go
tests/integration/tests/no_istiod_test.go
tests/integration/tests/services_test.go
tests/integration/utils/kiali/kiali_client.go

In Service list page, there was sending a REST API request to retrieve services per namespace, which was causing to filter per cluster which contains the provided namespace.
Now Optimized to send Service list request to REST API per cluster with providing selected namespaces list.
Create a set of namespaces:
`for i in {1..200}; do kubectl create ns test-$i; done`
Open the Service list page and select all services.
Compare the loading time between before and now.
Check if Health and Configuration fields are loading correctly: There was a bug here which was mirroring one cluster's Configuration to another one when two Services with same name/namespace.
Added unit tests. Added integration tests.
https://github.com/kiali/kiali/issues/4832

Service list backend request per cluster

---

go.mod
go.sum
kiali.go

This adds [automaxprocs](https://github.com/uber-go/automaxprocs) to determine `GOMAXPROCS` automatically in a container according to `resources.limits.cpu`. We're currently seeing excessive throttling when setting a CPU limit.
Originally implemented in #4579 
Removed in #6100 though that doesn't look intentional.
Setting limits lower than the node CPU count on the container shouldn't cause excessive CPU throttling
Fixes #7254

add automaxprocs to determine gomaxprocs

---

frontend/cypress/integration/common/kiali_login.ts
frontend/cypress/integration/featureFiles/kiali_login.feature
frontend/src/services/Api.ts

Fixes https://github.com/kiali/kiali/issues/7252

Update Content-Type for login request

---

frontend/src/pages/Overview/OverviewPage.tsx

This PR adds the `flex` CSS value to the overview page, ensuring that the background color in the OSSMC overview page expands to cover the entire height.
Before:
Now:
This change is already in v1.73 branch, but it is not present in `master` branch:
https://github.com/kiali/kiali/blob/823746f51ab53e2aee2194172eda560a7a6fa32b/frontend/src/pages/Overview/OverviewPage.tsx#L85
This change does not affect Kiali.
N/A

Adjust flex css value in overview page for OSSMC

---

hack/istio/skupper/demo-emit-metrics-deployment/Dockerfile
hack/istio/skupper/demo-emit-metrics-deployment/Makefile
hack/istio/skupper/demo-emit-metrics-deployment/emit-metrics.sh
hack/istio/skupper/demo-emit-metrics-deployment/k8s.yaml

This is a small demo app (docker container and some k8s resources) that will be useful when doing the extensions metrics work in Kiali graph generator/appenders.
The Makefile provides some basically commands for dev workflow. The idea is we can define a series of metrics timeseries and labels, see how Kiali graphs them. Then we can change the metrics with different names or labels and see how well Kiali graphs those. In other words, this allows us to do quick dev cycles as we try to determine what good extension metrics would look like.
This is going to be useful for the skupper integration work.
Dev cycle would look like this:
1. Edit `k8s.yaml`, specifically the metric definitions in the ConfigMap.
2. Run `make deploy` to get the simple app installed. Prometheus will immediately scrape …

[hack] for extension metrics R&D

---

hack/istio/install-sleep-demo.sh

I added the sed command before applying the YAML and I also added a regex check to make sure the script can be run multiple times.
This needs to be backported to 1.73.

Fix sleep yaml for s390x

---

hack/istio/skupper/demo-emit-metrics-deployment/Makefile

I want this to work with podman as well as docker. Podman gives me a permission denied when trying to read the mounted file. Use :z so it can work around this permissions issue.
test: `make -e DORP=podman run`
see that you do not get the error `cat: /tmp/metrics.txt: Permission denied`

[hack] use :z when mounting the skupper metrics file

---

business/checkers/virtualservices/no_gateway_checker_test.go
business/istio_validations.go
frontend/cypress/integration/featureFiles/istio_config.feature

There was a regression in Istio config details validations that only local namespace objects are loaded, now it loads config objects for all namespaces.
1. Create a gateway
2. Create a virtual service in a different namespace and map it that gateway
Added unit and cypress tests.
https://github.com/kiali/kiali/issues/7287

Fixed validations for details, load configs for all namespaces

---

frontend/src/services/Api.ts

OSSMC shows weird CORS issues because Kiali login header is present in the HTTP requests to the Kiali server. This Kiali login header can be removed for those requests performed with an API proxy like OSSMC because it has a different login process. 
This PR does not affect Kiali standalone, only OSSMC. Kiali should work as expected.

Don't use kiali login headers with api proxy (OSSMC)

---

deploy/docker/Dockerfile-cypress

By default, the cypress cache folder is under /root/.cache folder which causes permission error in LPTINTEROP/OpenShift CI pipelines

[1.73] Fix cypress cache folder in test image

---

frontend/src/pages/IstioConfigNew/GatewayForm/ServerBuilder.tsx

Original issue https://github.com/kiali/kiali/issues/7315 failure is caused by 'client-go@v0.28.3' library inconsistency used in Kiali v1.82, but it is fixed in Kiali v1.84.
However the missing option 'OPTIONAL_MUTUAL' is added in 'Istio Config List -> Actions -> Create Gateway'  wizard:

Added missing tls option OPTIONAL_MUTUAL

---

business/checkers/authorization/principals_checker.go
business/checkers/authorization/principals_checker_test.go
business/checkers/authorization_policies_checker.go
business/istio_validations.go
models/istio_validation.go

Actual for multicluster mode only. Kiali does not have validations for multicluster configs.
Currently, when ServiceAccount is created on a workload on remote cluster and the access is configured by spiffe: https://spiffe.io/docs/latest/try/getting-started-k8s/
Kiali is complaining on AuthPolicy that the ServiceAccount for the principal is not found. But in fact the SA exists.
Added a support of checking SA existence on remote clusters, and if exists, show warning message only on principals that "Service Account for this principal is on remote cluster"
Create a multicluster environment.
On `east` cluster create a Deployment with 'serviceAccountName', like in a SPIRE described in steps here: https://istio.io/latest/docs/ops/integrations/spire/
On `west` cluster create  AuthPolicy which …

New KIA0107 for ServiceAccounts on remote cluster

---

hack/run-molecule-tests.sh

Right now we have tests "ossmconsole-config-values-test" and "config-values-test". The way the bash test works right now is that config-values-test is being skipped when only ossmconsole-config-values-test should be skipped. This commit fixes that flaw.

[hack] be able to run tests whose name is a subset of another test

---

business/tracing.go
tracing/jaeger/model/types.go
tracing/tempo/http_client.go

- Fix url for Tempo api trace ID 
- Use hostname tag to see if the workload is related to a span, in order for Tempo to be able to get the Kiali traces correctly
- Better error handling: 
- Test that everything works fine setting the environment with `istio/tempo/install-tempo-env.sh -c kubectl -ik true`.
- For this particular error and urls with subpaths, it can be tested with a grafana cloud datasource: 
```
tracing:
enabled: true
provider: "tempo"
in_cluster_url: https://tempo-prod-10-prod-eu-west-2.grafana.net/tempo
url: https://tempo-prod-10-prod-eu-west-2.grafana.net/tempo
query_timeout: 40
whitelist_istio_system:
- jaeger-query
- istio-ingressgateway
port: 443
service: tracing
health_check_url: …
```

Fix URL for Tempo urls with paths for trace IDs

---

business/workloads.go

Fix for index out of bounds when trying to parse ztunnel log line. 
Install Istio ambient 1.22 dev: 
- `istio/download-istio.sh -div 1.22-dev`
- `istio/install-istio-via-istioctl.sh -c kubectl -cp ambient -it default -ih default`
- `istio/install-bookinfo-demo.sh -c kubectl -ai false -tg`
Access one of the workloads logs and select ztunnel. No error 500 should be found:

Fix index out of bounds

---

frontend/cypress.config.ts
frontend/cypress/integration/common/kiali_login.ts
frontend/cypress/integration/featureFiles/kiali_login.feature
frontend/cypress/support/commands.ts

Validates cookie is present in `cy.session`. Fixes `my_htpasswd_provider` environments.
Deploy kiali on openshift. Run cypress with:
```
CYPRESS_BASE_URL=<kiali_route>
CYPRESS_USERNAME=<username>
CYPRESS_PASSWD=<pass>
```
Fixes existing tests.

Fix cypress login on openshift

---

hack/run-performance-tests.sh

Added a new option '-do --delete-only' in hack/run-performance-tests.sh.
Necessary for 'create Jenkins Job to run perf cypress tests' subtask https://github.com/kiali/kiali/issues/7247

[Perf] Added script option for delete only

---

tests/integration/assets/remote-istiod/proxy-patch.yaml

Use quay image for nginx-unprivileged in remote istiod test instead of docker

[v1.73] Use quay image for nginx-unprivileged in remote istiod test

---

hack/istio/sail/func-kiali.sh
hack/istio/sail/func-minio.sh
hack/istio/sail/func-sm.sh

Some things have changed with Sail operator. This updates the hack scripts to work with it.
To test:
1. Start an OpenShift cluster (e.g. `hack/crc-openshift.sh start`)
2. Use `oc` to log into the cluster as a kubeadmin user
3. Install the operators for Sail, Kiali, Tempo, etc.: `hack/istio/sail/install-ossm-release.sh install-operators`
4. Install a Istio, Kiali, Prometheus, etc. etc.: `hack/istio/sail/install-ossm-release.sh install-istio`
5. See that everything eventually installs successfully: `hack/istio/sail/install-ossm-release.sh status`
6. Bring up the Kiali UI in a browser: `hack/istio/sail/install-ossm-release.sh kiali-ui`
7. See that you can get to the UI and things look OK
When you are done, you can delete everything except the operators with: …

[hack] update with new sail stuff

---

hack/istio/multicluster/env.sh
hack/istio/multicluster/install-multi-primary.sh
hack/istio/multicluster/install-primary-remote.sh
hack/setup-kind-in-ci.sh

fixes: https://github.com/kiali/kiali/issues/7313
I do not know why these were removed. We have all the kiali options for these hack scripts but they are now ignored - kiali is never deployed even if enabled.
These were removed in the following commits:
* https://github.com/kiali/kiali/commit/804f21ebe3d93be9f167353b81895ce7044c7e44#diff-ae968abe0209eefd78f858f137a2e418a056ec6e02965d2214bcb46c8a978efeL77-L78
* https://github.com/kiali/kiali/commit/d8631a1d8814f2c025ce6ca460de147aa810368b#diff-b53029271ec37bbeb86a1eb29db8fd5e77a74f0fda8dac3d7d22109fcb11fdf3L203-L204

[hack] bring back kiali in MC scripts

---

config/dashboards/dashboards.go
config/dashboards/dashboards_config_test.go

fixes: https://github.com/kiali/kiali/issues/7238
To test, navigate to the istiod Application, and click the "Istiod Metrics" tab:
See https://istio.io/latest/docs/reference/commands/pilot-discovery/#metrics

add Istiod dashboard

---

hack/istio/install-istio-via-istioctl.sh
hack/setup-kind-in-ci.sh

Re-enables tracing for tempo CI job.
Follow up to #7356

Fix tracing for tempo CI job

---

tests/integration/tests/remote_istiod_test.go
tests/integration/utils/kiali/instance.go
tests/integration/utils/kube/util.go

Previously we were updating the istiod but then not waiting for it to be ready before the next test started causing the next test to fail. This change will wait for the istiod to be ready before the next test starts.
If automation passes and the flake goes away then this change worked.
Fixes #7134

Wait for istiod deployment to be ready after updating it

---

hack/istio/multicluster/deploy-kiali.sh

Due to recent helm chart changes, the `kiali` clusterrole no longer gets created when using the oauth strategy. The CI tests relied on this role to be present to give the testing user permissions to login and interact with kiali. This change generates the old `kiali` clusterrole from helm directly rather than relying on it being present in the cluster.
`./hack/run-integration-tests.sh --test-suite frontend-multi-primary`
Multi-primary tests pass.

Fix deploy-kiali.sh testing user roles

---

frontend/cypress/integration/common/mesh_test.ts
frontend/cypress/integration/featureFiles/mesh.feature
frontend/package.json
frontend/src/pages/Mesh/Mesh.tsx
frontend/src/pages/Mesh/MeshPage.tsx
frontend/yarn.lock
make/Makefile.ui.mk

Fixes https://github.com/kiali/kiali/issues/7374
- Fix meshpage cypress issue caused by excessively large state (i.e. the  PFT controller object.
- Add `make cypress-selected` command for convenience
- update cypress-react-selector to 3.0 as it is supposed to the version for Cypress 10+ (we are on cypress 13). Note that this project seems unmaintained, but there is currently no obvious alternative.

Fix meshpage cypress issue

---

frontend/src/pages/Graph/GraphPage.tsx
frontend/src/pages/GraphPF/GraphPagePF.tsx
frontend/src/pages/Mesh/MeshPage.tsx

The initial loading of the mesh and graph data is performed in the `componentDidUpdate` method to ensure that everything is set before the mesh loads. The issue is that the `componentDidUpdate` method is not called in OSSMC during the initial mesh load, so the page displays the `Loading` message until the user performs an action that triggers the componentDidUpdate method.
This PR also sets some missing redux properties in the mesh page and fix lint issues.
This PR only affects OSSMC. Kiali standalone should work as usual.
N/A
https://github.com/kiali/openshift-servicemesh-plugin/issues/308

Initial load graph or mesh on componentDidMount

---

frontend/public/locales/zh/translation.json
frontend/src/pages/Mesh/target/TargetPanelMesh.tsx
mesh/generator/generator.go
status/versions.go

This PR adds support for multi-primary scenarios, providing correct versions for Kubernetes in the mesh page. 
1. Deploy a multi-primary scenario 
2. Go to Mesh page
3. Verify that Kubernetes versions are the correct ones
N/A
Fixes #7361

Correct Kubernetes versions for multi-primary scenarios

---

business/istio_config.go
frontend/cypress/integration/common/hooks.ts
hack/istio/install-bookinfo-demo.sh
hack/istio/multicluster/setup-external-controlplane.sh
kubernetes/cache/kube_cache.go
kubernetes/kubernetes.go
kubernetes/types.go
models/istio_config.go

Explanation of what this PR does
K8sGRPCRoute is updated to v1 which comes with K8s GW API v1.1.0 CRDs.
- Apply K8s GW CRDs v1.1.0. `kubectl apply -k "github.com/kubernetes-sigs/gateway-api/config/crd/experimental?ref=v1.1.0"`
- Create GRPCRoute v1alpha2:
```
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GRPCRoute
metadata:
name: example-route
spec:
parentRefs:
- name: example-gateway
hostnames:
- "example.com"
rules:
- backendRefs:
- name: example-svc
port: 50051
```
- Load Kiali. Make sure that GRPCRoute created loading fine in Kiali Istio Config YAML editor. It should change it to v1.
- Update/View/Delete the GRPCRoute, it should work fine.
Existing cypress and e2e tests are updated to support v1 in v1.1.0.
https://github.com/kiali/kiali/issues/7355
Blocked by …

K8sGRPCRoute updated to released v1

---

graph/telemetry/istio/appender/appender.go
graph/telemetry/istio/appender/service_entry.go
graph/telemetry/istio/appender/service_entry_test.go
graph/telemetry/istio/appender/workload_entry.go
graph/telemetry/istio/appender/workload_entry_test.go

Fixes #7305 
Fixes #7349
Add accessibility checks in ServiceEntry and WorkloadEntry appenders, to protect against business-layer auth failures when asking for config info.
Additionally:
- add tests
- fix IsFinalizer() return value in WorkloadEntry appender.  It's not a finalizer, it's a namespace appender.
- remove unnecessary appender param for WorkloadEntry appender
- add missing GraphType appender param in service_entry_test.go tests -
Testing
I think a code review is sufficient as I've added unit tests for the problem scenarios.  Of course it's possible to set it up for real, if you want to do it.  For the Service Entry issue the source node needs to be in an inaccessible cluster or namespace.  For the Workload Entry, the WE node itself needs to be in an inaccessible cluster, although …

Prevent accessibility failures in ServiceEntry and WorkloadEntry appenders

---

config/config.go
mesh/api/testdata/test_mesh_graph.expected
tracing/client.go
tracing/jaeger/grpc_client.go

fixes: https://github.com/kiali/kiali/issues/7266

send custom headers in tracing backend requests

---

hack/istio/install-istio-via-istioctl.sh
hack/istio/multicluster/split-bookinfo.sh
hack/setup-kind-in-ci.sh

Updates the tracing settings for the CI environment so that remote traces will properly send to `zipkin.istio-system:9411`.
N/A
Should fix primary-remote CI job.
Fixes #7387

[CI] Fix default tracing settings

---

frontend/cypress/integration/common/istio_config.ts
frontend/cypress/integration/featureFiles/wizard_istio_config.feature

Related to #7237.
I have not found a reliable way to reproduce the failure, but I have encountered it multiple times both on upstream OCP and Kind. Occasionally, the code inside the Mocha hook was not executed at all and the test passed even though it should detect a failure. This piece of code is tied to most of the CRD validation tests in Cypress.
Create a minimal Istio gateway in Kiali and insert this scenario in the `istio_config.feature` file:
```
@bookinfo-app
@selected
Scenario: delete me later
When user selects the "bookinfo" namespace
Then the "foo" "Gateway" of the "bookinfo" namespace should have a "danger"
```
Run the `yarn cypress:selected` command and the test should fail.
When doing the same procedure against the master branch, there is a chance that the scenario will pass …

Flaky assertion fix

---

status/versions.go
status/versions_test.go

OSSM releases with 'TP' inside version were ignoring 'TP'. Now it is also included.
Issue: OSSM-6425

Support TP releases for OSSM versions

---

frontend/cypress/integration/featureFiles/wizard_istio_config.feature
frontend/src/components/IstioWizards/WizardActions.ts
frontend/src/pages/IstioConfigNew/GatewayForm/ListenerBuilder.tsx
frontend/src/pages/IstioConfigNew/GatewayForm/ListenerList.tsx
frontend/src/pages/IstioConfigNew/K8sGatewayForm.tsx
frontend/src/types/IstioObjects.ts

In K8s Gateway creation wizard, added support of 'HTTPS'  protocol and 'TLS Certificate' input.
Done in a scope of GRPC Routing https://gateway-api.sigs.k8s.io/guides/grpc-routing/
Istio config list -> Actions -> Create K8sGateway.
Add listener.
Choose HTTPS.
New row appears for TLS params. Currently only 'Terminate' is supported.
Add TLS Certificate.
Preview and save.
In create config object should be 'tls:' field with Kind and name. The 'Terminate' default mode value is not shown, considered as default for 'HTTPS'.
Regression testing: Make sure that "HTTP" protocol mode creation is also working fine.
cypress test added
https://github.com/kiali/kiali/issues/7223
Parent epic https://github.com/kiali/kiali/issues/7355

Adding HTTPS and TLS into K8s Gateway creation wizard

---

config/config.go
handlers/tracing.go
models/tracing.go
tracing/jaeger/http_client.go
tracing/tempo/http_client.go

The cluster tag in tracing was "cluster". When Istio added the cluster id tag, it was named istio.cluster_id. https://istio.io/latest/news/releases/1.21.x/announcing-1.21/change-notes/#telemetry
- Start a multi cluster environment. Ex. `hack/run-integration-tests.sh --test-suite frontend-primary-remote --setup-only true`
- Go to workloads/bookinfo/reviews-v1 from cluster east: Should have traces. 
- Go to workloads/bookinfo/reviews-v1 from cluster west: Should not have traces. 
This message should NOT appear: 
In master code, reviews-v1 from west cluster has traces, because they are not filtered by cluster. 
N/A
Fixes #7384

Update cluster tag for traces

---

frontend/cypress/integration/featureFiles/graph_display.feature
hack/istio/install-bookinfo-demo.sh
hack/istio/install-travel-agency-demo.sh
hack/run-integration-tests.sh

Updated bookinfo and travel portal demo
Deploy demos in Ambient mesh: 
- `hack/istio/install-travel-agency-demo.sh -c kubectl -di travel-agency`
- `istio/install-bookinfo-demo.sh -c kubectl -ai false -tg -w true`
To include also waypoint in travel agency: 
- `hack/istio/install-travel-agency-demo.sh -c kubectl -di travel-agency,travel-portal -w true`
Fixes #7402

Improve hack scripts for Ambient

---

.github/workflows/test-images-release.yml

When a new Kiali version is released, this [workflow](https://github.com/kiali/kiali/blob/master/.github/workflows/test-images-release.yml#L6) should build and publish test images as well however, it didn't work ( because it is triggered by tag pushing, not by release, fixed ).
Let's imagine we release the following kiali versions in a particular time frame
- Kiali v1.85.0 is released
-  The workflow creates int and cypress test images with `v1.85.0` and `v1.85` tags.
- Kiali v1.85.1 is released
-  The workflow creates int and cypress test images with `v1.85.1` tag and update images under `v1.85` tag
- Kiali v1.85.2 is released
-  The workflow creates int and cypress test images with `v1.85.2` tag and update images under `v1.85` tag
So these test images would exist:
v1.85.0
v1.85.1 …

Fix release test suite images workflow

---

frontend/package.json

Remove ambient tests from jenkins pipeline tests, as Ambient requires another environment.
Run yarn cypress:run:junit, `@ambient `tests should not run.
N/A

Remove ambient tests from jenkins pipeline tests

---

.github/workflows/build-backend.yml
.github/workflows/release.yml
Makefile
README.adoc
go.mod
make/Makefile.build.mk

- Update go.mod version
- Add a check in the Makefile to make sure both go versions are de same
- Update GO_VERSION_KIALI = 1.22.2
- Run make 
- It should be an error
GH Actions
Failing Actions, ex. https://github.com/kiali/kiali/actions/runs/9361191323/job/25767881628

Go version 1.22.1

---

frontend/cypress/integration/common/mesh.ts

In some environments, external services (such as tracing, metric store, etc.) can be deployed outside of the mesh (external deployments). This PR adds support for executing mesh cypress tests in such environments.
Mesh page cypress test

Add support for external deployment cluster in mesh cypress test

---

frontend/src/pages/GraphPF/elements/extendedBaseEdge.ts
frontend/src/pages/Mesh/elements/extendedBaseEdge.ts

Fixes #7418 
In the early days of the PFT graph dev we overrode PFT's bendpoints to force straight edges, like we have in Cytoscape.  But in the case that the same source and dest nodes (a -> b) has parallel edges (typically edges with different protocols), the removal of bendpoints caused the edges to bothe be straight, thus overlaying. This adds a check to allow bendpoints in this situation.
before:
after:

Don't force parallel edges to be straight

---

config/config.go
frontend/src/components/IstioWizards/WorkloadWizardDropdown.tsx
frontend/src/config/ServerConfig.ts
frontend/src/pages/Overview/OverviewPage.tsx
frontend/src/types/ErrorRate/__testData__/ErrorRateConfig.ts
frontend/src/types/ServerConfig.ts
frontend/src/types/__testData__/HealthConfig.ts

Hide Enable auto injection menu action for Ambient NS
1. Install Ambient mesh
2. Add namespace to Ambient
3. "Enable Auto injection" menu option should not be in the actions for the NS card
5. Go to a workload in Ambient: The "Enable Auto injection" menu option should not be there: 
6. The option should be in a ns with no Ambient annotations: 
N/A
Fixes #7420

Hide Enable auto injection menu action for Ambient NS

---

frontend/cypress/integration/common/graph_context_menu.ts

Fixes #7256 
This wraps the logic in "wait" for graph to load.   If it works I could apply it in all places.

An attempt to fix the flake by ensuring the graph has loaded.

---

business/checkers/services/port_mapping_checker.go
business/checkers/services/port_mapping_checker_test.go
business/workloads.go
config/config.go
graph/telemetry/istio/appender/ambient.go
models/pod.go

Skips 'KIA0701 Deployment exposing same port as Service not found' for generated 'waypoint' service.
Unit testing.

Skipp KIA0701 check for waypoint proxy generated service

---

business/checkers/k8sgrpcroutes/no_host_checker.go
business/checkers/k8sgrpcroutes/no_host_checker_test.go
business/checkers/k8sgrpcroutes/no_k8sgateway_checker_test.go
business/checkers/k8shttproutes/no_host_checker.go
business/checkers/k8shttproutes/no_host_checker_test.go
business/checkers/k8shttproutes/no_k8sgateway_checker_test.go
models/istio_validation.go
tests/data/k8sgateway_data.go
tests/integration/tests/config_validations_test.go

K8s HTTPRoute and GRPCRoute 'parentRef' field now can accept 'Service' kind of references.
Extended KIA1402 "Reference doesn't have a valid service (Service name not found)" validation message to support "spec/parentRefs[n]/name".
Modify any K8s HTTPRoute to have a parentRef to a Service which does not exist:
```
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
metadata:
name: details
spec:
parentRefs:
- group: core
kind: Service
name: details_wrong
port: 9080
hostnames:
- details.bookinfo.svc.cluster.local
rules:
- matches:
- path:
type: PathPrefix
value: /
backendRefs:
- group: ''
kind: Service
name: details
port: 9080
weight: 100
```
backend tests updated
https://github.com/kiali/kiali/issues/7355

Added new validation check on HTTP/GRPC Route parentRef Service

---

frontend/src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
frontend/src/components/CytoscapeGraph/CytoscapeContextMenu.tsx
graph/telemetry/istio/appender/ambient.go
graph/telemetry/istio/appender/ambient_test.go
graph/telemetry/istio/appender/appender.go

Doesn't fail if node is not accessible for graph
- Install istio 1.22 with Ambient profile: `istio/install-istio-via-istioctl.sh -c kubectl -cp ambient`
- Install bookinfo and include in Ambient: `istio/install-bookinfo-demo.sh -c kubectl -ai false -tg -w true`
- Add some workload in one namespace excluded for Kiali with traffic for a selected namespace. An easy way is to label the `istio-system` namespace with the Ambient label (`kubectl label ns istio-sytem istio.io/dataplane-mode=ambient`)
- Go to the Traffic graph and select bookinfo an istio-system namespaces. The graph should be seen, no errors in the log. In master, there should be a stack trace error, and sometimes, the "Cannot generate graph" message (It doesn't appear always)
Added unit test.
Fixes …

Fix graph issue with excluded namespaces

---

business/istio_config.go
frontend/src/components/IstioWizards/WizardActions.ts

This PR fixes the `apiVersion` value of the Gateway API Reference Grant object in the Kiali wizard.
1. Navigate to the Istio Config page
2. Click on Actions -> K8sReferenceGrant
3. Fulfill the wizard form and click on the `Preview` button
4. Check that the `apiVersion` value is the correct one `gateway.networking.k8s.io/v1beta1`
N/A
Fixes #7463

Fix the apiVersion of ReferenceGrant in the Kiali wizard

---

frontend/src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
frontend/src/components/CytoscapeGraph/CytoscapeContextMenu.tsx
frontend/src/pages/GraphPF/components/stylesComponentFactory.tsx
graph/telemetry/istio/appender/ambient.go
graph/telemetry/istio/appender/ambient_test.go
graph/telemetry/istio/appender/appender.go

Related to #7448 
A follow-up for https://github.com/kiali/kiali/issues/7448.  The original PR may be sufficient but I think could be improved by using some of the existing conventions and/or flags available.
- In Ambient appender, use AccessibleNamespaces to check whether it is safe to call the back-end.
- For the cytoscape context menu, use the `isInaccessible` flag to block the user (and the code) from requesting unavailable information.
- Also block context menu options in PFT graph for inaccessible nodes.

A follow-up for https://github.com/kiali/kiali/issues/7448

---

frontend/cypress/integration/common/app_details_multicluster.ts
frontend/cypress/integration/common/apps.ts
frontend/cypress/integration/common/graph.ts
frontend/cypress/integration/common/graph_display.ts
frontend/cypress/integration/common/graph_find_hide.ts
frontend/cypress/integration/common/graph_side_panel.ts
frontend/cypress/integration/common/graph_toolbar.ts

In an effort to prevent graph-page-related flakes, add the same wrapping we did to avoid the content-menu flake (#7256), around remaining instances.
Note that this does not apply the same logic to the mini-graph tests, because that code is a bit different.  If we suspect a similar flake in that area, we'll have to do some additional work to apply this kind of logic.
@nrfox Should be a straightforward review.  I ran the tests a few times already, feel free to try again if you like.

apply same flake protection as we did for issue 7256

---

business/test_util.go
business/workloads.go
business/workloads_test.go
config/config.go
kubernetes/kubetest/mock.go
models/pod.go

The labels for the waypoint proxies had changed: 
- Not using `pod.Labels["istio.io/gateway-name"] == "namespace"` or `pod.Annotations["istio.io/for-service-account"]`
- It is using `stio.io/use-waypoint` equals to the waypoint name. The label can be placed: 
- In the namespace
- In the service
- In the workload
- Use Istio > 1.22.rc
- Install Istio Ambient: 
`istio/install-istio-via-istioctl.sh -c kubectl -cp ambient`
- Install bookinfo with Ambient and a waypoint proxy: 
`istio/install-bookinfo-demo.sh -c kubectl -ai false -tg -w true`
- Apply different waypoint proxies and check if Kiali identifies them correctly: 
- namespace
- pod
- service
https://istio.io/latest/docs/ambient/usage/waypoint/
```
kubectl label pod -l version=v1,app=productpage -n bookinfo …
```

Identify waypoint proxies

---

frontend/src/components/IstioWizards/K8sRequestRouting.tsx
frontend/src/components/IstioWizards/RequestRouting.tsx
frontend/src/components/IstioWizards/RequestRouting/MatchBuilder.tsx
frontend/src/components/IstioWizards/WizardActions.ts
frontend/src/types/IstioObjects.ts

For Routing Wizards:
- Request Routing
- K8s HTTP Routing
- K8s GRPC Routing 
Made impossible to create Rule on empty "Header Name/Value" combination by default.
Go To above mentioned routing wizards.
It should be impossible to add "Add Rule" on empty Header.
n/a
There is a bigger task of refactoring the wizards, so this solution is temporary for fixing issue:  https://github.com/kiali/kiali/issues/7447

Avoid empty matches adding

---

hack/istio/skupper/install-skupper-demo.sh

without this, the "kui" command can't display kiali ui in browser when installing non-dev kiali

[hack] kiali service type should be LoadBalancer for skupper demo

---

frontend/src/services/Api.ts

Currently, Kiali can send body data in requests as JSON or string since its `Content-Type` header has the value `application/json`. However, OSSMC only supports string data because its `Content-Type` header is `application/x-www-form-urlencoded` to avoid CORS issues. 
Previously, all request data for OSSMC was stringified, but the problem is that some request data is already stringified in the business logic, which causes failures (e.g., updateNamespace). Now the application only stringifies data that is not already stringified.
This PR fixes an OSSMC issue. From Kiali perspective, just check that everything works as expected.
N/A
Fixes https://github.com/kiali/openshift-servicemesh-plugin/issues/330

Stringify the query data only if it is not already stringified

---

mesh/api/testdata/test_mesh_graph.expected
mesh/generator/generator.go

Adds the controlplane revision to the dataplane nodes on the mesh graph.
1. Deploy kiali + istio
```
hack/run-integration-tests.sh --test-suite backend --setup-only true
```
2. Install a second revision 
```
istioctl install --set revision=canary
```
3. Navigate to mesh page and ensure that there's no edge from the canary controlplane to the dataplane.
Test with multicluster
1. Deploy kiali + istio
```
hack/run-integration-tests.sh --test-suite frontend-multi-primary --setup-only true
```
2. Navigate to mesh page and ensure that there's no edge from the east istiod to the west dataplane and vice versa
N/A
Fixes #7458

Add revision to dataplane node

---

frontend/src/pages/Overview/OverviewPage.tsx

In MC mode, Overview page, refresh button click was causing mixing results from one cluster to another before the refresh is done.
There was missing filter of results by cluster of namespace.
Added now.
Setup Multicluster either primary-remote or multi-primary.
Open Overview page.
Click the 'refresh' button several times.
You will notice that 'bookinfo' card content from 'east' cluster is shown for the card from 'west' cluster, then in a second or less the card is shown correctly when refresh response is ready.
n/a
https://github.com/kiali/kiali/issues/7063

Overview: Added missing cluster filter of results.

---

frontend/cypress/support/commands.ts

Since https://github.com/kiali/kiali/pull/7366 was merged the kiali token cookie has changed and needs to be updated in the cypress tests.
Run the cypress tests on openshift and ensure they are passing.

Update kiali token assertion in cypress tests

---

frontend/src/components/DebugInformation/DebugInformation.tsx

Fix issue with yaml debug-info generation when we try to dump cytoscape graph info.  Make sure to protect against cy's duplicate refs, and also stringification of any cy structures. 
Fixes https://github.com/kiali/kiali/issues/7504
See issue for more detail about the problem.
To test:
Before the PR visiting a Cy graph and then asking for debug info would hang the browser tab.  After the fix it should work as expected.

Fix issue with yaml debug-info generation

---

business/workloads.go
graph/telemetry/istio/appender/ambient.go
graph/telemetry/istio/appender/appender.go
kubernetes/cache/cache.go
models/workload.go

Use a waypoint list cache to save at least for 1 minute the list of waypoints. 
Use that list to compare against the values of the workloads in the map.
- Install istio with Ambient mesh
- Install bookinfo demo with Ambient labels and a waypoint
- See the graph. Should be no waypoints. Display with the waypoint label, it should appear in the map. 
backend tests already covered the changes. 
Include additional e2e tests in a separate PR.
Fixes #7473

Improve Ambient appender performance

---

config/config.go
hack/istio/multicluster/deploy-kiali.sh
hack/setup-kind-in-ci.sh
mesh/api/api_test.go
tests/integration/utils/kiali/instance.go

Tracing is disabled by default now
Run Kiali without any additional config (And without the operator).
Tracing should be disabled. 
Update setup for tests
#7332

Tracing is disabled by default

---

frontend/cypress/integration/common/kiali_login.ts

Fix url matching for openshift login negative test. Uses new auth callback url.
Run `kiali_login` test on openshift with the changes.
Fixes e2e test.

Fix url matching for openshift login negative test

---

business/istio_status.go
business/istio_status_test.go
config/config.go
handlers/istio_status.go
istio/discovery.go
istio/discovery_test.go
mesh/api/testdata/test_mesh_graph.expected

`external_services.istio.component_status.components` was expecting to have values for `istiod` and `ingress/egressgateway`, which was causing duplication for Istio component statuses, also duplication of labels in configuration and in code.
Now `external_services.istio.component_status.components` by default made empty, and `istiod` and `ingress/egressgateway` component statuses are read in code.
Functionality of  `external_services.istio.component_status.components` is left as deprecated for now, until will be removed, or will left as empty for possible custom components such as `eastwestgateway`.
Make sure you have 'istiod' without pods sunning.
Before:
After:
Tests modified.
https://github.com/kiali/kiali/issues/7501
https://github.com/kiali/kiali/issues/7524
Operator PR …

Removed 'external_services.istio.component_status.components' duplicate labels.

---

mesh/generator/generator.go

Check the permissions for the control plane component. The cluster won't be shown if there are no permissions. 
No permissions in west cluster: 
User with permissions in both clusters: 
1. Deploy multi-cluster environment with RBAC enabled:
`hack/run-integration-tests.sh --test-suite frontend-multi-primary --setup-only true`
2. Disable access for the logged in user to the west cluster
`kubectl delete clusterrolebindings --context kind-west kiali-testing-user`
3. Visit mesh page
Fixes https://github.com/kiali/kiali/issues/7455

Mesh page throws error when one of the clusters is inaccessible

---

hack/istio/install-bookinfo-demo.sh
hack/istio/kustomization/bookinfo-ppc64le.yaml
hack/istio/kustomization/bookinfo-s390x.yaml

IBM images in the Kiali scripts are pretty old (2.0.0)
https://github.com/kiali/kiali/tree/v1.73/hack/istio/kustomization
so they needs to be updated to be aligned with MTT images here https://github.com/maistra/maistra-test-tool/blob/main/images.yaml

[OSSM-6833] Update IBM images

---

business/istio_status.go
config/config.go
frontend/src/pages/Overview/ControlPlaneBadge.tsx
handlers/istio_status.go
mesh/api/testdata/test_mesh_graph.expected

There can be a potential issue in gateways discovery, as Ingress and Egress Gateways can be in a different namespaces.
Made 2 separate configurations for IngressGatewayNamespace and EgressGatewayNamespace.
Make sure that Istio Ingress Gateway is installed in 'istio-system' but the pod is not running.
Verify that Kiali component status ill display a warning.
Install Ingress gateway into different namespaces than 'istio-system' and make sure pod is running.
Set 'ingress_gateway_namespace' config value to the correct namespaces.
Verify that the Inress component is recognized and not showing any warning.
The same steps for Egress Gateway.
Fixed automation tests.
https://github.com/kiali/kiali/issues/7501

Gateway Namespace divided into Ingress and Egress.

---

tests/integration/tests/no_istiod_test.go
tests/integration/utils/kiali/instance.go
tests/integration/utils/kiali/kiali_client.go
tests/integration/utils/kube/util.go

- Update the way the Kiali CR is updated (Not working on IBM clusters) for no istiod tests
- Do proper cleanup 
`make test-integration -e URL=https://kiali-istio-system.apps.ppc64le-qe54c.psi.redhat.com -e TOKEN=sha256~2ULKI2rGCIaEg6P0_PD89VWzDaBx8TEUFiKUHsw0xrk -e 'GO_TEST_FLAGS=-run="TestNoIstiod"'`
N/A

[1.73] Update the way the Kiali CR is updated for no istiod tests 

---

business/checkers/k8sgrpcroute_checker.go
business/checkers/k8sgrpcroutes/no_k8sgateway_checker.go
business/checkers/k8sgrpcroutes/no_k8sgateway_checker_test.go
business/checkers/k8shttproute_checker.go
business/checkers/k8shttproutes/no_k8sgateway_checker.go
business/checkers/k8shttproutes/no_k8sgateway_checker_test.go
business/istio_config.go
kubernetes/cache/kube_cache.go
kubernetes/istio.go
models/istio_validation.go
models/namespace.go
tests/data/k8sgateway_data.go
tests/integration/tests/config_validations_test.go

K8s HTTPRoutes and GRPCRoutes can be created in a different namespace than K8sGateway exists and is referred in a parentRef.
For having access to K8sGateway from different namespace:
1. Gateway should be marked by label `shared-gateway-access: "true"`.
2. Namespace where HTTPRoute is created should also be labeled `shared-gateway-access: "true"`.
Then the HTTPRoute with a 'parentRefs' to a K8sGateways from different namespace will be recognized. Otherwise Error `KIA1401 Route is pointing to a non-existent K8s gateway` will be shown.
Fixed GRPCRoutes showing. Added tests.
More info at https://gateway-api.sigs.k8s.io/guides/multiple-ns/
Added cross namespace validation for GRPCRoute and HTTPRoute objects which point to K8sGateways from different namespace.
GRPCRoute is GA, not experimental. …

Added cross-namespace validations into K8s Routes.

---

design/KEPS/namespace-discovery/proposal.md

This is consistent with how Istio and Kubernetes both specify them:
* Istio selectors: https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#k8s-io-apimachinery-pkg-apis-meta-v1-LabelSelector
* Kubernetes selectors: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#resources-that-support-set-based-requirements
This also will make things easier to code up in the server since we need to look at both Kiali AND Istio discovery selectors. It will be nice to have the same yaml parsing for both.

use camelCase for set-based discovery selectors

---

hack/istio/functions.sh
hack/istio/install-testing-demos.sh

Sometimes (on some platforms), not every demo application has a sidecar which causes test failures. 
I suspect that the install script starts patching deployment CRs with sidecar annotation, however, the deployments are not ready yet, or, starts restarting the pods before the annotation is there ( so no sidecar after the restart ).
- So the script must wait until all pods are ready in the namespace (without sidecars) before enabling sidecar infections.
- Added also get all pods after the script is done to identify this type of issue in the future from the log.
Backport is not needed since this is only maistra-related (which is removed in the next branches).

[v1.73] Fix missing sidecars in some demo applications

---

frontend/package.json
frontend/yarn.lock

This PR updates some frontend dev dependencies that do not affect Kiali runtime.
List of updates fixed:
- [OSSM-6575](https://issues.redhat.com/browse/OSSM-6575)
- [OSSM-6647](https://issues.redhat.com/browse/OSSM-6647)
1. Verify that build of Kiali works fine.
2. Verify that you can run Kiali locally.
N/A

Update frontend dev dependencies

---

config/config.go
config/config_test.go
kubernetes/cache/cache.go
kubernetes/client_factory.go
kubernetes/client_factory_test.go
kubernetes/testing.go
store/expiration_store.go

When the auth strategy is `anonymous` or `openid` with rbac disabled, Kiali uses its own service account client to talk to the kube API. This commit ensures for these auth strategies that the client factory will always use the service account client rather than creating a new client with the kiali service account token.
Unit tests created.
Fixes #7542

Always return service account clients when rbac disabled

---

frontend/src/services/Api.ts
frontend/src/types/Auth.ts

The OpenShift console blocks any non-GET request that does not contain CSRF token in the request header. For this reason OSSMC has to add CSRF token in the non-GET request header to avoid a `403 Forbidden` response.
**Kiali**: This PR does not affect Kiali
**OSSMC**:
1. Execute `./hack/crc-openshift.sh start` to launch an OpenShift cluster
2. Install Istio via `./hack/istio/install-istio-via-istioctl.sh` and bookinfo demo `./hack/istio/install-bookinfo-demo.sh -tg -c oc`
3. cd to the kiali/kiali local repo and run this to prepare the image registry: `make cluster-status`
4. Look at the output of that make command to find the login command to the image registry and run that (it will be something like `podman login --tls-verify=false -u kubeadmin -p $(oc whoami -t) …

Add CSRF token to OSSMC non-GET request header

---

hack/hooks/pre-commit.sh

When a developer adds a new i18n label (e.g., t('label')), translation files must be re-generated with the new i18n statements. To avoid committing without the new i18n statements, this PR updates the pre-commit hook to re-generate the translation files and ensure that no new i18n statements remain uncommitted.
1. Add a new i18n label (e.g., change `Log In` to `t('Log In')` in [LoginPage.tsx](https://github.com/kiali/kiali/blob/86d5778217d5784aeb8bfbe4f6d712980378a91f/frontend/src/pages/Login/LoginPage.tsx#L191)).
2. Attempt to create a commit.
3. Verify that the commit is aborted because new i18n statements have not been committed and `translation.json` is modified with the new i18n statement.
N/A

Verify uncommitted new i18n statements

---

deploy/docker/Dockerfile-cypress

Update the Cypress/base Docker image to Node 20 in the GitHub workflow `test-images-update-latest`. This workflow is currently failing because Kiali has been updated recently to Node 20.

Update cypress/base docker image to Node 20

---

business/workloads.go
kubernetes/cache/kube_cache.go
kubernetes/cache/kube_cache_test.go

Retrieving Pods and Services comes with a lot of additional info which is not used in Kiali.
Added WithTransform to trim those objects and return only used fields.
Removed deprecated 'fetchWorkloads' method and replaced by 'fetchWorkloadsFromCluster'.
Full Regression test, including health checks of Workloads, Services.
n/a, existing tests should pass.
Running Kiali perf tests does show only slightly improvements.
https://github.com/kiali/kiali/issues/7017

Added WithTransform for Pods and Services.

---

hack/crc-openshift.sh

Modify `crc-openshift.sh` script to upgrade the CRC version to 4.16
Execute `./hack/crc-openshift.sh start` and verify that OpenShift CRC version 4.16 is installed correctly
N/A

Upgrade CRC to version 4.16

---

hack/istio/install-bookinfo-demo.sh

Apply the correct namespace as this is creating the additional services in the default namespace.
- Verify no additional services are created in the default namespace.
- Verify the graph works as expected: 
Waypoint e2e added in a follow up PR.
N/A

Include namespace in service versions yaml from Ambient hack bookinfo script

---

frontend/cypress/integration/common/hooks.ts
frontend/cypress/integration/common/overview.ts
frontend/cypress/integration/common/workloads.ts
frontend/cypress/integration/featureFiles/apps.feature
frontend/cypress/integration/featureFiles/overview.feature
frontend/cypress/integration/featureFiles/workloads.feature

The `sleep` application is scaled down in one test but it does not scale up after the test, which causes failures in the next tests.
The test `The idle status of a logical mesh application is reported in the list of applications` in the `apps.feature` scale down `sleep` application, so before the `services.feature` tests start, the `sleep` application is installed again (because there is no sleep pod ready) by the hack script which causes restarting of Kiali pod. 
However, the session had already been saved before that, so after the Kiali restart, the tests could not continue because they contained old session info.
ref.: https://issues.redhat.com/browse/OSSM-6835 and also https://issues.redhat.com/browse/OSSM-6843 ( the big number of restarts were already fixed by …

[v1.73][OSSM-6835][OSSM-6843] Fix for cypress flakiness on OCP 4.16

---

frontend/cypress/integration/common/authorization.ts
frontend/cypress/integration/common/navigation.ts
frontend/cypress/integration/featureFiles/authorization.feature

Add multi cluster no access tests for istio configurations
- `hack/run-integration-tests.sh --test-suite frontend-multi-primary --setup-only true`
- Run `cypress:run:multi-primary`
e2e
Fixes #7617

Update cypress tests

---

frontend/package.json
frontend/src/actions/JaegerThunkActions.ts
frontend/src/actions/LoginThunkActions.ts
frontend/src/app/StartupInitializer.tsx
frontend/src/components/CytoscapeGraph/TrafficAnimation/TrafficRenderer.ts
frontend/src/components/Details/__tests__/DetailObject.test.tsx
frontend/src/components/Details/__tests__/__snapshots__/DetailObject.test.tsx.snap
frontend/src/components/FilterList/FilterComponent.tsx
frontend/src/components/IstioConfigPreview/EditorPreview.tsx
frontend/src/components/Kiosk/KioskActions.ts
frontend/src/components/Metrics/IstioMetrics.tsx
frontend/src/hooks/services.ts
frontend/src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
frontend/src/pages/Mesh/MeshPage.tsx
frontend/src/pages/Overview/OverviewPage.tsx
frontend/src/pages/WorkloadDetails/WorkloadPodLogs.tsx
frontend/src/services/Api.ts
frontend/src/services/__tests__/ApiMethods.test.tsx.ts
frontend/src/store/Selectors/GraphData.ts
frontend/src/types/AceValidations.ts
frontend/src/types/Api.ts
frontend/src/utils/AlertUtils.ts
frontend/yarn.lock

Update axios 1.7.4.
It required: 
- Upgrade typescript version as the axios module was giving an error from typescript and required the upgrade from 3 to 4 (Updated to the one in master). 
- Upgrade source files due to library upgrades (Mainly axios and typescript).
- Add transformIgnorePatterns (Some tests failing) 
- Upgrade axios-mock-adapter
N/A
Ref. https://github.com/kiali/kiali/pull/7641 backport v1.65

[v1.65] Update axios version

---

frontend/cypress/integration/common/hooks.ts
frontend/cypress/integration/featureFiles/istio_config.feature

After `@istio-config` test, there are leftovers resources in the istio namespace which block all communication after test suite is done
ref.: https://issues.redhat.com/browse/OSSM-6967
2 runs in a row without SMCP reinstalling:
1. https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/kiali/job/test-jobs/job/kiali-cypress-tests/2915/
2. https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/kiali/job/test-jobs/job/kiali-cypress-tests/2916/

[v1.73][OSSM-6967] Clean up created resources in istio namespace after test

---

frontend/cypress/integration/featureFiles/overview.feature

This backport PR https://github.com/kiali/kiali/pull/7627 from 1.73 returned `@error-rates-app` which was removed by https://github.com/kiali/kiali/pull/7321

Revert regresion introduced by backport #7627

---

frontend/src/index.tsx

In the React Router upgrade to v6 (https://github.com/kiali/kiali/pull/7482), we have to re-implement a feature provided by the previous v5 version, but not by v6.
The feature is that if you add a basename for your router (in our case `/console`), React Router v5 added it automatically when you navigate to the root URL (e.g., `http://localhost:20001/kiali`). However, this is not the case with v6. Therefore, we have to force the navigation to /console if this basename is not included in the URL pathname.
More info here: https://www.github.com/remix-run/react-router/issues/8427
In that PR, we missed that URL parameters should be included in the navigation to `/console` because Kiali takes these into account in the OpenShift authentication process (e.g. `openshift_error` url parameter). This …

Include url parameters on router basename redirect

---

.github/workflows/tag-creator.yml

Remove the extra code from the `tag-creator` workflow added for Kiali versions `v1.24` and `v1.36`, which are currently unsupported. Yaml formatted with pre-commit hook.
Tested in my fork (https://github.com/ferhoyos/kiali/actions/runs/10347091079)

Remove unsupported Kiali versions from tag creator workflow

---

hack/istio/functions.sh
hack/istio/install-bookinfo-demo.sh
hack/istio/install-travel-agency-demo.sh

Update bookinfo and travel demo script in order to check the Istio version before create a waypoint and use the x (experimental) for Istio < 1.23.
- Verify the waypoint proxy is created:
- Install travels demo (ztunnel and waypoint): `istio/install-travel-agency-demo.sh -c kubectl -ei false -di travel-control,travel-agency,travel-portal -w true`
- Verify the waypoint proxy is created:
N/A
Ref. https://github.com/kiali/kiali/issues/7624

[Ambient] Update bookinfo script for Istio 1.23 and waypoints

---

.github/workflows/config/.golangci.yml

Update deprecate options in github golang workflow
No warning messages in "Verify Code Linting" step in backend build github action
N/A
Fixes https://github.com/kiali/kiali/issues/7663

Update deprecate options in github golang workflow

---

kubernetes/filters_test.go
kubernetes/types.go
kubernetes/types_test.go
tests/data/service_data.go

In istio 1.20 these are `map[string]struct{}` but in earlier versions they are `map[string]bool` so this change implements some custom json unmarshaling to handle both.
Deploy Kiali 1.73 with istio 1.20. Create a `ServiceEntry` with `exportTo` set:
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
name: se-kiali-test
namespace: kialitest
spec:
exportTo:
- .
- istio-system
hosts:
- www.example.com
location: MESH_EXTERNAL
ports:
- name: https
number: 443
protocol: HTTPS
targetPort: 443
resolution: DNS
```
Not covered.
Relates to https://github.com/kiali/kiali/issues/6856

[v1.73] Handle structs or bools when unmarshaling service entries from the istio registry

---

business/mesh.go
business/mesh_test.go
config/config.go
frontend/src/components/DebugInformation/DebugInformation.tsx
frontend/src/config/ServerConfig.ts
frontend/src/pages/Mesh/target/TargetPanelControlPlane.tsx
frontend/src/pages/Mesh/target/TargetPanelNamespace.tsx
frontend/src/pages/Overview/CanaryUpgradeProgress.tsx
frontend/src/pages/Overview/OverviewPage.tsx
frontend/src/pages/Overview/OverviewTrafficPolicies.tsx
frontend/src/types/ErrorRate/__testData__/ErrorRateConfig.ts
frontend/src/types/IstioObjects.ts
frontend/src/types/ServerConfig.ts
frontend/src/types/__testData__/HealthConfig.ts
handlers/config.go
istio/discovery.go
istio/kubernetes.go
mesh/api/testdata/test_mesh_graph.expected
mesh/generator/generator.go
models/istio_canaries.go

Removed `ExternalServices.Istio.IstioCanaryRevision` configuration usage, now Kiali checks if there are Istiod pods with  `istio.io/rev=canary` and `istio.io/rev=default` labels.
Install Istio default.
Install Istio 1.22.2.
Install bookinfo.
Install Istio 1.22.3.
In Kiali UI you should be able to canary upgrade downgrade your data plane namespaces.
In Mesh page, the piechart is removed for dataplane.
In Mesh page, the piechart is changed to support multiple revisions.
Unit tests are modified to support listing istiod pods.
https://github.com/kiali/kiali/issues/7515

Canary versions autodiscover

---

graph/telemetry/istio/appender/service_entry.go
graph/telemetry/istio/appender/service_entry_test.go

Fixes #7589
Ensure that when an se-service node is shared by (i.e. has edges from) nodes on different clusters, that each cluster gets its own service entry nodes (using the cluster-specific SE definitions).
I think this is best tested via the new unit test.  And hopefully by the issue creator in his env.

Fix multicluster service entry scenario

---

mesh/generator/generator.go

Previously `namespaces` were passed to `addInfra` but now `dPNss` is passed so we need to sort that slice instead of `namespaces` before passing them to `addInfra`.
`for i in {1..20}; do go clean -testcache && make test; done`
N/A
N/A

Sort the correct namespaces

---

business/tracing.go
hack/istio/multicluster/deploy-kiali.sh
hack/istio/multicluster/env.sh
hack/istio/multicluster/install-primary-remote.sh
hack/run-integration-tests.sh
hack/setup-kind-in-ci.sh
tracing/tempo/http_client.go

* Update hack scripts and Tempo query_scope
Single cluster: 
- `istio/tempo/install-tempo-env.sh -c kubectl`
- Verify there are traces
Multi cluster (Primary remote): 
- `hack/run-integration-tests.sh --test-suite frontend-primary-remote --setup-only true --tempo true`
- Verify there are traces filtered by cluster
- Add query_scope with valid value and verify there are traces
- Add query_scope with invalida value and verify there are no traces
```
query_scope: 
istio.mesh_id: "mesh-hack"
```
Ref. https://github.com/kiali/kiali/pull/7662

[v1.89] Tempo query scope fix (#7662)

---

graph/telemetry/istio/appender/appender.go
graph/telemetry/istio/appender/istio_details_test.go

Fixes https://github.com/kiali/kiali/issues/7672
Fix a subtle problem in Appender processing in the appender.getTrafficClusters() utility function.  This function depended on the "isInaccessible" node metadata being set. But "isInaccessible" is set in the "Outsider" appender, a Finalizer which is run late in the appender processing, so appenders using this utility prior to the Outsider Finalizer being run, were at risk.
Update appender.getTrafficClusters() to not depend on that node metadata being set.
Updated test code reproduced the issue.

Fix graph appender problem

---

frontend/src/components/CytoscapeGraph/__tests__/GraphScore.test.ts
frontend/src/components/CytoscapeGraph/graphs/GraphStyles.ts
frontend/src/pages/GraphPF/GraphHighlighterPF.ts
frontend/src/pages/GraphPF/GraphPFElems.tsx
frontend/src/types/Graph.ts
graph/config/cytoscape/cytoscape.go
graph/meta.go
graph/telemetry/istio/appender/ambient.go

This PR: 
- Adds a double arrow in the same edge for the waypoint proxies. This aims to simplify the number of edges in the graph
- Fixes patternfly graph to avoid infinite loops on hover: 
This error: 
The specific error cannot be reproduced in master, just when the waypoint appender does not delete the double edges.
Install Kiali and Ambient: 
New tests will be added in a separate PR.
Ref. #7445 
TODO: 
This is just a proposal, but in order to be merged, it would need some improvements like: 
- Traffic animation
- Traffic rate: (It is needed to add …

[ambient] waypoint arrows and PF fix

---

hack/istio/install-istio-via-istioctl.sh

We need to disable ipv6 when installing Ambient because it breaks on minikube when not using docker driver (you get errors that say something like "Command error output: xtables parameter problem: ip6tables-restore: unable to initialize table 'nat'"
To test this:
1. Start minikube with some driver other than docker (our hack script defaults to kvm2, so this is a good test)
```
hack/k8s-minikube.sh start
```
2. Install Istio with Ambient using the hack script
```
hack/istio/install-istio-via-istioctl.sh -c kubectl -cp ambient
```
Istio with Ambient should install successfully now.

[hack] disable ambient cni ipv6

---

tests/integration/utils/kiali/kiali_client.go

The Kiali Integration tests related to `Tracing` are sometimes flaky when Tempo tracing is used (since the older jaeger collector is used for ossm 2.6 / Kiali 1.73, so query to tempo tracing can take longer )
In the Kiali CR, I increased the query timeout to 60s, however, the test uses hardcoded 10s.
This PR increases client timeout to 60s for Tracing and Spans tests. ( to be aligned with downstream pipeline where integration with tempo is tested )
The backport is not needed since the newer Kali version supports Tempo querier, which is faster than the old and, in a little while, deprecated Jaeger querier.
Tested this change 3x against clusters: OCP on OpenStack, ARM, IPv6, ARO, ROSA, IBM P and all integration tests passed. ( so they are not flaky anymore )

[1.73] Fix flaky int tests with tempo tracing

---

frontend/src/components/Metrics/CustomMetrics.tsx

Workload's Custom dashboard's Link to Grafana had hardcoded 'App' instead of checking the object type.
Now it sets 'Workload' for workloads.
Create Custom Dashboard on Grafana side.
Add that custom dashboard into Kiali CR, and make sure `variables` ar also set:
```
custom_dashboards:
- discoverOn: envoy_server_uptime
externalLinks:
- name: grafana
type: grafana
variables:
namespace: "var-namespace"
service: "var-service"
workload: "var-workload"
items:
- chart:
dataType: raw
metricName: envoy_server_uptime
name: Pods uptime
spans: 12
name: grafana-test
runtime: GRAFANA
title: Grafana metrics
```
Workload details should have the 'Graffana metrics' tab with "View in Grafana" link.
Verify that the link contains variables 'var-namespace' and 'var-workload'. The issue was that here there was …

Fixed hardcoded App param for CustomMetrics Links

---

hack/istio/install-sleep-demo.sh
hack/istio/kustomization/bookinfo-ppc64le.yaml
hack/istio/kustomization/bookinfo-s390x.yaml

Upgrade IBM mirror images to the latest one. 
`quay.io/maistra/examples-bookinfo-details-v1:2.6` == `docker.io/istio/examples-bookinfo-details-v1:1.19.1`
Once, they create `s390x` and `ppc64le` variants of the latest upstream one `1.20.2`, the files `bookinfo-ppc64le.yaml` and `bookinfo-s390x.yaml` needs to be updated again. ( so now, it updates the bookinfo to the latest one which are available for IBM) 
Backports of:
- https://github.com/kiali/kiali/pull/7594
- https://github.com/kiali/kiali/pull/7692

[v1.89] Upgrade images for IBM

---

frontend/cypress/integration/common/sidecar_injection.ts

Fix the flaky sidecar injection test by restarting the `sleep` workload when sidecar injection is enabled or disabled in the Kiali Cypress tests.
Verify that the sidecar injection tests pass on an OpenShift console (the same tests already pass in the e2e GitHub Action).
Fixes two flaky tests in the sidecar injection feature scenario.
Fixes #7714

Fix sidecar injection flaky test

---

business/mesh.go
business/namespaces.go
business/tls.go
config/config.go
frontend/cypress/integration/common/mesh.ts
frontend/cypress/integration/featureFiles/mesh.feature
frontend/public/locales/zh/translation.json
frontend/src/pages/Mesh/target/TargetPanelDataPlane.tsx
frontend/src/pages/Mesh/target/TargetPanelMesh.tsx
frontend/src/pages/Mesh/target/TargetPanelNamespace.tsx
frontend/src/pages/Overview/ControlPlaneVersionBadge.tsx
frontend/src/pages/Overview/OverviewPage.tsx
frontend/src/types/Mesh.ts
hack/run-integration-tests.sh
hack/setup-kind-in-ci.sh
istio/discovery.go
istio/discovery_selectors.go
istio/discovery_selectors_test.go
istio/discovery_test.go
istio/kubernetes.go
kubernetes/cache/cache.go
mesh/api/api_test.go
mesh/api/testdata/test_mesh_graph.expected
mesh/config/cytoscape/cytoscape.go
mesh/generator/generator.go
mesh/meta.go
models/mesh.go
models/namespace.go

Adds support for tags to the mesh page. Now when a namespace has a tag that references a controlplane revision, the controlplane will properly have an edge to that dataplane.
This change requires adding `LIST` permissions for `mutatingwebhookconfigurations.admissionregistration.k8s.io`. Multi-cluster Kiali deployments will need to regenerate their remote cluster roles even after they have updated their Kiali helm deployment. However to be more backwards compatible, this change also checks for `LIST` permission to read mutating webhooks and if the kiali service account does not have the permission then a warning will be logged and tags will be ignored.
1. Deploy Kiali
**Deploying with helm/kind:**
Helm chart PR: https://github.com/kiali/helm-charts/pull/279
In helm chart repo with above PR …

Add support for tags in mesh page

---

business/namespaces.go
business/namespaces_test.go
business/openshift_oauth.go
business/openshift_oauth_test.go
handlers/authentication/openshift_auth_controller_test.go

Allows you to run multi-cluster Kiali with mixed openshift and kube clusters in `anonymous` mode.
1. Deploy Kiali on an openshift cluster
```
hack/crc-openshift.sh start                                                                                                                                                          
oc login -u kubeadmin -p kiali https://api.crc.testing:6443 --insecure-skip-tls-verify                                                                                                                                                                                                  
podman login --tls-verify=false -u kiali -p (oc whoami -t) default-route-openshift-image-registry.apps-crc.testing …
```

Check each cluster individually to see if they are openshift in namespace service

---

config/config.go
frontend/src/config/ServerConfig.ts
frontend/src/helpers/LabelFilterHelper.ts
frontend/src/helpers/__tests__/LabelFilterHelper.test.ts
frontend/src/types/ErrorRate/__testData__/ErrorRateConfig.ts
frontend/src/types/ServerConfig.ts
frontend/src/types/__testData__/HealthConfig.ts
graph/telemetry/istio/appender/mesh_check.go
models/workload.go
models/workload_test.go

Added missing `isK8sGateway` check while checking `isGateway` for `MissingSidecar` icon.
Added a new config `K8sGatewayLabelName` in IstioLabels. Currently has a default value as constant.
Setup Istio in ambient mode.
```
./hack/istio/install-istio-via-istioctl.sh -c kubectl -cp ambient 
./hack/istio/install-bookinfo-demo.sh -c kubectl -ai false -tg
kubectl apply -f _output/istio-1.23.0/samples/addons/kiali.yaml
./_output/istio-1.23.0/bin/istioctl x waypoint apply -n bookinfo
```
Go to bookinfo's 'bookinfo-gateway-istio' Workload or Service details.
You should not see the red icon "Out of mesh".
Same in Workload and Services lists page.
unit tests added
https://github.com/kiali/kiali/issues/7720

Added missing K8sGateway label name check for MissingSidecar icon

---

frontend/package.json
frontend/yarn.lock

Update the following frontend dependencies:
- body-parser: 1.20.3
- express: 4.20.0
- micromatch: 4.0.8
- path-to-regexp: 8.0.0
Verify that Kiali works as expected. Passing CI tests should be enough.
N/A
https://issues.redhat.com/browse/OSSM-8094

Update express, path-to-regexp and micromatch dependencies

---

hack/istio/install-sleep-demo.sh
hack/istio/kustomization/bookinfo-ppc64le.yaml
hack/istio/kustomization/bookinfo-s390x.yaml

Upgrade IBM mirror images to the latest one. 
`quay.io/maistra/examples-bookinfo-details-v1:2.6` == `docker.io/istio/examples-bookinfo-details-v1:1.19.1`
Once, they create `s390x` and `ppc64le` variants of the latest upstream one `1.20.2`, the files `bookinfo-ppc64le.yaml` and `bookinfo-s390x.yaml` needs to be updated again. ( so now, it updates the bookinfo to the latest one which are available for IBM) 
Backports of:
- https://github.com/kiali/kiali/pull/7594
- https://github.com/kiali/kiali/pull/7692

Upgrade images for IBM

---

frontend/package.json
frontend/yarn.lock

Backport of PR https://github.com/kiali/kiali/pull/7730 to version 1.73

[v1.73] Update express, path-to-regexp and micromatch dependencies

---

frontend/package.json
frontend/yarn.lock

Backport of PR https://github.com/kiali/kiali/pull/7730 to version 1.65

[v1.65] Update express, path-to-regexp and micromatch dependencies

---

hack/istio/install-bookinfo-demo.sh

Update bookinfo install hack script such that for ambient the two "db" services opt out of the namespace waypoint.  This helps test L4-only traffic.

Update bookinfo install hack script to have db services opt out of waypoint

---

frontend/package.json
frontend/yarn.lock

Update the express dependency to version 4.21.0 to remove version 0.18.0 of the `send` dependency.
Also, I have updated `path-to-regexp` to the latest 1.x release (version 1.9.0), instead of 8.0.0. Both versions meet our requirements, but I believe it is a bit risky to force an upgrade from version 1.x to 8.x.
Check that Kiali works as expected and CI tests pass.
N/A
https://issues.redhat.com/browse/OSSM-8124

Update express dependency (again)

---

frontend/package.json
frontend/yarn.lock

Update `serialize-javascript` dependency to version 6.0.2.
Instead of adding this version to `resolutions` section, I have updated the parent dependencies that import `serialize-javascript` as they were a bit outdated. This will improve the application's security."
Libraries updated:
- `@badeball/cypress-cucumber-preprocessor` to version `20.1.2`.  
- `workbox-webpack-plugin` to version `7.1.0`.
Breaking changes in the major version of both dependencies do not affect us:
- https://github.com/badeball/cypress-cucumber-preprocessor/releases?page=2
- https://github.com/GoogleChrome/workbox/releases
**Bonus:** 
- Align `seed-random` version in `package.json` to download only one version in the application.
Verify that CI tests pass.
https://issues.redhat.com/browse/OSSM-8148

Update serialize-javascript dependency

---

graph/telemetry/istio/appender/response_time.go
graph/telemetry/istio/appender/security_policy.go
graph/telemetry/istio/appender/throughput.go
graph/telemetry/istio/istio.go

partof https://github.com/kiali/kiali/issues/7445
Multiple appenders perform service node injection and could have been affected by the new code preventing injection for ztunnel waypoint edges.  Fortunately, only one required changes, the security appender, and in there we were able to make a fairly simple change.
Before: Note that some of the waypoint edges lack a lock icon and show no mTLS wuth graph find:
After: The waypoint edges show secure mTLS:

Appender work related to waypoint service injection

---

hack/istio/install-bookinfo-demo.sh
hack/istio/sail/README-RELEASE.md
hack/istio/sail/func-addons.sh
hack/istio/sail/func-kiali.sh
hack/istio/sail/func-olm.sh
hack/istio/sail/func-sm.sh
hack/istio/sail/func-tempo.sh
hack/istio/sail/install-ossm-release.sh

These set of scripts will be able to install a full Istio-Kiali setup locally on a vanilla Kubernetes (not OpenShift).
You will get Sail operator and its Istio installation, Kiali operator and Kiali UI, along with Tempo operator and Tempo (for tracing backend and JaegerUI), Grafana, and Prometheus. The external services will have their UIs available assuming your k8s has a LoadBalancer (the steps below will give you that).
Here's how you can try it out.
For those that already have the kiali source repo git cloned locally and this PR branch checked out, here's a quick summary of the commands you can run to see everything... following this will be a more detailed set of instructions that even those that do not have the full source git cloned can run this stuff.
1. `hack/k8s-minikube.sh …

[hack] support Sail on vanilla Kubernetes now that OperatorHub.io has the Sail operator

---

frontend/cypress/integration/common/graph_side_panel.ts
frontend/cypress/integration/featureFiles/graph_side_panel.feature

Add coverage for the summary panel when click on an edge in the graph
Run cypress test graph_side_panel. Also it is running in CI
e2e
Fixes #7762

[cypress] Add coverage for the summary panel when click on an edge in the graph

---

istio/discovery.go

fixes: https://github.com/kiali/kiali/issues/7751

Mesh page: do not show namespaces that fail to match any discovery selector

---

frontend/src/config/Icons.ts
frontend/src/pages/Graph/GraphToolbar/GraphSettings.tsx
frontend/src/pages/Graph/SummaryLink.tsx
frontend/src/pages/Graph/SummaryPanelEdge.tsx
frontend/src/pages/GraphPF/GraphPFElems.tsx

Use right left arrows to indicate the direction:
- Remove "Feature Under Development" For the Graph Display option "Waypoint"
- Display `waypoint`
Ref. #7706

[ambient] Updated styles for waypoint edges summary panel

---

config/config.go
frontend/cypress/integration/common/graph_toolbar.ts
frontend/cypress/integration/featureFiles/graph_toolbar.feature
frontend/src/app/AuthenticationController.tsx
frontend/src/config/ServerConfig.ts
frontend/src/pages/Graph/GraphToolbar/GraphTraffic.tsx
frontend/src/reducers/GraphDataState.ts
frontend/src/services/GraphDataSource.ts
frontend/src/types/ErrorRate/__testData__/ErrorRateConfig.ts
frontend/src/types/Graph.ts
frontend/src/types/ServerConfig.ts
frontend/src/types/__testData__/HealthConfig.ts
graph/options.go
graph/telemetry/istio/appender/aggregate_node.go
graph/telemetry/istio/appender/aggregate_node_test.go
graph/telemetry/istio/appender/ambient.go
graph/telemetry/istio/appender/response_time.go
graph/telemetry/istio/appender/response_time_test.go
graph/telemetry/istio/appender/security_policy.go
graph/telemetry/istio/appender/security_policy_test.go
graph/telemetry/istio/appender/throughput.go
graph/telemetry/istio/appender/throughput_test.go
graph/telemetry/istio/istio.go
graph/telemetry/istio/util/util.go

Closes #6900 
Add to the Graph Traffic Dropdown, allowing the user to select no ambient reporting, full ambient reporting, only waypoint or only ztunnel.  This should help users identify or remove ambient-reported traffic.

[ambient] Add to the Graph Traffic Dropdown

---

hack/istio/sail/README-RELEASE.md
hack/istio/sail/func-tempo.sh

Update tempo resources for Sail hack script.
I think this resources specification are not enough for Tempo operator. This resources specification splits the resources between all the components, which is not enough for the Tempo query-frontend component. 
The tests can be done with the url and a simple query (With master code), for one minute: 
http://localhost:3200/api/search?end=1727106314&q={+.service.name+=+%22reviews.bookinfo%22}&start=1727106301
It takes around ~30 request to be OOM killed. 
In the query that we do, takes ~10 requests to be OOM killed (There is more data requested in order to create the chart): 
`http://localhost:3200/api/search?end=1727106314&limit=100&q={+.service.name+=+"reviews.bookinfo"++&&+.istio.mesh_id+=+"cluster.local"+++}+&&+{++}+|+select(status,+.service_n …

Update tempo resources for Sail hack script

---

frontend/src/actions/GraphThunkActions.ts
frontend/src/pages/Graph/GraphToolbar/GraphFindPF.tsx
frontend/src/pages/GraphPF/GraphPF.tsx
frontend/src/pages/GraphPF/GraphPagePF.tsx
frontend/src/pages/Mesh/Mesh.tsx
frontend/src/pages/Mesh/toolbar/MeshFind.tsx

Fixes https://github.com/kiali/kiali/issues/7781
- Fix issue with bookmarked find/hide not being evaluated in PFT graph or Mesh page
@leandroberetta - This fix also provides the infrastructure for PFT cypress tests to access the graph in the same way as the Mesh Page cypress tests.
To Test:
1. Define a graph find or hide expression. It should work fine.
2. Do a full refresh of the Bookmarked page
Before: The expression is populated in the toolbar but does not get applied until the first refresh.
After: The expression is populated in the toolbar and gets applied immediately.

Fix issue with bookmarked find/hide not being evaluated in PFT graph or Mesh page

---

config/config.go
frontend/cypress/integration/common/authorization-pf.ts
frontend/cypress/integration/common/graph-pf.ts
frontend/cypress/integration/common/graph_context_menu-pf.ts
frontend/cypress/integration/common/graph_display-pf.ts
frontend/cypress/integration/common/graph_find_hide-pf.ts
frontend/cypress/integration/common/graph_side_panel-pf.ts
frontend/cypress/integration/common/graph_toolbar-pf.ts
frontend/cypress/integration/common/mesh.ts
frontend/cypress/integration/featureFiles/graph_toolbar-cy.feature
frontend/src/config/ServerConfig.ts
frontend/src/pages/GraphPF/GraphPagePF.tsx
frontend/src/pages/Mesh/MeshPage.tsx
frontend/src/types/ErrorRate/__testData__/ErrorRateConfig.ts
frontend/src/types/ServerConfig.ts
frontend/src/types/__testData__/HealthConfig.ts
hack/istio/multicluster/deploy-kiali.sh
hack/setup-kind-in-ci.sh

Closes #7785 
- Set default graph impl to PFT
- also remove some old, hidden mesh page options
- maintains cytoscape in CI until we want to change the tests to PFT (WIP)
- fix an issue in the cy/pft test split
- also, this fixes test flakiness introduced in the recent PR to fix find/hide, as well as add support for PFT cypress testing.  That change slightly delayed when the PFT controller was made available to the test code, which could cause a flake when the test tried to access it prematurely.  This should ensure that the controller is available prior to the test trying to use it.

Set default graph impl to PFT

---

frontend/src/pages/GraphPF/GraphPF.tsx

Fixes https://github.com/kiali/kiali/issues/7770
Only pre-select node-graph node when the graph data has actually changed (i.e. for a new node graph, or when there is a structural change on refresh).
- also, downgrade some logging from debug to trace
Test:
1. Go to node graph
2. see side panel is set to selected target node
3. select an edge or different node (click on it)
4. see side panel change as expected
5. refresh, or wait for auto-refresh
- Before:
- side panel snaps back to select the original node-graph node
- After:
- It should remain showing the selected element

[pft graph] fix node-graph selection snap-back issue

---

hack/k8s-minikube.sh

due to https://github.com/oauth2-proxy/oauth2-proxy/issues/2802
Without this fix, some of the molecule tests fail

[hack] k8s-minikube.sh to pin to oauth v7.6.0 

---

config/config.go
config/config_test.go

This also adds the ability to put customdashboards.prometheus credentials in secrets
fixes: https://github.com/kiali/kiali/issues/7795

be able to put username in secrets

---

frontend/src/pages/GraphPF/elements/extendedBaseEdge.ts
frontend/src/pages/GraphPF/layouts/ExtendedDagreLayout.ts
frontend/src/pages/GraphPF/layouts/layoutFactory.ts

Fixes #7780
Apply our own bendpoint logic to parallel edges.  Use simple bendpoints and update them when needed (after drag).
@josunect This is what I came up with to solve the parallel edge issue.  Read the [issue description](https://github.com/kiali/kiali/issues/7780) and it talks about the problem and two options.  This is the second option.  We could still look at option 1 in the future, but I ended up going with something that was a smaller overall change.  The coding was a little tricky, but it's not as big as trying to merge edges, both in implementation and in UX impact

Apply our own bendpoint logic to parallel edges

---

frontend/src/pages/GraphPF/GraphPFElems.tsx
frontend/src/pages/GraphPF/styles/styleGroup.tsx
frontend/src/pages/GraphPF/styles/styleNode.tsx
frontend/src/styles/GlobalStyle.ts

This PR hides the node kebab context menus in the PFT graph using CSS, as it is not possible to disable them within patternfly topology
I have been able to center the text in the label, but I couldn't reduce the size of the label's rectangle since it is defined programmatically in the `patternfly-topology` library. However, the labels still look nice.
**Bonus:** Fine-tune the CSS of the gateway icon within the gateway label node.
Look that the kebab menus are hiding in the pft graph and only the right-click action can display the context menu.
Closes #7803

Hide node kebab context menus from pft graph

---

frontend/src/pages/GraphPF/GraphPFElems.tsx
frontend/src/pages/GraphPF/styles/styleNode.tsx
frontend/src/styles/GlobalStyle.ts

PR https://github.com/kiali/kiali/pull/7805 introduces a small margin CSS issue in the Firefox browser. 
This PR fixes this small margin issue.
Verify that the margin issue is fixed in the Firefox browser
N/A
https://github.com/kiali/kiali/issues/7803

Fix margin issue in the label graph in Firefox

---

frontend/src/components/IstioWizards/GatewaySelector.tsx
frontend/src/components/IstioWizards/ServiceWizard.tsx

Refactor: Use Select from @patternfly/react-core instead of FormSelect
Render GatewaySelector component
Issue : https://github.com/kiali/kiali/issues/7277

Refactor : Gateway Selector - Form Select to Select

---

frontend/src/components/BreadcrumbView/BreadcrumbView.tsx

Breadcrumb name was wrong for Object details, such as App, Workloads and Services.
Before:
After:
https://github.com/kiali/kiali/issues/7817

Fixed breadcrumb object name

---

business/workloads.go

Fixed DaemonSet workload fetching error message in business/workloads.go.
We use the alternative DaemonSet controller for `controller-main` workload and got the confusing error:
```
{"level":"error","time":"2024-10-15T13:25:37Z","message":"Workload controller-main is not found as Deployment"}
```
Deploy the alternative DaemonSet controller like [kruise](https://openkruise.io/docs/user-manuals/advanceddaemonset/). Then there must be an error:
```
{"level":"error","time":"2024-10-15T13:25:37Z","message":"Workload controller-main is not found as DaemonSet"}
```
—
—

Fixed DaemonSet workload fetching error message

---

frontend/src/pages/GraphPF/GraphPF.tsx
frontend/src/pages/GraphPF/MiniGraphCardPF.tsx
frontend/src/pages/Mesh/Mesh.tsx
frontend/src/styles/GraphStyle.ts

Currently, active options in the patternfly graph toolbar appear disabled. This is not ideal from a UX perspective, as they can be mistaken for actually disabled toolbar options. Therefore, this PR changes the toolbar icons to blue when they are active and slightly increases their size to better differentiate them from similar inactive icons. 
Before:
After: 
To be consistent with the Cytoscape graph, options to hide edges can be activated and deactivated by clicking the same toolbar option (which was not possible with the disabled approach).
1. Go to graph page
2. Verify that the toolbar looks fine with the new active icon styles.
N/A

Graph toolbar: Replace disabled with active style

---

frontend/src/pages/GraphPF/GraphPF.tsx
frontend/src/pages/GraphPF/MiniGraphCardPF.tsx

This PR enables the rank feature in the patternfly graph
1. Go to the traffic graph
2. Click on the `Display` dropdown, select `Rank` option, followed by `Inbound Edges`
3. Select any node in the graph
4. Verify that a rank value is displayed in the side panel
Cypress test implemented in https://github.com/kiali/kiali/pull/7799

Enable rank feature in the patternfly graph

---

config/config.go
frontend/src/types/StatusState.ts
frontend/src/types/Tracing.ts
frontend/src/utils/tracing/UrlProviders/Jaeger.ts
frontend/src/utils/tracing/UrlProviders/index.ts
hack/istio/tempo/install-tempo-env.sh

Adds a new tempo config option to specify the tracing url format. So it is possible to link to the Jaeger UI or to a Grafana datasource.
- Create an environment with Tempo. It can be done with: `hack/istio/tempo/install-tempo-env.sh -c kubectl`
- Install Kiali in the cluster (needs the operator PR https://github.com/kiali/kiali-operator/pull/830 
- Update the Tracing settings: 
Using the Grafana Datasource: 
```
grafana:
enabled: true
external_url: 'http://localhost:13000'
health_check_url: ''
internal_url: http://grafana.istio-system:3000
tracing:
enabled: true
external_url: ''
internal_url: http://localhost:3200
provider: tempo
tempo_config:
datasource_uid: ''
org_id: ''
url_format: ''
```
The Traces tab should contain traces, and the "View in tracing" should redirect to …

[Tempo] View in Tracing url

---

frontend/src/pages/Graph/GraphToolbar/GraphFindPF.tsx
frontend/src/pages/GraphPF/GraphPF.tsx
frontend/src/pages/GraphPF/GraphPagePF.tsx
frontend/src/pages/Mesh/Mesh.tsx
frontend/src/pages/Mesh/MeshElems.tsx
frontend/src/pages/Mesh/MeshPage.tsx
frontend/src/pages/Mesh/components/meshComponentFactory.tsx
frontend/src/pages/Mesh/toolbar/MeshFind.tsx
frontend/src/pages/Mesh/toolbar/__tests__/MeshFind.test.tsx

Fix issue with laying out on an element change in both the traffic graph and the mesh page.
Also, fix a resize issue for mesh page.
Fixes https://github.com/kiali/kiali/issues/7835
To test:
- try the repro steps in the issue.  
- for the resize issue on the mesh page, try collapse and expand of the side panel
- also try resizing, graph hide/unhide (refresh with hide), eliminating/adding things via the Traffic dropdown, refreshing when you have changed the default layout (like zooming in/out, dragging etc) and make sure your custom view is maintained (unless there is an element change).

[mesh page] [graph] Fix issue with laying out on an element change

---

frontend/yarn.lock

Upgrade http-proxy-middleware to 2.0.7
https://issues.redhat.com/browse/OSSM-8281

[v1.89] Upgrade http-proxy-middleware to 2.0.7

---

frontend/src/pages/GraphPF/GraphPFElems.tsx
frontend/src/pages/GraphPF/MiniGraphCardPF.tsx
frontend/src/pages/GraphPF/styles/styleNode.tsx
frontend/src/pages/Mesh/MeshElems.tsx
frontend/src/pages/Mesh/MeshHighlighter.ts
frontend/src/pages/Mesh/components/meshComponentFactory.tsx
frontend/src/pages/Mesh/styles/MeshEdge.tsx
frontend/src/pages/Mesh/styles/MeshNode.tsx
frontend/src/styles/GlobalStyle.ts

This PR changes some mesh topology styles for a better appearance.
- Keep other nodes highlighted when a mesh node is selected or hovered. This feature is useful in the traffic graph, where many nodes are present, but it's less helpful in the mesh graph when there are only a few nodes.
- Hovering over an edge does not change its style. Since edges on the mesh page are not clickable, it's better to maintain a consistent CSS style to avoid user confusion.
- Don't hide the icons at low detail levels. The icons remain recognizable even at the lowest zoom levels.
- Scale the nodes at low detail levels:
- The selection stroke is wider and blue like in the traffic graph:
- Edges connected to failure nodes are thicker, making the failures more visible:
**Bonus:**
- Adjusted the margin for the …

Fine-tune Mesh topology style

---

kubernetes/cache/kube_cache.go
kubernetes/cache/kube_cache_test.go
kubernetes/types.go

The `apiVersion` value is added to the Istio config object in those use cases when the value is not cached previously (e.g., the Istio object is created outside of Kiali using `kubectl`.
I have also fixed some typo for ReferenceGrant `version`, whose value is `v1beta1`, not `v1`.
1. Create any Istio config object from kubectl, for example this simple AuthorizationPolicy:
```
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
name: test
labels: {}
annotations: {}
spec: {}
```
2. From your browser, open the Network section of Chrome/Firefox Dev Tools (click F12 + Network tab)
3. Navigate to the `Istio Config` page
4. In the Network tab section, click on the request `config?validate=true`
5. Verify that the `apiVersion` value of the AuthorizationPolicy …

Add APIVersion value to the Istio config object

---

hack/istio/install-bookinfo-demo.sh
hack/istio/install-testing-demos.sh
tests/integration/assets/bookinfo-workloads.yaml

Fix for https://github.com/kiali/kiali/issues/7837
Verified on clusters:
| OCP  | Kiali integration tests | Kiali cypress tests |
| ------------- | ------------- | ------------- |
| OCP 4.18-ec2-fips | [ok](https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/kiali/job/test-jobs/job/kiali-integration-tests/2978/) | [ok](https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/kiali/job/test-jobs/job/kiali-cypress-tests/3201/) |
| OCP 4.17 GA | [ok](https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/kiali/job/test-jobs/job/kiali-integration-tests/2979/) | [ok](https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/kiali/job/test-jobs/job/kiali-cypress-tests/3202/) |
| OCP 4.14 -fips | …

[v1.65] Fix sleep hack and TestDiscoverWorkload test to run on the latest fips ocp cluster

---

hack/istio/install-bookinfo-demo.sh
hack/istio/install-sleep-demo.sh

Additional fix for bookinfo regarding 4.18 fips cluster changes (https://github.com/kiali/kiali/issues/7837). (Needed for ossm 2.5 testing which uses 1.17.0 bookapp images, forgot about that in PR https://github.com/kiali/kiali/pull/7838 where only ossm 2.6 was used [and 1.19.1 bookapp images which have `USER 1000`]) 
Verified on clusters:
| OCP  | Kiali integration tests | Kiali cypress tests |
| ------------- | ------------- | ------------- |
| OCP 4.18-ec2-fips | [ok](https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/kiali/job/test-jobs/job/kiali-integration-tests/2982) | [ok](https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/kiali/job/test-jobs/job/kiali-cypress-tests/3203/) |
| OCP 4.17 GA | …

[v1.73] Adapt bookinfo for 4.18 fips

---

frontend/cypress/integration/common/app_details_multicluster-pf.ts
frontend/cypress/integration/featureFiles/app_details_multicluster_graph-pf.feature
frontend/cypress/integration/featureFiles/workloads_details_multicluster_graph-pf.feature
frontend/src/index.tsx
frontend/src/pages/Graph/GraphToolbar/GraphFindPF.tsx
frontend/src/pages/GraphPF/GraphHighlighterPF.ts
frontend/src/pages/GraphPF/GraphPF.tsx
frontend/src/pages/GraphPF/GraphPFElems.tsx
frontend/src/pages/GraphPF/GraphPagePF.tsx
frontend/src/pages/GraphPF/MiniGraphCardPF.tsx
frontend/src/pages/GraphPF/TracePF.ts
frontend/src/pages/Mesh/Mesh.tsx
frontend/src/pages/Mesh/MeshElems.tsx
frontend/src/pages/Mesh/MeshHighlighter.ts
frontend/src/pages/Mesh/toolbar/MeshFind.tsx

Protect against minigraph problems when the parent detail page component is changing its target element.
This is a semi-hack to prevent a major refactoring of how we work with the GraphDatasource object in the detail pages. Because we re-use the GraphDatasource, and it's an asynch fetch, it's possible that if the component gets re-used for a new workload/service/app, that things get out of sync.
In short, detect a mismatch between the target component and the datasource, and avoid updating the graph until things get back in sync.
Also:
- remove an unwanted dependency on "graphData" in effect that responds to a change in selectedIds
- slightly shorten the focus node flashing.
- suppress a bunch of console warnings.
Fixes https://github.com/kiali/kiali/issues/7839

Fix issue with minigraph node navigation

---

frontend/cypress/integration/common/graph_display-cy.ts
frontend/cypress/integration/common/graph_display-pf.ts
frontend/cypress/integration/common/graph_replay.ts
frontend/cypress/integration/common/graph_toolbar-cy.ts
frontend/cypress/integration/common/graph_toolbar-pf.ts
frontend/cypress/integration/common/hooks.ts
frontend/cypress/integration/common/mesh.ts
frontend/cypress/integration/common/overview.ts
frontend/cypress/integration/common/wizard_request_routing.ts

This small PR prevents multiple executions of the same Before function within Cypress tests.
Before:
After:

A single Before statement in Cypress is enough

---

hack/crc-openshift.sh

Modify `crc-openshift.sh` script to upgrade the CRC version to 2.42.0, which installs OpenShift 4.17.0
Execute `./hack/crc-openshift.sh start` and verify that OpenShift CRC version 4.17.0 is installed correctly
N/A

Upgrade CRC to 2.42.0 - OpenShift 4.17

---

make/Makefile.olm.mk

There is a bug in OLM v0.29.0 that causes OLM not to start. Use v0.28.0 for now until OLM is fixed.
See: https://github.com/operator-framework/operator-lifecycle-manager/issues/3419
(note: we need this PR because as of now our CI molecule test runs are failing because of this issue)

[ci] fallback to olm v0.28.0 due to bug in v0.29.0

---

.github/workflows/molecules.yml
hack/ci-kind-molecule-tests.sh
make/Makefile.olm.mk

OLM has a bug that causes it to be uninstallable so we need a way to install an older version to continue being able to test.
Right now the github action molecule tests are failing - that's the reason why I'm doing this now.
See https://github.com/operator-framework/operator-lifecycle-manager/issues/3419#issuecomment-2451589801
(when that bug is fixed and a new OLM release is published, we will follow up and reset to the "latest" olm release in our tests by merging this second PR: https://github.com/kiali/kiali/pull/7881)

Be able to tell our test scripts what version of OLM to use.

---

frontend/src/config/ServerConfig.ts
graph/telemetry/istio/appender/security_policy.go
graph/telemetry/istio/appender/security_policy_test.go

Fixes #7811 
Handle Security appender Ambient corner case. For ztunnel-to-sidecar traffic, we get source reporting only.  Historically we always use destination reporting to determine mtls.
- add necessary queries to security_appender
- unfortunate but I don't see an alternative
- make sure we disable ambient traffic when ambient is not enabled
- this saves unnecessary queries
- update unit test 
Test:
@josunect , you already have the environment because you were the one to figure out the problem :-)  I think I updated the queries as you suggested, to look for ztunnel source telem when needed.  Let me know if this solves the issue for you, and if the solution looks good.  It does add queries, and those queries may often return duplicate reporting (because ztunnel typically reports both …

Handle Security appender Ambient corner case

---

hack/istio/install-bookinfo-demo.sh
hack/istio/install-istio-via-istioctl.sh
hack/istio/install-sleep-demo.sh
tests/integration/assets/bookinfo-workloads.yaml

Fix for https://github.com/kiali/kiali/issues/7837
Verified ( with the latest kiali and istio via `upstream-istio-pipeline`) on clusters:
| OCP  | integration tests | cypress tests
| ------------- | ------------- | ------------- |
| OCP 4.18-ec2-fips | [ok](https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/kiali/job/test-jobs/job/kiali-integration-tests/3006/)  | [ok](https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/kiali/job/test-jobs/job/kiali-cypress-tests/3225/) |
| OCP 4.18-ec2 | [ok](https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/kiali/job/test-jobs/job/kiali-integration-tests/3011/) | [ok](https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/kiali/job/test-jobs/job/kiali-cypress-test …

Fix sleep hack and TestDiscoverWorkload test to run on the latest fips ocp cluster

---

frontend/src/pages/Graph/GraphToolbar/GraphFindPF.tsx
frontend/src/pages/Mesh/toolbar/MeshFind.tsx

PFT Graph and Mesh hide had needed to call e.remove() to detach hidden edges from their parent group. I had inline comments stating that it really shouldn't be necessary. Now, either do to a PFT fix, and/or our recent change to wrap element updates in mobx actions, it seems unnecessary, and seems to be causing this orphan edge issue. Which makes sense because we're detaching it from its parent.
Fixes https://github.com/kiali/kiali/issues/7878
@jmazzitelli note: repro steps are in the issue.  Also, you reported this originally in https://github.com/kiali/kiali/pull/7836#issuecomment-2424905214.

Fix orphan edge hide issue in graph and mesh page

---

frontend/src/types/Mesh.ts

The `infraData` variable of type `unknown` throws an error in OSSMC because the version of the `redux` library used (v4.0.1) has a known issue (see https://www.github.com/reduxjs/redux/issues/3368). This issue has been resolved in the `redux` library version used by the Kiali application. However, OSSMC cannot update its `redux` version, as it is dictated by the OpenShift Console dynamic plugin. To work around this, the `infraData` type must be converted to `any`.
Verify that Kiali works as expected
N/A

Convert infraData type from unknown to any

---

graph/api/api_test.go
graph/telemetry/istio/appender/security_policy.go
graph/telemetry/istio/appender/security_policy_test.go
graph/telemetry/istio/istio.go

Get the reporter based on ambient rates for tcp telemetry 
- Start istio with: 
```--set values.pilot.env.PILOT_ENABLE_IP_AUTOALLOCATE=true" --set values.cni.ambient.dnsCapture=true" ```and Ambient profile.
- Add default ns to ambient: `kubectl label ns default istio.io/dataplane-mode=ambient`
- Create a pod in default namespace to sent http and https requests: 
```apiVersion: v1
kind: Pod
metadata:
name: curl-test
spec:
containers:
- name: curl
image: curlimages/curl
command: ["sh", "-c", "sleep infinity"]
```
- Create ns istio-egress  
- Add to ambient: `kubectl label ns istio-egress istio.io/dataplane-mode=ambient`
- Create and enroll to waypoint: istioctl waypoint apply --enroll-namespace --namespace istio-egress
- Create a service entry in the istio-egress namespace:
```apiVersion: …
```

[Ambient] get reporter for tcp telemetry

---

hack/istio/multicluster/kiali-prepare-remote-cluster.sh

part of: https://github.com/kiali/kiali/issues/7861

multi-cluster setup - no need for script to show only specific templates - the helm chart has a flag for this now

---

frontend/cypress/integration/common/workload_logs.ts
frontend/cypress/integration/featureFiles/traffic_policies_multicluster.feature
frontend/cypress/integration/featureFiles/waypoint.feature
frontend/cypress/integration/featureFiles/wizard_istio_config_multicluster.feature
frontend/cypress/integration/featureFiles/wizard_request_routing.feature
frontend/cypress/integration/featureFiles/workload_logs.feature

**Ambient tests**
Remove the check looking for the label "istio.io/gateway-name=waypoint" as it was removed in istio 1.24.
This label is not been used in other checks internally, only this change is required.
**Frontend tests**
The image for the bookinfo deployment has been updated. The logs had changed and the just log INFO messages. The "Last 30m" was updated in the logs to be able to see the messages (They are no so frequent as the DEBUG), and also filter by INFO text. (Trying to patch the deployment changing the log level but it doesn't have any effect). 
**Multi primary tests**
The failures are because the tests are trying to create a remote istio config and they expect failure, but now the Istio CRDs are created in the remote cluster so it successful creates the istio config in the …

[CI] Fix cypress test failures with Istio 1.24

---

frontend/package.json
frontend/yarn.lock

Upgrade `cross-spawn` dependency to version 7.0.5
**Bonus**: Remove `rollup` entry from resolutions, as it is not needed.
https://issues.redhat.com/browse/OSSM-8365

Update cross-spawn dependency

---

make/Makefile.container.mk

This is to fix the multi-arch build error:
Fatal glibc error: CPU lacks float128 support (POWER 9 or later required)

get release to build with updated buildkit and binfmt

---

hack/istio/install-istio-via-sail.sh
hack/run-integration-tests.sh
hack/setup-kind-in-ci.sh
tests/integration/assets/bookinfo-simple-gateway.yaml
tests/integration/tests/istio_config_test.go
tests/integration/tests/no_istiod_test.go
tests/integration/tests/workloads_test.go

Installs Istio with the Sail Operator rather than `istioctl` for the backend integration tests. The other test suites can be updated later.
```bash
hack/run-integration-tests.sh --test-suite backend
```
Ensure tests complete successfully.
N/A
#7830

[CI] Install Istio with the Sail Operator

---

.github/workflows/molecules.yml
make/Makefile.olm.mk

Go back to using the latest version of OLM in our make and ci workflows.
Do NOT merge this until after the upstream OLM bug is fixed and a new release is published. We expect a v0.30.0 release to be published soon - when you see it here we can merge this PR: https://github.com/operator-framework/operator-lifecycle-manager/releases
For details, see: https://github.com/operator-framework/operator-lifecycle-manager/issues/3419#issuecomment-2451589801

[CI] go back to using the latest version of OLM

---

hack/istio/tempo/helm.yaml
hack/istio/tempo/install-tempo-env.sh

Tempo has different installations method. Helm supports a more up to date version of Tempo. That changes will make easier to test new changes.
- `minikube start` (minikube might require more resources, like `minikube start --memory=16384 --cpus=4`, how to know? If any of the pods can't start, that might be a reason) 
- `hack/istio/tempo/install-tempo-env.sh -c kubectl -im helm`
See traces in any Trace tab: 
N/A
Ref. #7903

[Tempo] Add helm installation method to hack script

---

frontend/src/components/Metrics/TraceLimit.tsx
frontend/src/pages/Graph/SummaryPanelNodeTraces.tsx

For completeness, we should also allow users the ability to set the trace fetch limit in the graph's node-side-panel Traces tab.
As part of this, remove the "use graph refresh" option and just have users manually refresh the traces list, as needed. This simplifies the tab header, given the new dropdown, and I doubt anyone will miss this option. If they do, we can always bring it back.
part-of kiali7769
Test
@josunect , I overlooked this in the original PR, but I think we need the option here as well. You can look at the network requests to ensure the initial request has limit 20, and that new requests are made if the limit changes.

Allow setting trace limit in graph node-side-panel Trace tab

---

frontend/yarn.lock

Backport of PR https://github.com/kiali/kiali/pull/7910 to version 1.89
https://issues.redhat.com/browse/OSSM-8365

[v1.89] Update cross-spawn dependency

---

hack/use-openshift-prometheus.sh

It's now possible to specify a namespace where the script will look for the Kiali CR.

OSSM-8304: fixing ocp prometheus hack script for multiple kiali CRs

---

frontend/src/pages/GraphPF/GraphPF.tsx
frontend/src/pages/Mesh/Mesh.tsx

Fixes https://github.com/kiali/kiali/issues/7935
Layout should probably always also fit to the screen.
[Screencast From 2024-11-18 21-45-13.webm](https://github.com/user-attachments/assets/06fc9885-ec22-466d-b6f8-f502233c0d98)

When performing a layout, reset the graph by default.

---

hack/istio/multicluster/kiali-prepare-remote-cluster.sh

fixes: https://github.com/kiali/kiali/issues/7926

get CA cert data from remote cluster if it cannot be obtained from the local kubeconfig

---

hack/istio/multicluster/env.sh
hack/istio/multicluster/install-multi-primary.sh
hack/istio/multicluster/install-primary-remote.sh
hack/istio/multicluster/setup-external-controlplane.sh
hack/setup-kind-in-ci.sh
hack/start-kind.sh

Currently, the Kind node image is defined in multiple hack scripts according to different criteria (sometimes it is hardcoded, sometimes the latest version is used, and sometimes it is not). This PR centralizes the criteria for determining the Kind node image to be used based on the Istio version. It also ensures that the latest Kind node image is used for the latest Istio version (e.g., multicluster scripts were installing kind 1.27 which is not supported by the latest Istio version 1.24.0)
- Verify that the hack scripts use the latest Kind version with the `master` branch.
- Check that specific Kind versions are used for previous Istio versions.
N/A

Use the same kind node image criteria for all hack scripts

---

frontend/cypress/integration/common/apps.ts
frontend/cypress/integration/common/workload_logs.ts
frontend/src/components/Time/TimeDurationIndicator.tsx
frontend/src/components/Time/TimeDurationModal.tsx
frontend/src/pages/WorkloadDetails/WorkloadPodLogs.tsx

There are some Cypress tests that need to be adapted for OSSMC:
- In workload logs, the duration interval is configured using the time duration modal.
- One of the span table values is not immediately visible in OSSMC (scrolling is required due to OpenShift overhead). We need to verify that the value exists.
**Bonus:** Center-align the time duration button in workload logs.
Verify that cypress tests pass for OSSMC

Adapt some cypress tests to OSSMC

---

make/Makefile.build.mk

Removed controller tests from integration target to avoid failuresin jenkins pipelines.
To be added those tests into Kiali CI.

Removed controller tests from integration target

---

frontend/package.json
frontend/src/pages/GraphPF/GraphPF.tsx
frontend/src/pages/Mesh/Mesh.tsx
frontend/yarn.lock

Closes #7935 (again)
Increase the delay before performing a resize fit.  This seems to be enough in several tries to break it.
Also update react-resize-detector to the highest version prior to dropping support for react 17.
There are still times when PFT seems to just slightly lose its scale, I can't figure how to fix or avoid it.
To test you can just try various things, combining resize, changing layouts, zooming and panning, graph hide, side panel collapse/expand, etc.  Unless something horrible happens it's probably OK, even if it does sort of start laying out slightly too big.

[graph] more tweaks to layout/reset

---

business/openshift_oauth.go
business/openshift_oauth_internal_test.go
config/config.go

Adds an option to the `openshift` auth strategy to skip tls verification for testing purposes only. This is only used when communicating to the OAuth server during token exchange.
This doesn't test the feature directly but it's the easiest way to test this:
1. Deploy Kiali on openshift
2. Set logger to trace level
3. Login to Kiali
4. Get kiali logs and look for "insecure connection" `kubectl logs <kiali-pod> -n <kiali-ns> | grep -i insecure connection`

Add insecure skip verify option to OpenShift auth

---

business/openshift_oauth.go
business/openshift_oauth_internal_test.go
business/openshift_oauth_test.go
handlers/authentication/openshift_auth_controller.go

Add ability to specify custom CA configmap for openshift auth at `/kiali-cabundle/oauth-server-ca.crt`.
N/A.
Unit tests included.
Docs PR: https://github.com/kiali/kiali.io/pull/838
Operator PR: https://github.com/kiali/kiali-operator/pull/853

Add ability to specify custom CA to Openshift Auth

---

frontend/package.json
frontend/yarn.lock

Resolves OSSM-8528 / CVE-2024-52798 
This will need to be backported to v1.73 for OSSM 2.6.

[security] update path-to-regexp

---

frontend/package.json
frontend/yarn.lock

Resolves OSSM-8538 / CVE-2024-55565
This will need to be backported to v1.73 for OSSM 2.6.

[security] update nanoid

---

hack/istio/install-testing-demos.sh

Bookinfo app doesn't work when it is installed by `install-testing-demos.sh` script.
```
elif [ -v GATEWAY_HOST ]; then
```
is always true, since `-v` check if a variable [was set, not if it is empty or not](https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Bash-Conditional-Expressions)
It is always true, since by default, GATEWAY_HOST is an empty string ( https://github.com/kiali/kiali/blob/master/hack/istio/install-testing-demos.sh#L27 )
So when I run `install-testing-demos.sh` without gateway host param, GATEWAY_HOST is an empty string and the script sets
```
hosts:
- ""
```
to the Gateway resource which is created in the temp file (e.g. `/tmp/tmp.8LV8qsrLq`R) which is passed and will be used in `./install-bookinfo-demo.sh` script.
However that Gateway is not valid …

Fix install testing demos when GATEWAY_HOST was not set

---

hack/istio/install-testing-demos.sh

Backport of https://github.com/kiali/kiali/pull/7986

[backport v2.1] Fix install testing demos when GATEWAY_HOST was not set

---

graph/api/api_test.go
graph/options.go
graph/telemetry/istio/appender/aggregate_node.go
graph/telemetry/istio/appender/response_time.go
graph/telemetry/istio/appender/response_time_test.go
graph/telemetry/istio/istio.go
graph/telemetry/istio/util/util.go
graph/types.go

HTTP traffic from a gateway to an ambient workload travels via HBONE to ztunnel and reports L7 telem only as source proxy. Our ambient handling depends on L7 telem from a waypoint, but there is no waypoint involved. Because there is no waypoint or Destination proxy involved, we were missing this source-reported telemetry. The only way to solve this seems to be adding more queries, specfically to pick up this traffic :-(.
Notes:
- namespace graphs should now be capturing the data as long as the namespace "IsAmbient".
- node graphs should now be capturing the traffic as long as the node's namespace "IsAmbient".
- responseTime should be available on these edges as long as the namespace "IsAmbient".
- aggregate node handling (aka requestClassification/operation nodes) is set as a TODO until …

[ambient] handle gateway-to-ambient traffic in the graph

---

hack/istio/install-istio-via-sail.sh

Bump Istio version in Sail hack script. 
The current version is giving an error: 
```
2024-12-16T08:03:52Z	ERROR	ctrlr.istio	Reconciler error	{"Istio": "default", "reconcileID": "1c69c321-72c3-4ac2-8154-b8acd6529183", "error": "failed to apply profile: failed to get values from profile [\"default\"]: failed to read profile file /var/lib/sail-operator/resources/v1.23.0/profiles/default.yaml: open /var/lib/sail-operator/resources/v1.23.0/profiles/default.yaml: no such file or directory"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler
sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:316
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem …
```

Bump istio version for sail hack script

---

business/checkers/virtualservices/route_checker_test.go

Missing not provided route Weight check for TCP and TLS Route types in VirtualServices while KIA1104 Validations. (HTTP Route was working fine).
This was causing odd 'Warning KIA1104 The weight is assumed to be 100 because there is only one route destination' then VS had empty Weight in TCP and TLS Routes.
Added the missing similar checks in TCP and TLS routes (aligned to HTTP route).
Create "samples/tcp-echo/tcp-echo-all-v1.yaml"
You will not see a Warning KIA1104 on that VS.
Added unit tests.
https://github.com/kiali/kiali/issues/8000

Added missing tests for KIA1104

---

hack/use-openshift-prometheus.sh

This was thought to be needed when working on https://github.com/kiali/kiali/issues/7954 - however, it doesn't seem to be required. I was getting an "failed to verify cert" error at one point, and this was needed. But I cannot repeat that failure. Leaving this PR open since it could be useful and may be needed under some situations.

[hack] when setting up user-monitoring on openshift, be able to connect to Prom insecurely

---

business/checkers/virtualservices/route_checker_test.go
frontend/src/pages/ServiceDetails/ServiceNetwork.tsx
frontend/src/types/ServiceInfo.ts
frontend/src/utils/IstioConfigUtils.ts
models/service.go

Closes #8004
This parses out more IP information from the core_v1.Service, passes it back to the client, and now Service detail will display the multiple IP familes, as needed.

[dual stack] Support dual stack by being able to display multiple IPs for a service

---

frontend/src/components/Time/TimeDurationModal.tsx

Handle URL in kiosk for time duration modal
Go to: http://localhost:3000/console/namespaces/bookinfo/workloads/productpage-v1?duration=604800&refresh=30000&kiosk=true&tab=logs&rangeDuration=604800
Make sure that the selector is: 
Also in the modal: 
Update the modal data: 
Make sure it changes in the URL. 
Note: For Overview & Traffic, the duration parameter is used. For the other tabs, rangeDuration. Where rangeDuration is used, the "to" and "from" parameters can also be used:
http://localhost:3000/console/namespaces/bookinfo/workloads/productpage-v1?duration=604800&refresh=60000&kiosk=true&tab=traces&from=1733912384867&to=1733912700115
I think this will be validated in OSSMC tests (Can be done in a follow up PR)
Fixes https://github.com/kiali/kiali/issues/7958

Handle URL in kiosk for time duration modal

---

frontend/package.json
frontend/yarn.lock

Currently, `yarn.lock` contains some entries that download the same tarball file. To avoid these duplications, I have merged the entries to ensure consistency. These duplicated tarballs can cause some build systems, such as Konflux, to fail
Verify that CI test pass

Avoid duplicated tarballs

---

frontend/cypress/integration/featureFiles/service_details_multicluster.feature

The service ratings for the east cluster, which is not supposed to have traffic, has one initial tracing for some reason, causing a CI flake. 
Update the service for one that is not generating traces. 
Verify that the logic is correct: 
CI passes. Also, the tests can be run locally for: 
`hack/run-integration-tests.sh --test-suite frontend-primary-remote --setup-only true`

Update service with no traces

---

business/namespaces.go
hack/keycloak.sh

The multi cluster multi primary CI is failing because keycloak cannot be accessed with the configured user/password in the latest image (https://github.com/bitnami/charts/blob/main/bitnami/keycloak/CHANGELOG.md#2432-2024-12-20). 
It is not picking the username/password in the helm charts, and it is using the bitnami defaults. 
This change just uses the previous version. 
This is just a temporary fix, that should be reverted to use the latest image once it correctly sets up the bootstrap admin username and password. But I haven't found a way to pass the new variables in helm charts (The way the scripts are doing look correct, regarding the docs https://artifacthub.io/packages/helm/bitnami/keycloak#keycloak-parameters), or it should use a different keycloak image to been able to set up them …

Keycloak tmp fix

---

business/namespaces.go
hack/keycloak.sh

This issue is not always reproducible, but i think it might happen when the namespace is not found in the cache by `GetClusterNamespace`. This method uses `FilterNamespacesWithDiscoverySelectors` but it doesn't always have all the information needed to verify if the namespace is accessible, because the namespaces labels are missing:
I tested with Ambient, but I think it also might happen in a non Ambient Mesh. 
Install istio, kiali and bookinfo, set the discovery selectors: 
```
deployment:
cluster_wide_access: true
discovery_selectors:
default:
- matchExpressions:
- key: istio.io/dataplane-mode
operator: Exists
- matchExpressions:    
- key: istio-injection
operator: Exists  
```
Go to a workload, metrics and let the refresh button. It needs to wait until the cache is empty to be able to …

Add the namespace labels for FilterNamespacesWithDiscoverySelectors

---

hack/keycloak.sh

The admin user/pwd variables of the Keycloak container (21.1.2) doesn't look compatible with the ones updated in the charts in the latest version (24.3.2).
With the defaults, it looks like everything is working, but I just wondering if there is any issue to use that specific container image. 
`hack/run-integration-tests.sh --test-suite frontend-multi-primary --setup-only true`
The changes are affecting frontend-multi-primary environment
Fixes #8029

Update keycloak image and container

---

status/versions.go

Create a client with TLS settings to check the version
Create a Tempo Stack in OpenShift following: https://medium.com/kialiproject/installing-openshift-service-mesh-3-tp1-with-kiali-and-grafana-tempo-6b76881ceaef
Kiali config: 
```
tracing:
enabled: true
provider: "tempo"
auth:
insecure_skip_verify: true
type: bearer
token: "sha256..."
external_url: "https://tempo-sample-gateway-tempo.apps-crc.testing/api/traces/v1/north/search"
internal_url: "https://tempo-sample-gateway-tempo.apps-crc.testing/api/traces/v1/north/tempo"
health_check_url: "https://tempo-sample-gateway-tempo.apps-crc.testing/api/traces/v1/north/tempo/api/echo"
tempo_config: 
url_format: "jaeger"
```
Fixes …

Use transport to check the version

---

graph/api/api_test.go
graph/api/testdata/test_ambient_graph.expected
graph/api/testdata/test_app_graph.expected
graph/api/testdata/test_app_node_graph.expected
graph/api/testdata/test_complex_graph.expected
graph/api/testdata/test_mc_source_graph.expected
graph/api/testdata/test_rates_node_graph_total.expected
graph/api/testdata/test_rates_none_graph.expected
graph/api/testdata/test_rates_received_graph.expected
graph/api/testdata/test_rates_sent_graph.expected
graph/api/testdata/test_rates_total_graph.expected
graph/api/testdata/test_service_graph.expected
graph/api/testdata/test_service_node_graph.expected
graph/api/testdata/test_versioned_app_graph.expected
graph/api/testdata/test_versioned_app_node_graph.expected
graph/api/testdata/test_workload_graph.expected
graph/api/testdata/test_workload_node_graph.expected
graph/config/cytoscape/cytoscape.go
graph/telemetry/istio/appender/extensions.go
graph/telemetry/istio/istio.go
kubernetes/client_factory.go
mesh/api/api_test.go
mesh/api/testdata/test_mesh_graph.expected
mesh/config/cytoscape/cytoscape.go
mesh/generator/generator.go

replace use of crypto/md5 with crypto/sha256
- regenerate the expected graph test output files due to the new element ids produced by the new hashing
Closes https://issues.redhat.com/browse/OSSM-8373

replace use of crypto/md5 with crypto/sha256

---

.github/workflows/molecules.yml
.github/workflows/test-istio-version.yml

This runs all integration tests 2 times nightly - at 2am it runs with the minor version previous to the latest version; at 4am it runs with the minor version that is 2 previous versions back.
So if the latest version of Istio is 1.25.4 and the previous two minor versions are 1.24.8 and 1.23.0 then those last two are run at 2am and 4am respectively.
You can alternatively run this CI action manually - you can either give a specific Istio version to test with (e.g. "1.24.2") or you can specify an offset to the latest minor version. If you give an offset of "1" it will run with the Istio minor version previous to the current minor version. "2" will use the version before that one, and so on. You can opt to specify negative offsets if you find that more intuitive - it doesn't matter. "-1" …

run integration tests on different istio versions

---

frontend/cypress/integration/common/workload_logs.ts
frontend/cypress/integration/featureFiles/workload_logs.feature

Update time duration for the workload logs cypress test.
The default was 1800 (30 min), but this is not enough for OSSMC. 
The bookinfo demo only writes logs at the initialization, and OSSMC tests take longer than the server tests. 
Cypress test passing or run `yarn cypress:run`
**e2e** tests updated
Fixes https://github.com/kiali/openshift-servicemesh-plugin/issues/410

Increase logs period for OSSMC

---

frontend/cypress/support/commands.ts

Override cy.exec to print full output on failure
N/A
N/A

Override cy.exec to print full output on failure.

---

frontend/src/pages/AppDetails/AppDetailsPage.tsx
frontend/src/pages/ServiceDetails/ServiceDetailsPage.tsx
frontend/src/pages/WorkloadDetails/WorkloadDetailsPage.tsx

Fixes https://github.com/kiali/kiali/issues/8034
When navigating from within a workload detail to a different workload detail, ensure that the new workload is fetched. This is the main bug reported in this issue. But furthermore, protect against a similar situation for app detail and service detail.
See issue for repro steps.  I removed what I think is an unnecessary `await` in one place. Make sure you are ok with the async stuff.  I applied basically the same logic across the three scenarios.

Fix issue with workload detail navigation

---

frontend/cypress/integration/common/waypoint.ts
frontend/cypress/integration/featureFiles/waypoint.feature
frontend/public/locales/zh/translation.json
frontend/src/components/Ambient/WaypointConfig.tsx
frontend/src/components/Ambient/WaypointWorkloadsTable.tsx

Cypress tests for the waypoint tab
Cy passes (This test are running in the Ambient job), it can also be tested locally with:
`yarn cypress run -e TAGS="@waypoint"`
e2e tests
Ref. https://github.com/kiali/kiali/pull/8009

[cy] Add test coverage for waypoint tab

---

business/apps.go
business/istio_config.go
business/workloads.go
frontend/src/pages/WorkloadDetails/WorkloadInfo.tsx
kubernetes/filters.go

Application and Workloads lists got links to WorkloadGroup Istio config.
Workload Details got link to WorkloadGroup Istio config:
Create WorkloadGroups and manually create WorkloadEntries with Sidecars:
```
apiVersion: networking.istio.io/v1
kind: WorkloadGroup
metadata:
name: ratings-vm
labels:
app: ratings-vm
spec:
template:
address: 2.2.2.2
labels:
app: ratings-vm
class: vm
serviceAccount: bookinfo-ratings
---
apiVersion: networking.istio.io/v1
kind: WorkloadEntry
metadata:
name: ratings-vm
spec:
address: 2.2.2.2
labels:
class: vm
app: ratings-vm
version: v3
serviceAccount: bookinfo-ratings
network: vm-us-east
---
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
name: bookinfo-ratings-vm
spec:
egress:
- bind: …
```

Added WorkloadGroup references from App and Workload lists.

---

frontend/src/app/InitializingScreen.tsx
frontend/src/components/About/AboutUIModal.tsx
frontend/src/components/IstioWizards/WizardLabels.tsx
frontend/src/components/MessageCenter/NotificationList.tsx
frontend/src/components/TracingIntegration/TracesComponent.tsx

Making sure that Alerts are mimicking,  https://v5-archive.patternfly.org/components/alert  
AboutUIModal.tsx Before and After (margin needs to be changed):
Before:
After:
InitializingScreen.tsx
Before:
After:
WizardLabels.tsx
Before: 
(No need to make changes other than margin)
After:
NotificationList.tsx
How the alert shows:
Removed the isInLine in the code since toast alerts DO NOT use isInLine alerts
TracesComponent.tsx
Before: 
After:
Closes #8044

Make sure all inline alerts have correct styles

---

.github/workflows/test-istio-version.yml

I tested on my fork and I see the ambient test skipped when testing 1.22.7. This is what it will look like when ambient tests are skipped on the earlier istio versions:
I also tested on my fork with Istio 1.23 and as expected, all green. So this PR is good to go.

we only test ambient when on Istio 1.23 and above

---

config/config.go
routing/routes.go

When auth.strategy is not anonymous, users can still see the /api endpoint version and config information. This new config allows users to disable that unauthenticated access, requiring users to authenticate with the server in order to see the /api info.
```yaml
server:
require_auth: true
```
operator PR: https://github.com/kiali/kiali-operator/pull/865

be able to configure /api endpoint to require user authentication

---

config/config.go
routing/routes.go

When auth.strategy is not anonymous, users can still see the /api endpoint version and config information. This new config allows users to disable that unauthenticated access, requiring users to authenticate with the server in order to see the /api info.
cherry-pick of https://github.com/kiali/kiali/pull/8055

[v2.4] be able to configure /api endpoint to require user authentication

---

frontend/src/components/Nav/Masthead/ThemeSwitch.tsx
frontend/src/types/Common.ts
frontend/src/utils/ThemeUtils.ts

Theme is not stored in browser from v1.81(https://github.com/kiali/kiali/blob/v1.81/frontend/src/components/ThemeSwitch/ThemeSwitch.tsx)
localStorage was eliminated in migration
[Bug.webm](https://github.com/user-attachments/assets/b66168a5-4c45-4696-a80a-25da52d80ccd)
[Fix Theme.webm](https://github.com/user-attachments/assets/9bee0601-eec8-452e-a506-319e111d3ac8)
Change the theme and refresh the browser. 
https://github.com/kiali/kiali/issues/8069

fix: Store theme in localstorage

---

business/apps.go
business/istio_validations.go
business/references/k8s_gateway_references.go
business/references/k8s_gateway_references_test.go
business/services.go
business/workloads.go
config/config.go
frontend/src/config/ServerConfig.ts
frontend/src/pages/ServiceDetails/ServiceInfo.tsx
frontend/src/pages/WorkloadDetails/WorkloadInfo.tsx
frontend/src/types/ErrorRate/__testData__/ErrorRateConfig.ts
frontend/src/types/IstioConfigList.ts
frontend/src/types/ServerConfig.ts
frontend/src/types/__testData__/HealthConfig.ts
kubernetes/filters.go

In K8sGateway Workload details page, list K8s Gateway in Istio config:
Setup ambient environment.
Or in K8s Gateway setup environment create a K8sGateway which will cause Workload generated.
Go to 'waypoint' or any K8s Gateway Workload details.
You will see the Istio Config list not empty, but will show those objects which name matches the `gateway.networking.k8s.io/gateway-name` label of workload.
https://github.com/kiali/kiali/issues/8075

Added support of listing K8sGateways for Workloads.

---

frontend/cypress/integration/common/waypoint.ts
frontend/cypress/integration/featureFiles/waypoint.feature

Adding cypress coverage for istio config waypoint link in the workload list and the workload details
Cy passes (This test are running in the Ambient job), it can also be tested locally with:
- Install istio with Ambient profile  `istio/install-istio-via-istioctl.sh -c kubectl -cp ambient`
- Install bookinfo, add it into the mesh page and create a waypoint  `istio/install-bookinfo-demo.sh -c kubectl -ai false -tg -w true`
- Run waypoint tests: `yarn cypress run -e TAGS="@waypoint"`
Ref. https://github.com/kiali/kiali/pull/8077

[cy] Add cypress test coverage for k8s gw waypoint links

---

frontend/src/pages/Graph/SummaryPanelNode.tsx

Create a unique key in the list to force the recreation of the services list to avoid duplicates.
With no fix: 
Click in the workloads for review generate service links duplicates.
1. Install Kiali
2. Install bookinfo
3. Click in the different workload versions from reviews
4. Validate the links are not duplicated

Remove duplicates in summary panel node service links

---

business/apps.go
business/checkers/authorization/principals_checker_test.go
business/checkers/workload_groups_checker.go
business/checkers/workloadgroups/duplicate_labels_checker.go
business/checkers/workloadgroups/duplicate_labels_checker_test.go
business/checkers/workloadgroups/service_accounts_checker.go
business/checkers/workloadgroups/service_accounts_checker_test.go
business/istio_validations.go
business/references/workloadentry_references.go
business/references/workloadgroup_references.go
business/workloads.go
frontend/src/pages/AppDetails/AppDescription.tsx
frontend/src/pages/AppDetails/AppDetailsPage.tsx
frontend/src/pages/AppDetails/AppInfo.tsx
frontend/src/pages/ServiceDetails/ServiceDescription.tsx
frontend/src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
frontend/src/types/App.ts
kubernetes/cache/kube_cache.go
kubernetes/filters.go
models/app.go
models/istio_validation.go
models/workload.go
tests/data/workload_data.go
util/maps.go

Added 2 new Validation Warning messages for Workload Groups:
"Warning KIA1701 Service Account not found in this namespace".
"Warning KIA1702 More than one Workload Group with duplicate labels found in the same namespace" 
Kiali does not list ServiceAccounts directly from the system but is listing them from the Pods.
That is why the notification severity is Warning not a Error.
Create a WorkloadGroup with non existing Service Account, or with Service Account from other namespace, and with labels which exist in another WG in the same namespace.
```
apiVersion: networking.istio.io/v1
kind: WorkloadGroup
metadata:
name: ratings-vm
spec:
metadata:
labels:
app: ratings-vm
template:
serviceAccount: bookinfo-ratings
---
apiVersion: networking.istio.io/v1
kind: WorkloadEntry …
```

Added Validations for WorkloadGroups, fixed issue with references.

---

frontend/src/pages/Graph/SummaryPanelGraph.tsx
frontend/src/utils/Common.ts
frontend/src/utils/__tests__/Common.test.ts

In multicluster installation, in Graph pages when all namespaces are selected, Kiali UI sends `validations` request to backend per cluster with all namespaces sent as a param.
So those namespaces which exist in 'east' and are requested for 'west', cause 500 errors in response.
Fixed the frontend by adding filter namespaces per cluster in Graph Validations queries.
1.  Install istio and kiali in multi-primary (This is probable happening in primary remote)
2.  Create a namepsace in the west cluster
3.  Go to the traffic graph
4.  Select all the namespaces
https://github.com/kiali/kiali/issues/8081

Added filter namespaces per cluster in Graph Validations

---

kubernetes/cache/kube_cache.go

The filtering by WorkloadGroup Labels were including those WorkloadGroups without Labels, so they were included in all services.
Fixed the filter, added comments.
Before:
After:
Create objects:
```
apiVersion: networking.istio.io/v1
kind: WorkloadGroup
metadata:
name: ratings-vm
spec:
metadata:
labels:
app: ratings-vm
template:
serviceAccount: bookinfo-ratings
---
apiVersion: networking.istio.io/v1
kind: WorkloadEntry
metadata:
name: ratings-vm
spec:
address: 2.2.2.2
labels:
class: vm
app: ratings-vm
version: v3
serviceAccount: bookinfo-ratings
network: vm-us-east
---
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
name: bookinfo-ratings-vm
spec:
egress:
- bind: 127.0.0.2
hosts:
- ./*
ingress:
- defaultEndpoint: 127.0.0.1:9080
port:
name: http
number: …
```

Fixed filtering WorkloadGroups with empty Spec.Metadata.Labels

---

frontend/cypress/integration/common/mesh.ts
frontend/cypress/integration/featureFiles/mesh.feature

Update mesh cypress testing to be flexible given the tracing test deployment, which may be jaeger or tempo, and may be deployed in the CP namespace, its own namespace, or externally.
Note that our cypress tests do require one of the two to be deployed, it will not pass in an env with no tracing configured.
This fixes https://issues.redhat.com/browse/OSSM-8763
Testing
Upstream CI testing should handle the jaeger deployment option.  This should also be tested in an environment using Tempo for tracing.

[cypress] Update mesh cypress testing to be flexible

---

tests/integration/tests/traces_spans_test.go
tests/integration/utils/kiali/kiali_client.go

The Tempo query doesn't seem to be able to return the parentSpanId in the query. The parentSpanId is used to create the references array. There is a conversion in the trace data because the trace format from Tempo is different than the Jaeger trace format. 
This shouldn't affect the functionality of the spans api call
Affected tests: 
- TestServiceSpans
- TestAppSpans
- TestWorkloadSpans
Updated integration tests
Fixes https://github.com/kiali/kiali/issues/8112

Update integration tests for Tempo

---

frontend/src/types/IstioConfigList.ts
kubernetes/types.go

This PR set the apiVersion of ReferenceGrant istio object to `v1beta` when Kiali gets any object of this kind from Kubernetes.
1. Create a test `ReferenceGrant` istio object using Kiali wizard
2. Click in the created `ReferenceGrant` istio object to access details page
3. Verify that the apiVersion is `v1beta1`:
Fixes #8133

Set apiVersion of ReferenceGrant to v1beta1

---

frontend/src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
frontend/src/pages/WorkloadDetails/WorkloadPodLogs.tsx

Added support of K8s Native Sidecars logs in Workload Logs tab.
Install Istio in native sidecars mode `./hack/istio/install-istio-via-istioctl.sh -c kubectl --native-sidecars true`
Install bookinfo.
Bookinfo's Workload details page Logs tab.
Make sure "sidecar-proxy" checkbox exists and works, loads the logs.
n/a
https://github.com/kiali/kiali/issues/7909

Workload logs for k8s native sidecar.

---

frontend/cypress/integration/common/mesh.ts
frontend/cypress/integration/common/workload_logs.ts
frontend/cypress/integration/featureFiles/mesh.feature
frontend/cypress/integration/featureFiles/workload_logs.feature

Include cypress logs for ambient logs correlation.
Also, it adds the mesh Ambient test to the @waypoint-tracing tests, because they are executed at the end, so it give it some time to be available. waypoint-tracing tests were just for tracing, because they also need some time to have traces generated once the waypoint is created, but as they include a non tracing test now, the tag might be renamed.
- Install Istio Ambient, Kiali, bookinfo
- Add bookinfo to Ambient mesh with waypoint
- run cypress:  `yarn cypress:ambient` or `yarn cypress:waypoint` 
Or, ci test passes
e2e test
Ref. https://github.com/kiali/kiali/pull/8103

Add ambient logs cypress tests

---

frontend/cypress/integration/common/app_details.ts
frontend/cypress/integration/common/app_details_multicluster-pf.ts
frontend/cypress/integration/common/istio_config.ts
frontend/cypress/integration/common/workloads_details.ts
frontend/cypress/integration/featureFiles/wizard_istio_config.feature
frontend/cypress/support/commands.ts

Increase timeout between retries for crd validation status cypress tests. The current timeout is not enough for the test https://github.com/kiali/kiali/blob/a5bb923eeac18aaad04e926959c5c17a3587ef2a/frontend/cypress/integration/featureFiles/wizard_istio_config.feature#L303
Other changes in this PR that affect Cypress tests:
-  Session validation is modified to fix session lost issues we had in OpenShift CI tests.
- Default `cy.waitForReact()` used for all cases (the #root selector does not exist in OSSMC).
Verify that CI tests pass.

Increase timeout of crd validation status cypress tests

---

istio/discovery.go
istio/discovery_test.go
istio/kubernetes.go
models/mesh.go

Fixes the mesh page for maistra managed namespaces.
1. Install Maistra 2.6 operator AND the OSSM 3 operator
2. Deploy SMCP
```
kubectl create ns istio-system
kubectl apply -f - <<EOF
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
name: basic
spec:
mode: ClusterWide
addons:
grafana:
enabled: false
kiali:
enabled: false
prometheus:
enabled: false
gateways:
enabled: false
egress:
enabled: false
openshiftRoute:
enabled: false
security:
manageNetworkPolicy: false
dataPlane:
mtls: true
identity:
type: ThirdParty
tracing:
type: None
EOF
```
3. Create bookinfo ns
```
kubectl create ns bookinfo
```
4. Add a namespace to SMMR
```
kubectl label ns bookinfo istio-injection=enabled
```
5. Deploy bookinfo
```
oc apply -f …
```

Fix maistra managed namespaces

---

frontend/cypress/integration/common/istio_config.ts
frontend/cypress/integration/featureFiles/wizard_istio_config.feature

Increase the retries and reduce the timeout of validation object in cypress test. Doing that we can reduce the time of the test execution in case istio config list page is reconciled earlier.

Fine-tune of config validation cypress test

---

istio/discovery.go
istio/discovery_test.go
istio/kubernetes.go
models/mesh.go

Cherry-pick of #8141 to 2.4 branch
1. Install Maistra 2.6 operator AND the OSSM 3 operator
2. Deploy SMCP
```
kubectl create ns istio-system
kubectl apply -f - <<EOF
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
name: basic
spec:
mode: ClusterWide
addons:
grafana:
enabled: false
kiali:
enabled: false
prometheus:
enabled: false
gateways:
enabled: false
egress:
enabled: false
openshiftRoute:
enabled: false
security:
manageNetworkPolicy: false
dataPlane:
mtls: true
identity:
type: ThirdParty
tracing:
type: None
EOF
```
3. Create bookinfo ns
```
kubectl create ns bookinfo
```
4. Add a namespace to SMMR
```
kubectl label ns bookinfo istio-injection=enabled
```
5. Deploy bookinfo
```
oc apply -f …
```

[2.4] Fix maistra managed namespaces (#8141)

---

controller/controller.go
controller/validations.go
tests/integration/controller/validations_test.go

In one of tests, the VirtualService api version was remaining v1beta1, fixed it to v1.

Fixed VS version from beta1 to v1

---

hack/istio/ambient/curl-pod.yaml
hack/istio/ambient/echo-service.yaml
hack/istio/ambient/install-waypoints.sh

Add hack script to create different waypoint proxies scenarios for testing purposes.
This PR creates 6 namespaces: 
- waypoint-forservice
- waypoint-forworkload
- waypoint-forall
- waypoint-fornone
- waypoint-fordifferentns
- waypoint-foroverride
The graph seems correct except for: 
- waypoint-fordifferentns It doesn't look to be redirecting the traffic correctly 
- waypoint-forworkload: Points to a service but it is sending the traffic directly to the workload
Ref. https://istio.io/latest/docs/ambient/usage/waypoint/
Run `hack/istio/ambient/install-waypoints.sh` and the waypoints will be created in the Ambient Mesh, in different namespaces.
N/A, this hack could be used in the future for testing CI
Fixes #7499

Add hack script to create different waypoint proxies scenarios for testing purposes

---

frontend/src/pages/Mesh/target/TargetPanelCommon.tsx
frontend/src/pages/Mesh/target/TargetPanelDataPlaneNamespace.tsx
frontend/src/pages/Mesh/target/TargetPanelNamespace.tsx

Fixes #8159
Mesh page side-panel improvements/fixes:
- remove error message when dataplane namespace disappears on refresh
- this was a timing thing, but happened most of the time. No reason to generate an error, now just logs a console debug message
- improve dataplane namespace by fetching data only for expanded rows,this can prevent a lot of fetches when there are a lot of namespaces.
- ensure namespace control planes stay in sync with the mesh topology
Steps to test the PR:
part one
1. As in the #8159, nav to the mesh page and select a dataplane.
2. using kubectl, add a namespace to the dataplane, then start refreshing the mesh page
Ensure that when the mesh page dataplane node label increments that the new namespace also appears in the side panel.
4. delete the namespace and again …

Mesh page side-panel improvements/fixes

---

hack/istio/install-istio-via-istioctl.sh

This PR changes the port name in the `istio-ingressgateway` route exposed by the `install-istio` hack script. This port name was recently changed and it was not propagated to this route.
1. Install OpenShift CRC: ./hack/crc-openshift.sh start
2. Install istio: ./hack/istio/install-istio-via-istioctl.sh
3. Install bookinfo demo with traffic generator: ./hack/istio/install-bookinfo-demo.sh -tg
4. Check that istio-ingressgateway route is working correctly: http://istio-ingressgateway-istio-system.apps-crc.testing/productpage
An optional way to check is installing Kiali and see that there is traffic graph for the bookinfo demo
N/A
Fixes #8163

Change port name in the istio-ingressgateway route

---

business/workloads.go
frontend/src/components/TracingIntegration/TracesComponent.tsx
frontend/src/components/TracingIntegration/TracingResults/SpanDetails.tsx
frontend/src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
frontend/src/pages/WorkloadDetails/WorkloadPodLogs.tsx
frontend/src/services/Api.ts
frontend/src/types/IstioObjects.ts
handlers/workloads.go

- Use service instead of app to filter waypoint logs and traces
- If service filter is empty, don't return the log line
- Don't show the waypoint check if the workload is not enrolled
- Install Istio Ambient
- Install bookinfo and add it to the mesh 
- Check that there are logs and traces for the workloads
Fixes https://github.com/kiali/kiali/issues/8180

Use service name, not app

---

hack/istio/sail/func-sm.sh

more sail hack script updates. After learning more about profiles, I found out the istio operator will automatically apply the openshift platform profile values for us. Here we now just always set to the demo profile which reduces the pod limits for the istio resources allowing us to more easily run on local laptops

[hack] don't specify openshift profile, there is no need anymore

---

business/checkers/services/port_mapping_checker.go
business/istio_validations.go
business/services.go
business/services_test.go
business/test_util.go
config/config.go
handlers/services.go
models/workload.go

- Include service validations for service details 
- Exclude service validations for gateways (The validation should be done by the Istio config?)
- Move isGateway to config to be used by services/workloads
- Install Istio Ambient
- Install bookinfo with: 
`istio/install-bookinfo-demo.sh -c kubectl -ai false -tg -w true `
- Modify ratings service to create a validation error: 
```
cat <<NAD | kubectl -n bookinfo apply -f -
apiVersion: v1
kind: Service
metadata:
name: ratings
labels:
app: ratings
service: ratings
spec:
ports:
- port: 9081
name: http
selector:
app: ratings
NAD
```
What should we expect? 
- In service list, bookinfo gateway shouldn't have a warning
- In service list, ratings should have a warning
- In ratings services details should be a warning
- In bookinfo …

Service details validations

---

business/checkers/authorization/principals_checker.go
business/checkers/workloadgroups/service_accounts_checker.go
business/istio_config.go
business/istio_validations.go
business/istio_validations_perf_test.go
business/istio_validations_test.go
business/workloads.go
controller/validations.go
handlers/istio_config.go
kubernetes/host.go
util/sliceutil/slice.go

Part-of #8007 
So this PR does not fundamentally change the way we do validations, and therefore is looking to make only marginal perf gains via some code refactoring for efficiency.  Perhaps there are fundamental things we can do to speed things up, but I'm not yet sure what they may be.  The biggest win may be to just invest in reconciling in response to config changes, as opposed to looking for gains in approach.  One way to do that would be to have watchers and respond to changes. But perhaps an easier way would be to "hash" all of the resource versions of everything involved in validation, save that, and skip validation if it doesn't change.  We'd still have to fetch everything on each reconcile, but most everything is cached.
As for this PR, the general approach to the refactor was …

[perf] validation perf work

---

business/istio_validations_perf_test.go
business/istio_validations_test.go
business/testing.go
kubernetes/cache/testing.go

Adds a benchmark test for validations.
Example of how to run this:
```
go test -run=XXX -benchmem -cpuprofile cpu.prof -memprofile mem.prof -bench=. github.com/kiali/kiali/business -num-objects 25
```
That produces a cpu and memory profile that you can examine with pprof like:
```
go tool pprof -http=":8080" ~/go/bin/kiali mem.prof
```
or
```
go tool pprof -web mem.prof
```
It's not perfect. Especially the data generation could use some more work but at least it's a start.
Run the benchmark with the instructions above.
If this PR is related to a github issue, please link it here ([more info](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to- …

Add benchmark test for validations

---

frontend/cypress/integration/common/kiali_login.ts
frontend/cypress/integration/featureFiles/kiali_login.feature

When testing OSSM2.6 in interop pipeline, this testcase fails on OCP4.19 since its no longer possible to send empty login form. We skip the test by using tag `@skip-lpinterop`.
This should be cherry picked into OSSM 3.0 and eventually removed in master.

[v2.6] Cypress - ignore skip empty login form in interop

---

store/fifo_store_test.go
store/store_test.go
store/threadsafe_store.go

Adds a read lock to `store.Version()`. Also removes a duplicated unit test and speeds up another one that was causing tests to be slow.
`go test -timeout 30s -race -run '^TestVersionIsThreadsafe$' github.com/kiali/kiali/store`
Unit tests
https://github.com/kiali/kiali/issues/8207

Make store.Version() threadsafe

---

hack/istio/install-istio-via-sail.sh

The otel operator does not wait until its webhook is ready before considering itself ready so we must wait a few seconds before trying to create otel resources.
```
./hack/run-integration-tests.sh --test-suite frontend-tempo --setup-only true
```
N/A

[CI] Fix tempo suite flake

---

business/workloads.go

Changed a log level `This controller %s is assigned in a Pod and it's not properly managed` from Error to Debug, as it is ignored anyway and is a corner case.
Happened when upgrading Kiali from v1.87 to v2.0.
This issue can happen when a Pod's `OwnerReferences` contains `Service`.
But could not find a reproducer.
https://github.com/kiali/kiali/issues/8192

Changed corner case log level to debug.

---

frontend/cypress/integration/common/kiali_login.ts
frontend/cypress/integration/featureFiles/kiali_login.feature

This reverts commit f6a7886f24b832363a76c505f56d8dd044cadb6e. Testing is not passing just before the release.

Revert "[v2.6] Cypress - ignore skip empty login form in interop"

---

frontend/src/types/IstioConfigList.ts

The validations key for Istio config object types was fixed to be in "GVK".
So the validations for Service details Istio Config items shows correctly.
Create a traffic routing for any bookinfo Service.
Spoil the VS to have validation warning or error.
Service details page should show that VS with correct status which is in that VS details page.
n/a
https://github.com/kiali/kiali/issues/8228

Fixed validations retrieval by GVK key

---

hack/istio/sail/func-sm.sh
hack/istio/sail/install-ossm-release.sh

install CRC cluster on your local machine then run:
`./install-ossm-release.sh install-operators`
then
`./install-ossm-release.sh install-istio`
Watch the magic happen.
You will get Istio, Kiali, and OSSMC installed in your OpenShift/CRC cluster.
to clean up:
```
./install-ossm-release.sh delete-istio
./install-ossm-release.sh delete-operators
```

[hack] now that OSSM 3.0 is released, update hack scripts to be able to install it

---

frontend/src/helpers/GraphHelpers.tsx
frontend/src/pages/Graph/GraphToolbar/GraphFindPF.tsx

Fixes #8232
Test:
1. deploy bookinfo
2. traffic graph page
3. graph find: `label:service`
4. graph find: `!label:service`
You can supplement with other label-oriented tests.  Note that the active "app" and "version" label names are special, and not applicable to graph find/hide.

Fix issue with unary "label:" graph find/hide

---

.github/workflows/molecules.yml
.github/workflows/test-istio-version.yml

The original code in the workflow was ignoring the GA version if RC versions existed - when it should be the opposite.
This code now only uses RC versions if there is no GA version. If there is a GA version, it is used; RCs are ignored.

[ci] parse istio versions so that we ignore RC versions when GA is released

---

go.mod

Upgrade golang to 1.23.6
https://issues.redhat.com/browse/OSSM-8745
https://issues.redhat.com/browse/OSSM-8837

[v2.4] Upgrade go 

---

business/metrics.go
frontend/src/config/Config.ts
frontend/src/pages/Mesh/target/TargetPanel.tsx
frontend/src/pages/Mesh/target/TargetPanelCommon.tsx
frontend/src/pages/Mesh/target/TargetPanelMetrics.tsx
frontend/src/services/Api.ts
frontend/src/types/Metrics.ts
handlers/metrics.go
routing/routes.go

Show Resource usage for Kiali in the Mesh page: 
Added a Kiali link to the workload
- Install Istio
- Go to the Mesh Page
- Click in the Kiali node
- See the metrics 
Fixes #8196

[Mesh Page] Kiali resource usage metrics

---

frontend/cypress/integration/common/apps.ts
frontend/cypress/integration/featureFiles/app_details.feature
frontend/cypress/integration/featureFiles/app_details_multicluster.feature
frontend/cypress/integration/featureFiles/service_details.feature
frontend/cypress/integration/featureFiles/waypoint.feature
frontend/cypress/integration/featureFiles/workloads_details.feature
frontend/src/components/Metrics/TraceLimit.tsx
frontend/src/components/TracingIntegration/TracesDisplayOptions.tsx

Attempts to fix tracing flakes like this one: https://github.com/kiali/kiali/actions/runs/13909420482/job/38920315175#step:8:766
N/A
Included

Bump the limit of traces we see in e2e tests

---

frontend/cypress/integration/common/app_details_multicluster.ts
frontend/cypress/integration/common/authorization.ts
frontend/cypress/integration/common/graph.ts
frontend/cypress/integration/common/graph_context_menu.ts
frontend/cypress/integration/common/graph_display.ts
frontend/cypress/integration/common/graph_find_hide.ts
frontend/cypress/integration/common/graph_side_panel.ts
frontend/cypress/integration/common/graph_toolbar.ts
frontend/cypress/perf/common.ts
frontend/src/pages/Graph/MiniGraphCard.tsx

In a PR for issue 7256, and the subsequent PR https://github.com/kiali/kiali/pull/7442, we updated cytoscape cypress tests to more reliably wait for the graph to be populated before testing for edges and nodes. Probably due to timing, those changes were not applied to the analogous PFT cypress tests. This PR applies those changes and will hopefully prevent similar flakes.

update PFT cypress tests with some logic in the cytsoscape cypress  tests

---

business/istio_config.go
business/workloads.go
graph/telemetry/istio/appender/service_entry_test.go
handlers/config.go
handlers/config_test.go
istio/discovery.go
istio/istiotest/fake.go
prometheus/client.go
prometheus/prometheustest/mock.go
routing/routes.go

Refactors config handlers to use closures instead of global vars.
N/A
Covered by existing e2e tests. This PR adds a unit test for the config handler.
Related to: https://github.com/kiali/kiali/issues/6923

Refactor config handlers

---

frontend/src/actions/__tests__/JaegerActions.test.ts
frontend/src/components/Kiosk/KioskActions.ts
frontend/src/components/TracingIntegration/TracesComponent.tsx
frontend/src/components/TracingIntegration/TracingResults/SpanTable.tsx
frontend/src/components/TracingIntegration/TracingResults/TraceDetails.tsx
frontend/src/components/TracingIntegration/TracingResults/TracingTraceTitle.tsx
frontend/src/reducers/__tests__/TracingStateReducer.test.ts
frontend/src/types/TracingInfo.ts
handlers/tracing.go
models/tracing.go

- Add a new parent kiosk action for tracing.
See https://github.com/kiali/openshift-servicemesh-plugin/pull/428
- Lint 
See https://github.com/kiali/openshift-servicemesh-plugin/pull/428 
Ref. https://github.com/kiali/kiali/issues/7904

[OSSMC] View in tracing integration with the tracing UI

---

business/layer.go
handlers/apps.go
handlers/dashboards.go
handlers/health.go
handlers/istio_config.go
handlers/metrics.go
handlers/namespaces.go
handlers/proxy_logging.go
handlers/proxy_status.go
handlers/services.go
handlers/tls.go
handlers/tracing.go
handlers/utils.go
handlers/utils_test.go
handlers/workloads.go
routing/routes.go

Refactors the istio config handlers and passing config into `clusterNameFromQuery` func. Where `config.Get()` is used now, it will be updated to pass conf once the signature of the remaining handlers are updated.
N/A
Covered by existing tests.
https://github.com/kiali/kiali/issues/6923

Refactor istio config handlers and update clusterName func

---

handlers/istio_status.go
handlers/metrics_test.go
handlers/workloads.go
handlers/workloads_test.go
routing/routes.go

Refactors istio status and workload handlers to use closures instead of global vars. Moves workload metrics tests into the `metrics_test.go` file since that's where the handler is.
N/A
Existing tests pass.
https://github.com/kiali/kiali/issues/6923

Refactor istio status and workload handlers

---

hack/README.adoc
hack/istio/bookinfo-traffic/bookinfo-service-entry.yaml
hack/istio/install-bookinfo-demo.sh
hack/istio/install-bookinfo-workload-entry.sh
hack/istio/install-istio-via-istioctl.sh
hack/istio/multicluster/deploy-kiali.sh
hack/istio/multicluster/env.sh
hack/k8s-minikube.sh

rely on other more friendly image repos
Run this to see the hack files that have `docker.io` in them - many of those need to change.
```
grep -Rl 'docker[.]io' --exclude docker-io-auth.sh hack
```
fixes: https://github.com/kiali/kiali/issues/8278

remove docker.io from as many places in hack scripts as possible

---

handlers/istio_config.go
handlers/metrics_test.go
handlers/namespaces.go
handlers/namespaces_test.go
handlers/proxy_logging.go
handlers/proxy_logging_test.go
kubernetes/kubetest/fake.go
routing/routes.go

Refactors proxy logging and namespace handlers. Moves some namespace metrics tests into `metrics_test.go` and moves an istio config handler into `istio_config.go`.
N/A
Covered by existing tests.
https://github.com/kiali/kiali/issues/6923

Refactor proxy_logging and namespace handlers

---

make/Makefile.molecule.mk

After a recent set of operating system updates, I'm now seeing "podman cp" hang infintely. Not sure why. But this PR changes the way the molecule image is created which works around this problem. I also moved away from another docker.io image being used here... moving to quay.io.
To test, just run a simple molecule test run of the "default" molecule test - these three commands:
```
hack/k8s-minikube.sh start
hack/k8s-minikube.sh istio
make CLUSTER_TYPE=minikube MOLECULE_SCENARIO="default" molecule-test
```

[make] workaround podman cp hanging; also move off of docker.io

---

kubernetes/cache/cache.go
kubernetes/cache/kube_cache.go
kubernetes/cache/kube_cache_test.go
kubernetes/cache/testing.go

Pass a custom sync func to reduce polling times in unit tests.
Reduces unit tests times on my machine from ~27s --> 18.3s
Run this before and after to see the time difference:
`go clean -testcache && make test`
N/A
N/A
Thanks to @howardjohn blog for pointing this out to me: https://blog.howardjohn.info/posts/kube-client/#better-testing!

Optimize unit tests

---

mesh/generator/generator.go

There was missing cluster name in getting addons component status for Mesh page.
Causing wrong status in Mesh page for Obsevability components.
Set 0 replicas on adsons Grafana and Jaeger.
The Warning should be in masthead.
Those 2 Observability components should be displayed Unreachable.
n/a
https://github.com/kiali/kiali/issues/8279

Added default cluster name in addon status

---

business/istio_status.go
business/workloads.go
business/workloads_test.go

Fix gateway caching. It was caching only gateways of a single cluster.  This was causing a MC test failure because istio status for "west" was coming back as "east", because the gateways were from "east".
Fixes https://github.com/kiali/kiali/issues/8306

Fix primary-remote CI failure

---

hack/crc-openshift.sh

The network-mode is now "user" by default, check for that and use ssh port 2222 if so
1. Clean up your old CRC install: `hack/crc-openshift.sh cleanup`
2. Move your old crc binary to make room for the new one: `mv "$(which crc)" "$(dirname "$(which crc)")/crc.old"`
3. Run the new CRC hack script, making sure to pass in your pull secret file: `hack/crc-openshift.sh start -p <your pull secret file> start`
It should install file, you should now be running OpenShift 4.18, and the status output should be complete. Run `hack/crc-openshift.sh status` again to see that you do not get any prompts - you should see all the status information for your cluster.

[hack] bump to CRC 2.49 / OS 4.18 and fix status command

---

business/checkers/gateways/multi_match_checker.go
business/checkers/gateways/multi_match_checker_test.go

In Gateway config validation there is a Warning "KIA0301 More than one Gateway for the same host port combination".
Skip this warning when two hosts have wildcards in their FQDN, like "*.host.com" and "*.subdomain.host.com"
Create a Gateway with hosts:
"*.host.com" and "*.subdomain.host.com"
Make sure that the validation warning is not shown for them:
Modify the hosts **both** to be:
"*.host.com"
Verify that the validation KIA0301 is shown:
Added more automations.
https://github.com/kiali/kiali/issues/8174

Skip KIA0301 when both hosts are wildcard but not equal

---

business/workloads.go

Fixes typo in warning message: cature -> capture
Also fix a couple of typos in a comment
n/a
n/a
n/a

Fix typo in warning log

---

.github/workflows/molecules.yml

GH actions wan't honoring the exit value of the script ci-kind-molecule-tests.sh, so I simplified the script and now it's working:
Example with no failure:
https://github.com/leandroberetta/kiali/actions/runs/14405688709 (run from my master branch)
Example with failure:
https://github.com/leandroberetta/kiali/actions/runs/14405487031 (run from my molecule-failure branch where I mock the error)

Fix molecule testing to catch errors in the molecule tests

---

hack/istio/multicluster/start-minikube.sh

On Fedora 41, I needed to remove the following line because it throws an error as the configuration is already in the req.cnf
After deleting this, the certs were created fine.

Removed duplicated subjectAltName

---

frontend/cypress/integration/common/overview.ts
hack/istio/install-istio-via-sail.sh
hack/istio/istio-gateway.yaml
hack/istio/multicluster/install-primary-remote.sh

Updates the primary-remote pipeline to use sail instead of istioctl.
`hack/run-integration-tests.sh --test-suite frontend-primary-remote`
CI should pass.
Fixes #8097

Use Sail Operator in primary-remote setup

---

business/istio_validations.go
business/workloads.go
graph/options.go
graph/telemetry/istio/appender/appender.go
graph/telemetry/istio/appender/extensions.go
graph/telemetry/istio/istio.go
mesh/generator/generator.go
mesh/options.go
models/metrics.go
tracing/client.go

Minor perf enhancement to generate keys by concatenating string.Join or +, as opposed to fmt.Sprintf. These alternatives are faster and use less memory.
This is related to, and will close #8007 subtask, `pre-compute validation keys for istio config objects`. The pre-compute wasn't really viable, it was doable but not worth the complexity, as we would need to create type wrappers to hold the pre-compute value, for likely nominal gain.
There isn't much testing here, probably a visual sanity check and green CI.

Minor perf enhancement to improve key generation

---

hack/istio/multicluster/setup-tracing.sh
hack/run-integration-tests.sh

Moves off the docker hub image and onto the gcr otel collector image. My guess is that CI was being rate limited which is why the tracing wasn't being exported. Also we weren't waiting for the helm installation of the otel collector to succeed which is probably the source of a number of other flakes. We also weren't failing the tests when the trace check failed.
CI passes.
Covered.
N/A

Use gcr otel collector image

---

hack/istio/install-istio-via-sail.sh
hack/istio/multicluster/setup-external-controlplane.sh
hack/run-integration-tests.sh

Use Sail Operator to install Istio in external controlplane pipeline.
`hack/run-integration-tests.sh --test-suite backend-external-controlplane`
Included
Fixes #8098

Use Sail in external controlplane pipeline

---

hack/istio/multicluster/env.sh
hack/istio/multicluster/install-multi-primary.sh
hack/istio/multicluster/install-primary-remote.sh
hack/istio/multicluster/setup-external-controlplane.sh
hack/setup-kind-in-ci.sh

Passes istio version through to various install scripts.
Run a test suite with `--istio-version` and ensure that the istio version that gets created is the one passed in.
1. `hack/run-integration-tests.sh --test-suite backend-external-controlplane --setup-only true --istio-version 1.24.3`
2. `kubectl get istios`
Tests passing. Specifically the istio version test.
Fixes #8289

Pass istio version through to all install scripts

---

deploy/docker/Dockerfile-distroless
deploy/docker/Dockerfile-multi-arch-distroless

The ubi9/openssl base image is deprecated. We no longer want to use it. Let's create our own base image that is the same thing - this will ensure we get the latest updates for each of our build releases.
This code was taken from the now-deprecated ubi9/openssl Dockerfile: 
* https://catalog.redhat.com/software/containers/ubi9/openssl/6195a359ce09ff98ccc36340?container-tabs=dockerfile
The distro release is still produced for those that want to use it (usually this is just for debugging purposes). The distroless release is the new one. It looks good, I tested in my own fork to see if this works, which it does. The release that I built in my fork was 2.9.1 (`quay.io/jmazzitelli/kiali:v2.9`)
```
$ podman run -it --rm --entrypoint '' quay.io/jmazzitelli/kiali:v2.9 openssl version
OpenSSL 3.2.2 …
```

Build our own base image which is essentially ubi-micro + openssl/certs

---

frontend/cypress/integration/featureFiles/app_details.feature
frontend/cypress/integration/featureFiles/app_details_multicluster.feature
frontend/cypress/integration/featureFiles/service_details.feature
frontend/cypress/integration/featureFiles/workload_logs.feature
frontend/cypress/integration/featureFiles/workloads_details.feature

The Jaeger operator is no longer available in the OCP 4.19 catalog, so it will be removed from our LPINTEROP jobs. (We have not set Tempo yet; it will be part of OSSM3 lpinterop.)
Due to that, we need to skip tracing tests in lpinterop pipelines (the tests are still running in our downstream pipeline with Tempo integration)

[v1.73] Skip tracing tests in lpinterop pipelines

---

business/test_util.go
business/workloads.go
business/workloads_test.go

Istio did some changes in support of retrieving Argo Rollouts https://github.com/istio/istio/pull/49256
Thus our changes we did in PR https://github.com/kiali/kiali/pull/5491 is not necessary anymore,
Reverting changes.
The original issue has well described scenarios how to install the env:
https://github.com/kiali/kiali/issues/8284#issuecomment-2817173896
Before: There was a problem linking to Workload details page, and workload list page was showing odd ReplicaSets with empty names which details page was failing.
Now: Workload lists shown correct info which details page is loaded correctly and is read-only. App details is shown as read-only as well.
Only thing is that only one of ReplicaSet's Pods are shown in Workload details.
n/a
https://github.com/kiali/kiali/issues/8284

Reverted workaround changes in PR#5491 for Rollouts support

---

config/config.go
istio/discovery.go
kubernetes/cache/cache.go
kubernetes/cache/cache_test.go
kubernetes/cache/ztunnel_dump.go
kubernetes/istio.go

Prevent returning the istiod status if there are no access to ztunnel config dump, making the code more robust. 
I was not able to reproduce the scenario where the ztunnel pod is not correct, but if this situation happens, returning the istiod status might prevent some errors:
I've emulated the situation changing here: https://github.com/kiali/kiali/blob/master/kubernetes/cache/cache.go#L363 `config.ztunnel` for "cni" (Or whatever string that matches).
https://github.com/kiali/kiali/discussions/8364

Prevent returning the istiod status if no access to ztunnel config dump

---

tests/integration/tests/kiali_urls_test.go
tests/integration/tests/traces_spans_test.go

Jaeger is not available in OCP 4.19+ . Due to that, skip integration tests regarding tracing ( that tests will still be running as part of our downstream pipelines with Tempo )
Ticket: https://issues.redhat.com/browse/OSSM-9386 
Verified manually ([jenkins job](https://jenkins-csb-servicemesh-master.dno.corp.redhat.com/job/kiali/job/test-jobs/job/kiali-integration-tests/3539/)) against cluster without jaeger. (the PR gating job is not working due to https://github.com/kiali/kiali/pull/8366 )

[v1.73] Skip integration tests in lpinterop pipelines regarding tracing

---

make/Makefile.container.mk
tests/integration/Dockerfile

Backport of https://github.com/kiali/kiali/pull/7372 + update kiali int test container to rhel9
Resolving: https://github.com/kiali/kiali/issues/8376 to be able to rebuild v1.73 kiali integration test image
(the new image is needed to use LPINTEROP env for kiali integration tests https://github.com/kiali/kiali/pull/8375 in LPINTEROP pipelines)
===
Verified manually in my fork (https://github.com/mkralik3/kiali/actions/runs/14705552918 (https://quay.io/repository/mkralik3/kiali-int-tests?tab=tags))
(the PR gating jobs are not working due to https://github.com/kiali/kiali/pull/8366 )

[v1.73]backport: test container takes go version from makefile (#7372)

---

frontend/cypress/integration/featureFiles/kiali_about.feature
frontend/cypress/integration/featureFiles/kiali_alert.feature

Skip one more test after Jaeger removal in lpinterop (note that in our downstream pipeline, the all tests are still running)

[v1.73] Skip flaky cypress tests in lpinterop

---

.github/workflows/test-istio-version.yml
hack/istio/download-istio.sh

Test Istio Version GH run is failing because the latest minor Istio version is not available in Sail (ex. https://github.com/kiali/kiali/actions/runs/14688366334/job/41220128371). Use as patch version -latest, supported in Sail
I wasn't sure how to test this in the GH actions, so I run the run: command isolated on a sh script. 

Use -latest as patch version

---

deploy/docker/Dockerfile-cypress
tests/integration/Dockerfile

Backport https://github.com/kiali/kiali/pull/7236 (which is only in v1.73 branch)
Fix for [runtime error](https://github.com/kiali/kiali/issues/8376) in the current kiali integration test container
```
oc: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by oc)
oc: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by oc)
oc: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by oc)
```

Bump to RHEL9 in kiali integration tests container

---

frontend/cypress/integration/common/waypoint.ts
frontend/cypress/integration/featureFiles/waypoint.feature
frontend/public/locales/es/translation.json
frontend/public/locales/zh/translation.json
frontend/src/components/Ambient/Filters/Filters.tsx
frontend/src/components/Ambient/Filters/ZtunnelFilters.tsx
frontend/src/components/Ambient/Filters/ZtunnelLabels.tsx
frontend/src/components/Ambient/ZtunnelConfig.tsx
frontend/src/components/Filters/StatefulFilters.tsx
frontend/src/types/IstioObjects.ts

Include filter by name/namespace in ztunnel table
- Install Istio Ambient
- Go to ztunnel workload details
- Go to ztunnel tab
- Use the filters in services/Workloads. Validate it work as expected
- cy test for filter
Closes #7996

Include filter by name/namespace in ztunnel table

---

hack/setup-kind-in-ci.sh
make/Makefile.build.mk
tests/integration/controller/suite_test.go

Follow up of: https://github.com/kiali/kiali/pull/8378
Some tests are still failing: https://github.com/kiali/kiali/actions/runs/14746679127/job/41395384846 
- `make $(if [ -n "1.24-latest" ]; then echo "ISTIO_VERSION=1.24-latest"; fi) test-integration-controller`
- `hack/run-integration-tests.sh --test-suite frontend-multi-primary $(if [ -n "1.24-latest" ]; then echo "--istio-version 1.24-latest"; fi)`
Test Istio Version pipeline
Ref. https://github.com/kiali/kiali/pull/8378

Fix failures for Test Istio Version jobs

---

business/istio_config.go
business/istio_config_test.go
config/config.go
controller/validations.go
handlers/istio_config.go
kiali.go

Resolves https://github.com/kiali/kiali/issues/8317
If *validation_reconcile_interval* is 0 (0s), then Kiali won't create the periodic validations controller.
I believed that there is no need for a change in the operator.
```yaml
spec:
istio:
validation_reconcile_interval: "0s"
```

Skip validations if  reconcile interval is 0s

---

tracing/tempo/http_client.go

Update tracing query for errors, error tag doesn't exist, so the query uses http.status_code != 200
In minikube
- Install Kiali and Tempo (hack/istio/tempo/install-tempo-env.sh -c kubectl)
- Install bookinfo and create an Error rates traffic policy
- Go to a service with errors and select the "Show only traces with errors option"
Fixes #8406

Update tracing query for errors

---

business/istio_config.go
business/istio_validations.go
cache/cache.go
config/config.go
frontend/src/components/IstioWizards/K8sGatewaySelector.tsx
frontend/src/pages/IstioConfigNew/K8sGatewayForm.tsx
handlers/config.go
kubernetes/istio.go
mesh/api/testdata/test_mesh_graph.expected

When `gateway_api_classes:` is not set in Kiali CR, when Gateway API Classes are auto-discovered.
The auto discovery can use `gateway_api_classes_label_selector:` config for filtering those objects, which by default is empty.
a. Regression testing then K8s Gateway API CRDs are not installed. No error in Kiali logs.
b. Install CRDs, leave  `gateway_api_classes:` empty. Go to Isto configs page's Actions wizard, create a new K8sGateway. Verify that the system installed Gateway API Classes are shown in dropdown.
Verify that in created K8sGateway, the `gatewayClassName` is set, and when has a wrong value, the validation error is shown.
b1. Similar to previous one, but add a value for `gateway_api_classes_label_selector: "key=value"`. Verify that the filtered list is shown.
b2. …

Gateway API Classes auto-discovery

---

mesh/api/api.go
prometheus/internalmetrics/internal_metrics.go

fixes: https://github.com/kiali/kiali/issues/8429
This code will need to be updated to use the new common observe-and-log function once [this](https://github.com/kiali/kiali/pull/8427) is merged, but we can do that as part of that PR, if we can merge this one first.
@jshaughn I just need confirmation - there are NO appenders that are invoked when generating a mesh graph, correct?

get mesh graph generation metrics

---

make/Makefile.molecule.mk

Enhance cleanup process for molecule tests by ensuring all related resources are removed before creating new volumes
Do we need to backport this into older branches?

Molecule make update

---

prometheus/client.go
prometheus/prometheustest/mock.go

There was unused GetFlags() method in Prometheus client, removed it.
Regression testing.
n/a
https://github.com/kiali/kiali/issues/8405

Removed unused Prometheus client's GetFlags function

---

business/services.go
cache/transform.go
kiali.go
kubernetes/filters.go
kubernetes/filters_test.go
kubernetes/kubetest/mock_kubernetes.go
kubernetes/types.go
models/address.go
models/endpoint.go
models/endpoints_test.go
models/port.go
models/service.go
models/service_test.go

Removed loading Endpoints from the cache, and instead load the necessary data for Service details from Pods.
Regression testing that Service detail's Networking Section Endpoints is still showing correct IP addresses and tooltip:
existing tests should not pass
https://github.com/kiali/kiali/issues/8396

Get Service Endpoint IP Addresses from Pods.

---

hack/istio/multicluster/verify-kiali-permissions.sh

fixes: https://github.com/kiali/kiali/issues/8358
test procedures are [here](https://github.com/kiali/kiali/pull/8460#issuecomment-2908460384) and [here](https://github.com/kiali/kiali/pull/8460#issuecomment-2919794187)
The important thing to notice here is that this script [will look at](https://github.com/kiali/kiali/pull/8460/files#diff-868101df9f7266cab67bf9980637931b63af4fb5f1647e92617da384eeec4348R182) the role that will be assigned to the user (it does this by looking at the role generated by the server helm chart) and that role's permissions are checked:
```bash
mapfile -t RESOURCES_ARR < <(echo "$ROLE_YAML" | yq eval-all '. | select(.kind == "ClusterRole") | .rules[].resources[]' - | sort -u)
```
All those permissions will be [confirmed with `auth can-i` …

script to check if a remote cluster secret is correct

---

config/config.go
frontend/src/pages/Graph/GraphElems.tsx
graph/telemetry/istio/appender/istio_details.go

Explanation of what this PR does
- Install any K8s GW and see if it has the GW icon in the graph. 
- An example with Istio Ambient: 
`istio/install-bookinfo-demo.sh -c kubectl -ai false -tg -w true`
Already supported: 
Fixes #8442

Add logic to show GW icon

---

business/test_util.go
business/workloads.go
cache/cache.go
cache/cache_test.go
config/config.go
kubernetes/filters.go
mesh/api/testdata/test_mesh_graph.expected

Include a partial match field in FilterDaemonSetsBySelector so the selector can be a superset of the filter.
The motivation is to match ztunnel even if it includes more selectors than just the label app=ztunnel 
- Verify Istio Ambient is enabled by just installing Istio Ambient
- Verify Istio Ambient is enabled by adding a new selector to ztunnel*
- Verify Istio Ambient is disabled when Istio is installed in the default profile.
*Followed the steps: 
`k get daemonset ztunnel -n istio-system -o yaml > ztunnel.yaml`
edit ztunnel.yaml to add additional selectors
`k delete daemonset ztunnel -n istio-system`
`k apply -f ztunnel.yaml -n istio-system`
CI should pass
Fixes https://github.com/kiali/kiali/issues/8464

Add partial selector match for ztunnel

---

handlers/workloads.go

The 'gvk' param name was wrong in UpdateWorkload, causing conflict in backend.
Edit Workload Details in Actions, change Annotations or Injection.
It should not fail.
Fixes https://github.com/kiali/kiali/issues/8478

Fixed the gvk param name in workload update request

---

kubernetes/kubernetes.go

part-of https://github.com/kiali/kiali/issues/8478
An unlikely issue, but possible if someone enables all workload types but isn't on openshift.

Don't let the DeploymentConfig case fall through if not on OpenShift

---

frontend/cypress/integration/common/sidecar_injection.ts
frontend/src/pages/AppDetails/AppDetailsPage.tsx
frontend/src/pages/ServiceDetails/ServiceDescription.tsx
frontend/src/types/App.ts
handlers/workloads.go
models/app.go

Replaced 'workloadGVK' param in json and requests by a 'gvk'
Fixed sending 'gvk' to server instead of old 'type' param.
Regression testing in Workload/App lists and details pages required.

Replaced workloadGVK param with gvk

---

frontend/cypress/integration/common/traffic_policies_multicluster.ts
frontend/cypress/integration/featureFiles/apps.feature
frontend/cypress/integration/featureFiles/waypoint.feature

Sidecar was removed from traffic generator by https://github.com/kiali/kiali-test-mesh/pull/80 . 
Adapted cypress tests

Update cypress tests after sidecar was removed from traffic generator

---

istio/discovery.go

Merge shared config map 
- Install Istio with: 
```
"--set values.pilot.env.SHARED_MESH_CONFIG=istio-cn" \
"--set values.meshConfig.defaultConfig.proxyMetadata.group1=group" \
```
Create a configmap: 
```
apiVersion: v1
kind: ConfigMap
metadata:
name: istio-cn
data:
mesh: |-
defaultConfig:
proxyMetadata:
group2: group
```
Apply it, and verify proxyMetadata is using both values, for example: 
Verify the Istio config map in Kiali has merged values as well: 

Merge shared config map

---

hack/ci-kind-molecule-tests.sh
hack/ci-openshift-molecule-tests.sh
hack/istio/multicluster/deploy-kiali.sh
hack/istio/skupper/install-skupper-demo.sh
hack/perf-ibmcloud-openshift.sh
hack/test-pull-request.sh

Now that the frontend UI code is embedded in the container, we have to run build-ui target first, and then build. I found this change (swapping the order of the make targets) was not done in some hack scripts. This PR fixes that.

[hack] build-ui must now be done first before build

---

hack/istio/multicluster/env.sh
hack/istio/multicluster/install-multi-primary.sh
hack/istio/multicluster/install-primary-remote.sh

fixes: #8512
You only see the bug if prometheus is installed in a cluster that doesn't have a loadbalancer IP (I see this when installing in a cluster of OpenShifts). Now this just spits out a warning rather than erroneously making a change to the hack file prometheus.yaml
NOTE: this also fixes a minor bug regarding the name of the helm chart to be used by default

[hack] do not change committed files when running hack scripts

---

frontend/cypress/integration/common/traffic_policies_multicluster.ts
frontend/cypress/integration/featureFiles/apps.feature
frontend/cypress/integration/featureFiles/waypoint.feature

Backport of https://github.com/kiali/kiali/pull/8488

[2.4] Update cypress tests after sidecar was removed from traffic generator

---

frontend/cypress/integration/common/mesh.ts

There was a potential flaky test which was up/down scaling the Grafana pod and checking it's status on Mesh page.
Added a iteration to retry the status check, because 40000ms could be not enough based on the environment.
https://github.com/kiali/kiali/issues/8503

[CI] flaky fix, added iteration retry on graph side panel icons

---

hack/istio/kustomization/bookinfo-ppc64le.yaml
hack/istio/kustomization/bookinfo-s390x.yaml

Istio 1.26 has newer version of bookinfo images. We rebuild the images for IBM platforms.
https://issues.redhat.com/browse/OSSM-9664

Bump bookinfo images to 1.20.3 for IBM P/Z

---

config/config.go
frontend/cypress/integration/common/mesh.ts
frontend/cypress/integration/featureFiles/mesh.feature
frontend/src/components/IstioStatus/IstioComponentStatus.tsx
frontend/src/components/IstioStatus/IstioStatus.tsx
frontend/src/components/IstioStatus/IstioStatusList.tsx
frontend/src/components/IstioStatus/__tests__/IstioComponentStatus.test.tsx
frontend/src/components/IstioStatus/__tests__/IstioStatus.test.tsx
frontend/src/components/IstioStatus/__tests__/IstioStatusList.test.tsx
frontend/src/components/IstioStatus/__tests__/__snapshots__/IstioStatus.test.tsx.snap
frontend/src/components/IstioStatus/__tests__/__snapshots__/IstioStatusList.test.tsx.snap
frontend/src/components/Mesh/TraceConfigurationModal.tsx
frontend/src/types/IstioStatus.ts
frontend/src/types/StatusState.ts
frontend/src/utils/tracing/UrlProviders/Tempo.ts
frontend/src/utils/tracing/UrlProviders/index.ts
kubernetes/istio.go
mesh/api/testdata/test_mesh_graph.expected

Unify the format of the configs in the Mesh page using lower camel case:
- Validate configs are in the same format (lower camel case)
- Regression test
Updated required tests
Fixes https://github.com/kiali/kiali/issues/8493

Unify the format of the configs in the Mesh page

---

business/metrics.go
handlers/metrics.go

This approach replaces the query by specific pods `{pod="istiod-6f67cdbfc9-4vd4w"}` by `{pod=~"istiod-.*"}` because: 
- It keeps stats along the time if the deployment is restarted
- Keeps consistency (E.x. kind doesn't provide stats by specific pod) 
- Istio query metrics are using the same regex in Grafana dashboards
- It doesn't need to get the control plane logs, so it can be a bit faster
- This change should remove flakes in the jenkins pipelines 
- Install Istio
- Go to the mesh page
- Stats should be available: 
CI should pass
Fixes https://github.com/kiali/kiali/issues/8552

Update Istio metrics

---

frontend/cypress/integration/common/mesh.ts
frontend/cypress/integration/featureFiles/mesh.feature
frontend/src/pages/Mesh/target/TargetPanelCommon.tsx

Fixed the number of dataplane namespaces shown for control plane namespace in Mesh page.
Before, showing 0:
After, showing the correct number:
added cypress check
https://github.com/kiali/kiali/pull/8499

Fixed dataplane namespaces number

---

business/istio_validations.go
business/references/k8s_gateway_references.go
business/references/k8s_inference_pool_references.go
business/references/k8s_inference_pool_references_test.go
business/references/k8shttproute_references.go
business/references/k8shttproute_references_test.go

Added cross references between K8s HTTPRoute and InferencePool.
Make sure K8s Gateway API and Inference Extensions CRDs are installed.
`kubectl get crd gateways.gateway.networking.k8s.io || { kubectl kustomize "github.com/kubernetes-sigs/gateway-api/config/crd?ref=v1.3.0" | kubectl apply -f -; }
`
`kubectl kustomize "github.com/kubernetes-sigs/gateway-api-inference-extension/config/crd?ref=v0.4.0" | kubectl apply -f -;`
Create these objects.
```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
name: model-llama3-route
namespace: default
spec:
parentRefs:
- name: my-gateway
namespace: default
hostnames:
- "llama3.example.com"
rules:
- matches:
- path:
type: PathPrefix
value: /
backendRefs:
- name: llama3-pool
kind: InferencePool
namespace: default
group: …
```

Added HTTPRoute to InferencePool cross references.

---

frontend/package.json
frontend/yarn.lock

Upgrade some frontend libraries to upgrade form-data dependency to version 4.0.4:
- Axios from v1.8.4. to v1.11.0
- @cypress/request from v3.0.1 to v3.0.9
Additionally, this PR upgrades directly form-data to version 3.0.4.
Verify that CI tests pass.

Upgrade form-data frontend dependency

---

business/controlplane_monitor.go
config/config.go
istio/constants.go
istio/discovery.go
istio/discovery_internal_test.go
istio/version.go
istio/version_test.go
mesh/api/testdata/test_mesh_graph.expected
models/mesh.go

- Autodetects the monitoring port instead of assuming it is the default `15014`.
- Does this by parsing the istiod args for what is passed in the `--monitoringAddr` cmd line flag. This could have come from the deployment's ports but there's no guarantee that what is set there matches what gets passed as an arg.
- Removes the `IstiodPodMonitoringPort` config setting as part of https://github.com/kiali/kiali/issues/8576
- Adds structured logging to the control plane monitor and properly passes context through
```
2025-07-28T19:06:32Z DBG Getting proxy status from istiod cluster=cluster-default component=controlplane-monitor revision=default
E0728 19:06:32.081872       1 portforward.go:424] "Unhandled Error" err="an error occurred forwarding 14052 -> 15014: error forwarding port 15014 to pod …
```

Autodetect the istiod monitoring port

---

.github/workflows/kiali-ci.yml
hack/istio/multicluster/deploy-kiali.sh
hack/istio/multicluster/install-external-kiali.sh
hack/istio/multicluster/install-multi-primary.sh
hack/run-integration-tests.sh
hack/setup-kind-in-ci.sh

Closes #8612 
Currently running with `anonymous`, but for upstream production we need to support `openid`.  This PR:
- changes the auth strategy for the external-kiali CI from `anonymous` to `openid`
- adds some missing keycloak support in the `install-external-kiali.sh` hack script
- protects `deploy-kiali.sh` from an assumption that bookinfo will always exist
- adds some missing `infomsg` support in a couple of hack scripts

Run External kiali CI with openid auth strategy

---

hack/purge-kiali-from-cluster.sh

this was mainly because when I ask Cursor to run molecule tests, sometimes it needs to purge kiali resources and when it does it seems like it goes so fast the CRD doesn't clean up and the test fails. I am not convinced this fixes the problem entirely, but it helps.

[hack] update the resources that are purged, wait for CRDs to delete

---

frontend/src/pages/WorkloadDetails/WorkloadDescription.tsx

In a case when cluster name was shown in Workload Details page, the Validations icon was on the same line with it,
fixed now to be on a new line:
Multicluster env.
n/a
https://github.com/kiali/kiali/issues/8648

Fixed Workload Validations style

---

business/apps.go
business/health.go
business/istio_status.go
business/istio_status_test.go
business/services.go
business/workloads.go
models/workload.go
models/workload_test.go

Fixes https://github.com/kiali/kiali/issues/8657
Several WorkloadService functions, most notably `GetAllWorkloads`, had the potential for a circular call paths in ambient environments. The resulting recursion could cause OOM or perf issues.  The fundamental problem is that the required logic is a bit circular, where we want to decorate workloads with waypoint information, but waypoints themselves are workloads.
The updated approach is to ensure, when needed, that we first fetch all waypoint workloads, and then pass the waypoints down into the logic collecting the requested workloads. The prior logic fetched the waypoint workloads as needed, but that could end up calling the original entry points functions.
I considered gathering the Waypoints at in NewWorkloadService(), so they would …

[ambient] avoid circular calling when fetching workloads with waypoint information

---

business/mesh.go
hack/istio/install-istio-via-istioctl.sh
handlers/metrics.go
istio/discovery.go

In Mesh page, when clicking on 'istiod' from another mesh and control-plane, show the into in side panel and do not display error.
Install several versions of Istio on the same cluster, by putting different meshIDs.
`/hack/istio/install-istio-via-istioctl.sh -c oc -iv 1.24.0 -mid istio_24 -n istio-system-24 -ir "default-v1-24-0"`  
`/hack/istio/install-istio-via-istioctl.sh -c oc -iv 1.25.0 -mid istio_25 -n istio-system-25 -ir "default-v1-25-0`
`oc create namespace bookinfo25`
`oc create namespace bookinfo24`
`kubectl label namespace bookinfo25 istio.io/rev=default-v1-25-0`
`kubectl label namespace bookinfo24 istio.io/rev=default-v1-24-0`
or similar.
Go to Mesh page.
Click on all 'istiod's, and you will see the side panel correctly shown with Istio Version and the rest.
And and cluster …

Mesh Namespace check in ControlPlanes.

---

.github/workflows/integration-tests-backend-multicluster-external-controlplane.yml
.github/workflows/integration-tests-backend.yml
.github/workflows/integration-tests-frontend-ambient.yml
.github/workflows/integration-tests-frontend-multicluster-multi-primary.yml
.github/workflows/integration-tests-frontend-multicluster-primary-remote.yml
.github/workflows/integration-tests-frontend-tempo.yml
.github/workflows/integration-tests-frontend.yml
hack/setup-kind-in-ci.sh

Running from master I've go the error: 
```
=== SETTINGS ===
[INFO] Running backend-external-controlplane integration tests
Istio install script: ~/kiali_sources/kiali/hack/istio/install-istio-via-sail.sh
[INFO] Evaluating helm-charts branch candidate: []
[INFO]  -> branch skipped (empty)
[INFO] Evaluating helm-charts branch candidate: []
[INFO]  -> branch skipped (empty)
[INFO] Evaluating helm-charts branch candidate: [master]
[INFO] Evaluating helm-charts branch [master] of owner []: https://github.com//helm-charts.git
Username for 'https://github.com': 
```
Git this change, just kiali is set (Not empty string) 
Also, use TARGET_BRANCH when BUILD_BRANCH is empty
Run any test suite, for example: 
`hack/run-integration-tests.sh --test-suite backend-external-controlplane`
If applicable, …

Don't add GH actor if it is empty

---

frontend/cypress/integration/featureFiles/waypoint.feature
hack/istio/functions.sh
hack/run-integration-tests.sh

This reverts commit e3d2c4c7345071f0718f50685e9c164e0c955212.
As istio 1.23 is no longer supported, remove the code for testing handling this version
Recommendations for how to test this PR. Reminder that each PR should also include a "Test" label.

[CI] Remove support in testing for Istio 1.23

---

.gitignore
Makefile
make/Makefile.ui.mk

Adds `tmp/` to `.gitignore` and makes the default `YARN_START_URL` = the default `make run-backend` url so that you don't need to provide it anymore.
1. Deploy istio
2. Run make targets
```
make run-backend
make run-frontend
```
3. `tmp` should not appear when you do `git status` and the `proxy` field should get automatically cleaned up when you exit `make run-frontend`.
N/A
None

Cleanup the run make targets

---

frontend/cypress/integration/common/apps.ts
frontend/cypress/integration/common/graph_display.ts
frontend/cypress/integration/common/navigation.ts
frontend/cypress/integration/common/transition.ts
frontend/cypress/integration/featureFiles/app_details.feature
frontend/cypress/integration/featureFiles/services.feature
frontend/cypress/integration/featureFiles/waypoint.feature
frontend/cypress/integration/featureFiles/workloads.feature
frontend/src/components/DetailDescription/DetailDescription.tsx
handlers/dashboards.go
handlers/metrics.go

- OSSMC doesn't have a list of workloads/services, so skipping the tests for list related to `waypoints`
- Added timeout in get table and get - It was failing using tests in UI
- intercepting graph namespace was failing for ossmc due to the redirection
- Added pods for testing in details page for the pods that don't include a deployment (ossmc)
- Skipped tests for waypoint and list pages
- Required to enable traffic option "ambient" to have the other sub options available
- Removed control plane check in the handler for metrics and ztunnel dashboard. Resource usage metrics are used by Kiali and Ztunnel, they might not be deployed in the controlplane namespace. 
- Added data tests for detail description link when it is parent kiosk as well
- Use this PR: …

[CI] ossmc tests

---

.github/workflows/bump-release-version.yml
.github/workflows/tag-release-creator.yml

This PR enhances the tag release creation workflow by adding functionality to automatically bump to the next version after creating a release tag. Additionally, the latest tag of the branch is analyzed to verify if it is the expected one to avoid errors during the workflow.

[GH Action] Option to bump to the next version after the tag release creation

---

hack/istio/tempo/install-tempo-env.sh

Adds a sleep before creating tempo operator. The thought here is that these kinds of failures in CI:
are due to the [cert-manager webhook's dynamic cert](https://github.com/cert-manager/cert-manager/blob/e2aa55ced7cf3ef8878d8c81a73a0d132fa462e8/deploy/charts/cert-manager/templates/webhook-deployment.yaml#L103-L107) not being loaded in time before the Tempo operator manifest tries to create a cert-manager resource like `Certificate` and calls the webhook.
I searched around a bit and [this](https://github.com/cert-manager/cert-manager/issues/7687) might be a similar issue.
N/A
N/A
N/A

[CI] Attempt to fix tempo flake

---

frontend/package.json
frontend/yarn.lock

Upgrade axios frontend dependency to version 1.12.2

Upgrade axios frontend dependency

---

config/config.go
frontend/src/config/ServerConfig.ts
frontend/src/pages/WorkloadList/FiltersAndSorts.ts
frontend/src/types/ServerConfig.ts
frontend/src/utils/IstioConfigUtils.ts
frontend/src/utils/__tests__/IstioConfigUtils.test.ts

I'm in the process of evaluating and rolling out Kiali and I have noticed the UI hides certain useful observability features (logs, metrics, traces) for workloads with unknown GVKs.
For me specifically this affects the Argo `Rollout` resources which we favor internally almost exclusively over `Deployment` but I presume it affects other custom controllers that also manage pods.
There is a whitelist in the Kiali product that couples these observability features to controller recognition.
However, AFAIK these restricted observability features operate at pod/mesh level and require no controller understanding.
I could not find an existing configuration property to augment the whitelist so this PR adds one allowing users to enumerate custom GVKs to be considered during the UI feature …

Support custom GVKs in UI observability feature gating

---

frontend/cypress/integration/featureFiles/mesh.feature
mesh/generator/generator.go

Added Kiali local mode in Mesh page.
For simplicity and escaping further fixes with metrics load and other side panel items loading, showing Kiali in current cluster.
Start Kiali in local mode: Steps here https://github.com/kiali/kiali/pull/8274
Make sure that Kiali is shown in Mesh page:
Added new cypress test.
https://github.com/kiali/kiali/issues/8668

Show local mode Kiali in Mesh
