kiali/kiali

- Makefile
- README.adoc
- config.yaml
- config/config.go
- config/config_test.go
- config/security/config_security.go
- config/security/config_security_test.go
- deploy/docker/Dockerfile
- deploy/kubernetes/sws-configmap.yaml
- deploy/kubernetes/sws.yaml
- deploy/openshift/sws-configmap.yaml
- deploy/openshift/sws.yaml
- fileserver/fileserver.go
- sws.go
see https://issues.jboss.org/browse/SWS-77
and https://issues.jboss.org/browse/SWS-89
> serve static content over http(s)

- server/server.go
Gofmt throw errors only in this file @jmazzitelli
> gofmt format files with errors

- .travis.yml
- Makefile
- hack/hooks/pre-commit
Adding the format task to Makefile to fix the format
Related with [Jira SWS-66](https://issues.jboss.org/browse/SWS-66)
> SWS-66 feat(Makefile, Travis): Add format task, Add Style task in Travis

- .travis.yml
- Makefile
don't use -s option.
the change in the Makefile is trivial - just stop it from echo'ing the comment during the format
> do NOT assume code is simplified when gofmt'ed

- config/config.go
- config/config_test.go
- config/security/config_security.go
- prometheus/client.go
- routing/router.go
- server/server.go
- server/server_test.go
- sws.go
Using struct tags to define the yaml mappings
More info: https://github.com/swift-sunshine/swscore/pull/30#discussion_r168771530
> Refactors config structures to follow golang conventions

- Makefile
- README.adoc
- hack/check_go_version.sh
This test in build that at least you have the go version of travis
> Make task for check go version

- .travis.yml
Show in trravis the erros of gofmt.
cc @xeviknal Here is the improve ^^
> feat(travis): add show errors if gofmt fail

- .gitignore
- hack/env-openshift.sh
So that we can change those variables without having to remove the change from every commit.
> Add support to have a local env-openshift.sh

- hack/istio-bookinfo-openshift.sh
- hack/istio-install-openshift.sh
the set -e was in the wrong place - "please log in" message never appears
> fix bug in install script - don't set -e at the top

- hack/istio-install-openshift.sh
Adding the permission that was missing in order to make Prometheus running with istio 0.5.1
> Adding Prometheus Policy to run on Istio 0.5.1

- handlers/base.go
- respond with an error if the jspn parsing fails
- add util func for returning formatted json
> JSON util enhancements

- README.adoc
PR #53 added a new config - this documents it. Also documenting the other config prop that was added a while ago.
> add the new configs

- hack/cluster-openshift.sh
- hack/env-openshift.sh
@abonas a gift just for you :)
> cluster script now supports (and is the default) persisting data across OS restarts

- hack/istio/kubernetes/istio-bookinfo-kubernetes.sh
- hack/istio/openshift/istio-bookinfo-openshift.sh
minor tweek so we can install bookinfo demo to any project, not just istio-system.
FWIW, these scripts are to be considered temporary (though helpful at the moment). Eventually we will probably want to be using the ansible installer: https://github.com/istio/istio/tree/master/install/ansible
> be able to deploy bookdemo in the project that oc is currently using

- handlers/services.go
- models/address.go
- models/endpoint.go
- models/pod.go
- models/port.go
- models/route_rules.go
- models/service.go
- routing/routes.go
Here the Service Details endpoint ([SWS-67](https://issues.jboss.org/browse/SWS-67)).
- It is built under path: `"/api/namespaces/{namespace}/services/{service}"`
- It shows for each service the data specified in [SWS-68](https://issues.jboss.org/browse/SWS-68?focusedCommentId=13530601&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13530601). Here you have an example:
Tests are going to be implemented in an upcoming PR. This way, I unlock de @aljesusg work with the UI side.
> [SWS-67] - Service details Endpoint

- models/pod.go
Just fixing a JSON key. Lowercasing it, from Name to name.
This is a change that @aljesusg needs to finish his work :+1:
> SWS-67 Pods json name label lowercased

- prometheus/client.go
- prometheus/client_test.go
@jotak please review
I'm not sure if this is a reasonable approach but I wanted to be able to mock Prometheus queries when testing my graph package; see https://github.com/swift-sunshine/swscore/pull/74 which I've labeled DNM until we discuss this PR.
Let me know what you think, thanks.
> Related SWS-163: Allow public injection of mock API

- handlers/graph.go
- handlers/graph_test.go
- handlers/testdata/test_namespace_graph.expected
- handlers/testdata/test_service_graph.expected
This is pending the PR for a hook in client.go...
> SWS-163 Add unit test for graph generation

- handlers/graph.go
- handlers/graph_test.go
- Fix issue, unknown source service ("") didn't constrain results to a namespace
> SWS-188 Namespace leakage in service graph

- Makefile
@pilhuhn just for you. Though I think this is a day too late for you :)
> for Mac OS users - make sure envsubst exists

- config.yaml
Note that this file is just an example and is not used with deployment scripts
> Add information/comments in config.yaml example

- handlers/root.go
- routing/routes.go
- status/status.go
- sws.go
- Add /api/status endpoint to return map of server-side status info
- Let /api return the same info
- removed temporary "demo" info from root handler as swsui now provides
the information
> SWS-227 Add status endpoint

- graph/options/options.go
- handlers/testdata/test_namespace_graph.expected
- handlers/testdata/test_service_graph.expected
This should not have been changed as part of a prior PR.
> reinstate groupByVersion

- deploy/openshift/sws.yaml
- kubernetes/kubernetes_service.go
- kubernetes/types.go
- models/autoscalers.go
- models/service.go
- models/service_test.go
Adding autoscalers list into Service Detail endpoint
> SWS-282: Adding autoscalers into service details endpoint

- handlers/services.go
- handlers/services_test.go
- prometheus/client.go
- prometheus/client_test.go
- prometheus/metrics.go
- routing/routes.go
Also remove health from previous Metrics object
Add some missing doc to metrics endpoint
> SWS-285 Create new health endpoint (per service)

- README.adoc
- hack/istio/README.adoc
Both readmes from root and from hack folder updated.
The istio upgrade is done to 0.7.1 since [0.7.0 was buggy](https://github.com/istio/istio/releases/tag/0.7.0).
> Kiali requires istio 0.7.1+ version

- hack/istio/README.adoc
- hack/istio/istio-install.sh
This PR adds the dependencies required to run the ansible scripts, and also adds a Troubleshooting section to cover some problems that might occur during installation.
> Improve Istio hack script documentation

- README.adoc
Also made the default verbage consistent across all rows -- now indicates default values with "(default is `<value>`)"
> remove that erroneous third column in IN_CLUSTER row

- graph/appender/circuit_breaker.go
- graph/appender/unused_service.go
- graph/cytoscape/cytoscape.go
- handlers/graph.go
- handlers/testdata/test_namespace_graph.expected
- handlers/testdata/test_service_graph.expected
Part 1: add new fields to json better suited to allowing ui-side presentation decisions
Part 2: (pending UI update) will remove obsalete fields from json
> KIALI-582	Remove presentation concerns from graph json

- graph/appender/circuit_breaker.go
- graph/appender/unused_service.go
- graph/appender/unused_service_test.go
- graph/cytoscape/cytoscape.go
- graph/options/options.go
- handlers/graph.go
- handlers/testdata/test_namespace_graph.expected
- handlers/testdata/test_service_graph.expected
This is part 2, where we remove the legacy fields from the json
> KIALI-582 (part 2) remove presentation concerns from graph json

- graph/cytoscape/cytoscape.go
- handlers/testdata/test_namespace_graph.expected
- handlers/testdata/test_service_graph.expected
part2 - remove obsolete json fields now that UI is updated
> KIALI-595 limit service count in graph summary to services in namespace

- kubernetes/client_test.go
need to check all possibilities.
travis has been randomly failing on this test because of this
> go does not guarantee any order when using range over a map - fix test

- hack/istio/istio-install.sh
* Download istio.zip instead of cloning
* Only do a shallow clone of Ansible to fetch a lot less data
> KIALI-617: Speed up Istio install

- services/models/destination_policy.go
- services/models/destination_rule.go
- services/models/istio_rule.go
- services/models/route_rule.go
- services/models/virtual_service.go
Per comment https://github.com/kiali/kiali/pull/181#issuecomment-385414951 there was a discussion to include null values on yaml editors-
> Revert KIALI-629 Do not bring unnecessary null values on Istio Objects

- kubernetes/kubernetes_service.go
- kubernetes/types.go
- services/models/service_test.go
This is only gathering data, but not yet exposing it in the JSON
returned for the API consumers.
> KIALI-683: Gather pod data for a service

- graph/appender/dead_service_test.go
- graph/appender/latency.go
- graph/appender/latency_test.go
- graph/cytoscape/cytoscape.go
- graph/options/options.go
- handlers/graph.go
@josejulio , the PR is set to do not merge because it has no tests, but it is OK to start reviewing.  If you'd like we can go through it together in more detail, as a learning experience for this sort of back-end code.
> KIALI-677 Add latency to graph

- prometheus/metrics.go
- prometheus/prometheustest/client_test.go
- make it like metric data, saves space, better for presentation
- helpful to kiala-447
> Round datapoint values for histograms

- graph/appender/dead_service.go
- graph/appender/dead_service_test.go
- graph/appender/sidecars_check.go
- kubernetes/client.go
- kubernetes/client_test.go
- kubernetes/kubernetes_service.go
- kubernetes/kubetest/mock.go
- kubernetes/types.go
- services/business/health.go
- services/business/istio_validations.go
- services/business/services.go
- services/business/services_test.go
Also replace our home-made label matching functions with the ones provided by the k8s client
> KIALI-725 Fetch deployments by matching pod labels

- graph/cytoscape/cytoscape.go
- graph/options/options.go
This is the necessary server-side change.  There will also be a ui-side follow-on.
> KIALI-744 badge orphan services

- services/models/autoscalers.go
- services/models/deployment.go
- services/models/destination_policy.go
- services/models/destination_rule.go
- services/models/pod.go
- services/models/route_rule.go
- services/models/service.go
- services/models/service_test.go
- services/models/util.go
- services/models/virtual_service.go
+ have a single point to describe time formatting in model
> KIALI-766 Add pod information to model

- graph/appender/dead_service.go
- graph/appender/dead_service_test.go
- graph/appender/istio_details.go
- graph/appender/latency.go
- graph/appender/sidecars_check.go
- graph/appender/unused_service.go
- graph/cytoscape/cytoscape.go
- graph/options/options.go
- handlers/graph.go
- handlers/graph_test.go
- handlers/testdata/test_overview_graph.expected
- kubernetes/client.go
- kubernetes/kubetest/mock.go
- routing/routes.go
@jmazzitelli, note that there is some stuff in here that is outside the scope of kiali-781, specifically the stuff related to the Overview graph, that's really for kiali-756 and the "traffic light" stuff.  But it's here because I thought there would be more overlap.  And then there sort of wasn't.  But I don't really want to take it out because 756 is also in progress.
@cfcosta , I ask mazz to review because he is interested but if you have comments feel free to add.
> [KIALI-781] Multiple/All namespace support

- README.adoc
- STYLE_GUIDE.adoc
Initial Style Code Guide, we'll update this
> [KIALI-599] Init Style Code Guide

- Makefile
This just fixes up some issues with the Makefile. Before the version label value wasn't the actual version, we were converting it to all lowercase, for example, when we didn't need to. We just have to make sure the resource names follow the more strict syntax.
> KIALI-877 Makefile need to be able to build releases with proper version label and name suffixes

- Makefile
bump up to next snapshot version
> next snapshot release

- kubernetes/client.go
- kubernetes/client_test.go
- kubernetes/kubernetes_service.go
- kubernetes/types.go
- services/business/services.go
- services/models/pod.go
- services/models/service_test.go
Also improve error messages for faster debugging while tracking an error
> KIALI-864 Fix fetching pods with empty selector

- graph/appender/health.go
- graph/appender/sidecars_check.go
- graph/cytoscape/cytoscape.go
- graph/options/options.go
- handlers/graph.go
- add health info to overview services
- fix bug in missing sidecar check
This is required to support the kiali-ui work for kiali-756.
> KIALI-756 Overview graph generator

- README.adoc
- config.yaml
- config/config.go
- graph/appender/unused_service.go
- handlers/grafana.go
- handlers/grafana_test.go
- handlers/jaeger.go
- handlers/jaeger_test.go
- prometheus/client.go
- prometheus/metrics.go
- prometheus/prometheustest/client_test.go
- services/business/services.go
- status/status.go
- status/versions.go
```json
{
"status": {
"Kiali console version": "0.2.10-SNAPSHOT.1213",
"Kiali core commit hash": "91d178374fa13f6ff932d9a04bd94bf19f62eb02",
"Kiali core version": "0.3.2.Alpha-SNAPSHOT",
"Kiali state": "running"
},
"externalServices": [
{
"name": "Istio",
"version": "0.7.1"
},
{
"name": "Prometheus",
"version": "2.0.0"
},
{
"name": "Kubernetes",
"version": "v1.7.6+a08f5eeb62"
}
],
"warningMessages": []
}
```
> Fix Change products by components

- hack/README.adoc
- hack/cluster-openshift.sh
- hack/env-openshift.sh
The default is still 0.8.0 but we need to be able to switch back to 0.7.1 which kiali is more stable on right now.
> support being able to switch back to Istio 0.7.1 plus add kiali

- kubernetes/istio_details_service.go
- kubernetes/istio_details_service_test.go
> Revert "Kiali 893 DestinatioRule is using host field"

- services/models/pod.go
- services/models/pod_test.go
It was deprecated and replaced with "OwnerReferences"
Supersedes https://github.com/kiali/kiali/pull/259
> KIALI-918 Fix pod's "created by" field absent in recent k8s API

- services/business/checkers/pod_checker_test.go
- services/business/checkers/pods/sidecar_presence_checker.go
This is a fix to use the same way for detecting sidecars across all logic.
> KIALI-914 Fix sidecars detection from checkers

- Makefile
- deploy/kubernetes/kiali-configmap.yaml
- deploy/kubernetes/kiali.yaml
- deploy/openshift/kiali-configmap.yaml
- deploy/openshift/kiali.yaml
This is built on top of PR #275.
If we merge this PR, we can just close #275.
> Remove the Makefile's ability to install multiple Kiali deployments in one namespace

- README.adoc
- config/config.go
Set istio 8.0 in configuration and Readme
> Move config and Readme to Istio 8.0

- hack/istio/README.adoc
- hack/istio/download-istio.sh
- hack/istio/install-bookinfo-demo.sh
- handlers/metrics.go
- handlers/metrics_test.go
This is a result of fetch latest master and istio-0.8 branches; merge istio-0.8 and master and PR on istio-0.8.
Please @jotak review if this is correct.
Thanks.
> Update istio 0.8

- handlers/namespaces.go
- handlers/namespaces_test.go
- routing/routes.go
- services/business/health.go
- services/business/services.go
Some refactoring to share code with ServiceList health fetching (which also relies on namespace)
Also add tests for namespace metrics handler
> KIALI-911 New endpoint for namespace health

- Makefile
Once in master, this will be tagged as our "v0.4.0" image.
> set version - this now supports istio 0.8.0

- hack/cluster-openshift.sh
this new instiooc installs kiali v0.4.0 as its default kiali version
> KIALI-1040 use latest istiooc

- handlers/services.go
- services/business/services.go
- services/business/services_test.go
- services/models/service.go
This is now done asynchronously from front-end.
Remove related field in model & update tests
Needs https://github.com/kiali/kiali-ui/pull/466
> KIALI-1047 Do not fetch health while querying services list

- deploy/kubernetes/kiali.yaml
- deploy/openshift/kiali.yaml
This field is causing problems on Istio Helm.
See more on https://github.com/istio/istio/issues/6583 and https://github.com/istio/istio/pull/6594#pullrequestreview-131827121
> [KIALI-1055] Remove attributeRestrictions: null from Kiali Templates

- prometheus/metrics.go
- prometheus/prometheustest/client_test.go
Also simplify character strings escaping with backticks
> KIALI-1093 exclude istio connections from health error rate reports

- services/business/checkers/virtual_service_checker.go
JIRA: [KIALI-1081](https://issues.jboss.org/browse/KIALI-1081)
I have done a little benchmark and the concurrent version had better performance over the sequential one. Benchmark aimed to discard over-concurrency.
> KIALI-1081 Add concurrence for each virtual service validation

- services/business/checkers/no_service_checker.go
- services/business/checkers/virtual_service_checker.go
Remove WaitGroups where channels are used anyway. Number of items to receive from channels are known, so we don't need any subterfuge to close them.
> Simplify checkers concurrency

- DEMOS.adoc
- README.adoc
See https://github.com/jotak/swscore/blob/list-demos/DEMOS.adoc
@lucasponce , I guess it only partly respond to your request, I'm not introducing any new hack script here. If there are some one-line commands to get a demo up & running we can show it here as well, but at the moment they're more like step-by-step tutorials.
@vnugent I'm listing here your Petsiogram it is fine with you?
> Add a list of mesh examples

- hack/README.adoc
- hack/cluster-openshift.sh
this version of istiooc pulls in kiali v0.5.0 by default
> hack script to use new istiooc

- hack/cluster-openshift.sh
This allows you to install a OpenShift cluster without Istio so you can install your own Istio later.
This is useful if you want an easy way to install an OpenShift cluster using this script but need to test with a new Istio version that is not yet supported by istiooc.
> Be able to tell istiooc not to install Istio.

- status/versions.go
> KIALI-1169 show unrecognized istio versions

- graph/appender/dead_service.go
- graph/appender/health.go
- graph/appender/istio_details.go
- graph/appender/response_time.go
- graph/appender/sidecars_check.go
- graph/appender/unused_service.go
- graph/cytoscape/cytoscape.go
- graph/graph.go
- graph/options/options.go
- graph/vizceral/vizceral.go
- handlers/graph.go
- handlers/graph_test.go
- handlers/testdata/test_multi_namespace_graph.expected
- handlers/testdata/test_namespace_graph.expected
This gets the graph to generate using the 1.0 istio metrics.
** It does not yet handle the appenders **
The appenders compile but getting them working will be follow-up PRs.
Also, the Service graph endpoint is not functional (although it's not used)
> KIALI-1127 [1.0] Update Graph

- handlers/namespaces_test.go
- handlers/services_test.go
- prometheus/client.go
- prometheus/metrics.go
- prometheus/prometheustest/client_test.go
- prometheus/prometheustest/mock.go
- services/business/health.go
- services/business/services.go
- services/business/services_test.go
- services/models/service.go
- services/models/service_test.go
Note, for source services (dependencies), this part will most probably have to be refactored due to the introduction of workloads (so this is temporary).
Tests updated
The goal here is to have something "working" with istio 1.0, even if it doesn't have the final shape we plan to have. So, just a step.
> KIALI-1181 Update prom queries for error rate & service deps

- hack/cluster-openshift.sh
- hack/istio/download-istio.sh
- hack/istio/install-bookinfo-demo.sh
I installed istio 1.0 on my box and updated these files to make it easier to up/down.
> Update hack scripts to use istio 1.0.0-snapshot.1

- hack/istio/playbooks/README.adoc
- hack/istio/playbooks/bookinfo.yml
- hack/istio/playbooks/files/traffic-generator-configmap.yml
- hack/istio/playbooks/files/traffic-generator-deployment.yml
- Also including Traffic Generator with Openshift Route and Istio Ingress Route
It is the same pull request #379, just rebasing to istio-1.0
Best Regards,
> [KIALI-967] Updating Bookinfo to Istio 1.0

- hack/istio/bookinfo-rename/bookinfo-gateway-rename.yaml
- hack/istio/bookinfo-rename/bookinfo-rename.yaml
- hack/istio/download-istio.sh
- hack/istio/install-bookinfo-demo.sh
run: 
```
install-bookinfo-demo.sh -b bookinfo-rename/bookinfo-rename.yaml -g bookinfo-rename/bookinfo-gateway-rename.yaml
```
> bookinfo: rename the app so not the same as service name

- hack/istio/playbooks/bookinfo.yml
Another Minor detail on the playbook that will not work ansible 2.5
Best Regards,
> [ḰIALI-967] Modifying to use openshift_raw instead of k8s

- handlers/workloads.go
- handlers/workloads_test.go
- routing/routes.go
> KIALI-1261 Adds Get metrics by workload (WorkloadMetrics)

- hack/istio/playbooks/README.adoc
- hack/istio/playbooks/bookinfo.yml
- Added bookinfo namespace (`bookinfo_namespace=namespace`)
- Added renamed option in order to deploy custom app labels (`renamed=true`)
Best Regards, 
> [KIALI-1268] Bookinfo demo with different app labels and namespace

- hack/istio/download-istio.sh
now that istio 1.0.0 is released, our download script can pull it.
> download hack script can now pull in istio release

- graph/appender/dead_node_test.go
- graph/appender/response_time_test.go
- graph/appender/unused_node_test.go
- handlers/testdata/test_multi_namespace_graph.expected
- handlers/testdata/test_namespace_graph.expected
This fixes test failures introduced by a premature merge of the kiali-1281 changes
> KIALI-1281 Fix tests

- README.adoc
- services/models/pod.go
- services/models/pod_test.go
> Update README with recent config changes

- hack/istio/bookinfo-reviews-all-cb.yaml
this yaml creates a circuit breaker on a host with no specified subset.
> add hack script so devs can quickly test with circuit breakers on all versions in an app

- README.adoc
> Fixes README: broken img link and update istio version

- README.adoc
Missing 1.0 reference in README
> Bump to Istio 1.0 in README.doc

- graph/appender/appender.go
- graph/appender/response_time.go
- graph/appender/response_time_test.go
- graph/appender/security_policy.go
- graph/appender/security_policy_test.go
- graph/appender/util.go
- graph/appender/util_test.go
- graph/graph.go
- graph/options/options.go
- handlers/graph.go
- handlers/graph_test.go
- handlers/testdata/test_namespace_graph.expected
- add new SecurityPolicyAppender
- add tests for new appender
Also:
- move some shared package-private util code to util.go and util_test.go
- use one consistent time format across graphing (TF)
> KIALI-1320 [1.0] add new support for mTLS detection

- services/business/checkers/pod_checker.go
- services/business/checkers/virtual_service_checker.go
- services/business/checkers/virtual_services/no_host_checker.go
This is for pre-release
https://issues.jboss.org/browse/KIALI-1322
> KIALI-1322 Fix unexpected null arrays in istio validation json

- handlers/workloads.go
- handlers/workloads_test.go
- kubernetes/client.go
- kubernetes/kubernetes_service.go
- kubernetes/kubetest/mock.go
- services/business/services.go
- services/business/workloads.go
- services/business/workloads_test.go
- services/models/pod.go
- services/models/service.go
- services/models/workload.go
- swagger.json
[Kiali-1211](https://issues.jboss.org/browse/KIALI-1211)
> KIALI-1211 Add a new label validation at WorkloadList endpoint level, check labels and istioSidecar

- handlers/apps.go
- handlers/apps_test.go
- handlers/workloads_test.go
- prometheus/metrics.go
- routing/routes.go
- services/business/services.go
https://issues.jboss.org/browse/KIALI-1324
> KIALI-1324 Add AppMetrics handler & route

- Makefile
Add a help command to Makefile to help dev users to know each command.
```bash
~/.../kiali/kiali (improve_makefile *%)$ make help
Choose a command run in :
clean                    Clean ${GOPATH}/bin/kiali, ${GOPATH}/pkg/*, _output/docker and the kilai binary
clean-all                Runs `make clean` internally and remove the _output dir
git-init                 Set the hooks under ./git/hooks
go-check                 Check if the go version installed is supported by Kiali
build                    Runs `make go-check` internally and build Kiali binary
install                  Install missing dependencies. Runs `go install` internally
format                   Format all the files excluding vendor. Runs `gofmt` internally
build-test               Run tests and …
```
> Improve Makefile help for devs

- Makefile
> KIALI-1364 Prepare for the next version

- doc.go
- handlers/apps.go
- handlers/apps_test.go
- routing/routes.go
- services/business/apps.go
- services/business/apps_test.go
- services/business/layer.go
- services/business/workloads.go
- services/business/workloads_test.go
- services/models/app.go
- services/models/workload.go
https://issues.jboss.org/browse/KIALI-1239
No
> KIALI-1239 Add a new AppList endpoint

- deploy/kubernetes/kiali.yaml
- deploy/openshift/kiali.yaml
Include `imagePullPolicy: Always` on Deployment Templates
> KIALI-1373 Include ImagePullPolicy Always on Templates

- routing/routes.go
- services/business/apps.go
- services/models/app.go
In the GetAppList Endpoint we added the IstioFlag field, that was missing on the GetApp details.
https://issues.jboss.org/browse/KIALI-1395
> KIALI-1395 Add missing IstioFlag field in AppDetails Endpoint

- hack/cluster-openshift.sh
- hack/istio/install-bookinfo-demo.sh
This uses the latest istiooc - do not merge unless you can confirm this works. I tested on my box and it is working, but I would like others to try it, too.
Also adds `--mongo` and `--mysql` options to the bookinfo hack script in case you want to add those to your bookinfo install.
> hack script now uses the new istiooc - installs OS 3.10, Istio 1.0

- Makefile
- tests/e2e/README.md
- tests/e2e/assets/bookinfo-ratings-delay.yaml
- tests/e2e/assets/circuitbreaker.yaml
- tests/e2e/config/env.yaml
- tests/e2e/requirements.txt
- tests/e2e/setup.sh
- tests/e2e/tests/conftest.py
- tests/e2e/tests/test_kiali_endpoint.py
- tests/e2e/tests/test_kiali_graph_badges.py
- tests/e2e/utils/timeout.py
Adding E2E tests for testing Kiali integration with Istio.
> KIALI-1241 Kiali E2E Tests with Istio

- kubernetes/istio_details_service.go
- kubernetes/types.go
- services/business/checkers/no_service_checker.go
- services/business/checkers/no_service_checker_test.go
- services/business/checkers/virtual_services/no_gateway_checker.go
- services/business/checkers/virtual_services/no_gateway_checker_test.go
- services/business/istio_validations.go
- services/business/istio_validations_test.go
- services/models/service_test.go
If gateway is defined in VirtualService, validates that such Gateway also exists (by name)
> KIALI-1135 Check that VirtualService gateway exists

- hack/cluster-openshift.sh
this is needed when you want to install your own version of istio
> fix the hack script's ability to disable istio installation 

- tests/e2e/config/env.yaml
- tests/e2e/requirements.txt
- tests/e2e/tests/conftest.py
- tests/e2e/tests/test_kiali_endpoint.py
- tests/e2e/tests/test_kiali_graph_badges.py
- Updating End to End Tests to Suport SSL
- `KIALI-1468`
Best Regards,
cc @mattmahoneyrh
> [KIALI-1468] SSL on End to End Tests

- services/models/service.go
- services/models/service_test.go
https://issues.jboss.org/browse/KIALI-1480
Related frontend PR: https://github.com/kiali/kiali-ui/pull/647
> KIALI-1480 Provide workload name and namespace for service source deps

- .travis.yml
Get travis notification in IRC when status of a branch change.
https://issues.jboss.org/browse/KIALI-113
> KIALI-113 Add Bot for UI Build success/failure to IRC

- tests/e2e/README.md
- tests/e2e/requirements.txt
- tests/e2e/tests/conftest.py
- tests/e2e/tests/test_kiali_endpoint.py
- tests/e2e/tests/test_kiali_graph_badges.py
New End-Point and Graph Badge test cases. Also fix to README.
> Kiali 1468

- tests/e2e/README.md
- tests/e2e/tests/test_kiali_endpoint.py
- tests/e2e/utils/url_connection.py
Grafana and Jaeger URL Endpoint test cases.
> Kiali 1499

- graph/options/options.go
- handlers/graph.go
- routing/routes.go
- add support for app and workload node detail graphs
- add support for injecting service nodes into the graph
- add support for injectServiceNodes query param
> KIALI-959 Node-Detail graph

- services/business/checkers/destination_rules/multi_match_checker.go
- services/business/checkers/destination_rules/multi_match_checker_test.go
- services/business/checkers/destination_rules_checker.go
- services/business/checkers/virtual_service_checker.go
- services/business/checkers/virtual_service_checker_test.go
- services/business/checkers/virtual_services/no_gateway_checker.go
- services/business/istio_validations.go
Checks that only a single DestinationRule per host is created
> KIALI-1136 Add new GroupChecker for DestinationRules

- tests/e2e/tests/test_kiali_endpoint.py
- Disable Grafana URL check
- Disable Service Detail Sidecar check
> KIALI-1556 - Remove Grafana URL Connection validation

- handlers/graph.go
- services/business/services.go
commit 8e51f83ba8c0cf82b9cc28fbd6464d1d89bf9b58 broke the ``make test`` as the Sprintf has wrong number of parameters
> fmt.Sprintf is missing istioNamespace

- tests/e2e/requirements.txt
- tests/e2e/tests/conftest.py
- tests/e2e/tests/test_kiali_application_endpoint.py
- tests/e2e/tests/test_kiali_bookinfo_namespace_endpoint.py
- tests/e2e/tests/test_kiali_graph_badges.py
- tests/e2e/tests/test_kiali_istio_endpoint.py
- tests/e2e/tests/test_kiali_service_endpoint.py
- tests/e2e/tests/test_kiali_urls.py
- tests/e2e/tests/test_kiali_workload_endpoint.py
- Restructured test classes
- New test cases:
- Applications
- Workloads
- Istio
> KIALI-1532 - Added new test cases and restructured test classes

- hack/cluster-openshift.sh
istiooc took out support for kiali installations. Our hack script used that. Until istiooc adds support back in, this PR will do the kiali install manually.
> hack script: add back support for --kiali-enabled

- graph/appender/response_time.go
- graph/appender/util.go
- handlers/graph.go
- also remove some dead code and tweak some logging
> KIALI-1595 Run appropriate appenders on node graphs

- doc.go
- handlers/apps_test.go
- handlers/metrics.go
- handlers/namespaces_test.go
- handlers/services_test.go
- handlers/workloads_test.go
- prometheus/metrics.go
- prometheus/prometheustest/client_test.go
- swagger.json
JIRA: https://issues.jboss.org/browse/KIALI-936
Related frontend PR: https://github.com/kiali/kiali-ui/pull/701
yes: Changes in REST API, https://github.com/kiali/kiali-ui/pull/701 is necessary for no regression
> KIALI-936 Metrics queries can receive quantile parameters

- tests/e2e/tests/conftest.py
- tests/e2e/tests/test_kiali_graph_badges.py
- tests/e2e/tests/test_kiali_service_endpoint.py
Fixing failures of E2E tests.
https://issues.jboss.org/browse/KIALI-1627
Yes.
> KIALI-1627 Prevent failure when no virtual services presented

- Makefile
> KIALI-1657 Release 0.8.0

- Makefile
> KIALI-1656 Prepare for 0.9.0-SNAPSHOT

- hack/cluster-openshift.sh
don't rely on "oc" existing - we should not hardcode it in the hack script
> KIALI-1664 use the configured command

- kubernetes/client.go
The target of this change is to enable consumption of the IstioClient externally (in our case for `github.com/skydive-project/skydive/topology/probes/istio`), overall including:
- ability to create the client using external k8s configuration (by being handled a `rest.Config` object)
- exporting of the internal Istio APIs (Config and Networking) 
None
N/A
> kubernetes: client creation/usage external to kiali

- doc.go
- handlers/graph.go
- routing/routes.go
- swagger.json
- This also covers KIALI-1643 KIALI-1644 KIALI-1645 KIALI-1646
- Also, a few edits to existing text for clarity and consistency
> KIALI-1642 graph api swagger

- hack/istio/install-istio-via-helm.sh
hack script now supports `--use-demo` and `--use-demo-auth` to install Istio+Kiali just as if you used the Istio demo yaml files.
This also fixes a bug in the -p/-u options.
> be able to install Istio just as if you used the istio-demo[-auth].yaml

- graph/appender/response_time.go
- graph/options/options.go
- handlers/graph.go
- add response time support to service graph reducer
- also fixes a subtle bug in response time appender wrt service destinations
- rename a few methods for clarity
> KIALI-1707 Add service injection support to response time appender

- tests/e2e/tests/test_kiali_application_endpoint.py
- tests/e2e/tests/test_kiali_service_endpoint.py
- tests/e2e/tests/test_kiali_workload_endpoint.py
- tests/e2e/utils/command_exec.py
In addition to disabling failing tests temporarily, also quiet 'oc delete' error text.
> KIALI-1740 - Disable failing tests

- README.adoc
Adding a static screenshot instead of hot linking to an image on kiali.io
Kiali-1586
No
> Kiali-1586 add a screenshot of Kiali 

- business/checkers/virtual_services/route_checker.go
Since Istio 1.0, Galley is the engine in charge of perform validations to all the istio objects deployed to the cluster.
In this PR, validations that overlaps Galley ones are deleted.
The following errors are the one removed:
https://issues.jboss.org/browse/KIALI-1668
> KIALI-1668 Deprecate galley validations

- status/versions.go
- status/versions_test.go
see discussion in https://issues.jboss.org/browse/KIALI-1733 that describes what checks this is performing
> KIALI-1733 - check release branch snapshots in our version check

- business/istio_config.go
- business/istio_config_test.go
- kubernetes/client.go
- kubernetes/kubernetes_service.go
- kubernetes/kubetest/mock.go
- models/istio_config.go
Add permission information to the istio models.
This is Kiali permissions (SelfSubjectAccessReview), not user permissions.
Add some tests
JIRA: https://issues.jboss.org/browse/KIALI-1661
> KIALI-1661 Provide permissions on istio objects

- business/checkers/virtual_services/subset_presence_checker.go
- business/checkers/virtual_services/subset_presence_checker_test.go
Support TLS and TCP route subset validations. Before this PR, KIALI checks whether a subset is defined in the system or not. Only for [HTTPRoute](https://istio.io/docs/reference/config/istio.networking.v1alpha3/#HTTPRoute), missing [TLSRoute](https://istio.io/docs/reference/config/istio.networking.v1alpha3/#TLSRoute) and [TCPRoute](https://istio.io/docs/reference/config/istio.networking.v1alpha3/#TLSRoute).
https://issues.jboss.org/browse/KIALI-1739
** Screenshot **
> KIALI-1739 Support TLS and TCP route validation for VS

- status/status.go
- status/versions.go
- swagger.json
Provide jaeger and grfana URL in status
[KIALI-1587](https://issues.jboss.org/browse/KIALI-1587)
> KIALI-1587 Jaeger link tries to open popup

- .travis.yml
- Makefile
This control that the swagger.json is generated, valid and added
> Control that the swagger documentation is correct

- swagger.json
I've just regenerated the swagger.json with make swagger-gen command.
> Re-generate swagger.json to update doc

- business/istio_config.go
- business/istio_config_test.go
- kubernetes/client.go
- kubernetes/kubernetes_service.go
- kubernetes/kubetest/mock.go
- models/istio_config.go
- swagger.json
Fetch permissions only while looking for istio object details - not lists, as it heavily impacts performances
JIRA: https://issues.jboss.org/browse/KIALI-1661 and https://issues.jboss.org/browse/KIALI-1809
> KIALI-1661 Fetch Kiali permissions with Istio resources

- hack/istio/install-istio-via-helm.sh
this also sets the grafana/jaeger permissions when using a demo yaml
> [hack script] when deleting istio, no need to create permissions and secret

- business/istio_config.go
- business/istio_config_test.go
- deploy/kubernetes/kiali.yaml
- deploy/openshift/kiali.yaml
- graph/appender/dead_node.go
- handlers/istio_config.go
- kubernetes/client.go
- kubernetes/istio_details_service.go
- kubernetes/kubetest/mock.go
- routing/routes.go
Supersedes #533 
Thanks to @pilhuhn for the original PR
JIRA: https://issues.jboss.org/browse/KIALI-1650
> KIALI-1650 Delete Istio-config objects

- .gitignore
> Exclude .kiali-e2e from repo

- handlers/graph.go
- handlers/graph_test.go
The namespace graph:
DoubleClick ProductPage Service (triangle)...
Before:
After:
> KIALI-1825 Service focus graph should show traffic from unknown

- business/istio_config_test.go
- graph/appender/appender.go
- graph/appender/dead_node.go
- graph/appender/istio_details.go
- graph/appender/istio_details_test.go
- kubernetes/istio_details_service.go
- kubernetes/istio_details_service_test.go
- models/destination_rule.go
- models/virtual_service.go
- move some supporting logic/tests from istio_details to business
- remove some unused functions from istio_details_service
- CheckVirtualServiceSubset
- FilterByDestination
- add appender test file
> KIALI-1822 Migrate istio (badging) appender to business layer API

- graph/cytoscape/cytoscape.go
- handlers/testdata/test_app_graph.expected
- handlers/testdata/test_app_node_graph.expected
- handlers/testdata/test_complex_graph.expected
- handlers/testdata/test_service_graph.expected
- handlers/testdata/test_service_node_graph.expected
- handlers/testdata/test_versioned_app_graph.expected
- handlers/testdata/test_versioned_app_node_graph.expected
- handlers/testdata/test_workload_graph.expected
- handlers/testdata/test_workload_node_graph.expected
This seems to be working OK for me.  Maybe needs to be run for a while and sanity checked in various situations.
> KIALI-1609 Drop to 2 digits of precision in the graph JSON

- tests/e2e/tests/test_kiali_graph_badges.py
- tests/e2e/tests/test_kiali_reduced_permissions.py
- tests/e2e/utils/command_exec.py
> KIALI-1832 - Reduced permisstions

- business/istio_config.go
- business/istio_config_test.go
- business/istio_validations.go
- business/services.go
- graph/appender/istio_details.go
- handlers/istio_config.go
- models/destination_rule.go
- models/istio_config.go
- models/service.go
- models/service_test.go
- models/virtual_service.go
- swagger.json
Remove "create" flag, as it's unused at the moment and may have to be set differently
Also add constants for istio object types as they're used in more and more places
> KIALI-1821 Add resource permissions in DR and VS models

- handlers/config.go
- routing/routes.go
- swagger.json
- add new REST endpoint to provide certain server-side config
> KIALI-1831 Remove hard-coded istio-system namespace in UI

- hack/istio/install-istio-via-helm.sh
> hack - helm install script supports the ability to pull down a different kiali tag

- hack/istio/install-istio-via-helm.sh
this also removes a "exit" I left in before - a remnant of debugging that I forgot to remove
> if the user doesn't have helm installed, download a temporary copy

- hack/istio/playbooks/install_bookinfo.yml
when needed.
Allow to specify number of retries via parameter so we can fail faster when needed.
* If this is a fix for a JIRA, please put JIRA-reference in the PR title like _`KIALI-7 New icons`_ (Jira-id, one space, description)
* If this is a fix for a GH-issue, please link it here
yes
> Allow to specify number of retries via parameter so we can fail faster

- config/config.go
- config/config_test.go
> KIALI-1877 Do not exclude Default namespace in default config

- hack/istio/install-istio-kiali-via-helm.sh
upstream istio changed their helm repo again - this changes the hack script to use it. Also adds the option to tell hack script what repo to add in case we need to specify a different one.
> install the new helm repo

- tests/e2e/tests/conftest.py
- tests/e2e/tests/test_kiali_application_endpoint.py
- tests/e2e/tests/test_kiali_bookinfo_namespace_endpoint.py
- tests/e2e/tests/test_kiali_graph_badges.py
- tests/e2e/tests/test_kiali_reduced_permissions.py
Refactoring for Graph API changes
> Kiali 1869

- tests/e2e/tests/test_kiali_application_endpoint.py
- tests/e2e/tests/test_kiali_bookinfo_namespace_endpoint.py
- tests/e2e/tests/test_kiali_graph_badges.py
API Parms changes.
Debug info.
> KIALI-1845 - More Params - Debug info

- deploy/kubernetes/kiali.yaml
- deploy/openshift/kiali.yaml
This is going to make it easier when people change - we can diff them and see/make the changes easier
> reordering and alphabetizing yaml file values so they are easier to maintain

- business/istio_validations.go
Import missing validations from IstioConfig section to yaml in service details.
https://issues.jboss.org/browse/KIALI-1886
> KIALI-1886 Trigger NoServiceChecker validations for service details page

- business/istio_validations.go
Services validation was missing Gateways fetching so the virtualService gateway validation failed.
> KIALI-1968 Add missing fetch to service validations

- business/health.go
- models/health.go
(reuse "NewEmptyRequestHealth")
see also: PR https://github.com/kiali/kiali-ui/pull/834
> Bugfix: initialize namespace service health items with correct values

- tests/e2e/config/env.yaml
- tests/e2e/tests/conftest.py
- tests/e2e/tests/test_kiali_istio_clusterrole_binding.py
- Including E2E tests to validate Kiali Kubernetes Templates 
* _`KIALI-1931 E2E Tests`_
> [KIALI-1931] E2E Test Istio Cluster Role/Kubernetes

- tests/e2e/tests/test_kiali_service_endpoint.py
- tests/e2e/tests/test_kiali_workload_endpoint.py
Some timeouts jumped. Increasing them. Also adding some debug info in order to ease upcoming error fixing.
https://issues.jboss.org/browse/KIALI-1961
yep
> KIALI-1961 Increase timeouts and add some debug data for further research

- business/istio_validations_test.go
- business/layer.go
- business/workloads.go
- business/workloads_test.go
- kubernetes/kubetest/mock.go
- models/workload.go
- prometheus/client.go
- prometheus/prometheustest/client_test.go
- prometheus/prometheustest/mock.go
- swagger.json
> Revert "KIALI-1140 Add destination services for workload details endpoint"

- status/versions.go
Because of assignments like
`something, err := function(args)`
the `err` variable was being redeclared under and re-scoped. This was
leading to returning null values for both the result and the error. The
caller was, then, failing.
Solving by pre-declaring variables and avoiding the ":=" assignment.
https://issues.jboss.org/browse/KIALI-2046
> KIALI-2046 Fix variable shadowing issue

- business/istio_validations_test.go
- business/layer.go
- business/workloads.go
- business/workloads_test.go
- kubernetes/kubetest/mock.go
- models/workload.go
- prometheus/client.go
- prometheus/prometheustest/client_test.go
- prometheus/prometheustest/mock.go
- swagger.json
Continuing this reverted PR: https://github.com/kiali/kiali/pull/676
https://issues.jboss.org/browse/KIALI-1140
> KIALI-1140 Add destination services for workload details endpoint

- deploy/kubernetes/deploy-kiali-to-kubernetes.sh
- deploy/openshift/deploy-kiali-to-openshift.sh
These are the two installer scripts. Now that we have our latest release with the yaml files split out, we can use these.
> support installing the latest release as the default, but also support latest image from master

- handlers/grafana.go
- handlers/grafana_test.go
- Better handling of grafana errors & unmarshalling
- Propagate error message
- More tests
JIRA: https://issues.jboss.org/browse/KIALI-2048
> KIALI-2048 Don't panic on Grafana error

- doc.go
- graph/options/options.go
- swagger.json
- namespace graphs now require at least one explicitly specified, accessible namespace
Blocking PR: https://github.com/kiali/kiali-ui/pull/861
> KIALI-2073 Remove all-namespace support

- graph/options/options.go
- routing/routes.go
- swagger.json
@gbaufake This adds validation not only to graphType but for every graph API query param.
> KIALI-1980 Add validation to graph REST API params

- graph/appender/appender.go
- graph/appender/dead_node.go
- graph/appender/dead_node_test.go
- handlers/graph.go
- this actually managed to uncover a small issue in service graph reduction, now fixed
> KIALI-2081 Only show unknown node when it has traffic

- business/checkers/destinationrules/multi_match_checker.go
- business/checkers/gateways/multi_match_checker.go
Changes do to https://github.com/kiali/kiali.io/pull/76/files
It changes only couple of validations messages for sake of correctness :)
> KIALI-2085 Update validation messages to make it valid

- graph/appender/appender.go
- graph/appender/dead_node.go
- graph/appender/dead_node_test.go
- graph/appender/istio_details.go
- graph/appender/istio_details_test.go
- graph/appender/response_time_test.go
- graph/appender/security_policy_test.go
- graph/appender/service_entry_test.go
- graph/appender/sidecars_check_test.go
- graph/appender/unused_node.go
- graph/appender/unused_node_test.go
- graph/graph.go
- graph/util.go
- handlers/graph.go
- simplify by getting rid of the multiple "unknown" constants
> KIALI-2090 refactor: consolidate telem value validation to a method

- tests/e2e/config/env.yaml
- tests/e2e/requirements.txt
- tests/e2e/tests/conftest.py
- tests/e2e/tests/test_api_methods.py
- tests/e2e/tests/test_kiali_application_endpoint.py
- tests/e2e/tests/test_kiali_bookinfo_namespace_endpoint.py
- tests/e2e/tests/test_kiali_graph_badges.py
- tests/e2e/tests/test_kiali_istio_endpoint.py
- tests/e2e/tests/test_kiali_reduced_permissions.py
- tests/e2e/tests/test_kiali_service_endpoint.py
- tests/e2e/tests/test_kiali_urls.py
- tests/e2e/tests/test_kiali_workload_endpoint.py
- tests/e2e/utils/command_exec.py
- Refactor to support Kiali-Client redesign KIALI-1766.
- Updating with Kiali Client test (Updates from #702)
- 65 tests on total
> KIALI-2038 - Refactor to support redesigned Kiali-Client

- tests/e2e/requirements.txt
Python modules update for requirements.txt
> KIALI-2101 - python module updates

- hack/istio/install-bookinfo-demo.sh
- hack/k8s-minikube.sh
gwurl command plus it will tell you how to access bookinfo over this url.
the install bookinfo script now supports k8s for the traffic generator (before it only supported OS)
> k8s hack script and install-bookinfo script supports k8s gateways urls

- deploy/kubernetes/deploy-kiali-to-kubernetes.sh
> Fix missing crd yaml in k8s hack script

- RELEASING.adoc
- deploy/jenkins-ci/Jenkinsfile
- deploy/jenkins-ci/Makefile
- deploy/jenkins-ci/bin/determine-release-type.sh
https://issues.jboss.org/browse/KIALI-2040
> KIALI-2040 Support for snapshot releases through Jenkins Pipeline

- handlers/apps.go
- handlers/namespaces.go
- handlers/services.go
- handlers/utils.go
- handlers/workloads.go
- Type supplier-kind functions
- Group client initialization + namespace check in common function
(no functional change expected)
> Simplify code in metrics handlers

- tests/e2e/tests/test_kiali_application_endpoint.py
- tests/e2e/tests/test_kiali_service_endpoint.py
- tests/e2e/tests/test_kiali_workload_endpoint.py
> KIALI-2113 - Refactor Metrics Test Cases Due To KIALI-2086

- hack/k8s-minikube.sh
This now provides an option to get all known and available GW URLs in minikube:
Here's an example (note the new `all` option to the `gwurl` command):
```
$ ./k8s-minikube.sh gwurl all
Gateway URLs for all known ports are:
http2: 192.168.99.100:31380
https: 192.168.99.100:31390
tcp: 192.168.99.100:31400
http-kiali: 192.168.99.100:30718
http2-prometheus: 192.168.99.100:31222
http2-grafana: 192.168.99.100:30181
http2-tracing: 192.168.99.100:31058
tls: 192.168.99.100:32114
```
Here's the new help text related to this new option:
```
$ ./k8s-minikube.sh --help
./k8s-minikube.sh [option...] command
...
gwurl [<portName>|'all']:
displays the Ingress Gateway URL. If a port name is given, the gateway port is also shown.
If the port name is "all" then all the URLs for all known ports are shown.
``` …
> [Hack] k8s minikube script can now print all known and available gateway URLs

- graph/options/options.go
- graph/util.go
- handlers/graph.go
- also, only dump stack traces to the logs on 500 errors.
> KIALI-2098 Return BadRequest (400) as opposed to ApplicationError (500) for URL validation issues

- business/istio_config.go
Race condition here: when patch and update permissions are different, only the last that comes up is taken
> Fix inconsistent patch/update permissions reported

- tests/e2e/tests/test_api_methods.py
- Fixing istioConfigDetailsSubtype E2E test and GraphApp and GraphAppVersion E2E Tests
> [KIALI-2145] Updating istioConfigDetailsSubtype test and graphApp/graphAppVersion (Support for KIALI-1654 and KIALI-2098)

- RELEASING.adoc
- deploy/jenkins-ci/Jenkinsfile
- deploy/jenkins-ci/Makefile
https://issues.jboss.org/browse/KIALI-2039
> KIALI-2039 Support for patch releases through Jenkins Pipeline

- handlers/graph.go
- handlers/graph_test.go
- handlers/testdata/test_app_graph.expected
- handlers/testdata/test_service_graph.expected
- handlers/testdata/test_versioned_app_graph.expected
- handlers/testdata/test_workload_graph.expected
We were only aggregating 200 traffic.
- add test
> KIALI-2172 Fix error traffic aggregation in service graph reducer

- tests/e2e/tests/test_api_methods.py
Added positive api tests - serviceDashboard, workloadDashboard and appDashboard
Also added negative tests for 400, 404 and 500 responses.
> KIALI-2201 Added negative tests to kiali api

- hack/istio/install-rh-tutorial.sh
We can use this to test in addition to the bookinfo demo
> hack script to install the Red Hat tutorial.

- business/health.go
- business/health_test.go
- business/services.go
- handlers/health_test.go
- models/health.go
- prometheus/client.go
- prometheus/metrics.go
- prometheus/prometheustest/client_test.go
- prometheus/prometheustest/mock.go
- prometheus/types.go
- swagger.json
Also:
- provide better error reporting on health
- move some mocking functions to shared mock struct
JIRA: https://issues.jboss.org/browse/KIALI-2209
UI PR: https://github.com/kiali/kiali-ui/pull/913
> KIALI-2209 Remove Envoy health

- business/dashboards.go
JIRA: https://issues.jboss.org/browse/KIALI-2230
Note: frontend PR is also part of the work to reduce height size, but can be merged independently: https://github.com/kiali/kiali-ui/pull/931
> KIALI-2230 Displays metrics on 2 columns

- business/dashboards.go
JIRA: https://issues.jboss.org/browse/KIALI-2179
That cache wasn't anyway so useful as dashboards are anyway displayed one by one, so not a great overhead.
> KIALI-2179 remove dashboards cache

- business/istio_config.go
- business/istio_config_test.go
- doc.go
- handlers/istio_config.go
- kubernetes/client.go
- kubernetes/istio_details_service.go
- kubernetes/kubetest/mock.go
- routing/routes.go
- swagger.json
Allows to create new Istio Objects through Kiali's backend (for UI's purposes)
KIALI-2034
WIP: Requires testing (.. how is the question ..)
> KIALI-2034 Add POST endpoints to create new IstioObjects

- Makefile
- deploy/kubernetes/deploy-kiali-to-kubernetes.sh
- deploy/openshift/deploy-kiali-to-openshift.sh
Do this for both k8s and os install scripts.
As part of this JIRA task, I will also add some docs to our kiali.io gettingstarted page. That will be in another PR.
> KIALI-2294 By default, ask for credentials via prompt, and add docs to script

- deploy/kubernetes/clusterrole.yaml
- deploy/openshift/clusterrole.yaml
see https://github.com/istio/istio/pull/11234 go in (there is another PR against istio master, too)
This was due to this issue: https://github.com/istio/istio/issues/10883
> KIALI-2331 - re-organize cluster roles.

- README.adoc
- config/authentication.go
- config/config.go
- config/token.go
- handlers/istio_config.go
This PR adds additional logging tagged with "AUDIT" for easy filtering by external logging processors (thinking on EFK systems).
It adds traces on Write operations.
https://issues.jboss.org/browse/KIALI-1711
> KIALI-1711 Audit config changes

- business/istio_config.go
- handlers/istio_config.go
- handlers/istio_config_test.go
- kubernetes/client.go
- kubernetes/istio_details_service.go
- kubernetes/kubetest/mock.go
- models/istio_config.go
- models/mesh_policy.go
- swagger.json
MeshPolicies are now listed and detailed into Istio Config section.
UI changes in here: https://github.com/kiali/kiali-ui/pull/986
https://issues.jboss.org/browse/KIALI-2311
yes
> KIALI-2311 Show MeshPolicies into IstioConfig section

- handlers/config.go
- prometheus/client.go
- prometheus/prometheustest/client_test.go
- prometheus/prometheustest/mock.go
- Add GetConfiguration and GetFlags to the Prometheus client
- Add prom scrapeInterval and retention info to PublicConfig
> KIALI-2359 Add Prometheus configuration to the Kiali public config

- deploy/dashboards/thorntail.yaml
JIRA https://issues.jboss.org/browse/KIALI-2349
> KIALI-2349 Thorntail dashboard

- business/istio_config.go
- business/istio_config_test.go
Don't show 'mesh-wide mTLS partially enabled' when user has a mesh policy with mTLS in `permissive` mode (and there is any mesh-wide DR enabling mTLS)
https://issues.jboss.org/browse/KIALI-2375
yes
> KIALI-2375 mTLS padlock considers PERMISSIVE meshpolicies

- business/dashboards.go
- business/dashboards_test.go
For app-based dashboards, automatically add a possible aggregation/grouping over versions
JIRA: https://issues.jboss.org/browse/KIALI-2387
Screenshot:
> KIALI-2387 Custom dashboards: add grouping over version

- graph/protocol.go
- handlers/graph.go
- handlers/graph_test.go
- handlers/testdata/test_app_graph.expected
- handlers/testdata/test_service_graph.expected
- handlers/testdata/test_versioned_app_graph.expected
- handlers/testdata/test_workload_graph.expected
Terminate paths that are not service request paths.
> KIALI-2412 Handle workload-to-workload edges in service graph generation

- business/health.go
- business/health_test.go
- business/test_util.go
- handlers/health_test.go
- kubernetes/kubetest/mock.go
Avoid fetching health from istio metrics when there's no sidecar
This is a side perf improvement related to https://issues.jboss.org/browse/KIALI-1469
> KIALI-1469 Performance improvement on health fetching

- deploy/kubernetes/deploy-kiali-to-kubernetes.sh
- deploy/openshift/deploy-kiali-to-openshift.sh
> KIALI-2447 log error message if github api fails

- Makefile
- business/layer.go
- business/openshift_oauth.go
- config/config.go
- config/token.go
- deploy/kubernetes/deploy-kiali-to-kubernetes.sh
- deploy/openshift/clusterrole.yaml
- deploy/openshift/configmap.yaml
- deploy/openshift/deploy-kiali-to-openshift.sh
- deploy/openshift/oauth.yaml
- doc.go
- handlers/authentication.go
- handlers/oauth.go
- handlers/root.go
- routing/router.go
- routing/routes.go
- server/server_test.go
- swagger.json
Check https://github.com/kiali/kiali-ui/pull/906 for information, there's a write-up there.
> KIALI-1185 Implement Openshift OAuth support

- deploy/kubernetes/deploy-kiali-to-kubernetes.sh
Fixing https://github.com/kiali/kiali/pull/768#pullrequestreview-207812739 and https://github.com/kiali/kiali/pull/768#pullrequestreview-207814269
> Hotfix deploy to kubernetes script

- deploy/kubernetes/deploy-kiali-to-kubernetes.sh
- deploy/openshift/deploy-kiali-to-openshift.sh
JIRA: https://issues.jboss.org/browse/KIALI-2421
> KIALI-2421 deploy dashboards with our public-facing install scripts

- models/workload.go
- models/workload_test.go
It seems Status.Replicas may not be equal to Spec.Replicas which is the "desired" replicas field.
> KIALI-2473 Use Spec.Replicas instead of Status.Replicas

- business/dashboards.go
- deploy/dashboards/generic-go.yaml
- deploy/dashboards/kiali.yaml
- deploy/dashboards/nodejs.yaml
- deploy/dashboards/springboot-jvm.yaml
- deploy/dashboards/springboot-tomcat.yaml
- deploy/dashboards/thorntail.yaml
- deploy/dashboards/vertx-client.yaml
- deploy/dashboards/vertx-eventbus.yaml
- deploy/dashboards/vertx-pool.yaml
- deploy/dashboards/vertx-server.yaml
- kubernetes/kiali_monitoring_types.go
JIRA: https://issues.jboss.org/browse/KIALI-2481
Related frontend PR : https://github.com/kiali/kiali-ui/pull/1030
> KIALI-2481 dashboards: move runtime definition from labels to spec

- business/health.go
- business/health_test.go
- business/services_test.go
- handlers/health_test.go
- kubernetes/kubetest/mock.go
We need to load all services prior to fetching their health.
JIRA: https://issues.jboss.org/browse/KIALI-2487
> KIALI-2487 fix services number inconsistency

- README.adoc
- config/config.go
- config/config_test.go
- config/security/config_security.go
- handlers/authentication.go
- kiali.go
- server/server.go
- server/server_test.go
Remove the allow-anonymous flag for the login strategy
https://issues.jboss.org/projects/KIALI/issues/KIALI-2503
> KIALI-2503 implement anonymous mode with the auth.strategy setting only

- models/pod.go
JIRA https://issues.jboss.org/browse/KIALI-2519
> KIALI-2519 trim space on each runtime name

- README.adoc
- config/config.go
- deploy/dashboards/all.yaml
- deploy/kubernetes/deployment.yaml
- deploy/openshift/deployment.yaml
- routing/router.go
- server/metrics_server.go
- server/server.go
- server/server_test.go
For Kiali self-monitoring: https://issues.jboss.org/browse/KIALI-2340
> KIALI-2340 Get kiali metrics into prometheus

- server/metrics_server.go
Fix typo that can cause the tests to fail.
https://issues.jboss.org/browse/KIALI-2539
> KIALI-2539 Fix missing f on log output

- deploy/dashboards/dashboards.txt
- deploy/dashboards/quarkus.yaml
Provide an initial dashboard for Quarkus
> Add initial Quarkus dashboard

- hack/cluster-openshift.sh
@burmanm just making sure this wasn't done on purpose :) We don't need this if-stmt in here twice, correct?
> no idea how we got duplicate code in here - removing

- business/checkers/authorization/service_binding_checker.go
- business/checkers/authorization/service_binding_checker_test.go
- business/checkers/authorization/service_checker.go
- business/checkers/authorization/service_checker_test.go
- business/checkers/no_service_checker.go
- business/checkers/no_service_checker_test.go
- business/checkers/service_role_bind_checker.go
- business/istio_validations.go
- business/istio_validations_test.go
- kubernetes/client.go
- kubernetes/istio_details_service.go
- kubernetes/kubetest/mock.go
- kubernetes/types.go
- models/istio_validation.go
- tests/data/service_role_data.go
This PR adds validations for ServiceRole / ServiceRoleBindings
KIALI-2392
Requires kiali-ui PR #1057 for results to be visible
Requires updates to the kiali.io docs as this generates two new error messages
> KIALI-2392 Add validation for authorization configs

- tests/e2e/tests/conftest.py
Console Role tests refactored to support clusterrole.yaml changes.
> KIALI-2603 - Fix Console-Role Tests

- hack/istio/install-istio-kiali-via-helm.sh
To install 1.0, get a version of this script from the v0.16 branch
> [Hack] install script now works with 1.1.

- prometheus/metrics.go
make a available length slice to store results of fetching metrics
> make results length available when fetchAllMetrics

- business/checkers/checker.go
- business/checkers/destination_rules_checker.go
- business/checkers/gateway_checker.go
- business/checkers/mesh_policies_checker.go
- business/checkers/no_service_checker.go
- business/checkers/policies_checker.go
- business/checkers/service_entry_checker.go
- business/checkers/virtual_service_checker.go
This refactors the validation results to remove repetition.
Yes.
> KIALI-2642 Refactor the validations to remove repetition

- models/quota_spec_binding.go
- models/service_role_binding.go
- swagger.json
Fix missing fields in Istio config mapping.
https://issues.jboss.org/browse/KIALI-2658
> KIALI-2658 Fix missing kind in *Binding Istio CRDs

- Makefile
fix the help make target - the comments need to have colon (:) for the help to format.
Also, there is no PROJECTNAME in our makefile, so remove that.
> trivial fix to makefile

- business/workloads_test.go
Looks like there was an issue merging PRs,
> Fix merge issue

- operator/deploy/deploy-kiali-operator.sh
cc @gbaufake 
Just set "OPERATOR_SKIP_WAIT=true" when running this script and it won't wait. e.g.
```
OPERATOR_SKIP_WAIT=true ./deploy-kiali-operator.sh
```
> be able to tell the op deploy script not to wait

- operator/deploy/deploy-kiali-operator.sh
> operator script - tell user to pass in the -n option

- operator/build/Dockerfile
Updating Ansible Operator to 0.7.0
KIALI-2709
> [KIALI-2709] Update Kiali Operator version to 0.7.0

- graph/appender/response_time.go
- graph/appender/response_time_test.go
- add test for this case
- fix some linter suggestions
Before (rt < 50):
After  (rt < 50):
> KIALI-2718 Don't confuse no response time with rt=0

- operator/roles/kiali-deploy/tasks/main.yml
there's a typo in here that breaks the web_root check. fix it
> [operator] fix wrong name of web_root var

- tests/e2e/tests/test_kiali_configmap.py
> KIALI-2651

- operator/deploy/kiali/kiali_cr.yaml
- operator/roles/kiali-deploy/defaults/main.yml
- operator/roles/kiali-deploy/templates/kubernetes/service.yaml
- operator/roles/kiali-deploy/templates/openshift/service.yaml
This follows up on https://github.com/kiali/kiali/pull/1013. Do NOT merge this PR until that PR 1013 is merged.
See: https://issues.jboss.org/browse/KIALI-2727
> KIALI-2727 [operator] extend service

- hack/cluster-openshift.sh
I've just updated the hack script to use maistra 0.10.0 in the installation.
Let me know if there is other place to update this.
> Bump to maistra 0.10.0

- Makefile
- operator/Makefile
Changes such that Makefiles work better in certain bash envs
> KIALI-2755 Add more quoting in the makefiles

- hack/cluster-openshift.sh
> issue #1034 - have cluster-openshift.sh use the new operator deploy script

- operator/Makefile
@burmanm , merry christmas.
this currently only downloads the x86_64-linux-gnu version (the [only other version available](https://github.com/operator-framework/operator-sdk/releases/tag/v0.7.0) is for mac - I'll leave it as a future exercise for someone that cares about mac to enhance this to pull the mac version when appropriate)
> if the dev does not have operator-sdk, download it automatically and use it

- tests/e2e/tests/test_api_methods.py
Add tests for the following:
AuthenticationInfo
OpenshiftCheckToken
namespaceTls
podDetails
podLogs
> KIALI-2771 - New Test cases

- operator/deploy/kiali/kiali_cr.yaml
This bit of doc was removed when resolving conflict here : https://github.com/kiali/kiali/pull/977
> Config doc update after merge conflict

- prometheus/metrics.go
Switching reviewer from mazz to joel because mazz is on pto...
> KIALI-2781 Remove aggressive metrics logging

- business/istio_validations.go
KIALI-2454 introduced a small regression that removed ServiceRoles validations from the Istio Config List (they appeared correctly in the details). This returns them back to the list as well.
KIALI-2762
> KIALI-2762 Fix regression, missing ServiceRole validations in list

- config/config.go
- status/versions_test.go
update versions to ensure necessary telemetry
> KIALI-2783 up required istio/maistra versions

- operator/deploy/kiali/kiali_cr.yaml
- operator/roles/kiali-deploy/defaults/main.yml
> KIALI-2814 only exclude kiali-operator

- kiali.go
- kiali_test.go
allow web root validation to support things as mentioned in issue #1059
> KIALI-2836 enhance webroot validation

- operator/deploy/deploy-kiali-operator.sh
cc @jotak 
See if this provides what you want. It is kind of weird syntax (opts go after the <() argument), but to pass cmdline opts when using <() notation, you do it like this
`bash <(curl -L https://git.io/getLatestKialiOperator) --help`
e.g.
`bash <(curl -L https://git.io/getLatestKialiOperator) -ju http://my-jaeger --auth-strategy anonymous `
> KIALI-2847 support cmd line options in deploy script

- graph/protocol.go
> KIALI-2869 Don't assume a service graph edge has non-error traffic

- business/health.go
- models/health.go
- models/workload.go
- models/workload_test.go
- swagger.json
This still needs a UI PR, otherwise it will break the frontend.
https://github.com/kiali/kiali-ui/pull/1191
> KIALI-2728 Use Desired/Current/Available replicas for Workload Health

- business/jaeger_helper.go
JIRA: [KIALI-2893](https://issues.jboss.org/browse/KIALI-2893)
> KIALI-2893 Show the traces tab if jaeger is configured but application is not available and show warning

- .github/stale.yml
Change the stalebot label from wontfix to stale
> Change label and make text more explicit

- config/config.go
- operator/deploy/kiali/kiali_cr.yaml
- operator/roles/kiali-deploy/defaults/main.yml
- status/versions.go
JIRA: [KIALI-2850]( https://issues.jboss.org/browse/KIALI-2850)
> KIALI-2850 Disable displaying tracing information in the UI

- deploy/jenkins-ci/Jenkinsfile
https://issues.jboss.org/browse/KIALI-2900
> KIALI-2900 Create release cut in UI repo after NPM publish

- business/jaeger_helper.go
- kiali.go
Fix control in kiali when tracing is not enabled
Related with: [KIALI-2902](https://issues.jboss.org/browse/KIALI-2902)
cc @mwringe
> KIALI-2902 Missing tracing tab

- business/openshift_oauth.go
https://issues.jboss.org/browse/KIALI-2929
When using OpenShift authentication, Kiali was assuming that
installation namespace is the same as the Istio namespace.
Fixing by using the ServiceAccount default namespace context as Kiali's
namespace.
This is related to issue #1094
> KIALI-2929 Fix wrong assumption of Kiali being in Istio namespace

- operator/Makefile
- operator/deploy/kiali/kiali_cr.yaml
- operator/roles/kiali-deploy/defaults/main.yml
> KIALI-2941 Change default logging from Debug to Info

- business/threescale.go
Updates the 3scale rule and instance to meet Istio and 3scale requiremetns 
No
> Threescale fixes

- hack/istio/install-istio-kiali-via-helm.sh
just some small changes so the hack script installs 1.1 according to the istio docs
> hack script changes for istio 1.1

- tests/e2e/config/env.yaml
- tests/e2e/requirements.txt
- tests/e2e/tests/conftest.py
- tests/e2e/tests/test_api_methods.py
- Adding Support for OAuth on E2ES
> KIALI-2944 - Adding Support for OAuth on E2E Tests

- business/istio_config.go
- handlers/istio_config.go
- kubernetes/client.go
- kubernetes/istio_details_service.go
- kubernetes/kubetest/mock.go
- kubernetes/types.go
- models/istio_config.go
- models/sidecars.go
- swagger.json
Adds Sidecar istio resource
UI PR: https://github.com/kiali/kiali-ui/pull/1230
> KIALI-2748 Support Sidecar Istio resource in Istio Config

- config/config.go
- handlers/grafana.go
- models/grafana_info.go
- operator/deploy/kiali/kiali_cr.yaml
- operator/roles/kiali-deploy/defaults/main.yml
- operator/roles/kiali-deploy/tasks/main.yml
- status/discover.go
- swagger.json
JIRA: https://issues.jboss.org/browse/KIALI-2963
As discussed in comments, I'm also renaming / cleaning some of the grafana config: https://issues.jboss.org/browse/KIALI-2966
Frontend PR: https://github.com/kiali/kiali-ui/pull/1234
> KIALI-2963 Use configured istio namespace for grafana/jaeger/prometheus

- config/config.go
- handlers/grafana.go
- handlers/grafana_test.go
- operator/deploy/kiali/kiali_cr.yaml
- operator/roles/kiali-deploy/defaults/main.yml
- prometheus/client.go
- status/discover.go
- status/versions.go
- util/http_util.go
Both for Grafana and Prometheus
JIRA: https://issues.jboss.org/browse/KIALI-2960
See also #786
> KIALI-2960 Add config to skip verify insecure https

- tests/e2e/assets/bookinfo-ratings-delay.yaml
- tests/e2e/tests/test_kiali_istio_endpoint.py
- Update E2Es to support multiple bookinfo namespaces
> KIALI-2991 - Update E2Es to support multiple bookinfo namespaces

- handlers/graph_test.go
https://github.com/kiali/kiali/issues/1125
> fix graph_test failed on Windows

- hack/cluster-openshift.sh
Minor, just adjust the waiting order with the natural startup order.
> Change order of waiting apps to improve user experience

- operator/deploy/role.yaml
- operator/roles/kiali-deploy/templates/kubernetes/role-viewer.yaml
- operator/roles/kiali-deploy/templates/kubernetes/role.yaml
- operator/roles/kiali-deploy/templates/openshift/role-viewer.yaml
- operator/roles/kiali-deploy/templates/openshift/role.yaml
Missing entries in role.yaml for kubernetes and openshift deployments.
> KIALI-3004 Fix missing sidecars role

- operator/deploy/deploy-kiali-operator.sh
This now provides an option to uninstall the operator if it already exists.
> KIALI-2924 option to uninstall operator if exists

- operator/deploy/deploy-kiali-operator.sh
This allows you to pass `-kcr <file.yaml>` to the deploy script and that will be used when creating a Kiali CR rather that using the cmdline opts/env vars to build the CR.
This has some yaml parsing magic to try to extract the auth-strategy and the accessible-namespaces from the Kiali CR - the script needs to know these two things so it can do special things (like know if it has to create the secret or if it needs to grant the operator special cluster-admin-like permissions).
> KIALI-3011 give a custom CR to the script

- operator/roles/kiali-deploy/templates/kubernetes/deployment.yaml
- operator/roles/kiali-deploy/templates/openshift/deployment.yaml
https://issues.jboss.org/browse/KIALI-3024
> KIALI-3024 probes should use http when no identity cert is defined

- config/config.go
- operator/deploy/kiali/kiali_cr.yaml
- status/discover.go
jira: [kiali-3025](https://issues.jboss.org/browse/KIALI-3025)
> KIALI-3025 Wrong Jaeger base query when defined

- config/config.go
- operator/deploy/kiali/kiali_cr.yaml
- status/discover.go
> Fix to return jaeger url + path

- tests/e2e/tests/test_kiali_service_endpoint.py
- tests/e2e/tests/test_kiali_workload_endpoint.py
- tests/e2e/utils/command_exec.py
Some e2e test were broken.
https://issues.jboss.org/browse/KIALI-2102
> KIALI-2102 Fixing service/workload e2e tests

- models/service_entry.go
- models/virtual_service.go
- swagger.json
VirtualServices and ServiceEntries added new top level fields at Spec.
https://issues.jboss.org/browse/KIALI-3031
> KIALI-3031 Add missing fields in VS/SE

- Makefile
Moving master to 1.1.0-snapshot
> Mark master as 1.1.0

- status/discover.go
I prefer keep the code and change order , we need to check if there is an impact of this
> KIALI-3054 need auto-detection to work for jaeger under all situations

- RELEASING.adoc
- deploy/jenkins-ci/Dockerfile
- deploy/jenkins-ci/Makefile
- operator/Makefile
Now that the workflow for a major release is defined, apply this knowledge to the Jenkins pipeline.
> Prepare for major release workflow

- README.adoc
> fix README spell mistake

- config/config.go
overriding Prometheus auth config with grafana auth config
https://github.com/kiali/kiali/pull/1120/files#r298045690
> Wrong override of prometheus auth config

- graph/config/cytoscape/cytoscape.go
Fix traffic graph and Response Codes didn't match when dealing with very low request rates
https://github.com/kiali/kiali/issues/1196
no
> fix precision about traffic rate

- graph/config/cytoscape/cytoscape.go
- graph/config/cytoscape/cytoscape_test.go
Earlier today we merged https://github.com/kiali/kiali/pull/1207 but when running things it seemed the fix may not be quite right.  I added some tests and as a result I've tweaked the algorithm.  It's not quite as slick but seems to work.
> Kiali-GH-1196 fix small rate handling

- Makefile
> Swagger HEAD is broken (generates non-deterministic output)

- hack/crc-openshift.sh
to support one-command-install (without requiring addition user input at a prompt) provide a way to tell the script to make the kiali user cluster-admin (or not).
> [hack] option to tell script to make kiali user cluster-admin or not

- ADOPTERS.adoc
A list of adopters / users of Kiali.
> Initial adopters file

- operator/README.adoc
Update the README to give correct information
> Operator is now available.

- operator/molecule/accessible-namespaces-test/kiali-cr.yaml
- operator/molecule/accessible-namespaces-test/molecule.yml
- operator/molecule/accessible-namespaces-test/playbook.yml
- operator/molecule/asserts/accessible_namespaces_contains.yml
- operator/molecule/asserts/accessible_namespaces_equals.yml
- operator/molecule/common/set_accessible_namespaces_to_list.yml
tests you can change accessible_namespaces from ** to a specific list of names and back.
cc @gbaufake
> add molecule test - making sure you can switch accessible_namespaces

- operator/deploy/kiali/kiali_cr.yaml
- operator/roles/kiali-deploy/defaults/main.yml
- operator/roles/kiali-deploy/templates/kubernetes/deployment.yaml
- operator/roles/kiali-deploy/templates/openshift/deployment.yaml
https://issues.jboss.org/browse/KIALI-3128
> KIALI-3128 be able to specify imagePullSecrets in the Deployment

- operator/roles/kiali-deploy/tasks/main.yml
https://issues.jboss.org/browse/KIALI-3111
> KIALI-3111 delete deployment if the image name or version is changing

- operator/deploy/kiali/kiali_cr.yaml
- operator/roles/kiali-deploy/defaults/main.yml
- operator/roles/kiali-deploy/templates/kubernetes/deployment.yaml
- operator/roles/kiali-deploy/templates/openshift/deployment.yaml
> KIALI-3128 be able to specify imagePullSecrets in the Deployment 

- operator/deploy/deploy-kiali-operator.sh
- operator/roles/kiali-deploy/templates/kubernetes/deployment.yaml
- operator/roles/kiali-deploy/templates/openshift/deployment.yaml
https://issues.jboss.org/browse/KIALI-3136
> KIALI-3136 - use deployment.secret_name

- business/dashboards.go
Need to check the UseKialiToken field to pass token to k-charted
JIRA: https://issues.jboss.org/browse/KIALI-3096
> KIALI-3096 Fix runtimes metrics w/ maistra (v1.1.x)

- business/jaeger_helper.go
- config/config.go
- operator/deploy/kiali/kiali_cr.yaml
- operator/roles/kiali-deploy/defaults/main.yml
- status/discover.go
This is a backport into [v1.0] of https://github.com/kiali/kiali/pull/1275
> KIALI-3151 [v1.0] Add namespace and port for Jaeger integration test

- business/checkers/gateways/multi_match_checker.go
- business/checkers/gateways/multi_match_checker_test.go
Mark all the hosts as duplicate validations, not just the first occurence.
KIALI-3171
> KIALI-3171 Mark all matching duplicate gateway hosts

- business/checkers/gateways/multi_match_checker.go
- business/checkers/gateways/multi_match_checker_test.go
> KIALI-3171 [v1.0] Mark all matching duplicate gateway hosts as validation warnings 

- operator/deploy/kiali/kiali_cr.yaml
- operator/roles/kiali-deploy/defaults/main.yml
keep operator reference/doc yaml and actual yaml sorted
> KIALI-3180 sort files/settings properly

- handlers/base.go
- handlers/graph.go
- add RespondWithDetailedError() for reporting an error with additional
detail (stack trace, or whatever)
- use formal type for error responses
- graph code now returns a stack trace for app errors
- fix multiple-response bug in error response handling in graph code
*** UI PR: https://github.com/kiali/kiali-ui/pull/1353
> KIALI-2938 Better support detailed error messages

- business/checkers/destinationrules/disabled_namespacewide_mtls_checker.go
- business/checkers/destinationrules/meshwide_mtls_checker.go
- business/checkers/destinationrules/namespacewide_mtls_checker.go
- business/checkers/mesh_policies_checker.go
- business/checkers/meshpolicies/mesh_mtls_checker.go
- business/checkers/service_mesh_policies_checker.go
- business/istio_config.go
- business/istio_validations.go
- business/istio_validations_test.go
- business/tls.go
- business/tls_test.go
- handlers/istio_config.go
- kubernetes/client.go
- kubernetes/istio_details_service.go
- kubernetes/kubernetes_service.go
- kubernetes/kubetest/mock.go
- kubernetes/types.go
- models/cluster_rbac_config.go
- models/istio_config.go
- models/istio_validation.go
- models/mesh_policy.go
- operator/deploy/role.yaml
- operator/roles/kiali-deploy/templates/openshift/role-viewer.yaml
- operator/roles/kiali-deploy/templates/openshift/role.yaml
- swagger.json
This is the v1.0 version of https://github.com/kiali/kiali/pull/1326
It's still in WIP, it needs some changes in the operator as Kiali will require new permissions on maistra.io API.
> [V1.0] KIALI-3193 Add support for ServiceMeshPolicy,ServiceMeshRbacConfig

- business/istio_validations.go
- business/tls.go
backport of KIALI-3220 into v1.0 branch
> [V1.0] KIALI-3220 Fetch ServiceMeshPolicies from control-plane

- tests/e2e/tests/test_kiali_service_endpoint.py
Fixing service endpoint e2e tests
> Fix service endpoint e2e tests

- hack/crc-openshift.sh
> [hack] upgrade to CRC 0.90.0 and OpenShift 4.1.9 bundle

- business/istio_config.go
- business/istio_validations.go
- business/tls.go
After we changed the MeshPolicies and ClusterRbacConfig queries.
If Kiali doesn't have cluster wide permissions, these queries can fail.
When Kiali doesn't have cluster rights, these queries will return empty.
> KIALI-3235 MeshPolicies queries shouldn't fail without cluster rights

- graph/telemetry/istio/istio.go
I was looking at the code and noticed that we used destSvc as the var name for the value of the destination_service_name label.  Since there is also a destination_service label I was momentarily confused as to which value was stored.  This makes it explicit.
> trivial - change some var names from destSvc to destSvcName to better reflect the content.

- hack/istio/install-istio-kiali-via-helm.sh
- 1.3.0 RC1 has 24, up from 23 in RC0
> Update CRD count in helm installer

- hack/istio/install-istio-kiali-via-helm.sh
The official 1.3.0 release has dropped the number of CRDs back to 23.
> Istio 1.3.0-RC3 -> 1.3.0, CRD count 25 -> 23

- operator/deploy/deploy-kiali-operator.sh
> don't output message when not installing kiali

- operator/roles/kiali-deploy/templates/kubernetes/deployment.yaml
- operator/roles/kiali-deploy/templates/openshift/deployment.yaml
> make secret optional when http is configured

- handlers/authentication.go
Return 401 instead, so that Kiali UI will get back to the login screen
Also, fixes an issue with response being written twice (`RespondWithError` call followed by `RespondWithCode`)
Closes https://github.com/kiali/kiali/issues/1662
> Do not return error 500 on missing cookie during logout

- tests/e2e/tests/test_api_methods.py
- tests/e2e/tests/test_kiali_urls.py
> Revert "E2E - Fixes for Jaeger related test cases"

- business/jaeger_helper.go
- config/config.go
- handlers/jaeger.go
- operator/deploy/kiali/kiali_cr.yaml
- operator/roles/kiali-deploy/defaults/main.yml
Related with : https://github.com/kiali/kiali/issues/1624
Push changes to master
Done in v1.0 https://github.com/kiali/kiali/pull/1628
> Add inClusterURL to Jaeger configuration

- models/workload.go
- models/workload_test.go
In some cases k8s API can return a nil value for Labels instead of empty value.
Fixes https://github.com/kiali/kiali/issues/1718
> Fix potential nil value in workloads

- business/dashboards.go
- glide.lock
- glide.yaml
- models/dashboards.go
- vendor/github.com/kiali/k-charted/README.md
- vendor/github.com/kiali/k-charted/RELEASE.md
- vendor/github.com/kiali/k-charted/business/dashboards.go
- vendor/github.com/kiali/k-charted/business/dashboards_test.go
- vendor/github.com/kiali/k-charted/business/grafana.go
- vendor/github.com/kiali/k-charted/kubernetes/mock/mock.go
- vendor/github.com/kiali/k-charted/kubernetes/v1alpha1/spec.go
- vendor/github.com/kiali/k-charted/log/logger.go
- vendor/github.com/kiali/k-charted/log/logger_test.go
- vendor/github.com/kiali/k-charted/model/dashboards.go
- vendor/github.com/kiali/k-charted/model/dashboards_test.go
- vendor/github.com/kiali/k-charted/web/pf3/yarn.lock
- vendor/github.com/kiali/k-charted/web/pf4/package.json
- vendor/github.com/kiali/k-charted/web/pf4/src/components/Container.tsx
- vendor/github.com/kiali/k-charted/web/pf4/src/components/Dashboard.tsx
- vendor/github.com/kiali/k-charted/web/pf4/src/utils/victoryChartsUtils.ts
- vendor/github.com/kiali/k-charted/web/pf4/yarn.lock
- Change unit of request_duration_millis from "ms" to "seconds" with scaling 0.001, so that the scaling mechanism on time units is preserved
- Fix an issue with k-charted loggers (was all set to Warning)
- Update version of k-charted
Closes https://github.com/kiali/kiali/issues/1738
PR required: https://github.com/kiali/k-charted/pull/56
> Fix unit scaling for mixer-less telemetry

- glide.lock
- glide.yaml
- vendor/github.com/kiali/k-charted/web/pf3/package.json
- vendor/github.com/kiali/k-charted/web/pf4/package.json
Switch from release candidate to release (same code)
> Update k-charted 0.3.0

- operator/build/Dockerfile
> [operator] upgrades the ansible operator base image

- operator/deploy/operator.yaml
- operator/deploy/operator_without_ao.yaml
- operator/manifests/kiali-community/1.6.1/kiali.crd.yaml
- operator/manifests/kiali-community/1.6.1/kiali.monitoringdashboards.crd.yaml
- operator/manifests/kiali-community/1.6.1/kiali.v1.6.1.clusterserviceversion.yaml
- operator/manifests/kiali-community/1.7.0/kiali.crd.yaml
- operator/manifests/kiali-community/1.7.0/kiali.monitoringdashboards.crd.yaml
- operator/manifests/kiali-community/1.7.0/kiali.v1.7.0.clusterserviceversion.yaml
- operator/manifests/kiali-community/kiali.package.yaml
- operator/manifests/kiali-ossm/1.0.7/kiali.crd.yaml
- operator/manifests/kiali-ossm/1.0.7/kiali.monitoringdashboards.crd.yaml
- operator/manifests/kiali-ossm/1.0.7/kiali.v1.0.7.clusterserviceversion.yaml
- operator/manifests/kiali-ossm/kiali-ossm.package.yaml
- operator/manifests/kiali-upstream/kiali.package.yaml
- operator/manifests/kiali-upstream/kiali.v0.18.1.clusterserviceversion.yaml
- operator/manifests/kiali-upstream/kiali.v1.1.0.clusterserviceversion.yaml
- operator/manifests/kiali-upstream/kiali.v1.6.1.clusterserviceversion.yaml
- operator/manifests/kiali-upstream/kiali.v1.7.0.clusterserviceversion.yaml
- operator/roles/kiali-deploy/tasks/main.yml
> [operator] support operator upgrades

- Makefile
> Revert "Prepare for next version"

- hack/crc-openshift.sh
in case anyone wants to try CRC - this updates the hack script to the CRC 1.0.0 release.
> [hack] crc script - just moving to 1.0.0 of crc

- business/istio_validations.go
- handlers/services.go
Closes https://github.com/kiali/kiali/issues/1786
@burmanm @xeviknal If i'm correct, the error resulting from validation checks was ignored. Now at least it's logged.
If I'm correct having an error might result in empty validations object.
> Fix potentially ignored error from validation checks

- hack/aws-openshift.sh
This moves to OpenShift 4.2.2 - this version fixes the operator dependency bug we are hitting when installing ServiceMesh (where it was installing community versions of Jaeger and Kiali when it should not have been).
This also adds support for passing an SSH key to the installer for debugging. See: https://docs.openshift.com/container-platform/4.1/installing/installing_aws/installing-aws-customizations.html#ssh-agent-using_install-customizations-cloud
> [hack] move to OS 4.2.x and support ssh key

- Makefile
Adding version flags to build-system-test goal.
> Add version flags to build-system-test goal

- tests/e2e/tests/test_api_methods.py
- Adding E2E Istio Config Create Testing
@xeviknal, after preforming the request as you've shown me, I am getting ``'{"error":"invalid character \'m\' looking for beginning of value"}'``.
I already debugged it doesn't make the response to me.
> Adding  E2E VirtualService Create/Delete Test

- tests/e2e/tests/test_api_methods.py
> Minor fix on E2E method

- tests/e2e/tests/test_api_methods.py
> Revert "Minor fix on E2E method"

- business/checkers/services/port_mapping_checker_test.go
- kubernetes/istio_details_service.go
Adding support to mysql for port protocols in the mismatch validation.
Fixes https://github.com/kiali/kiali/issues/1885#event-2774474322
yes
> Validations - Adding mysql as port protocol for services

- hack/istio/install-istio-via-istioctl.sh
updates the resource requirements so default profile can be installed in our aws clusters
> [hack] allows you to install istio default profile

- hack/istio/install-istio-via-istioctl.sh
we can remove this workaround because istio 1.4 beta4 fixed the problem
> [hack] no need for this hack in the hack script

- operator/manifests/kiali-community/1.9.1/kiali.crd.yaml
- operator/manifests/kiali-community/1.9.1/kiali.monitoringdashboards.crd.yaml
- operator/manifests/kiali-community/1.9.1/kiali.v1.9.1.clusterserviceversion.yaml
- operator/manifests/kiali-community/kiali.package.yaml
- operator/manifests/kiali-upstream/1.9.1/kiali.crd.yaml
- operator/manifests/kiali-upstream/1.9.1/kiali.monitoringdashboards.crd.yaml
- operator/manifests/kiali-upstream/1.9.1/kiali.v1.9.1.clusterserviceversion.yaml
- operator/manifests/kiali-upstream/kiali.package.yaml
closes #1917 
This moves us up to Phase 4 "Deep Insights" (kiali operator is a phase 4 operator as per the OLM team)
> issue 1917 - add v1.9.1 operator manifests for community and upstream

- business/services.go
- config/config.go
- models/additional_item.go
- models/service.go
- models/workload.go
- models/workload_test.go
- operator/deploy/kiali/kiali_cr.yaml
- operator/roles/kiali-deploy/defaults/main.yml
- operator/roles/kiali-deploy/vars/main.yml
- swagger.json
- Add related annotation values in Workload and Service models
- Some refactoring to mutualize meta-related conversions in all workload kinds
- Add some tests
Part of https://github.com/kiali/kiali/issues/1564
Frontend PR: https://github.com/kiali/kiali-ui/pull/1527
> Add annotations for display config

- business/checkers/destinationrules/multi_match_checker.go
Preventing the following json output:
Needs https://github.com/kiali/kiali-ui/pull/1522
https://github.com/kiali/kiali/issues/1419
> Prevent empty reference on validations

- business/namespaces.go
- handlers/apps.go
- handlers/errors.go
- handlers/health.go
- handlers/istio_config.go
- handlers/services.go
- handlers/threescale.go
- handlers/workloads.go
Ignore a namespace included in accessible_namespaces that does not exist
Fix #1906
> Return 403 instead 500 for accessible_namespaces filtered queries

- business/namespaces.go
Fixes #1924 
@jshaughn I've prepared a fix, but I couldn't test it yet, I'm preparing an AWS environment (but you know it takes time...).
If you can test it, I guess this should solve the issue.
Let me know, thanks !
> Filter OS projects with accessible_namespaces for consistency

- business/istio_config.go
- kubernetes/cache/cache.go
- kubernetes/cache/istio.go
- kubernetes/cache/kubernetes.go
Fixes #1877 
@hhovsepy I couldn't test it locally, but I guess it should work.
Tomorrow I will perform more tests but let me know if you can test it.
> Refresh Kiali caches after Create/Update/Delete

- business/jaeger_helper.go
- config/config.go
- handlers/jaeger.go
- models/jaeger_info.go
- operator/deploy/kiali/kiali_cr.yaml
- operator/roles/kiali-deploy/defaults/main.yml
- swagger.json
Fix https://github.com/kiali/kiali/issues/1785
> Add Jaeger configuration for namespaceSelector

- operator/deploy/deploy-kiali-operator.sh
> issue 1934 - fix the name in deploy script - it is now tracing, not jaeger

- hack/istio/install-istio-kiali-via-helm.sh
This is the old hack script that installs Istio using the helm charts. The current istio 1.4 beta is broken when attempting to install via istioctl, so this PR updates the hack script that installs 1.4 using the old helm method. Helm installation like this is deprecated in 1.4 but still works.
> [hack] this is to support installing upstream istio 1.4.

- handlers/authentication.go
related to: https://github.com/kiali/kiali/issues/1953
> Improve error reporting in authentication.go

- operator/deploy/kiali/kiali_cr.yaml
- operator/roles/kiali-deploy/defaults/main.yml
- operator/roles/kiali-deploy/templates/kubernetes/deployment.yaml
- operator/roles/kiali-deploy/templates/openshift/deployment.yaml
upstream istio expects components to be configured with a custom priorityClassName and pod annotations. its a good feature to have. this PR adds this.
> [operator] customize priority class name and pod annotations

- doc.go
- handlers/namespaces.go
- models/istio_validation.go
- models/istio_validation_test.go
- routing/routes.go
- swagger.json
Backend work for https://github.com/kiali/kiali-ui/pull/1541
Returns Validation aggregation count for each namespace:
kiali/kiali#1556
> Adding NamespaceValidations endpoint with summary of validations

- hack/istio/install-bookinfo-demo.sh
new option: `-in` or `--istio-namespace`
> hack - tell bookinfo install script what the control plane namespace is

- business/checkers/destinationrules/traffic_policy_checker.go
- business/checkers/destinationrules/traffic_policy_checker_test.go
Steps to reproduce:
1. Add a DR rule pointing to host `*.bookinfo.svc.cluster.local` enabling mtls.
2. See DR in istio-system, for example `istio-telemetry`
Kiali warns DR in istio-system. It shouldn't be.
This PR fixes that.
Closes https://github.com/kiali/kiali/issues/1963
> Validations - Destination Rule traffic policy override error

- operator/molecule/maistra-e2e-test/prepare.yml
Minor fix on Molecule OLM Tests
> [minor] Adding Extra timeout on Molecule OLM Tests

- operator/molecule/olm-test/prepare.yml
Minor fix on OLM tests to run it on Jenkins.
> Minor Fix on Molecule OLM Test

- graph/options.go
Bug fix needed for https://github.com/kiali/kiali/issues/1421
> Fix handling of safeDuration for custom queryTimes

- operator/manifests/kiali-ossm/1.0.8/kiali.crd.yaml
- operator/manifests/kiali-ossm/1.0.8/kiali.monitoringdashboards.crd.yaml
- operator/manifests/kiali-ossm/1.0.8/kiali.v1.0.8.clusterserviceversion.yaml
> Update Kiali CSV to 1.0.8

- operator/deploy/deploy-kiali-operator.sh
- operator/deploy/role.yaml
- operator/molecule/asserts/roles-test/ro_clusterrole_asserts.yml
- operator/molecule/asserts/roles-test/ro_role_asserts.yml
- operator/molecule/asserts/roles-test/rw_clusterrole_asserts.yml
- operator/molecule/asserts/roles-test/rw_role_asserts.yml
- operator/molecule/default/destroy.yml
- operator/molecule/default/prepare.yml
- operator/molecule/only-view-only-mode-test/kiali-cr.yaml
- operator/molecule/only-view-only-mode-test/molecule.yml
- operator/molecule/only-view-only-mode-test/playbook.yml
- operator/roles/kiali-deploy/tasks/kubernetes/k8s-main.yml
- operator/roles/kiali-deploy/tasks/openshift/os-main.yml
- operator/roles/kiali-deploy/tasks/process-additional-roles.yml
fixes https://github.com/kiali/kiali/issues/1873
> [operator] restrict operator permissions with view-only-mode option in deploy script

- operator/manifests/create-new-version.sh
This is additional work to help with generating manifests that can be used during QE/testing.
> enhance the script that generates new olm manifests

- operator/manifests/kiali-community/1.11.0/kiali.crd.yaml
- operator/manifests/kiali-community/1.11.0/kiali.monitoringdashboards.crd.yaml
- operator/manifests/kiali-community/1.11.0/kiali.v1.11.0.clusterserviceversion.yaml
- operator/manifests/kiali-community/kiali.package.yaml
- operator/manifests/kiali-upstream/1.11.0/kiali.crd.yaml
- operator/manifests/kiali-upstream/1.11.0/kiali.monitoringdashboards.crd.yaml
- operator/manifests/kiali-upstream/1.11.0/kiali.v1.11.0.clusterserviceversion.yaml
- operator/manifests/kiali-upstream/kiali.package.yaml
these are the golden copies for the community and upstream manifests. Once merged, I'll copy them over and submit them to the OLM repos for publication.
> [operator] OLM manifests for 1.11.0

- hack/crc-openshift.sh
This just keeps the CRC hack script up to date for use when you want to test simple things out on a local openshift cluster.
Since we can't install Maistra/Istio in CRC, this PR rips that all out.
This does update to a newer CRC version.
> [hack] update CRC hack script plus rip out istio stuff

- operator/deploy/kiali/kiali_cr.yaml
> remove an obsolete comment from CR since it isn't true anymore

- README.adoc
> fix the README section on building the server with a locally built UI

- business/istio_config.go
- business/istio_validations.go
- handlers/istio_config.go
- kubernetes/client.go
- kubernetes/istio_details_service.go
- kubernetes/kubetest/mock.go
- kubernetes/types.go
- models/authorization_policy.go
- models/istio_config.go
- swagger.json
Adding new CRD: AuthorizationPolicies
Needs to be merged with frontend changes: https://github.com/kiali/kiali-ui/pull/1582.
References https://github.com/kiali/kiali/issues/1344
> Add AuthorizationPolicies support to Kiali 

- business/checkers/destinationrules/multi_match_checker.go
- business/checkers/destinationrules/multi_match_checker_test.go
- business/checkers/destinationrules/traffic_policy_checker_test.go
- business/checkers/virtual_services/single_host_checker_test.go
Fixes https://github.com/kiali/kiali/issues/2052
> Fix references for DR multimatch checker

- operator/deploy/kiali/kiali_cr.yaml
- operator/molecule/null-cr-values-test/kiali-cr.yaml
- operator/molecule/null-cr-values-test/molecule.yml
- operator/molecule/null-cr-values-test/playbook.yml
- operator/roles/kiali-deploy/filter_plugins/stripnone.py
- operator/roles/kiali-deploy/vars/main.yml
fixes #2059 
This is to support when users want to remove their own custom values and want to fall back to the defaults.
> [operator] strip all values in the dicts that are of type NoneType

- kubernetes/istio_details_service.go
Approaching minors from https://github.com/kiali/kiali/pull/2028#pullrequestreview-334813932
https://github.com/kiali/kiali/pull/2028#pullrequestreview-334813932
> Approaching minors from kiali/kiali#2028

- operator/roles/kiali-deploy/templates/kubernetes/ingress.yaml
fixes https://github.com/kiali/kiali/issues/2066
> [operator] create proper annotations on k8s ingress when https is disabled on the backend

- operator/build/Dockerfile
- operator/deploy/kiali/kiali_cr.yaml
- operator/deploy/kiali/kiali_cr_dev.yaml
- operator/deploy/kiali/kiali_cr_dev_servicemesh.yaml
fixes #1584
Move up to base image of ansible operator SDK 0.13
> [operator] update base ansible image

- config/config.go
- operator/roles/kiali-deploy/tasks/main.yml
Fixes https://github.com/kiali/kiali/issues/2084
> Have a correct default in-cluster URL for Jaeger without Maistra

- config/config.go
- config/config_test.go
- config/security/config_security.go
Fixes https://github.com/kiali/kiali/issues/2095
> Purge sensitive config from logs

- make/Makefile.cluster.mk
This is to give devs details about the cluster the makefiles will use.
This is helpful when devs switch between different environments (e.g. minikube and openshift).
Example output when the cluster is a remote OpenShift cluster:
```
$ make cluster-status
OCP repos: external=[default-route-openshift-image-registry.apps.some.cluster.openshift.com] internal=[image-registry.openshift-image-registry.svc:5000]
===============
CLUSTER DETAILS
===============
Client executable: /home/me/bin/oc
===============
/home/me/bin/oc version
Client Version: openshift-clients-4.2.2-201910250432
Server Version: 4.2.4
Kubernetes Version: v1.14.6+dc8862c
===============
/home/me/bin/oc cluster-info
Kubernetes master is running at https://api.some.cluster.openshift.com:6443
To further debug and diagnose …
```
> Add a new make target 'cluster-status'

- business/jaeger.go
- business/services.go
- doc.go
- handlers/jaeger.go
- jaeger/client.go
- jaeger/info.go
- jaeger/services.go
- jaeger/spans.go
- jaeger/traces.go
- jaeger/types.go
- models/jaeger_info.go
- swagger.json
Related with https://github.com/kiali/kiali/issues/1855
> Move jaegerInfo and return if there is an integration and errorMessage

- tests/e2e/tests/test_kiali_urls.py
Fix expected URL assert, to be more generic.
> E2E - Jaeger URL fix

- jaeger/info.go
Fix https://github.com/kiali/kiali/issues/2117
> Traces tab should be visible just with InClusterURL configured

- business/services.go
- handlers/threescale.go
- jaeger/spans.go
> Improve log messages for 3scale and traces

- business/checkers/mesh_policies_checker.go
Fixes https://github.com/kiali/kiali/issues/2102
> MeshPolicies#details show now validations

- business/checkers/virtual_service_checker_test.go
- business/checkers/virtual_services/route_checker.go
- business/checkers/virtual_services/route_checker_test.go
- models/istio_validation.go
Cherry-pick of https://github.com/kiali/kiali/pull/2108
> VirtualService#Route validation: one route under 100 weight warning

- operator/deploy/role.yaml
- operator/manifests/kiali-community/1.13.0/kiali.crd.yaml
- operator/manifests/kiali-community/1.13.0/kiali.monitoringdashboards.crd.yaml
- operator/manifests/kiali-community/1.13.0/kiali.v1.13.0.clusterserviceversion.yaml
- operator/manifests/kiali-community/kiali.package.yaml
- operator/manifests/kiali-upstream/1.13.0/kiali.crd.yaml
- operator/manifests/kiali-upstream/1.13.0/kiali.monitoringdashboards.crd.yaml
- operator/manifests/kiali-upstream/1.13.0/kiali.v1.13.0.clusterserviceversion.yaml
- operator/manifests/kiali-upstream/kiali.package.yaml
- operator/molecule/os-console-links-test/kiali-cr.yaml
- operator/molecule/os-console-links-test/molecule.yml
- operator/molecule/os-console-links-test/playbook.yml
- operator/roles/kiali-deploy/tasks/openshift/os-get-kiali-route-url.yml
- operator/roles/kiali-deploy/tasks/openshift/os-main.yml
- operator/roles/kiali-deploy/templates/openshift/console-links.yaml
- operator/roles/kiali-remove/tasks/main.yml
> [operator] Add console links to OS 4.3 (#2078)

- operator/molecule/os-console-links-test/kiali-cr.yaml
- operator/molecule/os-console-links-test/molecule.yml
- operator/molecule/os-console-links-test/playbook.yml
- operator/roles/kiali-deploy/templates/openshift/console-links.yaml
if server.web_root is "/" (the default when on OS) make sure ConsoleLink href urls do not have `///` in them.
> [operator] make sure ConsoleLink doesn't have triple-slashes in url

- operator/molecule/os-console-links-test/kiali-cr.yaml
- operator/molecule/os-console-links-test/molecule.yml
- operator/molecule/os-console-links-test/playbook.yml
- operator/roles/kiali-deploy/templates/openshift/console-links.yaml
fixes https://github.com/kiali/kiali/issues/2132
> [backport] [operator] make sure ConsoleLink doesn't have triple-slashes in url

- operator/deploy/role.yaml
- operator/manifests/kiali-community/1.13.0/kiali.v1.13.0.clusterserviceversion.yaml
- operator/manifests/kiali-ossm/1.1.0/kiali.v1.1.0.clusterserviceversion.yaml
- operator/manifests/kiali-upstream/1.13.0/kiali.v1.13.0.clusterserviceversion.yaml
- operator/roles/kiali-deploy/tasks/main.yml
- operator/roles/kiali-deploy/templates/openshift/console-links.yaml
backport for fix to https://github.com/kiali/kiali/issues/2136
see the master PR here: https://github.com/kiali/kiali/pull/2138
> [operator] do not create consolelinks if not supported on the openshift version

- config/config.go
- jaeger/client.go
- jaeger/info.go
- jaeger/traces.go
Fix https://github.com/kiali/kiali/issues/2155
> Service Details load Error when Jaeger is configured wrongly

- make/Makefile.operator.mk
fixes https://github.com/kiali/kiali/issues/2157
> fix the grafana and jaeger default urls created by the makefile

- operator/roles/kiali-deploy/tasks/main.yml
fixes https://github.com/kiali/kiali/issues/2170
> [operator] don't look for version if not on openshift.

- operator/roles/kiali-deploy/tasks/main.yml
backport of https://github.com/kiali/kiali/pull/2171
> [backport] [operator] don't look for version if not on openshift.

- operator/deploy/role.yaml
- operator/manifests/kiali-community/1.13.0/kiali.v1.13.0.clusterserviceversion.yaml
- operator/manifests/kiali-ossm/1.12.0/kiali.v1.12.0.clusterserviceversion.yaml
- operator/manifests/kiali-upstream/1.13.0/kiali.v1.13.0.clusterserviceversion.yaml
backport of https://github.com/kiali/kiali/pull/2163
> [backport] [operator] needs new permissions

- operator/deploy/deploy-kiali-operator.sh
fixes https://github.com/kiali/kiali/issues/2174
> don't spit out errors if route or oauthclient types don't exist

- config/config.go
> Set url jaeger default to empty

- jaeger/info.go
- jaeger/types.go
Checked in:
The problem was parsing the data, I don't know why it works in maistra
Fix https://github.com/kiali/kiali/issues/2167
> Fix error integration in Jaeger

- operator/roles/kiali-deploy/tasks/main.yml
> [operator] get k8s version and simplify task getting OS version

- operator/roles/kiali-deploy/tasks/main.yml
backport of https://github.com/kiali/kiali/pull/2184
> [backport] [operator] get k8s version and simplify task getting OS version

- handlers/namespaces.go
- models/istio_validation.go
- models/istio_validation_test.go
- swagger.json
Backend part of this one: https://github.com/kiali/kiali-ui/pull/1646
> Return ObjectCount and validations only of current ns

- operator/manifests/kiali-ossm/1.0.10/kiali.crd.yaml
- operator/manifests/kiali-ossm/1.0.10/kiali.monitoringdashboards.crd.yaml
- operator/manifests/kiali-ossm/1.0.10/kiali.v1.0.10.clusterserviceversion.yaml
This adds the 1.0.10 metadata to our golden copies
> [operator] add the 1.0.10 metadata

- operator/manifests/kiali-ossm/1.0.10/kiali.crd.yaml
- operator/manifests/kiali-ossm/1.0.10/kiali.monitoringdashboards.crd.yaml
- operator/manifests/kiali-ossm/1.0.10/kiali.v1.0.10.clusterserviceversion.yaml
backport of https://github.com/kiali/kiali/pull/2207
> [backport] [operator] add the 1.0.10 metadata

- config/config.go
- handlers/jaeger.go
- models/tracing.go
- operator/deploy/kiali/kiali_cr.yaml
- operator/roles/kiali-deploy/defaults/main.yml
- swagger.json
UI https://github.com/kiali/kiali-ui/pull/1612
Fix https://github.com/kiali/kiali/issues/2230
cc @hhovsepy @lucasponce
> Provide a istio-system services whitelist for jaeger tracing integration

- config/config.go
- jaeger/client.go
- jaeger/info.go
- operator/deploy/kiali/kiali_cr.yaml
- operator/roles/kiali-deploy/defaults/main.yml
- swagger.json
FIx whitelist jaeger services
Fix https://github.com/kiali/kiali/issues/2230
Ui https://github.com/kiali/kiali-ui/pull/1658
> Add a whitelist for services in istio-system

- operator/molecule/affinity-tolerations-resources-test/playbook.yml
- operator/molecule/affinity-tolerations-resources-test/set-affinity-tolerations-resources.yml
- operator/roles/kiali-deploy/tasks/main.yml
> [operator] do not convert pod annotations to snake case

- prometheus/metrics.go
- prometheus/prometheustest/client_test.go
Backport fix for https://github.com/kiali/kiali/issues/2242
> Fix issue when pulling "request_error_count" metrics

- hack/istio/install-istio-via-istioctl.sh
fixes https://github.com/kiali/kiali/issues/2173
> [hack] support installing istio 1.5

- business/checkers/no_service_checker_test.go
- models/istio_validation.go
Adding codes to each validation. Sorting validations by object type alphabetically.
https://github.com/kiali/kiali/issues/1629
> Adding codes to each validation, sorting validation alphabetically by code

- operator/roles/default/kiali-deploy/tasks/main.yml
fixes: https://github.com/kiali/kiali/issues/2440
> Istio no longer generating secrets/certs - so go behind http by default now

- hack/istio/install-istio-via-istioctl.sh
see https://preliminary.istio.io/docs/setup/additional-setup/cni/#hosted-kubernetes-settings
> [hack] looks like new changes to cni options are coming with istio 1.5

- operator/deploy/kiali/kiali_cr.yaml
- operator/roles/default/kiali-deploy/defaults/main.yml
- operator/roles/default/kiali-deploy/templates/kubernetes/deployment.yaml
- operator/roles/default/kiali-deploy/templates/openshift/deployment.yaml
fixes https://github.com/kiali/kiali/issues/2462
> [operator] support node_selector

- hack/istio/download-istio.sh
This allows us to easily download a dev build of upstream Istio. You can then just run `install-istio-via-istioctl` to install it.
You can ask to download a master branch build (`-div latest`) or a specific version dev build (e.g. `-div 1.5-dev`).
> [hack] be able to download a dev build of upstream istio

- business/health_test.go
- models/health.go
Backport for https://github.com/kiali/kiali/issues/2457
Will be included in build 1.12.4 for test purposes.
> Include GRPC failures in Health calculation

- Makefile
- make/Makefile.operator.mk
- operator/deploy/deploy-kiali-operator.sh
- operator/deploy/kiali/kiali_cr_dev.yaml
- operator/deploy/kiali/kiali_cr_dev_servicemesh.yaml
- operator/dev-hosts
- operator/playbooks/kiali-deploy.yml
- operator/playbooks/kiali-remove.yml
- operator/roles/default/kiali-deploy/tasks/main.yml
- operator/roles/v1.12/kiali-deploy/tasks/main.yml
> [operator] if Kiali CR does not specify version, assume "v1.0" as the default

- Makefile
- make/Makefile.operator.mk
- operator/deploy/deploy-kiali-operator.sh
- operator/deploy/kiali/kiali_cr_dev.yaml
- operator/deploy/kiali/kiali_cr_dev_servicemesh.yaml
- operator/dev-hosts
- operator/playbooks/kiali-deploy.yml
- operator/playbooks/kiali-remove.yml
- operator/roles/default/kiali-deploy/tasks/main.yml
- operator/roles/v1.12/kiali-deploy/tasks/main.yml
fixes #2505 
a backport of #2506
> [operator][backport] if Kiali CR does not specify version, assume "v1.0" as the default

- graph/api/api_test.go
- handlers/apps_test.go
- handlers/health_test.go
- handlers/namespaces_test.go
- handlers/services_test.go
Related to #2508 
Not sure if it fixed completely, but I'm preparing one PR with my findings.
> Disable cache on mocked api_test

- business/dashboards_test.go
- models/dashboards.go
- models/dashboards_test.go
Fixes https://github.com/kiali/kiali/issues/2485
> Add GRPC status as dashboards available aggregation/filters

- kubernetes/cache/namespaces.go
This is removing some TRACE logs that were writing some data that is really not required.
> Remove unwanted logs

- business/apps.go
- business/services.go
- models/app.go
- models/namespace.go
- models/service.go
- swagger.json
Related with https://github.com/kiali/kiali/issues/2233
Fix https://github.com/kiali/kiali/issues/1511 & https://github.com/kiali/kiali/issues/1522
Now we show Labels in 
- Namespaces endpoint
- Services endpoint
- Apps endpoint
> Improve filtering capabilities of Overview and List pages

- status/versions.go
- status/versions_test.go
> be able to parse OSSM 1.1 version strings

- handlers/authentication_test.go
- ldap/models.go
> Run `make format` to fix linting issues

- operator/deploy/role.yaml
- operator/manifests/kiali-community/1.15.1/kiali.v1.15.1.clusterserviceversion.yaml
- operator/manifests/kiali-ossm/1.12.6/kiali.v1.12.6.clusterserviceversion.yaml
- operator/manifests/kiali-upstream/1.15.1/kiali.v1.15.1.clusterserviceversion.yaml
this is a cherry pick of https://github.com/kiali/kiali/pull/2564 and also adds some metadata for v1.15.1
> [kiali] [v1.15] update role for cve

- operator/deploy/deploy-kiali-operator.sh
fixes https://github.com/kiali/kiali/issues/2565
> [operator] provide correct docs on default settings

- operator/manifests/kiali-ossm/1.12.6/kiali.v1.12.6.clusterserviceversion.yaml
These weird characters should be a space (ASCII 32) but it appears they are 3 bytes ef-bf-bc - and I have no idea how these got in there:
```
ef  bf  bc
o   ?   <
```
> no idea how these weird special non-space chars got in here, but remove them

- operator/manifests/create-new-version.sh
This goes along with the doc update in "Prepare for future release" section of:
https://docs.jboss.org/pages/viewpage.action?spaceKey=KIALI&title=Productization+Build+and+Release+Process
> add -rv option to manifest generator

- operator/roles/default/kiali-deploy/tasks/main.yml
fixes https://github.com/kiali/kiali/issues/2590
backport of https://github.com/kiali/kiali/pull/2593
> [operator] [v1.12] base64 encode the signing key in the secret

- operator/roles/default/kiali-deploy/tasks/main.yml
fixes https://github.com/kiali/kiali/issues/2590
> [operator] base64 encode the signing key in the secret

- make/Makefile.container.mk
- operator/build/Dockerfile
fixes https://github.com/kiali/kiali/issues/2484
> [operator] move to 0.16 of the operator base image/operator-sdk

- tests/e2e/requirements.txt
- tests/e2e/tests/test_api_methods.py
> E2E - Fix for new swagger changes

- graph/api/api_test.go
- graph/api/testdata/test_complex_graph.expected
- graph/telemetry/istio/util/util.go
Backport fix for service entry node regression to support 1.15
> [v1.15] Relax filtering of bad telemetry (#2571)

- graph/api/api_test.go
- graph/telemetry/istio/appender/response_time.go
- graph/telemetry/istio/istio.go
- graph/telemetry/istio/util/util.go
- graph/types.go
- Add filter for bad source telemetry matching the signature identified in this issue.
- Add test
backport for https://github.com/kiali/kiali/issues/2622
> [v1.15] Protect against bad source telemetry (#2636)

- operator/manifests/kiali-ossm/1.12.8/kiali.crd.yaml
- operator/manifests/kiali-ossm/1.12.8/kiali.monitoringdashboards.crd.yaml
- operator/manifests/kiali-ossm/1.12.8/kiali.v1.12.8.clusterserviceversion.yaml
- operator/manifests/kiali-ossm/kiali-ossm.package.yaml
fixes https://github.com/kiali/kiali/issues/2627
backport of https://github.com/kiali/kiali/pull/2639
> [operator] [v1.12] additional changes needed to support disconnected use-case

- business/istio_config.go
- kubernetes/istio_details_service.go
- kubernetes/types.go
- models/authorization_policy.go
- swagger.json
These are the changes in backend to support the new AuthorizationPolicy form from Kiali.
It updates the AuthorizationPolicy model to Istio 1.5.
It's not rebased with master yet but I think it's in a stable state to start testing it.
It requires UI PR https://github.com/kiali/kiali-ui/pull/1747
> Update AuthorizationPolicy model

- handlers/graph.go
resolve a typo in graph.go comments
No issue
- Is your change introducing backwards incompatible changes? Yes
If so, please also update README.adoc
> resolve a typo in graph.go comments

- jaeger/spans.go
Fixes https://github.com/kiali/kiali/issues/2702
> Decrease some logs level while fetching spans

- hack/istio/install-sm11.sh
avoids a race condition - we need to wait for the servicemesh webhook
> [hack] wait for service mesh webhook before creating SMCP

- business/istio_config.go
- business/istio_validations.go
- handlers/istio_config.go
- kubernetes/client.go
- kubernetes/istio_details_service.go
- kubernetes/kubetest/mock.go
- kubernetes/types.go
- models/istio_config.go
- models/peer_authentication.go
- swagger.json
Adding PeerAuthentication to IstioConfig section.
Needs https://github.com/kiali/kiali/pull/2738 before MERGE!
Part of #2520 
Backend: https://github.com/kiali/kiali-ui/pull/1774
> Adding PeerAuthentication to IstioConfig section

- business/istio_config.go
- business/istio_validations.go
- handlers/istio_config.go
- kubernetes/client.go
- kubernetes/istio_details_service.go
- kubernetes/kubetest/mock.go
- kubernetes/types.go
- models/authorization_policy.go
- models/istio_config.go
- models/peer_authentication.go
- models/request_authentication.go
- models/workload_entry.go
- swagger.json
This PRs adds WorkloadEntry and RequestAuthentication CRD into Kiali backend.
It's related to issues:
https://github.com/kiali/kiali/issues/2226
https://github.com/kiali/kiali/issues/2737
UI counterpart:
https://github.com/kiali/kiali-ui/pull/1778
> Add WorkloadEntry and RequestAuthentication for Istio 1.6

- hack/istio/install-istio-via-istioctl.sh
This also avoids a crash in the current istio dev build.
> [hack] istio 1.6 has new options

- business/apps.go
- business/apps_test.go
When a duplicate is found, it must just be ignored, not erase the previous values
Adding some unit tests
Fixes https://github.com/kiali/kiali/issues/2670
> Fix apps labels being incomplete when duplicates are found

- server/server.go
- server/server_test.go
fixes: https://github.com/kiali/kiali/issues/2770
> server should not allow TLS 1.1 or lower

- .travis.yml
- Makefile
>  require go 1.14.1 minimum

- .travis.yml
- Makefile
fixes #2779
backport of https://github.com/kiali/kiali/pull/2780
> [v1.15] require go 1.14.1 minimum

- .travis.yml
fixes: https://github.com/kiali/kiali/issues/2602
> encrypt IRC server/room to avoid spam from forks

- hack/crc-openshift.sh
This also adds some more information in the status output - uptime, memory usage (via free), and cpu usage (via top).
> [hack] move to CRC 0.10.0 / OpenShift 4.4

- hack/crc-openshift.sh
There is an odd race condition that this PR is trying to fight - it doesn't seem like you can add cluster roles to users until that user is ready. Doing it anytime before and it puts the user in an unusable state from then after.
> [hack] wait for user to be created before assigning cluster-admin role

- tests/e2e/tests/test_api_methods.py
- tests/e2e/tests/test_kiali_istio_endpoint.py
- tests/e2e/tests/test_kiali_urls.py
Test this modified E2E test cases against the latest Istio- 1.6 V
> Modified E2E Test Cases

- business/istio_validations.go
Cherry-pick of https://github.com/kiali/kiali/pull/2813
> v1.18 backport - Allow Policies and MeshPolicies still be shown

- business/checkers/destinationrules/disabled_namespacewide_mtls_checker.go
- business/checkers/destinationrules/disabled_namespacewide_mtls_checker_test.go
Cherry-pick of https://github.com/kiali/kiali/pull/2814
> v1.18 - backport - Disabled namespace validations

- business/istio_config.go
Part of https://github.com/kiali/kiali/issues/2797
UI counterpart: https://github.com/kiali/kiali-ui/pull/1804
> Updates IstioConfig with {Peer,Request}Authentication

- business/istio_config.go
Backport of https://github.com/kiali/kiali/issues/2797 into v1.18 branch.
> [v1.18] Updates IstioConfig with {Peer,Request}Authentication

- make/Makefile.cluster.mk
This new make code will help users that have a cluster that was not created by our hack scripts. You need to remember to expose the image registry in order to use the cluster-push targets - this new make code will do that.
This PR also adds new details reported by the cluster-status target.
> expose the image registry if it has not yet been done in the cluster

- make/Makefile.molecule.mk
fixes: https://github.com/kiali/kiali/issues/2849
> changes to run molecule tests on minikube

- tests/e2e/tests/test_api_methods.py
Test this modified E2E test cases against Istio - 1.6 V
> Adding new test cases to "api_methods"

- hack/istio/install-travel-agency-demo.sh
- hack/jwt-decode.sh
- hack/jwt-encode.sh
1. hack/istio/install-travel-agency-demo.sh
* Another microservice demo with added benefit of a couple defined operations in telemetry.
2. hack/jwt-[en,de]code.sh
* Two scripts that let us test passing in and examining JWT tokens. Useful to make sure hacking JWT tokens is not possible. Also useful to pass in when testing Kiali APIs as authenticated users.
I used these hack scripts for several things. First to confirm the correctness of our new OpenID integration. Also the demo let's us test the graph as well as producing telemetry with classified metric data (the operation ID stuff).
> [hack] some scripts we can use for testing

- .travis.yml
fixes https://github.com/kiali/kiali/issues/2834
> travis: do not require arm64 builds

- hack/jwt-encode.sh
1. By default, get the true signing key from the default location. You can still override this via -k option.
2. Run the decode script from the same location where this script is - don't assume it is in ".".
> [hack] make the jwt-encode easier to use.

- business/dashboards.go
- business/dashboards_test.go
- prometheus/metrics_definitions.go
- prometheus/prometheustest/client_test.go
Related to https://github.com/kiali/kiali/issues/2897
Fix / add tests
> Add rq/rs throughput in metrics page

- business/checkers/destinationrules/disabled_meshwide_mtls_checker_test.go
- business/checkers/peerauthentications/disabled_meshwide_checker_test.go
- business/checkers/peerauthentications/disabled_namespacewide_checker_test.go
- business/checkers/virtual_service_checker.go
- business/checkers/virtual_services/subset_presence_checker.go
- business/checkers/virtual_services/subset_presence_checker_test.go
- kubernetes/host.go
- tests/data/validations/test_asserter.go
- tests/data/validations/virtualservices/subset-presence-matching-subsets-1.yaml
- tests/data/validations/virtualservices/subset-presence-matching-subsets-2.yaml
- tests/data/validations/virtualservices/subset-presence-matching-subsets-diff-ns-fqdn.yaml
- tests/data/validations/virtualservices/subset-presence-matching-subsets-diff-ns-half-fqdn.yaml
- tests/data/validations/virtualservices/subset-presence-matching-subsets-diff-ns.yaml
- tests/data/validations/virtualservices/subset-presence-matching-subsets-half-fqdn.yaml
- tests/data/validations/virtualservices/subset-presence-no-matching-subsets-1.yaml
- tests/data/validations/virtualservices/subset-presence-no-matching-subsets-2.yaml
- tests/data/validations/virtualservices/subset-presence-no-matching-subsets-3.yaml
- tests/data/validations/virtualservices/subset-presence-service-entry-invalid.yaml
- tests/data/validations/virtualservices/subset-presence-service-entry.yaml
Fixes https://github.com/kiali/kiali/issues/2918
It also move previous tests to yaml scenarios. Easing the task to test.
> Allow ServiceEntries to KIA1107 validation

- hack/run-molecule-tests.sh
This will help with https://github.com/kiali/kiali/issues/2591
> a script that can be used to run the molecule tests

- deploy/jenkins-ci/Jenkinsfile
- deploy/jenkins-ci/Makefile.site.jenkins
- deploy/jenkins-ci/jenkins_ref/jobs/kiali-release/config.xml
Needs major testing, but it works for me.
> Prepare CI for releasing the website

- handlers/authentication.go
State parameter is a recommended parameter in the OpenId Spec. Despite just "recommended", some IdPs are _requiring_ it. So, adding `state` parameter for better compatibility.
Fixes kiali/kiali#2933
> Add `state` parameter when requesting autorization to OpenId IdP

- doc.go
- routing/routes.go
- swagger.json
Fixes https://github.com/kiali/kiali/issues/2970
Frontend PR: https://github.com/kiali/kiali-ui/pull/1844
> Remove namespace/service path params for single trace

- tests/e2e/tests/test_api_methods.py
- tests/e2e/tests/test_kiali_service_endpoint.py
Test this E2E against  Istio - 1.6.5 Version
> E2E - Fix Service End Point test 

- handlers/authentication.go
Closes #2954
Fix a problem where some authentication providers (such as Okta) do not provide an expiration date for the token. It is optional on the spec, so we make it optional here as well with a value of **1 day**.
> Make expires in optional for OpenId authentication

- graph/telemetry/istio/appender/dead_node.go
- graph/telemetry/istio/appender/dead_node_test.go
Because dead node removal can then make other nodes eligible we now iterate until no nodes need to be removed.
Fixes https://github.com/kiali/kiali/issues/2982
This isn't easy to test unless you are suffering from the issue.  But I have added new test code to make sure the use case is handled.  So, I think we just need a visual pass of the code and a regression test from QE to ensure that all of the expected graph nodes always show up.
> Ensure removal of leaf service nodes with no incoming traffic

- README.adoc
- deploy/jenkins-ci/Makefile.operator.jenkins
- hack/run-molecule-tests.sh
- make/Makefile.cluster.mk
- make/Makefile.operator.mk
This goes with PR https://github.com/kiali/kiali-operator/pull/93
> PoC: changes to go with the introduction of helm

- hack/istio/install-istio-via-istioctl.sh
Related to Epic https://github.com/kiali/kiali/issues/3052
> Update install-istio-via-istiocl hack script for istio 1.7

- hack/istio/install-travel-agency-demo.sh
- proxy version matches updated
- stats-filter patch update to add custom attribute
- added new required @type inlining for attribute matching JSON
- vip/standard user header changed to new/registered for cars/hotels reqs
- path matching made more flexible for travel reqs
Related to Epic #3052
> Update request_operation support to Istio 1.7 and Travel 2.0

- go.mod
- go.sum
- swagger.json
Related to https://github.com/kiali/kiali-ui/pull/1872 / #3047
> Bump k-charted v0.6.1

- .gitignore
- README.adoc
- hack/run-molecule-tests.sh
- make/Makefile.helm.mk
fixes: https://github.com/kiali/kiali/issues/3097
> expect the helm-charts as a peer to the operator directory always

- deploy/jenkins-ci/Jenkinsfile
- deploy/jenkins-ci/Makefile.helm.jenkins
- deploy/jenkins-ci/README.md
- deploy/jenkins-ci/jenkins_ref/jobs/kiali-release/config.xml
fixes: https://github.com/kiali/kiali/issues/3093
> jenkins build for helm charts

- hack/istio/install-istio-via-istioctl.sh
You can optionally tell the hack script what addons to install. Default is "prometheus grafana jaeger" But you can pass any combination of `grafana`, `jaeger`, and `kiali`.  Note that "prometheus" will always be installed so you do not have to explicitly mention it in the `-a` option:
This will install all addons:
```
install-istio-via-istioctl.sh -a "grafana jaeger kiali"
```
This will install nothing but prometheus:
```
install-istio-via-istioctl.sh -a ""
```
Note: when uninstalling, it will attempt to uninstall everything (since you are destroying Istio, all components must go).
This is something @FilipB asked for.
> [hack] be able to tell the hack script what istio addons to install

- hack/istio/install-travel-agency-demo.sh
this supports deploying  on OpenShift
> [hack] deploy travel demo using the new kiali demos repo

- business/namespaces.go
Fixes https://github.com/kiali/kiali/issues/3119
> Use Namespace resources for updates in all scenarios

- tests/e2e/tests/test_api_methods.py
- tests/e2e/tests/test_kiali_urls.py
Test this E2E against Istio - 1.7.0-beta.2 Version
> E2E - Fix ThreeScale test case and Jaeger URL

- config/config.go
- handlers/config.go
- models/workload.go
- swagger.json
Required for https://github.com/kiali/kiali/issues/3125 and https://github.com/kiali/kiali-ui/pull/1886
> Changes for auto-injection workload annotations

- business/istio_status.go
Fixes https://github.com/kiali/kiali/issues/3139
Note, that Istio Status is a perf operation, so using cache is something reasonable.
Cache is enabled by default in all namespaces:
https://github.com/kiali/kiali-operator/blob/master/roles/default/kiali-deploy/defaults/main.yml#L188
In the cornercase that the user has an explicit disabled cache, it will show a warning in Kiali log and it will query the Istio deployments with the user's token.
> Use cache for fetching Istio Status deployments

- business/istio_status.go
Fixes https://github.com/kiali/kiali/issues/3110
I've run the travis job 4 times, no race found. In case the race happens again, let's reopen the base issue.
> Travis test-race fix approach

- business/jaeger.go
- business/services.go
- doc.go
- handlers/jaeger.go
- jaeger/client.go
- jaeger/spans.go
- jaeger/traces.go
- jaeger/types.go
- jaeger/util.go
- routing/routes.go
- swagger.json
- tests/e2e/tests/test_api_methods.py
- tests/e2e/tests/test_kiali_service_endpoint.py
Fixes https://github.com/kiali/kiali/issues/3071
- New server endpoint
- New function to get app name for a service
- Filter app traces for service based on operation name in spans
- Update swagger
Frontend PR: https://github.com/kiali/kiali-ui/pull/1905
> Fetch traces for service

- business/jaeger.go
- business/workloads.go
- doc.go
- handlers/jaeger.go
- jaeger/client.go
- jaeger/traces.go
- jaeger/types.go
- routing/routes.go
- swagger.json
Searches traces of a given workload by first searching traces for the whole app, then narrowing down to workload based on envoy tags
Fixes https://github.com/kiali/kiali/issues/2710
Frontend PR: https://github.com/kiali/kiali-ui/pull/1910
> Implement workload-based traces

- graph/config/cytoscape/cytoscape.go
- graph/meta.go
- graph/telemetry/istio/appender/security_policy.go
- graph/telemetry/istio/appender/security_policy_test.go
- swagger.json
@jshaughn: I've started to add the discussed changes for https://github.com/kiali/kiali/issues/2924 into the security appender.
I think these changes make sense but perhaps I'm less familiar with the structure.
Feel free to comment.
Note: it's not yet finished, tests and other checks are missing.
> Add principals into security appender

- business/iter8.go
- handlers/iter8.go
- kubernetes/iter8.go
- kubernetes/kubetest/mock_iter8.go
- kubernetes/types.go
- models/iter8.go
- routing/routes.go
- swagger.json
Support Iter8 v1.0.0  (Documentation - https://iter8.tools/)
Require Kiali-UI PR (https://github.com/kiali/kiali-ui/pull/1911)
issue #2007 
Yes, Will not support Iter8 v0.2.x or earlier
_describe the changes if appropriate_
Change of the Experiment CRD in Iter8 v1.0.0 
https://iter8.tools/
Yes, the UI will change
> Support Iter8-v1.0.0

- models/authorization_policy.go
Relates to https://github.com/kiali/kiali/issues/2695
Requires UI PR.
> Allow empty values in AuthorizationPolicy model

- models/authorization_policy.go
> [v1.24] fix authorization policy

- handlers/authentication.go
fixes: https://github.com/kiali/kiali/issues/3248
backport PR: https://github.com/kiali/kiali/pull/3250
> fix panic in openid check

- handlers/authentication.go
fixes: https://github.com/kiali/kiali/issues/3248
backport of: https://github.com/kiali/kiali/pull/3249
(cherry picked from commit d0751d9fe6aa65e5ce61ccd4061910c4b6582c97)
> [v1.24] fix panic in openid check

- README.adoc
fixes: https://github.com/kiali/kiali/issues/3266
> fix helm chart repo location in readme

- make/Makefile.cluster.mk
Never saw the need to do this until just now - need to make sure image registry is Managed. This also removes some hardcoded 'oc' commands that accidentally came in during past commits
> update make targets to work better with OpenShift image registry

- business/dashboards.go
- config/config.go
- handlers/apps.go
Fixes https://github.com/kiali/kiali/issues/3269
Operator PR: https://github.com/kiali/kiali-operator/pull/153
> Custom dashboards: implement "enabled" config flag

- business/iter8.go
- kubernetes/iter8.go
- models/iter8.go
- swagger.json
Support Iter8 v1.0.0-rc3 feature enhancement: Match Rules
#2007 
Note: need  https://github.com/kiali/kiali-ui/pull/1955 to test out the capabilities
> Add Iter8 Match Rules Support

- business/dashboards.go
- config/config.go
- handlers/apps.go
This is a cherry-pick of PR https://github.com/kiali/kiali/pull/3283
fixes: https://github.com/kiali/kiali/issues/3301
> [v1.24] Custom dashboards: implement "enabled" config flag

- README.adoc
I have added npm as a requirement for building Kiali in the readme.
This fixes #1375 
Thanks,
Swapnadeep
> Added NPM requirement in the readme prerequisites

- business/checkers/gateways/multi_match_checker.go
- business/checkers/gateways/multi_match_checker_test.go
fixes https://github.com/kiali/kiali/issues/3219
The warning appears when two gateways share the same host, port and gateway labels.
We consider that if two gateways are pointing to the same gateway with different labels, then users should unify the criteria by using the same selector in both gateways.
Testing scenario: https://github.com/xeviknal/istio-lab/blob/master/kiali-3219/gateways.yaml
> Gateways can share host+port if they point to different ingress gws

- models/iter8.go
Fixes https://github.com/kiali/kiali/issues/3274
Now created/started/ended at have same format used in Kiali.
> Fix Iter8 time format

- business/health.go
- business/proxy_status.go
- business/workloads.go
Fixes https://github.com/kiali/kiali/issues/3318
I'm sure this is going to fix a flawn that is happening in your scenario.
Added an extra warning for a hidden error that perhaps may show up something extra (i.e. not access to the istiod for some reason).
> Fix missing ProxyStatus check

- config/config.go
- kiali.go
Write will no longer be required env.js
https://github.com/kiali/kiali-ui/pull/1882
https://github.com/kiali/kiali-ui/pull/1882
- No, Fully compatible
_describe the changes if appropriate_
If so, please also update README.adoc
> Support setting history mode by parameter 

- business/checkers/destinationrules/no_dest_checker.go
- business/checkers/destinationrules/no_dest_checker_test.go
- models/istio_validation.go
- tests/data/destination_rules_data.go
Needed for https://github.com/kiali/kiali/issues/3336
> Add No Labels checker for DR

- handlers/utils.go
> delete unused variable

- hack/ci-openshift-molecule-tests.sh
run "--help" for description of this tool. Can be used as a cron job to periodically run the molecule tests on an existing openshift cluster
> new hack script for ci when testing with openshift

- tests/e2e/tests/test_api_methods.py
> New Trace methods

- models/pod.go
- swagger.json
part-of  https://github.com/kiali/kiali/issues/1399
> Capture more info about the Pod phase/status

- hack/istio/install-istio-via-istioctl.sh
This rips out some old stuff for 1.4 which we don't care about anymore.
This also changes the --addons so it no longer always adds prometheus - someone asked if it was possible to not install Prometheus and there was no way to do so before. Now there is.
Also did some other changes due to 1.8.
> [hack] get the install istio script to work with 1.8.

- business/iter8.go
- models/iter8.go
- swagger.json
1. adding MatchRule section in experiment detail json return
2. fix misspell matchrule (marchrule->matchrule)
> Adding MatchRule to Iter8 Experiment Detail JSON return

- hack/istio/install-sm2.sh
hack script to install Red Hat ServiceMesh 2.0
> [hack] install SM 2.0

- business/openshift_oauth.go
Also, ensure keep-alive connections are closed. And make some error messaging more distinct.
Backport for #2905
> [1.24] Add timeout to http client used with OAuth API

- business/openshift_oauth.go
Also, ensure keep-alive connections are closed.  And make some error messaging more distinct.
Backport for kiali#2905
> [1.12] Add timeout to http client used with OAuth API

- Makefile
- hack/k8s-minikube.sh
- hack/purge-kiali-from-cluster.sh
- make/Makefile.operator.mk
part of fix to https://github.com/kiali/kiali/issues/3411 that added common k8s labels.
backport: https://github.com/kiali/kiali/pull/3416
> update makefile and hack scripts to use the new k8s labels

- handlers/authentication.go
Function checkOpenIdSession should skip token validation via fetching namespaces when RBAC is OFF. It's assumed the token will be rejected by the cluster. Also, it's assumed that the Kiali Service Account (which is used in place) has enough privileges.
Related #3410
> [v1.26] [openid] Fix token validation when RBAC is off

- handlers/authentication.go
Function checkOpenIdSession should skip token validation via fetching namespaces. It's assumed the token will be rejected by the cluster. Also, it's assumed that the Kiali Service Account (which is used in place) has enough privileges.
Fixes #3410
Backport to v1.26 is #3414 .
> [openid] Fix token validation when RBAC is off

- hack/istio/install-sm2.sh
The docs here are incomplete: https://docs.openshift.com/container-platform/4.6/service_mesh/v2x/installing-ossm.html#ossm-operatorhub-remove_installing-ossm
Need to delete a couple other things, too.
> [hack] clean up some more things hanging around after uninstalling SM 2.x.

- hack/istio/install-istio-via-istioctl.sh
- make/Makefile.cluster.mk
* Have make cluster-status tell you what version of istio you have installed (if any)
* Also have the istio hack script delete istio-system ns when uninstalling.
> [hack] Some changes to dev tools (make and hack script)

- config/config.go
- util/httputil/http_util.go
- util/httputil/http_util_test.go
> Add support to setting up the web port in the configuration

- server/metrics_server.go
- server/server.go
- status/versions.go
- util/httputil/http_util.go
- Add http client timeout to istio version call
- Add server 30s timeouts
Fixes https://github.com/kiali/kiali/issues/3406
> Add client and server timeouts

- jaeger/client.go
- prometheus/client.go
- util/httputil/http_util.go
Closes #3436.
Adds timeouts to prometheus. As a bonus, also sets some more strict timeouts and add timeouts to Jaeger :)
> Add timeouts to prometheus and jaeger calls

- hack/ci-openshift-molecule-tests.sh
This may be needed by the QE team.
cc @mattmahoneyrh
> [hack] Allow user to dictate what protocol (git or https) to use when git cloning repos.

- business/services.go
Fixes https://github.com/kiali/kiali/issues/3497
> Fix regression on Endpoints cache

- deploy/jenkins-ci/Jenkinsfile
- deploy/jenkins-ci/Makefile
- deploy/jenkins-ci/Makefile.operator.jenkins
- make/Makefile.container.mk
Signed-off-by: Morlay <morlay.null@gmail.com>
* publish multi-arch backend and operator images to quay.io
fix #3463
> publish multi-arch backend and operator images to quay.io

- hack/istio/install-istio-via-istioctl.sh
See: https://istio.io/latest/blog/2020/docker-rate-limit/#mitigations
> [hack] when installing istio, do not pull images from docker.io anymore

- business/jaeger.go
- go.sum
- handlers/jaeger.go
- jaeger/util.go
- models/tracing.go
Fixes https://github.com/kiali/kiali/issues/3311
> Traces fetching: new "split and join" strategy

- business/dashboards.go
- business/dashboards_test.go
- business/grafana.go
- business/grafana_test.go
- handlers/dashboards.go
- handlers/grafana.go
- handlers/utils.go
- swagger.json
Fixes https://github.com/kiali/kiali/issues/3305
Also there was some duplicated code that I left after the k-charted
merge, in handlers/grafana.go ; it's now removed, and some pieces moved
to business package like other grafana stuff.
> Fix grafana links when configured with absolute URLs

- .github/workflows/kiali-ci.yml
This PR runs the CI tests on each push or PR. Effectively doing what Travis CI is doing today but with Github Actions instead.
fixes: https://github.com/kiali/kiali/issues/3502
Yes
> Add Github Actions CI to Kiali repo

- business/istio_status.go
- business/istio_status_test.go
- kubernetes/istio.go
cherry-pick https://github.com/kiali/kiali/commit/ce6e0ae9708a39b233914d8ac6ebb79d79649527
cherry-pick https://github.com/kiali/kiali/pull/3544
> [1.28] Use the hardcoded app label (#3544)

- hack/purge-kiali-from-cluster.sh
- make/Makefile.operator.mk
part of https://github.com/kiali/kiali/issues/3533
* kiali/kiali PR: https://github.com/kiali/kiali/pull/3542
* operator PR: https://github.com/kiali/kiali-operator/pull/230
* helm-charts PR: https://github.com/kiali/helm-charts/pull/26
> purge HPAs

- hack/k8s-minikube.sh
fixes https://github.com/kiali/kiali/issues/3541
> [hack] add role/binding to the Dex admin@example.com user so the openid molecule test passes

- .github/ISSUE_TEMPLATE/bug_report.md
Adding the Kiali discussion link into the bug template
> Add discussion to bug template

- handlers/authentication.go
fixes: https://github.com/kiali/kiali/issues/3591
> fix openshift auth strategy

- business/istio_config.go
- handlers/istio_config.go
fixing https://github.com/kiali/kiali/issues/3598
> Fixing a typo on GeIstioConfigPermissions method

- business/mesh.go
After merging https://github.com/kiali/kiali/pull/3603, the `multi-cluster` branch requires a small fix to build correctly.
Related kiali/kiali#3592
> Fix multi-cluster build

- hack/run-molecule-tests.sh
- make/Makefile.molecule.mk
fixes: https://github.com/kiali/kiali/issues/3608
> changes to support openshift-auth-test molecule test

- hack/istio/install-travel-agency-demo.sh
- helps follow tutorial on openshift
> add --enable-injection option to travel hack script

- handlers/authentication.go
I came across this looking at https://github.com/kiali/kiali/issues/3595. But since these are separate bugs, I'm committing as a separate PR (although this kinda addressed 3595 because that issue also reports the warning message with the bad logging). This fixes the logging in places where the "f" form of the the logging messages either should have been used or was used incorrectly.
> fix logging calls

- hack/jwt-decode.sh
- hack/jwt-encode.sh
I was using these utilities to debug some auth issue and needed to fix them up to work with OpenShift
> [hack] fix up the jwt hack utilities so they work

- graph/telemetry/istio/istio.go
Backport for https://github.com/kiali/kiali/issues/3644
> [V1.29] Fix issue with operation node detail graphs

- business/layer.go
- business/proxy_status.go
- kubernetes/host.go
- models/config_dump.go
Adding formatted information about the services listed in Clusters and Routes.
Needs https://github.com/kiali/kiali-ui/pull/2063
> Adding host information to clusters and routes

- business/openshift_oauth.go
perform a logout correctly by converting the access token to the corresponding OAuthAccessToken name and deleting it.
Molecule test PR: https://github.com/kiali/kiali-operator/pull/242
backport 1.24 PR: https://github.com/kiali/kiali/pull/3661
backport 1.12 PR: https://github.com/kiali/kiali/pull/3662
fixes: https://github.com/kiali/kiali/issues/3595
This PR uses the same mechanism that the OpenShift Console itself uses:
https://github.com/openshift/console/blob/79c6d1118674cb1a2c8dcfcfd1797f25492e699b/pkg/server/server.go#L581-L593
https://github.com/openshift/console/blob/79c6d1118674cb1a2c8dcfcfd1797f25492e699b/pkg/server/server.go#L607-L613
https://github.com/openshift/console/blob/79c6d1118674cb1a2c8dcfcfd1797f25492e699b/pkg/server/server.go#L228 …
> fix logout

- business/openshift_oauth.go
backport of https://github.com/kiali/kiali/pull/3655
part of: https://github.com/kiali/kiali/issues/3595
> [v1.24] fix logout

- business/openshift_oauth.go
backport of https://github.com/kiali/kiali/pull/3655
part of: https://github.com/kiali/kiali/issues/3595
> [v1.12] fix logout

- handlers/authentication.go
delete the token cookies so the client never uses them again
fixes: https://github.com/kiali/kiali/issues/3643
> whenever the server detects the client is unauthorized, delete the token cookies

- handlers/authentication.go
fixes: https://github.com/kiali/kiali/issues/3643
(cherry picked from commit 4eab4ce0a7f82343df4ec6655570db3eac4a01cc)
> [v1.24] whenever the server detects the client is unauthorized, delete the token cookies

- handlers/authentication.go
fixes: https://github.com/kiali/kiali/issues/3643
(cherry picked from commit 4eab4ce0a7f82343df4ec6655570db3eac4a01cc)
> [v1.29] whenever the server detects the client is unauthorized, delete the token cookies

- config/config.go
Part of https://github.com/kiali/kiali/issues/3371
Requires Operator PR: https://github.com/kiali/kiali-operator/pull/241
Requires UI PR: https://github.com/kiali/kiali-ui/pull/2081
> Server config support UI Defaults

- business/health.go
- business/health_test.go
- business/services.go
- config/config.go
- doc.go
- graph/config/cytoscape/cytoscape.go
- graph/meta.go
- graph/telemetry/istio/appender/appender.go
- graph/telemetry/istio/appender/health_config.go
- graph/telemetry/istio/appender/health_config_test.go
- handlers/health_test.go
- handlers/services.go
- kubernetes/client.go
- kubernetes/kubernetes.go
- kubernetes/kubetest/mock_kubernetes.go
- models/health.go
- models/health_config.go
- models/service.go
- models/workload.go
- routing/routes.go
- swagger.json
Fix https://github.com/kiali/kiali/issues/3332
Fix https://github.com/kiali/kiali/issues/3435
> Allow custom health configuration to be deployed as annotations

- deploy/jenkins-ci/Jenkinsfile
> Allow releasing helm charts on patch releases

- tests/e2e/tests/test_api_methods.py
- tests/e2e/tests/test_kiali_service_endpoint.py
- tests/e2e/tests/test_kiali_traces.py
Query Parameter is added to spans and trace API.
Validating with Istio-v1..9.0
> Fixing_Testcase_Failures:E2E

- .github/workflows/snyk.yml
The official Snyk action didn't work. Using something that is more close to what was being done in Travis. This is better, because docker is not involved.
Related #3481
> Fix Snyk GitHub action

- business/checkers/authorization/mtls_enabled_checker.go
- business/checkers/authorization/mtls_enabled_checker_test.go
- kubernetes/istio.go
- tests/data/validations/authorization/mtls_enabled_checker_18.yaml
- tests/data/validations/authorization/mtls_enabled_checker_19.yaml
- tests/data/validations/authorization/mtls_enabled_checker_20.yaml
- tests/data/validations/authorization/mtls_enabled_checker_21.yaml
- tests/data/validations/authorization/mtls_enabled_checker_22.yaml
- util/mtls/status.go
fixes https://github.com/kiali/kiali/issues/3697
mTLS can be specified at workload level. This validation didn't considered this scenario. it is considered now.
> KIA0105 - Checks mtls status at workload level

- business/workloads.go
- business/workloads_test.go
Fixes https://github.com/kiali/kiali/issues/3769
How to test:
- DaemonSet workloads shouldn't fail in Workload details.
> Fix cornercase in controllers from Pods

- hack/run-prometheus.sh
- make/Makefile.cluster.mk
- make/Makefile.container.mk
part of: https://github.com/kiali/kiali/issues/2983
> Changes necessary to move to Ansible Operator SDK 1.x

- hack/istio/install-istio-via-istioctl.sh
taking away this permission was wrong - we still need it.
> [hack] this is still needed - this perm is required in the control plane ns

- business/mesh.go
The annotation value will be passed to the front-end and this will make cross-linking possible.
Related front-end PR: https://github.com/kiali/kiali-ui/pull/2102
Related to kiali/kiali#3526
> Extract external-url annotation when discovering Kialis

- tests/e2e/tests/test_kiali_graph.py
New Graph test cases. Improved response validation
> E2E - Graph Test Cases

- tests/e2e/tests/test_kiali_node_detail_graph.py
Added new node details test cases.
> Node Details tests

- tests/e2e/tests/test_kiali_health.py
adding new health negative testcases
> E2E: Health Negative testcases

- tests/e2e/tests/test_kiali_metrics.py
> E2E - Metrics test cases

- tests/e2e/tests/test_kiali_health.py
Adding negative test cases for workload_health_deployment
> Adding negative tests cases for health:E2E

- hack/ci-openshift-molecule-tests.sh
- hack/run-molecule-tests.sh
also pass env vars to make using -e option since that's the way it should be done
> Pass dorp to run-molecule-tests.sh

- README.adoc
- config/config.go
> fix spelling error in README doc

- Makefile
- make/Makefile.operator.mk
OSSM-438
- https://github.com/kiali/kiali-operator/pull/278
- https://github.com/kiali/helm-charts/pull/59
> the way our make targets work, we need to allow ad-hoc kiali namespaces

- tests/e2e/tests/test_api_methods.py
- tests/e2e/tests/test_kiali_health.py
- tests/e2e/tests/test_kiali_logs.py
- tests/e2e/tests/test_kiali_metrics.py
- tests/e2e/tests/test_kiali_node_detail_graph.py
- tests/e2e/tests/test_kiali_urls.py
- tests/e2e/utils/common_utils.py
> E2E - Added new logs test cases

- business/test_util.go
- business/workloads.go
- business/workloads_test.go
- go.mod
- go.sum
- handlers/workloads.go
Part of Epic #3499 
UI PR: https://github.com/kiali/kiali-ui/pull/2104
This adds backend support for access log parsing.
> Enhanced logs view with access log detail

- hack/kiali-port-forward.sh
useful for multicluster setups
> be able to port forward multiple kiali servers

- graph/telemetry/istio/appender/sidecars_check.go
- graph/telemetry/istio/appender/sidecars_check_test.go
Fixes https://github.com/kiali/kiali/issues/3896
> sidecar graph appender, fix problem when verifying node's namespace is accessible

- models/istio_validation.go
fix https://github.com/kiali/kiali/issues/3890
> Cleanup - remove reference to an ServiceMesh CRD

- hack/ci-minikube-molecule-tests.sh
- hack/istio/multicluster/env.sh
- hack/k8s-minikube.sh
- hack/run-molecule-tests.sh
- hack/run-prometheus.sh
some changes to make it easier to use the hack scripts for some environments.
> better support for machines with podman

- handlers/authentication.go
Although the OpenIdCodeFlowHandler was terminating using the "RespondWithError" or "RespondWithDetailedError" helper functions, these functions return a JSON under the assuption that the Kiali UI did the request.
However, the OpenIdCodeFlowHandler is not called by the Kiali UI, but by the browser directly. This was causing a bad experience, because the user would see the returned JSON in the browser window.
These changes change this behavior: errors are logged and, additionally, a redirection to boot the Kiali UI is done. The redirection includes an "openid_error" parameter to let know the UI that there was an error and show the message in the login page.
Related front-end PR (required to properly show the returned message in login form): https://github.com/kiali/kiali-ui/pull/2131
Fixes …
> Terminate gracefully on errors in OpenID's authorization code flow

- kubernetes/cache/cache.go
Fixes https://github.com/kiali/kiali/issues/3964
@juliantaylor I've prepared a first fix that I'd like if you have a chance to test in your environment.
I'm still working on the case as I don't consider it closed until we can check properly.
Basically this fix will protect the creation of new namespaces at some scale.
This issues has not been detected before in the test-race and in our testing, I'm ccing @FilipB to help me to test this in our perf tests as well to see if we have any chance to reproduce.
Again, I can't simulate in an easy way a high level of kubernetes informers to create a mockup of the same situation, that will be done in a future step, but I'm curious if with this protection, it will prevent your environment to fail.
Thanks !
> Use RW for cache lock

- business/istio_config.go
- business/services.go
Fixes https://github.com/kiali/kiali/issues/3966
Kiali performs a "Get permissions" query to enable/disable write features (in the UI, to render actions or create/update/delete buttons).
This query was doing some extra calls, also now that the list of verbs are explicit in the operator config, one of the calls was wrong and introduced a potential performance penalty.
This PR reduces the calls needed for the "get permissions" logic.
How to test:
- Deploy Kiali in a the default scenario and check no regressions are introduced.
- Deploy Kiali in "view_only_mode" [1] and check no regressions are introduced.
- No suspicious error/warning in Kiali logs.
[1] https://kiali.io/documentation/latest/installation-guide/#_reducing_permissions_in_openshift
> Fix get permissions queries

- graph/telemetry/istio/appender/service_entry.go
- graph/telemetry/istio/appender/service_entry_test.go
- graph/types.go
- kiali_api.md
- swagger.json
This is the potential server-side PR for the issue.
Requires UI PR:  TBD
PartOf #3798
> Add the ServiceEntry definition namespace to the SEInfo returned to client

- business/layer.go
- business/mesh.go
- business/mesh_test.go
- jaeger/http_client.go
- kubernetes/filters.go
- kubernetes/kubernetes.go
- kubernetes/kubetest/mock_kubernetes.go
> Reduce number of API calls to discover remote Kialis (#3970)

- hack/istio/multicluster/deploy-kiali.sh
- hack/istio/multicluster/env.sh
fixes: https://github.com/kiali/kiali/issues/4016
> [hack] be able to set web_fqdn and web_schema for the 2 kiali instances

- business/dashboards.go
- models/dashboards.go
Relates to https://github.com/kiali/kiali/issues/3948
> Research Metrics tab main layout

- tests/e2e/tests/test_kiali_graph_badges.py
I have added service graph badges
> E2E: service_graph_badges

- business/dashboards.go
- config/dashboards/dashboards.go
- config/dashboards/dashboards_config_test.go
Followup work for https://github.com/kiali/kiali/issues/3948
Frontend PR https://github.com/kiali/kiali-ui/pull/2176
> Metrics tab layout - followup

- business/iter8.go
- config/config.go
- graph/api/api_test.go
- handlers/config.go
- kubernetes/types.go
fixes: https://github.com/kiali/kiali/issues/4109
> remove istio_component_namespaces config

- hack/ci-minikube-molecule-tests.sh
- hack/k8s-minikube.sh
We should be able to do this and get the operator to install via OLM subscription:
```
minikube addons enable olm --images "UpstreamCommunityOperators=operator-framework/upstream-community-operators:latest"
```
This operator PR is also needed: https://github.com/kiali/kiali-operator/pull/335
> [hack] be able to enable OLM in minikube

- make/Makefile.operator.mk
These are useful when installing the operator via OLM (one use case is when installing with OLM but want to install ad hoc images for testing)
The need arose for this when I was installing the operator via OLM and the allow ad hoc namespace and image features are disabled by default and thus prohibiting someone from running molecule tests or deploying local dev images. Now you just run things like `make operator-set-config-allow-ad-hoc-kiali-namespace` or `make operator-set-config-allow-ad-hoc-kiali-image` to allow this.
Another nice thing is this allows you to turn on the operator profiler - `make operator-set-config-ansible-profiler-on`
Here's the `make help` for the new targets:
```
operator-set-config-allow-ad-hoc-kiali-namespace   Tells the operator if it should allow Kiali CRs in an …
```
> provide some make targets to allow you to set operator feature settings easily

- config/config.go
- handlers/config.go
Fix for issue https://github.com/kiali/kiali/issues/3988
UI changes required: https://github.com/kiali/kiali-ui/pull/2184
> Added new config in Kiali CR for Istio upgrade scenario.

- business/apps.go
- business/apps_test.go
- business/dashboards.go
- business/dashboards_test.go
- business/workloads.go
- business/workloads_test.go
- config/dashboards/dashboards_config.go
- handlers/dashboards.go
- kiali_api.md
- models/dashboards.go
- models/namespace.go
- models/workload.go
- swagger.json
Backport of https://github.com/kiali/kiali/pull/4146
Please @jmazzitelli @prachiyadav could you take a look to this as well if something is missing ?
I've resolved a couple of conflicts and it may need some check if everything is working as expected in the v1.36 branch.
Thanks
> [v1.36] Fix regression in personalized CustomDashboards at namespace level

- business/dashboards.go
- config/dashboards/dashboards_config.go
- kiali_api.md
- models/dashboards.go
- swagger.json
Backport of https://github.com/kiali/kiali/pull/4171
> [v1.36] Support multiple rows in metrics dashboards

- config/dashboards/dashboards_config.go
- swagger.json
> [v1.36] Fix missing Grafana Workload and Service links

- hack/run-kiali.sh
This is trivial. But (1) the comments were wrong and (2) the pkill comment wouldn't work correctly.
> [hack] fix the comments in run-kiali.sh - had some wrong information

- routing/router.go
Cherry-pick of https://github.com/kiali/kiali/pull/4235
> [v1.36] Fix root URL not loading with URL parameters

- business/mesh.go
- graph/telemetry/istio/appender/aggregate_node_test.go
- graph/telemetry/istio/appender/dead_node.go
- graph/telemetry/istio/appender/dead_node_test.go
- graph/telemetry/istio/appender/idle_node.go
- graph/telemetry/istio/appender/idle_node_test.go
- graph/telemetry/istio/appender/istio_details_test.go
- graph/telemetry/istio/appender/response_time_test.go
- graph/telemetry/istio/appender/security_policy_test.go
- graph/telemetry/istio/appender/service_entry.go
- graph/telemetry/istio/appender/sidecars_check_test.go
- graph/telemetry/istio/appender/throughput_test.go
Cherry-pick of #4231 to `v1.36` branch
> [v1.36] Fix graph with spurious cluster boxes and a crash

- business/istio_validations.go
- prometheus/internalmetrics/internal_metrics.go
fixes: https://github.com/kiali/kiali/issues/4230
> add metric to track processing time for each individual checker

- business/istio_validations.go
- prometheus/internalmetrics/internal_metrics.go
cherry pick of https://github.com/kiali/kiali/pull/4248
> [v1.36] add metric to track processing time for each individual checker (#4248)

- hack/istio/install-istio-via-istioctl.sh
The openshift profile existed on istio 1.9 and 1.10 so we should be able to use this for those as well. But if something is wrong and it doesn't work with 1.9 and/or 1.10 on your machine, just pass in `-cp demo` to get back to the original way the script was working.
> [hack] support istio 1.11 and the openshift profile

- business/grafana_test.go
- config/config.go
backport of https://github.com/kiali/kiali/pull/4262
> [backport 1.38] Adding default grafana in_cluster_url

- business/mesh.go
When trying to discover remote clusters, some secrets are queried from the Istio namespace. If Kiali has got some reduced privileges, a warning message telling about forbidden permissions is repeatedly logged, which causes some unneeded noise in the logs.
This is detecting the forbidden response and replacing the warning-level message in the logs with a trace-level message, hopefully reducing the noise in the logs.
Fixes kiali/kiali#4147.
> Reduce logging related to clustering discovery

- business/mesh.go
- hack/istio/create-mesh-namespace.sh
- hack/istio/enable_maistra_deployment_injection.sh
- A general purpose hack script for adding namespaces
- A Maistra-specific hack script for enabling injection for deployments
> [hack] a couple of new, general purpose scripts

- hack/ci-kind-molecule-tests.sh
- hack/ci-minikube-molecule-tests.sh
- hack/ci-openshift-molecule-tests.sh
also, minikube CI script can now send irc message
> [hack] ci tests will now report the number of failed tests

- hack/crc-openshift.sh
This should help people that want an OpenShift cluster on their local machine. This still may not be enough to run a full Istio+Kiali+demo set up, but it should be able to at least provide a platform to run Istio if not also with Kiali.
> [hack] update CRC script so it can run the latest

- business/istio_config.go
- config/config.go
- handlers/config.go
Backport of #4273.
UI PR: [#2226](https://github.com/kiali/kiali-ui/pull/2226)
> [v1.36] Add viewOnlyMode property into config object (#4273)

- kiali_api.md
- models/workload.go
- status/status.go
- status/versions.go
- swagger.json
fixes: https://github.com/kiali/kiali/issues/4268
UI PR: https://github.com/kiali/kiali-ui/pull/2230
Operator PR: https://github.com/kiali/kiali-operator/pull/413
> when checking for sidecar injection, check the label as well as the annotation

- status/status.go
fixes: https://github.com/kiali/kiali/issues/4351
> avoid NPE - always make sure istio environment has been retrieved

- status/status.go
> [v1.40] avoid NPE - always make sure istio environment has been retrieved

- hack/ci-minikube-molecule-tests.sh
fixes: https://github.com/kiali/kiali/issues/4318
> spit out human-readable error if upload logs is true but the user did not provide a logs dir

- business/grafana.go
- business/istio_status.go
- config/config.go
- jaeger/client.go
- kubernetes/kubernetes.go
- prometheus/client.go
- status/versions.go
- util/httputil/http_util.go
fixes: https://github.com/kiali/kiali/issues/4323
operator PR: https://github.com/kiali/kiali-operator/pull/421
> send custom headers in prometheus requests

- config/config.go
- handlers/config.go
Fix https://github.com/kiali/kiali/issues/4303
PR operator : https://github.com/kiali/kiali-operator/pull/427
> Kiali Istio dashboards incompatible with thanos-query

- deploy/jenkins-ci/jenkins_ref/jobs/kiali-website-release/config.xml
> Update Jenkins config files for dev container

- hack/istio/enable_maistra_deployment_injection.sh
The patch adds an annotation instead of a label.
> Fix Maistra injection script

- deploy/jenkins-ci/Jenkinsfile
Also, remove reference to another job that is now unused/non-existent.
> Fix syntax error on Jenkinsfile

- business/layer.go
- jaeger/client.go
Fixes https://github.com/kiali/kiali/issues/4527
> Cache Jaeger client

- tests/e2e/tests/test_api_methods.py
Test_cases fixing with latest changes in the API
> E2E:fix_test_cases_error_codes

- hack/istio/install-istio-via-istioctl.sh
The optional --purge flag will remove all Istio resources,
including cluster-scoped resources that may be shared with other Istio control planes.
This helps to reuse a cluster as there should be no istio leftovers after uninstalling.
> Do complete purge of all istio resources when uninstalling

- business/apps.go
Based on a conversation https://github.com/kiali/kiali/pull/4535#issuecomment-989830113
> Fixed Istio Config links in App pages, Name/Namespace params swap.

- hack/k8s-minikube.sh
fixes: https://github.com/kiali/kiali/issues/4582
When this PR is merged, the molecule tests will fail until you also merge this PR: https://github.com/kiali/kiali-operator/pull/466
> [hack] update to the latest Dex version so we can run on newer minikube

- business/checkers/gateways/multi_match_checker.go
- business/checkers/gateways/multi_match_checker_test.go
Up until now, the duplicate Gateway Host only considered Ports and Selectors for separating the Comparison Spaces for Gateways. No special consideration was given for Hosts in the `namespace/host` Syntax (see [hosts in Gateway.spec.servers](https://istio.io/latest/docs/reference/config/networking/gateway/#Server) for a detailed description of this syntax). 
This PR explicitly checks the namespace of a Gateway Host in the duplicate check and thereby accomplishes two improvements:
* The duplicate check for a Gateway in namespace `test` with the host `./example.com` and the host `test/example.com` (in the same Port / Selector) is now correctly identified as duplicate host.
* The number of regex-based comparisons is greatly reduced for Gateways that expose one host …
> Fix and Optimize Gateway Host Duplicate check for hosts with target namespace

- config/config.go
Related to: https://github.com/kiali/kiali-operator/pull/452
> Add rank query to find defaults
