Makefile

```bash
$ make build
Cleaning...
Building...
GOOS=linux GOARCH=amd64 CGO_ENABLED=0  go build \
-o sws -ldflags "-X main.version=0.0.1.Final-SNAPSHOT -X main.commitHash=3793fa21e5f854019ba31010f3f61a8fa1754d0f"
$ make run
Running...
make: sws: Command not found
make: *** [run] Error 127
```
It looks like `-o` flag on `go build` generates the `sws` bin in same folder. So, `make run` doesn't find the bin.

Make run command output bin inside ${GOLANG}/bin for being coherent with readme

---

server/server.go
server/server_test.go
sws.go

~~This adds a convenience http client object useful to making http and https calls with basic or bearer token auth~~
This also tests that the API Server and Console endpoints are valid. Also tests https and auth.

Add http client and tests

---

Makefile

If we have not yet pulled down the UI from npm, "make docker" will do so.
Otherwise, the npm install is skipped.
If you want to pull down the UI again, just do a "make clean" and the docker
target will do the npm install again (e.g. "make clean docker")

make docker builds go faster in the normal repeat case

---

handlers/root.go
prometheus/client.go

- rename PrometheusClient to Client as using it as an imported type is
verbose:
f(c prometheus.PrometheusClient) changes to f(c prometheus.Client)
- Add function to just get the prom api in order to make calls that are not
[yet] formalized in this client.
- rename GetIncomeServices() to getSourceServices() as the original name
does not read well in English and "Source" is more in line with the
Istio Metric label terminology.
- Also, tweak function comment to be match convention of leading with
the name

Prometheus Client Tweaks

---

Makefile

Second part of #25 .
It adds a Makefile target called `docker-push` which push the local docker image to docker hub.
Docker image pushed is defined by the environment variables: `DOCKER_NAME`:`DOCKER_VERSION`
@jmazzitelli actually code is yours from comment in #25, haha :man_dancing:

Makefile target for pushing docker image to docker hub

---

.travis.yml
Makefile

I propose we do not do anything extra in the build target. I'm removing both clean and format as dependent targets on build for the following reasons:
1) format - we now have a pre-commit hook that will format the files for you on commit. Thus, there is no need to always format on build which is inefficient. The developer has options here - he can set up his IDE to always format on save (most devs do this) or they can "make format build" on the command line if they want to format during the build. By removing format dependency on build target, we don't force a format for EVERY build for EVERY developer.
2) clean - if we clean on every build, it deletes the UI code we installed in _output/npm. This has the detrimental effect of always forcing the user to download again (via npm install) …

don't do extra steps in build so things are faster in the normal case

---

hack/build-openshift.sh
hack/env-openshift.sh
hack/istio-install-openshift.sh

I still can't get prometheus to run successfully. Getting:
level=error
ts=2018-02-17T02:10:53.269935415Z
caller=main.go:323
msg="Opening storage failed"
err="mkdir data/: permission denied"

install istio into openshift

---

hack/build-openshift.sh
hack/istio-bookinfo-openshift.sh
hack/istio-install-openshift.sh

This PR fixes some of the errors I've got when trying to run oc+istio with the provided hack scripts.

Install script fixes

---

config/config.go
config/config_test.go
config/security/config_security.go
config/security/config_security_test.go
kubernetes/client.go
kubernetes/types.go
prometheus/client.go
routing/routes.go
server/server_test.go

- Vet: fix yaml tagging
(Go vet was reporting: struct field tag `,omitempty` not compatible with reflect.StructTag.Get: bad syntax for struct tag pair)
- Good practice: document all exported functions
- Good practice: mixedCaps https://golang.org/doc/effective_go.html#mixed-caps
- Good practice: use consistent case for initials
( https://github.com/golang/go/wiki/CodeReviewComments#initialisms )
PS: topic opened internally to discuss about code style

Fixing warnings / go vet

---

handlers/base.go
handlers/namespaces.go
handlers/root.go
handlers/services.go
kubernetes/client.go
models/namespace.go
models/service.go
routing/routes.go

New features included here:
- `/api/namespaces` - listing all namespaces created within openshift
- `/api/namespaces/{namespace}/services` - list of services for a namespace named `{namespace}`
This PR addresses to [SWS-62](https://issues.jboss.org/browse/SWS-62) and is unblocking [SWS-63](https://issues.jboss.org/browse/SWS-63)  - showing those services in the UI - in progress by @lucasponce.
Let's see the output:
`/namespaces`
`/namespaces/istio-system/services`

Endpoints for Service List page

---

hack/build-openshift.sh
hack/cluster-openshift.sh
hack/istio-bookinfo-openshift.sh
hack/istio-install-openshift.sh

now you can run the hack scripts from anywhere. Like if you are in the main source directory (parent of hack/) you can `./hack/cluster-openshift.sh up` and it will work. Same with the others.

be able to run the hack scripts from any directory

---

Makefile
deploy/docker/Dockerfile

@pilhuhn for you to review.
I found no way to tell npm install to only produce /build files.

SWS-127: don't move the entire 300MB npm install into docker - just retain what we need

---

Makefile

be able to specify the console version we want

---

Makefile
README.adoc
deploy/kubernetes/sws-configmap.yaml
deploy/kubernetes/sws.yaml
deploy/openshift/sws.yaml
hack/istio/README.adoc
hack/istio/kubernetes/istio-bookinfo-kubernetes.sh
hack/istio/kubernetes/istio-install-kubernetes.sh
hack/istio/openshift/istio-bookinfo-openshift.sh
hack/istio/openshift/istio-install-openshift.sh

This gets k8s deployment to work. Also includes hack scripts to get istio and bookinfo installed easily on k8s. I use minishift, but the hack scripts don't require that.

SWS 155: kubernetes scripts

---

config/config.go
handlers/grafana.go
handlers/grafana_test.go
models/grafana_info.go
routing/routes.go

Determine Grafana URL:
- If it's in the config, then use that one
- Else try to guess using k8s API
This URL will be used on the front-end to display a link to Grafana.
This function is exposed on endpoint `/api/grafana`

SWS-119 Expose grafana URL

---

handlers/services.go
models/service.go

This PR adds error handling to Service Details endpoint. In particular, it adds the 404 error instead of only responding with 500 errors.
This is connected to [SWS-67](https://issues.jboss.org/browse/SWS-67)

SWS-67 Handling errors (404,500) for Service Details endpoint

---

kubernetes/client.go
prometheus/client.go
prometheus/client_test.go

This is a bug fix, tests have been updated for prometheus client.
Kubernetes client tests will be added once https://github.com/swift-sunshine/swscore/pull/76 work is consolidated.
So I will add these tests later, but for Sprint 1, I guess we can fix this one.

SWS-190: Fix duplicated source services and routerules

---

models/route_rules.go

@lucasponce realized service endpoint missed RouteRule.MATCH fields from Istio Route Rules.

SWS-191 Add RouteRule.MATCH attribute into Service details endpoint

---

models/route_rules.go

Fine tunning Istio Route Rules view within Service Details.
This work addresses [SWS-192](https://issues.jboss.org/browse/SWS-192)
@lucasponce here it goes :)

SWS-192 Add RouteRule.Name to Service Details endpoint

---

hack/istio/openshift/istio-install-openshift.sh

Apparently the service-account name has been changed to just "grafana"
Also removed now unused service-account istio-prometheus-service-account, and duplicate lines
Note: without this change, I get this error while starting grafana pod:
```
jotak@cartago:/work/go/src/github.com/swift-sunshine/swscore (master %)$ oc logs grafana-4183644701-rcznr
chown: changing ownership of '/data/grafana': Operation not permitted
chown: changing ownership of '/var/log/grafana': Operation not permitted
```

SWS-245: [Hack scripts] Fix grafana service with istio-0.6.0

---

handlers/services.go
models/service.go
models/service_test.go

This PR addresses work of JIRA [SWS-168](https://issues.jboss.org/browse/SWS-168).
It adds unit testing to ServiceDetails endpoint data manipulation.
Do you mind put some attention to the way I managed to mock IstioClients and Prometheus clients?

SWS-168 Add Unit testing to Service.SetServiceDetails

---

README.adoc
config/config.go
deploy/openshift/sws.yaml
handlers/grafana.go
handlers/grafana_test.go
kubernetes/client.go
kubernetes/os_route_client.go
kubernetes/types.go
models/grafana_info.go

- Can be disabled
- Can be taken from openshift route (a new "OSRouteClient" had to be created for that, similar to IstioClient)
- If not using openshift route or explicit config, look for k8s service "ExternalIPs" instead of "ClusterIP"
- Added ClusterRole to get Routes in openshift template
- Updated README

SWS-171 more configurable Grafana links

---

README.adoc
graph/cytoscape/cytoscape.go
graph/options/options.go
graph/tree/tree.go
graph/vizceral/vizceral.go
handlers/graph.go
handlers/graph_test.go
handlers/testdata/test_namespace_graph.expected
handlers/testdata/test_service_graph.expected

NOTE: REQUIRES ISTIO 0.6.0 +
A few other changes here:
- refactor options to its own package
- be more clear about rate vs percentage in naming
- add rate_per_second query param support for thresholds and colors
- refactor vendor grpah generation to handle new istio 0.6 changes
- source_service="" is now source_service="unknown"
- the "unknown" service now serves as single root (is now parent of ingress)

SWS-249 Move to requests_per_second from requests_per_minute

---

hack/env-openshift.sh

Allows to set a value for OPENSHIFT_IP_ADDRESS that will be used by the hack scripts.
e.g.
`export OPENSHIFT_IP_ADDRESS="192.168.16.1"; ./cluster-openshift.sh up`

Allow to specify a default OPENSHIFT_IP_ADDRESS for the hack scripts

---

handlers/graph_test.go
handlers/services.go
handlers/services_test.go
prometheus/client.go
prometheus/client_test.go
prometheus/metrics.go
prometheus/prometheustest/mock.go

- ServiceMetrics handler: add duration and step query params
- Prometheus client: refactor channels usage, refactor model, provide Health with a dedicated model, fetch ranges
- Tests: share prometheus API mock. Use it in prom's client_test, graph_test, services_test
- Tests: update client tests for ranges, test empty metrics, test ServiceMetrics handler

SWS-261 Refactor metrics backend to provide range metrics

---

hack/istio/istio-install.sh

When installing Ansible from source, the ansible docs tell you to install some python deps via pip. This 
script now does that. If you already have the deps installed, the script keeps going. Note even if the pip-install fails, the script keeps going - it is possible you need to sudo the pip call - but since it might have already been done by the root user, this script keeps going in the hopes of being successful. A warning message is output just to let the user know what is going on in that case.
@jshaughn hit this - he didn't have some of those python deps installed so even after git cloning ansible, the ansible scripts failed to run properly.

enhance istio-installer to better prepare ansible

---

README.adoc
RELEASING.adoc
config/config.go
glide.yaml
graph/cytoscape/cytoscape.go
graph/vizceral/vizceral.go
handlers/grafana.go
handlers/grafana_test.go
handlers/graph.go
handlers/graph_test.go
handlers/namespaces.go
handlers/root.go
handlers/services.go
handlers/services_test.go
models/destination_policy.go
models/namespace.go
models/route_rule.go
models/service.go
models/service_test.go
prometheus/client.go
prometheus/client_test.go
prometheus/metrics.go
routing/router.go
routing/router_test.go
routing/routes.go
server/server.go
server/server_test.go
sws.go

swscore would not build anymore after the GitHub organization rename.
Similar exercise would have to happen when we rename swscore (waiting on kevin's input)

SWS-309 Fix build after GitHub Organization renaming

---

README.adoc
config.yaml
config/config.go
kubernetes/kubernetes_service.go

Removing a magic string from deployments filtering within service details endpoint.
This was a suggestion from @lucasponce :) thx

SWS-250/2 Remove magic numbers/literals from deployment filtering

---

handlers/services.go
handlers/services_test.go
prometheus/client.go
prometheus/client_test.go
prometheus/metrics.go

Also change the prom query on request volume to perform "round(sum(irate(" instead of "rate(" , same as in the istio grafana dashboard.
Sum allows grouping.

SWS-277 allow grouping metrics by label

---

handlers/graph.go
handlers/graph_test.go

To get a true reflection of incoming traffic show all relevant source
service nodes.

SWS-320 Graph root nodes should not be constrained to namespace

---

graph/cytoscape/cytoscape.go
handlers/graph.go
handlers/graph_test.go
handlers/testdata/test_namespace_graph.expected
handlers/testdata/test_service_graph.expected

Edge App fields (if non-zero):
Rate	   // total requests per second
Rate3xx  // requests per second returning 3xx errors
Rate4xx  // requests per second returning 4xx errors
Rate5xx  // requests per second returning 5xx errors
RateErr  // total requests per second returning 3|4|5xx errors
Node App Fields (if non-zero, for rate fields)
Service  // service name
Version  // service version
GroupBy  // set on compound nodes. valid values: [ 'version' ]
Rate	   // aggregate total requests per second
Rate3xx  // aggregate requests per second returning 3xx errors
Rate4xx  // aggregate requests per second returning 4xx errors
Rate5xx  // aggregate requests per second returning 5xx errors
RateErr  // aggregate total requests per second returning 3|4|5xx errors
* aggregates are for all incoming …

sws-278 decorate cytoscape nodes and edges with more data

---

kubernetes/client.go
kubernetes/client_test.go
kubernetes/kubernetes_service.go

Small but important refactor. Deployments were filtered by label in our side instead of asking k8s to do that.

SWS-250 Refactor - Ask K8s API to return deployments already filtered by label

---

kubernetes/istio_rules_service.go
models/istio_rule.go
models/istio_rule_test.go

- A non supported handler/instance is converted in a nil object but prevent to fail

SWS-327 Fix fetch Istio Rule with non supported handlers/instances

---

kubernetes/kubernetes_service.go
models/autoscalers.go
models/deployment.go
models/service.go
models/service_test.go

Instead of having two different lists in service details, this PR adds an autoscaler within the deployment object.

SWS-253: Embed autoscalers in each deployment

---

prometheus/client.go
prometheus/client_test.go
prometheus/metrics.go

(was: https://github.com/swift-sunshine/swscore/pull/99 )
Replacing channels in metrics.go with _sync.WaitGroup_ which is more suited for simple synchronization between goroutines

SWS-284 Remove some abusing usage of channels

---

handlers/services.go
prometheus/client.go
prometheus/client_test.go
prometheus/metrics.go

Adding one more behavior to the metrics endpoint:
* Pass query param component=details (or nothing) to trigger current behavior.
* Pass query param component=summaryPanel to trigger new behavior.
New behavior is to only return request_count_{in/out} metrics and also request_error_count_{in/out} metrics.
This is what should be needed to populate the "sparklines" of the side panel in the service graph.

SWS-216: Add request_error_count metrics

---

handlers/services.go
kubernetes/kubernetes_service.go
kubernetes/types.go
models/service.go
models/service_test.go

Adding pod status for each service into Service List:
Pod numbers are a sum of pods for each service deployment.
https://issues.jboss.org/browse/KIALI-361

SWS-361: Add pod status for each service in service list

---

models/route_rule.go
models/service_test.go

This PR is to add the missing fields used for the RouteRule object.
In the previous Sprint we only added the fields we used from examples, but now we are targeting more complex examples makes sense to expose all potential fields that can be used in the routes as in some way we need to show them in the UI.

KIALI-241 Add missing RouteRules attributes

---

handlers/namespaces.go
handlers/services.go
prometheus/client.go
prometheus/client_test.go
prometheus/metrics.go
routing/routes.go

This is analogous to the existing service metrics support but allows for
a an optional service pattern (regex) as opposed to an explicit service.
Without a pattern it will aggregate on all services in the namespace.
@jotak Please review.  I think this is needed to gather aggregate metrics when querying across different, or all, services in a namespace.  We needed it to support traffic summary for the namespace graph.  Thanks. Jay.

KIALI-330 Add backend support for namespace metrics

---

README.adoc
config/config.go
handlers/grafana.go
handlers/jaeger.go
handlers/jaeger_test.go
handlers/utils.go
models/jaeger_info.go
routing/routes.go

Provide the url for jaeger
@jotak I moved some methods of Grafana (Get service...) to utils because I need them to so please review this because is so similar to your code.

[KIALI-242] Add Jaeger Info to Backend

---

graph/options/options.go
handlers/graph.go
handlers/graph_test.go

- change from confusing 'interval' to correct and consistent 'duration'
- also change to 10m default duration from 30s to generate a graph based
on greater request data.

KIALI-407 use duration terminology for graph api/impl

---

Makefile

do not merge this until https://github.com/kiali/kiali-ui/pull/183 is merged and kiali-ui is published on npm - it will probably be here: https://www.npmjs.com/package/@kiali/kiali-ui

KIALI-318 pull the renamed kiali-ui from npm repo

---

README.adoc
config/config.go
models/deployment.go
models/service.go

This is a minor change, but we can use the Deployment details to identify services with and without Istio sidecar deployed.
So, we can show this parameter in the service list / service details and also as part of future work for graph where we may want to identify potential Istio services without traffic.

KIALI-446 Identify Services with Istio Sidecar

---

server/server.go

the highlighted part said "swift sunshine" before the fix

[minor] Fix swift sunshine to kiali in basic auth dialog

---

handlers/services.go
models/service.go
models/service_test.go
prometheus/client.go
prometheus/client_test.go
prometheus/metrics.go

Because of KIALI-388, the service list must show the error rate of the services.
With this PR, the service list endpoint is now fetching the request counters and calculating the error rates.
UI counterpart is in kiali/kiali-ui#208

KIALI-450: Adding backend support for error rates in service list

---

hack/istio/install-istio-rule.sh
hack/istio/ratings-delay-abort.yaml

Just some convenience stuff.
We should/could perhaps collect other rules here, so that we can more easily test stuff.
@lucasponce I think you should also have some that you are using for your tests (?)

Provide a routing rule for fault injection and an installer script

---

README.adoc
config.yaml
config/config.go
kubernetes/client.go

With this small changes we can configure de backend to be outside the cluster.
I think that we can add this to the method InCluster, Only we need to check if config.InCluster is false to 
get the environments instead of default values for the token and the CA file.
[KIALI-501](https://issues.jboss.org/browse/KIALI-501)
What do you think? I think this is useful to debug the backend
```
export KUBERNETES_SERVICE_HOST="127.0.0.1"
export KUBERNETES_SERVICE_PORT=8443
export KUBERNETES_TOKEN_PATH="/home/alberto/source/go/"
export KUBERNETES_CA_PATH="/var/lib/origin/openshift.local.config/master/"
```
cc @lucasponce

[Kiali-501] Out Cluster Configuration for dev environments

---

kubernetes/client.go
models/service.go
models/service_test.go

This PR fixes the issue of listing more pods than actually a service has. Check the following example out:
Deploy filtering it is now made using service.selector and deployment.template.labels. 
Result:

KIALI-460 Service pod status fixed

---

handlers/metrics.go
handlers/services_test.go
prometheus/metrics.go

Allow the caller to fix the query time instead of always using 'now'

KIALI-508 support queryTime param for metrics requests

---

README.adoc
config.yaml
config/config.go
handlers/grafana.go
handlers/grafana_test.go
handlers/graph_unused.go
handlers/jaeger.go
handlers/jaeger_test.go
prometheus/client.go
prometheus/metrics.go
prometheus/prometheustest/client_test.go
services/business/services.go
status/status.go
status/versions.go

I don't know if it is a good idea inspect the version of mixer and pilot, they return the version in the endpoint ip:9093/version, It could be possible that in the future they'll have a different version.
[KIALI-268](https://issues.jboss.org/browse/KIALI-268)
[KIALI-270](https://issues.jboss.org/browse/KIALI-270)
What do you think?

KIALI-268 - KIALI-270  Show Product Versions

---

graph/cytoscape/cytoscape.go
handlers/graph_unused.go
handlers/graph_unused_test.go
handlers/testdata/test_namespace_graph.expected
handlers/testdata/test_service_graph.expected

- Place them in the root trees when no info about siblings found.
- Place them grouped with siblings if appropiate.
- Mark nodes with dotted border to easily differentiate them.
Scenarios:
a) No traffic
b) Traffic and a new node appears, and we know where to place them:
c) Traffic and new nodes without information:
d) Same as c) but with multiple versions for unused nodes:
This PR changes only the backend, a following PR in the UI code will adapt the dotted style for the new nodes.

KIALI-511 Change unused nodes layout strategy

---

kubernetes/client.go
kubernetes/client_test.go
kubernetes/kubernetes_service.go
services/business/health.go
services/business/services.go

Some changes are necessary for that, such as passing []Deployment instead of DeploymentsList in the k8s temporary model

KIALI-402 use LabelsMatch algo to match deployments in service details

---

graph/appender/appender.go
graph/appender/circuit_breaker.go
graph/appender/unused_service.go
graph/appender/unused_service_test.go
graph/options/options.go
handlers/graph.go
handlers/graph_test.go
routing/routes.go

This refactors things to further detach unused service and circuit breaker
additions fron the base graph generation.  It sets things up to more
easily allow potential include/exclude options on requests.

KIALI-545 introduce appenders to graph generation

---

services/models/destination_policy.go
services/models/route_rule.go
services/models/service.go
services/models/service_test.go

Adding creation time to service, route rules and destination policies. Dates are shown in kubernetes format: [RFC3339](https://github.com/kubernetes/apimachinery/blob/master/pkg/apis/meta/v1/types.go#L168)

KIALI-544 Add creation time to route rules and destination policies

---

graph/appender/circuit_breaker.go
graph/appender/unused_service.go
graph/appender/unused_service_test.go
graph/cytoscape/cytoscape.go
handlers/graph.go
handlers/testdata/test_namespace_graph.expected
handlers/testdata/test_service_graph.expected

- flag root nodes for easier handling in the ui
- also, former pr feedback, use less verbose json field names

KIALI-595 better handling of root nodes

---

handlers/services.go
handlers/services_test.go
prometheus/client.go
prometheus/metrics.go
prometheus/prometheustest/client_test.go
prometheus/prometheustest/mock.go
services/business/health.go
services/business/services.go
services/business/services_test.go
services/models/health.go
services/models/service.go

- Move service error rate fields to health
- Add rateInterval query param to endpoints provding health
- Fix issue while getting error rates: dulicates may appear when fetching for namespace, they must not be added twice to the counters
- Fetch Error Rates per service
- Some rework on Health to make it easier to fill incrementally
UI counterpart: https://github.com/kiali/kiali-ui/pull/265

KIALI-505 Provide Error Rate in health

---

graph/appender/circuit_breaker.go

The way the code was originally, if nil that cast is going to panic. This PR fixes that.

KIALI-620 check the cast

---

graph/appender/circuit_breaker.go
graph/appender/route_rule.go
graph/cytoscape/cytoscape.go
graph/options/options.go
handlers/graph.go
handlers/testdata/test_namespace_graph.expected
handlers/testdata/test_service_graph.expected
kubernetes/istio_details_service.go

- make public the individual IstioClientGetIstioDetails methods to allow
for more targeted calls from the appenders.
- update CB appender to use GetDestinationPolicies() directly
- change some "isXxx" field names to "hasXxx" where appropriate
- shorten some json field names where appropriate

KIALI-619 Add route rule appender

---

handlers/services.go
routing/routes.go
services/business/checkers/route_rule_checker.go
services/business/checkers/route_rule_checker_test.go
services/business/checkers/route_rules/precedence_checker.go
services/business/checkers/route_rules/precedence_checker_test.go
services/business/checkers/route_rules/route_checker.go
services/business/checkers/route_rules/route_checker_test.go
services/business/istio_validations.go
services/business/istio_validations_test.go
services/business/layer.go
services/models/istio_validation.go
services/models/route_rule.go
util/intutil/convert.go

This provides to KIALI a system prepared to run checks for all desired Istio Objects (route rules, destination policies, virtual services and destination rules).
Right now, in this PR, route rule weight and precedence validations are added. However, this system allow us to add as many validations as wanted (following SOLID principles).
PR related to [KIALI-556](https://issues.jboss.org/browse/KIALI-556) (and parcially documented in [KIALI-555](https://issues.jboss.org/browse/KIALI-555)).
For each IstioObject, we have an IstioValidation which aggregate all checks run for it.
An IstioValidation has:
- name: name of the istio object
- object_type: routerule, destinationpolicy,...
- valid: bool - true means that there are at least one check that returns an error (warnings are counted as …

Kiali 556 - Add configuration checks for Istio Objects

---

Makefile

we released 0.2.0.Alpha - this PR bumps up the version to the next snapshot version

bump up version

---

config.yaml
graph/cytoscape/cytoscape.go
kubernetes/istio_details_service.go
kubernetes/istio_details_service_test.go

KIALI-718 Fix proper version location on RouteRule objects
Now when RouteRule is defined in any of the versioned services, the badge will be placed on the box.
KIALI-718 was somehow rejected, but the bug detected there was also affecting, so now CheckRouteRule detects a version in Destination and the DestinationWeight, so, graph will show correctly where the badge is.

KIALI-719 Place RouteRule badges on service

---

services/business/checkers/route_rules/route_checker.go

Quick fix. A path to any weight field in a route rule configuration is under `spec/route/weight` not under `spec/precedence`.

Route Rule weight validation path fixed

---

graph/appender/sidecars_check.go
services/business/checkers/pod_checker.go
services/business/checkers/pod_checker_test.go
services/business/checkers/route_rule_checker.go
services/business/checkers/route_rule_checker_test.go
services/business/istio_validations.go
services/business/istio_validations_test.go
services/models/istio_validation.go

Please @xeviknal, review this one.
I needed this change as the IstioValidation model didn't consider that name are not unique betwen different objectTypes.
So, I introduced another map to group first by type, and then by name, as per a single type names are unique.
This blocked me in the progress of KIALI-557.
Don't merge yet, as I need to prepare the changes on the UI for these one but I guess it can be reviewed.

KIALI-769 Refactor IstioValidation to group per type and name

---

services/models/pod.go
services/models/pod_test.go

@lucasponce , following our discussion, this is to provide the container images information.
I've also transposed the annotation parsing from frontend to backend, so that we build our own model that is closer to what we need on the frontend side. It's also good for reducing the amount of data coming from the backend.

KIALI-767 parse annotations and provide container images info

---

graph/appender/sidecars_check.go

without this fix. PR #208 blows up

check for nil

---

services/business/checkers/route_rule_checker.go
services/business/checkers/route_rule_checker_test.go

Small but pitty bug. Only showing validations for one single object type, the latest one. All the previous validations were overwritten.
Now it is fixed.

Keeping validations when multiple route rules are present

---

Makefile

0.3.0.Alpha has been released, this bumps up the version to the next snapshot

prepare for next release

---

handlers/services.go
services/business/checkers/pod_checker.go
services/business/checkers/pods/sidecar_presence_checker.go
services/business/checkers/route_rule_checker.go
services/business/checkers/route_rules/precedence_checker.go
services/business/checkers/route_rules/route_checker.go
services/business/istio_validations.go
services/models/istio_validation.go

Thinking that we could also add somewhere the description of #180. Should we start a wiki?

KIALI-686: Adding documentation to validation system

---

graph/cytoscape/cytoscape.go
handlers/graph_test.go
handlers/testdata/test_namespace_graph.expected
handlers/testdata/test_service_graph.expected

We're going to support multiple/all namespaces, that ensures that even
if we do many requests to get more nodes on the graph, the edges between
them will not crash.
The graph using hashes:

Use hashes for the edges on the cytoscape graph

---

handlers/services.go
kubernetes/istio_details_service.go
kubernetes/istio_details_service_test.go
routing/routes.go
services/business/checkers/checker.go
services/business/checkers/destination_policies/no_destination_checker.go
services/business/checkers/destination_policies/no_destination_checker_test.go
services/business/checkers/destination_rules/no_name_checker.go
services/business/checkers/destination_rules/no_name_checker_test.go
services/business/checkers/no_service_checker.go
services/business/checkers/no_service_checker_test.go
services/business/checkers/route_rule_checker.go
services/business/checkers/route_rules/no_destination_checker.go
services/business/checkers/route_rules/no_destination_checker_test.go
services/business/checkers/virtual_services/no_host_checker.go
services/business/checkers/virtual_services/no_host_checker_test.go
services/business/istio_validations.go
services/business/istio_validations_test.go

@xeviknal this is the PR to back the logic for KIALI-557. 
Basically it introduces a new endpoint to run validations per namespace.

KIALI-557 Implement NoService validation logic in backend

---

.travis.yml
Makefile
graph/appender/sidecars_check.go
handlers/services_test.go
services/business/checkers/no_service_checker.go
services/business/checkers/no_service_checker_test.go
services/business/checkers/pod_checker.go
services/business/checkers/pod_checker_test.go
services/business/checkers/route_rule_checker.go
services/business/checkers/route_rule_checker_test.go
services/business/istio_config.go
services/business/istio_validations.go
services/business/istio_validations_test.go
services/models/istio_validation.go
services/models/istio_validation_test.go

This PR adds a Makefile target (`make test-race`) to run the tests with [race detection](https://golang.org/doc/articles/race_detector.html) enabled. It also fixes the reported data races. The Travis CI configuration is modified to run `make test-race` as it can surface problems that are hard to debug in live conditions.

Fix data races

---

graph/appender/dead_service.go
graph/appender/istio_details.go
graph/appender/latency.go
graph/appender/sidecars_check.go
handlers/graph.go

- appenders must now handle an empty tree list.

KIALI-833 Always run appenders, even on empty graph

---

config/config.go
status/status.go
status/versions.go
status/versions_test.go

[KIALI-269](https://issues.jboss.org/browse/KIALI-269)
The object will be warning_messages

[Kiali_269] Throw warning message when istio version is not supported

---

kubernetes/client.go
kubernetes/kubernetes_service.go
kubernetes/kubetest/mock.go
services/business/checkers/route_rule_checker.go
services/business/checkers/route_rule_checker_test.go
services/business/checkers/route_rules/version_presence_checker.go
services/business/checkers/route_rules/version_presence_checker_test.go
services/business/istio_validations.go
services/business/istio_validations_test.go

Given a route rule routing traffic to v1 and v2, add a new validation if v1 or v2 doesn't have any pod running.

Kiali 812 - Check if route rule versions labels has pods running

---

handlers/istio_config.go
handlers/namespaces.go
handlers/services.go
routing/routes.go
services/business/istio_validations.go
services/business/istio_validations_test.go

@xeviknal this is an extension of the GetNamespaceValidations logic, but just focus to a single istio object.
To respond into the UI logic of list vs detail for IstioConfig.

KIALI-851 Add validation endpoint per IstioObject

---

services/business/checkers/route_rules/route_checker.go
services/business/checkers/route_rules/route_checker_test.go
services/business/istio_validations_test.go

Minor change for allowing UI to show warnings/errors into weight table.
Needs to be merged at same time as [kiali/kiali-ui#389](https://github.com/kiali/kiali-ui/pull/389).

Allowing show error/warning messages to collection fields e.g. labels

---

hack/build-openshift.sh
hack/env-openshift.sh

1. Support building from a tag
2. Not sure why python2 is being passed hack/env - hack/env is a bash script. Removing python2 because this is broken the way it is.
3. Build release-3.9 by default
@jshaughn item 2 above fixes the build error I think you are getting (at least, it is why my build was broken; I think you are probably hitting the same thing). Please review and merge.

fix build hack script

---

kubernetes/client.go
kubernetes/client_test.go
kubernetes/kubernetes_service.go
services/business/services.go

IstioDeployed flag was calculated from Deployments.
So, in Service List view, we couldn't filter when deployment is different from k8s "Deployment" object.

KIALI-879 Calculate IstioDeployed flag from Pods

---

kubernetes/istio_details_service.go
kubernetes/istio_details_service_test.go

Due to a change of Destination Rule specification in Istio 0.8,  those resources are bound to a hostname instead of a service name.
In this PR all API calls that fetch Destination Rules are adapted to this change.

Kiali 893 DestinatioRule is using host field

---

kubernetes/istio_details_service.go
kubernetes/istio_details_service_test.go

Due to a change of Destination Rule specification in Istio 0.8, those resources are bound to a hostname instead of a service name.
In this PR all API calls that fetch Destination Rules are adapted to this change.
This PR is a copy of #257

Kiali 893 DestinatioRule is using host field now

---

config/token.go

When running ```make test``` the following error fails the tests:
```
config/token.go:55: Sprintf call has arguments but no formatting directives
```
This PR adds the missing formatting argument

Fix error when running tests

---

server/server.go
server/server_test.go

Jira: [KIALI-913](https://issues.jboss.org/browse/KIALI-913)
When the request come from Kiali-UI there is a header called X-Auth-Type-Kiali-UI to avoid the response with header Basic realm=\"Kiali\" and avoid the auth popup.
When the user go to the same url / or /console this not happens so we need to filter this kind of requests.
Removed tests authentication when request is /console, this has no sense when the authentication is against Kiali-UI

KIALI-913 Fix auth PopUp when access to url different to /api

---

graph/appender/istio_details.go
graph/cytoscape/cytoscape.go
kubernetes/istio_details_service.go
kubernetes/istio_details_service_test.go

This is copy of #254. Feature added here works for Istio 0.8 version. That's why the base of this PR is istio-0.8 branch.
-----------------------------------
The goal of this PR is to add an attribute to those edges that connect two services transmitting under mTLS.
This PR is a first step to add fully coverage of mTLS. Right now, it only support the meshes using Istio without default mTLS enabled. 
Please, see more information into https://issues.jboss.org/browse/KIALI-750
This PR should be merged after achieving Istio 0.8.0 migration.

KIALI-750 Adding mTLS attribute to edges

---

kubernetes/istio_details_service.go
kubernetes/istio_details_service_test.go
services/business/checkers/destination_rules/no_host_checker.go
services/business/checkers/destination_rules/no_host_checker_test.go
services/business/checkers/no_service_checker.go
services/business/checkers/no_service_checker_test.go
services/business/istio_validations_test.go
services/models/destination_rule.go
services/models/service_test.go

This updates the DestinationRule name -> host in model and checkers.
There is also a missing PR for the UI side.

KIALI-941 Update DestinationRule Host on model and checker

---

graph/appender/istio_details.go
kubernetes/istio_details_service.go
kubernetes/istio_details_service_test.go

This is a quick fix of #269. It didn't include the change to use 0.8 syntax for Destination Rule

KIALI-750 Fixing enablemTLS flag - now using destination rule with 0.8 syntax

---

config/authentication.go
routing/router.go
routing/router_test.go
routing/routes.go
server/server.go
server/server_test.go

Jira : [KIALI-923](https://issues.jboss.org/browse/KIALI-923)
- Server file now only have the server methods related
- Authentication moved to configuration
- Allow set authentication required by route
- Disable authentication required in /api and /api/status this routes only show status of kiali and products versions

KIALI-923 Allow authentication by route

---

handlers/services_test.go
prometheus/client.go
prometheus/metrics.go
prometheus/prometheustest/client_test.go
prometheus/prometheustest/mock.go
services/business/health.go
services/business/services.go
services/business/services_test.go
services/models/health.go

- metric queries updated as per new naming scheme
- now inbound and outbound metrics are available; model updated
- remove some goroutines from fine-grained metric-fetching and add some to coarser level => this should optimize waiting time

KIALI-922 Fix empty envoy metrics with istio0.8

---

hack/istio/README.adoc
hack/istio/download-istio.sh
hack/istio/install-bookinfo-demo.sh

Let the bookinfo demo script use the download script only when necessary.
I am finding these helpful, especially when needing to switch between Istio versions but also knowing that the bookinfo demo is the same across recent versions.

be able to download different versions of Istio.

---

graph/appender/response_time.go
graph/appender/response_time_test.go
graph/cytoscape/cytoscape.go
graph/options/options.go

Latency is not really correct for the data we are showing, it is the complete response time for the request (of which latency is only a part).

Kiali 924 replace latency with responseTime

---

kubernetes/istio_details_service.go
kubernetes/istio_details_service_test.go

Tested locally, installed bookinfo-ratings-delay.yaml from hack/istio folder

KIALI-985 Fix missing rename field in VirtualService

---

kubernetes/istio_details_service.go
kubernetes/istio_details_service_test.go
services/business/checkers/virtual_services/no_host_checker.go

- Unify checker function used
This PR unifies checker function for hostname and supports single wildcard.
There are other use cases that are not yet covered but I will prepare a following PR to separate from this one.

KIALI-982 Support generic wildcard in host validation

---

Makefile
config.yaml
deploy/kubernetes/kiali-configmap.yaml
deploy/kubernetes/kiali-secrets.yaml
deploy/kubernetes/kiali.yaml
deploy/openshift/kiali-configmap.yaml
deploy/openshift/kiali-secrets.yaml
deploy/openshift/kiali.yaml

Credentials are now passed to Kiali in environment variables.
Tried both in OS and  K8s and everything seems to work ok.

KIALI-855 Move credentials from ConfigMap to Secrets

---

graph/cytoscape/cytoscape.go
handlers/graph.go
handlers/graph_test.go
handlers/testdata/test_multi_namespace_graph.expected
handlers/testdata/test_namespace_graph.expected
handlers/testdata/test_service_graph.expected

This is a two-part PR, the other one being on the ui repo. The idea here is to
show the services on a different namespace with a different color and shape.
Here's how it looks right now:
Things that are missing:
shown on the image below. I'm not sure exactly what happens on that, what I do
have in mind right now is that those bugs appear when there's a graph on the
connection that comes and goes to a different namespace, like this:
The configuration on this one is pingpong, which is `a d a e a f`, meaning that
it goes from one namespace to the other and then back.
On the other namespace page, the weird behaviour also happens:
That means that ingress traffic that comes from another namespace is not being shown.
---
If you want to test these configurations, you can use this script on the …

KIALI-817 Change shape of nodes on different namespaces

---

README.adoc
STYLE_GUIDE.adoc

I took inspiration from origin's contributing section ( https://github.com/openshift/origin#contributing )
Added links to gougle groups (kiali-dev + kiali-users) , bug tracker and other anchored sections.
I didn't mentioned JIRA or Confluence to keep things simple for newcomers. I guess GitHub tracker & docs should be enough for external contributors.
Please review also my English.

KIALI-454 Contributing section (readme) - more in style guide

---

deploy/kubernetes/kiali.yaml
deploy/openshift/kiali.yaml

Fixing issue of not able to show the *Istio Config* tab for istio 0.8.0  as permissions for gateways and virtualservices were missing in *kiali* cluster role
Ref: https://issues.jboss.org/browse/KIALI-1046

Fixing kiali cluster role to list new istio resources

---

prometheus/metrics.go

Output metrics for the unknown service are available in prometheus, but
queries are a little different. This generated the proper queries to get
output metrics for the unknown service.

KIALI-988 Fix metrics query for the "unknown" service

---

handlers/graph.go
handlers/testdata/test_namespace_graph.expected

I'm going to generate a PR that does two things:
- remove the no outgoing edge restriction on outsider nodes.
- disallow outsider roots.
That means that only insider traffic generators (and unknown) will get the isRoot=true and the subsequent diamond shape. This will distinguish insider traffic generator services from the rest of the insider services. It will also make all outsider services consistently show as a pentagon and make it easy to know which services support the navigation feature.

KIALI-1077 Another attempt at correctly handling root and outsider nodes

---

services/business/checkers/checker.go
services/business/checkers/virtual_service_checker.go
services/business/checkers/virtual_services/single_host_checker.go
services/business/checkers/virtual_services/single_host_checker_test.go
services/business/checkers/virtual_services/subset_presence_checker.go
services/business/istio_validations.go

When two virtual services point to one host, it returns a warning:
First Virtual Service SPEC:
```yaml
spec:
hosts:
- reviews
http:
- route:
- destination:
host: reviews
subset: v2
weight: 50
- destination:
host: reviews
subset: v3
weight: 50
```
Second Virtual Service SPEC:
```yaml
spec:
hosts:
- mongo.backup.svc.cluster.local
- mongo.staging.svc.cluster.local
- reviews
http:
- match:
- headers:
cookie:
regex: ^(.*?;)?(user=jason)(;.*)?$
retries:
attempts: 3
perTryTimeout: 2s
route:
- destination:
host: reviews
subset: v2
[...]
```
Result of running that validation:

KIALI-1068 Warn user when more than virtual service points to one host

---

graph/cytoscape/cytoscape.go
handlers/graph.go

- only set rate metadata when necessary, this reduces the metadata and
allows us to know when there is no rate data for a service.  Also, use
some helper methods to be safer about float64 conversions.

KIALI-1095 restrict isRoot/Diamond to nodes without incoming edges

---

services/business/istio_validations.go
services/business/istio_validations_test.go
services/models/istio_validation.go

JIRA: [KIALI-1115](https://issues.jboss.org/browse/KIALI-1115)
In order to validate multiple host constraint, we need to include all virtual services in the computation.
The output now would respond with checks of all virtual services from namespace. Frontend will use only the needed one.

KIALI-1115 Individual Virtual Service validates also multiple host constraint

---

kubernetes/istio_details_service.go
kubernetes/istio_details_service_test.go
services/business/checkers/destination_rules/no_host_checker.go
services/business/checkers/destination_rules/no_host_checker_test.go
services/business/checkers/no_service_checker_test.go
services/business/checkers/virtual_services/no_host_checker.go
services/business/checkers/virtual_services/no_host_checker_test.go
services/business/checkers/virtual_services/subset_presence_checker.go
services/business/istio_validations_test.go

Main change for this fix is to filter services by host defined in routes.
VirtualServices "hosts" field can be anything:
https://istio.io/docs/reference/config/istio.networking.v1alpha3/#VirtualService
So, it is not correct to link the services by that field, instead, using the host defined within the routes, it filter correctly from services from the mesh.

KIALI-1121 VirtualServices are filtered by host from routes

---

graph/cytoscape/cytoscape.go

The UI needs to know if the compound node "isOutside" to show the namespace/service name there and not in every children.

KIALI-1119 Sets isOutside to compound node

---

README.adoc
config/config.go
deploy/kubernetes/kiali.yaml
deploy/openshift/kiali.yaml
handlers/jaeger.go
server/server.go

This is the most clean thing than I found. We don't need any change in the UI and I commented the new things to remove them in future.
The problem was that after get the content of jaeger site the browser need to get the static build files of jaeger, trying to get /static/js/<files> and /static/css/<files> , so the browser try to get this files in : 
http://kiali-istio-system.127.0.0.1.nip.io/static/js
when should go to http://kiali-istio-system.127.0.0.1.nip.io/api/jaeger/static/js, or we do scrapping of the content that could be a nightmare o this solution.
A port service for the proxy opened in port 20002 in the container and expose 32439, and the api/jaeger result will be the same until we fix the certificates.

KIALI-976 Proxy solution for Jaeger https

---

hack/cluster-openshift.sh

This is to address issue #314
There were a few changes required due to differences in commands on macOS.
There should be a better solution to the IP address issue then the option I coded which just tells the user to specify the command line argument.
It really should be tested on a "clean" macOS install, which I haven't done.
It works with the docker-machine setup described https://medium.com/@pilhuhn/running-openshift-with-istio-on-os-x-1d4e5014bd01, but not with Docker for Mac Version 18.03.1-ce-mac65 (24312). I didn't try other docker versions.
comments and reviews welcome, particularly if I've missed any project requirements.

Darwin detect

---

handlers/namespaces_test.go
handlers/services_test.go
prometheus/client.go
prometheus/metrics.go
prometheus/prometheustest/client_test.go
prometheus/prometheustest/mock.go
services/business/health.go
services/business/services.go
services/business/services_test.go

- service ports are gathered from k8s Service before querying for envoy health. Some refactoring was necessary to make it ok for all three use cases (from service list, service details & graph) and keep an optimized loading workflow.
- updated envoy health query. While we could have a per-port granularity in health, at the moment the simplest is to aggregate all metrics regardless the port.
- tests & mocks updated

KIALI-1170 Fix envoy health hardcoded ports

---

Makefile

Starting from Go1.8, the user defined GOPATH is not mandatory. If it's not set, use the default $HOME/go

If GOPATH is not set, compile with the default GOPATH

---

kubernetes/istio_details_service.go

When trying to compile make test, the compilation fails with:
kubernetes/istio_details_service.go:146: Errorf format %s has arg serviceEntry of wrong type *kubernetes.ServiceEntry
This is because *kubernetes.ServiceEntry should use %v instead of %s

Fix Errorf formatting to correct type

---

services/business/checkers/no_service_checker.go
services/business/checkers/virtual_service_checker.go
services/business/istio_validations.go

Since there's no I/O done by any of the checkers, it is wasteful to spawn new goroutines for them. Processing in a single thread provides better use of CPU caches, reduces stack usage and makes the code more simple.

KIALI-1123 Remove use of goroutines and channels from checkers

---

handlers/metrics.go
handlers/namespaces.go
handlers/namespaces_test.go
handlers/services.go
handlers/services_test.go
prometheus/client.go
prometheus/metrics.go
prometheus/metrics_definitions.go
prometheus/prometheustest/client_test.go
services/business/services.go

- Update queries to match new names and labels
- Keep our internal names
- For service metrics fetching, search for "app" labels in deployments before actually querying prometheus

KIALI-1133 [Istio-1.0] Update metrics queries

---

graph/appender/sidecars_check.go
graph/cytoscape/cytoscape.go
graph/graph.go
graph/options/options.go

- update to 1.0 nodes
- add support for workload nodes
- restrict appPreferred nodes to requiring app+version labels
- enable appender
also:
- fix issue with group compound nodes, only add for versioned app or appPreferred

KIALI-1225 [1.0] graph, update missing-sidecar appender

---

config/token.go
doc.go
routing/routes.go
services/models/istio_config.go
services/models/istio_validation.go
services/models/namespace.go
status/status.go
swagger.json

In my process to add documentation to Validation endpoints:
* /api/namespaces/{namespace}/services/{service}/istio_validations
* /api/namespaces/{namespace}/istio_validations
I detect two issues:
1. GoSwagger doesn't allow us to document structs like `map[keyObject]valueObject`
2. Each API endpoint needs a different response (not letting us reuse a single response with different data object in the response body)
In [services/models/istio_validations.go#L17](https://github.com/kiali/kiali/blob/master/services/models/istio_validation.go#L17) we have the type:
```golang
// IstioValidations represents a set of IstioValidation grouped by IstioValidationKey.
type IstioValidations map[IstioValidationKey]*IstioValidation
```
Which is what we add in the response body for [service validations …

KIALI-1144 Add swagger documentation to validations endpoints

---

graph/appender/dead_node.go
graph/appender/dead_node_test.go
graph/appender/istio_details.go
graph/appender/response_time.go
graph/appender/response_time_test.go
graph/appender/sidecars_check.go
graph/appender/unused_node.go
graph/appender/unused_node_test.go
graph/cytoscape/cytoscape.go
graph/graph.go
graph/options/options.go
handlers/graph.go
handlers/testdata/test_multi_namespace_graph.expected
handlers/testdata/test_namespace_graph.expected
kubernetes/istio_details_service.go

- now handles the fact that a single node can represent multiple services
- by collecting the requested destServices (from the prom telemetry)
while constructing the graph
- activate the appender
Also:
- add Node.destServices to json for use in the ui

KIALI-1226 [1.0] graph, update istio_details (badging) appender

---

kubernetes/istio_details_service_test.go

Update test to call renamed method.  We may just want to get rid of this renamed method,
it's no longer used and I'm not sure we ever want to look for a virtual service
based on subset.

trivial - fix test

---

doc.go
handlers/deployments.go
handlers/deployments_test.go
kubernetes/client.go
kubernetes/kubetest/mock.go
routing/routes.go
services/business/deployments.go
services/business/deployments_test.go
services/business/layer.go
services/models/deployment.go
swagger.json

Adding a WorkloadList endpoint returning the list of deployments of a namespace.
** Questions **
We say it is a Workload list, but in our backend is a deployment list with toppings. Should we rename endpoints, models and so on?
[KIALI-1210](https://issues.jboss.org/browse/KIALI-1278) 
Yes.

KIALI-1210 Adding WorkloadList endpoint

---

graph/appender/response_time.go
graph/appender/response_time_test.go
graph/options/options.go
handlers/graph.go
handlers/metrics.go
prometheus/client.go
prometheus/metrics.go
prometheus/prometheustest/client_test.go
routing/routes.go

Telemetry surrounding istio-system namespace has changed in Istio 1.0.
With the exception of ingressgateway istio-system components only support
destination-side telemetry (reporter="destination").  Also, some prior
telemetry is now not reported since the traffic changed from http to gRPC.
- update the graph "includeIstio" support to perform additional queries as necessary
- remove "includeIstio" option from metrics support in favor of just changing
queries from source to destination telemetry when dealing with the
istio-system namespace. Remove the special filtering for istio-system as
the source-side reporting will not include it anyway.

KIALI-1267 [1.0] includeIstio changes

---

graph/appender/response_time.go
graph/appender/sidecars_check.go
graph/appender/unused_node.go
graph/cytoscape/cytoscape.go
graph/graph.go
graph/options/options.go
handlers/graph.go
routing/routes.go

- remove isWorkload for more robust nodeType
- change node ids to use workloadName instead of app+version label value. This
is better when anti-pattern labeling is used.

KIALI-1281 Introduce NodeType

---

doc.go
handlers/workloads.go
handlers/workloads_test.go
routing/routes.go
services/business/layer.go
services/business/workloads.go
services/business/workloads_test.go
services/models/deployment.go
services/models/workload.go
swagger.json

Renaming DeploymentList by WorkloadList.
URL listening: `api/namespaces/bookinfo/workloads`
[KIALI-1210](https://issues.jboss.org/browse/KIALI-1210)
Yes.

KIALI-1210 DeploymentsList endpoint renamed to WorkloadList

---

graph/cytoscape/cytoscape.go
handlers/health.go
handlers/health_test.go
handlers/namespaces.go
handlers/namespaces_test.go
handlers/services.go
handlers/services_test.go
kubernetes/client.go
kubernetes/kubernetes_service.go
kubernetes/kubetest/mock.go
kubernetes/types.go
prometheus/client.go
prometheus/metrics.go
prometheus/prometheustest/client_test.go
prometheus/prometheustest/mock.go
routing/routes.go
services/business/health.go
services/business/health_test.go
services/business/services.go
services/business/services_test.go
services/models/health.go
services/models/service.go
swagger.json

- New endpoints & business functions for workload-based health and app-based health
- Refactored service-based health to focus on service only (ie. inbound interface, deployment-agnostic)
- From kubernetes client, create new "AppDetails" type that gathers pods, services and deployments that shares the app label
- Move common stubs (service details/list) to k8s mock

KIALI-1215 , istio-1.0, new health endpoints

---

config/config.go
handlers/grafana.go
handlers/grafana_test.go
services/models/grafana_info.go

We now need to fetch the grafana REST API in order to get the dashboard path because they now include some random id.
Also, istio now provides two different dashboards for workloads and services

KIALI-1180 Update grafana info for istio-1 dashboards

---

services/models/workload.go
swagger.json

Adding Type to WorkloadList as suggested in https://github.com/kiali/kiali/pull/407#pullrequestreview-143951511
https://github.com/kiali/kiali/pull/407#pullrequestreview-143951511
Yes.

KIALI-1210 Add type to workload list

---

handlers/services_test.go
services/business/services.go

Apps were being resolved using k8s-deployments. This is incorrect since
a service can cover several kinds of "deployments".
This issue was found because metrics were being fetched incorrectly for
services that are backed by something else than a k8s-deployment.
Using pods to resolve apps involved in a k8s-service.

KIALI-1313 Fix Apps not being resoved correctly for a service

---

README.adoc
config/config.go
config/token.go

As pointed out in https://issues.jboss.org/browse/KIALI-1296 there was several inconsistencies or ambiguities in doc & options

KIALI-1296 Improve doc and config names for token-based auth

---

graph/appender/dead_node.go

For why this is needed see this [Jira](https://issues.jboss.org/browse/KIALI-1326).

KIALI-1326 Remove service nodes not showing error traffic

---

handlers/jaeger.go

The service used to fetch the Jaeger proxy url builds incorrectly the URL in some scenarios, as the host:port is not correctly parsed.
https://github.com/kiali/kiali/issues/416
https://issues.jboss.org/browse/KIALI-1346
No

KIALI-1346 Fix to parse correctly the Jaeger proxy

---

graph/appender/response_time.go
graph/appender/response_time_test.go

Added regex to get all 2xx response_codes in  response_time promtheus query.
https://github.com/kiali/kiali/issues/435
no
_describe the changes if appropriate_
The prometheus query response_times query was only returning requests that were ```response_code=\"200\"``` . However some other responses codes are also acceptable in a  restfull environment like  201 (created). This change allows the query to also return those valid 2xx response codes

added regex to enabled all 2xx response codes in response_time query

---

doc.go
routing/routes.go
services/business/services.go
services/business/workloads.go
services/models/pod.go
services/models/service.go
services/models/service_test.go
services/models/workload.go
services/models/workload_test.go
swagger.json

This PR works towards istio1.0 upgrade. Updates the service details endpoint:
- Removing Pods
- Removing Deployments
- Adding workloads
#404 Needs to be merged first.
[KIALI-1304](https://issues.jboss.org/browse/KIALI-1304)
No. It needs frontend to be adapted to this change.
There is actually an ongoing PR for that:  https://github.com/kiali/kiali-ui/pull/566 ([KIALI-1218](https://issues.jboss.org/browse/KIALI-1218))
_describe the changes if appropriate_
New output for service details:

KIALI-1304 Service details update - workloads added, deployments/pods removed

---

README.adoc
config/config.go
doc.go
handlers/workloads.go
routing/routes.go
services/business/checkers/pod_checker.go
services/business/checkers/pod_checker_test.go
services/business/checkers/pods/label_presence_checker.go
services/business/istio_validations.go
services/models/workload.go
swagger.json

Added the type to the Workload Details Endpoint
Added Endpoint to check labels and IstioSidecar Validations related a Workload
[KIALI-1347](https://issues.jboss.org/browse/KIALI-1347)
Yes

KIALI-1347 Add type in workloadEndpoint Details and validations by Workload

---

graph/appender/dead_node.go
graph/appender/dead_node_test.go
graph/cytoscape/cytoscape.go
graph/options/options.go
handlers/graph.go
handlers/graph_test.go
handlers/testdata/test_namespace_graph.expected
routing/routes.go

This is adding the required queries to Prometheus and adding the relevant metadata to the graph JSON.
** Backwards incompatible? No

KIALI-1097 Add graph support for nodes with TCP traffic

---

deploy/kubernetes/kiali.yaml
deploy/openshift/kiali.yaml

This reverts commit bc3934ce5e97c5636e5238585bba81285f433849 and removes `imagepullpolicy:always` from deployment template.
Best Regards,

[KIALI-1373] Revert "Moving ImagePullPolicy Always (#441)"

---

handlers/apps_test.go
handlers/graph.go
handlers/namespaces_test.go
handlers/services_test.go
handlers/testdata/test_namespace_graph.expected
handlers/workloads_test.go
prometheus/metrics.go
prometheus/prometheustest/client_test.go

- update getMetrics to return both source and destination telemetry to allow the client to use what he needs.
- use source telemetry and add more label qualifiers to ensure only service metrics are retrieved.

KIALI-1379 Fix service metric support

---

README.adoc
config.yaml
config/config.go
graph/appender/sidecars_check.go
graph/appender/unused_node.go
kubernetes/istio_details_service.go
kubernetes/kubernetes_service.go
services/business/apps.go
services/business/istio_validations.go

Refactor and clean after workloads
- We used the same values in the configuration file
[KIALI-1244](https://issues.jboss.org/browse/KIALI-1244)

KIALI-1244 Post-refactor cleaning/verification aftewr workloads

---

Makefile

Currently the Kiali UI version is set to 0.7.0 snapshot and the Kiali version is set to 0.6.1 snapshot. They versions are suppose to be kept in sync and they should both be 0.7.0 snapshot.

KIALI-1399 Keep Kiali versions in sync

---

graph/appender/sidecars_check.go
graph/appender/sidecars_check_test.go

Graph sidecar appender was mistakenly also checking pod labels. This was causing the graph to show the missing sidecar badge even if all pods correctly have sidecars.
Fixing issue and adding tests to avoid future regressions.
** Backwards incompatible? ** It's compatible

KIALI-1414 Fix sidecar appender when no version label

---

Makefile

There was an error when building the docker image that if the console tar failed the build would continue. This would result in the docker image not containing the console code and only the version.txt
See https://issues.jboss.org/browse/KIALI-1369
This update will now fail the build if the console could not be downloaded.

Kiali-1369 Fail the build if error on fetching the console tar

---

doc.go
routing/routes.go
swagger.json

1. Adding all the query params from metrics endpoints has been adapted to be in swagger format.
2. Fixed missing params in swagger for AppList endpoint.
3. Classified all the endpoints per resource type (Apps, Namespaces, Services, Workloads, Config).
4. Adding swagger documentation to old undocumented endpoints.
[KIALI-1329](https://issues.jboss.org/browse/KIALI-1329)
Yes.
NOTE: update your swagger installation to fix a infinit loop (https://github.com/go-swagger/go-swagger/issues/1614) // remove its installation folder and run again `make swagger-install`

KIALI-1329 Adding documentation to Metrics endpoints

---

services/business/checkers/virtual_services/route_checker.go
services/models/virtual_service.go

In Istio 1.0 VirtualServices have a new type of routes called tls. This PR adds this new routes to the API.
https://issues.jboss.org/browse/KIALI-1145
yes.
Is your change introducing backwards incompatible changes?
NO

KIALI-1145 Add TLS support to virtual services

---

Makefile
README.adoc
config.yaml
config/config.go
deploy/kubernetes/kiali-configmap.yaml
deploy/kubernetes/kiali.yaml
deploy/openshift/kiali-configmap.yaml
deploy/openshift/kiali.yaml
handlers/grafana.go
handlers/grafana_test.go
handlers/jaeger.go
handlers/utils.go
server/server.go

Remove proxy configuration for Jaeger
UI Side https://github.com/kiali/kiali-ui/pull/619
[KIALI-1423](
https://issues.jboss.org/browse/KIALI-1423)
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
name: kiali
labels:
app: kiali
version: ${VERSION_LABEL}
data:
config.yaml: |
server:
port: 20001
static_content_root_directory: /opt/kiali/console
jaeger:
url: https://jaeger-query-istio-system.127.0.0.1.nip.io
grafana:
url: http://grafana-istio-system.127.0.0.1.nip.io
```

KIALI-1423 Move Jaeger iFrame to external links

---

Makefile
deploy/kubernetes/kiali.yaml
deploy/openshift/kiali.yaml

If we are using an image tag of vX.Y then we should be using an imagePullPolicy of 'Always'.
The vX.Y releases represent the latest vX.Y.Z release, and if someone is using vX.Y we want them to always pull in the latest since those will have bug fixes.
The PR also allows someone to override the imagePullPolicy so they can set it to whatever they want.
Note: we don't explicitly set the imagePullPolicy if its doesn't match vX.Y, we let the system use the defaults in that case (which is IfNotPresent unless its 'latest' which will use 'Always'). This is why we use the IMAGE_PULL_POLICY_TOKEN in the yaml files, if its not specified then nothing extra is added to the yaml.
https://issues.jboss.org/browse/KIALI-1373

KIALI-1373 Set the imagePullPolicy to always for vX.Y tags

---

graph/appender/security_policy.go
graph/appender/security_policy_test.go

Making security appender sensitive to policy switch (from non-secure to secure and viceversa).
Prom queries only took secure data points (connection_security_policy != none) which isn't an accurate query. It turns out that secure data points are also present in queries even if mtls is switched off in istio.
This PR takes all the data points and compute the `isMTLS` flag.
In this solution, there is only one unknown scenario which is when you have secure and non-secure data points with a 0 value. Meaning that there is no traffic for that edge. In that case, `isMTLS` is set to `false` (taking a conservative approach).
When switching from mtls to non-tls security policy, graph doesn't change.
https://issues.jboss.org/browse/KIALI-1235
** …

KIALI-1235 Security appender sensitive to policy switch

---

config/authentication.go
config/token.go

About dead code: what I removed is some error handling part, but:
- it never ran into that code (see line 65)
- the initial error message is actually already accurate so it's not necessary to replace it

Remove some dead code and fix a log in token generation

---

services/business/services.go
services/business/workloads_test.go
services/models/workload.go

[KIALI-1464](https://issues.jboss.org/browse/KIALI-1464)

KIALI-1464 labels need to come from pods not the deployments

---

README.adoc
config.yaml
config/config.go
deploy/docker/Dockerfile
deploy/kubernetes/kiali-configmap.yaml
deploy/openshift/kiali-configmap.yaml
kiali.go
routing/router.go
server/server.go
util/config_to_js.go
util/update_base_url.go

Introduce optional context root to serve Kiali API and frontend under.  Users can customize the path by editing config.yaml `server.web_root` or passing SERVER_WEB_ROOT env (recommended) to the docker container. 
SERVER_WEB_ROOT not defined
-> `http://<fqdn>/`
SERVER_WEB_ROOT=/kiali
-> `http://<fqdn>/kiali`
The crux of the problem is injecting the path value into Kiali frontend code at deployment time since create-react-app doesn't have any support for doing that. I resorted to shell script trickery to dynamically generate an env js file to be imported by index.html as well as updating `<base href="/path/">` in index.html
- KIALI-1059
- https://github.com/kiali/kiali/issues/321
** Backwards compatible? **
Yes
------
Unit test
``` …
```

KIALI-1059 Support custom context root

---

config/config.go
status/versions.go
status/versions_test.go

This backports the Maistra version check in the Kiali v0.7 branch.
See https://issues.jboss.org/browse/KIALI-1539

KIALI-1539 : Backport Maistra check

---

graph/appender/dead_node_test.go
graph/appender/sidecars_check.go
graph/appender/sidecars_check_test.go
graph/cytoscape/cytoscape.go
graph/options/options.go
handlers/apps_test.go
handlers/graph.go
handlers/graph_test.go
handlers/health_test.go
handlers/namespaces.go
handlers/services_test.go
handlers/testdata/test_namespace_graph.expected
handlers/workloads_test.go
kubernetes/client.go
kubernetes/kubernetes_service.go
kubernetes/kubetest/mock.go
services/business/layer.go
services/business/namespaces.go
services/models/namespace.go

Allows user to run Kiali without granting them cluster wide permissions.
A user will be able to remove the cluser-wide 'kiali' role and the be able to select which namespaces it wants Kiali to have access to.
From the console, it will just appear like that namespace doesn't exist in the OpenShift cluster.
Caveats
- this only affects access to namespaces using the k8s RBAC. Kiali still has access to all the metrics and we don't do anything new in the PR to prevent access to these metrics. The purpose of this is to reduce and control access Kiali has to k8s objects.
- this only really works with Openshift. There really isn't a way in k8s to ask what namespaces a user has access to. Once k8s has that ability it should be easy to add it in. But for now its really …

KIALI-616 Support limited access to namespaces

---

graph/appender/dead_node.go
graph/appender/dead_node_test.go
graph/cytoscape/cytoscape.go

This is adding an exception to the dead node appender. This will allow terminal service nodes to be shown in the graph if those nodes are representing traffic going outside of the cluster.

KIALI-1526 Show services nodes representing egress traffic

---

prometheus/metrics.go

In a "select block" of channels, Go does not guarantee any priority of evaluation. This was leading to a race condition when reading between the "done" channel and the data channels: the "count" variable may be incremented even before respective data was read. This was leading to early termination of the for loop, causing not all data being collected.
The extreme case was if Go evaluates first the "done" case  on all iterations. Under this circumstance, no data will be read and getServiceHealth would return EnvoyServiceHealth{} with zeroes.
The channel read-race condition was also leading to sporadic test failures in CI.
To fix the issue, the "done" channel is removed by ensuring that data and error channels always return a value.

KIALI-1429 Fix channel read race condition

---

.gitignore

Running `pytest` produces some files for caching purposes. As they are not intended to be tracked, I propose to add them into gitignore.
yep.

Ignore cache files from pytest e2e suite

---

config.yaml
config/config.go
deploy/kubernetes/kiali-configmap.yaml
deploy/openshift/kiali-configmap.yaml

All generated images (both up and downstream) uses the /opt/kiali path
as base, and /opt/kiali/console for the UI. This change reflects that.

Change default path for console

---

graph/cytoscape/cytoscape.go
handlers/graph.go
handlers/testdata/test_multi_namespace_graph.expected
handlers/testdata/test_namespace_graph.expected

Per UXD, when there is both HTTP and TCP traffic between two nodes, there should be two edges between those nodes representing each kind of traffic.
These changes will generate to a graph like this:

KIALI-1401 Allow one edge for HTTP and one for TCP

---

graph/appender/security_policy.go
handlers/graph.go

- also improve readability:
- remove some dead code
- remove escaped-quotes from some query strings
- use %s (as opposed to %v) where appropriate in sprintf

KIALI-1598 Support service node detail graph

---

services/business/checkers/destination_rules/multi_match_checker.go
services/business/checkers/destination_rules/multi_match_checker_test.go
services/business/istio_validations.go

All offending DestinationRules should be flagged with WARN, not just the last one. Also, fix a typo that caused the warnings to be filtered and add the warns to the config listing also.

KIALI-1578 KIALI-1136 Show WARN on all DRs with duplicate hosts

---

graph/appender/unused_node.go
graph/appender/unused_node_test.go
graph/graph.go
graph/options/options.go
handlers/graph.go
handlers/graph_test.go
handlers/testdata/test_multi_namespace_graph.expected
handlers/testdata/test_namespace_graph.expected

- Service graphs are produced by generating a workload graph with service injection,
and then reducing it to only service nodes by removing the workload nodes
aggregating their outgoing edges.
- add logic to unused_appender to decide if it is applicable (it's not applicable to service graphs)
Also:
- change default graph type to workload (not related to this but makes sense)
- remove some unnecessary fields on graph.Options

KIALI-1534 Introduce Service GraphType

---

hack/istio/install-istio-via-helm.sh

This is a hack script that can install Istio + Kiali into an existing k8s or OS cluster using the Istio Helm charts.
You can install just Istio (no Kiali) by passing in `-ke false`. You can enable Jaeger and Grafana by passing in `-de true`.
If you want to delete Istio, pass in `-d`.
It should be simple - just have a running OpenShift or K8s cluster (you can use `hack/cluster-openshift.sh -ie false` to start OS without istio), have `helm` installed in your PATH (just grab the helm executable out of the [helm tarball](https://github.com/helm/helm/releases)), and have a cluster CLI executable (oc, kubectl, istiooc) in your path.
Pass in `--help` to the new hack script for details.

hack script to install istio+kiali via helm

---

tests/e2e/tests/conftest.py
tests/e2e/tests/test_kiali_application_endpoint.py
tests/e2e/tests/test_kiali_bookinfo_namespace_endpoint.py
tests/e2e/tests/test_kiali_graph_badges.py
tests/e2e/tests/test_kiali_istio_endpoint.py
tests/e2e/tests/test_kiali_service_endpoint.py
tests/e2e/tests/test_kiali_workload_endpoint.py

Increase timeouts around Badge tests 'oc' commands due to slow Openshift cluster response.
Method name change, as well.

KIALI-1674 - Increase Timeouts For Badge Tests

---

services/business/apps.go
services/business/workloads.go

0-value of slices is nil, not empty slice. Although nil slice behaves very much like empty slice, it is serialized as nil in json. So should be avoided.
JIRA: https://issues.jboss.org/browse/KIALI-1710

KIALI-1710 explicitely initialize slices as empty

---

README.adoc

I think it's more correct to reformulate the question, because Kiali doesn't know anything about what a service is doing, beyond its interactions. We have no idea of the services business value.
See also https://github.com/kiali/kiali.io/pull/20

Readme: change intro question

---

services/business/checkers/destination_rules/multi_match_checker.go
services/business/checkers/destination_rules/multi_match_checker_test.go
tests/data/destination_rules_data.go

Allows multiple destination rules to target the same host, but not the combination of same host+subset

KIALI-1551 Only same subset sharing is considered duplicate DR

---

services/business/checkers/destination_rules/multi_match_checker.go

Showing multimatch DR validation properly in ACEditor. See the screenshots for better understanding.
https://issues.jboss.org/browse/KIALI-1727
Error:
Fix:

KIALI-1727 Fix how multimatch destination rule validation is shown in ACEditor

---

CONTRIBUTING.md

Provide contributions guide

---

business/health.go
handlers/health.go
models/health.go
prometheus/client.go
prometheus/metrics.go
prometheus/prometheustest/client_test.go
prometheus/prometheustest/mock.go

This is to support health indication on service nodes in the graph.  See kiali-ui PR https://github.com/kiali/kiali-ui/pull/744
@jotak Please take a look.  The changes should be analogous to what was already there for namespace app and namespace workload health.

KIALI-1728 Add support for namespace service health

---

business/checkers/virtual_services/single_host_checker.go
business/checkers/virtual_services/single_host_checker_test.go

Starting with Istio 1.0.1, multiple virtual services for the same host are allowed if the VSs are bound to a gateway.
This PR prevent Kiali to show a warning in whenever this situation is reached.
https://issues.jboss.org/browse/KIALI-1616
Yes.
** Screenshot **
Before:
After:
When the VS has a gateway:
When the VS doesn't have any gateway:
(warning message: More than one virtual service for the same host)
When the VS doesn't target the same host:
(host changed to myapp.org)

KIALI-1616 A VirtualService sharing a host is valid if it has gateway

---

.travis.yml

@jmazzitelli @cfcosta @xeviknal 
In our documented process to release snapshots, we ask to modify this part of the travis script: see https://docs.jboss.org/display/KIALI/How+to+create+the+weekly+snapshot+version+for+KIALI#app-switcher
But is there a reason why this isn't commited directly in master? Would it damage anything to have travis always building *-snapshot branches or tags?

Allow to build docker images for snapshots

---

status/versions.go

Reverting this additional "kialiConfig" import alias - no idea what it was added, but it is not needed and it breaks the build now that a PR was merged that used the original "config" import name.

remove unnecessary import alias to fix broken build

---

business/istio_config.go
business/istio_config_test.go
kubernetes/client.go
kubernetes/kubernetes_service.go
kubernetes/kubetest/mock.go
models/istio_config.go

Reverts kiali/kiali#554
This PR is logically correct, but introduces a performance penalty.
So we are going to remove it from master until we can put in place a cache (similar as istio uses in adapters to query objects).

Revert "KIALI-1661 Provide permissions on istio objects"

---

business/apps.go
business/apps_test.go
business/health.go
business/test_util.go
handlers/apps.go
handlers/apps_test.go
handlers/workloads.go
kubernetes/filters.go
models/app.go
models/health.go

There is a corner case that may happen.
Application with Pods as workload with no controllers; at some point, Pods are deleted, but a service is still active.
On this scenario an app with no workloads it's necessary as it is not covered and there could be an app in the graph linking to a non valid app.

KIALI-1738 Support app without workload

---

deploy/kubernetes/kiali.yaml
deploy/openshift/kiali.yaml

…
The change adds liveness and readiness probes for the Kiali pods for Kubernetes and OpenShift. It does so by probing path "/api/status".
KIALI-1497 

KIALI-1497 Create liveliness and ready probes for Kiali pod (fixes #540)

---

Makefile

Release v0.9.0 is done. Now, repo is pointing to 0.10.0 version.
https://issues.jboss.org/browse/KIALI-1756

KIALI-1756 Preparing for release 0.10.0-SNAPSHOT

---

graph/appender/appender.go
graph/appender/dead_node.go
graph/appender/dead_node_test.go
graph/appender/istio_details.go
graph/appender/response_time.go
graph/appender/security_policy.go
graph/appender/sidecars_check.go
graph/appender/sidecars_check_test.go
graph/appender/unused_node.go
graph/options/options.go
handlers/graph.go
models/workload.go

- cache global and namespace-level info so appenders can reuse it
- update sidecars_check appender to leverage business package support because it already determines whether the backing workload's pods have a sidecar
- redo dead_node appender logic for flagging egress nodes, it was very slow
TODO: Update tests
TODO: replace business layer call in dead_node appepender when it performs
@jmazzitelli This can be tested/reviewed but is not ready for merge until the TODOs are complete

KIALI-1757 Perf improvements for graph appenders

---

business/checkers/virtual_services/no_gateway_checker.go
kubernetes/istio_details_service.go

Gateway validation shown in wrong place
https://issues.jboss.org/browse/KIALI-1776
Yes
The bug is because "path" field in validation result is empty, so the error showed on the first line of ACE editor. And this pr will get the index number of missing gateway during validation, and pass it back to generate full path right at the missing gateway index number. And the result will be like:

KIALI-1776 Gateway validation shown in wrong place

---

deploy/kubernetes/kiali.yaml
deploy/openshift/kiali.yaml

Undoing https://github.com/kiali/kiali/pull/563 for now until we come up with a better solution.  I was hoping to simply increase the polling intervals, but I discovered that the probe endpoints won't work if users deploy Kiali under a custom web root. (see comments in KIALI-1497 for more details).
KIALI-1497
** Backwards compatible? **
Yes

Kiali-1497 Undo health checks

---

README.adoc
business/namespaces.go
config/config.go
config/config_test.go

- remove by default the "technical" namespaces so the user gets a more
focused list and the 'all' namespace does not waste time on them.

KIALI-1812 Add API namespace config to support namespace exclusion

---

business/health_test.go
business/test_util.go
business/workloads.go
business/workloads_test.go

Fetch workload details was wrongly simplified and some corner cases as described in KIALI-1730 were showing different workloads in list/details pages.

KIALI-1730 Unify logic to fetch workload list and workload details

---

business/checkers/virtual_services/no_gateway_checker.go

Due to Github messing up the review on PR #576, here is a patch that should address a code quality issue. Validations should not have dual truth, either we trust the index or we trust the boolean indicating failure. Not a mess of both. This one chooses the boolean since it makes more sense than trying to duplicate the boolean with integers like in C (which is essentially what index -1 does - and since index is a loop counter it can't be negative if valid = false)
Also, simplify code that avoided variable shadowing.

Address PR #576 comments

---

doc.go
graph/appender/appender.go
graph/appender/dead_node.go
graph/appender/istio_details.go
graph/appender/response_time.go
graph/appender/security_policy.go
graph/appender/sidecars_check.go
graph/appender/unused_node.go
graph/options/options.go
swagger.json

I left the old queryParam strings in there for backward compatibility.  We can remove them later if we update the UI (or just leave it).

KIALI-1824 Formalize appender names

---

routing/routes.go

I noticed some names of the routes look wrong - this tries to fix them.

fix what appear to be typos and copy-paste errors in route names

---

business/istio_validations.go
business/istio_validations_test.go
handlers/namespaces.go
handlers/services.go
routing/routes.go
swagger.json

- workloadDetails and appDetails already returned 404, only updated the docs
- Additional checks were added to  serviceValidations and
namespaceValidations to verify the existance of the namespace
and the service.
serviceValidations and namespaceValidations now return 404 instead of 500 if the namespace or service does not exist
~Edit: I need to update the tests.~

KIALI-1783 Resource endpoint now return 404

---

graph/appender/response_time.go
graph/appender/security_policy.go
graph/appender/util.go
graph/options/options.go
hack/run-prometheus.sh
handlers/graph.go
kiali.go
prometheus/client.go
prometheus/internalmetrics/internal_metrics.go
prometheus/metrics.go
routing/router.go
server/server_test.go

This adds a Prometheus scrape endpoint to Kiali and it collects/exposes several metrics to help detect performance issues within Kiali itself.
This also includes a hack script that lets you run a local Prometheus server that can scrape the Kiali endpoint so you can examine the data (this hack script requires you to have Kiali installed with an exposed OpenShift route - you don't have to worry about this if you are deploying via "make openshift-deploy" because that creates the route for you).

KIALI-1820 prometheus scrape endpoint

---

hack/istio/playbooks/README.adoc
hack/istio/playbooks/files/bookinfo-mongodb.yaml
hack/istio/playbooks/files/bookinfo-mysql.yaml
hack/istio/playbooks/files/bookinfo-ratings-v2-mongodb.yaml
hack/istio/playbooks/files/bookinfo-ratings-v2-mysql.yaml
hack/istio/playbooks/files/bookinfo.yaml
hack/istio/playbooks/install_bookinfo.yml

- Bookinfo ansible playbooks (https://github.com/kiali/kiali/tree/master/hack/istio/playbooks) differ from standard bookinfo playbooks available on Istio repository. We use some labeling which is very helpful to differ service, workload, app and pod name (that was created before the complex-mesh on kiali-test-mesh).
- Bookinfo have been updated from 1.8.0 to 1.9.0 (https://github.com/istio/istio/blob/master/samples/bookinfo/platform/kube/bookinfo.yaml) on 1.0.3, so I have added a variable to make it changeable 
- It is causing failures on PR tester (https://paste.fedoraproject.org/paste/T6AiNU9g0EBfGPC~VgyCFA)
`KIALI-1846 Update Bookinfo Ansible Playbooks`

[KIALI-1846] Update Bookinfo Ansible Playbooks

---

business/apps.go
business/health.go
business/istio_config.go
business/istio_validations.go
business/namespaces.go
business/services.go
business/workloads.go
prometheus/internalmetrics/internal_metrics.go

The idea was to first collect this metric for all business layer functions. We can add more as we go.
I only include a single metric collection to the GetNamespaces business function in the first commit because I didn't want to conflict with work currently going on. We can add more as we go along.

KIALI-1840 added a new metric that can let us track the behavior of individual Go funcs

---

README.adoc
config/config.go
kubernetes/client.go
kubernetes/kubernetes_service.go

Main discussion for this issue can be found under the JIRA:
https://issues.jboss.org/browse/KIALI-1843
Reducing permissions scenarios won't work well with k8s cache.
So, instead to add complexity including cache per namespace (and per token in a future) I think it's doable to disable the cache.
I put the cache enabled by default as main scenarios are without security, but it's open to change that on the PR.

KIALI-1843 Enable/disable k8s cache from config

---

business/apps.go
business/health.go
business/istio_config.go
business/istio_validations.go
business/namespaces.go
business/services.go
business/workloads.go
prometheus/internalmetrics/internal_metrics.go
prometheus/internalmetrics/internal_metrics_test.go

This adds a kiali_go_function_failures_total metric.
See the go doc for the GetGoFunctionMetric() method and the SuccessOrFailureMetricType struct for details on typical usage.
Trying to keep the amount of boilerplate code down to a minimum.

KIALI-1848 add error counters for go function metrics

---

deploy/kubernetes/kiali-secrets.yaml
deploy/kubernetes/kiali.yaml
deploy/openshift/kiali-secrets.yaml
deploy/openshift/kiali.yaml

When Kiali was incorporated on Istio, Istio Engineers asked us to change our secrets from password to passphrase (https://github.com/istio/istio/pull/7967/files#r210915209).
That was done on this PR (https://github.com/istio/istio/pull/7326), but it led to a mismatch between our secrets on helm and ansible installer and on the repository, because kiali stills uses password on the master
`KIALI-1823`
cc @jmazzitelli

KIALI-1823 Reconciling Kiali Secrets with Istio Helm Charts Secrets

---

hack/istio/build-istio.sh

This is a hack script that you can use to build Istio. I want to build images for the istio release-1.1 branch, so this script came out of that need. Run with `--help` for usage. But in short, you can do this:
`build-istio.sh -c -b release-1.1 -y -d`
This should build the binaries, build the yaml, and install the images in your local docker.
Unfortunately, I can't get the go tests to pass. So I have not seen this run fully. Would like someone to try to verify this. Just grab the script, put it in your hack/istio directory, and run it with the command I show above and see what you get.

hack script to build upstream istio binaries, including istioctl

---

doc.go
graph/options/options.go
handlers/graph.go
handlers/graph_test.go
routing/routes.go
swagger.json

This changes the REST endpoint for getting namespace graphs:
Endpoint for namespace1:
```
old: .../api/namepaces/namespace1/graph
new: .../api/namepaces/graph?namepaces=namespace1
```
Endpoint for namespace1 and namespace2:
```
old: .../api/namepaces/ignored/graph?namepaces=namespace1,namespaces2
new: .../api/namepaces/graph?namepaces=namespace1,namespaces2
```
Endpoint for all accessible namespaces:
```
old: .../api/namepaces/all/graph
new: .../api/namepaces/graph
```
NO
This requires kiali-ui PR: https://github.com/kiali/kiali-ui/pull/795

KIALI-1542 Improve namespaces graph endpoint

---

Makefile
deploy/kubernetes/kiali-configmap.yaml
deploy/openshift/kiali-configmap.yaml

This requires a change in the gettingstarted/ docs, too - because it requires NAMESPACE env var to be set when running envsubstr - for that change, see https://github.com/kiali/kiali.io/pull/56

KIALI-1868 - define the namespace explicitly

---

tests/e2e/assets/bookinfo-workloads.yaml
tests/e2e/tests/test_kiali_service_endpoint.py
tests/e2e/tests/test_kiali_workload_endpoint.py

Workload list shows now Pods, ReplicationControllers, StatefulSets and ReplicaSets. I have added e2e test verifying that all this types are listed in that endpoint.
In addition, I fixed couple of failing tests from feature of adding permissions to VS and DR (https://github.com/kiali/kiali/pull/612)
https://issues.jboss.org/browse/KIALI-1736

KIALI-1736 Update e2e test to validate that all kinds of workloads are listed

---

business/health.go
business/health_test.go
models/health.go
swagger.json

The overall error rate is detailed into inbound and outbound error rates. This will bring a better idea about where to look for issues.
https://issues.jboss.org/browse/KIALI-1873
** Backwards compatible? ** *yes*
Related UI PR: https://github.com/kiali/kiali-ui/pull/810

KIALI-1873 Provide inbound and outbound error ratios in RequestHealth

---

business/services.go
doc.go
graph/appender/istio_details.go
graph/appender/istio_details_test.go
graph/cytoscape/cytoscape.go
graph/graph.go
graph/options/options.go
handlers/graph.go
handlers/graph_test.go
handlers/testdata/test_app_node_graph.expected
handlers/testdata/test_versioned_app_graph.expected
handlers/testdata/test_versioned_app_node_graph.expected
swagger.json

This PR is provides the backend support for adding groupBy=app support.  Currently we support only groupBy=version (only for versionedApp graphs) .
There are some ui-side challenges here so the PR is currently set to DoNotMerge, and exists only to support the investigation.  In particular, the expanded compound nodes (App Boxes) need to render well a graph subset, minimally at least a two-deep graph from a source service node to one or more destination nodes.  Until now an app box could contain only a grouping of version nodes (typically presented vertically)

KIALI-1670 Support option groupBy=app to group nodes by app label

---

business/checkers/gateway_checker.go
business/checkers/gateways/multi_match_checker.go
business/checkers/gateways/multi_match_checker_test.go
business/istio_validations.go
business/istio_validations_test.go
tests/data/gateway_data.go

Checks that there are no duplicate gateways in any of the namespaces that the application can see. Some notes on scaling though:
* Uses linear search to check for matching hosts
* If performance becomes a real issue, then something more complex like a hostname graph structure or a trie is required. This feels like an overkill in my opinion however at this point.
* Since golang has no unbounded channels, the errChan could get blocked. I've increased the size to 64 and try to avoid writing there, but in theory there's a possibility that the errChan returns len = 0 and it is actually full. In theory.

KIALI-1319 Add multi-namespace gateway multi-match checker

---

kiali.go

Currently, the WebRoot prefix only allows a single path component, ie. `/kiali`, but fails on a WebRoot with multiple components:
```F1113 10:27:49.548275       1 kiali.go:80] web root must begin with a / and contain only alphanumerics: /istio/kiali```
This PR simply allows a `/` in the web root validation regex.
This change should be backwards compatible.

Allow multiple components in WebRoot prefix path

---

business/istio_config_test.go
graph/appender/dead_node.go
models/destination_rule.go
models/gateway.go
models/istio_rule.go
models/istio_rule_test.go
models/quota_spec.go
models/quota_spec_binding.go
models/service_entry.go
models/service_test.go
models/virtual_service.go
swagger.json

Istio Objects mapped in Kiali that will be editable need to bring explicit metadata/spec fields.
https://issues.jboss.org/browse/KIALI-1984
Yes, this requires changes in e2e test and also a PR in the UI to map the changes.

KIALI-1984 Refactor Kiali model to include metadata/spec in Istio config

---

hack/istio/bookinfo-ext-service-entry.yaml

this hack config helps us dev/test with external services.
see kiali-2014 for example why we need this

hack config to create external service in bookinfo

---

business/istio_validations_test.go
business/layer.go
business/workloads.go
business/workloads_test.go
kubernetes/kubetest/mock.go
models/workload.go
prometheus/client.go
prometheus/prometheustest/client_test.go
prometheus/prometheustest/mock.go
swagger.json

Adding the services that are called by an specific workload.
https://issues.jboss.org/browse/KIALI-1140
This goes along a UI feature that will list those services in the workload details: https://github.com/kiali/kiali-ui/pull/839

KIALI-1140 Add destination services for workload details endpoint

---

graph/appender/appender.go
graph/appender/dead_node.go
graph/appender/dead_node_test.go
graph/options/options.go

ServiceEntry objects with MESH_EXTERNAL definitions were getting stripped out by the dead node appender. This fixes it.
KIALI-2014 Support ServiceEntry in Graph
No
Here's what the new graph will look like - notice the egress service node is now showing:

KIALI-2014 make sure dead nodes appender doesn't strip egress nodes

---

kubernetes/kubernetes_service.go

- Openshift based in 3.11 deprecated /version/openshift endpoint
Check if /apis/project.openshift.io exist works to determine if kiali is deployed in an OpenShift cluster based in 3.10 and 3.11.

KIALI-1952 Change IsOpenShift endpoint to support k8s 3.11

---

doc.go
graph/appender/appender.go
graph/appender/dead_node.go
graph/appender/dead_node_test.go
graph/appender/service_entry.go
graph/appender/service_entry_test.go
graph/cytoscape/cytoscape.go
graph/options/options.go
swagger.json

- extracts service entry handling from dead_node appender into more robust dedicated appender
- changes node flagging from isEgress=true to isServiceEntry="MESH_EXTERNAL"|"MESH_INTERNAL"
not totally, will require UI update along with server update to get proper handling for service entries
This PR works with UI PR https://github.com/kiali/kiali-ui/pull/854

KIALI-2031 Add service_entry appender (appenders=serviceEntry)

---

hack/istio/bookinfo-ext-service-entry.yaml

this is so you can easily control-c to kill the process. Otherwise, you need to go in another console window and docker kill it

trivial change to a comment in order to document the -t and -i 

---

README.adoc
doc.go
handlers/grafana.go
handlers/grafana_test.go
routing/routes.go
swagger.json

- Fix documentation
- Fix when grafanaConfig.DisplayLink=false, should not expect an URL to be set
- Fix returned HTTP codes (must be 5xx and not 4xx for invalid configuration)
- Regenerate swagger
JIRA: https://issues.jboss.org/browse/KIALI-2056
cf also #690

KIALI-2056 Few fixes around grafana links

---

routing/router.go
routing/routes.go
swagger.json

- Rename description swagger to be consistent with convetion
- GetToken => getToken
- Root => root
- Set StrictSlash to true to 
```go
When true, if the route path is "/path/", accessing "/path" will perform a redirect
// to the former and vice versa. In other words, your application will always
// see the path as specified in the route.
```
JIRA: [KIALI-1969](https://issues.jboss.org/browse/KIALI-1969
)  [KIALI-1994](https://issues.jboss.org/browse/KIALI-1994)
@gbaufake Can you check if tehre is /api/api routes? I didn't see them

KIALI-1969 KIALI-1994 Some Endpoints have double /api when swagger file is parsed / Root Swagger API is directing to an error

---

server/server_test.go

Test is stuck for 60s in function "checkHTTPReady", because it gets an error when probing "/" URL (too many redirects).
Fixed by probing "/status".

Fix server_test waiting 60s

---

deploy/get-console.sh

There are some environments where the version of git does not
have available the -C option.
Fixing the issue by using `cd`-ing.
https://issues.jboss.org/browse/KIALI-2067

KIALI-2067 Fix unrecognized git option in script

---

business/checkers/gateways/multi_match_checker.go
business/checkers/gateways/multi_match_checker_test.go
business/checkers/virtual_service_checker_test.go
business/checkers/virtual_services/subset_presence_checker.go
business/checkers/virtual_services/subset_presence_checker_test.go

'Subset not found' validations doesn't leave the validation as invalid since it is a warning.
https://issues.jboss.org/browse/KIALI-1954
yes
Before:
After:

KIALI-1954 Subset Presence Checker does not invalidate any object

---

doc.go
handlers/apps_test.go
handlers/metrics.go
handlers/metrics_test.go
handlers/namespaces_test.go
handlers/services_test.go
handlers/workloads_test.go
prometheus/metrics.go
prometheus/prometheustest/client_test.go
swagger.json

- Queries now must specify reporter and direction (in/out), avoiding to load much more metrics than necessary
- Response model is adapated, not providing reporter/direction anymore
This is removing from backend some of the business logic about reporter and direction
JIRA: https://issues.jboss.org/browse/KIALI-2086
Frontend PR required: https://github.com/kiali/kiali-ui/pull/871
Yes, metrics API changes, needs frontend PR

KIALI-2086 Optimize and simplify metrics fetching

---

business/namespaces.go
config/config.go
config/config_test.go

I was starting to go through the kiali code and noticed some of it doesn't line up with some basic go linting.  I am volunteering to go through the code and clean it up a bit... This will be the first of many PR's if you are interested. 
n/a
Yes

rename Config.Api -> Config.API

---

config/config.go
config/config_test.go

This PR excludes ibm vendor namespaces from kiali.  I am assuming other vendor's will want to do this as well so I am more than happy to modify the logic a bit to make it easier for vendors to exclude their namespaces
Yes

exclude ibm namespaces

---

tests/e2e/tests/test_kiali_workload_endpoint.py

Metrics API refactoring.
Pushed correct test_kiali_workload_endpoint.py

KIALI-2113 - Refactor Metrics Test Cases Due To KIALI-2086

---

deploy/kubernetes/clusterrolebinding.yaml
deploy/kubernetes/deployment.yaml
deploy/kubernetes/serviceaccount.yaml
deploy/openshift/clusterrolebinding.yaml
deploy/openshift/deployment.yaml
deploy/openshift/serviceaccount.yaml

We need this to remain consistent no matter how kiali is installed. This is important because citadel names the secrets with the name of the service account.

KIALI-2009 change service account name to match maistra and upstream helm

---

business/istio_config.go
business/istio_config_test.go
deploy/kubernetes/clusterrole.yaml
deploy/openshift/clusterrole.yaml
doc.go
handlers/istio_config.go
kubernetes/client.go
kubernetes/istio_details_service.go
kubernetes/kubetest/mock.go
routing/routes.go
swagger.json

Expose a PATCH endpoint to support modification on Istio objects [1][2] with more flexibility.
The new enpoint can be tested as described in the following examples.
Update a DestinationRule
```
PATCH http://admin:admin@localhost:8000/api/namespaces/bookinfo/istio/destinationrules/reviews
Content-Type: application/json
{
"spec": {
"host": "reviews",
"trafficPolicy": null,
"subsets": [
{
"labels": {
"version": "v1"
},
"name": "v1"
},
{
"labels": {
"version": "v2"
},
"name": "v2"
},
{
"labels": {
"version": "v3"
},
"name": "v3"
},
{
"labels": {
"version": "v4"
},
"name": "v4"
}
]
}
}
```
Update an Adapter/Template:
```
PATCH http://admin:admin@localhost:8000/api/namespaces/istio-system/istio/templates/quotas/requestcount
Content-Type: application/json
{
"spec": {
"dimensions": { …
```

KIALI-1654 Add support to modify Istio config objects

---

business/dashboards.go
business/dashboards_test.go
deploy/dashboards/vertx.yaml
doc.go
handlers/apps.go
handlers/metrics.go
handlers/metrics_test.go
handlers/namespaces.go
handlers/services.go
handlers/workloads.go
kubernetes/kiali_monitoring_client.go
kubernetes/kiali_monitoring_types.go
models/dashboards.go
models/dashboards_test.go
prometheus/client.go
prometheus/metrics.go
prometheus/metrics_definitions.go
prometheus/prometheustest/client_test.go
prometheus/prometheustest/mock.go
prometheus/types.go
routing/routes.go
swagger.json

JIRA: https://issues.jboss.org/browse/KIALI-1974
* First commit:
- Load custom dashboards from CRD
- Expose via new route & handler
* Second commit:
- Introduce a new hard-coded Istio dashboard that reuses the dashboard model to build Inbound & Outbound Istio metrics dashboard. The goal is to have the exact same Inbound & Outbound Metrics pages as before, but using new model.
- Create new routes & handlers for these dashboards (for workload, app and service)
Note that these changes should not break anything in the UI. "Old" metrics endpoints are still valid and can still be consumed as before. Graph side panel will continue to use the old _metrics_ routes.

KIALI-1974 Load custom metrics & dashboard

---

business/checkers/gateways/multi_match_checker.go

Istio's type for port is uint32 only in documentation and internally, it exports it as int and turns to int64 in parsing
Thus, we now expect int64 and hope that Istio doesn't fix anything..

Fix subset host+port validation issue

---

business/apps.go
business/dashboards.go
business/layer.go
business/workloads.go
models/app.go
models/dashboards.go
models/pod.go
models/workload.go
swagger.json

JIRA: https://issues.jboss.org/browse/KIALI-1975
- Add CustomDashboards in app & workload details
- Get dashboards by parsing annotation kiali.io/dashboards on pods
- Memoize title to avoid reloading resource to often

KIALI-1975 Runtime monitoring: list available runtimes for app and workload

---

graph/cytoscape/cytoscape.go
graph/options/options.go
handlers/testdata/test_app_graph.expected
handlers/testdata/test_app_node_graph.expected
handlers/testdata/test_complex_graph.expected
handlers/testdata/test_service_graph.expected
handlers/testdata/test_service_node_graph.expected
handlers/testdata/test_versioned_app_graph.expected
handlers/testdata/test_versioned_app_node_graph.expected
handlers/testdata/test_workload_graph.expected
handlers/testdata/test_workload_node_graph.expected
swagger.json

This allows the client to parse out the exact time range the graph represents

KIALI-565 Return graph duration in the JSON

---

graph/appender/response_time.go

The response time appender was adding, as opposed to averaging, response
times when edge aggregation took place.  This mainly affected edges into service
nodes when the service then routed to multiple workloads.

KIALI-2177 Fix issue with inflated response times

---

deploy/kubernetes/deploy-kiali-to-kubernetes.sh
deploy/openshift/deploy-kiali-to-openshift.sh

The install script uses readlink to see if the yaml files are on disk. Even though most people won't (and thus this failure doesn't make a difference other than an error message spit out) let's help out kiali devs that are on MacOS and want to use these install scripts.
Rather than use readlink, do it another way that is supported on linux and macos.

issue 761 - macOS doesn't have readlink - do it another way

---

deploy/kubernetes/deploy-kiali-to-kubernetes.sh
deploy/openshift/deploy-kiali-to-openshift.sh

In the deploy scripts for both openshift and k8s, the use of curl was explicit when downloading the github json which is used to determine the latest release. They should be using the `$downloader` var since some systems don't have curl, but do have wget. We want to support both.
https://issues.jboss.org/browse/KIALI-2187
yes

KIALI-2187 use the downloader var rather than hardcoding curl

---

Makefile

This just changes the Makefile, and so only affects devs.
The defaults for the addon URLs are not necessarily correct (for me, they are never correct). This changes the Makefile to more accurately get the Jaeger and Grafana URLs.

find the true jaeger and grafana URLs to better support different dev evirons

---

hack/cluster-openshift.sh

Adds a flag -nj that removes ES & Jaeger from the cluster after it has been setup. This reduces memory consumption and CPU of the running cluster.

Add the ability to remove Jaeger and ES from the cluster

---

deploy/jenkins-ci/Makefile

https://issues.jboss.org/browse/KIALI-2053
Because of the http://git.io/getLatestKialiKubernetes, a GitHub release
and the DockerHub tag are required so that the script works correctly.

KIALI-2053 Create a GitHub release and a vX.Y tag in DockerHub

---

routing/router.go

https://issues.jboss.org/browse/KIALI-2188
Because of the `StrictSlash(true)` on the root URL, the muxer was redirecting from `$webRoot/` -> to -> `$webRoot` (without trailing slash). However, there is a manual redirection in the opposite way when $webRoot is not '/' (custom context case). This was causing a redirection loop making impossible to access the UI using the root Kiali URL when custom context is configured.
The loop is removed by turning on "StrictSlash" after the manual redirection is configured.

KIALI-2188 Fix root path redirection loop

---

business/checkers/destinationrules/no_dest_checker.go
business/checkers/destinationrules/no_dest_checker_test.go
business/checkers/no_service_checker.go
business/checkers/no_service_checker_test.go
business/istio_validations_test.go
kubernetes/istio_details_service.go
kubernetes/istio_details_service_test.go
tests/data/workload_data.go

Modifies the behavior of NoDestinationChecker to allow any combination of labels, thus stopping the requirement for version & app labels. Adds also simplified way of creating some WorkloadListItems for testing.
KIALI-2021

KIALI-2021 Modify the behavior of the NoDestinationChecker

---

business/istio_validations.go
business/istio_validations_test.go
doc.go
hack/cluster-openshift.sh
handlers/istio_config.go
handlers/namespaces.go
handlers/services.go
kubernetes/istio_details_service.go
models/istio_config.go
models/istio_validation.go
models/service.go
routing/routes.go
swagger.json
tests/e2e/tests/test_api_methods.py
tests/e2e/tests/test_kiali_istio_endpoint.py
tests/e2e/tests/test_kiali_service_endpoint.py

Requires kiali-UI PR 892 to be merged at the same time.
This change will remove the validation endpoints and refactor them to the requested items. This requires changes to the UI part, which are not completed yet. 
Here for comments. I also changed the "istio_validations" to "validate" parameter in the REST-interface as it in my opinion fit the change better.

KIALI-1671 Refactor validations

---

hack/istio/bookinfo-reviews-mirroring.yaml

oc apply this yaml to your bookinfo demo and see mirroring in action (look at traffic going from productpage to reviews).

[hack] adds mirroring to bookinfo reviews

---

.gitignore

Adds .vscode/ to .gitignore to prevent those directories from appearing in the git status / add / commits / etc. These appear when for example using pipenv to run our e2e tests with Python and the VSCode has different settings to defaults (per project).

Ignore VSCode directories for git

---

business/dashboards.go
business/dashboards_test.go
deploy/dashboards/vertx.yaml
kubernetes/kiali_monitoring_types.go
models/dashboards.go
prometheus/client.go
prometheus/prometheustest/mock.go
swagger.json

Use "raw" data type to fetch gauges and counters (without rate)
In CRD, MetricType renamed to DataType and can now hold either raw, rate or histogram
JIRA: https://issues.jboss.org/browse/KIALI-2237
Frontend PR: https://github.com/kiali/kiali-ui/pull/932

KIALI-2237 Runtime metrics: allow raw metrics

---

tests/e2e/tests/test_kiali_istio_endpoint.py

KIALI-1671 got into master with a broken e2e that tries to check ``virtualservices``  equals ``virtualservice``. Fix the typo here.

KIALI-2270 KIALI-1671 Fix e2e test to check against singular name of VS

---

business/istio_config.go
business/istio_config_test.go
business/istio_validations.go
deploy/kubernetes/clusterrole.yaml
deploy/openshift/clusterrole.yaml
handlers/istio_config.go
kubernetes/client.go
kubernetes/istio_details_service.go
kubernetes/kubetest/mock.go
kubernetes/types.go
models/istio_config.go
models/policy.go
swagger.json

Users now can manage Policy Istio Objects within IstioConfig section. Users can Update/Delete those policies too.
https://issues.jboss.org/browse/KIALI-2082
Yes.

KIALI-2082 Add Policy support to IstioConfig

---

business/checkers/destinationrules/no_dest_checker.go
business/checkers/destinationrules/no_dest_checker_test.go
business/checkers/no_service_checker_test.go
business/checkers/virtual_services/no_host_checker.go
business/checkers/virtual_services/no_host_checker_test.go
kubernetes/istio_details_service.go

Currently the validation might show an error in the subset only for DRs, even when the host itself was the issue. Change the validation order to catch the host error first and stop checking the subsets if the host itself is invalid.
With VirtualServices, the host checking was happy if any destination had a valid host. Changed to check all the hosts for validity and make the path for those errors the host instead of the protocol. Also, remove code from kubernetes package as that wasn't used by anything.
KIALI-2260

KIALI-2260 Improve validation rules for DR and VS

---

graph/appender/dead_node.go
graph/appender/dead_node_test.go
graph/appender/unused_node.go
graph/cytoscape/cytoscape.go
graph/protocol.go
handlers/graph.go
handlers/graph_test.go
handlers/testdata/test_app_graph.expected
handlers/testdata/test_app_node_graph.expected
handlers/testdata/test_complex_graph.expected
handlers/testdata/test_service_graph.expected
handlers/testdata/test_service_node_graph.expected
handlers/testdata/test_versioned_app_graph.expected
handlers/testdata/test_versioned_app_node_graph.expected
handlers/testdata/test_workload_graph.expected
handlers/testdata/test_workload_node_graph.expected
swagger.json

- Introduce generic JSON structure for reporting traffic rates
- Add new protocol.go to centralize protocol-specific logic
- with the exception of protocol-specific queries (like for TCP)
THIS PR REQUIRES UI PR https://github.com/kiali/kiali-ui/pull/945 . When both are approved the DNM label can be removed and the two PRs should be merged in tandem.

KIALI-2272 Improve protocol support

---

doc.go
handlers/metrics.go
handlers/metrics_test.go
prometheus/metrics.go
prometheus/types.go
swagger.json

Add a new query parameter to the metrics API such that callers can restrict results to a specific protocol.

KIALI-2291 Support requestProtocol query param in metrics options

---

business/istio_config.go
business/istio_config_test.go
doc.go
handlers/istio_config.go
kubernetes/client.go
kubernetes/istio_details_service.go
kubernetes/kubetest/mock.go
kubernetes/types.go
routing/routes.go
swagger.json

- Adjust the right endpoint in the k8s Api
- Parse object to validate type vs payload
- Reformat JSON object used

KIALI-2034 Fixes for Create Istio Object endpoints

---

business/istio_config.go
business/istio_config_test.go
business/services.go
deploy/kubernetes/clusterrole.yaml
deploy/openshift/clusterrole.yaml
models/istio_config.go
models/service.go
models/service_test.go
swagger.json

We have added a new endpoint for create operations but the changes on clusterrole.yaml were missed.
This is blocker for the feature.
cc @jmazzitelli @gbaufake as these are another changes in the pipeline for Maistra and Istio upstream.

KIALI-2034 Missing create change on clusterrole.yaml

---

config/authentication.go
config/config.go
config/config_test.go
config/security/config_security.go
deploy/kubernetes/deployment.yaml
deploy/openshift/deployment.yaml
kiali.go

log some messages and let the user know a secret needs to be created

KIALI-2303 - do not abort the kiali pod startup when the secret is missing

---

business/checkers/destinationrules/no_dest_checker.go
business/checkers/no_service_checker.go

Currently we validate only against Workloads for both hosts and subsets. This PR modifies the check for pure ServiceEntry / ServiceNames for host checking. This should help the validation issues in istio-system namespace and some other edge cases.
For subset validation, we keep the workloads only validation.
KIALI-2288

KIALI-2288 Add ServiceEntries and serviceNames for DR host validation

---

hack/cluster-openshift.sh

The current hack/cluster-openshift.sh version uses a hardcoded command ``oc`` for status check after installation. If these return incorrect results (or command not found) then this script will never terminate and we'll see the output:
```
Waiting for Istio Deployments to be created........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................... …
```

Use correct oc command in hack for status checks

---

hack/istio/install-istio-kiali-via-helm.sh

looks like istio 1.1 snapshot 5 now requires CRDs to be installed explicitly (before, helm did it for you): https://preliminary.istio.io/docs/setup/kubernetes/helm-install/#option-1-install-with-helm-via-helm-template
this fixes our hack script to do this. You can still use the hack script for earlier versions of istio, just ignore the error message about the crd directory not existing (didn't exist until 1.1-snapshot.5)

istio 1.1 needs to have crds installed explicitly

---

graph/appender/response_time.go
graph/appender/response_time_test.go
graph/appender/unused_node.go
graph/cytoscape/cytoscape.go
graph/protocol.go
handlers/graph.go
handlers/testdata/test_app_graph.expected
handlers/testdata/test_app_node_graph.expected
handlers/testdata/test_complex_graph.expected
handlers/testdata/test_service_graph.expected
handlers/testdata/test_service_node_graph.expected
handlers/testdata/test_versioned_app_graph.expected
handlers/testdata/test_versioned_app_node_graph.expected
handlers/testdata/test_workload_graph.expected
handlers/testdata/test_workload_node_graph.expected
swagger.json

also:
- no longer default %traffic to 100%, it's confusing. Default to 0 like everything else and report 100s.
- change edge to a single traffic protocol, multiple protocols don't make sense.
- allow ResponseTime to accept grpc success code (0)
- Handle KIALI-2297 service edge response time issue
- Handle KIALI-2296 100% label issue
- Handle KIALI-2290 App box side panel issue
- Fix bug with istio namespace unknown traffic rates being doubled
THIS PR REQUIRES UI PR https://github.com/kiali/kiali-ui/pull/957

KIALI-2245 Add gRPC support

---

deploy/openshift/deploy-kiali-to-openshift.sh

When running ``make openshift-deploy`` the tool would look for a ``which oc`` which is not available if only the Maistra version is installed. This change polls for the istiooc from the $PATH also

Accept both istiooc and oc as valid tools when deploying Kiali to OS

---

business/checkers/destinationrules/multi_match_checker.go
business/checkers/destinationrules/multi_match_checker_test.go
business/checkers/destinationrules/no_dest_checker.go
business/checkers/destinationrules/no_dest_checker_test.go
tests/data/destination_rules_data.go

Destination Rules validations now takes into account the mTLS enablers (DR + MeshPolicy combo).
https://issues.jboss.org/browse/KIALI-2147
yep.

KIALI-2147 Change DR validations to support mesh/ns-wide mTLS enabled

---

graph/appender/service_entry.go
graph/appender/service_entry_test.go

Fix for https://github.com/kiali/kiali/issues/823

KIALI-2344 ServiceEntry.location is optional

---

business/checkers/no_service_checker_test.go
business/checkers/virtual_services/no_host_checker.go
business/checkers/virtual_services/no_host_checker_test.go

If there are multiple http routes with validation issues in the latter parts, then the validation is displayed in the wrong place. This adds index to the protocol part.
KIALI-2323

KIALI-2323 Add index to the protocol yaml path

---

business/istio_config.go
business/istio_config_test.go
business/namespaces.go
deploy/kubernetes/clusterrole.yaml
deploy/openshift/clusterrole.yaml
kubernetes/client.go
kubernetes/istio_details_service.go
kubernetes/kubetest/mock.go
kubernetes/types.go
status/mtls_status.go
status/status.go
tests/data/mesh_policy_data.go

We need to show whether or not mTLS is globally enabled or not. This PR adds that status in `/api/status` endpoint.
The idea is that the ui takes it and prints a padlock into the masthead.
https://issues.jboss.org/browse/KIALI-2148
yep.

KIALI-2148 Adding mTLS status into status endpoint

---

deploy/dashboards/nodejs.yaml

JIRA: https://issues.jboss.org/browse/KIALI-2348
For testing, I used this sample app: https://github.com/jotak/nodejs-metrics-example
And as always, dashboard has to be manually created :
```
oc apply -f deploy/dashboards/nodejs.yaml
```

KIALI-2348 Build node.js dashboard

---

business/dashboards.go
handlers/metrics.go
kubernetes/kiali_monitoring_types.go
prometheus/client.go
prometheus/prometheustest/mock.go
prometheus/types.go

JIRA: https://issues.jboss.org/browse/KIALI-2362
This allows to:
- Hard-define the operator to use in the dashboard definition
- Or let the client (UI) decide which to use, if no hard definition
Frontend: https://github.com/kiali/kiali-ui/pull/985

KIALI-2362 Allow different operators than "sum" for raw metrics

---

business/checkers/virtual_services/no_gateway_checker.go
business/checkers/virtual_services/no_gateway_checker_test.go
kubernetes/istio_details_service.go

gateways section in the VirtualService definition has a list of gateways, which we assume to be in a service-name only format. This patch allows the FQDN format to be used as well (Istio documentation does not mention which format is correct).
KIALI-2371

KIALI-2371 Accept FQDN format for gateway name in VS

---

business/checkers/destination_rules_checker.go
business/checkers/destinationrules/multi_match_checker.go
business/checkers/destinationrules/traffic_policy_checker.go
business/checkers/destinationrules/traffic_policy_checker_test.go
business/istio_config.go
business/istio_validations.go
business/istio_validations_test.go
business/layer.go
kubernetes/types.go
models/istio_validation.go
tests/data/destination_rules_data.go

This PR adds a warning into IstioConfig section whenever a Destination Rule doesn't specify any tls and there is one Destination Rule setting up a non-local TLS rule.
https://issues.jboss.org/browse/KIALI-2094
yes
** screenshots **
With warnings:
No trafficPolicy mentioned:
No TLS references in trafficPolicy level:
No TLS references in Port Level
Without warning scenarios:
There are no warnings when you have TLS settings in either trafficPolicy or port level.
All the yamls tested are compressed in here: [kiali-2094.zip](https://github.com/kiali/kiali/files/2861244/kiali-2094.zip)

KIALI-2094 Destination Rule validation when TLS not mentioned and non-local DR present

---

business/checkers/destinationrules/multi_match_checker.go
business/checkers/destinationrules/no_dest_checker.go
business/checkers/destinationrules/traffic_policy_checker.go
business/checkers/gateways/multi_match_checker_test.go
business/checkers/no_service_checker.go
business/checkers/virtual_services/no_gateway_checker.go
business/checkers/virtual_services/no_gateway_checker_test.go
business/istio_config_test.go
business/istio_validations.go
business/istio_validations_test.go
kubernetes/istio_details_service.go
kubernetes/types.go
tests/data/gateway_data.go

If FQDN format is used for the given gateway host, check against all namespaces and their gateways for a match. We already check all namespaces for gateway existing, so doing it for the VirtualServices makes sense also.
Also, added Host type to the kubernetes/types.go since this format is used in multiple places. Might be worth doing all internal checks with FQDN in the future (but this PR only adds that to few places).
KIALI-2390, issue #767 
Yes

KIALI-2390 Allow VirtualService gateway check to validate all namespaces

---

config/config.go

This struct is sent to the client for getting server config, so its fields need to be correctly written in json.
Frontend PR: https://github.com/kiali/kiali-ui/pull/997

Fix json camelCase on istio labels

---

business/checkers/virtual_services/subset_presence_checker.go

In theory, when Gallely is working, the VS/DR should be well formed, but if not, there can be a boggus resource which need extra check for nil values.
https://issues.jboss.org/browse/KIALI-2419

KIALI-2419 Subset name can be nil if Galley is not acting

---

business/checkers/destinationrules/no_dest_checker.go
business/checkers/no_service_checker.go
business/checkers/virtual_services/no_host_checker.go
kubernetes/istio_details_service.go
tests/data/virtual_service_data.go

Changes the type checking to match []interface{} first for hosts to match correctly the type. Also, changed the parsed datatype internally to make it easier to call for different purposes (such as when no protocol is known).
KIALI-2425

KIALI-2425 Fix ServiceEntry parsing for validation

---

models/istio_validation.go

Updating wording for destinationrules.nodest.matchingworkload.
Related to: https://github.com/kiali/kiali.io/pull/99

Better wording for destinationrules.nodest.matchingworkload validation

---

kubernetes/client.go

Minor.
The Perf debug was intended when using caches and reusing clients.
There are some use cases that are not very clear why it can be the cliend re-used but meanwhile we work on that, this Infof is not necessary.
Moving to Debugf instead.

Change perf info to Debugf

---

business/checkers/gateway_checker.go
business/checkers/gateways/port_checker.go
business/checkers/gateways/port_checker_test.go
business/istio_validations.go
kubernetes/istio_details_service.go
kubernetes/istio_details_service_test.go
models/istio_validation.go

Adds validation to the portname for gateways as it must match the Istio rules for the routing to work correctly
https://istio.io/docs/setup/kubernetes/spec-requirements/
KIALI-2434

KIALI-2434 Check the portname form

---

graph/appender/security_policy.go
graph/appender/security_policy_test.go
graph/cytoscape/cytoscape.go
swagger.json

@mwringe This may or may not be useful based on how we want to handle "partial mtls" but it's ready to support any UI-side POC that would need it.

KIALI-2332 Report isMTLS as a percentage of traffic

---

deploy/openshift/clusterrole.yaml

Grants the Kiali service account permission to access routes.
This was incorrectly setup in a previous PR but it was not applied correctly. This fixes the problem.
https://issues.jboss.org/browse/KIALI-2458

KIALI-2458 Grant Kiali permission to access routes

---

business/checkers/mesh_policies_checker.go
business/checkers/meshpolicies/mtls_checker.go
business/checkers/meshpolicies/mtls_checker_test.go
business/istio_config.go
business/istio_validations.go
business/istio_validations_test.go
kubernetes/istio_details_service.go
models/istio_validation.go
tests/data/mesh_policy_data.go

Adding a validation checking for a missing Destination Rule enabling mTLS mesh-wide when a MeshPolicy is present.
https://issues.jboss.org/browse/KIALI-2093
https://github.com/kiali/kiali.io/pull/104

KIALI-2093 - Verify rules for both sending+receiving are enabled

---

handlers/grafana.go
prometheus/metrics.go

... and change log.Info to log.Debug in metrics calls
This allows the user to set URL in config as "http://grafana-server" or "http://grafana-server/"

Minor change: allow trailing "/" in grafana url,

---

config/config.go
handlers/authentication.go
handlers/oauth.go
kiali.go

I was looking in this code and noticed we are using hardcoded strings throughout for the strategy names - these should be constant variables so we don't screw it up later with typos

should not be using hardcoded strings - use constants

---

deploy/dashboards/springboot-jvm.yaml
deploy/dashboards/springboot-tomcat.yaml
deploy/kubernetes/deploy-kiali-to-kubernetes.sh
deploy/openshift/deploy-kiali-to-openshift.sh

JIRA: https://issues.jboss.org/browse/KIALI-2405
Tomcat dashboard (tomcat is springboot default's webserver)
JVM metrics
For testing, you can use the new bookinfo-runtimes : https://github.com/jotak/bookinfo-runtimes
- run the `deploy-all.sh` script
- install the new dashboards from this PR (either directly or redeploy kiali)
- if you don't run the latest istio, you have to update once again prometheus config map (see `bookinfo-runtimes` readme)

KIALI-2405 Spring Boot dashboards

---

kubernetes/istio_details_service.go
kubernetes/istio_rules_service.go
kubernetes/types.go
models/cluster_rbac_config.go
models/destination_rule.go
models/gateway.go
models/istio_rule.go
models/mesh_policy.go
models/policy.go
models/quota_spec.go
models/service_entry.go
models/service_role.go
models/virtual_service.go
swagger.json

It adds mapping for "kind" and "apiVersion" objects from the backend.
Note that these fields are not returned from the k8s API (those are empty), so it should be provided by kiali.
https://issues.jboss.org/browse/KIALI-2442

KIALI-2442 Map kind and apiVersion attributes

---

business/checkers/destination_rules_checker.go
business/checkers/destinationrules/meshwide_mtls_checker.go
business/checkers/destinationrules/meshwide_mtls_checker_test.go
business/checkers/meshpolicies/mtls_checker_test.go
models/istio_validation.go

Add validation to any DR enabling mesh-wide mTLS when there isn't any MeshPolicy enabling mTLS.
https://issues.jboss.org/browse/KIALI-2457
** Screenshot **

KIALI-2457 Add validation to Destination Rule enabling Mesh-wide mTLS for clients

---

deploy/kubernetes/clusterrole.yaml
deploy/openshift/clusterrole.yaml

This PRs adds an additional "kiali-viewer" role than can be used manually in restricted scenarios.
It doesn't modify any clusterrolebinding.

KIALI-2325 Add a read only role for kiali

---

hack/istio/istio-mtls-meshwide.yaml

Adding a hack yaml which enables meshwide mTLS to the whole Istio installation.

Add yaml to hack folder to enable mesh-wide mTLS

---

routing/routes.go

mTLS masthead icon stopped to work after changes on authentication
https://issues.jboss.org/browse/KIALI-2542
yes

KIALI-2542 Status endpoint needs credentials to determinate mTLS status

---

handlers/authentication.go
swagger.json

https://issues.jboss.org/browse/KIALI-2501
Front-end is using momentjs library to parse the dates the back-end returns. momentjs library works correctly only with ISO and RFC2822 date formats.
This is returning the date in an RFC2822 compatible date format.
This is the console error that this PR is fixing:

KIALI-2501 Fix browser console deprecated warning message

---

hack/cluster-openshift.sh

Maistra 0.9.0 has renamed yaml files used by cluster-openshift.sh to install Istio:
https://github.com/Maistra/openshift-ansible/tree/maistra-0.9/istio

Update Maistra yaml file in hack script

---

business/checkers/destinationrules/no_dest_checker.go
business/checkers/destinationrules/no_dest_checker_test.go
business/checkers/no_service_checker.go

For NoDestinationChecker, first filter the WorkloadList to the correct service and only then check that labels are found correctly.
Fixes issue #800

KIALI-2521 Fix issue #800 by checking subset labels from a correct service

---

business/checkers/gateway_checker.go
business/checkers/service_entry_checker.go
business/checkers/serviceentries/port_checker.go
business/checkers/serviceentries/port_checker_test.go
business/istio_validations.go
tests/data/gateway_data.go
tests/data/service_entry_data.go
tests/data/virtual_service_data.go

ServiceEntries require the same port name checking as Gateways. This PR enables checks for ServiceEntries as well as uses the same validation code as Gateways.
KIALI-2436
Part of another JIRA (KIALI-2451)

KIALI-2436 Verify ServiceEntry port format

---

graph/options/options.go
handlers/config.go

Use Prometheus' model.ParseDuration as opposed to time.ParseDuration when
parsing a duration relevant to Prometheus.  Prom durations support a larger
set of period suffixes, like 'd' for days.
I tried this out manually by redeploying prom with 1d.  I saw the failure before the fix, and then success with the fix.

KIALI-2557 Ensure prometheus durations are parsed with prom utility

---

graph/appender/unused_node.go
graph/appender/unused_node_test.go
graph/cytoscape/cytoscape.go
swagger.json

The unused graph appender should limit itself to elements with true backing
definitions.  The edges generated by the appender are anticipated but don't
actually have any backing time series, and can be confusing or misleading.
It is not required for running but this PR goes with UI PR https://github.com/kiali/kiali-ui/pull/1066

KIALI-2544 remove unused edges

---

handlers/grafana.go

When fetching the Grafana service information, use the Kiali service account token instead of the user token.
This prevents issues when using OpenShift Oauth and the user doesn't have access to the Grafana service.
https://issues.jboss.org/browse/KIALI-2505

KIALI-2505 Fix error when fetching Grafana info with oauth

---

business/istio_config.go
business/istio_validations.go
deploy/kubernetes/clusterrole.yaml
deploy/openshift/clusterrole.yaml
handlers/istio_config.go
kubernetes/client.go
kubernetes/istio_details_service.go
kubernetes/kubetest/mock.go
kubernetes/types.go
models/istio_config.go
models/rbac_config.go
swagger.json

List only resources that are available in Istio into IstioConfig.
In case the cluster doesn't have that resource available, it returns an empty array.
https://issues.jboss.org/browse/KIALI-2563

KIALI-2563 List RBAC resources only if cluster specifies those resources

---

hack/istio/install-bookinfo-demo.sh
hack/istio/install-istio-kiali-via-helm.sh

@jshaughn this is what we were talking about - when installing istio and bookinfo, the hack scripts should use the last istio that was downloaded

hack scripts should use the last Istio release that was downloaded

---

kiali.go

Without this fix, custom context root paths cannot be used.
https://github.com/kiali/kiali/issues/927

issue 927 - fix custom context root bug

---

README.adoc
config/config.go
handlers/config.go

When running multiple clusters it can be so confusing which one kiali is looking at. This PR adds a new config variable that can be used to identify a kiali installation.
UI PR - [#1079](https://github.com/kiali/kiali-ui/pull/1079)
[JIRA KIALI-1987](https://issues.jboss.org/browse/KIALI-1987)
No
Yes

KIALI-1987 Add a new env var to tag the kiali installation

---

routing/router.go
server/server_test.go

If the root context path is not "/", and a request comes in for "/", help the user out by forwarding to the true context root. This means a request to "/" will never result in a 404 - it will be forwarded to the true root context.
https://issues.jboss.org/browse/KIALI-2548

KIALI-2548 forward "/" requests to the real root context path

---

models/dashboards.go
models/dashboards_test.go

(Not for inbound metrics, as it doesn't make much sense there)

KIALI-2607 Add Remote service label for outbound metrics

---

business/checkers/destination_rules_checker.go
business/checkers/destinationrules/disabled_namespacewide_mtls_checker.go
business/checkers/destinationrules/disabled_namespacewide_mtls_checker_test.go
business/checkers/destinationrules/meshwide_mtls_checker.go
business/checkers/destinationrules/namespacewide_mtls_checker.go
business/checkers/destinationrules/namespacewide_mtls_checker_test.go
business/checkers/mesh_policies_checker.go
business/checkers/meshpolicies/mesh_mtls_checker.go
business/checkers/meshpolicies/mesh_mtls_checker_test.go
business/checkers/policies/namespace_mtls_checker.go
business/checkers/policies/namespace_mtls_checker_test.go
business/checkers/policies_checker.go
business/istio_validations.go
business/istio_validations_test.go
business/tls.go
kubernetes/istio_details_service.go
kubernetes/istio_details_service_test.go
kubernetes/types.go
models/istio_validation.go

* Adding validations for enabling ns-wide mTLS scenarios (Destination Rules and Policies)
* Adding validations for disabling ns-wide mTLS scenarios (Destination Rules and Policies)
https://issues.jboss.org/browse/KIALI-2551
yes.
** Testing files **
[test-files.zip](https://github.com/kiali/kiali/files/2991563/2551.zip)
It contains three scripts that runs the scenarios covered by each one of the checkers introduced in this PR.

KIALI-2551 Adding ns-wide mtls validations

---

business/services.go
business/workloads.go
business/workloads_test.go
models/service.go
models/service_test.go
models/workload.go
prometheus/client.go
prometheus/prometheustest/client_test.go
prometheus/prometheustest/mock.go
swagger.json

This is code cleanup.
The destinationServices attribute of the WorkloadDetails endpoint and the dependencies attribute of the ServiceDetails endpont are no longer used in the front-end. Thus, removing this data from the JSON and also removing all involved code.
This is, probably, non-backwards compatible for the front-end side, since there will be missing JSON properties.

KIALI-2610 Remove unused data from Services and Workload details endpoints

---

deploy/kubernetes/configmap.yaml
deploy/kubernetes/deploy-kiali-to-kubernetes.sh
deploy/openshift/deploy-kiali-to-openshift.sh

When installing using OpenShift and there is no AUTH_STRATEGY specified it will ask if they want to use the login or OAuth option.
It will also check if the AUTH_STRATEGY is 'login' before asking for login credentials to be added (a username and password are only needed if the auth strategy is login. So there is no need to ask if we are not using 'login').
It also fixes a bug where if you run the install multiple times it will not update the Kiali installation. For instance, we could update the configmap or secret but since the deployment is not updated the Kiali pod wont get redeployed. Now we explicitly delete the Kiali deployment before doing the install.
https://issues.jboss.org/browse/KIALI-2644

KIALI-2644 Add in ability to specify the login type during install

---

business/layer.go
handlers/utils.go
kubernetes/client.go
kubernetes/client_factory.go
kubernetes/client_factory_test.go
kubernetes/kubetest/mock.go
prometheus/internalmetrics/internal_metrics.go

Instead of creating a new k8s client on each request, we store in memory the clients. If a client is not used in 15 minutes, it is deleted. This is done for performance reasons.
A new metric ('kiali_kubernetes_clients') tracks how many clients are in use at any given time.
https://issues.jboss.org/browse/KIALI-2506

KIALI-2506 Cache K8S clients between requests

---

Makefile
deploy/kubernetes/deploy-kiali-to-kubernetes.sh
deploy/openshift/deploy-kiali-to-openshift.sh

-- the Makefile didn't pass through the strategy for the k8s-deploy target - this fixes that
-- the install scripts now echo a message when the secret creation is skipped so its obvious what is going on
-- get the scripts to look more identical (trying to keep these more or less in sync with each other, minus differences required between k8s and OS)

fix some things I noticed while testing KIALI-2644

---

handlers/graph.go
handlers/graph_test.go
handlers/testdata/test_app_graph.expected
handlers/testdata/test_app_node_graph.expected
handlers/testdata/test_service_graph.expected
handlers/testdata/test_versioned_app_graph.expected
handlers/testdata/test_versioned_app_node_graph.expected
handlers/testdata/test_workload_graph.expected
handlers/testdata/test_workload_node_graph.expected

https://issues.jboss.org/browse/KIALI-2556
This will let the front-end know that this node cannot be examined further in detail pages, metrics, etc.

KIALI-2556 Set the inaccessible flag to the unknown destination service

---

business/checkers/gateway_checker.go
business/checkers/service_entry_checker.go

ServiceEntries and Gateways returned validation results only in case of errors, not when there's success. This adds positive results also and fixes the UI's view of "valid/false" for these object types.
KIALI-2562

KIALI-2562 Return a validation success also for each enabled type

---

graph/appender/istio_details_test.go
models/virtual_service.go

The way we were determining if a service in a graph had its traffic affected by a virtual service was wrong. We were assuming that the virtual service 'host' value would correspond to the hostname of the service, when it can be any valid hostname.
This change brings how the graph does its VS detection in line with how the service detail pages does things (which does correctly detect the virtual services).
https://issues.jboss.org/browse/KIALI-2155
This will change how VS badges are detected in the graph. They will now be in line with how the details page does things.
Meshes should now have their VS badge applied where appropriate to indicate that the traffic could have been modified by a VS.

KIALI-2155 Update the graph VS detection

---

hack/cluster-openshift.sh
hack/knative/config-domain.yaml
hack/knative/deploy-hello-world.sh
hack/knative/service.yaml

This patch enables support to installing knative on Openshift, as well as installing a sample application that can be used for testing.
Running `hack/cluster-openshift.sh up -kn true` prepares the cluster, installs knative and deploys a simple application.
```bash
DOMAIN="$(oc get route -n istio-system istio-ingressgateway --output=custom-columns=ROUTE:.spec.host | grep -v ROUTE | sed 's/istio-ingressgateway-istio-system.//g')"
INGRESS_IP="$(oc get svc istio-ingressgateway --namespace istio-system --output 'jsonpath={.status.loadBalancer.ingress[0].ip}')"
curl -H "Host: helloworld-go.knative-examples.knative.${DOMAIN}" "http://${INGRESS_IP}"
```
The response should be `Hello Go Sample v1!`, and changing the variable on `hack/knative/service.yaml` should change the result.
```bash
oc …
```

Add knative support to cluster-openshift.sh

---

deploy/kubernetes/clusterrole.yaml
deploy/openshift/clusterrole.yaml
kubernetes/types.go

Update adapters/templates code to support old CRD way to install/configure adapters (with one CRD per item) or new way with generic "adapter"/"template"/"handler"/"instances" way.
Note, that Istio 1.1 maintains old way, in Istio 1.2 the old CRD will be removed and that will highly simplify the logic as no need to fetch specific CRD code.
https://issues.jboss.org/browse/KIALI-2638
Yes, this modifies clusterrole.yaml as usual an it needs updates in upstream and downstream.
cc @gbaufake @jmazzitelli 
Note, this is a preliminar step towards 3scale integration, so now Kiali can proper list and edit external adapters code:

 KIALI-2638 Add Handlers and Instances to IstioConfig

---

graph/appender/security_policy.go

In the frontend we need to differentiate between non-loaded edges or edges with 0% of mtls traffic.
If we don't have that, then we see this effect in the graph when enabling security layer:
After this change, the effect is the following:
Front-end PR:
https://github.com/kiali/kiali-ui/pull/1089
https://issues.jboss.org/browse/KIALI-2312

KIALI-2312 Security policy appender return 0 values also

---

deploy/kubernetes/deployment.yaml
deploy/openshift/deployment.yaml

See https://issues.jboss.org/browse/KIALI-2664 for why we need this. Basically, moving away from deprecated apiVersions

KIALI-2664 switch to apps/v1

---

business/checkers/destinationrules/disabled_namespacewide_mtls_checker.go
business/checkers/destinationrules/disabled_namespacewide_mtls_checker_test.go
business/checkers/destinationrules/meshwide_mtls_checker.go
business/checkers/destinationrules/meshwide_mtls_checker_test.go

Scenarios fixed:
Scenario 1. 
MeshPolicy that uses PERMISSIVE mode + DestinationRule enabling mTLS traffic.
Problem: DR rule shows validation error: 'MeshPolicy enabling mTLS is missing'.
Expected: No validations shown for that DR.
Explanation: Permissive mode allows all kinds of traffic, mTLS included.
Scenario 2.
MeshPolicy in STRICT mode + DestinationRule enabling mTLS mesh-wide (classic scenario)
Policy ns-level in PERMISSIVE mode + DR disabling mTLS ns-wide.
Problem: DR rule shows validation error: MeshPolicy in strict mode has found, should be permissive.
Expected: No validations shown for that DR.
Explanation: ns-level Policy in PERMISSIVE mode allows disabled mtls connections.
https://issues.jboss.org/browse/KIALI-2668

KIALI-2668 Fixing validations around both ns-wide and mesh-wide mtls

---

handlers/authentication.go
handlers/authentication_test.go

https://issues.jboss.org/browse/KIALI-2497
The endpoint will set the flag if the secret is missing when auth_strategy is the regular login method.
This will allow the front-end to show a warning or an error to the user.
Related front-end PR: https://github.com/kiali/kiali-ui/pull/1105

KIALI-2497 Add secretMissing flag to /api/auth/info endpoint

---

business/test_util.go
business/workloads.go
business/workloads_test.go
deploy/kubernetes/clusterrole.yaml
deploy/openshift/clusterrole.yaml
doc.go
handlers/workloads.go
kubernetes/client.go
kubernetes/kubernetes_service.go
kubernetes/kubetest/mock.go
models/pod.go
routing/routes.go
swagger.json

Starting with a draft PR for this potential feature for dislaying pod logs via the Kiali console.  This is the initial server-side support, adding REST API endpoints for both Pod details and Pod logs.
@jotak If you'd like to take a look or give it a try please do so.  @jmazzitelli , @mwringe, Also take a look if you'd like to test/review/provide feedback.  I'll add you all as reviewers but feel free to take your name off if you're not interested in the draft PR.
*** REQUIRES UI PR: https://github.com/kiali/kiali-ui/pull/1101
** TODO create an upstream PR to change the helm chart for pods/log permission addition

KIALI-577 Server-side REST support for getting pod details and pod logs

---

kiali.go

https://issues.jboss.org/browse/KIALI-2497 (follow-up)
config.Get() is now returning a copy of the config. It cannot be updated anymore by setting fields directly.
To update the config, the full config must be get, then update the fields and, finally, re-set the config.

KIALI-2497 Fix update of secret config

---

business/openshift_oauth.go
deploy/openshift/clusterrole.yaml

Some of the endpoints we were using have now changed in OpenShift 4. This updates to use the newer endpoints.
They updates also work in OpenShift 3, so it should still continue to work for using currently on OpenShift 3. This change doesn't affect people running on kubernetes.
https://issues.jboss.org/browse/KIALI-2671

KIALI-2671: Update endpoints for OpenShift 4

---

graph/appender/response_time.go
graph/appender/security_policy.go
graph/appender/unused_node.go
graph/appender/util.go
handlers/graph.go
handlers/metrics.go

Even debug logging can be voluminous due to the auto-refreshing aspects of the UI.  Make some change to protect against spamming logs.

Kiali 2698 reduce server debug logging

---

kiali.go

- trailing / not allowed (should not happen using the operator, so this is really just a sanity check)

KIALI-2669 Add more validation for custom web root

---

Makefile
deploy/jenkins-ci/Jenkinsfile
deploy/jenkins-ci/Makefile

@israel-hdez please look this over and see if it makes sense/works.
The one part I'm not sure about is:
```
withCredentials([usernamePassword(credentialsId: 'kiali-docker', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USER'), usernamePassword(credentialsId: 'kiali-quay', passwordVariable: 'QUAY_PASSWORD', usernameVariable: 'QUAY_USER')]) {
sh "make -f ${backendMakefile} -C ${backendDir} backend-push-docker"
dockerTag = sh(returnStdout: true, script: "sed -rn 's/^VERSION \\?= v(.*)/v\\1/p' ${backendDir}/Makefile").trim()
quayTag = sh(returnStdout: true, script: "sed -rn 's/^VERSION \\?= v(.*)/v\\1/p' ${backendDir}/Makefile").trim()
```
Not sure what these dockerTag (and now quayTag) are used for.

push kiali image to both docker and quay. operator just goes to quay

---

deploy/jenkins-ci/Makefile

In main makefile, `docker-push` was renamed to `container-push`.
Fixing this in Jenkins Makefile.

Fix main Makefile target invocation that was renamed

---

hack/os-minishift.sh

It adds a command that installs Knative (serving) into the current minishift cluster.
It is a subsequent PR from https://github.com/kiali/kiali/pull/958.
** How to test that **
It should behave like in kiali/kiali#958.
```bash
DOMAIN="$(oc get route -n istio-system istio-ingressgateway --output=custom-columns=ROUTE:.spec.host | grep -v ROUTE | sed 's/istio-ingressgateway-istio-system.//g')"
INGRESS_IP="$(oc get svc istio-ingressgateway --namespace istio-system --output 'jsonpath={.status.loadBalancer.ingress[0].ip}')"
curl -H "Host: helloworld-go.knative-examples.knative.${DOMAIN}" "http://${INGRESS_IP}"
```
The exepected value is: `Hello Go Sample v1!`
https://issues.jboss.org/browse/KIALI-2242
yes

Add knative support to minishift hack script

---

operator/roles/kiali-deploy/templates/kubernetes/clusterrolebinding.yaml
operator/roles/kiali-deploy/templates/kubernetes/deployment.yaml
operator/roles/kiali-deploy/templates/kubernetes/serviceaccount.yaml
operator/roles/kiali-deploy/templates/openshift/clusterrolebinding.yaml
operator/roles/kiali-deploy/templates/openshift/deployment.yaml
operator/roles/kiali-deploy/templates/openshift/serviceaccount.yaml
operator/roles/kiali-remove/tasks/main.yml

everyone uses -service-account in their SA names - do that here. This fixes a problem to get this to run on minikube, too.

KIALI-2726 [operator] fix SA name

---

operator/Makefile
operator/deploy/kiali/kiali_cr.yaml
operator/deploy/kiali/kiali_cr_dev.yaml
operator/roles/kiali-deploy/defaults/main.yml
operator/roles/kiali-deploy/templates/kubernetes/service.yaml
operator/roles/kiali-deploy/templates/openshift/service.yaml

This is so users can indicate if service type should be ClusterIP or LoadBalancer. Default is NodePort.
This is now in the Kiali CR's deployment section. For developers, you can pass this into the operator's make target with the SERVICE_TYPE env var:
```
cd operator
SERVICE_TYPE=ClusterIP make kiali-create
```
The top level Makefile's k8s-deploy (and the openshift-deploy) delegate to this operator Makefile, so this works:
`SERVICE_TYPE=ClusterIP make k8s-delpoy`
See issue #621

KIALI-2723 [operator] be able to configure the service's type

---

Makefile
deploy/jenkins-ci/Jenkinsfile
deploy/jenkins-ci/Makefile
operator/Makefile
operator/build/Dockerfile
operator/deploy/deploy-kiali-operator.sh
operator/deploy/kiali/kiali_cr.yaml
operator/deploy/kiali/kiali_cr_dev.yaml
operator/roles/kiali-deploy/defaults/main.yml
operator/roles/kiali-deploy/tasks/main.yml
operator/roles/kiali-deploy/templates/kubernetes/clusterrolebinding.yaml
operator/roles/kiali-deploy/templates/kubernetes/deployment.yaml
operator/roles/kiali-deploy/templates/kubernetes/service.yaml
operator/roles/kiali-deploy/templates/kubernetes/serviceaccount.yaml
operator/roles/kiali-deploy/templates/openshift/clusterrolebinding.yaml
operator/roles/kiali-deploy/templates/openshift/deployment.yaml
operator/roles/kiali-deploy/templates/openshift/service.yaml
operator/roles/kiali-deploy/templates/openshift/serviceaccount.yaml
operator/roles/kiali-remove/tasks/main.yml

I see nothing in here that would require a new UI build. These really just affect server-side.
The point to this PR and v0.18.1 release is:
1) to get the operator to work on kubernetes
2) to get the operator to pass tests so we can get it into OperatorHub.io (which requires it to run on k8s)

changes for the v0.18.1 build

---

handlers/authentication.go

Kiali-User was being set to response headers but it is expected to be in the request headers.

KIALI-2524 Fix setting headers for audit info

---

operator/deploy/role.yaml
operator/roles/kiali-deploy/templates/kubernetes/clusterrole-viewer.yaml
operator/roles/kiali-deploy/templates/kubernetes/clusterrole.yaml
operator/roles/kiali-deploy/templates/openshift/clusterrole-viewer.yaml
operator/roles/kiali-deploy/templates/openshift/clusterrole.yaml

The "list" role is missing in operator for monitoringdashboards.
It was necessary for dashboards auto-discovery

Fix operator role on monitoringdashboards

---

Makefile
main_test.go

This commit adds possibility to build kiali which can produce code coverage report even for system tests which run against kiali deployed in OpenShift. Note this does not do anything for code coverage of unit tests.

Enable code coverage for system tests

---

business/istio_validations.go
models/istio_validation.go

Previous filtering was too aggressive and it removed validations for other object types as well, instead of only filtering the non-relevant services from the return JSON document. This changes the filtering to filter only the relevant type, not other types.
KIALI-2761

KIALI-2761 Modify validation service filtering 

---

business/apps.go
business/health.go
business/services.go
models/pod.go
models/service.go
models/workload.go

- return true when checking sidecar and there are no pods
- set true when checking apps sidecar and there are no workloads
- defer to Workload.IstioSidecar when possible, at times we were re-calling workload.pods.HasIstioSidecar()
- introduce Workload.HasIstioSidecar()
- optimize for Deployments where we can assume all pods are the same
- fix case consistency: SideCar -> Sidecar
- some clarity changes in health.go

KIALI-2677 Assume sidecar exists unless proven otherwise

---

business/services.go
models/service.go
swagger.json

Support ExternalName services. 
Knative creates both ClusterIP and ExternalName services. The last ones don't have endpoints attached to it. Therefore, the API returns a NotFound error.
Also, I found appropiate to add an extra field related to this scenario: ExternalName. It returns the hostname exposed in that Service (type of ExternalName).
PR showing this new field into Service Details page:  https://github.com/kiali/kiali-ui/pull/1134
https://issues.jboss.org/browse/KIALI-2676
yes.

KIALI-2676 Don't panic when there are no endpoints for a given service

---

kubernetes/kubernetes_service.go

Prevent workload details page to list services that aren't from its own scope.
Bug:
Solution:
https://issues.jboss.org/browse/KIALI-2760
yes

KIALI-2760 Exclude services with empty selector from workload details page

---

business/checkers/virtual_services/no_gateway_checker_test.go
kubernetes/istio_details_service.go

Istio 1.1 has added new format for linking gateway to VS. This is now "namespace/gateway-name". Although the documentation has removed mentions to FQDN, they should still be supported as some (all?) versions of Istio allow them. 
KIALI-2772

KIALI-2772 Add support for the new gateway annotation format

---

business/openshift_oauth.go
handlers/authentication.go
kubernetes/client.go
kubernetes/kubernetes_service.go
kubernetes/kubetest/mock.go

Adds in additional logout information needed when running on OpenShift 4. On OpenShift 4 we need to go to a logout page and include a specific redirect url to be used. On OpenShift 3 this not needed.
It will also delete the OpenShift token in the k8s backend so that it is marked as being invalid by OpenShift.
https://issues.jboss.org/browse/KIALI-2689
Yes, it will continue to work the same with OpenShift 3 and OpenShift 4. It will not affect what is happening when running in Kubernetes.

KIALI-2689 Support OAuth logout in OpenShift 4

---

operator/deploy/kiali/kiali_cr.yaml
operator/roles/kiali-deploy/defaults/main.yml

The kiali_cr.yaml file, though all comments, is a reference document.
The values you see in here are the actual defaults. So people can look up
kiali_cr.yaml and know what the defaults are if the user doesn't set it
(for example, if they use the minimal cr.yaml).
Therefore, this PR is changing the comments in kiali_cr.yaml to fix
the label_selector - the default is not "myLabel=myValue" so this removes
that. The example value is put in the description of the setting which
is where it belongs.
As the top-comment describing this file mentions, "If the setting is not defined by default, its name will be prefixed with "#"" - thus, kiali_cr.yaml will show "#label_selector:" informing the reader that this setting is not set by default.

fix the kiali_cr.yaml file

---

operator/deploy/deploy-kiali-operator.sh

If Kiali is found to already be installed, the script will ask the user if they want it uninstalled. If the user is OK  with that, the script will remove all the old Kiali resources and then move forward with installing the operator and then optionally installing a new Kiali via the Kiali CR.
This also adds a env var option so the user can tell us they are OK with uninstalling any existing kiali without having to be prompted about it.

KIALI-2838 install script can uninstall old kiali

---

status/discover.go

Jira: [KIALI-2848]( https://issues.jboss.org/browse/KIALI-2848)
I wasn't setting the url in the configuration but return the new one instead the url in the configuration.

KIALI-2848 Cannot specify the Tracing URL anymore

---

operator/roles/kiali-deploy/tasks/main.yml

@jotak was seeing this - his cluster couldn't get to github.com

KIALI-2845 abort the install if we can't get the image version info from github

---

business/checkers/destination_rules_checker.go
business/checkers/destinationrules/multi_match_checker.go
business/checkers/destinationrules/multi_match_checker_test.go
business/checkers/destinationrules/no_dest_checker.go
business/checkers/destinationrules/no_dest_checker_test.go
business/checkers/gateway_checker.go
business/checkers/no_service_checker_test.go
business/checkers/service_entry_checker.go
business/checkers/virtual_services/no_host_checker.go
business/checkers/virtual_services/no_host_checker_test.go
business/checkers/virtual_services/subset_presence_checker.go
business/istio_validations.go
kubernetes/types.go
models/istio_validation.go
tests/data/service_entry_data.go

Several cleanups for validations, including detection of cross-namespace request which we can not validate and we flag those with an unknown status.
KIALI-2818
KIALI-2819 https://github.com/istio/istio/issues/7659
Yes, requires support from UI to show the new feature, but see @hhovsepy's comment for backwards compatibility.

KIALI-2818 KIALI-2819 Detect cases when we can't validate

---

operator/deploy/deploy-kiali-operator.sh

see https://issues.jboss.org/browse/KIALI-2865 for the bug. To replicate, just pick "anonymous" when asked for the auth strategy. It should not fail with an error about can't create a secret.

KIALI-2865 when not using login mode, do not abort script with wrong error

---

business/services.go

Don't show workloads for a Service that doesn't have selector labels. Also, Istio sidecar shouldn't be computer either bc there aren't pods running under its umbrella.
https://issues.jboss.org/browse/KIALI-2759
yes
** Screenshoots **
Before:
After:
Test data: https://issues.jboss.org/browse/KIALI-2759?focusedCommentId=13734911&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13734911

KIALI-2759 Don't show workloads when service doesn't have selector labels

---

config.yaml

Reported in https://github.com/kiali/kiali/issues/1059#issuecomment-492785576.
Support for credentials in config.yaml was removed in PR #883. So this looks safe to remove, since credentials in config.yaml are no longer honored.

KIALI-2877 Remove outdated documentation in config.yaml

---

operator/Makefile

operator-sdk binary no longer has --version flag. It is now a "command".

Fix broken build

---

business/jaeger_helper.go
config/config.go
kiali.go
status/discover.go

Detected some problems with QUERY_BASE_PATh and jaeger.
- We are checking the services of jaeger to check if is available or not before the autodiscover so if the user not set the service name of tracing service jaegerAvailable will be false (https://github.com/kiali/kiali/blob/master/business/jaeger_helper.go#L29) and errorTraces will be -1 (Fix with https://github.com/kiali/kiali/pull/1082/files#diff-c19e5972b564f8f7ebd30c662b1974cbR104)
- If user is working with istio community the correct patch to check the services is `<endpoint>/<QUERY_BASE_PATH>/api` so we added a new param in configuration called Path to control this.
Thanks @hhovsepy

KIALI-2892 Jaeger traces not work when the user use Istio upstream with a QUERY_BASE_PATH

---

operator/build/Dockerfile

Hopefully this fixes the problem we had with the operator being unable to install dashboards

KIALI-2752 bump up the base image of operator-sdk to 0.8.0

---

models/pod_test.go
models/service_test.go
models/util.go

kiali's time format: 2019-05-06T10:56:58+08:00
k8s's time format: 2019-05-06T02:56:58Z
kiali's time format should be consistent with k8s, and UTC should be used by default.

the time format is consistent with the MarshalJSON of k8s

---

business/checkers/destinationrules/multi_match_checker.go
business/checkers/destinationrules/no_dest_checker.go
business/checkers/destinationrules/no_dest_checker_test.go
business/checkers/virtual_services/no_host_checker.go
business/checkers/virtual_services/no_host_checker_test.go
kubernetes/types.go

Modify the FQDN parsing to parse ServiceEntries to fqdn.Service part only, as the SEs are global scoped and do not adhere to the cluster parsing otherwise
This simplifies our code in some parts and makes it hopefully more reliable when catching SEs. Also, change certain parsing to use prefix matching instead of only "*" to avoid false positives.
Same PR adds support for wildcard ServiceEntries, which would in certain cases fail otherwise.
KIALI-2879, KIALI-2880
Yes.

KIALI-2880 KIALI-2879 Modify the FQDN parsing

---

business/checkers/gateway_checker.go
business/checkers/gateways/selector_checker.go
business/checkers/gateways/selector_checker_test.go
business/istio_validations.go
models/istio_validation.go

Gateway object's selector should a match a workload from the same namespace as per Istio documentation. This validation adds that, but also includes a workaround for "istio-ingressgateway" and "istio-egressgateway" which do not match Istio's documentation.
Marking as warning instead of error because older versions did not have this requirement in their documentations. They stated that selector can match any pod in any namespace in Kubernetes, but this has been changed in Istio 1.1 documentation with a note that it will become mandatory to match same namespace.
KIALI-2370

KIALI-2370 Add validation for gateway selector

---

operator/roles/kiali-deploy/vars/main.yml

https://issues.jboss.org/browse/KIALI-2935
Operator was always using default values for istio_namespace and installation_tag options of the CustomResource. This was creating a wrong config when deploying Kiali to a custom namespace.
Fixing by properly reading the values specified in the CR and using default values as a fallback.

KIALI-2935 Fix operator not honoring istio ns and install tag options

---

business/jaeger_helper.go
config/config.go
handlers/authentication.go
handlers/grafana.go
handlers/grafana_test.go
kubernetes/token.go
operator/deploy/kiali/kiali_cr.yaml
operator/roles/kiali-deploy/defaults/main.yml
status/discover.go

- Also fix KIALI-2921 for Grafana / potential race condition while setting config.
- Add a new config "InCluster" to tell if Grafana is in cluster or not
- Factorize code for access to service account token, and fix test failing while running that code
JIRA: https://issues.jboss.org/browse/KIALI-2920
See also #865

KIALI-2920 Make Grafana off-cluster still accessible

---

business/checkers/virtual_services/no_gateway_checker.go
business/checkers/virtual_services/no_gateway_checker_test.go
kubernetes/istio_details_service.go

If the first item in the gateways list was valid, the VS validation did not return the correct result. Validates correctly all the cases now.
KIALI-2947

KIALI-2947 Fix detection of valid+false pair of gateways in VS

---

models/service.go
swagger.json

Adding selectors field for a Service to ServiceDetails endpoint.
Need the following frontend PR: https://github.com/kiali/kiali-ui/pull/1213
https://issues.jboss.org/browse/KIALI-2570
yes

KIALI-2570 Adding Selector labels to ServiceDetails endpoint

---

appstate/grafana_state.go
appstate/jaeger_state.go
business/jaeger_helper.go
config/config.go
handlers/grafana.go
kiali.go
kubernetes/client.go
kubernetes/kubernetes_service.go
kubernetes/kubetest/mock.go
status/discover.go
status/versions.go

Introduce 'appstate' package, which can hold states more domain-specific, in order to avoid writes on global config.
The idea is to try to not mutate config (exception for kiali main and tests), hence avoiding concurrent writes.
Also try to clarify a couple of things:
- Renaming business.GetServices to business.GetJaegerServices
- In k8s client GetRoute, clarify that argument is route name and not service name (although they match most of the time)
- More consistent logging in discovery function
JIRA: https://issues.jboss.org/browse/KIALI-2921

KIALI-2921 Fix possible race on config write

---

appstate/jaeger_state.go
business/jaeger_helper.go
kiali.go

When Jaeger is temporary not available, it shows an error in Kiali console.
If Jaeger is not available at all then it should be configured with "Enabled: false".
JIRA: https://issues.jboss.org/browse/KIALI-2964

KIALI-2964 Remove JaegerAvailable flag

---

hack/cluster-openshift.sh
hack/maistra_v1_servicemeshcontrolplane_cr_basic.yaml

Bump hack/cluster-openshift.so to use maistra-0.11.
Note that we have changed the way that control plane is created, so I've added a local template into the hack folder and also updated how script waits for the installation.

Update hack/cluster-openshift.sh with maistra-0.11

---

business/openshift_oauth.go
operator/roles/kiali-deploy/templates/openshift/oauth.yaml
operator/roles/kiali-remove/tasks/main.yml

We used to use a hardcoded oauth name of "kiali" which doesn't work well if you have multiple Kiali's installed in the same cluster.
This update changes it to be hardcoded to "kiali-${NAMESPACE}" so that multiple Kiali instances can be installed in the cluster without a collision.
Note that installing multiple Kiali instances in the same namespace is not supported. 
https://issues.jboss.org/browse/KIALI-2955

KIALI-2955 Allow for multiple oauthclients

---

deploy/docker/Dockerfile

Changes the base image to be UBI7
https://issues.jboss.org/browse/KIALI-2958
Everything should work the same as before, we are just using a different base image now that seems to have more updated packages.

KIALI-2958: Move to UBI7 as our base image

---

operator/deploy/kiali/kiali_cr.yaml
operator/roles/kiali-deploy/defaults/main.yml
operator/roles/kiali-deploy/tasks/main.yml

https://issues.jboss.org/browse/KIALI-3010

KIALI-3010 support http by allowing the Kiali CR to define empty identity cert/key files

---

config/config.go
operator/deploy/kiali/kiali_cr.yaml
operator/roles/kiali-deploy/defaults/main.yml
prometheus/client.go

Allows for connection to Prometheus servers that are behind the oauth proxy. Such as what Maistra is going to be configurable in Maistra.
This introduced two new configuration options under the Prometheus option in external_services:
**ca_file**: The CA file that was used to sign the certificate used by Prometheus. If you are running with Maistra then the endpoint is signed by the service signer and you will need to use `/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt`. Leaving this empty means that no additional file is used.
**auth**: Setting this to `bearer` means that we send the Kiali service account bearer token in the `Authorization` header when contacting Prometheus. Leaving this as `none` means that it works as it does today where no …

KIALI-2776 Support bearer tokens when accessing Prometheus

---

README.adoc

Fix broken Kiali Graph image link in Documentation.
https://github.com/kiali/kiali/issues/1142
README.adoc file properly updated.

1142 - Update README.adoc

---

graph/telemetry/istio/appender/appender.go
graph/telemetry/istio/appender/istio_details.go
graph/telemetry/istio/appender/service_entry.go
graph/telemetry/istio/appender/service_entry_test.go

Given a telemetry destination_servicename we attempt to determine if that
destination is actually a serviceEntry.  We do it by matching the service
name to the hosts defined for the accessible serviceEntrys.  I'm pretty sure
this PR does not cover all of the cases but it is an improvment over the
exact string match previously required.  This PR adds:
- wildcard handling for external service entries
- prefix handling for internal service entries with host set to the fully qualified service
This also fixes two bugs:
- we were failing to cache serviceEntry info in the appender globalInfo
- we called for the serviceDefinition of a serviceEntry (in badging appender), which does not exist

KIALI-2999 Fix issues with ServiceEntry identification

---

operator/roles/kiali-deploy/defaults/main.yml
operator/roles/kiali-deploy/tasks/main.yml

Addresses something that was missed in https://github.com/kiali/kiali/pull/1120
We want the grafana URL to be dynamically generated since the istio namespace may be different.

make default grafana in_cluster_url dynamic

---

business/jaeger_helper.go
business/services.go
config/config.go
handlers/services.go
operator/deploy/kiali/kiali_cr.yaml
operator/roles/kiali-deploy/defaults/main.yml

JIRA: [KIALI-2779](https://issues.jboss.org/browse/KIALI-2779)
Require: 
1. https://github.com/kiali/kiali/pull/1129
2. https://github.com/kiali/kiali/pull/1120
Configmap
```yaml
tracing:
auth:
ca_file: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
insecure_skip_verify: true
password: ''
token: ''
type: bearer
use_kiali_token: true
username: ''
enabled: true
service: ''
url: ''
```

Kiali 2779 Handle Jaeger connections with authentication

---

operator/Makefile
operator/deploy/deploy-kiali-operator.sh
operator/deploy/merge-operator-yaml.sh
operator/deploy/namespace.yaml
operator/deploy/operator.yaml
operator/deploy/role.yaml
operator/deploy/role_binding.yaml
operator/deploy/service_account.yaml
operator/watches.yaml

https://issues.jboss.org/browse/KIALI-3007
I think this is going to be needed for https://issues.jboss.org/browse/KIALI-3007
NOTE: this PR does not affect current behavior. The defaults are set such that the behavior is left unchanged. This just allows someone to tell the install script to have the operator look elsewhere for the Kiali CR (as opposed to the same namespace where the operator is located). The default is the operator will look in its own namespace (which is how it works today).

KIALI-3007 support watching CR in a different namespace

---

operator/roles/kiali-deploy/templates/dashboards/go.yaml

CPU and RSS memory panels are added at the top. The rate of heap
allocations is also added.
The 'pod_name' label is added to all panels.
The 'go_gc_duration_seconds' panel is removed because it is based on a
summary metric that can't be aggregated. Instead the rate of GC events
is added.
The 'go_threads' panel is removed, tracking the number of goroutines is
usually enough.
None. It was discussed directly with @jotak 
No
If this is merged, [kiali.io](https://www.kiali.io/documentation/runtimes-monitoring/#_go) would need to be updated too.

Update Go dashboard

---

operator/roles/kiali-deploy/tasks/main.yml

Turns out, the operator already did the bulk of what we need - it only puts existing namespaces in the accessible_namespaces list in the configmap.
This PR does one additional thing though - it adds the deployment namespace to the list if it isn't already specified.

KIALI-3042 keep only existing namespaces (including the deployment namespace) in the list

---

hack/istio/install-bookinfo-demo.sh

- the 1.2 version uses dedicated service accounts for each service, see:
https://raw.githubusercontent.com/istio/istio/release-1.2/samples/bookinfo/platform/kube/bookinfo.yaml

Fix install-bookinfo hack script for istio 1.2

---

.travis.yml
Makefile
business/checkers/destinationrules/multi_match_checker.go
graph/telemetry/istio/appender/appender.go
handlers/istio_config.go
handlers/services.go
handlers/utils.go

https://issues.jboss.org/browse/KIALI-2859
Also, fixing the newly reported issues with the additional linter introduced by golangci-lint.
From the default linters set, only "errcheck" is disabled because it generates too many errors to fix under the scope of this PR/JIRA.

KIALI-2859 Replace gometalinter with golangci-lint

---

hack/istio/install-bookinfo-demo.sh

@jmazzitelli This fixed the issue I was having yesterday istalling bookinfo via the hack script but not having traffic generator work.  I think if you don't specify port you get the first one in the list of ports for the ingressgateway service.  And for me it was some weird "status-port", not the necessary http port.

Ensure expose ingressgateway on http2 port or traffic-gen may not work

---

operator/roles/kiali-deploy/tasks/main.yml

This is needed for MAISTRA-369
To test, install Kiali with a Kiali CR that has accessible_namespaces set to ["**"]. Then when its all installed, install it with an accessible_namespaces set to just [ "myproject" ]. Make sure the operator does not abort with the error message `The api.namespaces.label_selector cannot be changed to a different value....`

allow the user to go from non-MT mode to MT mode while relying on default label_selector

---

operator/deploy/deploy-kiali-operator.sh

We should not delete oauthclients by label as this would delete all of them. We only want the deploy script to remove the one in the namespace where kiali was deployed.

KIALI-3049 delete oauth client by name

---

business/services.go
status/discover.go

- Addded **istio-tracing** service to the list, it's the name in kubernetes environments.
- Now kiali check if there is a service "istio-tracing", "tracing", "jaeger-query" in **kubernetes** and **openshift** +1
- Now kiali check if there is a QUERY_BASE_PATH in **openshift** and **kubernetes** +1 (There was a bug here in errorTraces in the UI)
- Kiali only discover URL in openshift, routes are exposed only in this environment

Fix Jaeger in kubernetes, improve discovery, clean

---

handlers/grafana.go
handlers/jaeger.go

Preventing URL discovery of Jaeger and grafana in case user doesn't have access to pods of istio install namespace.
https://issues.jboss.org/browse/KIALI-2976
yes
Needs: https://github.com/kiali/kiali-ui/pull/1262
PRs:
This PR contents: https://github.com/kiali/kiali/pull/1129, https://github.com/kiali/kiali/pull/1120 and https://github.com/kiali/kiali/pull/1134. They should go first.
Outcome:
Admin with cluster-admin permissions:
Foo with permissions only to bookinfo:
Foo with disabled `authorize_external_services: false` option:
Note that Grafana url discovery actually needs to ping grafana for dashboard discovery. Then Kiali triggers an error.

KIALI-2976 Support hiding Jaeger and Grafana based on authorization

---

business/checkers/destinationrules/multi_match_checker.go
handlers/jaeger.go
handlers/utils.go

Fixes some warnings discovered locally and in travis:
```
[lponce@recopolis kiali]$ make lint
gometalinter --disable-all --enable=vet --enable=staticcheck --tests --deadline=500s --vendor $(glide nv | grep -v '^\.$')
business/checkers/destinationrules/multi_match_checker.go:81:28:warning: func MultiMatchChecker.matchingServiceEntry is unused (U1000) (staticcheck)
handlers/jaeger.go:42:56:warning: error strings should not be capitalized (ST1005) (staticcheck)
handlers/utils.go:21:5:warning: var clientFactory is unused (U1000) (staticcheck)
handlers/utils.go:23:6:warning: func getService is unused (U1000) (staticcheck)
make: *** [Makefile:289: lint] Error 1
```

Fix several warnings from lint

---

hack/crc-openshift.sh

Add some status text to tell the user how to log into the image registry

[hack] crc-openshift.sh: in status, tell people how to log into the image registry

---

graph/config/cytoscape/cytoscape.go
graph/meta.go
graph/protocol.go
graph/telemetry/istio/appender/appender.go
graph/telemetry/istio/appender/istio_details.go
graph/telemetry/istio/appender/istio_details_test.go
graph/telemetry/istio/appender/service_entry.go
graph/telemetry/istio/appender/service_entry_test.go
graph/telemetry/istio/istio.go
graph/types.go
hack/istio/install-istio-kiali-via-helm.sh

Service entry nodes have previously represented the actual requested endpoint and not an actual serviceEntry.  For example, the node may represent requests for  "en.wikipedia.com".  But in reality the actual "service" handling the request is a serviceEntry with a host that matches "en.wikipedia.com".  Moreover its hosts may match many different service requests (e.g. "en.wikipedia.com", "de.wikipedia.con" may both be handled by serviceEntry named "wikipedia" with host "*.wikipedia.com".
This PR changes the handling to generate nodes that represent the serviceEntry, not just a matching destination.  The new node will aggregate the traffic for the different requested endpoints.
*** REQUIRES UI PR: https://github.com/kiali/kiali-ui/pull/1271

KIALI-3034 ServiceEntry nodes should represent an actual ServiceEntry

---

business/tls.go
business/tls_test.go

Users receive an error regarding to MeshPolicies when they don't have access to any namespace.
I rename the error to a proper error message. Kiali is unable to determine the mesh-wide mTLS status without accessing to, at least, one namespace. Removing the error is not a solution.
Once the user has one namespaces added, the MeshPolicy could be fetch. However, the total mTLS status might be inaccurate.
Goes with: https://github.com/kiali/kiali-ui/pull/1284
https://issues.jboss.org/browse/KIALI-3057
yes

KIALI-3057 Fixing MeshPolicy error when user hasn't access to any namespace

---

hack/istio/install-istio-kiali-via-helm.sh

This adds istio-egressgateway to istio upstream hackscript. 
Maistra seems to install it by default, but using this script doesn't do the same, to test, verify that previous to this you get no egress.
I'm unsure if Kiali depends on it to be present or if we don't care.
Before:
```bash
$ oc get pod -l istio=egressgateway -n istio-system
No resources found.
```
After:
```bash
$ oc get pod -l istio=egressgateway -n istio-system
NAME                                   READY     STATUS    RESTARTS   AGE
istio-egressgateway-75964c5997-7dgj8   1/1       Running   0          3d
```

Adds istio-egressgateway to upstream installer

---

business/istio_validations.go

given a user without access to istio installation ns.
has access to at least one ns.
that ns has one service.
When user run the validations in service details page, validations crash.
Page now is up and also validations are returned.
https://issues.jboss.org/browse/KIALI-3072
yes

KIALI-3072 MTLS validations fixed when user doesn't have access to istio ns

---

config/config.go
handlers/grafana.go
handlers/grafana_test.go
operator/deploy/kiali/kiali_cr.yaml
operator/roles/kiali-deploy/defaults/main.yml
status/discover.go
status/versions.go

Renamed the Grafana 'display_link' property to 'enabled'. This is to be more aligned with the Jaeger 'enabled' configuration option.
https://issues.jboss.org/browse/KIALI-3066
Anyone with an existing configmap / kiali resource will need to update the value being used.
The example operator files are updated to include this change. I don't believe the display_link option is listed in any of our other documentation.

KIALI-3066 Rename Grafana display_link to enabled

---

business/dashboards.go
glide.lock
glide.yaml
vendor/github.com/kiali/k-charted/business/dashboards.go
vendor/github.com/kiali/k-charted/business/dashboards_test.go
vendor/github.com/kiali/k-charted/config/config.go
vendor/github.com/kiali/k-charted/config/promconfig/promconfig.go
vendor/github.com/kiali/k-charted/model/dashboards_test.go
vendor/github.com/kiali/k-charted/prometheus/client.go
vendor/github.com/kiali/k-charted/prometheus/roundtripper.go

JIRA: https://issues.jboss.org/browse/KIALI-3050
Required PR: https://github.com/kiali/k-charted/pull/19
Note: it doesn't have to be backported to 1.0 because k-charted isn't used in kiali 1.0
Suggested steps to quickly setup prometheus with a basic-auth proxy are described in a gist: https://gist.github.com/jotak/48c1d73e82a5a4d2f48cd86d6bccce54 (that's two little steps).
Then you can update Kiali config prom URL to use http://prometheus:8080 (protected w/ admin/admin) instead of http://prometheus:9090 (not protected)
Also, to build kiali with the k-charted PR you need to:
- checkout this branch as usual
- run:
```
glide mirror set https://github.com/kiali/k-charted https://github.com/jotak/k-charted
make dep-update
```
- build/deploy as usual
Once finished:
```
glide mirror remove …
```

KIALI-3050 Pass authentication data to k-charted

---

operator/roles/kiali-deploy/tasks/main.yml

if operator does not have permissions to create cluster roles or cluster role bindings, abort if it is asked to support accessible_namespaces=**
https://issues.jboss.org/browse/KIALI-3084
This is important to check (and fail-fast when this condition occurs) because if the operator was not given  permissions when it was installed, you cannot then change the accessible namespaces setting to "**" and expect it to work. Without failing fast here, kiali will be left in a broken state when this condition happens.

KIALI-3084 [operator] check create-cluster-role permissions if it needs them

---

deploy/docker/Dockerfile

Moves to using the ubi-minimal base image instead of the full ubi base image. This should help to prevent rebuilds due to security issues in unused packages.
https://issues.jboss.org/browse/KIALI-3077

KIALI-3077 Move to the ubi-minimal base image

---

business/istio_validations.go

Error message when trying to load details for Sidecar resources
"object type not found: sidecars"
Fixed it by adding that reference to the validations.
Note: I Think that this did nopt happened before  because we weren't correctly validating the result of "err". @israel-hdez configured a linter and fixed some linting issues some days ago.

KIALI-3094 Explicitly avoid validations on Sidecar resource

---

operator/Makefile
operator/molecule/asserts/configmap_asserts.yml
operator/molecule/asserts/multi-tenancy/role_asserts.yml
operator/molecule/asserts/pod_asserts.yml
operator/molecule/common/tasks.yml
operator/molecule/default/destroy.yml
operator/molecule/default/molecule.yml
operator/molecule/default/playbook.yml
operator/molecule/default/prepare.yml
operator/molecule/docker/Dockerfile
operator/molecule/multi-tenancy/molecule.yml
operator/molecule/multi-tenancy/playbook.yml

to avoid devs having to install the correct python/pip and then installing pip requirements, just run molecule via docker. This PR does that. "make molecule-test" runs the molecule tests via a docker image.

Molecule docker

---

operator/deploy/kiali/kiali_cr.yaml

A couple of places in the Jaeger-specific parts had references to Grafana and Prometheus, when they really meant Jaeger. This PR fixes that, as well as a similar problem under the Grafana properties.
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

Fixed a couple of descriptions in the reference CR

---

operator/Makefile
operator/molecule/asserts/multi-tenancy/role_asserts.yml
operator/molecule/asserts/roles-test/ro_clusterrole_asserts.yml
operator/molecule/asserts/roles-test/ro_role_asserts.yml
operator/molecule/asserts/roles-test/rw_clusterrole_asserts.yml
operator/molecule/asserts/roles-test/rw_role_asserts.yml
operator/molecule/common/set_accessible_namespaces_to_all.yml
operator/molecule/common/set_view_only_mode.yml
operator/molecule/common/tasks.yml
operator/molecule/common/unset_view_only_mode.yml
operator/molecule/common/wait_for_kiali_cr_changes.yml
operator/molecule/default/destroy.yml
operator/molecule/default/playbook.yml
operator/molecule/default/prepare.yml
operator/molecule/docker/Dockerfile
operator/molecule/roles-test/molecule.yml
operator/molecule/roles-test/playbook.yml
operator/roles/kiali-deploy/tasks/main.yml

Attempts to fix issue #1215 
Kubernetes role bindings are immutable. This means you cannot change a role binding to refer to a different role ref. Instead, you must delete and then create.
This PR deletes all role-related resources when view_only_mode is changing. That way, the tasks that reconcile the roles/rolebindings will perform a create as opposed to patch/merge.
~~This has NOT been tested. This is just my initial attempt based on what I think will work.~~ (UPDATE: there is now a molecule test in this PR that shows this working)
The molecule tests are fairly simple - this is what those tests do (you can do them as well):
1. Install Kiali Operator and a Kiali CR with all the defaults. This sets `deployment.view_only_mode` to false. Check the read-write roles are in effect.
2. Edit …

issue 1215 - Kubernetes role bindings are immutable, this works around that limitation

---

operator/Makefile

With this change, I can have a set of pre-built files and pick the one I want easily.
E.g:
`KIALI_CR_FILE=~/kiali_cr_maistra.yaml make openshift-deploy`
@jmazzitelli is that fine for you? Or do you have another way to achieve the same in mind?

Operator Makefile: make CR file configurable via envvar

---

business/checkers/services/port_mapping_checker.go
business/checkers/services/port_mapping_checker_test.go

Modify port validation to allow TargetPort to override Port definition (default is Port == TargetPort). In case of string in the TargetPort, search by the Port name in the deployment definition.
KIALI-3115, github issue #1228 
Yes
Will need kiali.io update to the validation page, kiali/kiali.io#154

KIALI-3115 Check TargetPort with string and port number, fixes #1228

---

graph/config/cytoscape/cytoscape.go

This lets the UI know the protocol an edge has, even if there is no traffic.
[KIALI-3102](https://issues.jboss.org/browse/KIALI-3102)
No

KIALI-3102 Always add the protocol to the edge

---

operator/deploy/deploy-kiali-operator.sh

The yaml will be written to a file rather than sent to the cluster. The yaml can be used to install the operator at a later time.

KIALI-3130 have operator installer support a dry run mode

---

operator/roles/kiali-deploy/templates/kubernetes/service.yaml
operator/roles/kiali-deploy/templates/openshift/service.yaml

Use the correct port name when https is disabled
https://github.com/kiali/kiali/issues/1259
Maybe, if someone is targeting the tcp port name
I don't think this needs a readme change

fix: Use correct port name when https is disabled

---

business/jaeger_helper.go
handlers/jaeger.go

In order to determine if kiali user has access to jaeger, we need to use internal urls
https://issues.jboss.org/browse/KIALI-3139
yes

KIALI-3139 Use internal url to determine if kiali user has access to jaeger

---

business/jaeger_helper.go

This is a developer helper.
When working with an external Kiali process, as a developer I'd like to configure the jaeger service to fetch traces errors from service details.
It's transparent to normal behaviour.

Trivial: allow to use Jaeger out-cluster

---

config/config.go
status/versions_test.go

Fixes KIALI-3156.
We just relax the permissions on the version check because Maistra is going to be using Istio 1.0 instead of 1.1 on its GA.

KIALI-3156 Relax Maistra version requirements

---

config/config.go
status/versions_test.go

KIALI-3156 Relax Maistra version requirements (Backport)

---

business/dashboards_test.go
models/dashboards.go
models/dashboards_test.go

JIRA: https://issues.jboss.org/browse/KIALI-3153
As mentioned in the JIRA, adding this new label is an easy one however the codes can be kind of cryptic (FI, UF, URX, etc.), so I suggest to prioritize task https://issues.jboss.org/browse/KIALI-1690 for an in-app help on the metrics page, which would add info about all codes.

KIALI-3153 Add response_flags to metrics

---

business/jaeger_helper.go
config/config.go
operator/deploy/kiali/kiali_cr.yaml
operator/roles/kiali-deploy/defaults/main.yml
status/discover.go

Don't assume that jaeger is in port 80 when testing if jaeger integration is enabled.
Also fixed the auto-discovery of the path.
https://issues.jboss.org/browse/KIALI-3151
yes

KIALI-3151 Add namespace and port for Jaeger integration test

---

business/checkers/gateways/multi_match_checker.go
business/checkers/gateways/multi_match_checker_test.go

This is to address an issue where a perfectly legitimate `Gateway`
with hostnames `example.com` and `foo.example.com` would get flagged
with a duplicate-host warning.  This was as a result of an unanchored
regular expression.  This PR introduces a test case to illustrate it,
as well as a fix.
Closes #1272.
* business/checkers/gateways/multi_match_checker.go (findMatch):
Anchor the hostname with `^$` when it is used as a regular
expression.  This avoids incorrect substring matching behaviour.
* business/checkers/gateways/multi_match_checker_test.go (TestNoMatchOnSubdomainHost):
Introduce a regression test of the above.

Gateway validations: tighten up duplicate host matching regex.

---

business/checkers/gateways/multi_match_checker.go
business/checkers/gateways/multi_match_checker_test.go

It turns out that Kiali doesn't throw a warning if adding both `FOO.com` and `foo.com` to a gateway, while in fact, [DNS should be case insensitive](https://tools.ietf.org/html/rfc4343).
I've updated the matcher to downcase both hostnames before comparison to achieve this.  I could've use a [case-insensitive flag on Golang's `regexp` library](https://tip.golang.org/pkg/regexp/syntax/) but that felt like overkill.
Closes #1285.
* business/checkers/gateways/multi_match_checker.go(findMatch): Adapt  the function to do case-insensitive match on hostnames.
* business/checkers/gateways/multi_match_checker_test.go(TestCaseMatching):   Add test case for the above.

Gateway host/port matching: make case-insensitive.  

---

.github/kiali.yml

https://issues.jboss.org/browse/KIALI-3082
This will enable the kiali-bot to require a review from, at least, one of the QE people.
The PR will still be mergeable. In order to get real mandatory checks, the repository will need to be configured turn the checks from the kiali-bot as required (this is good until we know that the bot works OK).

KIALI-3082 Enable check to enforce QE approvals

---

business/checkers/gateways/multi_match_checker.go
business/checkers/gateways/multi_match_checker_test.go

Cherry-pick from 
https://github.com/kiali/kiali/pull/1284
https://github.com/kiali/kiali/pull/1286
* Gateway validations: tighten up duplicate host matching regex.
This is to address an issue where a perfectly legitimate `Gateway`
with hostnames `example.com` and `foo.example.com` would get flagged
with a duplicate-host warning.  This was as a result of an unanchored
regular expression.  This PR introduces a test case to illustrate it,
as well as a fix.
Closes #1272.
* Gateway host/port matching: make case-insensitive.
It turns out that Kiali doesn't throw a warning if adding both FOO.com and foo.com to a gateway, while in fact, DNS should be case insensitive.
I've updated the matcher to downcase both hostnames before comparison to achieve this. I could've use a case-insensitive flag on …

[v1.0] Gateway validations fixes: #1284 and #1286

---

Makefile

Filter out packages which should not be part of binary for system tests code coverage.
e.g. test/data, kubetest,...
no
no

Filter out packages which should not be included in code coverage

---

operator/Makefile
operator/build/Dockerfile

- Updating Kiali Operator to use Operator SDK 0.9.0 (https://github.com/operator-framework/operator-sdk/releases/tag/v0.9.0) 
I have built a custom version of the Kiali operator and uploaded on https://quay.io/repository/gbaufake/kiali-operator 
with ``operator-sdk version: v0.9.0, commit: 560208dc998de497bbf59fea1b63426aec430934`` and I ran all molecule testing and I didn't find any regressions.
https://issues.jboss.org/browse/KIALI-3183

KIALI-3183 - Updating Kiali Operator to use 0.9.0

---

config/config.go
status/versions.go
status/versions_test.go

OSSM has a different naming and our old checks were incorrectly marking it as being 'Istio' in the about box.
This change allows us to detect that its running OSSM.
The new screen shot:
https://issues.jboss.org/browse/KIALI-3181

KIALI-3181 Support OSSM in version checks

---

Makefile
business/health_test.go
handlers/authentication.go
handlers/authentication_test.go
handlers/base.go
kiali.go
kubernetes/kubernetes_service.go
prometheus/internalmetrics/internal_metrics_test.go
server/server_test.go

Fixing errcheck linting errors and removing a Makefile target no longer necessary.

KIALI-3047 Enable errcheck linter

---

config/config.go
status/versions.go
status/versions_test.go

Backport of KIALI 3181 into the v1.0 branch.

KIALI-3181 [v1.0] Support OSSM in version checks

---

operator/Makefile
operator/deploy/kiali/kiali_cr.yaml
operator/molecule/affinity-tolerations-test/kiali-cr.yaml
operator/molecule/affinity-tolerations-test/molecule.yml
operator/molecule/affinity-tolerations-test/playbook.yml
operator/molecule/affinity-tolerations-test/set_affinity_tolerations.yml
operator/molecule/common/tasks.yml
operator/roles/kiali-deploy/defaults/main.yml
operator/roles/kiali-deploy/tasks/main.yml
operator/roles/kiali-deploy/templates/kubernetes/deployment.yaml
operator/roles/kiali-deploy/templates/openshift/deployment.yaml

Provide a way for the user to tell the operator what tolerations and affinities to assign to Kiali. The Kiali CR will have `affinity` and `tolerations` settings.
This is to address https://github.com/kiali/kiali/issues/1289

issue 1289 support tolerations and affinity config

---

graph/telemetry/istio/appender/appender.go
graph/telemetry/istio/appender/unused_node.go
graph/telemetry/istio/appender/unused_node_test.go

- show unused services for service graphs and non-service graphs
when service nodes are injected.
Before:
After:

KIALI-3161 Unused Nodes option should include service nodes

---

operator/Makefile
operator/deploy/kiali/kiali_cr.yaml
operator/roles/kiali-deploy/defaults/main.yml
operator/roles/kiali-deploy/templates/kubernetes/ingress.yaml
operator/roles/kiali-deploy/templates/kubernetes/service.yaml
operator/roles/kiali-deploy/templates/openshift/service.yaml

https://issues.jboss.org/browse/KIALI-3095
* Switching to default service type (ClusterIP) instead of NodePort
* Less invasive Ingress entry for Kubernetes
* Adds annotation to make Ingress to use the right protocol to forward the request to the Kiali service
Fixes #1308

KIALI-3095 Fix Kubernetes installation

---

operator/deploy/deploy-kiali-operator.sh
operator/roles/kiali-deploy/tasks/main.yml

Deploy script was taking the last release from a chronological point of view, which may not be the release we want users to install since it may not be the latest release using semantic versioning logic.
This, hopefully, fixes the deploy script to take the latest release using semver logic.

KIALI-3170 Fix operator deploy script to fetch last release

---

business/checkers/destinationrules/disabled_namespacewide_mtls_checker.go
business/checkers/destinationrules/meshwide_mtls_checker.go
business/checkers/destinationrules/namespacewide_mtls_checker.go
business/checkers/mesh_policies_checker.go
business/checkers/meshpolicies/mesh_mtls_checker.go
business/checkers/service_mesh_policies_checker.go
business/istio_config.go
business/istio_validations.go
business/istio_validations_test.go
business/tls.go
business/tls_test.go
handlers/istio_config.go
kubernetes/client.go
kubernetes/istio_details_service.go
kubernetes/kubernetes_service.go
kubernetes/kubetest/mock.go
kubernetes/types.go
models/cluster_rbac_config.go
models/istio_config.go
models/istio_validation.go
models/mesh_policy.go
operator/deploy/role.yaml
operator/roles/kiali-deploy/templates/openshift/role-viewer.yaml
operator/roles/kiali-deploy/templates/openshift/role.yaml
swagger.json

Maistra distribution will clone MeshPolicy and ClusterRbacConfig to ServiceMeshPolicy and ServiceMeshRbacConfig objects with identical meaning but these objects are namespaced.

KIALI-3193 Add support for ServiceMeshPolicy,ServiceMeshRbacConfig

---

business/istio_validations.go
business/tls.go

In Maistra scenarios, ServiceMeshPolicies need to be queried always from control-plane namespace.
This created some problems in the required object used by Kiali validations to perform DestinationRule checks.

KIALI-3220 Fetch ServiceMeshPolicies from control-plane

---

deploy/jenkins-ci/Jenkinsfile
deploy/jenkins-ci/jenkins_ref/jobs/kiali-release/config.xml

Adds NPM_CONFIG_REGISTRY parameter to the sample job.
Unfortunately, since different envs may need to use different package registries it's no longer possible to hardcode the parameters to make the Pipeline to "auto configure" itself if created manually (harcoding configs replaces any customized configs of the Pipeline on every run)
This means, that the Pipeline will need to be configured manually if the config.xml file cannot be placed in the Jenkins instance.

Add NPM registry parameter

---

business/services.go

Trivial, this is only changing some error logs to give context about API Documentation being involved.

(Trivial) give more context on APIDoc client calls errors

---

hack/crc-openshift.sh
operator/dev-playbook.yml

1. crc hack script bumps to 20g by default - seems the latest version needs it
2. to run the operator in dev mode (i.e. just the ansible playbook on the local dev machine, not running in k8s) we need a variable defined now to mimic the var passed in by the operator sdk

[hack] this fixes some dev tool things. nothing related to the actual code

---

operator/Makefile
operator/molecule/accessible-namespaces-test/kiali-cr.yaml
operator/molecule/accessible-namespaces-test/playbook.yml
operator/molecule/affinity-tolerations-test/kiali-cr.yaml
operator/molecule/affinity-tolerations-test/playbook.yml
operator/molecule/asserts/pod_asserts.yml
operator/molecule/common/set_auth_strategy.yml
operator/molecule/common/tasks.yml
operator/molecule/common/wait_for_kiali_running.yml
operator/molecule/default/playbook.yml
operator/molecule/kiali-cr.yaml
operator/molecule/ldap-test/playbook.yml
operator/molecule/roles-test/playbook.yml
operator/molecule/rolling-restart-test/kiali-cr.yaml
operator/molecule/rolling-restart-test/molecule.yml
operator/molecule/rolling-restart-test/playbook.yml
operator/roles/kiali-deploy/tasks/main.yml
operator/roles/kiali-deploy/templates/kubernetes/deployment.yaml
operator/roles/kiali-deploy/templates/openshift/deployment.yaml

When we need to restart Kiali, limit the downtime that the user will see by using the trick of adding an annotation to the deployment's template metadata. When a change to an annotation is made,
k8s will do a rolling upgrade to the pods when updating the annotation, thus restarting the pod.
https://issues.jboss.org/browse/KIALI-3051

KIALI-3051 [operator] do a rolling upgrade rather than deleting the pod

---

graph/telemetry/istio/appender/service_entry.go
graph/telemetry/istio/appender/service_entry_test.go

It was assumed that MESH_INTERNAL ServiceEntries refer to services in the local cluster. But when Istio is setup in a multi-cluster scenario, MESH_INTERNAL ServiceEntries are also used to route traffic to services in remote clusters.
ServiceEntries that route traffic to remote clusters must have a hostnames configured of the form remote_svc_name.remote_ns_name.global. I.e. always have three entries and last entry is the static string "global". This helps to clearly differentiate ServiceEntries are referring to local services and the ones that are routing traffic to remote clusters. This changes are implementing this logic.
This fixes #1364, fixes #1365, fixes #1366, fixes #1367

Do not do prefix matching for multi-cluster ServiceEntry

---

config/config.go
graph/telemetry/istio/appender/service_entry.go
graph/telemetry/istio/istio.go

In a multi-cluster scenario, in the cluster that is the destination of
the traffic, Istio will record telemetry with
destination_service="svc.namespace.global". This was generating a graph
with dummy service nodes labeled with "svc.namespace.global". These
represent the same "svc" kubernetes services without any suffix.
This changes perform some renaming to generate a traffic map that will
lead to proper unified service nodes.
Resolves #1481.
BEFORE:
AFTER:

Re-label telemetry destination_service={*.global} to hostname only

---

business/jaeger_helper.go
handlers/grafana.go
handlers/grafana_test.go

- In case of error from Grafana, return "ServiceNotAvailable" rather than "InternalServerError" (as Kiali is still OK)
- Decrease timeout from 30s to 10s
- (minor) simplify code while providing duration in jaeger helper
This is related to https://github.com/kiali/kiali/issues/1562 but can be merged independently

Small tweaks while fetching grafana info

---

business/services.go
graph/meta.go
graph/protocol.go
graph/telemetry/istio/appender/appender.go
graph/telemetry/istio/appender/dead_node.go
graph/telemetry/istio/appender/istio_details.go
graph/telemetry/istio/appender/istio_details_test.go
graph/telemetry/istio/appender/service_entry.go
graph/telemetry/istio/appender/unused_node.go
graph/telemetry/istio/appender/unused_node_test.go
graph/telemetry/istio/istio.go
graph/types.go
models/service.go

Istio 1.3 includes PassthroughCluster telemetry.  This is a special
"service" that acts as default ServiceEntry when ALLOW_ANY external
traffic is configured (the default).  It does not correlate to an
actual Service defined in k8s, as such it needs special handling.
- mark the PC service with IsPassthroughCluster = true in the node metadata
- service entry appender: don't try and determine if PC is a service entry
- istio details appender: don't try and fetch service definition
- as part of this I added GetServiceDefinitionList to the business.Svc API. This
replaces 1 round-trip per service node with 1 call for all service nodes
(per namespace). Moreover, this lighter-weight method also replaced the
call to getServices in the unused_node appender.  By adding it to the appender
namespace …

Add some special handling of PassthroughCluster service

---

config/config.go
handlers/grafana.go
handlers/grafana_test.go
models/grafana_info.go
operator/deploy/kiali/kiali_cr.yaml
operator/roles/kiali-deploy/defaults/main.yml
swagger.json

- Any number of dashboards can be defined
- Now we can also have links on "app" in addition to "workload" and "service"
- No change to the nominal case: default Istio dashboards for Workload and Service are still accessible same way as before
Frontend PR: https://github.com/kiali/kiali-ui/pull/1419
Closes https://github.com/kiali/kiali/issues/1268

Allow customized links to Grafana

---

operator/Makefile

This is to support local, CRC, and AWS cluster deployments. You can set `MOLECULE_KUBECONFIG` and that config file will be passed to the docker run... default is the usual `$HOME/.kube/config`.

[makefile] be able to tell molecule docker where to find kubeconfig

---

handlers/grafana.go
handlers/grafana_test.go
status/discover.go

Usually grafana dashboard path (as returned by grafana API) has a leading slash, but it seems there can be some exceptions (although circumstances are not established)
So make Kiali able to generate links to grafana with or without that leading slash
Closes https://github.com/kiali/kiali/issues/1692

Allow grafana dashboard path without leading slash

---

operator/roles/kiali-deploy/templates/openshift/route.yaml

Updates the route so that if a use enters the url using 'http' it will redirect them to the 'https' endpoint instead.
closes https://github.com/kiali/kiali/issues/1605

KIALI#1605 Update route to redirect http to https

---

business/dashboards.go
graph/telemetry/istio/appender/response_time.go
graph/telemetry/istio/appender/response_time_test.go
prometheus/metrics_definitions.go
prometheus/prometheustest/client_test.go

Istio 1.3.0 experimental introduces mixer-less telemetry.  In this new approach latency is reported via
a new metric: request_duration_milliseconds, as opposed to what has has been done with request_duration (in seconds).
I'm not aware of a way to drive off config to know which will be in service for a time period, so until the legacy metric is removed we need to support both.  This makes for some sort-of-hacky code. 
In the graph's response time appender we solved it mainly in the prom queries (this is the way Istio itself is doing it).  But the metrics code is table-driven/generic and so it's handled in a different way, based on determining which metric actually returns valid data.
See relevant Istio issue here: https://github.com/istio/istio/issues/16799.
I'm not really asking …

Support request_duration_milliseconds for latency reporting in mixer-less telemetry

---

graph/telemetry/istio/appender/response_time.go
graph/telemetry/istio/appender/security_policy.go
graph/telemetry/istio/istio.go

Some expanded querying for TCP security policy info revealed a weakness in
protecting against invalid service injection when generating the graph.  Update
base graph generation, as well as response_time and security_policy appenders,
with enhanced guards. Prevent node ID generation unless destSvcName is set.
Fixes #1731

Prevent "Failed ID gen" error in the graph

---

operator/manifests/README.adoc
operator/manifests/kiali-community/0.18.1/kiali.crd.yaml
operator/manifests/kiali-community/0.18.1/kiali.v0.18.1.clusterserviceversion.yaml
operator/manifests/kiali-community/1.1.0/kiali.crd.yaml
operator/manifests/kiali-community/1.1.0/kiali.monitoringdashboards.crd.yaml
operator/manifests/kiali-community/1.1.0/kiali.v1.1.0.clusterserviceversion.yaml
operator/manifests/kiali-community/1.3.1/kiali.crd.yaml
operator/manifests/kiali-community/1.3.1/kiali.monitoringdashboards.crd.yaml
operator/manifests/kiali-community/1.3.1/kiali.v1.3.1.clusterserviceversion.yaml
operator/manifests/kiali-community/1.4.2/kiali.crd.yaml
operator/manifests/kiali-community/1.4.2/kiali.monitoringdashboards.crd.yaml
operator/manifests/kiali-community/1.4.2/kiali.v1.4.2.clusterserviceversion.yaml
operator/manifests/kiali-community/kiali.package.yaml
operator/manifests/kiali-ossm/1.0.5/kiali.crd.yaml
operator/manifests/kiali-ossm/1.0.5/kiali.monitoringdashboards.crd.yaml
operator/manifests/kiali-ossm/1.0.5/kiali.v1.0.5.clusterserviceversion.yaml
operator/manifests/kiali-ossm/1.0.6/kiali.crd.yaml
operator/manifests/kiali-ossm/1.0.6/kiali.monitoringdashboards.crd.yaml
operator/manifests/kiali-ossm/1.0.6/kiali.v1.0.6.clusterserviceversion.yaml
operator/manifests/kiali-ossm/kiali-ossm.package.yaml
operator/manifests/kiali-upstream/kiali.crd.yaml
operator/manifests/kiali-upstream/kiali.monitoringdashboards.crd.yaml
operator/manifests/kiali-upstream/kiali.package.yaml
operator/manifests/kiali-upstream/kiali.v0.18.1.clusterserviceversion.yaml
operator/manifests/kiali-upstream/kiali.v1.1.0.clusterserviceversion.yaml
operator/manifests/kiali-upstream/kiali.v1.3.1.clusterserviceversion.yaml
operator/manifests/kiali-upstream/kiali.v1.4.2.clusterserviceversion.yaml

We have copies of our operator manifests in several different places (the upstream and community github repos, the RH production repo). We need one "golden copy" that we can be sure is the "correct" versions, and are maintained in a single place. We can then copy these over to the appropriate places when the time is right.
This PR also contains a 1.0.6 version of the productized Kiali - this is not published yet but I started it out here for now as we'll need it soon.

golden copy of the operator manifests

---

hack/istio/install-istio-kiali-via-helm.sh

- This allows in case we want to use a specific version of the oc
or in case we would like to use minikube kubectl command
When running minikube, is imposible to use the hack scripts with the kubectl command inside the minikube VM, adding a `--client-exe-path` option to specify the full command to execute.
Also improving the validation of the --client-exe, previously, if you had `--client-exe minikube kubectl --` It would try to execute `which minikube kubectl --` it would succeed because `minikube` command exists, but i didn't meant to use that command.
~~Yes~~ Err.. no! Is backwards compatible.

Allow to specify the full path of the executable

---

operator/deploy/deploy-kiali-operator.sh
operator/deploy/kiali/kiali_cr.yaml
operator/deploy/operator.yaml
operator/manifests/README.adoc
operator/roles/kiali-deploy/defaults/main.yml
operator/roles/kiali-deploy/tasks/main.yml
operator/roles/kiali-deploy/templates/kubernetes/deployment.yaml
operator/roles/kiali-deploy/templates/openshift/deployment.yaml

fixes #1618 
This will be work to see the operator work with OLM as a "phase 2" operator (meaning seamless upgrades).
Phases are part of the maturity model as described [here](https://github.com/operator-framework/operatorhub-docs/blob/master/building-operators/building-operators/types-of-operators.md#operator-maturity-model) and [here](https://github.com/operator-framework/operator-sdk/blob/master/doc/images/operator-capability-level.png)

getting ready for operator phase 2

---

business/checkers/checker.go
business/checkers/destination_rules_checker.go
business/checkers/destinationrules/multi_match_checker.go
business/checkers/destinationrules/multi_match_checker_test.go
business/checkers/destinationrules/traffic_policy_checker.go
business/checkers/destinationrules/traffic_policy_checker_test.go
business/checkers/gateway_checker.go
business/checkers/gateways/multi_match_checker.go
business/checkers/gateways/multi_match_checker_test.go
business/checkers/mesh_policies_checker.go
business/checkers/no_service_checker.go
business/checkers/no_service_checker_test.go
business/checkers/policies_checker.go
business/checkers/service_checker.go
business/checkers/service_entry_checker.go
business/checkers/service_mesh_policies_checker.go
business/checkers/service_role_bind_checker.go
business/checkers/virtual_service_checker.go
business/checkers/virtual_service_checker_test.go
business/checkers/virtual_services/single_host_checker.go
business/checkers/virtual_services/single_host_checker_test.go
business/istio_validations_test.go
handlers/istio_config.go
models/istio_validation.go
models/istio_validation_test.go
swagger.json

As described in the issue #1419, certain resources are causing each other validation errors. This change adds links to those other objects which could have caused the validation issue to each other (since we don't know which one the user has incorrectly defined).
This PR includes only a sample for multimatch gateway validations, nothing else so far. Waiting for input first.
Also makes the logic in multi_match_checker a little more sane (instead of relying only on the duplicate removal).
Closes issue #1419 
Yes. If we want to take advantage of the feature in the UI, then UI will require changes.

Add references to IstioValidation type and validators

---

hack/aws-openshift.sh

when the aws hack script installs bookinfo, it will now install the traffic generator, too.
This was requested by @jshaughn a while ago.

add traffic generator to the bookinfo install

---

graph/api/api.go
graph/protocol.go
graph/telemetry/istio/appender/service_entry.go
graph/telemetry/istio/appender/service_entry_test.go

One Istio ServiceEntry can have several hostnames in its definition, leading to an initial traffic map with one service node for each hostname in the SE. The service_entry appender was correctly reducing the service nodes into one ServiceEntry node, but edges were only being re-bounded leading to the possibility of multiple edges between the same source node and destination SE node.
This is adding a protocol-aware edge aggregation to remove redundant edges. It's also adding the protocol-awareness for the SE-to-Egress case.
Fixes #1752.

Implementing edge aggregation for nodes "talking" to a ServiceEntry

---

business/services.go

Fixes https://github.com/kiali/kiali/issues/1713

Return 404, not 500, when service is not found in apidoc call

---

Makefile
operator/Makefile

The UBI7 base images used to build Kiali are, apparently, updated to patch for vulnerabilities, but the machine building the Kiali containers seems to have a "shared" docker daemon which is caching the base images. So, Kiali is being built with the cached base image retrieved at some point of the time.
To fix, adding --pull argument to check and get available updates of the base images at build time.
Although operator base images will also be checked for updates, the base image has a fixed version tag. So, updates are not retrieved. The :latest tag of the base image is the one with the security fixes, but I'm not sure if changing the base image would break the operator. Leaving that for another PR, unless I get the green light to change the base image in this PR.
Fixes #1781.

Update base images when building Kiali containers

---

business/checkers/gateways/multi_match_checker.go
business/checkers/gateways/multi_match_checker_test.go

Closes https://github.com/kiali/kiali/issues/1804
Before:
After:

KIALI-1804 Remove false positive coming from . chars in RegExps

---

hack/aws-openshift.sh

we need to revert this when 1.0.7 is released since its deployment name is going back to its original

[hack] temp fix for the 1.0.6 release due to the change of the deployment name

---

operator/roles/kiali-deploy/templates/dashboards/envoy.yaml

It is disabled by default. To enable, we need to annotate pods (`kiali.io/runtimes: envoy`) or uncomment the "discoverOn" line in this dashboard.
Note that some charts require additional metrics from "listener" to be enabled on pods.
See https://istio.io/docs/ops/telemetry/envoy-stats/
E.g. of annotation: `sidecar.istio.io/statsInclusionPrefixes: cluster_manager,listener_manager,listener`
Closes https://github.com/kiali/kiali/issues/1453

Create an Envoy dashboard with a few metrics

---

README.adoc

Add a short section in README.md briefly explaining what is Kiosk mode
and how to use it.
Closes #1578.

Documentation of Kiosk mode

---

kubernetes/cache/kubernetes.go

During a last refactoring, there was a bug overwritting two caches in the same key.

Fix flipped Service/ServiceEntry cache

---

operator/molecule/common/tasks.yml
operator/molecule/ldap-test/ldap-service.yaml
operator/molecule/ldap-test/prepare-ldap.yml

fixes #1832 
The molecule tests will fail on an AWS cluster due to the way the kiali_base_url was being defined.  The LDAP test also failed because the LDAP service type was incompatible with running on a remote AWS cluster.
This fixes it to use the Kiali Route, which should always be there.
This makes the LDAP service of type "LoadBalancer" and the test uses the external load balancer URL.
Because of the use of Route, this means the molecule tests will only run on OpenShift clusters (which I think we assumed anyway, but I just wanted to point this out).
@gbaufake I'm running tests over here myself, but you might want to review this and run those e2e/olm tests you have.

[operator] fix molecule tests so they use the route and LoadBalancer

---

business/apps.go
business/apps_test.go
business/health.go
business/health_test.go
business/istio_config.go
business/istio_config_test.go
business/istio_validations.go
business/istio_validations_test.go
business/namespaces.go
business/services.go
business/services_test.go
business/tls.go
business/workloads.go
business/workloads_test.go
graph/telemetry/istio/appender/dead_node_test.go
graph/telemetry/istio/appender/istio_details_test.go
graph/telemetry/istio/appender/service_entry_test.go
graph/telemetry/istio/appender/sidecars_check_test.go
handlers/apps_test.go
handlers/workloads_test.go
kubernetes/cache/namespaces.go

This PR address two things:
- GetNamespaces() is filtered by AccessibleNamespaces, so API should be consistency, if Kiali has no visibility of a given namespace, rest of the API should skip it.
- There was an inconsistency in the cache/non cache use case.
There is no a "Security" flaw, as in any case, Kiali API is protected by RBAC (in OpenShift using the users's token, in Kubernetes, using the ServiceAccount).
Closes #1831

Filter API with AccessibleNamespaces

---

business/istio_config.go
models/destination_rule.go
models/virtual_service.go

The JSON coming from kiali-ui may not be "cleaned" from unset properties and Istio 1.4 seems to have more strict schemas for its CRDs.
This is ensuring that a "clean" JSON is used. Only CRDs involved in Kiali Wizards are fixed.
Related to kiali/kiali#1838, istio/istio#18558.

Fix wizards for Istio 1.4

---

operator/deploy/kiali/kiali_cr.yaml
operator/manifests/kiali-ossm/1.0.7/kiali.v1.0.7.clusterserviceversion.yaml
operator/roles/kiali-deploy/defaults/main.yml
operator/roles/kiali-deploy/tasks/main.yml

This is backwards compatible. Without a env var KIALI_IMAGE in the operator Deployment,
the behavior is the same as before.

This change is required to support disconnected installs within OLM environment

---

kubernetes/types.go

Istio 1.4 has removed old legacy adapters API.
This should be enough to minimally Kiali supports Istio 1.4 without errors.
Fixes #1880

Remove legacy adapters/templates

---

business/istio_config.go
models/destination_rule.go
models/virtual_service.go
util/maps.go
util/maps_test.go

Fixes #1883 
This is a continuation of #1870. Main issue in Kiali is that our model in backend doesn't map entire types, so Marshall/Unmarshall didn't work in some use cases.
Also, this is not trivial, as empty values are valid when using patches, so UI will continue sending them.
But now with this patch, all JSON on CREATE operations should be cleaned from nil values if whole type is mapped or not.
Note that Golang has not a "omitempty" tag for generic.

Remove null values from JSON on Create operations

---

business/checkers/destinationrules/no_dest_checker.go
business/checkers/destinationrules/no_dest_checker_test.go

DestinationRules might have a host in the format `servicename.namespace` without the domain.
Fixes https://github.com/kiali/kiali/issues/1884
yes

Covering scenario where host in DR is formatted as follows: svc.ns

---

hack/aws-openshift.sh

If your cluster has a maximum lifespan before it gets destroyed, this helps you judge when your cluster will be destroyed. The status can report how old the cluster is - you can use this to determine how much longer you have before the cluster goes away.
@jshaughn asked for this (or something like it).

[hack] status reports age of cluster

---

operator/molecule/olm-test/assets/catalog-sources.yaml
operator/molecule/olm-test/assets/elasticsearch-subscription.yaml
operator/molecule/olm-test/assets/jaeger-subscription.yaml
operator/molecule/olm-test/assets/kiali-subscription.yaml
operator/molecule/olm-test/assets/servicemesh-subscription.yaml
operator/molecule/olm-test/create.yml
operator/molecule/olm-test/destroy.yml

- To run this Pull Request:
0. Install Ansible and Molecule (``pip3 install ansible molecule junit-xml openshift --user``)
1. Deploy an Openshift 4.2 or 4.3 clean cluster
2. Login on the Openshift via `oc login`
3. Add more machines, because of this test uses 2 control planes for testing (including multi-tenancy testing) (something like 6 workers should do the work)
4. Run Following Commands if you want to see the full cycle (create-test-destroy):
``cd kiali/operator``
``molecule test -s olm-test``
5. If you don't want to destroy it, run the following commands:
``cd kiali/operator``
``molecule test -s olm-test --destroy never``

Updating Molecule OLM Tests for Openshift 4.2 and Openshift 4.3

---

business/istio_config.go

Tricky situation. In case there were two or more errors in the goroutines, the channel blocked the execution until the error was read. The problem was that there was a semaphore waiting for all the goroutines to finish. Deadlock. The result of this was a Timeout.
The execution is not blocked after adding a buffered channel of length 18. Each attempt to add will have room and won't block.
Right now, the response is:
Then, when the user has permissions for the resource, the list will be displayed. Meaning, we are following the same pattern as before.
Closes https://github.com/kiali/kiali/issues/1550

Removing deadlock in IstioConfigList

---

operator/deploy/operator.yaml
operator/manifests/kiali-community/1.10.0/kiali.crd.yaml
operator/manifests/kiali-community/1.10.0/kiali.monitoringdashboards.crd.yaml
operator/manifests/kiali-community/1.10.0/kiali.v1.10.0.clusterserviceversion.yaml
operator/manifests/kiali-community/kiali.package.yaml
operator/manifests/kiali-ossm/X.X.X/kiali.crd.yaml
operator/manifests/kiali-ossm/X.X.X/kiali.monitoringdashboards.crd.yaml
operator/manifests/kiali-ossm/X.X.X/kiali.vX.X.X.clusterserviceversion.yaml
operator/manifests/kiali-ossm/kiali-ossm.package.yaml
operator/manifests/kiali-upstream/1.10.0/kiali.crd.yaml
operator/manifests/kiali-upstream/1.10.0/kiali.monitoringdashboards.crd.yaml
operator/manifests/kiali-upstream/1.10.0/kiali.v1.10.0.clusterserviceversion.yaml
operator/manifests/kiali-upstream/kiali.package.yaml

fixes #1561 
This is part of the operator maturity model phase 4 which kiali operator supports.
This PR includes changes to the deploy script as well as the several gold copy of our OLM manifests.
To test this works, install operator normally using the deploy script:
```
cd operator/deploy
./deploy-kiali-operator.sh
```
Once the kiali operator pod is running, wait a short amount of time for prometheus to collect the metrics, then go to the Prometheus console (on OpenShift, you can expose a route to it) and look for metrics with the prometheus query `{app="kiali-operator"}`
You should see metrics like these (plus a lot more):
```
workqueue_retries_total{app="kiali-operator",name="kiali-controller",namespace="kiali-operator",pod_name="kiali-operator-57588b7b45-4gcv4", ... }
```
``` …
```

issue 1561 the operator SDK exposes metrics; tell prometheus to scrape it

---

hack/aws-openshift.sh

for now, hack script will ignore version warnings since openshift installer/client releases do not report the expected versions.
This also bumps up to OS 4.2.8

[hack] ignore version warnings

---

hack/aws-openshift.sh

The warnings about oc version mismatch are preventing the `eval $(aws-openshift.sh oc-env)` to work correctly.
Redirecting the warning messages to stderr seems to fix the issue.

[hack] Send oc version warnings to stderr

---

models/istio_validation.go

Lowing the severity down from error to warning.
Changing the validation message.
https://github.com/kiali/kiali/issues/1891#issuecomment-557519775
Closes https://github.com/kiali/kiali/issues/1891

Low down the severity of 'service.deployment.port.mismatch' validation

---

business/checkers/service_checker.go
business/checkers/services/port_mapping_checker.go
business/checkers/services/port_mapping_checker_test.go
business/istio_validations.go
business/services.go

Don't run the port name pattern validation for services out of the service mesh (without sidecar).
https://github.com/kiali/kiali/issues/1891

Adding port-naming-validation for service with sidecar

---

operator/molecule/maistra-e2e-test/molecule.yml

Updating Maistra Testing to 1.0.2 that was released yesterday (https://hub.docker.com/r/maistra/istio-ubi8-operator/tags) and Kiali/Kiali Operator to 1.10.0

[Molecule] Update Maistra to 1.0.2 and Kiali/Kiali Operator versions to 1.10

---

.travis.yml
Makefile
README.adoc
hack/check_go_version.sh
handlers/graph.go
operator/Makefile
util/intutil/convert.go

With these changes, Makefiles will ask for a minimum go version of 1.12.13. Additionally, the Makefile is changed so that it's possible to specify the go binary using an environment variable; ex: `GO=go1.13.4 make build`. This is useful if user has installed several go version (see https://golang.org/doc/install#extra_versions).
This also is:
* removing references to istiooc, because it's no longer supported in Maistra;
* a quick README.md cleanup;
Fixes #1970.

Move to Go1.12.13

---

config/config.go
config/token.go
handlers/authentication.go
operator/deploy/deploy-kiali-operator.sh
operator/deploy/kiali/kiali_cr.yaml
operator/molecule/asserts/token-test/assert-token-access.yml
operator/molecule/token-test/molecule.yml
operator/molecule/token-test/playbook.yml
operator/molecule/token-test/prepare-token.yml
operator/roles/kiali-deploy/tasks/main.yml

This is adding a login mechanism inspired on the [kubernetes dashboard login view](https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/README.md#login-view).
Instead of providing a username and a password, Kiali asks for a token. The provided token is meant to be a service account token and Kiali will use it during the session of the user to make calls to the cluster API.
By using the provided token to make calls to the cluster API, the cluster's RBAC mechanisms takes effect and write actions in Kiali can be limited using Roles and RoleBindings.
Currently, in Kubernetes, there is a limitation: the resulting _accessible namespaces_ given the Kiali ConfigMap should all be, at least, readable via the kiali-viewer role. Kiali will fail if a user logs in using a token …

Implement token authentication

---

handlers/config.go

IstioIdentityDomain parameter needs to be used by Kiali UI in the context of build FQDN in Wizards.

Expose IstioIdentityDomain in public config

---

operator/manifests/create-new-version.sh

fixed #2021 
This just does the grunt work of copying the previous version of the manifest files and editing the parts that correspond to the new version.
If anything extra needs to change per version  (such a new role permissions or new descriptions) then you will obviously still need to hand-edit the new manifest files after generating the new version with this script.

[operator] script to generate new OLM manifest files

---

hack/istio/install-istio-via-istioctl.sh

This fixes the problem that was reported here: https://github.com/kiali/kiali/pull/2029

[hack] only check if we are on OpenShift after the client-exe variable is determined

---

business/istio_config.go
business/istio_validations.go
business/tls.go

fixes #1698 
I took the path of least resistance. There should be no need to log this unless we have a cluster role and we know we have a cluster role when accessible namespaces is \*\* (and we know we do not have a cluster role when accessible namespaces is NOT \*\*).
This means it's a very small, localized change. No need to go through a huge change in the operator and adding a config setting to the configmap just to turn off this message - that seems like killing an ant with a sledgehammer.

issue 1698 do not log a warning if its expected

---

deploy/jenkins-ci/bin/determine-release-type.sh

Tested with:
```
% NOW_DATE=$(date -d '2019-12-13' '+%s') ./determine-release-type.sh
minor
% NOW_DATE=$(date -d '2019-12-20' '+%s') ./determine-release-type.sh
snapshot.0
% NOW_DATE=$(date -d '2019-12-21' '+%s') ./determine-release-type.sh
snapshot.0
% NOW_DATE=$(date -d '2019-12-27' '+%s') ./determine-release-type.sh
snapshot.1
% NOW_DATE=$(date -d '2019-12-28' '+%s') ./determine-release-type.sh
snapshot.1
% NOW_DATE=$(date -d '2020-01-03' '+%s') ./determine-release-type.sh
snapshot.2
% NOW_DATE=$(date -d '2020-01-04' '+%s') ./determine-release-type.sh
snapshot.2
% NOW_DATE=$(date -d '2020-01-10' '+%s') ./determine-release-type.sh
minor
% NOW_DATE=$(date -d '2020-01-11' '+%s') ./determine-release-type.sh
minor
% NOW_DATE=$(date -d '2020-01-17' '+%s') ./determine-release-type.sh …
```

Make Sprint #33 four weeks long

---

kiali.go
status/status.go

fixes #2054 
if KIALI_CONTAINER_VERSION is defined (typically in Dockerfile) then report it that version. Otherwise, assume container and server versions are the same.
related UI PR: https://github.com/kiali/kiali-ui/pull/1587

report a container version as part of status results

---

business/checkers/destination_rules_checker.go
business/checkers/destinationrules/multi_match_checker.go
business/checkers/destinationrules/multi_match_checker_test.go
business/checkers/destinationrules/no_dest_checker.go
business/checkers/destinationrules/no_dest_checker_test.go
business/checkers/no_service_checker.go
business/checkers/virtual_service_checker.go
business/checkers/virtual_service_checker_test.go
business/checkers/virtual_services/no_host_checker.go
business/checkers/virtual_services/no_host_checker_test.go
business/checkers/virtual_services/single_host_checker.go
business/checkers/virtual_services/single_host_checker_test.go
business/checkers/virtual_services/subset_presence_checker_test.go
business/istio_validations.go
kubernetes/types.go
models/namespace.go

Give support to 'service.namespace' support to DestinationRules and VirtualServices.
Fixes #1892 and also give extra support to #1884 (adds a unknown validation when refers to another namespace).
This is the list of the validations that now supports the `service.namespace` format:
1. DestinationWeight on route doesn't have a valid service (host not found)
https://kiali.io/documentation/validations/#_destinationweight_on_route_doesn_t_have_a_valid_service_host_not_found
NoHostChecker
2. Subset not found
https://kiali.io/documentation/validations/#_subset_not_found
SubsetPresenceChecker
3. More than one Virtual Service for same host
https://kiali.io/documentation/validations/#_more_than_one_virtual_service_for_same_host
SingleHostChecker
1. This host has no …

Fixing 2 DR pointing to same host with short name svc.ns

---

operator/manifests/kiali-ossm/1.1.0/kiali.crd.yaml
operator/manifests/kiali-ossm/1.1.0/kiali.monitoringdashboards.crd.yaml
operator/manifests/kiali-ossm/1.1.0/kiali.v1.1.0.clusterserviceversion.yaml
operator/manifests/kiali-ossm/kiali-ossm.package.yaml

OSSM-127
put back the ao-logs stuff since the ossm release will move up the op base image to a 4.2 version that supports ao.

[operator] OSSM-127 update manifests for kiali ossm 1.1

---

make/Makefile.operator.mk

I don't know why this is behaving differently for me now, but all of a sudden this isn't working like it was.
But if I remove the `echo ''` , it will still work because the base64 decode will return an empty string on error or if the secret doesn't exist (which happens on non-ServiceMesh environs). This env var isn't used anyway for non-SM environs so it shouldn't matter anyway. It just needs to be correct when you have ServiceMesh installed (and in that case the secret will exist so that command should succeed).

fix makefile so it works with servicemesh deployments

---

Makefile
README.adoc
make/Makefile.cluster.mk

fixes #2101 
If you do not have a minikube or remote openshift cluster, you can build and deploy using the  `CLUSTER_TYPE=local` env var. like this:
`CLUSTER_TYPE=local make container-build operator-create kiali-create`
This assumes the cluster can pull from your local repository.

update makefile to support building and deploying to other non-minikube/non-OS clusters

---

business/services.go
handlers/threescale.go
jaeger/spans.go

Fixes #2109 
It doesn't log an error when a 3scale rule is not found, because it's a valid business request, UI is handled correctly, but in backlog it was printing an unnecessary Error trace.
Also, moved to Trace a repetitive log when fetching spans.

Improve log messages for 3scale and traces

---

operator/deploy/kiali/kiali_cr.yaml
operator/roles/kiali-deploy/defaults/main.yml
operator/roles/kiali-deploy/tasks/main.yml
operator/roles/kiali-deploy/templates/kubernetes/ingress.yaml
operator/roles/kiali-deploy/templates/openshift/route.yaml

fixed #2111 
Because an ingress into a cluster can vary wildly in their desired configuration, a new setting in the Kiali CR is being introduced to allow the user to override complete portions of the ingress resource configuration (Ingress on Kubernetes and Route on OpenShift).
See the new setting in the Kiali CR for an example and the docs commenting the new setting.
For users that use these overrides, they are required to make sure the new configuration is valid - the operator will just blindly copy those settings into the resource - no validation is performed other than the validation the k8s master performs when it applies the new config to the resource.
@tillig can you see if this provides what you need? Based on your comments in the issue, you will want something like this in your …

[operator] allow user to override ingress spec and annotation sections to be able to customize it

---

business/checkers/virtual_service_checker_test.go
business/checkers/virtual_services/route_checker.go
business/checkers/virtual_services/route_checker_test.go
models/istio_validation.go

1. Removing all the outdated validations that Galley takes care of.
2. Adding one warning validation for the following scenario:
```yaml
kind: VirtualService
metadata:
name: reviews
spec:
hosts:
- reviews
http:
- route:
- destination:
host: reviews
subset: v1
weight: 80
```
This is the scenario where there is only one destinationRouteWeight but there is a weight different to 100. In this case, Istio assumes the weight to be 100. Independently the value set in the weight field.
The validation message is the following:
`The weight is assumed to be 100 because there is only one route destination`
Relates to https://github.com/kiali/kiali/issues/1528
** Screeeenshot **

VirtualService#Route validation: one route under 100 weight warning

---

operator/deploy/role.yaml
operator/manifests/kiali-community/1.13.0/kiali.v1.13.0.clusterserviceversion.yaml
operator/manifests/kiali-ossm/1.1.0/kiali.v1.1.0.clusterserviceversion.yaml
operator/manifests/kiali-upstream/1.13.0/kiali.v1.13.0.clusterserviceversion.yaml
operator/roles/kiali-deploy/tasks/main.yml
operator/roles/kiali-deploy/templates/openshift/console-links.yaml

fixes https://github.com/kiali/kiali/issues/2136
Need to not create consolelinks if not supported on the openshift version we are on.

[operator] do not create consolelinks if not supported on the openshift version

---

hack/aws-openshift.sh

OS 4.3.0 is available now. Have the hack script install it by default.
You can still have it use 4.2.4 by passing in `-ov 4.2.4` as a command line argument.

[hack] move aws-openshift.sh to OpenShift 4.3.0

---

operator/deploy/role.yaml
operator/manifests/kiali-community/1.13.0/kiali.v1.13.0.clusterserviceversion.yaml
operator/manifests/kiali-ossm/1.12.0/kiali.v1.12.0.clusterserviceversion.yaml
operator/manifests/kiali-upstream/1.13.0/kiali.v1.13.0.clusterserviceversion.yaml

When installing the operator via OLM, we need these permissions. Seems as though then installed via OLM, some caching mechanism is turned on which requires permission to list and watch the objects being queried.
See OSSM-133

[operator] needs new permissions

---

config/config.go

Set in the configuration default jaeger Url to empty to avoid that user not set this value.

Set url jaeger default to empty

---

jaeger/client.go

config.Get() involves a lock, so it must not be used when not necessary
@aljesusg @lucasponce this is a small one to avoid unnecessary calls to config.Get()

(Trivial) avoid too many config.Get()

---

operator/manifests/prepare-community-prs.sh

This is a script that helps prepare the community OLM metadata. It sets up a couple branches that you can then push to create PRs to the community-operators git repo.
This script is only used by devs that need to build community-operator PRs so we can push the OLM metadata to OperatorHub.io. It is not used internally by Kiali at all - it is strictly a dev tool.

[operator] script to help prepare the community operator metadata

---

hack/istio/download-istio.sh

Original solution was using
https://api.github.com/repos/istio/istio/releases/latest which is not
always pointing to the latest released version of istio but to last
release which can be older stream release.
Right now it's pointing to 1.3.7 but the latest version is 1.4.3.
New solution (taken from https://git.io/getLatestIstio) should always
pick the latest released version (now 1.4.3).

[hack] Get the latest released version of istio instead of last release

---

models/istio_validation.go

The namespaces that have istio config objects that are correct (no validations present) weren't presented with the green tick icon. It was because `objectCount` was 0. ObjectCount should count also the valid istio objects.
Fixes https://github.com/kiali/kiali/issues/2210
It remembers me the rocket which explode because of a lack of protection of an integer overflow: https://en.wikipedia.org/wiki/Cluster_(spacecraft)

ObjectCount has to count valid objects

---

graph/api/api_test.go
graph/api/testdata/test_complex_graph.expected
graph/protocol.go
graph/telemetry/istio/appender/response_time.go
graph/telemetry/istio/appender/response_time_test.go
graph/telemetry/istio/istio.go
graph/telemetry/istio/util/util.go
models/health.go
prometheus/client.go
prometheus/metrics.go
prometheus/metrics_definitions.go
prometheus/prometheustest/client_test.go

In Istio 1.5 (likely) and SM 1.1 (definite) GRPC status codes will be reported for requests using protocol="grpc".  We had partially coded for this in the graph but the code assumed that the GRPC code would be set in the existing response_code telemetry field.  Because Istio was afraid that existing consuming code may assume response_code contains only HTTP codes, it elected to add a new field, grpc_response_status.  See https://github.com/istio/istio/pull/20036 for more.
Although this protects existing consumer code it also makes it more difficult to add support as consumers now need to deal with two, protocol-specific, fields.
In this PR the graph code deals with it by basically setting our existing response code field with the appropriate protocol-specific code in the telemetry.  In …

Support GRPC status codes

---

graph/api/api_test.go
graph/api/testdata/test_complex_graph.expected
graph/protocol.go
graph/telemetry/istio/appender/response_time.go
graph/telemetry/istio/appender/response_time_test.go
graph/telemetry/istio/istio.go
graph/telemetry/istio/util/util.go
models/health.go
prometheus/client.go
prometheus/metrics.go
prometheus/metrics_definitions.go
prometheus/prometheustest/client_test.go

V1.12/SM1.1 Backport for https://github.com/kiali/kiali/issues/1235
Graph:
- For GRPC requests use grpc_response_status unless there was an HTTP-level failure (i.e. response_code is an HTTP failure code). Kiali only associates one response code with a request, so based on protocol we use one of the two supplied in the telemetry.
- We limit TCP metrics to only successful requests so now we also check for grpc success criteria to our queries.
Metrics/Health:
- To capture error rate when no protocol is specified we need to query separately for HTTP and GRPC errors. Update queries appropriately (pretty ugly now).  In the future we could consider
a refactor that eliminated support for error query and defered the filtering to the client.
- To aggregate errors for health checks we need to …

Support GRPC status codes (#2211)

---

business/threescale.go
config/config.go
handlers/config.go
operator/deploy/kiali/kiali_cr.yaml
operator/roles/kiali-deploy/defaults/main.yml
operator/roles/kiali-deploy/vars/main.yml

This is a WIP to re-organize the Kiali extensions/add-on.
At the moment, Kiali only has one feature that fits this cagegory: integration with 3scale Istio Adapter [1].
This PR starts to refactor configuration for this feature, only changed the private/public config, handlers/business layers are not touched, that can be do in following iterations.
Not this PR would require UI changes, so it's still in draft.
Fixes #2146 
[1] https://github.com/3scale/3scale-istio-adapter

Reorganize config for extensions

---

business/checkers/virtual_services/route_checker.go
business/checkers/virtual_services/route_checker_test.go
models/istio_validation.go

Adding new validation for VirtualServices. When there are two destination routes referencing to the same subset. 
Fixes https://github.com/kiali/kiali/issues/1515

Adding new validation: same subset in different route destination

---

business/checkers/authorization/namespace_method_checker_test.go
business/checkers/authorization/workload_selector_checker.go
business/checkers/authorization/workload_selector_checker_test.go
business/checkers/authorization_policies_checker.go
business/istio_validations.go
models/istio_validation.go
tests/data/authorization_policy_data.go

Adding validation for selector matchLabels on AuthorizationPolicy objects.
This is as part of https://github.com/kiali/kiali/issues/2081
Documentation PR: https://github.com/kiali/kiali.io/pull/204
When there is a workload with those labels:
When the AuthorizationPolicy has no selector, there's no warning either.
When the AuthPolicy related to a non-existing workload:

Adding workload checker for AuthPolicy

---

prometheus/metrics.go
prometheus/prometheustest/client_test.go

Fixes an unfortunate prom/regex issue introduced with the nre grpc_request_status handling for Istio 1.5.
Fixes https://github.com/kiali/kiali/issues/2242

Fix issue when pulling "request_error_count" metrics

---

business/checkers/virtual_services/route_checker_test.go

Both 0 and 2 have the validation.
Both 1 and 3 have the validation.
The order is indiferent.
Fixes: https://github.com/kiali/kiali/issues/2254

Fix test: order of items might change due to concurrence

---

hack/istio/install-istio-via-istioctl.sh

Minor change to the hack script that installs istio.
If it does not install kiali, then it should not create the kiali route. Otherwise, the script spits out an error that might be alarming: 
```
Error from server (NotFound): services "kiali" not found
```
This PR just skips the route creation if kiali wasn't enabled.

[hack] don't expose kiali if it wasn't installed

---

hack/aws-openshift.sh

This lets you use the aws-openshift.sh hack script to install OpenShift preview/nightly builds.
e.g. this now works to install a dev-preview of an OpenShift 4.4 nightly build:
```
./hack/aws-openshift.sh -odp -ov 4.4.0-0.nightly-2020-02-21-143916 create
```

[hack] make it possible for aws hack script to pull dev preview releases

---

tests/e2e/assets/bookinfo-workloads.yaml

Fixing e2e test about workload diversity. The assets yaml was outdated and seems that in OCP 4.4 the previous versions for StatefulSets and ReplicaSets are going to be unsupported.
@mattmahoneyrh Do that work for you?

Promote StatefulSet and ReplicaSets to v1 to fix e2e test

---

config/config.go
operator/deploy/kiali/kiali_cr.yaml
operator/roles/default/kiali-deploy/defaults/main.yml

Fixes https://github.com/kiali/kiali/issues/2253
Screenshot showing stateful sets in workloads list:

Enable cache, fetch StatefulSets by default

---

business/health_test.go
models/health.go

Starting is Istio 1.5 GRPC requests will generate request_protocol="grpc" grpc_request_status=<grpcStatus>.  Note that when request_protocol is not "grpc" the additional field is not provided (i.e. not present on the time series).
The health calculation was considering only http errors reported in response_code.  We need to include grpc errors.
Fixes #2457

Include GRPC failures in Health calculation

---

config/config.go
operator/deploy/kiali/kiali_cr.yaml
operator/roles/default/kiali-deploy/defaults/main.yml

Follow-up on https://github.com/kiali/kiali/pull/2470 (cache wasn't trully enabled)

Enable cache (missing config)

---

business/checkers/sidecars/multi_match_checker.go
business/checkers/sidecars/multi_match_checker_test.go
business/checkers/sidecars/workload_selector_checker.go
business/checkers/sidecars/workload_selector_checker_test.go
business/checkers/sidecars_checker.go
business/istio_validations.go
kubernetes/istio_details_service.go
kubernetes/types.go
models/istio_validation.go
tests/data/sidecar_data.go

Add validations for sidecar resources.
1. There are workloads with the provided labels in the workloadSelector field.
2. There aren't two sidecars in the same namespace without workloadSelector.
Requires to merge quick one in the frontend: https://github.com/kiali/kiali-ui/pull/1679
Next validation will come. Splitting https://github.com/kiali/kiali/issues/1541 for better review.
1.
2.

Sidecar validations: no matching workloads and multi sidecar match

---

business/istio_validations.go
business/istio_validations_test.go
kubernetes/client.go
kubernetes/istio_details_service.go
kubernetes/kubetest/mock.go

Need to change the logic in istio_validations, as istio objects can be part or not of cache, we need to fetch types, in cache or not, one by one and not all at the same time.
In the end, some logic in kubernetes package is moved to business package.
Fixes https://github.com/kiali/kiali/issues/2488

Fix error: Kiali cache doesn't support sidecars

---

business/health.go
graph/telemetry/istio/appender/appender.go
graph/telemetry/istio/appender/response_time.go
graph/telemetry/istio/appender/security_policy.go
graph/telemetry/istio/istio.go
graph/telemetry/istio/util/util.go
models/dashboards.go
prometheus/metrics.go
status/versions.go
status/versions_test.go

Istio 1.5 introduces` canonical_service` and `canonical_revision` telemetry labels and deprecates `app` and `version`.   This affects graph, metrics and health as they now need to prefer the new labels when the istio version is 1.5+.  This PR introduces the necessary version-specific handling.  When support for the deprecated fields is removed so can be the version-specific handling.  
Also added Istio dev builds as recognized istio versions.
Fixes #2276

Support canonical_service fields in Istio 1.5+ telemetry

---

business/checkers/sidecars/egress_listener_checker.go
business/checkers/sidecars/egress_listener_checker_test.go
business/checkers/sidecars_checker.go
business/istio_validations.go
models/istio_validation.go
tests/data/sidecar_data.go

Add validation to egress host field[1].
Each field is a string formatted like this: "namespace/fqdn". In the namespace there can be 4 different values: *, ~, ., namespace name.
*/*, ~/*, ./* are always valid scenarios.
ns/*, ns/*.ns.svc.cluster.local and ns/svc.ns.svc.cluster.local are valid when ns = sidecar namespace. Otherwise, cross-ns validation is shown.
ns/*.ns2.svc.cluster.local and ns/svc.ns2.svc.cluster.local is not a valid scenario unless ns = ns2. The service references is in another namespace. cross-ns validation is shown.
ServiceEntries are taken into account.
1. Check if the host is present in the namespace: 
2. Warns user that the host is in another namespace. kiali can cover this scenario
See the exact spec for this field:
[1] …

Add Sidecar egress host validation

---

config/config.go
operator/deploy/kiali/kiali_cr.yaml
operator/roles/default/kiali-deploy/defaults/main.yml

Disable Iter8 extension by default.
Add it to the kiali CR description and defaults.
cc @jadeyliu939

Disable Iter8 by default

---

graph/telemetry/istio/appender/dead_node.go
graph/telemetry/istio/appender/dead_node_test.go
graph/telemetry/istio/appender/response_time.go
graph/telemetry/istio/appender/response_time_test.go
graph/telemetry/istio/istio.go
graph/telemetry/istio/util/util.go

Remove aggressive filtering of bad telemetry from DeadNodeAppender because it was also removing good telemetry for headless services.  Instead, filter unwanted telemetry immediately when building the TrafficMap.
This change is based on the discussion in https://github.com/kiali/kiali-ui/pull/1680
Fixes #976
@jotak Try out this change and see how it affects the Kafka situation.

Remove aggressive filtering of bad telemetry from DeadNodeAppender

---

.travis.yml
CONTRIBUTING.md
Makefile
PULL_REQUEST_TEMPLATE.md
README.adoc
deploy/jenkins-ci/Dockerfile
make/Makefile.build.mk
swagger.json

* Change the version used in TravisCI
* Move to Swagger 0.22.0, because 0.19 has issues with go1.14
* Move to golangci 1.23.8 to stay up to date
* Change texts related to the go version in README.adoc
* Change minimum required go version in Makefile
* Bump versions in deploy/jenkins-ci/Dockerfile
* Updating some outdated texts from CONTRIBUTING.md and PULL_REQUEST_TEMPLATE.md files
Fixes https://github.com/kiali/kiali/issues/2490

Moving to go version 1.14

---

business/checkers/destinationrules/no_dest_checker.go
business/checkers/sidecars/multi_match_checker.go
business/checkers/sidecars/multi_match_checker_test.go
business/checkers/sidecars/workload_selector_checker_test.go
business/checkers/sidecars_checker.go
kubernetes/host.go
models/istio_validation.go
models/workload.go

Adding validation that checks whether multiple sidecars are pointing to the same workloads or not.
Istio says:
> The behavior of the system is undefined if two or more Sidecar resources with a workload selector select the same workload instance.
Test yaml demo:
https://github.com/xeviknal/istio-lab/blob/master/sidecars-examples/multimatch-deployment.yaml

Validation: multiple sidecars pointing to one workload

---

kubernetes/cache/namespaces.go

This is removing some TRACE logs that were writing some data that is really not required.
Backport of https://github.com/kiali/kiali/pull/2531 to v1.12 branch.

Remove unwanted logs (back-port to v1.12)

---

hack/crc-openshift.sh

move to the latest CRC 1.7.0. This starts up a OpenShift 4.3.1 cluster.

[hack] update crc to 1.7

---

graph/api/testdata/test_service_graph.expected
graph/protocol.go
graph/telemetry/common.go

When building the service graph, ensure outgoing metrics reflect only traffic from edges reflected in the final graph.
Pay attention to the edge(s) from reviews to ratings...
Workload Graph:
Before:
After:
This has been wrong for quite a while but the issue can be subtle as edge labeling must be %traffic and there must be multiple workload versions in play.  This fixes at least one other analogous scenario.
Fixes #2483

Fix service graph issue with percent traffic values

---

business/checkers/sidecars/egress_listener_checker_test.go
business/checkers/sidecars/global_checker.go
business/checkers/sidecars/global_checker_test.go
business/checkers/sidecars/multi_match_checker.go
business/checkers/sidecars/multi_match_checker_test.go
business/checkers/sidecars/workload_selector_checker_test.go
business/checkers/sidecars_checker.go
kubernetes/types.go
models/istio_validation.go
tests/data/sidecar_data.go

Sidecars placed in istio namespace will be defaulted to all sidecars in the mesh that don't have any sidecar applied to. 
https://github.com/kiali/kiali/issues/1541

Sidecar in istio ns shouldn't have workloadSelector

---

make/Makefile.cluster.mk

It got broken by the renaming of the Dockerfiles. This seems to fix it.

Fix Makefile cluster-push target

---

business/openshift_oauth.go
config/config.go
config/token.go
handlers/authentication.go
handlers/authentication_test.go
kiali.go
kiali_test.go
ldap/jwt.go
ldap/models.go
operator/deploy/kiali/kiali_cr.yaml
operator/deploy/role.yaml
operator/manifests/kiali-community/1.15.1/kiali.crd.yaml
operator/manifests/kiali-community/1.15.1/kiali.monitoringdashboards.crd.yaml
operator/manifests/kiali-community/1.15.1/kiali.v1.15.1.clusterserviceversion.yaml
operator/manifests/kiali-community/kiali.package.yaml
operator/manifests/kiali-upstream/1.15.1/kiali.crd.yaml
operator/manifests/kiali-upstream/1.15.1/kiali.monitoringdashboards.crd.yaml
operator/manifests/kiali-upstream/1.15.1/kiali.v1.15.1.clusterserviceversion.yaml
operator/manifests/kiali-upstream/kiali.package.yaml
operator/roles/default/kiali-deploy/defaults/main.yml
operator/roles/default/kiali-deploy/tasks/main.yml
operator/roles/default/kiali-remove/tasks/main.yml
operator/roles/v1.0/kiali-deploy/defaults/main.yml
operator/roles/v1.0/kiali-remove/tasks/main.yml
operator/roles/v1.12/kiali-deploy/defaults/main.yml
operator/roles/v1.12/kiali-deploy/tasks/main.yml
operator/roles/v1.12/kiali-remove/tasks/main.yml
server/server_test.go
util/random.go

Bringing to master fixes for bulleting [KIALI-SECURITY-001](https://kiali.io/news/security-bulletins/kiali-security-001/)
---
* [operator] generate random signing key by default
* Strengthen security of Kiali session with some additional validations
---
This is fixing some issues around authentication mechanisms.
For **all** auth strategies: 
* All sessions are invalidated if the signing key is changed
* If subject and/or expiration claims are missing in the Kiali token, the token is rejected and user is treated as not logged in.
* Usage of empty signing key (which provides no security) and *kiali* signing key (which is a well-known key) are now banned. Kiali server won't start and/or will panic if these keys are configured.
For **login** auth strategy:
* All sessions will be invalidated …

Fixes for CVE-2020-1764 and CVE-2020-1762

---

operator/manifests/kiali-community/1.15.1/kiali.v1.15.1.clusterserviceversion.yaml
operator/manifests/kiali-upstream/1.15.1/kiali.v1.15.1.clusterserviceversion.yaml

This is a trivial change to the community/upstream manifests - changes the created date to indicate the time this release was uploaded to the community repo.

[operator] trivial change to manifest created date

---

graph/api/testdata/test_service_graph.expected
graph/protocol.go
graph/telemetry/common.go

When building Service service graph ensure outgoing metrics reflect onl traffic from edges reflected in the final graph.
Backport: #2483

Backport Kiali#2483

---

business/dashboards_test.go
models/dashboards.go
models/dashboards_test.go

Backports https://github.com/kiali/kiali/issues/2485
@pbajjuri20 You should now see the "GRPC Status" option in Metric Settings:

V1.12: Add GRPC status as dashboards available aggregation/filters

---

operator/manifests/kiali-ossm/1.12.6/kiali.v1.12.6.clusterserviceversion.yaml

now that 1.0.12 was released, 1.12.6 replaces it

[operator] 1.0.12 was released, so 1.12.6 now replaces that version

---

operator/manifests/kiali-ossm/1.12.7/kiali.crd.yaml
operator/manifests/kiali-ossm/1.12.7/kiali.monitoringdashboards.crd.yaml
operator/manifests/kiali-ossm/1.12.7/kiali.v1.12.7.clusterserviceversion.yaml
operator/manifests/kiali-ossm/kiali-ossm.package.yaml

- Note, these are only needed if we build 1.12.7 and when/if we do, the
1.12.6 version can be deleted.

Prepare manifests for 1.12.7

---

business/istio_config.go
business/iter8.go
handlers/iter8.go
kubernetes/iter8.go
kubernetes/kubetest/mock.go
make/Makefile.cluster.mk
models/iter8.go
models/iter8_test.go
operator/deploy/role.yaml
operator/manifests/kiali-community/1.16.0/kiali.crd.yaml
operator/manifests/kiali-community/1.16.0/kiali.monitoringdashboards.crd.yaml
operator/manifests/kiali-community/1.16.0/kiali.v1.16.0.clusterserviceversion.yaml
operator/manifests/kiali-community/kiali.package.yaml
operator/manifests/kiali-upstream/1.16.0/kiali.crd.yaml
operator/manifests/kiali-upstream/1.16.0/kiali.monitoringdashboards.crd.yaml
operator/manifests/kiali-upstream/1.16.0/kiali.v1.16.0.clusterserviceversion.yaml
operator/manifests/kiali-upstream/kiali.package.yaml
operator/roles/default/kiali-deploy/templates/kubernetes/role-viewer.yaml
operator/roles/default/kiali-deploy/templates/kubernetes/role.yaml
operator/roles/default/kiali-deploy/templates/openshift/role-viewer.yaml
operator/roles/default/kiali-deploy/templates/openshift/role.yaml
routing/routes.go
swagger.json

More work to consolidate an end-to-end flow for Iter8 extension.
cc @jadeyliu939 
cc @kiali/iter8 
Frontend PR
https://github.com/kiali/kiali-ui/pull/1708
Main work on this PR:
- Avoid to pull Iter8 dependencies
- Create a static model of Iter8 entities to map the CRD. 
- Pros: avoid conflict with dependencies (Iter8 pulls different golang deps versions than Kiali and forces to non desired upgrades).
- Cons: this needs to be maintained on Iter8 changes and some logic (initialization of some default value) should be added.
- Refinements on endpoints and logic.
How to test in minikube:
- Install minikube + bookinfo.
- Install iter8 in minikube:
```
kubectl apply \
-f https://raw.githubusercontent.com/iter8-tools/iter8-analytics/master/install/kubernetes/iter8-analytics.yaml \
-f …
```

Iter8 fixes after UI end-to-end

---

hack/istio/install-sm11.sh

A script that lets you install Service Mesh 1.1 through the use of OLM. Let's you pull pre-release images if you are able to provide authorized credentials to quay.io (see the `-uq` option)

[hack] script to install service mesh 1.1 via OLM

---

Makefile
RELEASING.adoc
deploy/jenkins-ci/Jenkinsfile
deploy/jenkins-ci/Makefile
deploy/jenkins-ci/README.md
deploy/jenkins-ci/jenkins_ref/jobs/kiali-release/config.xml
make/Makefile.cluster.mk
make/Makefile.container.mk

* DockerHub references in main Makefiles are removed
* DockerHub references in Jenkins Pipeline are removed
* DockerHub references in docs are removed
Also, remove some outdated docs.
Fixes kiali/kiali#2615

Stop publishing Kiali to DockerHub

---

graph/api/api_test.go
graph/telemetry/istio/appender/response_time.go
graph/telemetry/istio/istio.go
graph/telemetry/istio/util/util.go
graph/types.go

Fixes https://github.com/kiali/kiali/issues/2622
After discussing with the community member in the issue we decided that the problematic telemetry is "bad" telemetry, likely due to a telemetry V2 corner case with reporting or scraping.  I asked in the istio Telemetry working group and they also said it seemed unintended to have source workload set, but with no other source information.
So, this PR adds a filter for telemetry with that signature.
@israel-hdez This is probably just a visual review of the code as we can't easily replicate the problem.  @mattmahoneyrh, the validation is likely just to ensure that bookinfo or any other traffic remains the same as before the PR (basically show that the new filtering doesn't lose any of the existing traffic we expect).

Protect against bad source telemetry

---

config/token.go
kiali.go

This disables the validation for `LoginToken.SigningKey` when using the `anonymous` Authentication Strategy. Currently, the value is required and cannot equal `"kiali"` which is not relevant when using an `anonymous` strategy.
[Issue](https://github.com/kiali/kiali/issues/2548)([comment](https://github.com/kiali/kiali/issues/2548#issuecomment-610630144))
This change is **not** backwards incompatible. 
TBD

Disable LoginToken.SigningKey validation with Anonymous auth strategy

---

operator/manifests/kiali-ossm/1.12.8/kiali.crd.yaml
operator/manifests/kiali-ossm/1.12.8/kiali.monitoringdashboards.crd.yaml
operator/manifests/kiali-ossm/1.12.8/kiali.v1.12.8.clusterserviceversion.yaml
operator/manifests/kiali-ossm/kiali-ossm.package.yaml

fixes https://github.com/kiali/kiali/issues/2627
These are changes to the OLM metadata required for disconnected use-case to work.
Do not merge this yet. My current testing on OpenShift 4.3 shows that the OLM annotations are not getting created. Need to verify that my testing was correct and if it was we need to figure out why those annotations are missing. I followed this doc: https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/contributors/design-proposals/related-images.md#clusterserviceversion-spec-changes

[operator] additional changes needed to support disconnected use-case

---

hack/crc-openshift.sh

This is useful if k8s api is down and you can't do a `oc debug` (which is now the "sshoc" command).
So there is now two ways you can log into the CRC VM - "sshoc" that uses `oc debug` but if that fails you can probe inside the VM using straight `ssh` - helpful to debug problems with CRC itself.

[hack] provide a second way to log into CRC VM using straight ssh

---

business/istio_config.go
kubernetes/cache/cache.go

This PR adds a method `RefreshNamespace` in `KialiCache` providing a way to clear the cache only in a specific namespace.
When updating istio object, caches from all namespaces will be refreshed. It takes 10s+ to finish this job when the number of namespaces is more than 50.
This PR is to solve this problem as it is not necessary to refresh all caches.

Refresh namespace level cache

---

hack/k8s-minikube.sh

I've recently needed the option of keeping multiple minikube instances alive. I've done so usign the minikube `profile` feature.
This PR allows users can start new clusters with a specific profile. You only need to add either the `mp` or `minikube-profile` param.
`./k8s-minikube.sh up -kdr kvm2 -mp kiali-1287 -v`
Once the minikube is up, you'll see the new profile:
```
$ minikube profile
kiali-1287
```

Allow minikube hack script to set different minikube profile
